### ISSUE TITLE
Design inconsistency in x86 version

### ISSUE THREAD

**Issue by MarcelBrusius** [UnigramDev/Unigram#100]
Edition: x86
OS: Windows 10 Pro, 14393.447
EDIT (30.11): This repro only applies when Unigram was minimized and opened again.
- click on a chat, it opens Fullscreen
- leave chat, still visible on the right of the chat overview
(chatting works in both)

See screenshots
![screenshot 23](https://cloud.githubusercontent.com/assets/22997398/20729155/276b0f5c-b681-11e6-88ee-8924c2740831.png)
![screenshot 24 _li](https://cloud.githubusercontent.com/assets/22997398/20729156/276f70f6-b681-11e6-90a3-e324dded7d73.jpg)

**Comment by FrayxRulez** [comment]
Fixed in 90fe768
