### ISSUE TITLE
Back button/esc to go to "all chats" from filters options

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1000]

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/cc66271a688554fc67b1d7a8841aa4d4686e7983. This will happen by pressing any back button (ESC, mouse back, title bar back, and so on). Do you think it would be better to make this happen only on ESC?

**Comment by MarcAnt01** [comment]
I think the implementation you've done is the best choice👍

**Comment by nahuelwexd** [comment]
@FrayxRulez I think only on ESC

**Comment by MarcAnt01** [comment]
> @FrayxRulez I think only on ESC

How would you like to go to the main screen then?
All the app perfo
