### ISSUE TITLE
Mobile installation issue

### ISSUE THREAD

**Issue by hooddy** [UnigramDev/Unigram#1002]
Current v3 didn't install on mobile from scratch but updating well from latest v2. Did ya drop mobile support?
![wp_ss_20190227_0001](https://user-images.githubusercontent.com/6899176/53487660-3087e680-3a9d-11e9-9081-2c7d767d3c00.png)

**Comment by FrayxRulez** [comment]
Nope

**Comment by MarcAnt01** [comment]
You clearly haven't read the message. SIGN IN with your Microsoft Account
