### ISSUE TITLE
Background sync function doesn't work with VPN connected

### ISSUE THREAD

**Issue by ArianMozafari** [UnigramDev/Unigram#1007]
I have to connect to a VPN since Telegram got blocked in my country recently. While the VPN is connected, Unigram has to be open (active or inactive window, but not minimized) and also be in the same desktop, otherwise, it'll not actively sync until I open the window and it passes the "connecting..." state. A few scenarios to reproduce the bug (all tested with a native Windows 10 1809 L2TP VPN connected):
1. Unigram is not open -> No push notifications received
2. Open Unigram but keep it minimized -> No push notifs & no taskbar badge, the window has to be restored in order to start syncing
3. Open Unigram in Desktop 1, navigate to another desktop (Desktop 2 for instance) and stay there to do your work -> No push notifs -> return to Desktop 1 and go to the app -> Connecting -> Updating -> New messages arrive

**Comment by FrayxRulez** [comment]
That's how UWP works: if you minimize the app (and this happens obiously when you switch desktop as well) the app process gets suspended by the operating system. https://docs.microsoft.com/en-us/windows/uwp/launch-resume/app-lifecycle

**Comment by ArianMozafari** [comment]
There are many UWP apps that work fine without getting suspended as they register a background task. First-party ones such as Groove Music or Skype and third-party ones including Newsflow. 
https://docs.microsoft.com/en-us/windows/uwp/launch-resume/create-and-register-a-background-task
https://docs.microsoft.com/en-us/windows/uwp/launch-resume/support-your-app-with-background-tasks

**Comment by FrayxRulez** [comment]
We are talking about completely different stuff. A background task is intended to be a task: something that gets triggered by the system due to some specific event, gets executed and it dies (example: a push notification arrives, the task runs to show the notifications and it ends)

**Comment by ArianMozafari** [comment]
Checking for new messages (at least in intervals) is considered a task, right? 
"Starting with Windows 10, version 1607, apps can run background tasks within the same process as the app itself. Read more about it in Background activity with the Single Process Model. We won't go into in-process background processing in this article, but how this impacts the app lifecycle is that two new events have been added related to when your app is in the background. They are: EnteredBackground and LeavingBackground.

These events also reflect whether the user can see your app's UI.

Running in the background is the default state that an application is launched, activated, or resumed into. In this state your application UI is not visible yet."
https://blogs.windows.com/buildingapps/2016/06/07/background-activity-with-the-single-process-model/#tMmI7wUuYu5CEeRm.99
