### ISSUE TITLE
Add notification area icon

### ISSUE THREAD

**Issue by electronic-dk** [UnigramDev/Unigram#1009]
It would be nice to have an icon (optionally displaying the number of unread messages) in the notifications area (system tray) as well as minimize to tray option.

Here's how it's implemented in the official telegram client:
![image](https://user-images.githubusercontent.com/2945527/53749358-43912100-3eb8-11e9-9b21-7a9ce0b15bc4.png)

AFAIK a UWP app can achieve this by using a companion win32 component:
https://stefanwick.com/2017/06/24/uwp-app-with-systray-extension/

Although, I'm not sure if it's easy to disable it for the mobile version.

**Comment by MarcAnt01** [comment]
It'd be possible, the things is that it's useless (minimising the app isn't supported by uwp platform and is at all in the case of Unigram) and notifications are received also with app closed and you can see you have received notifications in action centre

**Comment by Xalaxis** [comment]
I'd like to contest that it would be useless.  For me, the definite use case for the tray icon is acting as a "quick launcher" of sorts, for when you want to be the initiator of a conversation.  You are right that in all circumstances where you receive a message it's easy to open Unigram by clicking it, but besides those it's a multiple-key/click operation to reopen it.

**Comment by entdark** [comment]
Notifications counter is shown in opened programs on the task bar. That would be just a duplication.
Example:
https://thewindowsclub-thewindowsclubco.netdna-ssl.com/wp-content/uploads/2016/08/disable-show-badges-on-taskbar.jpg

**Comment by FrayxRulez** [comment]
System tray icon is surely an interesting features and it has its pro and cons. 
To add it I’d need to add to the package a win32 executable to implement this feature...
Pros are:
- the icon (of course)
- a deeper desktop integration (by example having the taskbar icon to blink when a new notification is received)
Cons are:
- Store certification would require up to 5 days for every update (vs the 2 hours we have to wait now)
- I’d have to send multiple packages of the app: one for desktop and another one for the other platforms.

**Comment by FrayxRulez** [comment]
The app here on GitHub already supports the system tray icon by the way.

**Comment by Xalaxis** [comment]
@entdark But if the application is running in the background, it's not displayed in the taskbar.  I don't want to pin it, because the tray icon would take up a lot less screen space.  (Also, would the pinned icon update in the same way?)

**Comment by MarcAnt01** [comment]
What 

> @entdark But if the application is running in the background, it's not displayed in the taskbar.  I don't want to pin it, because the tray icon would take up a lot less screen space.  (Also, would the pinned icon update in the same way?)

What do you mean?

**Comment by FrayxRulez** [comment]
> Also, would the pinned icon update in the same way?

No, it won't

**Comment by Xalaxis** [comment]
> The app here on GitHub already supports the system tray icon by the way.

As in the direct download one from https://unigramdev.github.io/ ?

**Comment by MarcAnt01** [comment]
> The app here on GitHub already supports the system tray icon by the way.
> 
> As in the direct download one from https://unigramdev.github.io/ ?

The app there is just the package redistributed to the Store

**Comment by Xalaxis** [comment]
> > @entdark But if the application is running in the background, it's not displayed in the taskbar.  I don't want to pin it, because the tray icon would take up a lot less screen space.  (Also, would the pinned icon update in the same way?)
> 
> What do you mean?

As in, would a pinned tray icon of a closed app still show the 'unread bubble'.  I think @FrayxRulez has already answered.

**Comment by FrayxRulez** [comment]
> As in the direct download one from https://unigramdev.github.io/ ?

No, you have to compile it by yourself. The `io` page is a mirror from the Store (this way the app is signed by Microsoft and I don't have to buy a certificate to do this.)

**Comment by Xalaxis** [comment]
> System tray icon is surely an interesting features and it has its pro and cons.
> To add it I’d need to add to the package a win32 executable to implement this feature...
> Pros are:
> 
> * the icon (of course)
> * a deeper desktop integration (by example having the taskbar icon to blink when a new notification is received)
>   Cons are:
> * Store certification would require up to 5 days for every update (vs the 2 hours we have to wait now)
> * I’d have to send multiple packages of the app: one for desktop and another one for the other platforms.

I think the pros are well worth the cons, although the store certification requirement is a real pain.  One option would perhaps be to have two different packages, one with the tray icon for desktop (with the delay) and another one without for mobile (without the delay).  Another combination could be having two separate packages for the desktop version, one with faster updates and no tray icon, the other with tray icon and slower updates.  Neither are ideal however.  Microsoft should have UWP support for tray icons in some manner.

**Comment by Xalaxis** [comment]
Perhaps we can reopen this issue for consideration?

**Comment by MarcAnt01** [comment]
> Perhaps we can reopen this issue for consideration?

The feature has been added in the code, I don't think reopening is something necessary.

**Comment by Xalaxis** [comment]
Would it be okay if I made a separate issue to keep track of progress towards inclusion in the distributed builds?

**Comment by MarcAnt01** [comment]
> Would it be okay if I made a separate issue to keep track of progress towards inclusion in the distributed builds?

Better to keep the discussion here

**Comment by MarcAnt01** [comment]
lol

**Comment by entdark** [comment]
> @entdark But if the application is running in the background, it's not displayed in the taskbar. I don't want to pin it, because the tray icon would take up a lot less screen space. (Also, would the pinned icon update in the same way?)

So the only benefit of sacrificing the releasing time is to have the tray icon for the state when the app is closed?

Are you sure the notifications counter will be presented there when the app is closed? Because Skype has an option to stay in tray but displays no counter there at all (I disabled the tray icon there as well since it's again a duplicate an a waste of space).

IMO it's not worth it. Just pin the app if you need that behavior now.
I personally don't think tray icon is worth the sacrifice of the release time because it's just a waste of space and is necessarily for minor amount of people while the rest either pin or have the app never closed.

I'd suggest to either release extra builds with extra features like that separately by the developers themself like (for example, v1.0 + v1.0e) here on GitHub releases section or compile the app yourself with the needed features because as I think the feature is needed for the minority.

**Comment by MarcAnt01** [comment]
> @entdark But if the application is running in the background, it's not displayed in the taskbar. I don't want to pin it, because the tray icon would take up a lot less screen space. (Also, would the pinned icon update in the same way?)
> 
> So the only benefit of sacrificing the releasing time is to have the tray icon for the state when the app is closed?
> Are you sure the notifications counter will be presented there when the app is closed? Because Skype has an option to stay in tray but displays no counter there at all (I disabled the tray icon there as well since it's again a duplicate an a waste of space).
> IMO it's not worth it. Just pin the app if you need that behavior now.
> I personally don't think tray icon is worth the sacrifice of the release time because it's just a waste of space and is necessarily for minor amount of people while the rest either pin or have the app never closed.
> I'd suggest to either release extra builds with extra features like that separately by the developers themself like (for example, v1.0 + v1.0e) here on GitHub releases section or compile the app yourself with the needed features because as I think the feature is needed for the minority.

The bigger benefit would be having the light up icon when receiving notifications tbh

**Comment by entdark** [comment]
> > @entdark But if the application is running in the background, it's not displayed in the taskbar. I don't want to pin it, because the tray icon would take up a lot less screen space. (Also, would the pinned icon update in the same way?)
> > So the only benefit of sacrificing the releasing time is to have the tray icon for the state when the app is closed?
> > Are you sure the notifications counter will be presented there when the app is closed? Because Skype has an option to stay in tray but displays no counter there at all (I disabled the tray icon there as well since it's again a duplicate an a waste of space).
> > IMO it's not worth it. Just pin the app if you need that behavior now.
> > I personally don't think tray icon is worth the sacrifice of the release time because it's just a waste of space and is necessarily for minor amount of people while the rest either pin or have the app never closed.
> > I'd suggest to either release extra builds with extra features like that separately by the developers themself like (for example, v1.0 + v1.0e) here on GitHub releases section or compile the app yourself with the needed features because as I think the feature is needed for the minority.
> 
> The bigger benefit would be having the light up icon when receiving notifications tbh

True.

But again, I wouldn't use it since I have the taskbar auto-hiding and that would just mess up my UX and I always check the notifications (the app has any counter number or not) myself periodically, but this time I think I am the minority.

**Comment by entdark** [comment]
Consider to make it as separate builds I suppose.

**Comment by MarcAnt01** [comment]
> @entdark But if the application is running in the background, it's not displayed in the taskbar. I don't want to pin it, because the tray icon would take up a lot less screen space. (Also, would the pinned icon update in the same way?)
> So the only benefit of sacrificing the releasing time is to have the tray icon for the state when the app is closed?
> Are you sure the notifications counter will be presented there when the app is closed? Because Skype has an option to stay in tray but displays no counter there at all (I disabled the tray icon there as well since it's again a duplicate an a waste of space).
> IMO it's not worth it. Just pin the app if you need that behavior now.
> I personally don't think tray icon is worth the sacrifice of the release time because it's just a waste of space and is necessarily for minor amount of people while the rest either pin or have the app never closed.
> I'd suggest to either release extra builds with extra features like that separately by the developers themself like (for example, v1.0 + v1.0e) here on GitHub releases section or compile the app yourself with the needed features because as I think the feature is needed for the minority.
> 
> The bigger benefit would be having the light up icon when receiving notifications tbh
> 
> True.
> But again, I wouldn't use it since I have the taskbar auto-hiding and that would just mess up my UX and I always check the notifications (the app has any counter number or not) myself periodically, but this time I think I am the minority.

Yes, most people on desktop will find it convenient, mostly because tags and quotes in messages aren't marked in the icon itself

**Comment by entdark** [comment]
> Yes, most people on desktop will find it convenient, mostly because tags and quotes in messages aren't marked in the icon itself
Do you mean to have different notifications icon/colour/whatever to different kind of notification?

**Comment by MarcAnt01** [comment]
No, just [that](https://t.me/c/1060755082/232014)

**Comment by entdark** [comment]
> No, just [that](https://t.me/c/1060755082/232014)

"Unfortunately, you can't access the message. You are not a member of the chat where it was posted."

**Comment by MarcAnt01** [comment]
Ah, forgot the group is private. Join the group from Readme or I will send you the photo if you prefer

**Comment by entdark** [comment]
Ok, got it. I already replied to that.
I thought you were talking about the tray icon the last quoting.

**Comment by FrayxRulez** [comment]
If you want you can join desktop bridge beta by using t.me/UnigramBot?start=beta

**Comment by MarcAnt01** [comment]
Present in latest release!

**Comment by digiredact** [comment]
> If you want you can join desktop bridge beta by using https://t.me/UnigramBot?start=beta

Hi, how can I Join the Beta program? The Bot doesn't do anything when i click the link you reported or when I select /Start button
![Cattura](https://user-images.githubusercontent.com/42168471/62206442-1e82da80-b392-11e9-9b00-934076d8b6a5.PNG)

**Comment by MarcAnt01** [comment]
Hi, now Unigram with Desktop Bridge is live for everyone

**Comment by digiredact** [comment]
> Hi, now Unigram with Desktop Bridge is live for everyone

Is this the Beta? Great but, where can I find the download link?

**Comment by MarcAnt01** [comment]
> Hi, now Unigram with Desktop Bridge is live for everyone
> 
> Is this the Beta? Great but, where can I find the download link?

Nope, it's in the stable release, just download from the store

**Comment by digiredact** [comment]
> > Hi, now Unigram with Desktop Bridge is live for everyone
> > Is this the Beta? Great but, where can I find the download link?
> 
> Nope, it's in the stable release, just download from the store

The Store version is Stable or Beta?

**Comment by MarcAnt01** [comment]
3.9 is stable 3.10 beta

**Comment by digiredact** [comment]
> 3.9 is stable 3.10 beta

Great, where can I download 3.10 version?

**Comment by MarcAnt01** [comment]
> 3.9 is stable 3.10 beta
> 
> Great, where can I download 3.10 version?

I think the rollout is partial (I am not sure since I am not the developer), once downloaded, looking for updates manually should force the download of that version
