### ISSUE TITLE
Unread chats: chat is in list twice 

### ISSUE THREAD

**Issue by ArmeF97** [UnigramDev/Unigram#1013]
Channel "WA Tensei"...

**Comment by ArmeF97** [comment]
![immagine](https://user-images.githubusercontent.com/6240983/54143507-45179780-442a-11e9-8510-357c27c186be.png)

**Comment by FrayxRulez** [comment]
Does this still happens?

**Comment by ArmeF97** [comment]
I don't think it's still happening. 

For now, I'll close this. If this happens again, I will re-open.

Thanks!
