### ISSUE TITLE
Double tap to reply outside of the message bubble

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1014]
Would be handy to double tap also on right or left area next to the message as happens on Telegram Desktop

**Comment by FrayxRulez** [comment]
Recently fixed

**Comment by rabiet** [comment]
Would it be possible to make it both ON the message bubble AND next to it? Double-clicking next to the messages feels odd and kind of unintuitive

**Comment by MarcAnt01** [comment]
This is the same implementation as TDesktop, you just have to get used to it🙂

**Comment by rabiet** [comment]
I feel like small changes like this that don't alter the complete behaviour of the app but make it more accessible should be within the reach of projects like this. After all, this is Unigram, not an exact TDesktop clone.

**Comment by MarcAnt01** [comment]
Yes, but as written in [contributing guidelines](https://github.com/UnigramDev/Unigram/blob/develop/CONTRIBUTING.md) Unigram aims to follow official client guidelines.
Apart from that, double tapping there is better, because it doesn't interfere with replies or photos and it's not going to be changed. Yours is more a personal taste.

**Comment by FrayxRulez** [comment]
The problem is that the only method that allows me to determine which mouse button you used to double click doesn't catch interactions done on child elements, so there's no way to
