### ISSUE TITLE
Wrong scrolling logic for instant view with more pictures

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1016]
When there is more than a picture and I'm scrolling down, it moves among the pictures instead of scrolling down the page. On touchpads, this action should be done with side swipe while with mouse should be disable, not to cause problems with scrolling.

**Comment by MarcAnt01** [comment]
Seems it happens when videos are in that place, as well

**Comment by FrayxRulez** [comment]
This is a system behavior and it can't be prevented
