### ISSUE TITLE
Pictures with too wide of an aspect ratio will not be sent

### ISSUE THREAD

**Issue by rabiet** [UnigramDev/Unigram#1019]
### Issue
If a picture has an aspect ratio that is too wide the picture will not be sent and a little lightning bolt appears in the lower right corner.

### Steps to reproduce
1. Open snipping tool
2. Select an extremely wide, but short in height area
3. Paste the image into Unigram
4. Send
5. Error will appear

This also happens with wide images that are already saved somewhere. Usage of snipping tool is not necessary.

![image](https://user-images.githubusercontent.com/15967138/54589178-3aaa5e80-4a25-11e9-8578-684dbfccf56f.png)

![image](https://user-images.githubusercontent.com/15967138/54589192-4564f380-4a25-11e9-9f5e-086aaf8b39b5.png)
### Possible fix
I believe this problem exists because of telegram not allowing to send those wide pictures. Telegram Desktop sends these images as files whenever they are too wide. It might be a good idea to send them as files whenever this occurs.

**Comment by HimbeersaftLP** [comment]
Or ask the user whether they want to send as file, add padding or cancel?

**Comment by FrayxRulez** [comment]
Adding a padding isn’t a good idea to me... Better to preserve the original file

**Comment by HimbeersaftLP** [comment]
Indeed it is, but that doesn't have an in-chat preview. (it would be nice to add one for images sent as file, though, however that isn't in the original app)

**Comment by FrayxRulez** [comment]
This is fixed now
