### ISSUE TITLE
app cant run

### ISSUE THREAD

**Issue by my2008** [UnigramDev/Unigram#102]
I install unigram but run only first time .plz help
My phone 640 xl
Tnx and so sorry . my english is bad 😉

**Comment by kesavaprasadarul** [comment]
@my2008 Please be more specific about the problem you're facing.
Did you install all dependencies?

**Comment by my2008** [comment]
No.I dont install dependencies.
I install unigram.and run it.unigram run ok and i can register phone number .i can chat too.
I quit the application . when I run the program again،not run😔

**Comment by my2008** [comment]
Im still waiting

**Comment by ikarago** [comment]
Tried running the new build? https://rink.hockeyapp.net/apps/7d36a4260af54125bbf6db407911ed3b/app_versions/35

**Comment by my2008** [comment]
Crash again and not run

**Comment by kesavaprasadarul** [comment]
@my2008 Please re-install all dependencies and try again.

**Comment by my2008** [comment]
all dependencies  link plz

**Comment by my2008** [comment]
@kesavaprasadarul  all dependencies link plz

**Comment by Marocco2** [comment]
@my2008 https://www.dropbox.com/sh/as1ua9ku7qtqro8/AADiKCGl3YZZCA1p5n-6BRwia?dl=0

**Comment by my2008** [comment]
Thats crt link.i want dependencies link

**Comment by ikarago** [comment]
@my2008 Are you running the Anniversary Update (RS1) on your device? This update is required in order to run Unigram.

**Comment by my2008** [comment]
This version not runing first time too.😑
