### ISSUE TITLE
Ctrl + 1/2/3/4/5 shortcuts work also for non-pinned chats

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1020]
If there aren't any pinned chats, shortcuts work the same, because they are thought to open the first five chats and don't work depending on the state.

How to reproduce:
-Pin 4 chats;
-Press ctrl + 5

It will open the fifth chat, even if it shouldn't.
The correct behaviour is present in Telegram Desktop

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/81c2ebe3c7ffdd63864361a6f1789efb38f80d36
