### ISSUE TITLE
Ctrl + F to work on other searches apart from messages one

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1022]
Would be great, if it was supported in:
- [x] Settings search;
- [x] Restricted people search;
- [x] Group members/channel subscribers search

**Comment by xperiandri** [comment]
Also, it does not work in chats opened with Shift key in a separate windows

**Comment by MarcAnt01** [comment]
> Also, it does not work in chats opened with Shift key in a separate windows

Can you open a separated ticket for that?
