### ISSUE TITLE
Pin chats to start

### ISSUE THREAD

**Issue by federico-terzi** [UnigramDev/Unigram#1023]
Hi,
I'm unable to add a chat to the home screen, is this an expected behaviour?

Version:  3.1.2112

![image](https://user-images.githubusercontent.com/20475953/54919016-f7a62a80-4eff-11e9-9e65-8454e28d0067.png)

**Comment by morenj96** [comment]
@federico-terzi Who can add?

**Comment by MarcAnt01** [comment]
@federico-terzi Hello, this feature hasn't been implemented yet

**Comment by federico-terzi** [comment]
All right, thank you very much!
Keep on the great work, your app is so good

**Comment by FrayxRulez** [comment]
Considering that tiles are no more I guess that this issue can be closed...
