### ISSUE TITLE
Search messages by person icon in search bar has disappeared

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1025]
Bug probably caused by https://github.com/UnigramDev/Unigram/commit/5d0ea0ac4d9feed5f8e61d6a68404b4743f059e8

**Comment by FrayxRulez** [comment]
![immagine](https://user-images.githubusercontent.com/8152849/54944419-c1829e00-4f33-11e9-9821-2f670b77d02a.png)
Can't reproduce

**Comment by MarcAnt01** [comment]
I think you haven't read my title "Search messages by person ICON IN SEARCH BAR has disappeared".
Anyway, will attach a screenshot of the bug
![image](https://user-images.githubusercontent.com/43090263/54944637-3eae1300-4f34-11e9-94ca-a090cafe0cee.png)

**Comment by FrayxRulez** [comment]
Dark theme bug.

**Comment by MarcAnt01** [comment]
Before the mentioned commit was OK btw

**Comment by MarcAnt01** [comment]
As it is a bug of the dark theme, here's another one with search bar unfocused
![image](https://user-images.githubusercontent.com/43090263/54944803-99476f00-4f34-11e9-8cf0-3ef56733d29b.png)

**Comment by FrayxRulez** [comment]
First one is fixed at https://github.com/UnigramDev/Unigram/commit/0f52f75885f02f41d86dbd25f098eccf741ac475, no idea about how to fix the second one

**Comment by MarcAnt01** [comment]
OK, should I close this one and open a new ticket to keep track of it?

**Comment by FrayxRulez** [comment]
Fixed
