### ISSUE TITLE
Add option to disable big emojis

### ISSUE THREAD

**Issue by rabiet** [UnigramDev/Unigram#1026]
When sending a message that contains only an emoji this gets displayed as a bigger message.
This was introduced in c92b71d74a7c2d6814ca8a979219eba036ccccb8 and is in line with how official Telegram apps do it, however, it is disliked by a lot of people. 

I think there should be an option to turn this off.

**Comment by MarcAnt01** [comment]
Fela already told in the Telegram group that he does like big emojis and the other official apps don't have an option to disable it, so this is something that isn't going to be considered, I'm sorry

**Comment by FrayxRulez** [comment]
The more the options the more confusing and complex the app becomes, especially when we talk about an option like this one
