### ISSUE TITLE
Muted chats shown as non muted

### ISSUE THREAD

**Issue by Vas0sky** [UnigramDev/Unigram#1028]
In my telegram settings all groups are silenced by default (ie. they don't show notification, except for mentions). In telegram or tg destkop, those groups are shown with the gray unread badge and the muted symbol, while in unigram only groups joined after installing unigram show this, the other groups have the blue unread badge and don't show the muted icon, but they still only notify me when mentioned. It's a bit annoying, especially when trying to search for an old unread message because I have to open every chat and every group in my list.

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/c9f709d1e1d2495c0ad720be3bd7f40a747cd1a9
