### ISSUE TITLE
Clicking on a notification while viewing any media in fullscreen doesn't close the image

### ISSUE THREAD

**Issue by Vas0sky** [UnigramDev/Unigram#1029]
If I'm viewing an image in fullscreen and I click a message notification (to go directly to that chat) the image stays on the screen (without blackened borders) and I cannot interact with unigram until I press ESC to exit the fullscreen view.

**Comment by MarcAnt01** [comment]
New send file ui when triggered by Windows Share causes the same bug (gallery has to be left open to reproduce)

**Comment by MarcAnt01** [comment]
It does now 🕺
