### ISSUE TITLE
Slide

### ISSUE THREAD

**Issue by deltapir** [UnigramDev/Unigram#103]
Use the slide from the edge of the screen when in a chat page. Slide to the right on the left edge: an hamburger-like menu appear for easily selecting different chat; slide to the left on the right edge: The profile menu of the chat appears (the one the we see now tapping on the title of the chat).

In this way it is much easier and fast using the app without tapping every time the back button.

**Comment by ikarago** [comment]
This is a pretty good idea! :D We're currently focusing first on bringing the core functions to the app though, so I'll stall it in the idea-cabin for later. :)

**Comment by deltapir** [comment]
😉😉 good luck!
