### ISSUE TITLE
Pressing ESC while searching issues

### ISSUE THREAD

**Issue by Vas0sky** [UnigramDev/Unigram#1030]
While viewing a chat, if I press the search button and then press ESC, unigram exits the current chat without exiting the search mode until I press ESC again or I click anywhere (I can still type in the box and click a search result). The issue is with the hamburger menu (3 lines menu) that appears when I press ESC the first time.

**Comment by MarcAnt01** [comment]
Are you talking about chat search or messages search?

**Comment by Vas0sky** [comment]
Chat search

**Comment by FrayxRulez** [comment]
I can't reproduce/understand this :/ any further info?

**Comment by MarcAnt01** [comment]
I think it's a duplicate of the issue of right part going back before left one when going back in chat search, but I cannot find the other issue lmao

**Comment by Vas0sky** [comment]
I'll get a short video of the issue tomorrow and send it over telegram channel.

**Comment by MattiaBLX** [comment]
@Vas0sky Lol?
