### ISSUE TITLE
[Feature Request] Writing without a chat open, should just trigger the "search" button and write there

### ISSUE THREAD

**Issue by telegram-user** [UnigramDev/Unigram#1033]
### Steps
1. Open Unigram, open a chat
2. Close the chat
3. Press the letter "A"

#### What should happen
It starts searching chats by letter "A"
#### What happens
Nothing

**Comment by MattiaBLX** [comment]
@telegram-user It's not a bug but a missing feature.

**Comment by telegram-user** [comment]
It think I wrote "Feature Request" on title

**Comment by MattiaBLX** [comment]
@telegram-user Oh yes sorry, I didn't see that.

**Comment by MarcAnt01** [comment]
Chat search is different from Telegram Desktop one, since search field isn't triggered when app is launched, so this isn't possible at the moemnt.

**Comment by telegram-user** [comment]
It's impossible? There isn't any way to force a focus? Or to implement this?

**Comment by MarcAnt01** [comment]
Of course there would be, but at the moment that area contains filters. This would also kill chat bubbles and the all chat search, as it's been tought (similar to mobile clients)

**Comment by telegram-user** [comment]
So for now, it's better to not touch it, ok
