### ISSUE TITLE
All notifications show up twice

### ISSUE THREAD

**Issue by jmml97** [UnigramDev/Unigram#1035]
Notifications for all messages show up a second time when I set Unigram as the active app. The first time they appear they have a "0" alongside the app name, the second time, my full name appears there instead.

![{D3A12912-559A-4117-B313-B416653B87E6} png](https://user-images.githubusercontent.com/2082283/55150873-5ad8cc80-514d-11e9-9f81-2d308b5ce7c7.jpg)

![paste_(7891dd)](https://user-images.githubusercontent.com/2082283/55150895-64facb00-514d-11e9-81ca-3ed9bd6d31ec.jpg)

Unigram 3.3.2146
Windows 10 build 18362.1

**Comment by morenj96** [comment]
@jmml97 System notifications are different from the app notifications
"0" is sign of system notification
"[your full name]" is sign of the app notification
You can turned off in-app notifications in Unigram Settings

**Comment by jmml97** [comment]
Where exactly? Can't seem to find it. Tried disabling all options in the settings regarding notifications but I still get them twice.

**Comment by morenj96** [comment]
@jmml97

**Comment by FrayxRulez** [comment]
I won't disable in-app notifications, especially on PC, as normal notifications are much slower to come. I'd rather wait for a fix (that I hope to realize in next update :))

**Comment by Sc0tTyXL** [comment]
I have the same issue, any eta on it being resolved?

**Comment by MarcAnt01** [comment]
> I have the same issue, any eta on it being resolved?

Soon™

**Comment by FrayxRulez** [comment]
I have no time at the moment to work on Unigram. I hope to be able to get back at it in later August

**Comment by MarcAnt01** [comment]
> I have no time at the moment to work on Unigram. I hope to be able to get back at it in later August

Can you consider removing push notifications before you pause development?

**Comment by FrayxRulez** [comment]
It's not a pause that I chosen to do

**Comment by MarcAnt01** [comment]
> It's not a planned pause on Unigram

No problem, take your time

**Comment by slackerstacker** [comment]
Hello, 

I have this issue on Windows 10 Phone. If I need to open a new issue for that please let me know. 

I'm seeing this issue has been open for a while. Is there any chance of a fix coming up?

The Unigram app is so much more better than the standard telegram one and with Whatsapp pulling the plug from their windows version it would be nice if we could have Unigram working properly. Getting all messages twice gets annoying really quickly if you use it for your daily chat app. 

Additional info: Using a Lumia 950. Notifications show when messages arive. Upon opening the app all notifications show up again. I have 2 friends who also have a Lumia 950 and they have the same issue. Disabling in-app notifications does not solve the issue, not sure if that's a bug too?
