### ISSUE TITLE
record voice/video message button accessibility

### ISSUE THREAD

**Issue by beqabeqa473** [UnigramDev/Unigram#1037]
hello.

first of all, thank you for making unigram better in terms of accessibility.

secondly, please make button to record voice/video messages accessible for screenreaders and something like cancel message with slide to cancel to make it possible to cancel recording message.

**Comment by mikefromua** [comment]
and fix problems with voice/video recording. I think it happened after [https://github.com/UnigramDev/Unigram/commit/041096b1f413b2b45abf6728cdd8c9628263727b?diff=split](this code changes)

**Comment by beqabeqa473** [comment]
hello.

no, it is not pressable with keyboard

On 3/31/19, mikefromua <notifications@github.com> wrote:
> and fix problems with voice/video recording. I think it happened after
> [https://github.com/UnigramDev/Unigram/commit/041096b1f413b2b45abf6728cdd8c9628263727b?diff=split](this
> code changes)
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/UnigramDev/Unigram/issues/1037#issuecomment-478327934


-- 
with best regards beqa

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/d65fd0dfc437041ce1d17efc4b6588ee5c71025d
