### ISSUE TITLE
Better Accessibility in contact list

### ISSUE THREAD

**Issue by MarcoZehe** [UnigramDev/Unigram#1039]
First of all, a big thank you for making Unigram more accessible!

I found a few problems in the contact list:

1. Each message item has a very long description, starting with user ID equals ..., and going on to speak meta data as if this was some JSON format string or the like. These labels on the individual list items should say something like "first name last name, last seen on ...", basically take the texts that are children of each list item and put them onto the list item label concatenated so Narrator and other screen readers speak comprehensible information.
2. Make arrows up and down work to walk through the list of contacts. Right now, they don't do anything, stick to the first contact in the list.
3. Make sorting by either name or last seen accessible. The button for that cannot currently be found with Narrator.

Thank you!

**Comment by MarcAnt01** [comment]
All the required changes are available in the latest release!
