### ISSUE TITLE
User should see only relevant controls in Group chat flyout

### ISSUE THREAD

**Issue by danielkornev** [UnigramDev/Unigram#104]
As a usual (non-administrator) member of a group, I want to see only those controls that I can use in the Group Management flyout.

Acceptance Criteria:

1. No control elements like "Manage Administrators", "Convert to Supergroup", or "Clear History" should be visible
2. I should not be able to delete the group and exit it
3. I should be able to see Shared Media
4. I should be able to Leave the Group if I want (instead of deleting & exiting it)

![image](https://cloud.githubusercontent.com/assets/5264043/20981771/feadf240-bcc6-11e6-98de-a7e36bfde5c7.png)

**Comment by FrayxRulez** [comment]
@danielkornev Actually the page is not implemented.

**Comment by danielkornev** [comment]
Disagree: it shows group's name and metadata. It's already useful (a little bit, but).

**Comment by danielkornev** [comment]
Still not fixed in the latest build (as of today)

**Comment by danielkornev** [comment]
![image](https://cloud.githubusercontent.com/assets/5264043/22863840/2fa4f018-f158-11e6-91ef-e6cb59ecf49d.png)

1 - I'd recommend to transform these icons into tabs with names (like in the main chat)
2 - I'd recommend to remove those horizontal lines, they make the whole UI too messy

**Comment by danielkornev** [comment]
![image](https://cloud.githubusercontent.com/assets/5264043/22863853/6bb4cc7c-f158-11e6-9da4-dbe1803e5366.png)

those icons (settings & group list) ask to be tabs with names even more in compact/phone UI context.

**Comment by kesavaprasadarul** [comment]
@danielkornev We think we'll be re-working on the page entirely. That's why we haven't made any progress during the development. Stay Tuned! :)

**Comment by larsschellhas** [comment]
I think we are finished with this issue, aren´t we? :)

**Comment by FrayxRulez** [comment]
@larsschellhas Yep
