### ISSUE TITLE
help in building unigram

### ISSUE THREAD

**Issue by beqabeqa473** [UnigramDev/Unigram#1040]
hello.

i am trying to build unigram but i have some issues.

2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1879,5): warning : The referenced project '..\Unigram.Infrastructure\Unigram.Infrastructure.csproj' does not exist.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2377,5): error MSB3774: Could not find SDK "Telegram.Td.UWP, Version=1.0".
========== Build: 0 succeeded, 2 failed, 7 up-to-date, 0 skipped ==========

**Comment by MarcAnt01** [comment]
Hello, at the moment building Unigram isn't easy, you'll get tones of errors because some components used by Unigram are not open source

**Comment by beqabeqa473** [comment]
ok, is it possible to get them in precompiled form?

On 4/2/19, Filippo Fedeli <notifications@github.com> wrote:
> Hello, at the moment building Unigram isn't easy, you'll get tones of errors
> because some components used by Unigram are not open source
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/UnigramDev/Unigram/issues/1040#issuecomment-478975228


-- 
with best regards beqa

**Comment by FrayxRulez** [comment]
Please reach me out on Telegram: t.me/frayxrulez

**Comment by kolomenkin** [comment]
Hi, @FrayxRulez !
Your link to telegram account does not work any more.
I have the same problem. How can I find Telegram.Td.UWP and maybe other necessary dependencies?

**Comment by makisukurisu** [comment]
Actually it does work, GitHub just thinks it's referring to an issue. Try to search for frayxrulez on Telegram.

Also - take a look at: https://github.com/UnigramDev/Unigram/blob/develop/Documentation/Build-instructions.md
*May be outdated
