### ISSUE TITLE
New messages search bar for desktop doesn't show the number of the results

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1042]

**Comment by FrayxRulez** [comment]
Intended, won't fix

**Comment by MarcAnt01** [comment]
What is the point of not showing them? All the client do have that

**Comment by FrayxRulez** [comment]
macOS client doesn't. There's no space to display it.

**Comment by MarcAnt01** [comment]
There's still some place next to this icons
![image](https://user-images.githubusercontent.com/43090263/55503884-de178800-564f-11e9-8744-995e4c9fc8da.png)
I have a 13-inches laptop and I don't feel that the search bar itself is too small to display the content I'm looking for

**Comment by abh-oss01** [comment]
agreed, pls add the number of words, there's a lotta space
