### ISSUE TITLE
UI Bug: displaying old number after changing phone number

### ISSUE THREAD

**Issue by entdark** [UnigramDev/Unigram#1044]
On the left menu panel it displays name and the phone number on top.
If to go to settings to change phone number, and have it changed successfully the old phone number is still displayed in the left menu panel.
Restarting the application fixes the issue and the new phone number gets displayed afterward.

Expectation: displaying new phone number on the left panel menu after changing the phone number.
Reality: displaying the old phone number on the left panel menu after changing the phone number. Possibly it also displays the old phone number in Settings->Phone as well, but I did not go there to check it out.

To reproduce, I followed the following official steps to change the phone number:
1. Clicked the "hamburger" icon to display the left menu panel.
2. Clicked "Settings".
3. Clicked "Phone" on top of the left panel.
4. Clicked "Change number" in the bottom.
5. Chose the country code and typed the new phone number.
6. Clicked "OK".
7. Typed the verification code that I received by SMS and the phone number has been changed successfully.
8. Clicked the "hamburger" icon again to verify the phone number has been changed but it displayed the old phone number.
9. Restarted the application and it displayed the correct new phone number.

Thanks in advance.

P.S.: sorry if duplicate - I could not find anything related.

**Comment by FrayxRulez** [comment]
This should be fixed now
