### ISSUE TITLE
Can't record voice message

### ISSUE THREAD

**Issue by noquierouser** [UnigramDev/Unigram#1045]
In any chat pressing the microphone button at the bottom doesn't start recording, neither does Ctrl+R hotkey. Microphone permissions are allowed app and system-wide.

- Windows 10 1809, build 17763.379
- Unigram 3.4.2189, from Microsoft Store
- USB Microphone Samson C01U Pro

**Comment by MarcAnt01** [comment]
Sounds as a driver issue, are you able to record audio with other apps?

**Comment by noquierouser** [comment]
Yes, I can record with Sound Recorder app and Telegram Desktop app too.

**Comment by noquierouser** [comment]
I forgot to mention if you need any logfile or is there anything I can do to help to triage this issue. A recording or anything.

**Comment by pbsinnett** [comment]
Hello,

I'm seeing this issue also with the latest version of the store app. I'm using NVDA 2019.1 as my screen reader, and can't press the button or use the keyboard shortcuts. When I pressed it for the first time, it did ask for my microphone permission. I just reset the app and tried the shortcut, and it also asked for my microphone permission. I'm not sure what may be going on.

**Comment by noquierouser** [comment]
What @pbsinnett mentions is exactly what happened to me, the only difference is that I'm not using NVDA or any other screen reader technology.

**Comment by FrayxRulez** [comment]
Do you have a webcam?

**Comment by noquierouser** [comment]
Thanks for solving the issue, @FrayxRulez. Yes, I have no webcam connected to my computer and just tested the latest update, it works fantastically! :D

**Comment by tomeckit** [comment]
The problem still exist. I have Behringer 1820 audio interface and few other soundcards.
1. Recording on Behringer doesn't work and i set samplerate in mmsys.cpl to 44.1kHz and 48 kHz. In other apps it works.
2. On the same Behringer card calling works perfectly.
3. Recording voice message from Realtek Stereomix works too.
