### ISSUE TITLE
proxy fails if network is set to private? 

### ISSUE THREAD

**Issue by hyakki-** [UnigramDev/Unigram#1046]
Windows 10 (1809 Clean install), if network is set to Private 
(settings -> network & internet -> Ethernet -> Click Network and set Network Profile to "Private") 

Now the proxy that was setup in unigram no longer works just says  connecting/unavailable , if I set it back to "Public" then it connects fine, (note the proxy is hosted on another pc in my house, so its not using localhost, but it does use a LAN ip, not sure if its related.)

I have tried to disable the windows firewall for all profiles public , private, domain..etc and it still has the issue.

Debuging using 
"CheckNetIsolation.exe DEBUG -n=38833FF26BA1D.UnigramPreview_g9c9v27vpyspw"
showed this

PrivateNetworkClientServer    Missing, maybe intended
x.x.x.x x.x.x.x (lan ip)

reading around I think you need to declare the privateNetworkClientServer permission. (I don't think it's possible for end users to set it), I think this declaration fixes the localhost / loopback bug too.

> https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/appxmanifestschema/element-capability
> 
> PrivateNetworkClientServer | On Windows, this provides access to a home or work network – the app  can send information to or from your computer and other computers on  the same network. On Windows Phone, provides the same access as internetClient or internetClientServer.
> -

**Comment by FrayxRulez** [comment]
I will try to add the capability in the next Store update, let me know if it works

**Comment by hyakki-** [comment]
Thanks for the fast fix, 
I just tested with the latest update and it's working correctly when the network is in private mode.
