### ISSUE TITLE
proxy connection with multiple account

### ISSUE THREAD

**Issue by Hashtag-Plus** [UnigramDev/Unigram#1047]

**Comment by MattiaBLX** [comment]
Where's the problem

**Comment by Hashtag-Plus** [comment]
I'm using unigram for two accounts and the first account can connect MTProto proxy but second account cant connect that proxy.

**Comment by Hashtag-Plus** [comment]
proxy is :
https://t.me/proxy?server=ir.tgproxy.today&port=8080&secret=ddfb175d6d7f820cdc73ab11edbdcdbd74
first account working fine but second account showing the connecting message.
