### ISSUE TITLE
Message recording UI is displayed in all views

### ISSUE THREAD

**Issue by xperiandri** [UnigramDev/Unigram#1048]
When I record a voice message in one view UI changes in all views
![image](https://user-images.githubusercontent.com/2365592/56065472-98f50380-5d7d-11e9-95e9-4baeb0f9544d.png)

**Comment by MarcAnt01** [comment]
Do you mean chat open in a new window?

**Comment by xperiandri** [comment]
At the left, you see the main window, at the right you see People Experience hosted view
