### ISSUE TITLE
Users should see only working menu elements

### ISSUE THREAD

**Issue by danielkornev** [UnigramDev/Unigram#105]
As a user of Unigram, I want to see only those menu elements that are available to me:

Acceptance Criteria:

1. I open Unigram
1. I click on ... button
1. I should see only "About" menu item in it

![image](https://cloud.githubusercontent.com/assets/5264043/20981901/66bb51a2-bcc7-11e6-9b26-7b2e34baa2af.png)

**Comment by larsschellhas** [comment]
I think it is okay like it is. It gives you a glance on what you can expect to implemented and where. 

I would more likely say, that it would be nice to have a functional settings page :D

**Comment by danielkornev** [comment]
You can create a blog post and share screenshots illustrating proposed functionality for the purpose of giving users a glance on what to expect.

It shouldn't be in the product.

Sent from my Windows 10 phone
