### ISSUE TITLE
Improvements to new "send files" ui

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1050]
- [x] Auto trigger caption field
- [x] Use enter to send the content
- [ ] Open the selected chats after the OK and not before

**Comment by dmnmsc** [comment]
I can't type when dragging files. Tested with two PDF in saved messages

**Comment by cewbdex** [comment]
Maybe add a an option to add another file by picking, not only drag & drop.

**Comment by FrayxRulez** [comment]
I didn't know it was possible by drag & drop
