### ISSUE TITLE
RTL support for InstantView

### ISSUE THREAD

**Issue by runo280** [UnigramDev/Unigram#1053]
![ApplicationFrameHost_4vJGlgUiIh](https://user-images.githubusercontent.com/13608702/56096061-79361a80-5ef8-11e9-819f-194bb181cce5.png)

**Comment by MarcAnt01** [comment]
Added in https://github.com/UnigramDev/Unigram/commit/c7f89ff421c37c53cb6f55b2d239109ad619205c
