### ISSUE TITLE
Unhandled exception on clicking "Attach media" button

### ISSUE THREAD

**Issue by runo280** [UnigramDev/Unigram#1054]
![ApplicationFrameHost_jj7xW3hu3H](https://user-images.githubusercontent.com/13608702/56096178-f910b480-5ef9-11e9-9c93-5ea6cce4a3c8.png)

Unigram 3.5.2246
It occurs only once, each time I run the app, when clicking "Attach media" button.

**Comment by FrayxRulez** [comment]
Looks like that some of the medias in your pictures library is causing the issue 🤔

**Comment by runo280** [comment]
Click on "Attach media" -> **exception** -> click "Gallery" -> file browser opens
Anyway I removed contents of "My Pictures", it's happen again.
