### ISSUE TITLE
Support HexToUnicode hotkey

### ISSUE THREAD

**Issue by mirh** [UnigramDev/Unigram#1055]
Examples:
https://bugs.documentfoundation.org/show_bug.cgi?id=73691#c6
https://docs.microsoft.com/en-us/windows/desktop/controls/use-rich-edit-text-operations

**Comment by FrayxRulez** [comment]
I'm not sure about what "HexToUnicode hotkey" should be?

**Comment by mirh** [comment]
[Alt+X](https://docs.microsoft.com/en-us/windows/desktop/controls/about-rich-edit-controls#rich-edit-shortcut-keys) (the others wouldn't hurt either then). 
It's a remotely common thing for expanding physical keyboard symbols.

**Comment by FrayxRulez** [comment]
Done in https://github.com/UnigramDev/Unigram/commit/3371c811dceeda2b5d3c013af363f4e41c989edd, you must select 4 characters and press Alt+X to make it work.

Fun enough, the app is already using rich edit.

**Comment by mirh** [comment]
Wow, fastest bugfix ever. 
I don't need to type 4 digits in wordpad for the thing to work though.
