### ISSUE TITLE
Pinned chats will appear to reorder into unpinned ones during animation

### ISSUE THREAD

**Issue by rabiet** [UnigramDev/Unigram#1056]
When you're reordering the pinned chats and pull them down into the unpinned ones it will still appear to reorder it lower than it will actually be placed. 
For example, if you have two chats pinned and you pull the top one down a gap will open in the unpinned chats as long as your holding the chat.

Two pinned chats:
![image](https://user-images.githubusercontent.com/15967138/56131050-bf39bf80-5f86-11e9-9498-2a822e735061.png)

Dragging the top one down to a lower position:
![image](https://user-images.githubusercontent.com/15967138/56131100-dbd5f780-5f86-11e9-9382-b9cd292ef7e0.png)

**Comment by FrayxRulez** [comment]
If moved to a unallowed position the chat will reposition to its original one once released.

**Comment by rabiet** [comment]
I am aware of that. The animation leads to user to believe it will be placed farther down, though.
Since it was made clear to me that Unigram is supposed to follow the TDesktop standard, I think the behaviour should be adapted.

**Comment by FrayxRulez** [comment]
This is a system behavior and it can't be overridden.
