### ISSUE TITLE
Optimise margins for tablet mode

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1058]
![image](https://user-images.githubusercontent.com/43090263/56302470-1f249780-613a-11e9-8b36-9765dacac878.png)

In tablet mode, chat name is too close to the top margin and that's unpleasant to see

**Comment by FrayxRulez** [comment]
Would you prefer to always have the titlebar visible? 🤔

**Comment by MarcAnt01** [comment]
No, other apps display empty space there

**Comment by FrayxRulez** [comment]
Screenshot?

**Comment by MarcAnt01** [comment]
Just check Windows Mail in normal mode and then in tablet mode

**Comment by MarcAnt01** [comment]
Normal mode:
![image](https://user-images.githubusercontent.com/43090263/56303601-8cd1c300-613c-11e9-8ea8-0688ddec55e3.png)

Tablet mode:
![image](https://user-images.githubusercontent.com/43090263/56303657-b2f76300-613c-11e9-851f-940f44e51240.png)

**Comment by FrayxRulez** [comment]
Oke, I can do this...

**Comment by jp-weber** [comment]
I actually think it's the way it is, it looks good. But maybe you can use the space more efficiently by moving the chat name and online status of the chat to a RelativePanel. So the online status of the chat would be to the right of the chat name, if there is enough room.

**Comment by MarcAnt01** [comment]
I think adding the app name and some space as all uwp apps do is a better solution, also less work to be performed

**Comment by jp-weber** [comment]
"adding the app name and some space as all uwp apps"
This is no standard and few do this, in tablet mode it is standard to disable the title bar. So I don't like the idea.

**Comment by MarcAnt01** [comment]
> "adding the app name and some space as all uwp apps"

It just disables some elements of title bar, just take a look at the screenshots above

**Comment by jp-weber** [comment]
I've seen it, but I don't know why waste the space on the tablet.

**Comment by MarcAnt01** [comment]
https://docs.microsoft.com/en-us/windows/uwp/design/shell/title-bar#full-screen-and-tablet-mode

**Comment by FrayxRulez** [comment]
> https://docs.microsoft.com/en-us/windows/uwp/design/shell/title-bar#full-screen-and-tablet-mode

What you linked is exactly what the app does already: it hides the custom titlebar when the system one is hidden by the system, as standard behavior is to hide it.

**Comment by MarcAnt01** [comment]
That has been done at a certain point
