### ISSUE TITLE
Search messages per person disappears in some conditions

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1059]
Steps to reproduce:
1) Open messages search;
2) Select messages search per person;
3) Close messages search per person.

Now the options to search messages per person and per date are no longer visible in the next search, it's necessary to close and open the app to get them back.

This is applicable just to Desktop

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/f4c6398e727846212a37e16ff928d15c6162370f

**Comment by MarcAnt01** [comment]
It still happens in 3.6.2287
