### ISSUE TITLE
User shouldn't see strange error messages when errors happen and errors can be skipped

### ISSUE THREAD

**Issue by danielkornev** [UnigramDev/Unigram#106]
As a user, I don't want to see strange dialog boxes that bring zero sense to me, and confuse me.

Acceptance Criteria:

1. Open Unigram
1. Right click on a chat in the chat list
1. Show that no strange dialogs are shown to me

(in other words, right now, if you open Unigram and right click on a chat in the chat list, you can get this message)

![image](https://cloud.githubusercontent.com/assets/5264043/20982075/1d2a7c06-bcc8-11e6-8ed4-8f43a7733ad9.png)

**Comment by crafti5** [comment]
Can you confirm that the issue doesn't appear anymore?

**Comment by danielkornev** [comment]
Yep, haven't seen it
