### ISSUE TITLE
Add "Suggest Emoji replacements" option to turn the feature on or off

### ISSUE THREAD

**Issue by rabiet** [UnigramDev/Unigram#1060]
In Telegram Desktop we have the option to turn off the emoji suggestions when typing. Since it is a somewhat annoying feature to people who don't tend to use emojis but rather emoticons I'd suggest Unigram should have this option as well.

![image](https://user-images.githubusercontent.com/15967138/56312256-0fb04900-6150-11e9-973f-8cc734019887.png)

**Comment by FrayxRulez** [comment]
Yeee one more option without translation

**Comment by FrayxRulez** [comment]
This was done a long time ago
