### ISSUE TITLE
Remember video player volume level between plays

### ISSUE THREAD

**Issue by rabiet** [UnigramDev/Unigram#1063]
When playing multiple videos the volume always gets set at 100% at the start of each video. Since you likely want the volume to be consistent between the videos I think Unigram should remember the last volume setting for as long as the app is open.

**Comment by GingerPlusPlus** [comment]
+1, but I'd prefer if it persisted after closing the app too.

**Comment by FrayxRulez** [comment]
Implemented in https://github.com/UnigramDev/Unigram/commit/4e68adf246a540adfaccb507346146a578c98e99

**Comment by GingerPlusPlus** [comment]
https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by FrayxRulez** [comment]
I prefer to close them this way :)
