### ISSUE TITLE
Video player randomly skips to ending of video

### ISSUE THREAD

**Issue by rabiet** [UnigramDev/Unigram#1064]
Sometimes the video player skips to the end of the video after a few seconds. 
I haven't yet found a reliable way to reproduce this but I managed to capture a video of it happening.

[skip.zip](https://github.com/UnigramDev/Unigram/files/3091504/skip.zip)

**Comment by FrayxRulez** [comment]
It happened to me as well but I have zero skills with FFmpeg and Media Foundation and I have no idea about how to fix this

**Comment by gorbunovav** [comment]
For me it more or less consistently happens with the following video:
https://t.me/mudak/28555

**Comment by FrayxRulez** [comment]
This should be fixed by https://github.com/UnigramDev/Unigram/commit/9e8feea01fbc81ba95b1534ded175136f2ab1092#diff-1633f54736a2fd3ab41adf931ab21628
