### ISSUE TITLE
When creating a new group it's unmanageble 

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1068]
Steps to reproduce:
1. Create a new group
2. Go to manage group section

Just this stuff would be shown instead of the normal "manage group" functions.
![image](https://user-images.githubusercontent.com/43090263/56471358-c4e54880-6451-11e9-94ed-c8ba4e1358d3.png)

**Comment by FrayxRulez** [comment]
Those are the only options you can change in basic groups.

**Comment by MarcAnt01** [comment]
Doing the same steps from Android client, doesn't bring to that

**Comment by MarcAnt01** [comment]
@MarcAnt01
