### ISSUE TITLE
Wrong select alignment in RTL languages  

### ISSUE THREAD

**Issue by BehdadEs** [UnigramDev/Unigram#1071]
So there is a little problem in RTL languages
Whenever I select a piece of text the selected area is aligned to left
![bug](https://user-images.githubusercontent.com/39169918/56486066-ae8bcb00-64eb-11e9-8394-333f855d483c.JPG)

**Comment by FrayxRulez** [comment]
Text selection is provided by Microsoft through RichTextBlock control, reported the issue to them here: https://aka.ms/AA4ktnn

**Comment by mhahomeblog** [comment]
Hello, some right-to-left (RTL) messages have some bug in selection.
Please check this post:
https://t.me/official25band/818
![2020-01-25_8-46-38](https://user-images.githubusercontent.com/23485114/73116732-9a7c6a80-3f50-11ea-82bc-625dcebab459.gif)
