### ISSUE TITLE
Make the counter of messages from other chats with filters the same as muted chats (grey not blue)

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1075]
![image](https://user-images.githubusercontent.com/43090263/56808758-875a3400-6832-11e9-9938-d57452cb8cfd.png)

The actual implementation is inconsistent and distractive

**Comment by FrayxRulez** [comment]
Why?

**Comment by MarcAnt01** [comment]
Because the badge of those chats are grey, why making it different in the filters?
Moreover a lot of users asked that to be changed

**Comment by FrayxRulez** [comment]
Mmh, I don't understand really. Why "All chats" should be represented as muted chats?

**Comment by MarcAnt01** [comment]
Because there's no way to determine if are muted or not and that is distractive
