### ISSUE TITLE
Direct .exe installation

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1076]
In Unigram I can't install directly an .exe from a chat.
Telegram Desktop allows me to perform that and displays an additional alert
![image](https://user-images.githubusercontent.com/43090263/56848663-db751f00-68eb-11e9-9007-b43b6aa0bef7.png)

**Comment by FrayxRulez** [comment]
UWP apps can’t open exe files: https://docs.microsoft.com/en-us/uwp/api/windows.system.launcher.launchfileasync

**Comment by MarcAnt01** [comment]
Isn't it due to the location where those files are saved?

**Comment by FrayxRulez** [comment]
I even linked the explanation, please read

**Comment by MarcAnt01** [comment]
> I even linked the explanation, please read

I have already read it. I'm asking why it isn't possible to go  to the folder where those files are saved by default and execute them
