### ISSUE TITLE
Unhandled Exception when press Shift + Click

### ISSUE THREAD

**Issue by IvnSrv** [UnigramDev/Unigram#1078]
**How to reproduce:**
- Only press shift+click in any chat

![image](https://user-images.githubusercontent.com/47585736/56855535-d624ce00-6905-11e9-8a53-4e1f93fa1a78.png)

OS: Windows 10
Architecture: x64
Version: 1809
Compilation: 17763.437

Unigram Version: 3.6.2287.0

**Comment by MarcAnt01** [comment]
Fixed in 3.7.2309
