### ISSUE TITLE
Some settings should be moved to a different section

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1081]
![image](https://user-images.githubusercontent.com/43090263/56862235-01acc480-69a9-11e9-9d0c-d160ab54960d.png)

Now that custom themes have been added, it'd be better to move these options to advanced, so that they can be found more easily. Furthermore, "send by enter" option put in the actual place makes no sense.

**Comment by FrayxRulez** [comment]
This is organized the same way as official apps.

**Comment by MarcAnt01** [comment]
@FrayxRulez Yes, but it is "Chat Settings" not "appearance"

**Comment by MarcAnt01** [comment]
"send by enter option" can be linked to a setting of the chat not to appearence

**Comment by MarcAnt01** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/89f46afca68b7229999f5f9a9d9ea7253f1aa64f
