### ISSUE TITLE
Themes: Backbutton (on W10M) does not close the customizing dialog

### ISSUE THREAD

**Issue by jp-weber** [UnigramDev/Unigram#1083]

**Comment by FrayxRulez** [comment]
Theme editor isn't really designed for small screen usage at the moment, as it is designed to be used side by side with the app.

![immagine](https://user-images.githubusercontent.com/8152849/56862470-99abad80-69ab-11e9-8fc8-52538f54c0ae.png)

**Comment by MarcAnt01** [comment]
Custom themes are optimised for PC, the intended behaviour is to create them and testing them in real time while continuing to use the app.
![image](https://user-images.githubusercontent.com/43090263/56862473-a4fed900-69ab-11e9-94e6-b328210245d3.png)
