### ISSUE TITLE
Multi-select with long-press not working

### ISSUE THREAD

**Issue by Explorare** [UnigramDev/Unigram#1087]
Version: 3.7.2330

The selected messages with long-press will be unchecked after release the left click.

**Comment by MarcAnt01** [comment]
I can't reproduce

**Comment by Explorare** [comment]
![2019-04-30_08-42-34](https://user-images.githubusercontent.com/5090766/56965932-c2d96300-6b90-11e9-8946-bc1bc6fd16a5.gif)

**Comment by Explorare** [comment]
OK. I've found the cause of this issue. There is a small icon show up after selecting text, which belongs to QTranslate. The strange behavior has gone after disable the "Show icon after selecting text".
