### ISSUE TITLE
Deleting multiple chats using the chat selection only deletes one chat

### ISSUE THREAD

**Issue by doktormerlin** [UnigramDev/Unigram#1088]
I want to delete all "XXX joined telegram" messages, so I selected all chats that only had that message and also some others containing actual messages.

When I delete them, they get shown as deleted but as soon as the app is restarted or you switch accounts, the chats are back, except for the first one

#### Steps to reproduce:
1. Select a few chats from the chat list
2. Delete them

#### Expected outcome:
All chats are deleted from all devices

#### Actual Outcome:
The chats are not shown until you restart the app or switch accounts, then they are back. On other devices, the chats are always visible and only one chat is deleted.

**Comment by FrayxRulez** [comment]
A patch should be live in the store, check for updates!
