### ISSUE TITLE
Make the panel under hamburger menu the same width as chat list

### ISSUE THREAD

**Issue by kryvyifedir** [UnigramDev/Unigram#1090]
Right now, menu that slides from the left when clicking on hamburger button is comically small(especially on big screens). 
Wouldn't it be better for it to match the width of the chat list section?
![SharedScreenshot](https://user-images.githubusercontent.com/23722132/56985634-76425780-6b91-11e9-91b1-fd2a6066f115.jpg)
Additionaly, Icons can be anchored to the left part of the app, disregarding the fact that full panel is opened or closed. This would allow easy switching between chats, calls etc.(this can be done by moving list of available accounts on top, aligning the first account in the list with hamburger menu)

**Comment by morenj96** [comment]
@kryvyifedir Hamburger menu width is half a chats list width.
You can enlarge width of your chats list

**Comment by morenj96** [comment]
@morenj96 Half of*

**Comment by kryvyifedir** [comment]
@morenj96 yeah I know, that is what I am talking about. This is odd looking and UX value of having hamburger menu with the width of the half of the chat list is debatable.

**Comment by FrayxRulez** [comment]
Hamburger menu is designed to have fixed size.
I might make it a bit wider (let's say 320px) but I'm not sure this is needed, as the content fits perfectly in the current one.

Being it half of the width is relative, as you can resize the chats list :)
