### ISSUE TITLE
Reorder the list of items under the "hamburger menu"

### ISSUE THREAD

**Issue by kryvyifedir** [UnigramDev/Unigram#1091]
Current order of the options in the left panel that is opened by clicking on Hamburger menu is a bit disorienting

Purposed order:
[First group]
- Chats
- Saved Messages
- Calls
- Contacts

[Second group]
- New Group
- New Secret Chat
- New Channel

[Third group - align it to the bottom of this whole section]
- News
- Settings

**Comment by FrayxRulez** [comment]
We're using the same grouping order as the official apps at the moment, not sure if I'll change it.
