### ISSUE TITLE
Bug in inline bots

### ISSUE THREAD

**Issue by Pato05** [UnigramDev/Unigram#1095]
![image](https://user-images.githubusercontent.com/20874747/57018361-89056c80-6c23-11e9-842e-a7fc02f43122.png)
The inline bots are pretty bugged. That appeared to me after I've sent the message. Also, it doesn't load the inline sent images, there just appears a grey square. And the graphic is not really good.

**Comment by MarcAnt01** [comment]
Added to https://github.com/UnigramDev/Unigram/issues/690
