### ISSUE TITLE
No dark background

### ISSUE THREAD

**Issue by Hexaae** [UnigramDev/Unigram#1097]
Please add dark/black backgrounds. Current backgrounds are ugly on Windows 10 when set in dark mode:
![image](https://user-images.githubusercontent.com/8591462/57136404-090b0e00-6dad-11e9-947b-09a544de6eff.png)
even when you choose:
![image](https://user-images.githubusercontent.com/8591462/57136424-1aecb100-6dad-11e9-8bc4-7f29a0b67418.png)

**Comment by MarcAnt01** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/0293d896b5a1ed8ed181e932723dbdacc8d248f0
