### ISSUE TITLE
Default background preview with dark theme is still white

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1098]
![image](https://user-images.githubusercontent.com/43090263/57192495-8eb7c680-6f31-11e9-8d23-5f5a9eb65bec.png)

**Comment by LuKePicci** [comment]
I just came here to search for and get the dark background from the app resource files. The only other darkest background in the default collection is not dark enough for me. 😅

**Comment by FrayxRulez** [comment]
Fixed!
