### ISSUE TITLE
Closing search location, closes all the location ui

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1100]

**Comment by FrayxRulez** [comment]
You must use text box clear button, not search close button.

**Comment by MarcAnt01** [comment]
That happens when closing with ESC

**Comment by FrayxRulez** [comment]
This is the intended behavior: there are two X buttons in the search bar: one is to clear the search field, the other is to close search.

**Comment by MarcAnt01** [comment]
So esc isn't intended to go back?

**Comment by FrayxRulez** [comment]
ESC is intended to close search as well
