### ISSUE TITLE
Dark/Light theme according to Windows theme

### ISSUE THREAD

**Issue by smfilipe** [UnigramDev/Unigram#1101]
In previous versions it was possible to choose dark/light theme according to Windows color scheme. I don't find this option anymore.
Is this behavior a bug or this feature was removed on purpose?

**Comment by MarcAnt01** [comment]
Hello, as custom themes have been added to make that possible it would be needed to cut Windows 10 dark and light themes, that are the ones that use system accent colour.
We are making a survey and decide to remove them or not depending on how many users do use them.

**Comment by entdark** [comment]
Additional info: Windows 10 Dark/Light inherited system accent colour correctly.
When regular Dark/Light uses their own (Dark one uses blue accent in chats no matter what system accent colour is).
Bring back Windows 10 Dark/Light themes please.

**Comment by MarcAnt01** [comment]
Added in https://github.com/UnigramDev/Unigram/commit/d9edcfea37d5c0703ba40ff9b0a977b8fab9acbf

**Comment by entdark** [comment]
You did not mention that in the changelog that we receive in Telegram.

**Comment by MarcAnt01** [comment]
> You did not mention that in the changelog that we receive in Telegram.
> Mention next time, please.

I don't write changelogs, Fela does it aiming to be concise

**Comment by entdark** [comment]
When "Use system theme" is selected then it's impossible to create new theme based on it.
Clicking "Create new theme" does nothing.
I wanted that to fix the quoting accent colour that doesn't inherit from the system accent colour:
https://i.imgur.com/pd33avq.png

So basically there are 2 problems:
1) "Create new theme" does nothing when "Use system theme" is selected
2) "Use system theme" doesn't use accent colour fully
