### ISSUE TITLE
Unigram keeps resetting theme after installing an update

### ISSUE THREAD

**Issue by adrianghc** [UnigramDev/Unigram#1107]
I use the dark blue theme (great job, by the way!) but every time the app is updated, the theme is reset back to the default - even though in the theme selection list, none of the entries is selected. This is on build 18362.86. I can provide more details as needed.

**Comment by FrayxRulez** [comment]
There have been a few issues with themes in the last versions, but they're now solved

**Comment by adrianghc** [comment]
How can you be so quick to respond? It's amazing. Anyway, thanks a lot.

**Comment by adrianghc** [comment]
I still had this issue after the update to 3.8.2411, is this to be expected?

**Comment by FrayxRulez** [comment]
No, this isn't expected and I'm not able to reproduce the issue:
- Have you set a theme?
- Are you using a custom theme?

**Comment by adrianghc** [comment]
Yes, I've set the dark blue theme without any modifications (where have Windows 10 light and dark gone to, by the way?).

**Comment by adrianghc** [comment]
This issue is still there on a clean install over a year later. I can't be the only one to ever experience this.

**Comment by adrianghc** [comment]
@FrayxRulez This issue is still there on a clean install over a year later. I can't be the only one to ever experience this.

**Comment by MarcAnt01** [comment]
> @FrayxRulez This issue is still there on a clean install over a year later. I can't be the only one to ever experience this.

Are you using dark blue theme?

**Comment by FrayxRulez** [comment]
> @FrayxRulez This issue is still there on a clean install over a year later. I can't be the only one to ever experience this.

You're not the only one, but being this something I can't test myself it's really low priority in my backlog.

**Comment by MarcAnt01** [comment]
> You're not the only one, but being this something I can't test myself it's really low priority in my backlog.

I think he's using dark blue theme that is the only one with this issue

**Comment by FrayxRulez** [comment]
I figured out why. Custom themes are saved as their path, but package path changes when updating the app (that is, the package folder contains the app version) so the app can't find the old theme file. Will fix.

**Comment by adrianghc** [comment]
Yes, I'm using the dark blue theme. Glad you could locate the problem, thank you. :)

**Comment by MarcAnt01** [comment]
I have already opened https://github.com/UnigramDev/Unigram/issues/1266 some time ago
