### ISSUE TITLE
Tell letters are cut off when using expanded chat list setting

### ISSUE THREAD

**Issue by rabiet** [UnigramDev/Unigram#1109]
Some taller letters are being cut off when the chat list is set to expanded.

![image](https://user-images.githubusercontent.com/15967138/57476029-02d9cd80-7296-11e9-81e8-bae39fa3a832.png)
In this image, the crooked line is supposed to be a 7.

**Comment by FrayxRulez** [comment]
This has been fixed in the source code. (You can fix this on your device by manually replacing `Assets\Emoji\Apple.ttf` with the one you find here on GitHub)
