### ISSUE TITLE
Crashes short after displaying the Unigram logo

### ISSUE THREAD

**Issue by Rahsna** [UnigramDev/Unigram#1111]
No GUI other than the splash screen is visible before the crash happens.

I've restarted the device, resat the app, uninstalled, rebooted and re-installed the app, but it still crashes.

App version (according to Microsoft Store) 3.8.2435.0
Windows version: 18362.113 (released today)

Version of the app prior to the issue: 3.8.2411

**Comment by FrayxRulez** [comment]
Looks like you're one of the few that got a faulty package, hold on, I'm building a new update that should most likely solve the problem.

**Comment by FrayxRulez** [comment]
Opened a ticket on Microsoft side as well: https://developercommunity.visualstudio.com/content/problem/569416/visual-studio-2019-reuses-outdated-obj-files-while.html

**Comment by FrayxRulez** [comment]
The update is live!

**Comment by Rahsna** [comment]
Yep! It works again. Thank you for the super fast turn-around time ❤

**Comment by Rahsna** [comment]
> Opened a ticket on Microsoft side as well: https://developercommunity.visualstudio.com/content/problem/569416/visual-studio-2019-reuses-outdated-obj-files-while.html

You've got a "need more info" reply from them :)
