### ISSUE TITLE
Magnet links are rejected in add link dialog

### ISSUE THREAD

**Issue by DjArt** [UnigramDev/Unigram#1113]
Link for example: `magnet:?xt=urn:tree:tiger:M2FBP6USK5P6XEMRPNZQUZLOIAX6MKZW7I3BLTQ&xl=4169269248&dn=950XL_1078.0053.18895.13169.12547.035242_woaclient_pro_en-us_prod_unlocked.ffu`
![image](https://user-images.githubusercontent.com/1651555/57966544-9b9ad800-797d-11e9-9b69-7fbc12db5d6e.png)

**Comment by FrayxRulez** [comment]
Telegram only supports HTTP/S and TG uri schemes.

**Comment by DjArt** [comment]
You should be better! Why you can't realize that feature?

**Comment by MattiaBLX** [comment]
@DjArt it's server side

**Comment by FrayxRulez** [comment]
As @MattiaBLX said link are processed and validated by Telegram servers. Unallowed links would get removed once the message has been sent.
