### ISSUE TITLE
Use landscape months separator for shared media

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1116]
Unigram
![image](https://user-images.githubusercontent.com/43090263/58195644-c14f1680-7cc8-11e9-9775-442b6b923862.png)

Telegram for Android
![image](https://user-images.githubusercontent.com/43090263/58195846-34588d00-7cc9-11e9-87a6-06707d7bd946.png)

**Comment by FrayxRulez** [comment]
UWP doesn't allow this. If you want I can remove separators.

**Comment by MarcAnt01** [comment]
> UWP doesn't allow this. If you want I can remove separators.

What do you mean by that?

**Comment by FrayxRulez** [comment]
I removed the separators 👯
