### ISSUE TITLE
New music player and UI guidlines for UWP apps

### ISSUE THREAD

**Issue by f242** [UnigramDev/Unigram#1118]
Why you don't use UI guidelines for UWP apps? 
https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/media-playback

New music player is terrible! Seek bar is too slim and very hard to hit because it only 6 pixels height. Unfortunately you make same useless player like in telegram desktop.

**Comment by FrayxRulez** [comment]
The system provided transport controls won't fit this scenario: I believe it's quite important to know which file is currently being played and being able to easily access the current playlist, rather than having the huge system provided slider.

Do you have any better suggestion?
