### ISSUE TITLE
Duplicate notifications

### ISSUE THREAD

**Issue by adrianghc** [UnigramDev/Unigram#1119]
Since updating to the desktop beta, I'm often getting notifications twice in a row (particularly for group chats). Beginning with 3.9.2461, the first one of those sometimes triggers an exception that causes Unigram to appear unlocalized.

**Comment by FrayxRulez** [comment]
Linked to #1122

**Comment by adrianghc** [comment]
How exactly is it linked?

**Comment by FrayxRulez** [comment]
Removing push notifications would definitely solve the issue :)

**Comment by adrianghc** [comment]
Why would you want to remove push notifications?

**Comment by FrayxRulez** [comment]
You can read the linked ticket.

**Comment by mautheus** [comment]
@FrayxRulez I realized that after receiving a notification and only after a few hours I open the Unigram it is not displayed again

**Comment by adrianghc** [comment]
I'm getting duplicate notifications without the systray icon, though, so I assume you don't actually need that but only the UnigramBridge process needs to be running?

**Comment by MarcAnt01** [comment]
Included in #1206
