### ISSUE TITLE
Exception while resizing of chat list from the master panel

### ISSUE THREAD

**Issue by jp-weber** [UnigramDev/Unigram#1121]
at Unigram v. 3.9.2468
![grafik](https://user-images.githubusercontent.com/10946850/58336776-ab666080-7e44-11e9-964e-9cd7563e8a9f.png)

**Comment by MarcAnt01** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/333b0f6b23ccc09679a6d36775fb2d4cb1867797
