### ISSUE TITLE
Link notifications to system tray process

### ISSUE THREAD

**Issue by jp-weber** [UnigramDev/Unigram#1122]
so that the app is completely closed when the tray is closed and no messages will be received.

**Comment by FrayxRulez** [comment]
What do you mean?

**Comment by FrayxRulez** [comment]
You don’t want push notifications on desktop, is this right?

**Comment by jp-weber** [comment]
Yes, like the classic Telegram client, the tray icon control the message receive of the app. It would be good, if the app can have the same life cycle like the normal application.

**Comment by FrayxRulez** [comment]
I was thinking the same but I’m not 100% sure

**Comment by MarcAnt01** [comment]
Personally, I'd rather use the action centre to check if notifications are received, will it kill its functionality?

**Comment by FrayxRulez** [comment]
Push notifications are useless as you usually keep the softwares you actively use open

**Comment by MarcAnt01** [comment]
> Push notifications are useless as you usually keep the softwares you actively use open

Telling to me?

**Comment by FrayxRulez** [comment]
Yes

**Comment by MarcAnt01** [comment]
> Yes

I sometimes close Unigram and like to see the messages I have received through action panel, imagine that I don't wanna get online because of a specific message, killing push notifications this won't be possible

**Comment by jp-weber** [comment]
> 
> 
> I was thinking the same but I’m not 100% sure

Current notifications are displayed at the UWA by the background service regardless of whether the app is open or closed. With the classic desktop client, notifications are only displayed if the application is started (and the the tray icon is active). 

Is this for the app possible? That only as long as the application is started with the tray icon, notifcations are received.

**Comment by MarcAnt01** [comment]
> I was thinking the same but I’m not 100% sure
> 
> Current notifications are displayed at the UWA by the background service regardless of whether the app is open or closed. With the classic desktop client, notifications are only displayed if the application is started (and the the tray icon is active).
> Is this for the app possible? That only as long as the application is started with the tray icon, notifcations are received.

Now Unigram uses some Win32 stuff, but was born as uwp, why making its behaviour like a Win32 app

**Comment by jp-weber** [comment]
Because I think it's better. It's one of the reasons why I currently still prefer the Telegram desktop client instead of Unigram.

**Comment by MarcAnt01** [comment]
> Because I think it's better. It's one of the reasons why I currently still prefer the Telegram desktop client instead of Unigram.

Yes, but you don't seem to use Action Centre, Action Centre was initially meant to replace Tray Icons area. There you can have all the notifications contents, without opening the apps

**Comment by adrianghc** [comment]
I don't see why push notifications should be removed. I consider it a feature to get notifications without needing to have the app open. This said, if notifications get linked to the system tray icon it won't bother me too much (as long as they still work as they now do, i.e. with inline replies etc.) but I just don't see the need.

**Comment by MarcAnt01** [comment]
Definitely agree with @adrianghc

**Comment by FrayxRulez** [comment]
As mentioned earlier there are multiple reasons:
- Average user doesn't expect this: any other messenger client on desktop doesn't use push notifications, so they end up by moving to some other client
- Push notifications are slow and unreliable.
- Push notifications are quite limited compared to in-app notifications, and they require a lot of workarounds an maintenance

Even with all the mentioned workarounds user experience isn't as good as in-app notifications:
- Unread messages/chats counter doesn't work at all/doesn't work as expected
- Duplicated notifications can't be easily prevented (as is: one is in-app and the other is push)

I want to underline that other messengers don't use push notifications on desktop by UX choice, not because they aren't UWP.
I could go on but I think this is enough.

**Comment by adrianghc** [comment]
I understand. Well, as long as you can still get actionable notifications in the Action Center exactly as now without needing to have an Unigram window open I don't really mind whether they come as push notifications or through the desktop bridge.

**Comment by MarcAnt01** [comment]
> As mentioned earlier there are multiple reasons:
> 
> * Average user doesn't expect this: any other messenger client on desktop doesn't use push notifications, so they end up by moving to some other client
> * Push notifications are slow and unreliable.
> * Push notifications are quite limited compared to in-app notifications, and they require a lot of workarounds an maintenance
> 
> Even with all the mentioned workarounds user experience isn't as good as in-app notifications:
> 
> * Unread messages/chats counter doesn't work at all/doesn't work as expected
> * Duplicated notifications can't be easily prevented (as is: one is in-app and the other is push)
> 
> I want to underline that other messengers don't use push notifications on desktop by UX choice, not because they aren't UWP.
> I could go on but I think this is enough.

I have always appreciated them, but if they can't be fixed as they should, better to remove them!

**Comment by massijay** [comment]
I chose Unigram over the classic Telegram desktop because it was a 100% WinRT UWP app and it behaved like a mobile app, always receiving messages with push notifications, without the old-style (useless to me) tray icon. I love push notifications so I can fast reply to messages directly when I'm doing other things.
If you remove all of these functionalities it doesn't make any sense anymore to call it Unigram and prefer it over the official client to me. For now I have installed the Unigram "mobile" on my PCs to solve issues #1117 and #1119 and avoid the tray icon, I hope Unigram will remain full Universal.

**Comment by adrianghc** [comment]
I think there is a slight misunderstanding with the term "push notifications". The way it's being used by @FrayxRulez is a very technical one, as in push notifications sent by Microsoft's push notification servers to a local device. Removing these in favor of in-app notifications does not mean that actionable notifications are gone, nor that they would stop arriving in the background. It would just mean that they would not be sent by Microsoft's cloud service, but be generated by the Unigram desktop bridge process, which runs invisibly in the background and does NOT require the tray icon to be visible, at least not as of today. Correct me if I'm wrong @FrayxRulez .

**Comment by MarcAnt01** [comment]
@massijay the perspective of uwp programmes, is being Win32 programmes, with main app sandboxed as a uwp. That's how Skype uwp works and there are no downsides tbh

**Comment by massijay** [comment]
Desktop bridge was born to slowly migrate apps to WinRT, why Unigram is going in the opposite way? There are some features that require more capabilities? It worked really well and push notifications often arrive sooner with Unigram than with Telegram on my Android phone.
And what about the future Windows platform? Will these hybrid apps behave as good as pure winrt uwp apps outside the desktop too?

**Comment by MarcAnt01** [comment]
> Desktop bridge was born to slowly migrate apps to WinRT, why Unigram is going in the opposite way? There are some features that require more capabilities? It worked really well and push notifications often arrive sooner with Unigram than with Telegram on my Android phone.
> And what about the future Windows platform? Will these hybrid apps behave as good as pure winrt uwp apps outside the desktop too?

Desktop Bridge was born with this idea, but it can be used also to extend uwp functionalities, for example I really like light up icon.
On platforms like HoloLens and Xbox, Desktop Bridge will be simply not bundled in the update

**Comment by woutervanoorschot** [comment]
The tray icon seems unnecessary clutter, and a background task in win32 will use more battery than just letting windows 10 handle the push notifications. Besides that, you can just turn off push notifications in settings for unigram if you only want notifications when the app is open. Just turn off 'allow this app to run in the background'.

**Comment by entdark** [comment]
Also Unigram keeps running its process on background even after closing it.
It used to be closed completely and had no processes after closing.

**Comment by MarcAnt01** [comment]
> Also Unigram keeps running its process on background even after closing it.
> It used to be closed completely and had no processes after closing.

No, extended execution had been enabled some updates before Desktop Bridge to improve quick reply functionality

**Comment by entdark** [comment]
> > Also Unigram keeps running its process on background even after closing it.
> > It used to be closed completely and had no processes after closing.
> 
> No, extended execution had been enabled some updates before Desktop Bridge to improve quick reply functionality

Excuse me for off topic then, but is it possible to disable? Else I have to kill the process all the time manually and I didn't have the issue with quick reply before that anyways.

**Comment by MarcAnt01** [comment]
Soon, you'll be able to close Unigram at all

**Comment by entdark** [comment]
> Soon, you'll be able to close Unigram at all

With the ability to receive notifications when the app is closed and no background processes running as it used to be?

**Comment by woutervanoorschot** [comment]
If I understand it correctly the background notifications (which were previously managed by windows itself, as it should in uwp) are now moved to a win32 desktop bridge part. Which will create a separate process, and a tray icon as indicator of it running, not integrating or manageable through windows, but only by closing the tray icon (probably with right click, like the telegram desktop official client).

From a ux experience the same as the official telegram client, so in my eyes a step down in features for unigram.

**Comment by entdark** [comment]
> If I understand it correctly the background notifications (which were previously managed by windows itself, as it should in uwp) are now moved to a win32 desktop bridge part. Which will create a separate process, and a tray icon as indicator of it running, not integrating or manageable through windows, but only by closing the tray icon (probably with right click, like the telegram desktop official client).
> 
> From a ux experience the same as the official telegram client, so in my eyes a step down in features for unigram.

A big step down then, especially when I want Unigram completely closed but receive notifications anyways. Built-in features should be the priority IMO.

@devs
Why not to make that new tray&co feature optional:
those who want endless background process - let them have that;
but those who want to have the modern experience - let them have that too as it used to be.
So everyone is happy.

P.S.: I think if one wants all the Telegram Desktop features then they should install that client and not demand it in the native client and break the UX of current users.

**Comment by FrayxRulez** [comment]
> P.S.: I think if one wants all the Telegram Desktop features then they should install that client and not demand it in the native client and break the UX of current users.

But I try to target all Telegram users, not just UWP fans.

**Comment by massijay** [comment]
> I don't think we should expect the devs to maintain two solutions to a problem at the same time and invest double the time when one could do. Is the technicality of how exactly the notifications are generated really so important from a user perspective? The resources used by the desktop bridge are completely negligible. It's sitting at 0% CPU and 200 KB RAM for me right now, 2.2 MB right after using Unigram. And if it makes the development easier and enables better notifications and time investments into other features, why not?
> I propose the following:
> 
> Remove push notifications in favor of the ones generated by the desktop bridge.
> Keep the tray icon optional.
> Enable termination of Unigram whole (including the desktop bridge) via tray icon.
> If the tray icon is disabled, Unigram behaves as it already does now with constant background notifications (but generated via desktop bridge instead of push). If one doesn't want them, they can turn them off via settings as is already possible today.

I'm a UWP fan so I still prefer the old solution (100% WinRT) but I think this is the best compromise

**Comment by woutervanoorschot** [comment]
But there was nothing wrong with the old way of notifications? There could just be a setting within the app to disable/enable background notifications with a uwp implementation.

Also everyone could already disable it in settings, by disabling "allow this app to run in the background". I just don't get what advantage an extra tray icon and a win32 process give, since the argument is about disabling background notifications.

Nonetheless I would still use and love unigram, the rest of the app is still more clear, more beautiful and faster than the official client. This just feels like a weird approach.

**Comment by adrianghc** [comment]
@FrayxRulez gave some explanations for what is wrong with push notifications.

> As mentioned earlier there are multiple reasons:
> 
> * Average user doesn't expect this: any other messenger client on desktop doesn't use push notifications, so they end up by moving to some other client
> * Push notifications are slow and unreliable.
> * Push notifications are quite limited compared to in-app notifications, and they require a lot of workarounds an maintenance
> 
> Even with all the mentioned workarounds user experience isn't as good as in-app notifications:
> 
> * Unread messages/chats counter doesn't work at all/doesn't work as expected
> * Duplicated notifications can't be easily prevented (as is: one is in-app and the other is push)
> 
> I want to underline that other messengers don't use push notifications on desktop by UX choice, not because they aren't UWP.
> I could go on but I think this is enough.

**Comment by entdark** [comment]
> > P.S.: I think if one wants all the Telegram Desktop features then they should install that client and not demand it in the native client and break the UX of current users.
> 
> But I try to target all Telegram users, not just UWP fans.

I am not a UWP fan, I am fan of using native solutions in each platform (and I am a user of all main OSs and prefer native system client).

**Comment by adrianghc** [comment]
> > > P.S.: I think if one wants all the Telegram Desktop features then they should install that client and not demand it in the native client and break the UX of current users.
> > 
> > 
> > But I try to target all Telegram users, not just UWP fans.
> 
> I am not a UWP fan, I am fan of using native solutions in each platform (and I am a user of all main OSs and prefer native system client).

There is nothing non-native about Unigram's new approach, though.

**Comment by entdark** [comment]
> And if it makes the development easier and enables better notifications and time investments into other features, why not?

I am not sure if it makes the development easier. Just another way.
And that feature was already developed.

**Comment by adrianghc** [comment]
> > And if it makes the development easier and enables better notifications and time investments into other features, why not?
> 
> I am not sure if it makes the development easier. Just another way.
> And that feature was already developed.

As @FrayxRulez said further above:

> Push notifications are quite limited compared to in-app notifications, and they require a lot of workarounds an maintenance

**Comment by entdark** [comment]
> There is nothing non-native about Unigram's new approach, though.

Technically you are right, but it's a compromise MS had to do to let more people move their win32 apps to UWP wrappers.
But when the app is made from scratch by the guidelines then drops to win32 level then I'd say it's less native than it supposed to be.

**Comment by adrianghc** [comment]
> > There is nothing non-native about Unigram's new approach, though.
> 
> Technically you are right, but it's a compromise MS had to do to let more people move their win32 apps to UWP wrappers.
> But when the app is made from scratch by the guidelines then drops to win32 level then I'd say it's less native than it supposed to be.

I get where you're coming from but I think expecting UWP to become the main development platform on Windows is an outdated paradigm, and Microsoft themselves have said similar things recently. Instead, the goal is to offer a vast array of tools and let the developer choose whatever works best for their needs. The desktop bridge may have been originally conceived as a stop-gap measure but I don't think that's what it is anymore, I consider it a feature to make UWP apps more powerful, just like coming from the other direction XAML Islands is a feature to make Win32 apps prettier and more visually fluent. It's not about Win32 vs UWP, it's about taking the best from each world.

**Comment by FrayxRulez** [comment]
Well, Microsoft is moving back to a more open and desktop oriented development environment, so UWP as you imagine it is actually something from the past.

The most requested feature for Unigram is the tray icon, and the most claimed issue is about push notifications arriving while "the process isn't running", so I just thought that it might be a good idea to solve them both.

**Comment by woutervanoorschot** [comment]
> Average user doesn't expect this: any other messenger client on desktop doesn't use push notifications, so they end up by moving to some other client
I understand, users don't know the win10 settings menu, but an in app option to enable/disable push notifications (for all I care it is default off) would solve this.

> The most requested feature for Unigram is the tray icon, and the most claimed issue is about push notifications arriving while "the process isn't running", so I just thought that it might be a good idea to solve them both.
I still don't understand what the tray icon (in essence) would do, indicate that unigram is running? Then it would be open on the taskbar, otherwise an in app setting for background notifications would also solve the problem without a full desktop bridge companion process right?

I do understand the reason now, I just think maybe the few people complaining about push notifications are a minority under all the users of unigram as an alternative client for telegram. Anyway, (almost) everything about unigram is still better than the official client, it just seems non-ideal on small tablets/laptops.

I don't really like it just because it is more clutter, I do understand that it could make notifications more reliable. You are also probably more experienced with the trouble surrounding notifications than I am, so if it seems like overall the best solution I will just accept it.

**Comment by entdark** [comment]
I noticed another problem that will come if notifications will be handled by the app itself: some countries block connections to Telegram, including mine, and I often have to switch between proxies to fetch my account data.
But fortunately even when the app has connection issue I still receive notifications because they are handled my MS servers.

If notifications are handled by Unigram itself then the only way to receive them with blocked connection is to open the app and switch proxies, so no way to receive them on background. Or just hope that this time the connection is fine.
And that scenario breaks the experience significantly.

**Comment by MarcAnt01** [comment]
Include in https://github.com/UnigramDev/Unigram/issues/1206
