### ISSUE TITLE
Flashing taskbar icon

### ISSUE THREAD

**Issue by AkazaDorian** [UnigramDev/Unigram#1124]
The groups notifications settings seems to be synced with other platforms (e.g. Android), but that could be kinda annoying to have the icon flashing every time there is a message. 

In Android I set the group message notification priority to "normal", which means I would like to see the updates in notification panel but don't want to get interrupted by the heads-up pops. 

A similar logic is what I want on Windows: the badge may be updated with unread messages but please don't flash that icon. It would force me to check every time those nonsense messages come.

Would appreciate to see an option to disable the flashing for those "low-priority" messages, and nice work so far. Thanks!

**Comment by MarcAnt01** [comment]
How would you expect the behaviour with mentions that can't be handled with unread badge?

**Comment by AkazaDorian** [comment]
@MarcAnt01 I only said "the badge may be updated with unread messaged but please don't flash that icon." and said nothing about mentions, are you replying to the correct issue?

**Comment by MarcAnt01** [comment]
No, just would like to understand how you would imagine to handle this situation, if things are changed according to your issue

**Comment by AkazaDorian** [comment]
@MarcAnt01 I would like an option to make things like the version one week ago, where group messages (without mentioning me) may increase the unread count badge but doesn't flash the taskbar icon.
