### ISSUE TITLE
muted chats in unmuted chats filter

### ISSUE THREAD

**Issue by metya** [UnigramDev/Unigram#1127]
Hi. I have freshly installed windows 10 and unigram from market.

So my bug is that I choose filter unmuted chats, but it shows muted chats too. Not all muted chats, but some. And it either groups and channels and even bots.

![изображение](https://user-images.githubusercontent.com/968934/58500707-5e0f2980-818b-11e9-8789-1f51b526ece5.png)
![изображение](https://user-images.githubusercontent.com/968934/58500717-636c7400-818b-11e9-8a8f-b1603307311d.png)

**Comment by metya** [comment]
@metya submitted it)

**Comment by metya** [comment]
So, I reinstalled app and nothing changes. Bug is there.

**Comment by metya** [comment]
@metya nobody look to my issue(((

**Comment by morenj96** [comment]
@metya @MarcAct01 should look at your issue, he comments on all issues

**Comment by MarcAnt01** [comment]
> @metya @MarcAct01 should look at your issue, he comments on all issues

I am not a uwp developer, I can't fix this bug, neither understand the cause

**Comment by morenj96** [comment]
@MarcAnt01 I wish the users who can't help other users, don't comment on their issues.

**Comment by MarcAnt01** [comment]
> @MarcAnt01 I wish the users who can't help other users, don't comment on their issues.

Yes and this is what you do everytime. I hope you stop soon this flame and childish behaviour.
As for the topic:
1. Your messages are a violation of our code of conduct;
2. I am a project collaborator, so I am expected to check issues, add labels, ask for information and help the users.

If you don't stop this behaviour you will be restricted read-only on the repository.

**Comment by morenj96** [comment]
@MarcAnt01 No, you can ask the users, most of them tired from your posts, comments, messages, ...
