### ISSUE TITLE
[Feature request] Hide taskbar entry

### ISSUE THREAD

**Issue by Geobert** [UnigramDev/Unigram#1128]
Hi,

I'm discovering this project while looking for an alternative to TDesktop and I'm quite happy I found it :D 

The only missing feature from TDesktop for me is the ability to hide the taskbar entry (and only keeping systray icon).

As I understand that systray entry is quite new, I think it's not possible yet to hide this task entry :)

**Comment by MarcAnt01** [comment]
You can already close the window keeping the tray icon, what's the problem?

**Comment by Geobert** [comment]
I mean, having the window open and no task entry. At work, I have a bunch of stuff open, so I'm hiding any "background" program even if the window is open (so I can keep an eye on an ongoing discussion while doing something else)

**Comment by MarcAnt01** [comment]
You can already hide task entry from settings

**Comment by Geobert** [comment]
Do I? Unigram version 3.9.2468?

**Comment by MarcAnt01** [comment]
I have 

> Do I? Unigram version 3.9.2468?

I have edited the comment

**Comment by FrayxRulez** [comment]
You _can’t_ hide it at the moment, and I’m not sure this is technically possible.

**Comment by Geobert** [comment]
TDesktop is doing it so I think it is? I might be wrong, I don't know much about UWP.
![image](https://user-images.githubusercontent.com/72570/58504456-8d6d6880-8182-11e9-9531-46a89efa5636.png)

**Comment by MarcAnt01** [comment]
> TDesktop is doing it so I think it is? I might be wrong, I don't know much about UWP.

Uwp doesn't even support Tray Icon, it's present because Unigram now uses Desktop Bridge for PC release

**Comment by Geobert** [comment]
I see :( If really impossible, feel free to close this issue then :) Thank you for your answers!

**Comment by MarcAnt01** [comment]
No, I am not saying it isn't possible, you can wait Fela's answer to close😀

**Comment by Geobert** [comment]
Another benefit, is to avoid having Unigram in the alt-tab list as well.
I'm relying on Autohotkey scripts to call the window back :)

**Comment by FrayxRulez** [comment]
I documented a bit and this doesn’t seem to be possible. 
The only way to hide a window from the taskbar is to create a new hidden one and set the first one owner to that, sadly this isn’t applicable in our case as `SetWindowLong` can only be invoked from Win32 but it _can’t_ be used to change the window owner to a window from a different process.

**Comment by Geobert** [comment]
Too bad :( Thanks for trying!
