### ISSUE TITLE
Better touch logic in emoji/gif/sticker panel with resized window

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1129]
- [ ] Dismiss it by clicking outside of the panel;
- [x] Dismiss it by clicking on the button to open it the second time;
- [x] Handle properly the search with touch keyboard

**Comment by MarcAnt01** [comment]
Its logic has been changed and that's no longer a problem

**Comment by FrayxRulez** [comment]
Does touch work now?

**Comment by MarcAnt01** [comment]
@FrayxRulez yes it does, since it opens the expanded panel, but it still cannot handle the on-screen keyboard.
Another good improvement would be directly open the expanded panel without showing for an instant the non-expanded one

**Comment by MarcAnt01** [comment]
Now the third works, but the second two not any longer

**Comment by FrayxRulez** [comment]
Dismissing by tapping outside is not technically feasible, but now the panel gets closed if you tap on the text field or the sticker button itself.
