### ISSUE TITLE
Unhandle Exception when dragging contact list to avatar column

### ISSUE THREAD

**Issue by Geobert** [UnigramDev/Unigram#1131]
![image](https://user-images.githubusercontent.com/72570/58508697-851a2b00-818c-11e9-94e0-a52b014860f2.png)

When dragging the contact list until it collapse to a single avatar column

**Comment by MarcAnt01** [comment]
Duplicate of https://github.com/UnigramDev/Unigram/issues/1121

**Comment by Geobert** [comment]
Sorry, I've searched opened issue, forgot to search on closed one (the most important…)

**Comment by MarcAnt01** [comment]
Don't worry, bug is already fixed in the source code, but the developer has no access to a PC for the moment, so cannot push the hotfix to the Store
