### ISSUE TITLE
Ability to pin the following chats to people bar : (saved messages)/(group chats)/(chats with unsaved contacts)

### ISSUE THREAD

**Issue by theneelrana** [UnigramDev/Unigram#1138]
Unless I missed something, I believe there's no way currently to pin the above-mentioned chats to the people bar. Only saved contacts can be pinned to the people bar. I tried adding myself as a contact hoping to pin myself to the people bar, but my own contact doesn't show up anywhere in unigram. I think this feature can greatly improve the workflow of many people and would be highly appreciated if implemented.

**Comment by MarcAnt01** [comment]
My People is thought to be used only with your contacts (the ones present in Microsoft People in other words)
