### ISSUE TITLE
Impossibility to create custom theme based on system theme and system theme has hardcoded colours

### ISSUE THREAD

**Issue by entdark** [UnigramDev/Unigram#1142]
When "Use system theme" is selected then it's impossible to create new theme based on it.
Clicking "Create new theme" does nothing.
I wanted that to fix the quoting accent colour that doesn't inherit from the system accent colour:
https://i.imgur.com/pd33avq.png

So basically there are 2 problems:
1) "Create new theme" does nothing when "Use system theme" is selected
2) "Use system theme" doesn't use accent colour fully

Moved the description from #1101 because it seems it was unnoticed since the issue was closed.

**Comment by FrayxRulez** [comment]
The idea of "Use system theme" is exactly to have a workaround for this problem.
It is intended that you can't create a theme using accent colors and it will most likely never be possible to, simply because it isn't possible to use accent colors dynamically from code but just from markup ([source](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/themeresource-markup-extension)).

If you want to improve this themes feel free to do this from source code, I'll be happy to accept your PR.

**Comment by entdark** [comment]
Then you need at least fix the theme itself and avoid using hardcoded colours because you said it by your own: it's the idea of that theme to have that workaround but current theme violates the idea.

I am not sure why me or someone else has to do that when it has to not have hardcoded colours from the beginning by design. Seems like someone else have to fix the problem that you made originally.

I am fine to not be able to inherit from the system theme (though, why not?) but at least disable the creation button or show a dialog that it's impossible because for now it does nothing.

**Comment by FrayxRulez** [comment]
You don't get the point, and I don't really like your passive aggressive behaviour, to be honest.
I even linked technical documentation about why not: UWP doesn't allow to dynamically link system resources from code behind, you can do this just from markup. Doing this from markup means doing this from source code.

If you aren't happy with current system theme you can edit it in source code and make a pull request: this is how open source projects work.
I'm not a designer, and I have no plans to be one, so this isn't something I care to do by myself.

I also don't get what you mean by "hardcoded colours", bother to explain?

**Comment by entdark** [comment]
I have provided the screenshot with the description in the first post:
"I wanted that to fix the quoting accent colour that doesn't inherit from the system accent colour:
https://i.imgur.com/pd33avq.png"
The system accent colour is green, quoting is blue - that is the only thing that doesn't match and doesn't change accross any accent colour change.

**Comment by FrayxRulez** [comment]
Then, as I said, you can create a pull request editing this line to the accent color shade that you prefer:
https://github.com/UnigramDev/Unigram/blob/develop/Unigram/Unigram/Themes/ThemeSystem.xaml#L59

**Comment by entdark** [comment]
Yeah, but the difference between me and you is you know every detail about your project and can find the issue much quicker than me.

I did not mean to be passive aggressive, and the issue here is you decided I could maintain and I decided you could do that too. Probably the best we could do is to avoid deciding if each of us is able to do that and have time for that.

If that isn't fixed in the nearest future and will bother me much then I will try to fix myself of course. But now I think it's better to just leave the issue noted here and stay until it's gone.

**Comment by MarcAnt01** [comment]
Why making up problems, when you can simply embark a PR?

**Comment by entdark** [comment]
> Why making up problems, when you can simply embark a PR?

To make a PR, I have to clone and set up the project. Find out how things work. Test it if it works and doesn't break anything else and most importantly that all requires time.

None made up problems. It's an actual problem with the proof in the screenshot.

**Comment by MarcAnt01** [comment]
It's not required to do this stuff, code is simple to understand, just edit the required lines and open pr

**Comment by FrayxRulez** [comment]
@entdark you could at least suggest the colors that you'd like to get replaced, and with which accent color.

**Comment by entdark** [comment]
> @entdark you could at least suggest the colors that you'd like to get replaced, and with which accent color.
@FrayxRulez 

I'd like to get replaced the following colours in the screenshot above https://i.imgur.com/pd33avq.png:
- the colour of the quoter
- the line next to them
- the background of the quoter's message (slightly blue)

And everyone has their own accent colour so I cannot say which exactly colour they should be replaced with, but I guess the quoter and the line should be the accent colour without changes.
And the background of the quoter's message should be accent colour with the same low lightness value as the current slightly blue background one in HSL format.
I hope I made the last sentence clear.

**Comment by entdark** [comment]
The background of the quoter's message could also be a default background colour of the system theme.

**Comment by cewbdex** [comment]
I think this issue is no longer applicable and should be closed.

**Comment by FrayxRulez** [comment]
Yes, closing this as we have plenty of themes choice now.
