### ISSUE TITLE
No badge on the lock screen

### ISSUE THREAD

**Issue by Aarklendoia** [UnigramDev/Unigram#1144]
When a new message is received, no badge appears on the lock screen even if it has been added in the Windows settings.
Same thing on the glance screen (Windows 10 Mobile latest version).

**Comment by MarcAnt01** [comment]
It's a random bug happening on some devices. Since it happens only on Windows 10 Mobile and its support is expected to be cut by the end of this year, will close this ticket, thanks for reporting it anyway.

**Comment by FrayxRulez** [comment]
Badge counter is updated only while the app is open.

**Comment by MarcAnt01** [comment]
@FrayxRulez I think he is talking about the badge itself, some other users reported it not to be displayed at all on Windows Phones.

**Comment by Aarklendoia** [comment]
Yes, it's the badge itself. I try to remove it and add it again ! Maybe hopefully it'll work!
