### ISSUE TITLE
Issue with Hello when resuming windows 

### ISSUE THREAD

**Issue by Stefano-BS** [UnigramDev/Unigram#1146]
When resuming Windows from suspension, if Unigram was left open but minimized, it starts looking for eyes immediately (very annoying because the red lamp is always on and it is burning battery life). It should wait for user to maximize the window.
Also Windows Hello seems to have a bug because it always fails to unlock from this state, requiring a second check

**Comment by FrayxRulez** [comment]
Honestly this sounds more like a Windows bug to me...

**Comment by FrayxRulez** [comment]
So, I changed the code not to trigger Hello automatically if the window isn't focused & in foreground in this commit: https://github.com/UnigramDev/Unigram/commit/0b96a21f8a060286db227451875cd55c2220827c
