### ISSUE TITLE
Pop-up menus are often in English even if you change language

### ISSUE THREAD

**Issue by Hexaae** [UnigramDev/Unigram#1147]
My Windows is in Italian language, I use Unigram UWP for Windows 10 1903 and I've noticed that often (not always, sometimes are correct) pop-up menu are opened in English:

![Senza nome](https://user-images.githubusercontent.com/8591462/59119010-f8245e00-8951-11e9-858f-55ec459e15d3.png)

**Comment by FrayxRulez** [comment]
Some parts of the app can't be translated as those features aren't available in official Telegram app for Android.
