### ISSUE TITLE
Logical problems to messages search in chats

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1148]
Repro steps:
1. Look for a word:
2. This will bring you to the result in the chat;
3. Look for another word
4. This will bring you to the wrong point of the chat, in fact, it should bring to the last message containing it in the chat, but the client finds the first message after the one it has looked for before

Basically it ignores all the stuff before the first content

**Comment by FrayxRulez** [comment]
This is the intended behavior: messages are being searched by the current history position

**Comment by MarcAnt01** [comment]
@FrayxRulez both Telegram Desktop and Android client, don't change the results depending on that

**Comment by FrayxRulez** [comment]
I do as I think it's a better UX. Any other search within a page works this way.
