### ISSUE TITLE
Start the app in tray when windows starts

### ISSUE THREAD

**Issue by ghiki** [UnigramDev/Unigram#1150]
Is it possible to "start in tray"?. If I check the "start with windows" tick, the app always starts in main screen (or minimized in statusbar), and what I like is to start without interrupting whatever job I'm doing. Also is not possible to close tray icon/minimized app and continue reiciving messages?

**Comment by FrayxRulez** [comment]
Added in https://github.com/UnigramDev/Unigram/commit/d6d5769e0d9573e85850572bcf7d2e9279c053ba

**Comment by Terrance** [comment]
Searching issues about adding an option for this has led me here -- did this option get lost at some point?

Looks like there was a "Launch minimized" option next to "Launch Unigram when system starts", but there isn't any more:

![Advanced settings screen](https://github.com/user-attachments/assets/6f6e2947-d3e9-4eac-81b6-6469ff7c2055)

**Comment by FrayxRulez** [comment]
The feature has never worked
