### ISSUE TITLE
New back button, isn't present in some scenarios

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1151]
https://to-do.microsoft.com/sharing?InvitationToken=67YVXMTLsGneYLeXC0DTQApgGjELG10atGBt5zg-eJt0sHW-GhqV0p46Rj-Ilwfbc

**Comment by cherepets** [comment]
Why do we have 2 back buttons at all?
I'd prefer only a system one but if the dev team prefer a custom one than a system one should be removed.

**Comment by MarcAnt01** [comment]
All the new uwp don't have it top left as before, the actual position is easier to access while using the app. I have made a list of places where the new one isn't included with the hope that Fela will find a solution for that places and remove the old one.
