### ISSUE TITLE
Archive feature (from Official Telegram Desktop) is missing

### ISSUE THREAD

**Issue by telegram-user** [UnigramDev/Unigram#1153]
https://github.com/telegramdesktop/tdesktop/releases/tag/v1.7.0

**Comment by MarcAnt01** [comment]
https://telegra.ph/Features-not-supported-by-TDLib-12-23

**Comment by Mikaela** [comment]
Could this issue be reopened as https://github.com/tdlib/td/issues/554#issuecomment-535490856 hints that the feature may be coming to TDLib?

**Comment by MarcAnt01** [comment]
@Mikaela no, ofc TDLib will support that, but it is useless to keep that open, since it doesn't depend on us. Once TDLib supports that, that might make sense

**Comment by FrayxRulez** [comment]
Implemented in beta 👍
