### ISSUE TITLE
Windows theme switch doesn't change background image

### ISSUE THREAD

**Issue by Armin2208** [UnigramDev/Unigram#1161]
When the option "System theme" is choosed in the chat settings and I change the windows theme from dark to light, or from light to dark, Unigram doesn't change the background picture. A restart is required.

**Comment by FrayxRulez** [comment]
This should work now, can you confirm?

**Comment by woutervanoorschot** [comment]
It didn't seem to work in 3.14.2691, but after resetting the background (in the bottom of the background settings) it now works.
