### ISSUE TITLE
The name of files with long name gets cut

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1162]
![image](https://user-images.githubusercontent.com/43090263/59927321-7bf34580-943c-11e9-9294-84bfd28349a8.png)

**Comment by FrayxRulez** [comment]
... So?

**Comment by MarcAnt01** [comment]
In Telegram Desktop and Android client that doesn't happen, tested with the same file

**Comment by FrayxRulez** [comment]
It's just cut in the UI because there's no enough space to show it?

**Comment by MarcAnt01** [comment]
Same scaling and TDesktop doesn't do that🤷‍♂️

**Comment by FrayxRulez** [comment]
You know, different font sizes, different metrics, different whatever: no enough space, text gets trimmed.

**Comment by MarcAnt01** [comment]
Could the mouse hover be used to show all of the name? If so I'd open another ticket for that
