### ISSUE TITLE
The buttons are not displayed correctly - Add Account

### ISSUE THREAD

**Issue by Gerbi** [UnigramDev/Unigram#1163]
The buttons de  are placed on the bar.

![image](https://user-images.githubusercontent.com/10488959/59970867-30bd5d80-9536-11e9-8e2d-1d5039b8c17e.png)

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/30c8697a3331fbe234c084b1fe24a38caf8cf317 and https://github.com/UnigramDev/Unigram/commit/6b9b34945c1a1be997c80339555e0f8414a791ce
