### ISSUE TITLE
Session broken by proxy settings

### ISSUE THREAD

**Issue by Vulyer** [UnigramDev/Unigram#1165]
This might be a little hard to explain and harder to replicate, but I found a bug.
I tried unsuccesfully to connect through TOR port (9050) by running tor.exe at a terminal in the background. As I now know, this can't be done succesfully without enabling some loopback capability (something that I must study further). The problem is this failed connection led to somehow spoil my "No proxy" setting and made it "Unavailable". I could still get notifications for new messages but the main window stopped loading them and I couldn't send messages either.
I tried restarting the app, restarting the computer but none worked. Then, I logged out of my session and re-logged in. The problem was kind of fixed as my newly opened session does connect, but the old session has not dissapeared from the sessions list, so I have duplicate sessions and one (the closed one) is completely empty (it has no chats and no menu options besides from changing to another session).

**Comment by Vulyer** [comment]
Don't worry about timing. I had to give up on setting proxy, I checked a
discussion regarding how to do it but I couldn't follow. I can do it with
Telegram desktop very easily just running the TOR daemon and setting
Telegram to listen on localhost at TOR's port and it works (both on Windows
and GNU/Linux), but Unigram requires something else to be installed on the
OS that I couldn't understand. If you could make a guide about setting
proxies on Unigram it would be very useful.

Thank you and sorry for bothering you.

**Comment by FrayxRulez** [comment]
You might try to enable local loopback https://stackoverflow.com/questions/33259763/uwp-enable-local-network-loopback
