### ISSUE TITLE
Login as bot

### ISSUE THREAD

**Issue by madl-ash** [UnigramDev/Unigram#1168]
Can i use unigram to login as bot(with bot token) instead of a telegram account(with phone numbe)?
if not,can you recommend a client that can login as bot?

**Comment by MarcAnt01** [comment]
You can't

**Comment by madl-ash** [comment]
thanks for answer
can't you add support for it?it is already present in tdlib
you can login the same way in tdlib but instead of phone number you can pass the bot token and all functions are the same.
some functions are limited though
so i guess it must be as  simple as adding a text box in login page

**Comment by MarcAnt01** [comment]
Unigram has the same features of official clients, that don't support that
