### ISSUE TITLE
Notification when someone pin a message

### ISSUE THREAD

**Issue by ghiki** [UnigramDev/Unigram#1169]
When someone pins a message in a group, the Windows notification center always shows and notify, even if the option is disabled

![imagen](https://user-images.githubusercontent.com/854302/60396704-31ad4b00-9b45-11e9-8085-042b6bc7b57b.png)

**Comment by KarinaBauer** [comment]
This issue exist even for now. Four months, guys! Somebody, fix this finally!

**Comment by MarcAnt01** [comment]
I have included that in https://github.com/UnigramDev/Unigram/issues/1169#issuecomment-552137649 Just be patient and wait, no-one is paid to mantain Unigram

**Comment by KarinaBauer** [comment]
>no-one is paid

So, publish the donation details

**Comment by MarcAnt01** [comment]
You can’t buy everything, especially time
