### ISSUE TITLE
Cannot add contact by phone number

### ISSUE THREAD

**Issue by xperiandri** [UnigramDev/Unigram#1172]
After some update, I cannot add contacts by phone any longer
Unigram always tells that contact does not exist

**Comment by MarcAnt01** [comment]
This is not supported by TDLib, please read contribution guidelines https://github.com/UnigramDev/Unigram/blob/develop/CONTRIBUTING.md

**Comment by FrayxRulez** [comment]
@MarcAnt01 I don’t see how that’s related

**Comment by MarcAnt01** [comment]
It is in TgX TDLib missing features list, is that information wrong?

**Comment by FrayxRulez** [comment]
You completely misunderstood the ticket

**Comment by MarcAnt01** [comment]
Ah, add contacts sent with cards through Unigram, got now, sorry for the misunderstanding @FrayxRulez @xperiandri

**Comment by xperiandri** [comment]
![image](https://user-images.githubusercontent.com/2365592/60675128-53c80580-9e84-11e9-9e34-96386fd373d2.png)

I mean this UI

**Comment by cewbdex** [comment]
It works now for me.
