### ISSUE TITLE
Audio playback elapsed time gets frozen

### ISSUE THREAD

**Issue by entdark** [UnigramDev/Unigram#1173]
Audio playback elapsed time gets frozen after clicking on music title second and next times.
Audio keeps playing though.
Closing the player and starting playing audio back again fixes that, but then again clicking the title twice or more returns the bug.

This issues happened with audio tracks those total length is more than 1 hour. Not sure if that is related - I haven't tested shorter tracks.

**Comment by D4v2z** [comment]
The same issue. W10mobile

**Comment by FrayxRulez** [comment]
Which audio elapsed time? The one within the message or in the player?

**Comment by entdark** [comment]
Audio elapsed time in the player above the chat.
