### ISSUE TITLE
Custom mention badge in taskbar

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1175]
Just seen this stuff and thought it'd be amazing for mentions as they are not counted among unread messages
![image](https://user-images.githubusercontent.com/43090263/60772882-e5da4300-a0fc-11e9-9679-131b3e32781a.png)

**Comment by FrayxRulez** [comment]
There's no mention symbol: https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/badges

**Comment by MarcAnt01** [comment]
The documentation has been updated. Now it looks like it is possible to create a custom glyph badge
