### ISSUE TITLE
Animated stickers support

### ISSUE THREAD

**Issue by MikeVensel** [UnigramDev/Unigram#1176]
Telegram added animated stickers and Unigram displays them with the message, "This message is not supported on your version of Telegram. Update the app to view: https://telegram.org/update." The update only came out in the last 2 days but I just figured I'd add it here.

**Comment by MarcAnt01** [comment]
This needs TDLib support, next time kindly read https://github.com/UnigramDev/Unigram/blob/develop/README.md#contributing before opening a ticket

**Comment by kariudo** [comment]
@MarcAnt01 in fairness to the above, this feature is not on the list linked to via the contributing page for [TDLib missing features](https://telegra.ph/Features-not-supported-by-TDLib-12-23)

For anyone else looking to track this issue, the bug for tdlib: https://github.com/tdlib/td/issues/624

**Comment by MarcAnt01** [comment]
You are right, my bad, I have forgotten to update the telegraph yesterday. Thanks for making me notice😄

**Comment by MikeVensel** [comment]
> @MarcAnt01 in fairness to the above, this feature is not on the list linked to via the contributing page for [TDLib missing features](https://telegra.ph/Features-not-supported-by-TDLib-12-23)
> 
> For anyone else looking to track this issue, the bug for tdlib: [tdlib/td#624](https://github.com/tdlib/td/issues/624)

The tdlib issue was resolved so can we reopen this issue as an enhancement?

**Comment by MarcAnt01** [comment]
@MikeVensel Animated stickers are already supported in Unigram closed beta

**Comment by xmxrtyx** [comment]
> @MikeVensel Animated stickers are already supported in Unigram closed beta

closed beta??
how do i join

**Comment by MarcAnt01** [comment]
Beta program is not a thing,any longer

**Comment by MarcAnt01** [comment]
Now we share beta version in https://t.me/unigramappx
