### ISSUE TITLE
Prev/next photo controls stop working after direction change

### ISSUE THREAD

**Issue by gorbunovav** [UnigramDev/Unigram#1177]
Steps to reproduce:

1. Open chat with some photos among messages
2. Click on the photo to bring it full-window
3. Switch several photos in one direction
4. Try to switch in the opposite direction (it may require several direction changes)
5. The current photo will be stuck. You need to press the arrow key several times or click several times on the same arrow with the mouse to make it work again.

**Comment by MarcAnt01** [comment]
Are you still able to reproduce it?

**Comment by gorbunovav** [comment]
@MarcAnt01 yes, in any chat/channel with images posted.
(v 3.14.2700)

**Comment by MarcAnt01** [comment]
> @MarcAnt01 yes, in any chat/channel with images posted.
> 
> (v 3.14.2700)

I tried and I am unable to

**Comment by gorbunovav** [comment]
@MarcAnt01 
![gallery_scroll_bug](https://user-images.githubusercontent.com/2665015/79640236-24775080-8199-11ea-87be-def55707b1cc.gif)

**Comment by MarcAnt01** [comment]
?

**Comment by gorbunovav** [comment]
@MarcAnt01 I've attached the video with the bug.
You can see, that first I am scrolling images in one direction and it works ok.
Then I am trying to scroll in the opposite direction and it doesn't work until I am starting to click rapidly on the arrow (clicks are highlighted with red circles).

The same thing happens if I use keyboard for scrolling.

**Comment by MarcAnt01** [comment]
Ah, that's what I was seeing from the iOS GitHub app
![image](https://user-images.githubusercontent.com/43090263/79644343-9e630600-81a8-11ea-9b29-4083ac360911.png)

**Comment by MarcAnt01** [comment]
Anyway, I tried to do your same steps and arrows continued to work properly

**Comment by gorbunovav** [comment]
@MarcAnt01 hmm... Ok, I've performed some tests - it looks like the issue appears when you have the `Scale` value in Display settings different from 100% (I am using 4K display, so 100% is unusable).

<img width="642" alt="2020-04-18 20_23_57-Settings" src="https://user-images.githubusercontent.com/2665015/79644646-eedf6100-81b2-11ea-911c-b1190761e9ba.png">

**Comment by MarcAnt01** [comment]
I have 250% and I can't reproduce the same (3000x2000 135 inches display)

**Comment by gorbunovav** [comment]
@MarcAnt01 Could you try to change windows size (e.g. width) in small steps and test the gallery behavior on each step?

I've discovered that with the scale different than 100% on some sizes it works ok and on some, it doesn't.
With the scale 100% it always works ok.

I suspect that it can have something to do with how pixels are calculated based on the scale ratio (e.g. for some widths pixel values are non-integers).

**Comment by FrayxRulez** [comment]
Kind of fixed

**Comment by gorbunovav** [comment]
@FrayxRulez works for me, thank you!
