### ISSUE TITLE
Change adaptive layout behaviour

### ISSUE THREAD

**Issue by kowalski7cc** [UnigramDev/Unigram#1179]
Current adaptive layout behaviour is to make the chat column shorter. I think it would be nicer to behave like TDesktop which moves all messages to left, and show usericon also for the sender user.

**Comment by kowalski7cc** [comment]
No news?

**Comment by MarcAnt01** [comment]
> No news?

No, otherwise there would be comments down here, don't you think?

**Comment by FrayxRulez** [comment]
I was thinking about doing the same as [Telegram Web official mockups](https://t.me/contest/119), so doing the same as now but aligning the messages to the center of the screen.

**Comment by MarcAnt01** [comment]
I prefer the centre, as well, looks better👍

**Comment by kowalski7cc** [comment]
Yep, centring is not a bad idea too. It would play nicely with responsive window resize.

**Comment by dada051** [comment]
Why not use the free space on the right to pin chat information?

**Comment by MarcAnt01** [comment]
> Why not use the free space on the right to pin chat information?

That’s already covered by https://github.com/UnigramDev/Unigram/issues/554

**Comment by dada051** [comment]
Oups, sorry
