### ISSUE TITLE
Issues with new group members search

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1180]
- [x] Empty filters aren't hidden (when there are no contacts, no bots or no other members);
- [ ] My account is displayed among other members and not among contacts

**Comment by FrayxRulez** [comment]
You're part of "Other members" as long as you aren't your own contact...

**Comment by MarcAnt01** [comment]
> You're part of "Other members" as long as you aren't your own contact...

I have the same contacts synced with Google on all my devices. My iPhone and my Android phone don’t display it there, my laptop does.

**Comment by FrayxRulez** [comment]
You're not contact of yourself. If you were Unigram would show you in that list.

**Comment by MarcAnt01** [comment]
> You're not contact of yourself. If you were Unigram would show you in that list.

How can that be a thing if the contacts are the same in all of my devices?

**Comment by FrayxRulez** [comment]
Look, there's no magic involved: https://github.com/UnigramDev/Unigram/blob/develop/Unigram/Unigram/ViewModels/ProfileViewModel.cs#L1413

**Comment by MarcAnt01** [comment]
I think it’s a bug of Windows contacts, a workaround could be display one’s account among contacts

**Comment by FrayxRulez** [comment]
No, in that code Windows contacts aren't involved. Members list is fetched from Telegram servers by category and they aren't compared in any way with Windows contacts list.

**Comment by MarcAnt01** [comment]
> No, in that code Windows contacts aren't involved. Members list is fetched from Telegram servers by category and they aren't compared in any way with Windows contacts list.

Then both the Android and the iOS client display one’s account among contacts even if there’s no contact in Telegram contacts list
