### ISSUE TITLE
Double Notifications (Windows 10 Notifications Settings)

### ISSUE THREAD

**Issue by roughnecks** [UnigramDev/Unigram#1182]
Hello.

I read a couple of other posts about duplicate notifications but haven't quite understood how to stop them.

Here's what I see in Windows 10 Settings:

![RHN6UPi](https://user-images.githubusercontent.com/1666536/61173971-7b148600-a59a-11e9-99f9-4a165133b167.png)

**Comment by MarcAnt01** [comment]
In my PC disabling the background notification process fixed it

**Comment by roughnecks** [comment]
> In my PC disabling the background notification process fixed it

But do you still get notifications when the app is closed?

**Comment by MarcAnt01** [comment]
> > In my PC disabling the background notification process fixed it
> 
> But do you still get notifications when the app is closed?

Yes, but I just close the window, the app is kept alive by the Win32 process. On mobile I think that you won't

**Comment by roughnecks** [comment]
OK, so what background notification process are you talking about?
I thought you were referring to Windows - Settings - Privacy - Background processes.

**Comment by MarcAnt01** [comment]
> OK, so what background notification process are you talking about?
> I thought you were referring to Windows - Settings - Privacy - Background processes.

Yes

**Comment by roughnecks** [comment]
But if you remove that setting, windows shouldn't keep the app running anymore when you close it...

**Comment by MarcAnt01** [comment]
Yes, but the tray icon process does

**Comment by roughnecks** [comment]
> Yes, but the tray icon process does

Oh, I disabled that. Will try now, thanks :-)

**Comment by MarcAnt01** [comment]
Wait @roughnecks on mobile that'll prevent app from running at all

**Comment by roughnecks** [comment]
I'm only using the Windows 10 App!

**Comment by MarcAnt01** [comment]
Ah, sorry, I have confused another issue, on Desktop you won't have problems
