### ISSUE TITLE
App crashed when using :emoji-completion:

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#1184]

**Comment by FrayxRulez** [comment]
Would make sense to add that you’re using the beta app 😉

Open Language settings to fix the issue.

**Comment by larsschellhas** [comment]
Oh, sorry, I totally forgot about that :D

**Comment by DarthJahus** [comment]
@larsschellhas Is this issue proper to beta version?

**Comment by larsschellhas** [comment]
thanks @FrayxRulez !
But it´s not meant to be this way either, does it?
![image](https://user-images.githubusercontent.com/14281234/61646294-624a5580-aca9-11e9-86a6-28f3cccaed6f.png)

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/1fac58014e4a5de231a022a5426822ba7fdf1d24
