### ISSUE TITLE
"Mark as Read" from Action Center does nothing

### ISSUE THREAD

**Issue by roughnecks** [UnigramDev/Unigram#1186]
Hello.

Basically title. Whenever I click on the "Mark as Read" button on a notification in the Action Center (Windows 10) nothing happens, it only removes the notification but the message stays unread.

**Comment by MarcAnt01** [comment]
Can you still reproduce the issue? Works properly here

**Comment by roughnecks** [comment]
I haven't used Unigram in a while. Closing.
