### ISSUE TITLE
Chat background less blured than in settings

### ISSUE THREAD

**Issue by walamana** [UnigramDev/Unigram#1187]
The chat background is less blured than in the settings, when you enable / disable blur, and it is a little bit off, especially because it then has less effect on readability when you turn on blur.
Unigram 3.9.2507
![Original Image](https://user-images.githubusercontent.com/26465630/61593620-2f895a00-abe2-11e9-83ed-df0401fe2819.png)
Original image
![Blured settings](https://user-images.githubusercontent.com/26465630/61593625-49c33800-abe2-11e9-8e01-887aef872f95.png)
Blured settings
![Blured chat](https://user-images.githubusercontent.com/26465630/61593630-5f386200-abe2-11e9-99ab-82bb24fb3b8d.png)
Blured chat

**Comment by FrayxRulez** [comment]
Now it should be the same
