### ISSUE TITLE
Current downloading files option

### ISSUE THREAD

**Issue by ghiki** [UnigramDev/Unigram#1189]
Is it possible to add "current downloads" option?

Now, if you have a chat with downloadable files across the chat, and you start to downloading some files, you need to go to the part of the chat where are the downloaded files to see the download progress of every file (if your chat has 1000 mesages, and your download is in the message 156, another on in the message 455 and another in message 800, you need to switch between these three messages to know when the file is downloaded)

**Comment by MarcAnt01** [comment]
This feature isn't in official clients, so won't be added

**Comment by entdark** [comment]
Why cannot Unigram be more feature rich? I see no issues with that.

**Comment by MarcAnt01** [comment]
@entdark read contributing guidelines

**Comment by entdark** [comment]
I've read and it says 
> refrain from asking particular features of non-official clients 

That does not mean one cannot ask, or the issue should be closed immediately.

I think that issue should stay opened but marked with certain labels like Feature and Consideration, that the main Unigram developer should consider later.
Feature suggestions could be good or even highly innovative, and denying them without consideration is a pretty counter-productive move.

**Comment by MarcAnt01** [comment]
Can you read and not simply take a look?
![Screenshot_Chrome_20190723-113320__01](https://user-images.githubusercontent.com/43090263/61725647-27dec800-ad3e-11e9-94bb-955012058bb0.png)

**Comment by entdark** [comment]
> Can you read and not simply take a look?
> ![Screenshot_Chrome_20190723-113320__01](https://user-images.githubusercontent.com/43090263/61725647-27dec800-ad3e-11e9-94bb-955012058bb0.png)

I can read, I even quoted a text from there. Reread my message, please.

**Comment by MarcAnt01** [comment]
You quoted the first part, while here we are talking about the second one (stuff that isn't in official clients).
If feature requests don't follow contribution guidelines, they will be closed

**Comment by entdark** [comment]
> You quoted the first part, while here we are talking about the second one (stuff that isn't in official clients).

Similar meaning, has no sense in the current context, so I didn't bother to copy everything. The main word there is only "refrain".
> If feature requests don't follow contribution guidelines, they will be closed

And that's your personal will to close, unrelated to the Unigram guidelines.
If they said every feature request that is not in the official clients will be closed, then your actions of closing would had at least a little sense.
But it says to refrain from asking, so this doesn't mean, as I said before, issue has to be closed.

**Comment by MarcAnt01** [comment]
@entdark can you stop this useless discussion?
Whatever, I have closed giving a reason, nothing more is needed

**Comment by takarushi** [comment]
Unigram follows Official Guidelines and that's all, if a official clients doesn't adds, Unigram won't do it either, your issue is closed for a reason, quite useless, because no official client has a download manager or anything that you described

**Comment by entdark** [comment]
> Whatever, I have closed giving a reason, nothing more is needed

But your reason doesn't respect the guidelines as well. That's the point I was trying to explain to you.

> Unigram follows Official Guidelines and that's all, if a official clients doesn't adds, Unigram won't do it either, your issue is closed for a reason, quite useless, because no official client has a download manager or anything that you described

I didn't ask for this particular feature.

**Comment by ghiki** [comment]
@takarushi for this reason, I asked if it was possible to add this feature ... the official client does not have some features that unigram have, if not, it would not make sense to stop using the official client right?

Anyway, If It isn't possible to add this feature, this discussion have no sense

**Comment by MarcAnt01** [comment]
@ghiki that's the reason why I am locking the discussion
