### ISSUE TITLE
Ask the developer for Microsoft.NET.Native.Framework.1.7 package

### ISSUE THREAD

**Issue by tagizaade** [UnigramDev/Unigram#1190]
I am using windows build 18362.
When I want to install it without store it says:
App Installer failed to install package dependencies. Ask the developer for Microsoft.NET.Native.Framework.1.7 package.

**Comment by MarcAnt01** [comment]
https://github.com/UnigramDev/Unigram/wiki/Build-instructions

**Comment by FrayxRulez** [comment]
You can install the app using https://unigramdev.github.io/

**Comment by tagizaade** [comment]
> You can install the app using https://unigramdev.github.io/

Actually I was using that link.

![screen](https://user-images.githubusercontent.com/8199406/61964625-8e384480-afe3-11e9-9cb8-3b924da60ea7.jpg)

**Comment by MarcAnt01** [comment]
What is your architecture? @tagizaade

**Comment by tagizaade** [comment]
> What is your architecture? @tagizaade

hardware and software are both x64-bit.

**Comment by MarcAnt01** [comment]
https://www.dropbox.com/s/sm971rrk8mdrjyj/Microsoft.NET.Native.Framework.1.7.appx?dl=1

**Comment by MarcAnt01** [comment]
In the meanwhile we look into, get it here

**Comment by kissaev** [comment]
When i try to install on windows ltsc it asks for dependency Microsoft.NET.Native.Framework.1.7 minimum version 1.7.27413.0 but you provide Microsoft.NET.Native.Framework.1.7_1.7.25531.0 links
I can't find newer version to install, can you provide it please?
