### ISSUE TITLE
[Feature Request] "Favorites" tab

### ISSUE THREAD

**Issue by ccrowles** [UnigramDev/Unigram#1192]
It would be wonderful if you could add a "Favorites" tab and the possibility to add chats to said Favorites tab (like in the now dead Bettergram or in the only-on-phone Plus Messenger). Often, pinning tabs is not enough to organize everything...
Also, the option to set the starting tab when the app launches and remember it when minimized to tray would be wonderful.

**Comment by MarcAnt01** [comment]
Nope, https://github.com/UnigramDev/Unigram/blob/develop/CONTRIBUTING.md
