### ISSUE TITLE
Doubt about versioning

### ISSUE THREAD

**Issue by nacho-marin** [UnigramDev/Unigram#1195]
Latest release as of now in https://github.com/UnigramDev/Unigram/releases is 3.9.2461, but version info in my Unigram install from Microsoft Store is 3.9.2507.

Where does it come from?

Thank you! Best,

Nacho

**Comment by MarcAnt01** [comment]
Hello, we just use to update this section to keep tracks of the changes introduced in major updates, we don't provide a changelog for every single version of the app

**Comment by nacho-marin** [comment]
OK. Thank you. But, shouldn't at least each version released in the Store be a "formal" release in the repo?

Thanks for the wonderful work of the Unigram team and for your support.

**Comment by FrayxRulez** [comment]
Some times I'm lazy enough to not create a release. Especially if the update has no changelog (in that case that's a minor update)

**Comment by nacho-marin** [comment]
Ah, ok. Thank you!

Perhaps, in order to help users keeping track of the exact commit of the repo associated to a minor update release, a formal release plus a default changelog like "Minor functionality updates" or something like that would be useful. 

If you find it useful, I can give it a try to automate that and keep you from such a boring task.

Thank you again!
