### ISSUE TITLE
Light background for video player

### ISSUE THREAD

**Issue by xmha97** [UnigramDev/Unigram#1199]
Please add below feature:
- Light background for video player

Dark:
![Dark](https://user-images.githubusercontent.com/23485114/64071901-ed9c0b00-cc99-11e9-80a6-9159214dd5b4.png)

Light:
![Light](https://user-images.githubusercontent.com/23485114/64071896-d78e4a80-cc99-11e9-87a3-bfd0f3f8f428.png)

**Comment by FrayxRulez** [comment]
But why

**Comment by xmha97** [comment]
This is my taste.

**Comment by MarcAnt01** [comment]
De gustibus non disputandum est😎

**Comment by FrayxRulez** [comment]
This will not happen
