### ISSUE TITLE
Name, phone and profile picture don´'t show up on top of contacts list.

### ISSUE THREAD

**Issue by Gonzafuentep** [UnigramDev/Unigram#120]
![wp_ss_20170105_0004_li](https://cloud.githubusercontent.com/assets/23457989/21681113/0543fd46-d34e-11e6-9fef-4f40c688ca99.jpg)

**Comment by d8vjork** [comment]
You have last versión of Unigram?

Strange bug... In my case this screen doesn't show Online status:

![wp_ss_20170105_0004](https://cloud.githubusercontent.com/assets/2331052/21681306/f9ab0e56-d34e-11e6-9ce3-669e3014e502.png)

**Comment by Gonzafuentep** [comment]
Yes, I had 0.1.53.111, but I reinstalled it and it works now.
