### ISSUE TITLE
Taskbar Buttons

### ISSUE THREAD

**Issue by amirrammari** [UnigramDev/Unigram#1200]
Hello, please add taskbar buttons for playing music or video. (see below image)
![Taskbar Buttons](https://user-images.githubusercontent.com/23485114/64075715-07a51000-ccd1-11e9-8edd-02ae20a56bb9.png)

**Comment by MarcAnt01** [comment]
They were implemented some time ago for voice messages and music, but they were always present, so they have been removed. Will leave the ticket open for their use in the video player

**Comment by FrayxRulez** [comment]
I actually added them recently.
