### ISSUE TITLE
Exist a Portable version?

### ISSUE THREAD

**Issue by RobertusIT** [UnigramDev/Unigram#1201]
Hi,

i really love portable version, exist of it?

because if i change pc, i want to paste and copy unigram folder and here we go, i have my channels and my chat, without login, phone number, password etc...

I didn't found portable version, exist or is still in development?

**Comment by MarcAnt01** [comment]
A similar concept isn't compatible with uwp, copying manually the Unigram folder should work the same, tho

**Comment by RobertusIT** [comment]
i don't use it on windows phone but on windows
