### ISSUE TITLE
My People integration without syncing all contacts to Telegram

### ISSUE THREAD

**Issue by ivucica** [UnigramDev/Unigram#1202]
Hi,

I'd like to use My People integration only with the contacts that are already present in Telegram.

As it is, if I give Unigram access to system contacts database, it'll add my contacts to Telegram. Yet, access to contacts is required for My People to work.

**Comment by MarcAnt01** [comment]
Duplicate of https://github.com/UnigramDev/Unigram/issues/1104

**Comment by ivucica** [comment]
@MarcAnt01 Interesting. Though that discussion has diverged to "you can't add people by nickname".
