### ISSUE TITLE
Add the feature "Schedule Message" like Telegram app

### ISSUE THREAD

**Issue by SASFMONTOYA** [UnigramDev/Unigram#1205]
In the lasted versión of Telegram I can send a message like a "Schedule Message" [info](https://telegram.org/blog/scheduled-reminders-themes).

In the Telegram Desktop app is like that:
With right click on the send button the app show he options:

- Send without sound
- Schedule Message

![image](https://user-images.githubusercontent.com/22794697/65060491-92c30e80-d93d-11e9-9388-76cc30203f6f.png)

I think that this feature is important to add to Unigram.
Thanks 4 all.

**Comment by MarcAnt01** [comment]
@SASFMONTOYA This is not supported by [TDLib](https://telegra.ph/Features-not-supported-by-TDLib-12-23)

**Comment by tenzan** [comment]
Any plans to implement this "basic" feature?
