### ISSUE TITLE
Disable push notifications

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1206]
**Advantages**:
- No notifications when the process is closed through system tray icon;
- No duplicate or late notifications;
- Options to disable joining contacts and pinned message notifications would actually work 
- Working mark as read button from notifications
- Fix bugs of channel notifications that once clicked don't redirect to the channel

**Disadvantages**:
- No background notification on Xbox, HoloLens and Mobile;
- No notifications at startup if you don't open the app

**How to fix manually:**
Windows 10 settings > Privacy > Background apps > Unigram (untick it). On Windows 10 Desktop in-app notifications will be received also with the window closed, but that doesn't apply to other platforms

**Comment by slackerstacker** [comment]
Since #1275 is marked as duplicate to this issue, does that mean it's either double notifications or no notifications at all for mobile?

**Comment by MarcAnt01** [comment]
> Since #1275 is marked as duplicate to this issue, does that mean it's either double notifications or no notifications at all for mobile?

That explains that the problem described in that issue is part of this one, sometimes there is a conflict between in-app notifications and push one and user gets two notifications. The bug doesn't depend on the platform

**Comment by morenj96** [comment]
@MarcAnt01 In Mobile, the system sends notification once, also the application sends in-app notification once
"Duplicated notifications" means it

**Comment by MarcAnt01** [comment]
> @MarcAnt01 In Mobile, the system sends notification once, also the application sends in-app notification once
> "Duplicated notifications" means it

Exactly and the same thing happens on Desktop, Xbox and other platforms

**Comment by morenj96** [comment]
@MarcAnt01 That's all things about duplicated notifications issue in Mobile that users had reported

**Comment by MarcAnt01** [comment]
> @MarcAnt01 That's all things about duplicated notifications issue in Mobile that users had reported

Yes and that is one of the issues related to the presence of push notifications and this issue is about that. If you check among advantages it mentions "no duplicate notifications".

**Comment by MarcAnt01** [comment]
@morenj96 isn't that clear enough?

**Comment by morenj96** [comment]
@MarcAnt01 Idk anymore

**Comment by abh-oss01** [comment]
> **Advantages**:
> - No notifications when the process is closed through system tray icon;
> - No duplicate or late notifications;
> - Options to disable joining contacts and pinned message notifications would actually work 
> - Working mark as read button from notifications
> 
> **Disadvantages**:
> - No background notification on Xbox, HoloLens and Mobile;
> - No notifications at startup if you don't open the app
> 
> **How to fix manually:**
> Windows 10 settings > Privacy > Background apps > Unigram (untick it). On Windows 10 Desktop in-app notifications will be received also with the window closed, but that doesn't apply to other platforms

would this disable notifs altogether, if the app isn't open (in any process)?
currently, the app sends me notifs even if it's not opened and in startup (if any), that's pretty useful for me I like it, so would disabling it from running in the bg stop these for me altogether?

**Comment by MarcAnt01** [comment]
Once opened you'll continue to receive notifications also with the window closed. At start-up you can chose the option to launch the app (atm just in foreground since minimised option is broken)

**Comment by adrianghc** [comment]
This doesn't seem to work for me, I'm not getting any notifications when background permission is revoked and the window is closed. Is there anything I have missed? I'm on the latest beta.

**Comment by MarcAnt01** [comment]
@adrianghc I made this guide when tray icon was present, now following it will prevent you to receive background notifications

**Comment by adrianghc** [comment]
> @adrianghc I made this guide when tray icon was present, now following it will prevent you to receive background notifications

Well, that's unfortunate. Is the tray icon gone for good? Suppose I gave it a try to fix the issues with it (online status, #1422), is there a chance it could be merged back in?

**Comment by MarcAnt01** [comment]
I am closing it, I think notifications have been improved now and it isn't worthy to use Desktop Bridge

**Comment by abh-oss01** [comment]
@MarcAnt01 still no notifications after a few minutes after the app has been closed.

**Comment by MarcAnt01** [comment]
Feel free to open a new ticket
