### ISSUE TITLE
Text too small even at maximum size setting

### ISSUE THREAD

**Issue by garmilw** [UnigramDev/Unigram#1208]
I am not sure where Unigram is picking up the font that it uses.  I have a large screen monitor, and even at the maximum text size in Settings, the text is still too small to easily read on the screen.   I have tried increasing the Windows Desktop font size, thinking that Unigram was using that setting for its display, but those changes are not being reflected in the app.  I would like to be able to increase the text size more than is currently supported within the app.  Alternatively, have a way to specify the starting text size so it starts out larger before being increased.

**Comment by FrayxRulez** [comment]
I just tried and the system setting to change font size definitely works:
![image](https://user-images.githubusercontent.com/8152849/67867754-2d149580-fb2b-11e9-813f-d849863d95ac.png)

**Comment by garmilw** [comment]
I checked with Unigram 3.11.2588   I am unable to make the font bigger than what appears to be 16 point.  I have low vision and a large monitor, so I need to get the text to 24 point to be more readable.  I am at the maximum size setting in Unigram but the text is still too small.  I am able to make the font larger with the Telegram Desktop app by increasing the interface scale setting, I want to do the same with Unigram.

**Comment by DarthJahus** [comment]
@garmilw You can also make everything bigger by changing the DPI in Windows' graphical settings. Or have you done that already?

**Comment by MarcAnt01** [comment]
@FrayxRulez I bought a Surface Book with 2000 x 3000 display and yes, Unigram is too small

**Comment by FrayxRulez** [comment]
Any UWP app use the same font styles, so you should redirect this issue to Microsoft and not to me. 

I mentioned already all the things you can do to workaround this by yourself:
- Make sure you’re using the recommended screen scaling and resolution
- Move the slider under System preferences > Ease of Access > Display > Make text bigger.

**Comment by snowman** [comment]
![image](https://github.com/UnigramDev/Unigram/assets/16096559/31400a1b-6bec-4483-bfdc-a562eb911e2b)
![image](https://github.com/UnigramDev/Unigram/assets/16096559/033718b9-104d-4290-b1df-f5f07dd42bc6)
![image](https://github.com/UnigramDev/Unigram/assets/16096559/e94d0a5a-1338-4ddb-b863-6c0914dcb780)

**Comment by HLEBNY** [comment]
this issue brings really big pain beacause the menu and chat list has the font size ~50% bigger, than nicknames and texts in the messages field, and the message size setting only affects text of messages, but not the nicknames. so i get either unreadable 6pt messages with 10pt interface, or 12pt messages with a gigantic clunky interface when i scale it entirely, or 6pt nicks with 12 pt messages and interface when i scale only messages, or broken look of all the system/apps + unigram when i scale through windows setting. UPD i made a screenshot to compare fontsize consistency between original client and unigram, i believe you see this difference.

<img width="1920" height="1031" alt="Image" src="https://github.com/user-attachments/assets/6f7c2118-424e-4366-a7b9-45ebd7965164" />

**Comment by makisukurisu** [comment]
> or broken look of all the system/apps + unigram when i scale through windows setting.

That sounds like a system problem. Unigram uses same scaling your system does. It should be 12/14 pt for most of the text in the app at 100% scaling, I believe.

Also, what version are you on? Unigram has a dedicated UI scaling slider for a year now (if not more), so you can scale message text size separately from general UI without affecting system settings.
