### ISSUE TITLE
App won´t start after install

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#121]
Hey guys and girls,

I just downloaded the new build vom HockeyApp and installed it on my L950. Sadly it doesn´t start at all. 
After the installation the Unigram-Icon appears in the loading screen, but after approximately 24 seconds it just crashes.

May this be a bug or am I doing somthing wrong?

**Comment by kesavaprasadarul** [comment]
@larsschellhas Did you try re-installing it?

**Comment by FrayxRulez** [comment]
Can you try to uninstall and then install the app again? Some configuration files are changed since latest version and maybe there are some conflicts

**Comment by larsschellhas** [comment]
I did reinstall it, but from the same downloaded file. 
Actually I haven´t installed any previous version, so it´s probably no old configuration file.

I restarted the phone and even did a soft reset. Nothing changed.

**Comment by thevexed** [comment]
@larsschellhas I have the same probem. Before installing newer version I uninstalled previous version. The issue remains even if Unigram is installed in internal storage

**Comment by larsschellhas** [comment]
I just checked my installation preferences: First I installed it on the internal storage. Now I tried installing it on the SD Card, but I didn´t work, too. Just like in the internal storage.

**Comment by larsschellhas** [comment]
I have no idea, why, but after several tries to open the app, it finaly worked. :)
As long as the app was running in background, everything was fine, but after I closed the app by the "task manager", it´s the same again.
Seems like there goes something wrong in the initial Startup procedure...

**Comment by my2008** [comment]
I'm having the same problem

**Comment by FrayxRulez** [comment]
Should be fixed by latest builds. Feel free to open this again if the problem still persists for you
