### ISSUE TITLE
Use tabs instead of menu for chat type

### ISSUE THREAD

**Issue by Ansem93** [UnigramDev/Unigram#1211]
Hi!
I wanted to ask if it would be possible to add an option that will let use choose between menu and tabs for chat types.
I was thinking about "Plus Messenger" for Android or "Telegreat" for windows for example.
I find the menu a little hard to use compared to tabs. An option would be the best thing so that everyone could choose!

**Comment by FrayxRulez** [comment]
I don't really like tabs, honestly...
You can always use F1-F7 to switch between filters.

**Comment by Ansem93** [comment]
That's why I susggested to make it an option. I like tab more, but everyone should be free to choose.

**Comment by MarcAnt01** [comment]
I'd consider this added with folders now
