### ISSUE TITLE
Tray icon does not appear in tray

### ISSUE THREAD

**Issue by electronic-dk** [UnigramDev/Unigram#1214]
Tray icon doesn't appear in tray, even though the corresponding setting is "on".

Steps to reproduce:

1. Launch Unigram
2. Login if not logged in
3. Go to Settings > Advanced and turn on "Show tray icon"
4. Check the windows tray

Expected behavior:
Unigram icon is in the tray

Actual behavior:
Unigram icon is NOT in the tray

This was introduced by 3.11.2563, still reproducible in 3.11.2579
Windows 1903 Build 18362

**Comment by alex-fgsfds** [comment]
Can confirm

**Comment by FrayxRulez** [comment]
👋 will restore the tray icon asap!

**Comment by jw113** [comment]
2588, still waiting.
I hate minimize window with -

**Comment by FrayxRulez** [comment]
Microsoft broken their tooling and it isn’t possible anymore to have the tray icon it seems (to have the tray icon I was using a separate win32 app bundled and hidden within Unigram setup). 

I’m lazy to open a ticket on their side to ask for a fix to be honest.

**Comment by electronic-dk** [comment]
@FrayxRulez thanks for the update. Is it broken in a particular version of an SDK (read Windows version) or is it some say .NET thing which can be fixed without having to wait for a new Windows version?

**Comment by FrayxRulez** [comment]
It's actually broken starting from VS 16.3

**Comment by szedjani** [comment]
The official Windows store Telegram app does have a tray icon, so I am using that since then. Too bad, it doesn't support multiple accounts, so my secondary Telegram account is now in Unigram and I use my main one with the tray icon in the official.

**Comment by FrayxRulez** [comment]
You should provide this feedback to Microsoft and not to me, I can do really little to solve the issue.

**Comment by rfgamaral** [comment]
> 
> 
> Microsoft broken their tooling and it isn’t possible anymore to have the tray icon it seems (to have the tray icon I was using a separate win32 app bundled and hidden within Unigram setup).

Can't you share that win32 app separately? We could run that manually (or automatically at startup) instead of having it bundled with the Windows store app?

**Comment by rfgamaral** [comment]
Anyway, I'm using this as workaround for now:

```ahk
#NoEnv
#Persistent
#SingleInstance force

global AHK_NOTIFYICON = 0x404
global WM_LBUTTONDBLCLK = 0x203

SendMode Input

OnMessage(AHK_NOTIFYICON, "NotifyIconHandler")

Menu, Tray, NoStandard
Menu, Tray, Icon, %A_ScriptDir%\Default.ico
Menu, Tray, Tip, Unigram

Menu, Tray, Add, Unigram, UnigramHandler
Menu, Tray, Default, Unigram

Menu, Tray, Add

Menu, Tray, Add, Exit, ExitHandler

Return

NotifyIconHandler(wParam, lParam) {
    if (lParam = WM_LBUTTONDBLCLK) {
        Gosub, UnigramHandler
        Return
    }
}

UnigramHandler:
    Run shell:AppsFolder\38833FF26BA1D.UnigramPreview_g9c9v27vpyspw!App
Return

ExitHandler:
    ExitApp
Return
```

You can download the icon from the this repository [here](https://github.com/UnigramDev/Unigram/raw/develop/Unigram/UnigramBridge/Resources/Default.ico).

**Comment by soumyamahunt** [comment]
Reported the issue in feedback hub: https://aka.ms/AA6wooo

**Comment by FrayxRulez** [comment]
I think that opening a ticket to Visual Studio team would be more effective :/

**Comment by electronic-dk** [comment]
@FrayxRulez appreciate your work on the app and a quick response to this issue back in October. Could you, please, explain briefly what Microsoft broke that the previous workaround with a win32 companion app isn't working anymore? Is it something in the Windows SDK?

**Comment by sprite-1** [comment]
@FrayxRulez is the tray icon related to the delivery of notifications? Because I have sporadic notification issues (sometimes it comes, sometimes I have to open the app for all notifications to come)

**Comment by MarcAnt01** [comment]
Yes, it would allow in-app notifications when the window is closed

**Comment by sprite-1** [comment]
I thought the whole point of UWP apps is that it doesn't need to rely on an omnipresent tray icon already because it's tied to Windows' backend with receiving push notifs

**Comment by MarcAnt01** [comment]
> I thought the whole point of UWP apps is that it doesn't need to rely on an omnipresent tray icon already because it's tied to Windows' backend with receiving push notifs

I don't know if it's Microsoft's or Telegram's fault, but I don't enjoy the experience with push notifications.

**Comment by szedjani** [comment]
This ticket is not about that notifications are not coming properly, but about not having a tray icon.

**Comment by sprite-1** [comment]
I know, I was resolving my own comment/question that [I stated here](https://github.com/UnigramDev/Unigram/issues/1214#issuecomment-576171214). As well as responding to @MarcAnt01

**Comment by szedjani** [comment]
Suddenly it just started working today.

**Comment by FrayxRulez** [comment]
🕺

**Comment by szedjani** [comment]
Since the last update, it broke again. The tray icon disappeared.

When I click on the Advanced settings I get an unhandled exception.
![image](https://user-images.githubusercontent.com/5252438/80985923-221b2480-8e30-11ea-82e1-fbec75414fcb.png)

Then when I acknowledge it, I cannot see the relevant setting.
![image](https://user-images.githubusercontent.com/5252438/80986034-4a0a8800-8e30-11ea-8a07-87413d882ec8.png)

**Comment by MarcAnt01** [comment]
Tray icon has been removed and there's already an issue about the exception

**Comment by szedjani** [comment]
I haven't seen the removal of the tray icon in the release notes. Do you know the reason by any chance? Is it permanent or just temporary?

**Comment by FrayxRulez** [comment]
Hi @szedjani I have explained the reasons here: https://github.com/UnigramDev/Unigram/issues/1493
I will make sure you can download the tray icon as a external software in the future.

**Comment by MarcAnt01** [comment]
Furthermore we don't use release section to mention the changes in minor updates

**Comment by szedjani** [comment]
Thanks for the explanation. Yes please, send me as well the tray icon exe please :)
