### ISSUE TITLE
OutOfMemoryException on Unigram Windows 10 Desktop ver 3.11.2583

### ISSUE THREAD

**Issue by tng2903** [UnigramDev/Unigram#1215]
My PC Specs is a little weak (but still can run the official apps and older version of Unigram fine):
CPU i7 2600
8GB RAM DDR3
Only integrated graphic card
SSD 250GB

Step to reproduce:
- Open Unigram ver 3.11.2583
- Start a chat session with any contact
- Send or receive an animated sticker
- Let it loop, open the Task Manager, observe the RAM usage for Unigram

Observed result: RAM used by Unigram keep rising until it display OutOfMemoryException dialog
Expected result: RAM usage should be the same for loop animated sticker

![image](https://user-images.githubusercontent.com/1988874/66884118-5d701600-effa-11e9-88ca-e3c23d7ad646.png)

**Comment by FrayxRulez** [comment]
Yes. There's a memory leak indeed.

**Comment by FrayxRulez** [comment]
Was actually an easy one. Will be included in the next release!
