### ISSUE TITLE
Unigram crash on Windows Phone

### ISSUE THREAD

**Issue by Aarklendoia** [UnigramDev/Unigram#1216]
The latest version of Unigram crashes at startup on Windows 10 Mobile (10.0.15254.590) since the last update. A reset or reinstallation does not change this.

**Comment by morenj96** [comment]
@Aarklendoia Which version of Unigram?

**Comment by Aarklendoia** [comment]
The latest : 3.11.2587.0

**Comment by morenj96** [comment]
@Aarklendoia Update again
Newer is available

**Comment by Aarklendoia** [comment]
Okay, she wasn't there a few hours ago. I install and try it.

**Comment by Aarklendoia** [comment]
It's okay, it's working again.
