### ISSUE TITLE
Option to disable animated emojis

### ISSUE THREAD

**Issue by Qwwertz** [UnigramDev/Unigram#1217]
Hello, could you please add an option to **disable** these new animated emojis (not animated stickers, those animated emojis that automatically appear when you send a message consisting of only one emoji like this one: 😁
![image](https://user-images.githubusercontent.com/18066653/67083362-4f0d3000-f19b-11e9-94af-c4ee34c6d1f5.png)

**Comment by MarcAnt01** [comment]
Won't be added  because of official guidelines. You can find more details on controbuting.md

**Comment by entdark** [comment]
@Qwwertz unfortunately, the stupidity of a local ruleset won't let you suggest 99% of features for Unigram. But the feature request is quite good and expected. I'd suggest you to write that feature request to official Telegram devs because it's a good request.

**Comment by MarcAnt01** [comment]
Yeah, contact the marketing team on Twitter if you care

**Comment by nahuelwexd** [comment]
Telegram official on Android: If you disable 'Big emojis' option, the animated emojis are disabled as well
