### ISSUE TITLE
When you call someone and they dont answer it rings forever

### ISSUE THREAD

**Issue by Synkstar** [UnigramDev/Unigram#1218]
This is really annoying because you have to reload the whole app to fix it

**Comment by CornyjK** [comment]
Faced the issue and explored a bit further, when opponent declines the call, a window like in Figure 1 appears, if you click the "bottom round X", everything works as expected, but if you click the "top window X", it breaks: windows just closes, but does not end the declined call sound, also Unigram displays a box above chat lists as in Figure 2, but cannot be clicked.

![image](https://user-images.githubusercontent.com/9021297/80916594-fb8aba00-8d59-11ea-828d-e4277c32dfcb.png)
Figure 1: Declined call window

![image](https://user-images.githubusercontent.com/9021297/80916686-92577680-8d5a-11ea-8906-673ecd1dc9bf.png)
Figure 2: Return to call glitch

**Comment by MarcAnt01** [comment]
Anyone can confirm it happens with the other platforms? I have the same issue on my iPhone

**Comment by cewbdex** [comment]
> 
> 
> Anyone can confirm it happens with the other platforms? I have the same issue on my iPhone

I guess it is platform independent, just an issue how Unigram handles it.

**Comment by MarcAnt01** [comment]
This issue persists with WebRTC

**Comment by FrayxRulez** [comment]
Are we talking about the sound?

**Comment by MarcAnt01** [comment]
I think also about the call being processed

**Comment by cewbdex** [comment]
We tested it and it seems fixed, what is your issue @MarcAnt01?

**Comment by MarcAnt01** [comment]
@cewbdex I tested it again and the only issue seems to be the sound not stopping, even if the window is closed

**Comment by MarcAnt01** [comment]
This seems to be fixed now
