### ISSUE TITLE
Exception thrown when trying to use microphone

### ISSUE THREAD

**Issue by Tabris963** [UnigramDev/Unigram#122]
On mobile (Lumia 735 on latest Insider Build), when I try to use the microphone (with a single touch on the microphone button) a first exception is throwed. A second one (a different one) is throwed when you double touch the microphone button.

Images coming (sorry, I'm unable to upload them right now)

**Comment by larsschellhas** [comment]
![capture001](https://cloud.githubusercontent.com/assets/14281234/21712407/f606ac82-d3f4-11e6-9481-2d5447ae66e1.png)
One of the exceptions

**Comment by larsschellhas** [comment]
The previous shows up when single tapping.

The second, too.
![wp_ss_20170106_0005](https://cloud.githubusercontent.com/assets/14281234/21712451/30fa489e-d3f5-11e6-9234-4e833a76b0cf.png)

And this third when you double tap on the microphone.
![wp_ss_20170106_0004](https://cloud.githubusercontent.com/assets/14281234/21712452/30fd7d20-d3f5-11e6-8374-6ab4747b7176.png)

**Comment by Tabris963** [comment]
Thanks @larsschellhas for the screenshots. The exceptions throwed are the same that I've seen, so I won't upload them again.

I would also like to add a three things:
1) those exceptions are throwed after the first button selection. So, when you install the last version of Unigram and try to start the recording, nothing will happen. When you select the second time the button, the exceptions will start being throwed.
2) I have no idea how, but somehow I managed to send some audio-messages. Actually, no sound is recorded (but that's most probably because I don't know when I'm really registering, so the file is only created but is basically empty). See screenshot below 
3) when a message is sent, I should already be able to listen it without downloading it. See screenshot below
![wp_ss_20170107_0002](https://cloud.githubusercontent.com/assets/6726440/21741395/5c03c756-d4d4-11e6-8b66-8eda5c4a46a0.png)

**Comment by crafti5** [comment]
Hi all, first of all thanks for the screenshots! I have investigated the exception and created a pull request for to avoid the exception and hopefully solved it. (At this time I couldn't test it with my PC)

**Comment by larsschellhas** [comment]
I think, this is history, too :)
