### ISSUE TITLE
Animated Sticker Crash Unigram Client

### ISSUE THREAD

**Issue by gilmishal** [UnigramDev/Unigram#1220]
Since the new update, unigram is crashing whenever I scroll to an animated sticker in the chat, send an animated sticker or generally attempt to see an animated sticker.

There is no error message I receive that I can show you.

**Comment by MarcAnt01** [comment]
You'd better specify the exact version

**Comment by gilmishal** [comment]
Version 3.11.2588

**Comment by FrayxRulez** [comment]
Would be more interesting to know if with any animated sticker or a specific one

**Comment by gilmishal** [comment]
I am not sure if it specifically stickers, it now crashes for other reasons - I sent a recording through the feedback hub if it helps.

**Comment by FrayxRulez** [comment]
Sorry but I have no access to the feedback hub...

**Comment by gilmishal** [comment]
Then I am not sure how to help you fix this problem, I assume you need a dump file or something to debug it, because this issue isn't particularly helpful in pinpointing the problem.
Anyway currently Unigram is unusable for me, and I hope you can somehow recreate the problem.

isn't there a way to get access to the feedback hub? I remember they showed it on one of the build events in recent years
