### ISSUE TITLE
Change app icon to match new Fluent-Design style Windows icons

### ISSUE THREAD

**Issue by widersky** [UnigramDev/Unigram#1221]
I think that the application should get a new icon, matching the new style of Windows icons.

**Comment by FrayxRulez** [comment]
I am not sure about which style you’re referring to. 
By the way, I’m the only one working on this project and I’m not a designer...

**Comment by widersky** [comment]
I wasn't able to upload image for some reason, but I thinking about this style: https://imgur.com/a/8WZLBxI

If you specify requirements regarding format, size of UWP icons, I can create some suggestions :)

**Comment by MarcAnt01** [comment]
@FrayxRulez They're replacing monochrome assets for icons with colored icons like in Android/iOS ones

**Comment by FrayxRulez** [comment]
I see, but we need a designer for that!

**Comment by widersky** [comment]
@FrayxRulez - I'm an designer (and developer too, but JS focused). As I wrote, if you specify requirements of UWP icons, I can create some suggestions.

**Comment by FrayxRulez** [comment]
I have no clues about the requirements for UWP icons. But the logo should definitely keep the current shape.

**Comment by widersky** [comment]
Of course it should :)

**Comment by mintykii** [comment]
I've made a few concepts for potential icons that may or may not be good for use. I've got 2 variations and one Office 365 clone.
![unigram-ver1](https://user-images.githubusercontent.com/56522308/68100096-eac8bc80-fe7a-11e9-88fd-885c3bfd7bb3.png)
![unigram-ver2](https://user-images.githubusercontent.com/56522308/68100097-eac8bc80-fe7a-11e9-8233-3b320329194f.png)
![unigram-o365](https://user-images.githubusercontent.com/56522308/68100098-eb615300-fe7a-11e9-8cc8-735f59a06905.png)
(yes I am aware there are some clipping issues with the pngs I'm sorry)

**Comment by widersky** [comment]
@mintykii  IMO third one looks promising. First and second looks too "Skypey" for me. Anyway, my idea was make current icon colorful without doing anything else. But as I said, third one looks good, BUT (:D) I think app logo should be bigger.

**Comment by scriptfx** [comment]
I'm not a designer, but I think that dividing the current logo in two parts (wings) with two similar color is enough.
See Microsoft ToDo logo as reference [here](https://to-do-cdn.microsoft.com/webapp/c87265a87f887380a04cf21925a56539b29364b51ae53e089c3ee2b2180148c6/logo.png) or the '>' in Windows Terminal logo [here](https://en.wikipedia.org/wiki/Windows_Terminal#/media/File:Windows_Terminal_Logo_256x256.png).

**Comment by widersky** [comment]
My proposal:

![newicon_alone](https://user-images.githubusercontent.com/45122321/72322518-d426b900-36a6-11ea-91eb-03762e1996e3.png)
![newicon](https://user-images.githubusercontent.com/45122321/72322526-d6891300-36a6-11ea-8f4b-42089e3b2d94.png)

**Comment by MarcAnt01** [comment]
> My proposal:
> 
> ![newicon_alone](https://user-images.githubusercontent.com/45122321/72322518-d426b900-36a6-11ea-91eb-03762e1996e3.png)
> ![newicon](https://user-images.githubusercontent.com/45122321/72322526-d6891300-36a6-11ea-8f4b-42089e3b2d94.png)

I like it, how would it look with dark taskbar?

**Comment by widersky** [comment]
@MarcAnt01 
![newicondark](https://user-images.githubusercontent.com/45122321/72327573-aabf5a80-36b1-11ea-990e-3e5321f847c1.png)

**Comment by MarcAnt01** [comment]
> @MarcAnt01
> ![newicondark](https://user-images.githubusercontent.com/45122321/72327573-aabf5a80-36b1-11ea-990e-3e5321f847c1.png)

Thanks, I like the icon. Anyway, most of Microsoft apps still have a monochrome color. I don't know if it worths to change it

**Comment by widersky** [comment]
@MarcAnt01

It worths, many new system/apps icons are on the way: https://medium.com/microsoft-design/the-ripple-effect-expanding-our-icon-design-system-74b4d916b7a4

**Comment by nor0x** [comment]
Hi folks 👋
i would also share my idea for a fluent icon for unigram. i tried separating the logo into various parts ( [@scriptfx)](https://github.com/UnigramDev/Unigram/issues/1221#issuecomment-565102329) and added some fluent design elements and the original telegram gradient to it.

![unigram_fluent](https://user-images.githubusercontent.com/3210391/75670014-4a45a600-5c7c-11ea-943d-f4be8fc48e16.png)

![IMG_18sdf85](https://user-images.githubusercontent.com/3210391/75672369-ec678d00-5c80-11ea-8d46-33b474e86608.jpg)

let me know what you think, i'm happy to share my design assets

**Comment by FrayxRulez** [comment]
Hi @nor0x! I actually like the icon, but I'm not a big fan of this part:
![image](https://user-images.githubusercontent.com/8152849/75674060-972d7a80-5c84-11ea-81e5-2b89857ec739.png)

Did you try to design a plated version as well? (So with a blue ellipse as a background for the white plane)

**Comment by nor0x** [comment]
Hi @FrayxRulez thanks for the reply! Here are some plated versions - but i will look into the overlapping part of the plane again

![Unigram_Icon2](https://user-images.githubusercontent.com/3210391/75682195-4a9e6b00-5c95-11ea-8669-7db2aab9705e.png)
![Unigram_Icon3](https://user-images.githubusercontent.com/3210391/75682197-4b370180-5c95-11ea-8a12-cd7de940c8a0.png)
![Unigram_Icon4](https://user-images.githubusercontent.com/3210391/75682198-4bcf9800-5c95-11ea-93c9-74081f589aa6.png)

**Comment by SOI7** [comment]
> Hi folks 👋
> i would also share my idea for a fluent icon for unigram. i tried separating the logo into various parts ( [@scriptfx)](https://github.com/UnigramDev/Unigram/issues/1221#issuecomment-565102329) and added some fluent design elements and the original telegram gradient to it.
> 
> ![unigram_fluent](https://user-images.githubusercontent.com/3210391/75670014-4a45a600-5c7c-11ea-943d-f4be8fc48e16.png)
> 
> ![IMG_18sdf85](https://user-images.githubusercontent.com/3210391/75672369-ec678d00-5c80-11ea-8d46-33b474e86608.jpg)
> 
> let me know what you think, i'm happy to share my design assets

I like where this is going. I kinda prefer the icon without the circle (especially since the circle is used by the actual Telegram app and it would be better to differentiate them). The only thing that bugs me is that little white triangle, could you try making the lower blue "wing" fill that space, so that the icon is composed of just two overlapping blue wings that form the current logo?

**Comment by nor0x** [comment]
> I like where this is going. I kinda prefer the icon without the circle (especially since the circle is used by the actual Telegram app and it would be better to differentiate them). The only thing that bugs me is that little white triangle, could you try making the lower blue "wing" fill that space, so that the icon is composed of just two overlapping blue wings that form the current logo?

Hi all, thanks for the feedback. Here is a version without the white triangle thingy

![Unigram_Icon](https://user-images.githubusercontent.com/3210391/78648903-f6eaf700-78bc-11ea-8f72-bb4b91d4bd5d.png)

**Comment by MarcAnt01** [comment]
> > I like where this is going. I kinda prefer the icon without the circle (especially since the circle is used by the actual Telegram app and it would be better to differentiate them). The only thing that bugs me is that little white triangle, could you try making the lower blue "wing" fill that space, so that the icon is composed of just two overlapping blue wings that form the current logo?
> 
> Hi all, thanks for the feedback. Here is a version without the white triangle thingy
> 
> ![Unigram_Icon](https://user-images.githubusercontent.com/3210391/78648903-f6eaf700-78bc-11ea-8f72-bb4b91d4bd5d.png)

I love this one, I just prefer the color to be uniform without this line in the middle.
![image](https://user-images.githubusercontent.com/43090263/78649345-98724880-78bd-11ea-9072-0f2332a80f22.png)

**Comment by nor0x** [comment]
> I love this one, I just prefer the color to be uniform without this line in the middle.
> ![image](https://user-images.githubusercontent.com/43090263/78649345-98724880-78bd-11ea-9072-0f2332a80f22.png)

thanks for your feedback - here is a version without the overlap. I created the overlapping wings because most icons in the Fluent Design system consist of two or more different parts which are most of the time separated with shadows
![Unigram_Icon](https://user-images.githubusercontent.com/3210391/78657327-e771ab00-78c8-11ea-8cde-1bd4c70af5f2.png)

**Comment by widersky** [comment]
Looking great :)

**Comment by MarcAnt01** [comment]
@nor0x can you send the SVG to me at t.me/MarcAnt01 ?

**Comment by FrayxRulez** [comment]
So that's it:
![image](https://user-images.githubusercontent.com/8152849/82153966-091c6580-986b-11ea-85bc-fec170b8a371.png)
