### ISSUE TITLE
Altered Auto-download data limits not stored

### ISSUE THREAD

**Issue by Christoph142** [UnigramDev/Unigram#1223]
1. Go to settings > Data and Storage
1. Tick "Auto-Download Media"
1. Go to "Videos" or "Files"
1. Change the "Maximum file size" limit
1. Go back to settings > Data and Storage

**Result:** Back to default

**Comment by FrayxRulez** [comment]
You must press the tick button on top right corner

**Comment by Christoph142** [comment]
Oh. Sorry. I entirely missed this button.
Probably because it's inconsistent to all other sections where change is applied the way I tried.
Is this button really necessary / justified?
If it's only there because of the slider, a reset button next to it would save the same purpose without breaking consistency...

**Comment by Christoph142** [comment]
@Christoph142 Since I joined in here, we can also continue the discussion here if you want to... 😉

**Comment by FrayxRulez** [comment]
Most of the settings have the confirmation tick, so I'm not sure about what to do...
