### ISSUE TITLE
reconnect after restore from hibernation

### ISSUE THREAD

**Issue by GottZ** [UnigramDev/Unigram#1225]
unigram does not reconnect to telegram in case the pc wakes up from hibernation and stays in "Connecting" state

workaround:
restart unigram

Unigram 3.11.2588 from Microsoft Store on Windows 10 Pro

**Comment by FrayxRulez** [comment]
👋 sorry, I completely ignored this ticket.
I'm not sure about how I could handle this issue.

**Comment by matze19999** [comment]
Same problem here on surface pro x. If you wait about 1-2 minutes, it will connect.

**Comment by FrayxRulez** [comment]
> Same problem here on surface pro x. If you wait about 1-2 minutes, it will connect.

What if you try to unfocus and focus the app again?

**Comment by matze19999** [comment]
Doesn't change anything unfortunately

**Comment by FrayxRulez** [comment]
Can you tell me the exact steps to reproduce the issue? I'm not familiar with laptops 😅

**Comment by MarcAnt01** [comment]
Use your PC until the battery is totally discharged and turns off

**Comment by cewbdex** [comment]
> Use your PC until the battery is totally discharged and turns off

I think it is better to hibernate PC manually, as you can do it unlimited times you want and when you want.

**Comment by GottZ** [comment]
just use sleep / hibernate. after your pc wakes back up, unigram becomes useless

**Comment by GottZ** [comment]
great fix. sadly i'm not on windows anymore.
