### ISSUE TITLE
Unigram ignores system spell check options

### ISSUE THREAD

**Issue by Wanny** [UnigramDev/Unigram#1226]
I have "Autocorrect misspelled words" and "Highlight misspelled words" disabled in the Windows settings... and Unigram seems to completely ignore them. 
It still corrects some words and highlights everything (I chat in Spanish and English).

I'm using Unigram 3.11.2588

**Comment by FrayxRulez** [comment]
You must close and reopen any UWP app to apply system spell check settings

**Comment by Wanny** [comment]
I've done it lots of times and the problem persists.
I changed those settings MONTHS ago and Unigram recognized the change back then.

But now after updating, it just ignores them.

**Comment by FrayxRulez** [comment]
I'm not able to reproduce the issue to be honest, might something on your side, or might be related to the recent update to Microsoft.UI.Xaml 2.2...

**Comment by Wanny** [comment]
Most possibly. I'm using Windows 10 1903 (build 18362.418)

**Comment by FrayxRulez** [comment]
Because there's no API to control the Spell Check system, but they might have broken something in the text boxes style.

Still I'm not able to reproduce the issue (I keep spell checking turned off)

**Comment by unpollito** [comment]
Hi,

I've been having this issue as well. I think I must have been using Unigram for 4-5 months already, so it's been there for quite a while.

**Comment by FrayxRulez** [comment]
I just replied to another ticket that this should be handled by default by Windows: https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/text-controls#guidelines-for-spell-checking

I'm not even sure there's a way to override this behavior and I'm pretty sure there's no way to check if the spell checker is disabled.

**Comment by MarcAnt01** [comment]
With this combo Unigram starts to auto-correct words
![image](https://user-images.githubusercontent.com/43090263/80719926-78b8f380-8afc-11ea-80ed-122ce14bd586.png)

**Comment by MarcAnt01** [comment]
The option to highlight misspelled words appears both if it is on and off

**Comment by FrayxRulez** [comment]
I will implement an option in the app to actually disable spell check.

**Comment by Sominemo** [comment]
@MarcAnt01 Tgis

**Comment by FrayxRulez** [comment]
🕺
