### ISSUE TITLE
Privacy settings do not sync between different clients

### ISSUE THREAD

**Issue by strollingHeifer** [UnigramDev/Unigram#1231]
The settings under the 'privacy' tab are not in sync with other Telegram clients. When installing Unigram, the permissions about who can call me, see my number or profil picture etc. are set to 'nobody' by default, even though that is not what they are set to on my other Telegram clients. Changing them also does affect the setting on the other clients on Android and iOS as it should.

This causes confusion because it remains unclear to what each setting is actually set to.

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/a1fd99e364c11c48b46fa3abc19c13fa8333bef2
