### ISSUE TITLE
Unhandled Exception with animated stickers

### ISSUE THREAD

**Issue by scriptfx** [UnigramDev/Unigram#1233]
Opening a chat with animated stickers (also not in the visible part of the view) throws exceptions.

![immagine](https://user-images.githubusercontent.com/35109437/68840539-3709cd00-06c3-11ea-9255-a71c72a0f5f6.png)

**Comment by FrayxRulez** [comment]
Can you update the app to 3.12.2621?

**Comment by scriptfx** [comment]
Ok. Microsoft store didn't show me the update. Now it has appeared and I updated Unigram. Issue resolved. Thanks
