### ISSUE TITLE
Contact sync not working after initial install

### ISSUE THREAD

**Issue by tastyeggs** [UnigramDev/Unigram#1237]
On first use, Unigram imported all my contacts into the People app. Since then, I've cleaned up my contact list (deleted a few, nicely asked some of my contacts to add a picture). However these changes aren't showing up in the People app.

Is it possible to force a sync?

**Comment by FrayxRulez** [comment]
Yes, it is possible from Settings > Privacy and Security.
Disabling and re-enabling contacts sync would do the trick.
