### ISSUE TITLE
Problem when installing Unigram... (but not really an issue with the app)

### ISSUE THREAD

**Issue by Fuchur84** [UnigramDev/Unigram#1240]
I run into a strange/bad problem which might not be a real problem of Unigram, but I just do not know what to do or how to get rid of that problem:

1.) I installed Unigram on my Lumia 950 XL's internal drive and it worked great (really love it!). 
2.) I moved it to my SD card after that – still worked as it should.
3.) My SD card got bad and died.
4.) I got my SD card out to use the WOA-Deployer (Windows On Arm Dual Boot Deployer) and installed Windows 10 ARM in addition to Windows 10 Mobile. (worked)
5.) I got a new SD card and have put it into my smartphone.
6.) Tried to reinstalled Unigram afterwards now but it always throws an error. (specificly 0x80242020)
7.) To fix it I tried to uninstall it fully. That worked (kind of) because it is no longer in my All Apps List, but when I have a look at Settings > Apps it still it there.
8.) Tried to install it on my internal drive again (changing the new app target), but did not work. (same error)

Now I am stuck. I think what happened there is the following: When my SD card was removed while Windows 10 ARM was installed, the installer created new drives/partitions and one of those has now the same drive letter when booting into Windows 10 Mobile like my SD card had (pretty sure it was D:/). My new SD card has now the driveletter F:/.

Maybe somebody knows if there is a way to really fully uninstall Unigram (for instance with Mass Storage Mode by WPInternals) or anything like that? Or maybe change the drive letter in the "registery" (not sure if it is the same for Windows 10 Mobile)?

Does anybody have an idea what I could do? I could try to fork Unigram and change the name of it to Unigram2 or something, but first of I would need to find out how to do that and I would of cause not get the updates then... I could do it, but if there is another way of one of you wizards here, I'd really like to do try that first.

Thank you very much for any clue, help or advise in advance. 
It would be highly appreciated :).

**Comment by FrayxRulez** [comment]
I absolutely have no clue about this (Not using a Windows Mobile device since 2015) and Windows Mobile isn't supported by Unigram anymore...
