### ISSUE TITLE
Is recording/ is playing game animation stops when leaving a chat and reopening it

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1242]
Is typing animation is OK

**Comment by FrayxRulez** [comment]
I don't understand

**Comment by MarcAnt01** [comment]
If I open a chat and the other person is recording a message it is all right, during the message recording I switch to another chat and then go back, the animation is not working

**Comment by FrayxRulez** [comment]
Explain "not working"

**Comment by MarcAnt01** [comment]
OK, after some investigation I noticed that:
- The animation gets stuck in the last frame that is played before leaving the chat;
- After waiting a bit (20/30 secs) the animation gets back to normal (I guess it's played again since the beginning)

**Comment by MarcAnt01** [comment]
That's fixed
