### ISSUE TITLE
Wrong focus and missing enter input in passcode lock section

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1247]
- [x] Focus in on OK and not on input field
![image](https://user-images.githubusercontent.com/43090263/69811553-94873900-11ee-11ea-9da6-35c400395651.png)
- [ ] Enter does nothing while typing instead of selecting the OK confirmation

**Comment by FireCubeStudios** [comment]
looking into it

**Comment by MarcAnt01** [comment]
Focus has been somehow fixed

**Comment by MarcAnt01** [comment]
> Focus has been fixed somehow

**Comment by FireCubeStudios** [comment]
ok good
