### ISSUE TITLE
Minor issues of two-steps verification section

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1248]
- [ ] Input area isn't focused;
- [ ] The UI of the section is pretty ugly;
- [ ] Pressing enter does nothing instead of confirming
- [ ] Non-working back button
![image](https://user-images.githubusercontent.com/43090263/69811873-58a0a380-11ef-11ea-84a1-1e5ffdb02fe2.png)

**Comment by FrayxRulez** [comment]
Closing this in favor of #2418
