### ISSUE TITLE
Cannot see Sticker

### ISSUE THREAD

**Issue by KazamaSion** [UnigramDev/Unigram#1252]
![](https://i.loli.net/2019/12/01/bVFGo6NiQquU43x.png)
![](https://i.loli.net/2019/12/01/4pOucweJzMdWabI.png)
![](https://i.loli.net/2019/12/01/VQ2q6pwDgNvaXGc.png)

Windows 10 1809(OS Build 17763.864) LTSC

Already confirmed that there's nothing wrong with the network.
BTW, pic msg is okay.

**Comment by MarcAnt01** [comment]
Duplicate of https://github.com/UnigramDev/Unigram/issues/1105
