### ISSUE TITLE
'Launch minimized' option is not working

### ISSUE THREAD

**Issue by m-a-orlowski** [UnigramDev/Unigram#1253]
If I enable the 'launch minimized' switch in advanced settings, it reverts to disabled after restarting Unigram.

**Comment by MarcAnt01** [comment]
What is your version?
I cannot see it here
![image](https://user-images.githubusercontent.com/43090263/69964802-5bfb9e00-1513-11ea-895c-f9fec99721b8.png)

**Comment by m-a-orlowski** [comment]
Ah yes, forgot to say you have to enable 'Launch Unigram when system starts' for it to show up.

**Comment by MarcAnt01** [comment]
@m-a-orlowski Unigram cannot run minimised at the moment, due to bugged Microsoft tools that don't allow to ship the Win32 process like before

**Comment by MarcAnt01** [comment]
You might want to follow the progress of that in this ticket https://github.com/UnigramDev/Unigram/issues/1214

**Comment by rfgamaral** [comment]
> 
> 
> You might want to follow the progress of that in this ticket #1214

That issue seems to have been fixed itself, but this one still doesn't work... There's till nothing that can be done about it?

**Comment by MarcAnt01** [comment]
Fixed now

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/8f1b9e6a811f90aa16341f12e7bd2b3d2e49f13e
