### ISSUE TITLE
Play voice messages over telephone-call-speaker

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#126]
Voice messages should be played over the small speaker for calls, when the phone is hold to the ear. Probably one of the most important features when using voice messages :)

**Comment by FrayxRulez** [comment]
Voice messages playback should be moved from `AudioGraph` to `MediaPlayer`

**Comment by ariel-** [comment]
This was working on the last alpha version, and was broken when I did the update to 0.13.1144 through the store

**Comment by FrayxRulez** [comment]
I'm closing this as this is most likely never going to happen:
- UWP APIs to switch between speakerphone and earpiece don't even exist, using Windows Phone APIs would be needed.
- UWP `MediaPlayer` behaves quite in a weird way when using the previously mentioned APIs.
- Using `Communication` audio category on PC is out of discussion as PCs tends to have different peripherals for this and people would most likely end up with "I can't hear" issues. And this would be required to be able to use previously mentioned APIs.
- I don't even have a Windows Phone device to try to implement this feature.
