### ISSUE TITLE
Last posted animated sticker doesn't automatically plays

### ISSUE THREAD

**Issue by Luminarcy** [UnigramDev/Unigram#1260]
But previous one starts playing if new posted. Also all emojis start playing after changing chat and on app minimizing and maximizing.

![ApplicationFrameHost_7ZVAoHEoRV](https://user-images.githubusercontent.com/42573485/70613582-f21d7b80-1c19-11ea-8013-e2fcd3e63302.png)

**Comment by CornyjK** [comment]
I have a different scenario, the first animated sticker/dice/dart does not play, the others do, also this happens only sometimes, not always, not sure how to reproduce.

![image](https://user-images.githubusercontent.com/9021297/80343603-7b022000-8866-11ea-8c84-c6fc3016cc42.png)

Image 1: The first sticker does not play, the others do.

**Comment by FrayxRulez** [comment]
I think I fixed this one...

**Comment by MarcAnt01** [comment]
Yes, stopped happening along with the bug of dices and darts
