### ISSUE TITLE
Can't upload image

### ISSUE THREAD

**Issue by Luminarcy** [UnigramDev/Unigram#1261]
Send button does nothing

![ApplicationFrameHost_omRR0w87xQ](https://user-images.githubusercontent.com/42573485/70617565-f0f04c80-1c21-11ea-839d-c29ab943115a.png)

![ApplicationFrameHost_jN0CMmBfNJ](https://user-images.githubusercontent.com/42573485/70617571-f5b50080-1c21-11ea-8c1d-adcea3453bb8.png)

**Comment by sprainbrains** [comment]
Agree. I have the same problem.
Win 10 1909 
Unigram build 3.13.2635

**Comment by DarthJahus** [comment]
@sprainbrains Yes, same.
Windows 10 19027.1
Unigram 3.13.2635

**Comment by yuezhengbaizhi** [comment]
Having the same problem on my 950xl with unigram 3.13.2635 and 10.0.15254.600

**Comment by shemadolev** [comment]
Seems it doesn't work for videos or GIFs either.
(Which is ironic, because I've figured it out while trying to send a screenshot of Unigram to recommend it to my friends...)

**Comment by pztrn** [comment]
3.13.2636.0 just arrived to me via Microsoft Store, issue is fixed, I can upload images now.
