### ISSUE TITLE
Unhandled exception with Windows Hello login

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1262]
![image](https://user-images.githubusercontent.com/43090263/70624906-97881d80-1c21-11ea-873d-ce25ffc56d80.png)

Happened only once

**Comment by FrayxRulez** [comment]
That's your device fault

**Comment by MarcAnt01** [comment]
@FrayxRulez what does that mean?

**Comment by FrayxRulez** [comment]
Probably you should try to reboot or google for the error message

**Comment by MarcAnt01** [comment]
> Probably you should try to reboot or google for the error message

Closed the app and reopened and works fine
