### ISSUE TITLE
Crashed on privacy settings

### ISSUE THREAD

**Issue by hooddy** [UnigramDev/Unigram#1263]
Latest 3.13.2635 build is crashed on any Allow/Always share etc menu items in privacy settings.

**Comment by Tourniquet88** [comment]
Yep, can confirm.

**Comment by hooddy** [comment]
On today release it still present.

**Comment by Tourniquet88** [comment]
Yep, can confirm 💃

**Comment by MarcAnt01** [comment]
I cannot reproduce that with latest version

**Comment by FrayxRulez** [comment]
Fixed
