### ISSUE TITLE
Dark blue theme is reset to dark theme after every update

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1266]

**Comment by FrayxRulez** [comment]
This only happens if theme is Dark blue

**Comment by revanmj** [comment]
Same thing happens for me.

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/a6c69b6983c7d8e3c16b94b53964e0be2dc237cc
