### ISSUE TITLE
Attaching image from clipboard is not working

### ISSUE THREAD

**Issue by saltukkos** [UnigramDev/Unigram#1267]
After update to the 3.13.2635, Images, pasted from the clipboard (and the same way from "Share" via People App) are shown in the application (this window, which allows you to crop/add a caption and other), but after clicking Send button nothing happens, it just disappears.
I also tried to reset the application using windows settings, it didn't help.

**Comment by saltukkos** [comment]
Oh, okay, looks like it was fixed in 6861a405045e5abd165a2cbd609366af4094cd9d
When will it be released? It's really hard to use the current version from windows store.

**Comment by FrayxRulez** [comment]
Was released already; check for updates.
