### ISSUE TITLE
Chats list is empty when trying to share something through the app

### ISSUE THREAD

**Issue by javiergualix** [UnigramDev/Unigram#1270]
When the app is closed and you try to share something from another app using Unigram, the chat list is empty and cannot choose the chat where I would like to send it.
![image](https://user-images.githubusercontent.com/36969030/71311970-089bb200-2426-11ea-8930-a9741d259e44.png)

The GIF below shows the steps to repro the bug.
![Bug-Unigram-Share-2](https://user-images.githubusercontent.com/36969030/71312060-1271e500-2427-11ea-97e4-a463e5c301d3.gif)

**Comment by MarcAnt01** [comment]
Same here and it seems to break Windows Hello login, too

**Comment by FrayxRulez** [comment]
I think I fixed this one 👌
