### ISSUE TITLE
height of build in keyboard reduce

### ISSUE THREAD

**Issue by Eweol** [UnigramDev/Unigram#128]
Every time i push a key on build in keyboard the height of complete keyboard reduce to half.
![wp_ss_20170108_0001](https://cloud.githubusercontent.com/assets/22490016/21748523/5e8c0822-d587-11e6-9cb3-82c6cb80402e.png)
![wp_ss_20170108_0002](https://cloud.githubusercontent.com/assets/22490016/21748524/5e90e130-d587-11e6-88a5-5644964ac220.png)
![wp_ss_20170108_0003](https://cloud.githubusercontent.com/assets/22490016/21748525/5e928ada-d587-11e6-99a2-d74bd90fb7d5.png)

**Comment by FrayxRulez** [comment]
Ok, I know where's the problem, I'll fix asap :)

**Comment by Eweol** [comment]
@FrayxRulez OK thank you
