### ISSUE TITLE
Chat flyout menus dark theme issue

### ISSUE THREAD

**Issue by kryvyifedir** [UnigramDev/Unigram#1282]
When dark theme is switched on in OS settings - this is how context menu looks like in chat
![image](https://user-images.githubusercontent.com/23722132/71543701-c3740480-297e-11ea-9255-8182453e7b49.png)

**Comment by pizzapie** [comment]
This is occurring for me for _any_ theme selection other than Light. The menus display correctly immediately after switching to and from Light, but revert to white boxes when hovering the mouse cursor over them.

**Comment by FrayxRulez** [comment]
Fixed in 3.13.2647
