### ISSUE TITLE
Search bar Unigram crashes

### ISSUE THREAD

**Issue by DankDoggos** [UnigramDev/Unigram#1285]
Searching "fantasia" in the search bar, Unigram will crash.

**Comment by morenj96** [comment]
@DankDoggos I just tested it, no weird behavior

**Comment by DankDoggos** [comment]
it crashes for me

**Comment by morenj96** [comment]
@DankDoggos Resetting the app may make it better

**Comment by morenj96** [comment]
@DankDoggos Do not reset!

**Comment by MarcAnt01** [comment]
Yeah, I can reproduce

**Comment by MarcAnt01** [comment]
@morenj96 what version are you running? I have 3.13.4645

**Comment by FrayxRulez** [comment]
Can't reproduce either. Highly depends on your search results.

**Comment by MarcAnt01** [comment]
I'm shown these results on my iPhone
![image](https://user-images.githubusercontent.com/43090263/71576991-ba0ba900-2af2-11ea-9d68-517b32db025e.png)

**Comment by MarcAnt01** [comment]
For me it stopped happening with 3.13.2647

**Comment by MarcAnt01** [comment]
@DankDoggos tell me if you still can reproduce with this version, in case I'll reopen it

**Comment by DankDoggos** [comment]
3.13.2645
