### ISSUE TITLE
App crashes when "like" work is typed into search box

### ISSUE THREAD

**Issue by xperiandri** [UnigramDev/Unigram#1288]
If you type "like" or anything else and then prepend with "like", the app hangs and crashes

**Comment by FrayxRulez** [comment]
I'm not able to reproduce the issue

**Comment by MarcAnt01** [comment]
Can you try to update Unigram? With latest version a similar crash in search box does no longer happen

**Comment by xperiandri** [comment]
Indeed, fixed in 3.13.2647
