### ISSUE TITLE
add fingerprint support for app start

### ISSUE THREAD

**Issue by behroozbc** [UnigramDev/Unigram#1290]
hi 
please add fingerprint scan to passlock 
in my andriod phone i this feature 
i use windows pc

**Comment by githubcatw** [comment]
@behroozbc if your PC has a fingerprint sensor you can register it with Windows Hello and use it

**Comment by behroozbc** [comment]
i want scan my finger print when i open app like passlock
where i can active 
![image](https://user-images.githubusercontent.com/20381616/71769170-c351a700-2f32-11ea-8f40-1921ba2c2279.png)

**Comment by githubcatw** [comment]
> i want scan my finger print when i open app like passlock
> where i can active
> ![image](https://user-images.githubusercontent.com/20381616/71769170-c351a700-2f32-11ea-8f40-1921ba2c2279.png)

If your PC doesn't have fingerprint lock then you can't

**Comment by behroozbc** [comment]
> > i want scan my finger print when i open app like passlock
> > where i can active
> > ![image](https://user-images.githubusercontent.com/20381616/71769170-c351a700-2f32-11ea-8f40-1921ba2c2279.png)
> 
> If your PC doesn't have fingerprint lock then you can't

my pc have fingerprint

**Comment by githubcatw** [comment]
@behroozbc Set it up in windows hello

**Comment by githubcatw** [comment]
@behroozbc In windows settings

**Comment by behroozbc** [comment]
i done that

**Comment by behroozbc** [comment]
but i can see fingerprint in my unigram

**Comment by behroozbc** [comment]
i cant see

**Comment by nahuelwexd** [comment]
@behroozbc Set your fingerprint in Windows settings and then enable passcode lock in Unigram
