### ISSUE TITLE
voice icon is stuck 

### ISSUE THREAD

**Issue by behroozbc** [UnigramDev/Unigram#1291]
hi 
![image](https://user-images.githubusercontent.com/20381616/71837425-a3a1b680-30cb-11ea-9f21-9e733e363be8.png)
i record voice and before and a press esc button than i come back i saw that

**Comment by MarcAnt01** [comment]
Does that happen only with the chat open in a new windows?

**Comment by behroozbc** [comment]
NO

**Comment by FrayxRulez** [comment]
I'm not able to reproduce the issue so I'm considering this fixed

**Comment by behroozbc** [comment]
@FrayxRulez  Hi in new version I cant reproduce ,too , i thought this fixed
