### ISSUE TITLE
Badging on Taskbar icon?

### ISSUE THREAD

**Issue by pettijohn** [UnigramDev/Unigram#1293]
Hello, thanks for this great Telegram client, I am enjoying it so far.

Is the taskbar icon supposed to show an unread message count badge? It looks like yes? https://github.com/UnigramDev/Unigram/blob/76363f288396824956cac6979c49ce2058837ae5/Unigram/Unigram.Native.Tasks/NotificationTask.cpp#L403 

I am not seeing it. I have verified that Windows setting "show badges on taskbar buttons" is enabled and can't figure out if there is another setting I need to enable. App is up-to-date from Windows 10 store. 

The live tile on Start menu does show unread badges, so maybe that's what the referenced code is controlling? 

Thanks!

**Comment by pettijohn** [comment]
Never mind, I rebooted and it's working. ¯\_(ツ)_/¯

**Comment by FrayxRulez** [comment]
![](https://cdn-www.konbini.com/en/files/2018/03/spongebob.jpg)
