### ISSUE TITLE
Rotate media within gallery

### ISSUE THREAD

**Issue by valsydalv** [UnigramDev/Unigram#1296]
Hi!
I'd would be great to rotate a photo while viewing it inside the app. As currently I need either to rotate my head, screen or to save all the photos and videos sent to me and open in another viewer.

**Comment by MarcAnt01** [comment]
This feature isn't in official guidelines

**Comment by valsydalv** [comment]
OK, then adding for history this issue and hope for any progress: https://github.com/telegramdesktop/tdesktop/issues/1413

**Comment by MarcAnt01** [comment]
Would be nice to have it, but mobile apps lack it, too, so is not likely to be added to Unigram

**Comment by FrayxRulez** [comment]
Not sure about tdesktop but macOS has this feature.

**Comment by MarcAnt01** [comment]
> Not sure about tdesktop but macOS has this feature.

Good to know, would be nice to have it then

**Comment by MarcAnt01** [comment]
Looks like Telegram Desktop supports that now https://github.com/telegramdesktop/tdesktop/commit/4544b091a0722190f5aa21a1e01ff5df5b435bcf

**Comment by FrayxRulez** [comment]
Implemented
