### ISSUE TITLE
Features: list "AppContainer" permission as security feature

### ISSUE THREAD

**Issue by beerisgood** [UnigramDev/Unigram#1297]
It's nice to see that this app run with enabled [AppContainer](https://docs.microsoft.com/en-us/windows/win32/secauthz/appcontainer-isolation) permission - not like the official Telegram WindowStore app.

I guess it would be interesting for security related guys to know that, cause that's (sadly) no default for nowadays WindowsStore apps.
![processexplorer](https://user-images.githubusercontent.com/9625159/72532235-f23d1680-386a-11ea-9334-3151801b480f.jpg)
(checkable with Process Explorer from Microsoft)

**Comment by MarcAnt01** [comment]
That's how uwp works, Telegram Desktop isn't uwp

**Comment by beerisgood** [comment]
I don't mean the desktop client, i mean this: https://www.microsoft.com/en-us/p/telegram-desktop/9nztwsqntd0s?activetab=pivot:overviewtab

But okay, that explain it. Anyway i would still list that as feature. Maybe as "UWP" then or as "UWP / AppContainer"

**Comment by MarcAnt01** [comment]
> I don't mean the desktop client, i mean this: https://www.microsoft.com/en-us/p/telegram-desktop/9nztwsqntd0s?activetab=pivot:overviewtab
> 
> But okay, that explain it. Anyway i would still list that as feature. Maybe as "UWP" then or as "UWP / AppContainer"

It’s the same as Telegram Desktop downloaded through installer, the only difference is that it uses Microsoft Store for updates.

**Comment by beerisgood** [comment]
Ah thanks. Didn't know this.
Sadly the Store doesn't show any info if the app is a UWP one or not.

**Comment by MarcAnt01** [comment]
> Ah thanks. Didn't know this.
> Sadly the Store doesn't show any info if the app is a UWP one or not.

Yeah, the store has become a place where to put apps that can be easily installed from the web and they don't highlight uwp, despite being the place were it was supposed to be present.

**Comment by MarcAnt01** [comment]
Back to your issue, atm Unigram is uwp only, but in the past it used a Win32 process through Windows Bridge that isn't sandboxed like the app, so putting that in the features list will not make sense in case it gets added again.

**Comment by beerisgood** [comment]
Why you should implement that again?
The UWP app works great and provide better security then official Telegram client.

But i get your points to not list this as feature

**Comment by MarcAnt01** [comment]
> Why you should implement that again?
> The UWP app works great and provide better security then official Telegram client.
> 
> But i get your points to not list this as feature

It's handy to close the app and not receive notifications at all, moreover it allows in-app notifications to be received in background

**Comment by beerisgood** [comment]
Well closing a program means that it's closed. So it work as intended.

If users doesn't want that, they need to minimize it. Please don't change that

**Comment by MarcAnt01** [comment]
> Well closing a program means that it's closed. So it work as intended.
> 
> If users doesn't want that, they need to minimize it. Please don't change that

No offense, but saying that you show to have no clue about uwp. Uwp programs can’t be minimised, they just get closed and receive notifications through a background process (just push notifications)

**Comment by beerisgood** [comment]
What? Can't confirm this.
If I minimize Unigram, it get minimized to superbar and I get notifications.
Works perfectly.

It only close if I click on close button. Works as intended

**Comment by MarcAnt01** [comment]
Yes, but they are push notifications and can’t be disabled

**Comment by beerisgood** [comment]
With push you mean the Windows internal notifications? They can be configured in Windows itself and disabled for individual apps

**Comment by MarcAnt01** [comment]
> With push you mean the Windows internal notifications? They can be configured in Windows itself and disabled for individual apps

No, just Google them to understand their purpose.
