### ISSUE TITLE
Use new telegram intro

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1300]
It would be nice to have the same intro that is present in the iOS app, that uses animation instead of static images

**Comment by Bounty780** [comment]
Could you send a video of the intro?

**Comment by MarcAnt01** [comment]
It's the one here https://github.com/UnigramDev/Telegram.Intro , but Unigram for some reasons, doesn't seem to be using it

**Comment by FrayxRulez** [comment]
It isn’t new, it’s actually really old. 
Unigram doesn’t use it because OpenGL caused a really high amount of crashes and that’s a critical part of the app.
