### ISSUE TITLE
The upper part of the background during log-in is bugged

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1302]
The bug seems to be present just in the same screen when the phone number has to be inserted.
In case it isn't clear the bug is about the color not being the same of the background in the upper part.
![image](https://user-images.githubusercontent.com/43090263/72664673-dcf9f080-3a00-11ea-8a27-979ec9ab1370.png)

**Comment by FrayxRulez** [comment]
That's intended!
