### ISSUE TITLE
Improvements for gallery zoom with mouse/keyboard

### ISSUE THREAD

**Issue by sprite-1** [UnigramDev/Unigram#1304]
Once scrolling using ctrl + or control + mouse wheel there's no way of dragging the picture both with keyboard and mouse.
Double tap to zoom is missing

**Comment by MarcAnt01** [comment]
It doesn't seem to happen in Microsoft Photos, neither

**Comment by sprite-1** [comment]
Why would usability have to rely on Microsoft Photos?

**Comment by MarcAnt01** [comment]
> Why would usability have to rely on Microsoft Photos?

Just an example of uwp app, the apps you probably refer to aren't uwp

**Comment by sprite-1** [comment]
> Just an example of uwp app, the apps you probably refer to aren't uwp

If it's hard to implement, I would settle for being able to pan around images using the mouse curosr instead which is a thing that Microsoft Photos can do

**Comment by MarcAnt01** [comment]
> > Just an example of uwp app, the apps you probably refer to aren't uwp
> 
> If it's hard to implement, I would settle for being able to pan around images using the mouse curosr instead which is a thing that Microsoft Photos can do

Yeah, with mouse it'd be a good interaction. Luckily, with a touchpad I can use the gestures flawlessly.

**Comment by sprite-1** [comment]
Yeah but I have my touchpad disabled when I have a mouse plugged in to my laptop which is probably 90% of the time that I use it

**Comment by Paclanc** [comment]
> It doesn't seem to happen in Microsoft Photos, neither

Microsoft photos can do it now.

**Comment by MarcAnt01** [comment]
I have edited the issue, so we were probably talking about something different

**Comment by FrayxRulez** [comment]
It's now possible to drag around zoomed media
