### ISSUE TITLE
windows time line 

### ISSUE THREAD

**Issue by behroozbc** [UnigramDev/Unigram#1306]
hi 
please add people and group chatted in to windows time line

**Comment by MarcAnt01** [comment]
Do you have a concept or something about how to implement that? Timeline is more a thing for browsers and tabs

**Comment by behroozbc** [comment]
visual studio 2019 photo and Microsoft store  have support 
the name of class is [UserActivity ](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.useractivities.useractivity)

**Comment by behroozbc** [comment]
i like to implement but i think i dont have i enough time

**Comment by saltukkos** [comment]
When should we add user activity?

- Opening the chat
- Receiving a message
- Writing a message

**Comment by behroozbc** [comment]
Opening the chat

**Comment by FrayxRulez** [comment]
I actually tried to add this feature when Timeline has been introduced back in 2018, but it didn't seem to work any good.

**Comment by MarcAnt01** [comment]
Windows timeline has been removed from Windows, so I think it makes sense to close this
