### ISSUE TITLE
Notifications Stopped working (3.13.2649)

### ISSUE THREAD

**Issue by Wolfrisger** [UnigramDev/Unigram#1307]
Push notifications stopped working, only the unread message count on the task bar works when unigram is opened/minimized. No notification/sound showed up no matter unigram is opened or not.
Notifications for other programs works normally.
Version : Unigram 3.13.2649
System : Windows 10 1909 / 18363.592 on a desktop PC

Tried / used the following fix/settings but nothing works:
1. Reset Unigram / Reinstall unigram 
2. Disable Focus assist (it was never used)
3. Unigram -> Settings -> Notifications and sounds -> Unticked everything and tick them back.
4. Unigram -> Settings -> Advanced -> Launch Unigram when system starts (enabled)
5. Win10 -> Settings -> System -> Notifications and actions -> Everything is enabled.
6. Same as 5 but tried to disabled and re-enable it.

**Comment by Wolfrisger** [comment]
I have tried it for my other PC with same windows 10 version but it works...and the pc I had this issue is a fresh installed windows 10. I don't know what i missed.

**Comment by MarcAnt01** [comment]
So just in-app notifications are working?

**Comment by Wolfrisger** [comment]
> 
> 
> So just in-app notifications are working?

Nope, in-app notifications didn't showing up as well (I have them enabled.)

**Comment by MarcAnt01** [comment]
Yes, but the point is that you are calling push notifications, all of the notifications while they are different things

**Comment by MarcAnt01** [comment]
Does that still happen?
