### ISSUE TITLE
Unigram contact assigned to wrong person.

### ISSUE THREAD

**Issue by mbalcerzyk** [UnigramDev/Unigram#1308]
Somehow a contact of Unigram (Person A) was assigned the name of another person from my contacts who is not a user of Unigram (Person B). The icon is from Person A, yet the name of Person B. When I write a Unigram message it goes to Person A, but having it assigned Person B by name is very confusing. In Windows 10 Contacts, Person B is listed as Unigram user which is not true. Person A, the correct one has no data on Unigram.
I have no idea how to correct such an error in the contacts.

**Comment by FrayxRulez** [comment]
I guess this is a problem in the contacts linker algorithm in Windows, as Unigram doesn't try in any way to associate your local contacts to Telegram ones (as is: your phonebook is imported to Telegram and THEN your Telegram contacts are added to your phonebook as new ones)
