### ISSUE TITLE
App scaling

### ISSUE THREAD

**Issue by rexx0520** [UnigramDev/Unigram#1311]
Does Unigram support scaling?
I'm on Windows 1909 with a system-wide 125% DPI scaling. The app is too small for me.
Does Unigram support scaling as the official one? Thanks.

**Comment by abusarimhindi** [comment]
@rexx0520

**Comment by abusarimhindi** [comment]
> Does Unigram support scaling?
> I'm on Windows 1909 with a system-wide 125% DPI scaling. The app is too small for me.
> Does Unigram support scaling as the official one? Thanks.

Go to settings >> Chat Settings >> and increase Message Text Size
![image](https://user-images.githubusercontent.com/22712698/73123523-072a5000-3fb7-11ea-8100-21293b52d332.png)

**Comment by rexx0520** [comment]
> > Does Unigram support scaling?
> > I'm on Windows 1909 with a system-wide 125% DPI scaling. The app is too small for me.
> > Does Unigram support scaling as the official one? Thanks.
> 
> Go to settings >> Chat Settings >> and increase Message Text Size
> ![image](https://user-images.githubusercontent.com/22712698/73123523-072a5000-3fb7-11ea-8100-21293b52d332.png)

The UI didn't scale as the message text does...

**Comment by entdark** [comment]
As an owner of 100% and 125% scaling monitors Unigram does scaling, and since it's done on UWP side it looks seamless and almost identical on both monitors. Probably scaling that you want is already applied and you just want it to scale even more and that's unrelated to system scaling.

**Comment by MarcAnt01** [comment]
> Does Unigram support scaling?
> I'm on Windows 1909 with a system-wide 125% DPI scaling. The app is too small for me.
> Does Unigram support scaling as the official one? Thanks.

Sure, uwp supports scaling for both the ui and the font

**Comment by FrayxRulez** [comment]
A slider for changing UI scaling from 100 to 225% has been added to Settings > Appearance.

**Comment by cavallofurioso** [comment]
> A slider for changing UI scaling from 100 to 225% has been added to Settings > Appearance.

Is not possible to implement downscaling, from example from 100% to 90% or 80%?
