### ISSUE TITLE
Version 3.14.2636 - App crash when typing emoji on Windows 10 Mobile

### ISSUE THREAD

**Issue by Alphaprot** [UnigramDev/Unigram#1312]
I am running Unigram Build 3.14.2636 on Windows 10 Mobile (Windows 10 Build 10.0.15254.603 --> Version 1709).

Whenever I try to type in an emoji, be it from the Windows 10 Mobile keyboard-emoji-set or from Unigrams own emoji-set, the app crashes instantly.

**Comment by MarcAnt01** [comment]
Unigram doesn't support Windows Mobile now
