### ISSUE TITLE
Unable to set certain background after 3.14.2659 update

### ISSUE THREAD

**Issue by entdark** [UnigramDev/Unigram#1313]
Hello.
I want to set certain background that I always had set but since the latest update it offers me something weird instead.
What background I want to set: https://i.imgur.com/qVStnTF.png
What I see inside instead: https://i.imgur.com/poi4Exr.png
The other backgrounds work fine.
Seems like it wants to apply a patterned background instead.

Additionally you also cannot select and set a background from a file - it appears as a solid black colour.

OS: Windows 10 1903 18362.535
Unigram: 3.14.2659

**Comment by FrayxRulez** [comment]
This should be fixed
