### ISSUE TITLE
Show the number of votes of a pool as a tooltip

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1316]
It would be a good improvement to see how many people voted for an option, for example here's how it's implemented in the iOS client
![image](https://user-images.githubusercontent.com/43090263/73206024-6c5e7c80-4142-11ea-9880-2d458f09b0db.png)

**Comment by FrayxRulez** [comment]
It's sufficient to hover on the percentage

**Comment by MarcAnt01** [comment]
Sure, wasn't aware it wasn't shown in that way
