### ISSUE TITLE
Aspect ratio of wallpapers in settings is off

### ISSUE THREAD

**Issue by strollingHeifer** [UnigramDev/Unigram#1319]
When previewing a new wallpaper within the settings menu, the wallpaper looks shrunk or stretched, depending on the size of the window that Unigram runs in. I'm not sure if this bug that was introduced in v3.14, but it used to work differently a couple of releases ago.
Fortunately, it is just the preview though. After choosing a wallpaper and going back to one of your chat messages, the aspect ratio of that wallpaper will be fixed, no matter what the window size is.

**Comment by FrayxRulez** [comment]
Can you attach a screenshot?

**Comment by strollingHeifer** [comment]
Hope this helps.

Ratio in Fullscreen: https://www.dropbox.com/s/1tp8x9bjw8z399f/Fullscreen%20Size.PNG?dl=0
Ratio in a smaller sized window: https://www.dropbox.com/s/mfgznb2wyyr59js/Standard%20Size.PNG?dl=0

**Comment by FrayxRulez** [comment]
After opening the wallpaper, you mean?

**Comment by strollingHeifer** [comment]
No, the actual wallpaper is fine. The aspect ratio is only off when you go into the settings to select a new one. Then the preview of the wallpaper will look like this.

**Comment by FrayxRulez** [comment]
Fixed!
