### ISSUE TITLE
gif preview not working

### ISSUE THREAD

**Issue by richdb** [UnigramDev/Unigram#132]
If using the @gif option a menu shows up where you can choose the gifs that match you search string. Only the menu not show a preview of the gif, but the string Telegram.api.TL.TLBotInlineResults. This string is repeated for every found gif. So you can choose a gif (clicking on the string) but have no idea which gif you have choosen.

**Comment by FrayxRulez** [comment]
Gifs have now static preview.
Animated one is planned for the future, and in the meanwhile I'm closing this issue
