### ISSUE TITLE
Wrong cursor over animated emojis

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1321]
![image](https://user-images.githubusercontent.com/43090263/73351492-675b1380-428f-11ea-9acd-752d09d2723f.png)

**Comment by FrayxRulez** [comment]
That's the proper cursor

**Comment by MarcAnt01** [comment]
Isn't this type of cursor for clickable elements?

**Comment by entdark** [comment]
It's clickable - once you click it starts the animation again.

**Comment by MarcAnt01** [comment]
> It's clickable - once you click it starts the animation again.

Nice, didn't know
