### ISSUE TITLE
Sometimes ESC to go back in the gallery is not working

### ISSUE THREAD

**Issue by Martinligabue** [UnigramDev/Unigram#1323]

**Comment by Martinligabue** [comment]
It seems to work sometimes, but other times it just doesn't do anything, I can only close via the left-arrow in left upper corner

**Comment by MarcAnt01** [comment]
This issue seems to happen when the focus is lost somehow, by clicking on the screen esc works again. (Hope that will be helpful for looking into that)

**Comment by FrayxRulez** [comment]
I think this is fixed!
