### ISSUE TITLE
Request access to build Unigram

### ISSUE THREAD

**Issue by almas3s** [UnigramDev/Unigram#1324]
Hi, i need to build Unigram, how i can receive libraries and dependencies (TDLIB, TONLIB ...)

> Important: At the moment some Unigram components aren't publicly available on GitHub. If you are interested in them, you can request access to them by creating a new issue or by asking in our Telegram group.

Thanks.

**Comment by FrayxRulez** [comment]
https://github.com/tdlib/td/
https://github.com/ton-blockchain/ton

**Comment by almas3s** [comment]
@FrayxRulez Thanks.
But i can't build TonLib, can you give me this dll?

**Comment by MarcAnt01** [comment]
Use the Unigram fork

**Comment by FrayxRulez** [comment]
Yep, I'm going to open a PR some day, but for now you can use https://github.com/UnigramDev/ton.
Build instructions are the same as TDLib :)

**Comment by almas3s** [comment]
@FrayxRulez After several attempts, I could not build it 😔
Please give me the TON DLL

**Comment by FrayxRulez** [comment]
TON isn’t needed to build the app, it’s ignored by the compiler

**Comment by almas3s** [comment]
@FrayxRulez I just downloaded your project (unigram) but to run it needs ton library.
You can guide me?

**Comment by FrayxRulez** [comment]
You don’t need it, even if you see the ⚠️ the app will build anyway

**Comment by almas3s** [comment]
@FrayxRulez Thankful, But I actually downloaded your project to i work with TON on .NET...
And I need that DLL Because I couldn't build it in Windows
I wanted to take it from you

**Comment by FrayxRulez** [comment]
Ahhh now I understand. Actually my TON fork isn’t up to date, but you can find it in UnigramDev organization.

**Comment by almas3s** [comment]
Yes, I have seen it. can you update that? 😅

**Comment by MarcAnt01** [comment]
> Yes, I have seen it. can you update that? 😅

Update what?

**Comment by FrayxRulez** [comment]
> Update what?

Tonlib fork
