### ISSUE TITLE
[UI] QR code page displays bad

### ISSUE THREAD

**Issue by s1q** [UnigramDev/Unigram#1328]
Version: 3.14.2670 from Windows Store.
Windows version: Windows 10 Pro (1903).
Language: Russian.
Bug: the text of login with QR code is superimposed on the phone number form on the login page.
![приветик](https://i.imgur.com/J74g2VL.png)

**Comment by FrayxRulez** [comment]
Next time you should probably mentions that this happens when you open proxy settings and you go back.

**Comment by s1q** [comment]
> Next time you should probably mention that this happens when you open proxy settings and you go back.

Ok, I'll do, but Telegram doesn't work in my country without proxy, so I was just thinking that it is not matter.

**Comment by FrayxRulez** [comment]
Fluxed
