### ISSUE TITLE
Passcode Lock Bug

### ISSUE THREAD

**Issue by vinikonov** [UnigramDev/Unigram#1329]
If Passcode Lock is enabled, then when you open a chat through a pinned contact on the taskbar, then entering the password (PIN) in the field does not work (characters are not typed). Entering a password becomes possible only after clicking on the three-dot menu. 
![Annotation 2020-02-12 142704](https://user-images.githubusercontent.com/60967813/74331061-e9752d00-4da3-11ea-907d-92bdb0af28e1.png)

**Comment by MarcAnt01** [comment]
This feature has been removed by Microsoft in 1909
