### ISSUE TITLE
Channel shows "Users" icon and seemsto allow message reply

### ISSUE THREAD

**Issue by Tabris963** [UnigramDev/Unigram#133]
As in the following screen, in Channels it seems to be possible to see who are the members of said channel. Actually it doesn't work (and as far as I know, it shouldn't)
![wp_ss_20170109_0005](https://cloud.githubusercontent.com/assets/6726440/21786369/c85d7b22-d6c3-11e6-8b36-de7da8f05e5d.png)

Also in channels, it looks like to be possible to reply to messages. As above, also this is not possible (the message is not sent)
![wp_ss_20170109_0004](https://cloud.githubusercontent.com/assets/6726440/21786370/c85ea844-d6c3-11e6-981d-f067403e7760.png)

**Comment by FrayxRulez** [comment]
Disabled ability to send messages. 
I mark this as closed since the details page should be rewritten from scratch
