### ISSUE TITLE
Error on opening profiles, settings>Stickers, replying/editing messages (W10 desktop 17134.1246/Unigram 3.14.2680)

### ISSUE THREAD

**Issue by heroje** [UnigramDev/Unigram#1330]
Unhandled exception: System.InvalidCastException: Unable to cast object of type 'EETypeRva:memaddr(Windows.UI.Composition.Compositor)' to type 'EETypeRva:memaddr'
I'd copy the entire text over if I could - I don't have a context menu to do so.

Replies: 
1. Right-click on a user PM/group message
2. Choose Reply
3. Error pops up, there is no infobox that you're now replying to a message
4a. After writing the message press send - it gets sent as a reply
4b. If the chat is switched away from, on coming back the reply state seems to still be saved, and the message appears again. Writing a message clears it, and still makes it a reply.

Editing:
1. Right-click on a message
2. Choose Edit
3. Error message appears and the text box doesn't get filled in with the contents of the msg
4. On writing and pressing send, the previously marked message gets replaced with what's written

Profile:
1. Click on a contact
2. Click on their header to go to their profile page
3. Error appears, a second time also after clicking on OK

Sticker settings:
1. Open the app's internal Settings
2. Click on Stickers and Masks
3. Error appears

![error](https://user-images.githubusercontent.com/45423203/74523685-e1d99380-4f1d-11ea-88f4-c5c15a02cace.jpg)

**Comment by mardom1** [comment]
I get the same Error when trying to open any chat, making the app unusable. Hope this gets fixed soon, as I really liked the app and used it quite extensively.

Unigram 3.14.2680
Windows 10 Enterprise Version 1803 Build 17134.1246

**Comment by FrayxRulez** [comment]
> I get the same Error when trying to open any chat, making the app unusable. Hope this gets fixed soon, as I really liked the app and used it quite extensively.

Hi @mardom1, please update to 3.14.2681

**Comment by FrayxRulez** [comment]
Hi @heroje, are you sure that this error appears in Stickers & Masks as well? The Compositor isn't being used at all, there.

**Comment by FrayxRulez** [comment]
Oh, wow, I'm a super noob. I think I found it...

**Comment by heroje** [comment]
> Hi @heroje, are you sure that this error appears in Stickers & Masks as well? The Compositor isn't being used at all, there.
Yup. Below's a screen of what happens when I click on the Sticker & Masks tab.
![unigram-error](https://user-images.githubusercontent.com/45423203/74672029-aacce180-51ac-11ea-82c2-2e3c9e83c84a.PNG)
I've installed the .2681 update, restarted the app. Don't see any difference in the rest of the cases.

**Comment by FrayxRulez** [comment]
Does the list of sticker load? Are corners of the list round?

**Comment by mardom1** [comment]
@FrayxRulez I just updated to 3.14.2681 and the Error still occurs.

**Comment by heroje** [comment]
It's hard corners as below. They are rounded on the client I have running on Insider v. 2004/build 19551
![unigram-masks-panel](https://user-images.githubusercontent.com/45423203/74673484-92aa9180-51af-11ea-911c-c8e90ddbb65c.png)

**Comment by FrayxRulez** [comment]
Seems to be a “bug” on Microsoft side. Will fix it.

**Comment by FrayxRulez** [comment]
Fixed as well 🕺
