### ISSUE TITLE
Grey titlebar with dark blue theme

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1331]
![image](https://user-images.githubusercontent.com/43090263/74593421-6b2abc00-502b-11ea-9967-b8482979bee0.png)
Started happening from: 3.14.2680

**Comment by larsschellhas** [comment]
The grey title bar is also there in the dark theme and system dark theme. However, I suppose it shouldn't be there at all, since it was eliminated for a more modern design and suits no purpose now?
![image](https://user-images.githubusercontent.com/14281234/75816969-70f7ff80-5d96-11ea-9b0f-aae043a7e44f.png)

**Comment by MarcAnt01** [comment]
> The grey title bar is also there in the dark theme and system dark theme. However, I suppose it shouldn't be there at all, since it was eliminated for a more modern design and suits no purpose now?
> ![image](https://user-images.githubusercontent.com/14281234/75816969-70f7ff80-5d96-11ea-9b0f-aae043a7e44f.png)

Agree, it should be removed. Looks ugly and inconsistent to me

**Comment by FrayxRulez** [comment]
I'm pretty sure that I fixed this recently

**Comment by MarcAnt01** [comment]
![image](https://user-images.githubusercontent.com/43090263/82081364-70f57380-96e6-11ea-9e91-cbf2f123346c.png)

Doesn't look fixed to me

**Comment by FrayxRulez** [comment]
It is!

**Comment by larsschellhas** [comment]
You wanted to get back to a solid title bar?

**Comment by FrayxRulez** [comment]
> You wanted to get back to a solid title bar?

Solid title bar isn't a thing anymore in Unigram, but blue theme was left behind

**Comment by larsschellhas** [comment]
I thought so... But I still have it?
![image](https://user-images.githubusercontent.com/14281234/83132343-8bb1ea00-a0e1-11ea-80b4-7c3b2f8067e3.png)

I'm using the store version, but I might still be in some insider ring? Not sure about that anymore :'D

I'm on Unigram 3.15.4756 according to the settings.

**Comment by FrayxRulez** [comment]
> I thought so... But I still have it?
> ![image](https://user-images.githubusercontent.com/14281234/83132343-8bb1ea00-a0e1-11ea-80b4-7c3b2f8067e3.png)
> 
> I'm using the store version, but I might still be in some insider ring? Not sure about that anymore :'D
> 
> I'm on Unigram 3.15.4756 according to the settings.

That's exactly how it is supposed to be, a titlebar, "separated" from the rest of the app, not merging anymore with the content.

**Comment by revanmj** [comment]
I'm also wondering when new Store release is going to show up since the one available now still has grey titlebar when using dark blue theme..

**Comment by larsschellhas** [comment]
Hm ok... Sad to hear that! I liked it without an actual title bar :) 
But ok - still, there is the fine line in the title bar where the chats list and the right panel meet. I understand that's fixed, but not rolled out to store, yet?

**Comment by MarcAnt01** [comment]
Just in beta channel

**Comment by revanmj** [comment]
How can you sign up to beta channel?

**Comment by MarcAnt01** [comment]
https://t.me/unigramappx
