### ISSUE TITLE
Laggy scrolling in the new chat info section

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1332]
The lags seem to be present just at the beginning of the scrolling, once the scrolling continues they disappear

**Comment by MarcAnt01** [comment]
This still happens for me

**Comment by FrayxRulez** [comment]
This isn't something I can fix

**Comment by MarcAnt01** [comment]
> This isn't something I can fix

It seems to lag while changing from these two positions
![image](https://user-images.githubusercontent.com/43090263/75255404-2bf62b00-57e2-11ea-8afd-a92a1a5e9fa9.png)
![image](https://user-images.githubusercontent.com/43090263/75255458-44fedc00-57e2-11ea-8399-fd18fb8dd2ab.png)

**Comment by MarcAnt01** [comment]
It it isn't possible to fix this lag, I would advice to keep that bar always in the center without sliding it to the left

**Comment by FrayxRulez** [comment]
As if that was the lag source

**Comment by MarcAnt01** [comment]
> As if that was the lag source

Well it just happens in that area, when I scroll further up and down it doesn't happen🤷‍♂️

**Comment by FrayxRulez** [comment]
That's because it's two nested scrollers and when you reach media part outer one gets locked to allow inner one to scroll. Works nice with mouse in my VM and this is enough for me.

**Comment by MarcAnt01** [comment]
> That's because it's two nested scrollers and when you reach media part outer one gets locked to allow inner one to scroll. Works nice with mouse in my VM and this is enough for me.

With touchpad it works badly, since I have to stop the scrolling, wait some secs and then start to scroll again. With mouse I don't have to stop, but it still lags a bit and my hardware is good.

**Comment by FrayxRulez** [comment]
It isn't lagging, it's just a glitch

**Comment by FrayxRulez** [comment]
Anyway it's useless to discuss about this, there's no way to improve it

**Comment by MarcAnt01** [comment]
Yes, I understand that, but the old ui was working properly, I just hope it is possible to find an alternative solution

**Comment by MarcAnt01** [comment]
Whatever, it stopped happening with mouse since the latest store release and with touchpad is less accentuated
