### ISSUE TITLE
Delay after opening a chat from chats list

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1333]
In the latest versions of Unigram there is a delay every time I open a chat. Some time ago that didn't use to happen.

**Comment by beerisgood** [comment]
Can confirm that.
Also sometimes posts are displayed twice

**Comment by MarcAnt01** [comment]
> Can confirm that.
> Also sometimes posts are displayed twice

This is a different bug, you’d better create another ticket to keep track of it

**Comment by MarcAnt01** [comment]
Can you confirm that it doesn't seem to be present now?
(3.14.2683)

**Comment by beerisgood** [comment]
@MarcAnt01 looks fixed

**Comment by MarcAnt01** [comment]
> @MarcAnt01 looks fixed

OK, closing it
