### ISSUE TITLE
Duplicated messages in chats

### ISSUE THREAD

**Issue by TheGuardianWolf** [UnigramDev/Unigram#1334]
Essentially there is a double up of what others have posted, which seem to be an issue when loading a chat for the first time, especially a large chat that has lots of history.

![Duplicate messages image](https://i.imgur.com/gRv1S4Y.png)

This one seems somewhat sporadic, but the below actions have a good chance of reproducing this bug.

Reproduce: 
* Follow a chat link to another chat. The specific chat link I used was the GitHub bot when I was replying to another GitHub issue in the Unigram client
* Load a large chat room

**Comment by Jamesits** [comment]
Can reproduce at Unigram 3.14.2680. There are other symptoms:

* Some message is replaced with a duplication of the message above it (this can happen at random location)
* Messages are missing or duplicated (usually happens on the latest few messages, but can happen at random location)
* Very bad scrolling performance of chat history (I have joined some 500 superchats so Unigram scrolling performace is always a problem for me, but it became worse after the most recent update.)

**Comment by MarcAnt01** [comment]
@TheGuardianWolf or anyone else, it hasn't happened any longer to me, can you confirm the same for you?

**Comment by TheGuardianWolf** [comment]
I can confirm I haven't seen any duplicates in a while, perhaps this is fixed :D

**Comment by MarcAnt01** [comment]
OK, closing then, in case it happens again, ping me so that I can open it again
