### ISSUE TITLE
Button to start chat from chat or contact page

### ISSUE THREAD

**Issue by xperiandri** [UnigramDev/Unigram#1338]
It would be extremely useful to have a button near to call button on chat screen or as an item in the menu (`...` right to the call button) to start secret chat with current contact immediately

**Comment by FrayxRulez** [comment]
I don't think it would be so useful... You can start a secret chat already from the profile page

**Comment by xperiandri** [comment]
Ah, I see

**Comment by xperiandri** [comment]
Well, maybe
2 steps vs 1 step

**Comment by FrayxRulez** [comment]
People basically don't use secret chats...

**Comment by MarcAnt01** [comment]
> People basically don't use secret chats...

Yeah, agree on that. It’s easier to send auto-destruction media
