### ISSUE TITLE
Chat window scrolled up after pasting the media

### ISSUE THREAD

**Issue by saltukkos** [UnigramDev/Unigram#1340]
It happens only in "Windows My People" windows. After pasting the media chat automatically scrolled up on one or two screens.

**Comment by saltukkos** [comment]
Oh, as written [here](https://github.com/UnigramDev/Unigram/issues/744#issuecomment-463186380), we will not develop this feature anymore.

**Comment by MarcAnt01** [comment]
> Oh, as written [here](https://github.com/UnigramDev/Unigram/issues/744#issuecomment-463186380), we will not develop this feature anymore.

Yes, I am on 1909 and I can't pin people any longer one the taskbar, even if I still can use direct share with people I previously added to the taskbar, this direct share anyway just opens the associated app.
