### ISSUE TITLE
Use a different sound for received messages and sent ones

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1346]
The iOS client has different sounds

**Comment by FrayxRulez** [comment]
![image](https://user-images.githubusercontent.com/8152849/75354800-dbe49a80-58ad-11ea-9b53-774e9208aac8.png)

**Comment by MarcAnt01** [comment]
Why? It's so confusing

**Comment by beerisgood** [comment]
Please not.
I hate sounds for s
Outgoing messages. It's so useless and annoying.

**Comment by FrayxRulez** [comment]
You can disable “In-App Sounds” from notifications settings. I know they might be annoying for you, but for some people are necessary to be able to use the app 😊

**Comment by MarcAnt01** [comment]
> Please not.
> I hate sounds for s
> Outgoing messages. It's so useless and annoying.

I agree, if Unigram isn't following what the official clients do, it's better to have an option
