### ISSUE TITLE
Sounds when receiving messages in muted chats shouldn't be played

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1347]

**Comment by FrayxRulez** [comment]
As soon as the chat is open the sound must be played.

**Comment by MarcAnt01** [comment]
> As soon as the chat is open the sound must be played.

Why must be played? If a chat is muted, it is not important for the user

**Comment by FrayxRulez** [comment]
Because the chat is open, so you're using it.

**Comment by MarcAnt01** [comment]
I understand your point of view, but with big groups (2K members) where there is a flood of messages from a lot of  users, the experience would be bad. I am not talking about small groups, where it could be acceptable.
