### ISSUE TITLE
Match tray icon style with Windows 10

### ISSUE THREAD

**Issue by rfgamaral** [UnigramDev/Unigram#1348]
Instead of having a blue circle icon with a white envelope and a red dot for notifications, what about just a white envelope and a little blue dot for new notifications?

This is how my tray looks like right now:

![image](https://user-images.githubusercontent.com/96476/75464663-6cd77680-597f-11ea-9f1d-18c72be30c91.png)

That would match the Windows 10 look and feel much better. I believe Windows is preparing to have a more "white look" for the taskbar and whatnot, so maybe a darker version of the icon I just proposed would also be needed for contrast with the white taskbar.

**Comment by MarcAnt01** [comment]
> Instead of having a blue circle icon with a white envelope and a red dot for notifications, what about just a white envelope and a little blue dot for new notifications?
> 
> This is how my tray looks like right now:
> 
> ![image](https://user-images.githubusercontent.com/96476/75464663-6cd77680-597f-11ea-9f1d-18c72be30c91.png)
> 
> That would match the Windows 10 look and feel much better. I believe Windows is preparing to have a more "white look" for the taskbar and whatnot, so maybe a darker version of the icon I just proposed would also be needed for contrast with the white taskbar.

Have you found any documentation about how to make the tray icon adaptive depending on Windows theme? The problem is not to be able to use a different icon depending on the current theme

**Comment by rfgamaral** [comment]
See if this helps: https://stackoverflow.com/questions/38734615/how-can-i-detect-windows-10-light-dark-mode

**Comment by MarcAnt01** [comment]
> See if this helps: https://stackoverflow.com/questions/38734615/how-can-i-detect-windows-10-light-dark-mode

@FrayxRulez

**Comment by MarcAnt01** [comment]
Closed since tray icon has been removed again

**Comment by FrayxRulez** [comment]
For what I can see on Windows 11 many system icons are colored again, so I think that Unigram icon can stay as it is.
