### ISSUE TITLE
Filters menu overlaps with hamburger menu button

### ISSUE THREAD

**Issue by behroozbc** [UnigramDev/Unigram#1349]
![image](https://user-images.githubusercontent.com/20381616/75541563-74585780-5a33-11ea-80d5-55d3f70f96a5.png)

1. Select multiple chats;
2. Go back

**Comment by FrayxRulez** [comment]
Can you explain me all the steps?

**Comment by MarcAnt01** [comment]
> Can you explain me all the steps?

1. Open the app;
2. Open archived chats;
3. Go back

**Comment by behroozbc** [comment]
I make this gif 
![2020-02-28-211207](https://user-images.githubusercontent.com/20381616/75572946-0af73980-5a71-11ea-8fda-207bdc070901.gif)

**Comment by MarcAnt01** [comment]
Ah, so my bug is different

**Comment by MarcAnt01** [comment]
Will keep track of it in another ticket and edit the description of this one

**Comment by MarcAnt01** [comment]
Filters menu has been removed for a new design
