### ISSUE TITLE
Long press (touchscreen/pen) in chats list isn't working

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1351]
Right click works properly.

This behaviour happens just once a chat has been opened, before opening any chats it works properly

**Comment by FrayxRulez** [comment]
That’s how it should work.

**Comment by MarcAnt01** [comment]
> That’s how it should work.

Why?

**Comment by MarcAnt01** [comment]
In all the other parts of the apps it works properly

**Comment by MarcAnt01** [comment]
That seems to happen after opening a chat, before it works properly, so it is certainly not intended. I think you've misunderstood the issue

**Comment by MarcAnt01** [comment]
Looks like it's all right after some months
