### ISSUE TITLE
Weird "Telegram" label with a back button takes up filters menu and hamburger menu button

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1352]
1. Open the app;
2. Open archived chats;
3. Go back.

**Comment by 200mpx** [comment]
Hi, maybe I'm not fluent in English but I do not see how #1352 and #1366 are related by its descriptions

**Comment by FrayxRulez** [comment]
Yeah, @200mpx, you're right, unrelated.

**Comment by MarcAnt01** [comment]
Yes, my bad

**Comment by MarcAnt01** [comment]
Looks fixed
