### ISSUE TITLE
Hide empty sections in chat info 

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1355]
For example when no media is shared with that person or there are no groups in common

**Comment by FrayxRulez** [comment]
Given the current app design this isn’t technically possible

**Comment by MarcAnt01** [comment]
> Given the current app design this isn’t technically possible

Can I know the reason since both the Android and iOS app do that?

**Comment by MarcAnt01** [comment]
It also looks like "groups" tab already does that
