### ISSUE TITLE
Windows People integration: Configuration not working

### ISSUE THREAD

**Issue by markuspalme** [UnigramDev/Unigram#1356]
Clicking `Click to connect this app` launches Unigram on my machines but does not have any further effect. Is the feature still disabled as mentioned in #429?

Tested on two Windows 1909 machines.

![grafik](https://user-images.githubusercontent.com/1481801/75673929-5e8da100-5c84-11ea-9d17-f3e42a783401.png)

Please let me know If I can provide any further information (like logs etc.).

**Comment by FrayxRulez** [comment]
Once the app opens up you should go to Settings > Privacy and Security > Sync Contacts.
Actually I can't remember if this takes effect immediately, you might need to close and reopen the app after changing that option.
Also make sure that the app has access to your contacts from **System** settings > Privacy > Contacts.

**Comment by markuspalme** [comment]
Why is contact sync required for this integration? I do not wish to enable contact sync.

Wouln't it be nice if the app told you that the configuration does not allow the setup of the People integration?

**Comment by FrayxRulez** [comment]
I'm not sure about how the app should tell you.
The contacts to appear there must be part of your Windows contacts, obviously. To be part of your Windows contacts them must be synced.

**Comment by markuspalme** [comment]
Let me put if any other way: setting up the integration does not have any effect for me. I do not think that is ideal from a user's perspective. If there is no way to show a message to the user, please feel free to close the issue.

**Comment by MarcAnt01** [comment]
> Why is contact sync required for this integration? I do not wish to enable contact sync.
> 
> Wouln't it be nice if the app told you that the configuration does not allow the setup of the People integration?

MyPeople integration was thought (since it's basically being removed) for contacts
