### ISSUE TITLE
QR login UI is garbled

### ISSUE THREAD

**Issue by bazzilic** [UnigramDev/Unigram#1358]
Could be related to https://github.com/UnigramDev/Unigram/issues/1328

Steps to reproduce:
- Install from Windows Store (v3.14.2691)
- Click "Start Messaging"
- Click "Quick login using QR"
- It throws you back to the first page with the "Telegram. The world's fastest messaging app"
- Click "Start Messaging"
- See this:
![image](https://user-images.githubusercontent.com/1805832/75865984-54fc6880-5e3f-11ea-90b2-aafb910d7a93.png)

(idk if this QR is sensitive or not, so I masked it just in case)

**Comment by FrayxRulez** [comment]
Does this happen only for the first account you try to login?

**Comment by bazzilic** [comment]
I only have one account. But it's reproducible after restarting the app.
To be honest, I already uninstalled the app because of this and some other UI quirks. I will revisit in half a year :)

**Comment by FrayxRulez** [comment]
👋
