### ISSUE TITLE
Add translation function in unigram

### ISSUE THREAD

**Issue by xuan2261** [UnigramDev/Unigram#1361]
I have used Unigram and I find the application very good. I would like to suggest more translation functions in the application, which is of great help to everyone.

**Comment by FrayxRulez** [comment]
You can translate Unigram using translations.telegram.org. The target is Android.

**Comment by AndreiJirohHaliliDev2006** [comment]
@FrayxRulez What? Why Android?

**Comment by xuan2261** [comment]
I mean, translate the messages in that conversation? You misunderstood me.

**Comment by xuan2261** [comment]
> You can translate Unigram using translations.telegram.org. The target is Android.

I mean, translate the messages in that conversation? You misunderstood me.

**Comment by FrayxRulez** [comment]
> @FrayxRulez What? Why Android?

Because Unigram isn’t a official app and I can’t add it to the website

**Comment by FrayxRulez** [comment]
> I mean, translate the messages in that conversation? You misunderstood me.

Oh, I see. Well, I have no plans to add this feature, there are plenty of bots you can use for this

**Comment by xuan2261** [comment]
> > I mean, translate the messages in that conversation? You misunderstood me.
> 
> Oh, I see. Well, I have no plans to add this feature, there are plenty of bots you can use for this

Can you tell me some examples of bots that you mentioned?
