### ISSUE TITLE
Filters are not working properly on windows client after latest update

### ISSUE THREAD

**Issue by 200mpx** [UnigramDev/Unigram#1366]
If I use filters I have now weird selection for Private Chats - I have bots in it - and Groups - I have all Channels in it and that sucks!

Here is the screenshot with Groups filter and all Channels in it:
![image](https://user-images.githubusercontent.com/10790252/76412138-23861e80-63a4-11ea-8387-fd5b456c00af.png)

**Comment by MarcAnt01** [comment]
Duplicate of https://github.com/UnigramDev/Unigram/issues/1352

**Comment by FrayxRulez** [comment]
Fixed 👌
