### ISSUE TITLE
The number of views overlaps to download icon for files without caption in channels

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1367]
![image](https://user-images.githubusercontent.com/43090263/76615539-8998b000-6522-11ea-9166-224e5a298372.png)

**Comment by FrayxRulez** [comment]
This is expected, there's no way to fix it.

**Comment by MarcAnt01** [comment]
> This is expected, there's no way to fix it.

What do you mean by this is expected?
