### ISSUE TITLE
Videos fail to process and send

### ISSUE THREAD

**Issue by XeZrunner** [UnigramDev/Unigram#1368]
[Video demonstrating the issue](https://www.youtube.com/watch?v=I2WoHO0TMDE)

Video files _(OBS recordings, Xbox Game Bar recordings, videos recorded from phone etc..)_ in any file formats _(.mp4, .mov, .avi)_ fail to process and send through Unigram.

After a few seconds elapse, a tiny [_"failed"_](https://i.imgur.com/sud7Xh0.png) message reports failure. _(see video above)_

The Telegram Desktop client can send these video files without any issues.

Reinstalling the application did not solve the issue.

Unigram version 3.14.2691 from the Microsoft Store
Windows 10 1904 _build 18363.3.720_

**Comment by GameSpeck** [comment]
I can confirm this, it's happening with me too. Failed message as soon as I send video

**Comment by sudhegan** [comment]
yep but it only uploads AVC encoded videos and other formats not uploading but telegram desktop uploads all formats

**Comment by cewbdex** [comment]
@FrayxRulez should not happen now, right?

**Comment by FrayxRulez** [comment]
Yes, shouldn't happen any longer. The only transcoded videos now are the ones sent as GIFs, only if they actually have a audio profile, if not they're sent untouched.

**Comment by cewbdex** [comment]
So it will still happen when you choose to send them as a GIF?

**Comment by sudhegan** [comment]
@cewbdex now it does not have option to compress as before (720p to 360p) and some videos are sent as files not videos

**Comment by FrayxRulez** [comment]
> @cewbdex now it does not have option to compress as before (720p to 360p) and some videos are sent as files not videos

The option to compress was causing the issue, and there was no chance for me to fix it. Also MF seems to transcode videos with a super poor quality.

**Comment by sudhegan** [comment]
@FrayxRulez k but now some videos are only sent as files not as videos ??????????
