### ISSUE TITLE
[Windows N] Crash on startup straight after install from Store (W10 desktop v. 18363/Unigram 3.14.2691)

### ISSUE THREAD

**Issue by heroje** [UnigramDev/Unigram#1370]
eventvwr.msc shows the following Error Event under Windows Logs > Application:
```
Faulting application name: Unigram.exe, version: 1.0.0.0, time stamp: 0x5e565f18
Faulting module name: SharedLibrary.dll, version: 2.2.27912.0, time stamp: 0x5d27c65c
Exception code: 0xe31f4059
Fault offset: 0x00000000008fed32
Faulting process id: 0x780
Faulting application start time: 0x01d5fb08955bd7f9
Faulting application path: C:\Program Files\WindowsApps\38833FF26BA1D.UnigramPreview_3.14.2691.0_x64__g9c9v27vpyspw\Unigram.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.NET.Native.Framework.2.2_2.2.27912.0_x64__8wekyb3d8bbwe\SharedLibrary.dll
Report Id: e1161d21-311e-44c4-b622-1079b5426792
Faulting package full name: 38833FF26BA1D.UnigramPreview_3.14.2691.0_x64__g9c9v27vpyspw
Faulting package-relative application ID: App
```

WinDbg x64 says the following about the .dmp file, in the default config. I'm not sure whether I can attach the file, since I don't know whether it stores any personal information.
```
Loading Dump File [C:\Users\x\AppData\Local\CrashDumps\Unigram.exe.1920.dmp]
User Mini Dump File: Only registers, stack and portions of memory are available


************* Symbol Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       symsrv*symsrv.dll*C:\Windows\Symbols*http://msdl.microsoft.com/download/symbols
Symbol search path is: symsrv*symsrv.dll*C:\Windows\Symbols*http://msdl.microsoft.com/download/symbols
Executable search path is: 
Windows 10 Version 18363 MP (4 procs) Free x64
Product: WinNt, suite: SingleUserTS
Built by: 18362.1.amd64fre.19h1_release.190318-1202
Machine Name:
Debug session time: Sun Mar 15 21:30:42.000 2020 (UTC + 1:00)
System Uptime: not available
Process Uptime: 0 days 0:00:06.000
................................................................
...............................................................
Loading unloaded module list
........
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(780.cc4): Unknown exception - code e31f4059 (first/second chance not available)
ntdll!NtRaiseException+0x14:
00007ffc`aebfecb4 c3              ret
```

**Comment by heroje** [comment]
I noticed the same on W10 build 19582, but I don't see a dmp file being generated nor an Event Viewer entry. What could I use to track the application's startup, if it turns out to be a separate cause?
Checking `Enable-WindowsErrorReporting` in PowerShell returns `True`.

**Comment by FrayxRulez** [comment]
Are you using Windows N?

**Comment by heroje** [comment]
Oh! That's correct in both cases - apologies for having this slip past me. The 18363 install is running Windows 10 Pro N, the 19582 is Windows 10 for Workstations N.

**Comment by FrayxRulez** [comment]
Unigram (and most of UWP apps I would say) isn't compatible with Windows N. Sadly I was never able to find some kind of documentation about this topic...

**Comment by FrayxRulez** [comment]
Hi @heroje, I got told that installing the media pack from system settings should solve the issue, not sure if you want to

**Comment by heroje** [comment]
It did work! After installing the pack via modern Settings - Apps & Features - Optional Features. I also had to restart the OS, which I wasn't notified of, but after I did that, I was greeted by Unigram's login screen rather than a crash.
I'll leave it up to you whether this counts as a closed issue - it could be nice to note the requirement and workaround somewhere.

**Comment by MarcAnt01** [comment]
> It did work! After installing the pack via modern Settings - Apps & Features - Optional Features. I also had to restart the OS, which I wasn't notified of, but after I did that, I was greeted by Unigram's login screen rather than a crash.
> I'll leave it up to you whether this counts as a closed issue - it could be nice to note the requirement and workaround somewhere.

I'll try to add it in the Readme somehow

**Comment by FrayxRulez** [comment]
What's the name of the pack? I wonder if there's any way to mark this as a dependency in the Store.
Thanks!

**Comment by heroje** [comment]
Below is what it looks like after getting installed.
It originally displays under "Add a new feature", where after clicking on it you get the list of available features, clicking on any of them shows the "Install" button, which moves it back to the previous list.
![image](https://user-images.githubusercontent.com/45423203/82118177-af863f00-9775-11ea-9728-4923602e79e9.png)

**Comment by MarcAnt01** [comment]
Doesn't it have to be downloaded from here?
https://www.microsoft.com/en-us/download/details.aspx?id=48231

**Comment by FrayxRulez** [comment]
No Filippo, as far as I know that won't work for UWP apps.

**Comment by MarcAnt01** [comment]
> No Filippo, as far as I know that won't work for UWP apps.

Ah, that's probably the one that users used to download and that had no effect on Unigram
