### ISSUE TITLE
Full screen mode for photo viewer

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1372]
It would be nice to have a full screen mode like the video player

**Comment by FrayxRulez** [comment]
UWP apps don’t support such thing

**Comment by MarcAnt01** [comment]
@FrayxRulez I have seen that MS Photos includes a full screen mode, why?

**Comment by MarcAnt01** [comment]
I found also 3rd-party apps using full screen for similar scenarios

**Comment by FrayxRulez** [comment]
Switching the whole window to full screen to view a photo in a app that's not a photo viewer sounds like the worst UX ever

**Comment by FrayxRulez** [comment]
You can simply maximize the window by yourself and you would achieve the same result

**Comment by MarcAnt01** [comment]
The taskbar isn't hidden

**Comment by MarcAnt01** [comment]
And also full screen is already available for the video player
