### ISSUE TITLE
Audio not played when Unigram is on

### ISSUE THREAD

**Issue by import-shiburin** [UnigramDev/Unigram#1373]
I'm not sure 'when' it exactly happens, but when I turn on Unigram(in foreground), all audio stoppes to work. Video players, Audio players, System alerts, etc... are not playing audio, and just says that they failed to initialize sound device.

If I kill Unigram, not even keeping on background, and then start video players or audio players, sound works again.

I've checked that there are no audio message, video message, audio file, nor video clip are being played on Unigram.

I've already turned Video&audio streaming option off, which caused me immediate audio failure if the option is turned on when starting Unigram.

Currently using Unigram 3.14.2691, on Windows 10 Pro K, build 18363

**Comment by FrayxRulez** [comment]
Can you try to disable In-App Sounds in notification settings?

**Comment by sangeu2000** [comment]
That config is already disabled, forgot to mention it, but preblem persists.

**Comment by FrayxRulez** [comment]
🤔

**Comment by discoveruz** [comment]
Unigram 8.4, is not playing video and audio. Win 10
