### ISSUE TITLE
Possibility of changing the font in the app

### ISSUE THREAD

**Issue by MortezaRahmani** [UnigramDev/Unigram#1374]
Hi.
I am wondering if it is possible to change the font in the Unigram. 
It seems that the app is using **Segoe UI**, which is the default font on Windows 10. 
I tried to completely change the Segoe UI font using the available methods on the internet (via windows registry, etc), but it didn't affect Unigram.

**Comment by MarcAnt01** [comment]
Unigram uses a custom emoji font to have iOS emojis, this might be related to the whole font not being changed

**Comment by MortezaRahmani** [comment]
> Unigram uses a custom emoji font to have iOS emojis, this might be related to the whole font not being changed

Well, if that's the case, by changing the **Emoji Set** option inside **Chat Settings** to Microsoft, shouldn't it change the font behavior? (I tried, but it didn't work)

**Comment by FrayxRulez** [comment]
I think that you have to replace Segoe UI Emoji, rather than Segoe UI.
