### ISSUE TITLE
Use round bot buttons instead of squared ones

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1375]
That aims to follow the app general design and WinUI trend
![image](https://user-images.githubusercontent.com/43090263/77553089-a3d47580-6eb4-11ea-8a79-47d4a5bb1116.png)

**Comment by entdark** [comment]
Would look ugly.
Or at least make them dependent on rounding option for messages, because I completely get rid of roundings.

**Comment by MarcAnt01** [comment]
> Would look ugly.
> 
> Or at least make them dependent on rounding option for messages, because I completely get rid of roundings.

The two things are not correlated at all
