### ISSUE TITLE
The option to choose an app to view photos is broken

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1376]
This pop-up is displayed every time, even if I select "Always use this app"
![image](https://user-images.githubusercontent.com/43090263/77690172-2d627100-6fa3-11ea-94ad-e1e51b699a07.png)

**Comment by FrayxRulez** [comment]
That’s how it is intended to work

**Comment by MarcAnt01** [comment]
> That’s how it is intended to work

That makes no sense. If I select always choose this app I don't want that pop-up to appear again
