### ISSUE TITLE
App closes when starting post with smiley (Windows10Mobile/Lumia 950/XL)

### ISSUE THREAD

**Issue by PontifexTkr** [UnigramDev/Unigram#1377]
When I start a post in a chat with a smiley, the app closes completely to startscreen.
This issue does not happen by using Telegram, but by using Unigram. Also it does not happen on PC-desktop version.

Someone know that and what I can do?

(Sorry for my English)

**Comment by MarcAnt01** [comment]
Unigram doesn't support W10 Mobile now
