### ISSUE TITLE
Folders support

### ISSUE THREAD

**Issue by telegram-user** [UnigramDev/Unigram#1379]

**Comment by FrayxRulez** [comment]
This feature isn’t supported by TDLib.

**Comment by telegram-user** [comment]
Ok, we will wait

**Comment by FrayxRulez** [comment]
And also it isn’t even publicly released by Telegram yet, it is just available in beta versions of the apps.

**Comment by MarcAnt01** [comment]
Folders added in the beta version, will take a bit to reach the store
