### ISSUE TITLE
"Schedule when online" option is broken

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1380]
I can see the message in the scheduled messages list, but when the user is online, the message isn't sent

**Comment by FrayxRulez** [comment]
You can report this issue to Telegram.

**Comment by MarcAnt01** [comment]
@FrayxRulez Telegram has removed that feature. Checked now from TD, Android client and iOS one, at this point I think you'd better remove it

**Comment by FrayxRulez** [comment]
I can see the option in all official clients. Maybe you need to check in a private chat rather than in a group.

**Comment by hihain** [comment]
And it only fails when you cannot see the online status of the other person. For example if the other person has its privacy settings set so or even it is your setting...
It would be nice if the app says why it (might) have failed. ;)

**Comment by FrayxRulez** [comment]
Ah, yes, the option shouldn't be available for them, thanks @hihain!

**Comment by MarcAnt01** [comment]
> I can see the option in all official clients. Maybe you need to check in a private chat rather than in a group.

I was checking my chat with @hihain, who has that option disabled and only Unigram was showing it, that's why

**Comment by MarcAnt01** [comment]
https://github.com/UnigramDev/Unigram/issues/1381
