### ISSUE TITLE
App relaunches once closed

### ISSUE THREAD

**Issue by aTomicTurnip** [UnigramDev/Unigram#1388]
Sometimes when **"Quit Unigram"** is clicked in the tray icon, the app reopens itself one or even two times

**Comment by aTomicTurnip** [comment]
And sometimes I need to close it from Task Manager because the process keeps running

**Comment by FrayxRulez** [comment]
> And sometimes I need to close it from Task Manager because the process keeps running

It goes to the system tray.

**Comment by aTomicTurnip** [comment]
> 
> 
> > And sometimes I need to close it from Task Manager because the process keeps running
> 
> It goes to the system tray.

Yes, but if I choose to close it, I want it to stay closed ^-^'

**Comment by FrayxRulez** [comment]
Well, if the app is in the system tray it isn’t closed.

**Comment by aTomicTurnip** [comment]
> Well, if the app is in the system tray it isn’t closed.

I'm saying that EVEN if I close from the system tray icon it keeps re-opening or ignoring the click and still running UNTIL I close it from Task Manager

**Comment by FrayxRulez** [comment]
If Unigram process has a leaf then it’s managed by Windows: UWP apps lifecycle is fully managed by Windows.

**Comment by GameSpeck** [comment]
> If Unigram process has a leaf then it’s managed by Windows: UWP apps lifecycle is fully managed by Windows.

I have the same problem but there is no leaf icon in the Unigram process. To close the app, I need to first click close from the icon tray and then close it using the X button so that it fully closes.

**Comment by MarcAnt01** [comment]
Closed since tray icon has been removed again
