### ISSUE TITLE
Pictures send from in-app camera will be cropped like profile pics

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#1389]
Whenever you go to the attachment menu and want to send a picture, you take with your camera, afterwards it gets cropped as if you were taking a profile picture.

This issue has been there forever, but apparently noone ever made an issue for it...

![image](https://user-images.githubusercontent.com/14281234/78452954-e2c1b280-768e-11ea-9083-a4749dd63646.png)
![image](https://user-images.githubusercontent.com/14281234/78452967-fa993680-768e-11ea-954b-afce56224a05.png)
![image](https://user-images.githubusercontent.com/14281234/78452974-13a1e780-768f-11ea-915c-9d9128c83c3a.png)
![image](https://user-images.githubusercontent.com/14281234/78452990-2d432f00-768f-11ea-95e9-d52008838510.png)

**Comment by MarcAnt01** [comment]
Fixed now
