### ISSUE TITLE
Unigram doesn't format text marked as `monotype` when you switch focus to another app 

### ISSUE THREAD

**Issue by Kenya-West** [UnigramDev/Unigram#1390]
1. Type something like `` Here's my `code` ``;
2. Switch to another window;
3. See that `` `code` `` becomes just `code`;
4. Add the following `` `again` ``.
5. See that message has been sent with `` `again` `` that wasn't formatted.

![2020-04-13_19-32-22](https://user-images.githubusercontent.com/12271104/79114921-7f86fd00-7dbf-11ea-9255-1a7e01096533.gif)

I suggest to not format text at all until it sent.

**Comment by FrayxRulez** [comment]
This is fixed 😎
