### ISSUE TITLE
Add the OpenMoji set

### ISSUE THREAD

**Issue by inferno986return** [UnigramDev/Unigram#1392]
One of the features I like of Unigram is that you can choose the emoji character set. I would like to request that [OpenMoji](https://github.com/hfg-gmuend/openmoji) be added as a selectable set.

**Comment by FrayxRulez** [comment]
Nice! I will. At the moment I'm not really able to generate new emoji set/update the current ones, but I will in the future.

**Comment by FrayxRulez** [comment]
(Maybe I should also write some documentation about this...)

**Comment by FrayxRulez** [comment]
On it right now 😃

**Comment by FrayxRulez** [comment]
I don't think this will happen, but you can now create custom emoji packs.
