### ISSUE TITLE
Touch friendliness and dark theme in the tray icon ui

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1393]
Microsoft Edge (Chromium)
![image](https://user-images.githubusercontent.com/43090263/79251801-f46e3b80-7e80-11ea-9d85-cbfcc8c227e3.png)
Unigram
![image](https://user-images.githubusercontent.com/43090263/79251845-051eb180-7e81-11ea-86c3-09a4058146ac.png)

**Comment by FrayxRulez** [comment]
WinForms isn't touch friendly and it doesn't support dark theme. Plus I'm lazy!

**Comment by MarcAnt01** [comment]
> WinForms isn't touch friendly and it doesn't support dark theme. Plus I'm lazy!

That's not a high priority thing, we can wait

**Comment by MarcAnt01** [comment]
Closed since tray icon has been removed again

**Comment by FrayxRulez** [comment]
I think that this issue should be addressed to Microsoft itself, and not to Unigram: they currently don't provide the components to make this element touch friendly or modern, as they consider system tray discontinued.

**Comment by rakleed** [comment]
@FrayxRulez Microsoft still hasn't fully migrated settings from Control Panel to Settings for more than 7 years. And given that, as you say, they consider the system tray to be discontinued, I don't think they will improve the developer experience.

But if you still leave the tray icon, I would like you to adapt tray menu to a dark theme, as many developers have done (and the Electron framework supports out of the box). And there's the MagicPods app, which has a modern, beautiful tray menu that supports a dark theme.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/19418601/202265205-263c6a82-099d-4ad3-aa55-151cd374d7c3.png)

</details>
