### ISSUE TITLE
Swipe left/right with touchpad/touchscreen to switch among folders

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1398]
Atm swipe left/right is used for the elements of hamburger menu, but it'll be more intuitive to use it for folders with the current app design

**Comment by FrayxRulez** [comment]
This isn’t technically feasible

**Comment by MarcAnt01** [comment]
> This isn’t technically feasible

Why? It's working with the elements of hamburger menu

**Comment by MarcAnt01** [comment]
Pivots supports swiping out of the box

**Comment by FrayxRulez** [comment]
Switching among us
