### ISSUE TITLE
Dice rolling doesn't work properly

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1399]
If I try to use :dice emojis the animation crashes. Once I close the chat and reopen it, it works properly

**Comment by FrayxRulez** [comment]
“Crashes” is the wrong term

**Comment by MarcAnt01** [comment]
What is the right one? Is stuck maybe?

**Comment by githubcatw** [comment]
Probably stuck.

**Comment by CornyjK** [comment]
I'd say it stucks in middle of animating, same issue here.

**Comment by MarcAnt01** [comment]
This has been fixed
