### ISSUE TITLE
Unmatched corner radius of search box

### ISSUE THREAD

**Issue by AkazaRenn** [UnigramDev/Unigram#1401]
Before focusing:
![image](https://user-images.githubusercontent.com/8340896/79679255-47722680-81d2-11ea-989f-7d3fd48ddfa5.png)

After: 
![image](https://user-images.githubusercontent.com/8340896/79679256-4d680780-81d2-11ea-9ed9-1a6fcf1e5109.png)

Should be easy to tell the difference

**Comment by FrayxRulez** [comment]
I would say it’s not the only thing to unmatch 😅😂

**Comment by FrayxRulez** [comment]
Done
