### ISSUE TITLE
Stickers don't display

### ISSUE THREAD

**Issue by Evolto2019** [UnigramDev/Unigram#1403]
I have installed and reset Webp extension and Unigram for times. But webp stickers still don't display.
Windows 1909 18363.778
Unigram 3.4.2700

**Comment by MarcAnt01** [comment]
@FrayxRulez isn't webp decoding performed within Unigram now?

**Comment by FrayxRulez** [comment]
Yes, as it has been for few years before using the Microsoft app

**Comment by Riajyuu** [comment]
Hi

I have exactly the same issue on my Windows laptop, Lenovo Legion Y7000P 2019, Windows 10 1909 Pro 18363.815. But animated stickers work for me.

![image](https://user-images.githubusercontent.com/16912240/80311587-0c728300-87d0-11ea-8908-2b6c47b93f06.png)


But I can't see this happening on another PC with edu version of OS.

**Comment by FrayxRulez** [comment]
Hello!
I have an idea about what the problem could be. 
Can you provide me the resolved path of:
`Can you send me the full path of:
%LOCALAPPDATA%\Packages\38833FF26BA1D.UnigramPreview_g9c9v27vpyspw\LocalState`

**Comment by Riajyuu** [comment]
@FrayxRulez 
On Edu PC, which don't have this issue, it is `C:\Users\admin\AppData\Local\Packages\38833FF26BA1D.UnigramPreview_g9c9v27vpyspw\LocalState`

On Laptop, which is experiencing, it is `C:\Users\御用萝莉控\AppData\Local\Packages\38833FF26BA1D.UnigramPreview_g9c9v27vpyspw\LocalState`

**Comment by Evolto2019** [comment]
On my PC with Windows 10 Enterprise, it is C:\Users\username\AppData\Local\Packages\38833FF26BA1D.UnigramPreview_g9c9v27vpyspw\LocalState

**Comment by FrayxRulez** [comment]
> On my PC with Windows 10 Enterprise, it is C:\Users\username\AppData\Local\Packages\38833FF26BA1D.UnigramPreview_g9c9v27vpyspw\LocalState

The important part was the username that you censored out. The issue is fixed, update the app.
