### ISSUE TITLE
Archive and folders look bad in compact mode

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1404]
![image](https://user-images.githubusercontent.com/43090263/79760182-fcfec000-831f-11ea-8bda-a31bb19eaab5.png)

**Comment by FrayxRulez** [comment]
Any idea about how to display them?

**Comment by MarcAnt01** [comment]
Sure, for archived chats just use the icon, for folders add an icon that opens a flyout.

**Comment by githubcatw** [comment]
Like this?
![Mockup](https://user-images.githubusercontent.com/17374742/79845473-2aa24280-83ce-11ea-9fb4-782db717b975.png)

**Comment by MarcAnt01** [comment]
> Like this?
> ![Mockup](https://user-images.githubusercontent.com/17374742/79845473-2aa24280-83ce-11ea-9fb4-782db717b975.png)

For archive it'd be enough just to disable collapsed mode and place the folder icon above it.

**Comment by MarcAnt01** [comment]
This compact mode doesn't exist any longer

**Comment by FrayxRulez** [comment]
Can you move this to #2611? Thanks
