### ISSUE TITLE
Option to switch between chat list sort type

### ISSUE THREAD

**Issue by abh-oss01** [UnigramDev/Unigram#1412]
Please add an option to be able to switch between chat sort options in the header, horizontal (Current, forced) or vertical list (the previous, before the new update).

**Comment by MarcAnt01** [comment]
The app currently follows folder design from mobile clients which is closer to official guidelines.

**Comment by FrayxRulez** [comment]
I guess that the app should follow desktop apps design where it makes sense, as it is a desktop app

**Comment by MarcAnt01** [comment]
> I guess that the app should follow desktop apps design where it makes sense, as it is a desktop app

I thought you already made your choice, since you had changed filters to match mobile app design...

**Comment by MarcAnt01** [comment]
I personally don't like the UI of folders in Telegram Desktop and MacOS client since it takes too much space in landscape (that would be bad for screens smaller than 15 inches). Furthermore swiping among folders with touchpad would be a great feature.

**Comment by abh-oss01** [comment]
Thanks Fela ✌🏻👍🏻
