### ISSUE TITLE
Disabling message preview still shows preview (notification)

### ISSUE THREAD

**Issue by Daksh777** [UnigramDev/Unigram#1415]
![image](https://user-images.githubusercontent.com/43648146/80099137-9f6eab80-858b-11ea-871b-8fb81c0a2469.png)
Preview still showing even though the setting is turned off.

**Comment by MarcAnt01** [comment]
Please add one issue per ticket, otherwise they get confusing

**Comment by GameSpeck** [comment]
Oh, I am sorry. I will edit my message and create another ticket.

**Comment by MarcAnt01** [comment]
Does that happen with the app closed or open?

**Comment by GameSpeck** [comment]
> Does that happen with the app closed or open?

Both times

**Comment by bkaankose** [comment]
I can confirm this issue still exists in 7.3 (5951)

**Comment by FrayxRulez** [comment]
This should be fixed, please reopen if it's not the case
