### ISSUE TITLE
Broken send button from notifications

### ISSUE THREAD

**Issue by Daksh777** [UnigramDev/Unigram#1416]
The buttons don't do anything. They simply hide the notification.

**Comment by MarcAnt01** [comment]
They both work for me

**Comment by GameSpeck** [comment]
![bugreport](https://user-images.githubusercontent.com/43648146/80100698-f1b0cc00-858d-11ea-9581-a8dcd5039fbc.gif)
Not working for me, tried enabling message preview but still not working.
Unigram Version: 3.14.2700

**Comment by MarcAnt01** [comment]
Ah, I thought the buttons weren't clickable at all, will check when I get a new messaeg👍

**Comment by CornyjK** [comment]
They also work for me, but in past they did not.

**Comment by MarcAnt01** [comment]
OK, after further testing I came to this conclusion:
- Mark as read button is working if you disable buggy push notifications (https://github.com/UnigramDev/Unigram/issues/1206);
- Reply button is broken, since it won't send the message

**Comment by MarcAnt01** [comment]
I edited this issue to cover reply button and included mark as read in the one of pushed notifications (hoping that @FrayxRulez will disable them one day)

**Comment by CornyjK** [comment]
>     * Reply button is broken, since it won't send the message

In Which case? Works for me.

**Comment by MarcAnt01** [comment]
> In Which case? Works for me.

I tried with two private chats, will see if it is the same for groups

**Comment by GameSpeck** [comment]
> In Which case? Works for me.

Doesn't work for me either of those, private chat or group. What is your Windows version?

**Comment by brukbrhane** [comment]
Maybe related, Ctrl+return doesn't send the message on the notification. Only goes to a new line

**Comment by MarcAnt01** [comment]
> Maybe related, Ctrl+return doesn't send the message on the notification. Only goes to a new line

That's something related to Microsoft, I have already contacted an employee to have the issue tracked in their internal repo

**Comment by abh-oss01** [comment]
> > In Which case? Works for me.
> 
> I tried with two private chats, will see if it is the same for groups

and what about secret chats?

**Comment by MarcAnt01** [comment]
> > > In Which case? Works for me.
> > 
> > I tried with two private chats, will see if it is the same for groups
> 
> and what about secret chats?

Never used them

**Comment by CornyjK** [comment]
> Doesn't work for me in either of those, private chat or group. What is your Windows version?

I tested in private chats only.

![image](https://user-images.githubusercontent.com/9021297/80380424-da305680-889f-11ea-9a2c-42d1706990f5.png)

**Comment by GameSpeck** [comment]
> I tested in private chats only.
> 
> ![image](https://user-images.githubusercontent.com/9021297/80380424-da305680-889f-11ea-9a2c-42d1706990f5.png)

I am on the same version but even for private chat, it won't reply, the notification bubble will simply disappear.

**Comment by FrayxRulez** [comment]
Might work now

**Comment by lord-dubious** [comment]
stopped working again

**Comment by FrayxRulez** [comment]
@dubious-senpai We are not able to help you if you don’t provide further details

**Comment by lord-dubious** [comment]
The reply button on the notification pop up on windows 11 fails to send reply to replied chat

**Comment by FrayxRulez** [comment]
@dubious-senpai Maybe you could at least provide your app version… That’s like the bare minimum…

**Comment by lord-dubious** [comment]
Oh this is my first time reporting an issue please give me the steps, it's the latest version 10.3.0.0
