### ISSUE TITLE
Button for joining a group via local-group-search is mislabeled

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#1417]
I was looking for groups in my area and when I opened one, the button on the bottom said "Löschen und Verlassen" ("Delete and leave"). However, when I clicked it, I joined the group instead.

![image](https://user-images.githubusercontent.com/14281234/80104611-b2778080-8577-11ea-8bd0-9660f667db9d.png)

**Comment by hihain** [comment]
Does it only happen using the find groups nearby feature?
At least opening a group using a link does not have this issue for me...

**Comment by FrayxRulez** [comment]
I think I fixed this as part of https://github.com/UnigramDev/Unigram/commit/03fb00c4bae8fe9c23d87c56c7d3191b404cf7ed

**Comment by FrayxRulez** [comment]
But yes. Was only happening for location based groups and discussion groups.
