### ISSUE TITLE
Broken inline information

### ISSUE THREAD

**Issue by GameSpeck** [UnigramDev/Unigram#1419]
![image](https://user-images.githubusercontent.com/43648146/80107544-d5665c80-8598-11ea-93b3-6564b13fa787.png)
The ?? is the song's timestamp and the album art is also missing.

**Comment by MarcAnt01** [comment]
What do official clients show? Attaching a screenshot would be a good idea

**Comment by GameSpeck** [comment]
![image](https://user-images.githubusercontent.com/43648146/80108514-01cea880-859a-11ea-8094-cf86ac5d59cb.png)
Here's the image.

**Comment by FrayxRulez** [comment]
It would be more useful to get the bot name, rather than other apps screenshots.

**Comment by GameSpeck** [comment]
> It would be more useful to have the bot name, rather than other apps screenshots.

For sure, it is @ DeezerMusicBot

**Comment by FrayxRulez** [comment]
I think this is fine:
![image](https://user-images.githubusercontent.com/8152849/82754776-a62d5000-9dcf-11ea-9715-a9bc66a89483.png)
