### ISSUE TITLE
"Recent actions" to be moved to the edit menu

### ISSUE THREAD

**Issue by GameSpeck** [UnigramDev/Unigram#1421]
The "Recent actions" should be moved to the edit menu of the group instead of in Administrator>Recent Actions. In official app, it is not in the Administrator tab but in the edit menu.

Official app: 
![image](https://user-images.githubusercontent.com/43648146/80110093-efee0500-859b-11ea-8f40-b3e1c2612a6a.png)

Unigram: 
![image](https://user-images.githubusercontent.com/43648146/80110197-0ac07980-859c-11ea-80a9-605e608890c8.png)

**Comment by MarcAnt01** [comment]
Unigram organizes them in the same way as iOS and Android apps
