### ISSUE TITLE
"Quit Unigram" from task bar icons doesn't close the app

### ISSUE THREAD

**Issue by GameSpeck** [UnigramDev/Unigram#1422]
If you click the "Quit Unigram" from the task bar icons when you ARE NOT in the app (running in background), it will open Unigram instead and not close the app while in the official app it closes in spite of being in the background.

Edit: Sometimes it does not even quit while in app.

**Comment by MarcAnt01** [comment]
In the taskbar there is only "Close window" option

**Comment by MarcAnt01** [comment]
To close Unigram in background you have to use the tray icon

**Comment by GameSpeck** [comment]
> To close Unigram in background you have to use the tray icon

![image](https://user-images.githubusercontent.com/43648146/80127972-b248a680-85b2-11ea-9ea8-20f5056c3719.png)
Yes, I am using this tray icon but it won't close Unigram, it instead will open Unigram if it is running in the background/minimized.

**Comment by MarcAnt01** [comment]
I think you are reporting the same bug that has already been reported in https://github.com/UnigramDev/Unigram/issues/1388

**Comment by GameSpeck** [comment]
> I think you are reporting the same bug that has already been reported in #1388

For me it doesn't happen sometimes, it happens everytime

**Comment by MarcAnt01** [comment]
> > I think you are reporting the same bug that has already been reported in #1388
> 
> For me it doesn't happen sometimes, it happens everytime

Yes but the bug is the same, closing it
