### ISSUE TITLE
Names in right to left script gets overlapped with "admin" text

### ISSUE THREAD

**Issue by Daksh777** [UnigramDev/Unigram#1423]
People who have names in right to left script and are admin have their names and the admin tag overalpped while in Telegram the text alignment is still in left so it doesn't overlap

Unigram: 
![image](https://user-images.githubusercontent.com/43648146/80182278-2a9b8000-8624-11ea-82ba-c34fc5665a40.png)

Telegram: 
![image](https://user-images.githubusercontent.com/43648146/80182299-37b86f00-8624-11ea-9c9c-76b2bcda7017.png)

**Comment by MarcAnt01** [comment]
That is a bug of Windows UWP RTL rendering

**Comment by FrayxRulez** [comment]
This was fixed in https://github.com/UnigramDev/Unigram/commit/9fe287dc8e5c1a94ca6670af4003197b848732be
