### ISSUE TITLE
Custom theme maker not working

### ISSUE THREAD

**Issue by milindgoel15** [UnigramDev/Unigram#1424]
hi,

I just installed this after 1 year and got changed very much since last time. performance much improved and animations got dope.
I just saw a bug in chat settings where tapping on "create new theme" button doesnt do anything. idk if this issue is known so made one.

**Comment by GameSpeck** [comment]
Refer to this issue: https://github.com/UnigramDev/Unigram/issues/1142
Custom themes only work if you do not select system theme, if you have selected system theme, it won't work

**Comment by milindgoel15** [comment]
ahh that explains it. 
if its possible to implement a dialog when we tap on create new theme on system theme selected saying something like, "Custom Themes cant be made from system theme" would be much better.
just my opinion if its possible.

btw closing my isssue since i got to know i need to select unigram themes to make custom
thanks btw
