### ISSUE TITLE
Buttons overlapping in windowed mode

### ISSUE THREAD

**Issue by Daksh777** [UnigramDev/Unigram#1425]
In windowed mode some buttons overlay making it difficult to click in the right one.
![image](https://user-images.githubusercontent.com/43648146/80186413-9503ee80-862b-11ea-9393-c2d0848d5e48.png)

**Comment by MarcAnt01** [comment]
That search button when clicked doesn’t work some times, I think that’s related to the overlapping

**Comment by MarcAnt01** [comment]
Not happening any longer
