### ISSUE TITLE
Quiz answers explanation takes too much space

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1427]
![image](https://user-images.githubusercontent.com/43090263/80242331-80444c80-8665-11ea-896c-e16c48d36e8f.png)

**Comment by FrayxRulez** [comment]
This is a bug of Microsoft.UI.Xaml 2.3. Not sure if the issue is fixed in 2.4, as it is still in beta.

**Comment by MarcAnt01** [comment]
![image](https://user-images.githubusercontent.com/43090263/80242933-8129ae00-8666-11ea-9c46-21294ce6c19f.png)

**Comment by MarcAnt01** [comment]
@FrayxRulez why is this one all right?

**Comment by FrayxRulez** [comment]
Why users always act as if developers lie to them to not fix bugs?

**Comment by MarcAnt01** [comment]
> Why users always act as if developers lie to them to not fix bugs?

I haven't blamed you, just asked why it affects just some elements
