### ISSUE TITLE
Quiz explanation icon is shown also for who has chosen the correct answer

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1428]

**Comment by FrayxRulez** [comment]
It should!

**Comment by MarcAnt01** [comment]
No

**Comment by MarcAnt01** [comment]
iOS client doesn’t show them

**Comment by FrayxRulez** [comment]
Honestly, even if iPhone app didn't show it I would have shown it anyway, as even if you choose the right answer you might be still curious about the why.

But anyway:
![image](https://user-images.githubusercontent.com/8152849/80245904-d1efd580-866b-11ea-9604-419ae9c42ba3.png)

**Comment by MarcAnt01** [comment]
Unigram
![image](https://user-images.githubusercontent.com/43090263/80246293-76721780-866c-11ea-9d32-c6bb71db049f.png)

iPhone
![image](https://user-images.githubusercontent.com/43090263/80246271-6b1eec00-866c-11ea-8f73-6d3a6599465e.png)

**Comment by MarcAnt01** [comment]
And the content is empty, so doubt it’ll be useful in any way🤣🤷🏻‍♂️

**Comment by MarcAnt01** [comment]
It seems to depend on the lack of explanation
