### ISSUE TITLE
Error when opening group info

### ISSUE THREAD

**Issue by GameSpeck** [UnigramDev/Unigram#1429]
![image](https://user-images.githubusercontent.com/43648146/80283922-cdddb980-8738-11ea-90fc-36cc6b082bc4.png)
Issue persists on Windows 1803, checked on 1909 but wasn't there.

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/b93afe28df60956e842ceb1f8ff6126ec266fe9e
