### ISSUE TITLE
Keep Unigram for W10M published on the Store

### ISSUE THREAD

**Issue by Vespa2** [UnigramDev/Unigram#1431]
Please, keep Unigram for W10M published on the Store.
This is very important because WhatsApp is no longer available, so Telegram/Unigram remains the only way to chat with friends. The Abaculi's fork is only for Creators Update (15063.x) and can't be installed on W10M Anniversary Update (14393.x).
Thanks

**Comment by MarcAnt01** [comment]
You can use Telegram official client for Windows Phone
