### ISSUE TITLE
Improper padding in storage usage of any chat

### ISSUE THREAD

**Issue by GameSpeck** [UnigramDev/Unigram#1434]
![image](https://user-images.githubusercontent.com/43648146/80307341-17381280-87e6-11ea-9b10-6d6d3dfc6ca0.png)
The group's title is almost touching the card's edge, the checkbox is very close to the text and the text is also not alligned properly

**Comment by MarcAnt01** [comment]
Repro steps?

**Comment by GameSpeck** [comment]
Just go to settings > Storage & Usage > Storage Usage and click any chat you like

**Comment by FrayxRulez** [comment]
Done 👏
