### ISSUE TITLE
Add ability to send silent or scheduled images

### ISSUE THREAD

**Issue by cewbdex** [UnigramDev/Unigram#1437]
The same way as text messages.

**Comment by GameSpeck** [comment]
It is there already, just type your text and right click on the send button/icon
![image](https://user-images.githubusercontent.com/43648146/80347272-b82bd980-8889-11ea-9e3b-d73c115ed7bb.png)

**Comment by CornyjK** [comment]
@GameSpeck I am talking of images, not text messages.

**Comment by FrayxRulez** [comment]
> It is there already, just type your text and right click on the send button/icon

It isn't possible at the moment with pictures and files

**Comment by GameSpeck** [comment]
Oh, I am sorry, I didn't understand it properly
