### ISSUE TITLE
Unable to change private group to public

### ISSUE THREAD

**Issue by GameSpeck** [UnigramDev/Unigram#1440]
If you go to group settings and try to change the group type to public, and enter the public URL for your group, it will forever be stuck on checking.

**Comment by FrayxRulez** [comment]
Note for self: this is probably a basic group.

**Comment by GameSpeck** [comment]
What do you mean? I am trying to change a private group to a public one

**Comment by MarcAnt01** [comment]
> What do you mean? I am trying to change a private group to a public one

Basic groups are different from supergroups, no recent actions and all the members have full permissions

**Comment by GameSpeck** [comment]
I am not sure how is that related to my issue because on official app, I can easily change the group type to public and set its link while on Unigram it is just stuck on checking link.

**Comment by MarcAnt01** [comment]
If you create groups on mobile clients and in TD they should be automatically supergroups, but with TDLib it shouldn't be the case. At least, that's how it worked some time ago

**Comment by FrayxRulez** [comment]
> If you create groups on mobile clients and in TD they should be automatically supergroups, but with TDLib it shouldn't be the case. At least, that's how it worked some time ago

No, groups are always created as basic groups by default.

**Comment by FrayxRulez** [comment]
> I am not sure how is that related to my issue because on official app, I can easily change the group type to public and set its link while on Unigram it is just stuck on checking link.

It is because basic groups need to get converted to supergroups first

**Comment by GameSpeck** [comment]
> It is because basic groups need to get converted to supergroups first
So can't it be done on Unigram?

**Comment by MarcAnt01** [comment]
@GameSpeck ?

**Comment by GameSpeck** [comment]
> @GameSpeck ?

Can't basic groups be converted to supergroups on Unigram?
