### ISSUE TITLE
Count the number of found searched items

### ISSUE THREAD

**Issue by GameSpeck** [UnigramDev/Unigram#1441]
Unigram doesn't count the number of items which were input in the search bar. 

Unigram:
![image](https://user-images.githubusercontent.com/43648146/80369692-503aba80-88ac-11ea-8a3b-d4920cdfdd47.png)

Telegram:
![image](https://user-images.githubusercontent.com/43648146/80369748-68123e80-88ac-11ea-9ea1-2107fb7dc27e.png)

**Comment by MarcAnt01** [comment]
Duplicate of https://github.com/UnigramDev/Unigram/issues/1042

**Comment by MarcAnt01** [comment]
Please search also among the closed issues before creating one
