### ISSUE TITLE
Chat folder sync and edit problem?

### ISSUE THREAD

**Issue by azanone** [UnigramDev/Unigram#1442]
Unigram 3.15.3073 have chat folder, but Unigram's chat folder can't sync my telegram account chat folders(at other telegram client is good). And I can't edit they folders, not have "save" button, enter isn't work. They are problems.

**Comment by MarcAnt01** [comment]
Known, Unigram doesn’t support folder, they are just filters with the ui of folders

**Comment by MarcAnt01** [comment]
@FrayxRulez you should hide edit options atm since they confuse uers
