### ISSUE TITLE
"Admins have restricted....." remains even when you are unrestricted

### ISSUE THREAD

**Issue by GameSpeck** [UnigramDev/Unigram#1443]
![bsd](https://user-images.githubusercontent.com/43648146/80456077-96def200-894a-11ea-83f8-a9234bfdad58.gif)
You have to switch the chat for it to get removed and chat.

**Comment by FrayxRulez** [comment]
Group username?

**Comment by GameSpeck** [comment]
> Group username?

@retromusicapp
