### ISSUE TITLE
Once secret chat has been deleted, it cannot be made again

### ISSUE THREAD

**Issue by GameSpeck** [UnigramDev/Unigram#1444]
It will keep showing "Secret chat cancelled"

**Comment by MarcAnt01** [comment]
If you close the app and open it again will it be possible?

**Comment by GameSpeck** [comment]
> If you close the app and open it again will it be possible?

Yes, it is possible but that is kind of weird, to open and close the app to make another secret chat

**Comment by MarcAnt01** [comment]
> > If you close the app and open it again will it be possible?
> 
> 
> 
> Yes, it is possible but that is kind of weird, to open and close the app to make another secret chat

Sure
