### ISSUE TITLE
While forwarding, the search results are announced like random cords or number instead of the chat name

### ISSUE THREAD

**Issue by FrayxRulez** [UnigramDev/Unigram#1446]
While forwarding, the search results are announced like random cords or number instead of the chat name. We couldn't understand which is the chat is now in focus

https://t.me/unigraminsiders/270749

**Comment by sukiletxe** [comment]
I think this is fixed now too. Search works fine, even though the global search and messages groups are empty. But contacts and groups appear correctly, so I think this is the intended behaviour.
