### ISSUE TITLE
Exception throwed when trying to modify style on landscape

### ISSUE THREAD

**Issue by Tabris963** [UnigramDev/Unigram#145]
When I'm on landscape and I try to modify the style of what in writing (or what I've written), I can see for a moment the panel that allows me to choose between italic or bold (first screenshot), but then an Exception is throwed (second screenshot)

First:
![wp_ss_20170111_0003](https://cloud.githubusercontent.com/assets/6726440/21865621/40c4e530-d847-11e6-9e7b-8508e5502944.png)

Second:
![wp_ss_20170111_0002](https://cloud.githubusercontent.com/assets/6726440/21865643/53e77236-d847-11e6-9c1b-8fcfd4ad12a4.png)

**Comment by FrayxRulez** [comment]
You can now use **bold**, _italic_ and `monospace` using **, __ and `
