### ISSUE TITLE
Unigram sometimes refuses to load sticker list

### ISSUE THREAD

**Issue by cewbdex** [UnigramDev/Unigram#1461]
Stickers are not loaded, not waiting, nor restarting the app does not help, I fix this by killing Unigram processes. Unable to reproduce, it just happens sometimes.

![image](https://user-images.githubusercontent.com/9021297/80566153-97cb5e80-89f2-11ea-9732-200853561b74.png)

**Comment by MarcAnt01** [comment]
Duplicate of an issue that is fixed in develop branch

**Comment by FrayxRulez** [comment]
> Stickers are not loaded, not waiting, nor restarting the app does not help, I fix this by killing Unigram processes. Unable to reproduce, it just happens sometimes.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/9021297/80566153-97cb5e80-89f2-11ea-9732-200853561b74.png)
> 
>

**Comment by MarcAnt01** [comment]
@FrayxRulez we already have https://github.com/UnigramDev/Unigram/issues/1403

**Comment by FrayxRulez** [comment]
Two different things

**Comment by MarcAnt01** [comment]
> Two different things

Aren't both about stickers not displayed?

**Comment by FrayxRulez** [comment]
This is stickers not loaded, as you can see the pane is empty

**Comment by FrayxRulez** [comment]
🤷‍♂️
