### ISSUE TITLE
Consider having a specific page to edit user profile

### ISSUE THREAD

**Issue by FrayxRulez** [UnigramDev/Unigram#1468]
**Why**
Settings home is cluttered of data that are rarely changed by the user:
![image](https://user-images.githubusercontent.com/8152849/80706202-35ed2080-8ae8-11ea-8cad-0025b7720342.png)

**What**
Consider to move profile editing to a specific sub-setting, as it happens on iOS and macOS.

**Comment by MarcAnt01** [comment]
This is the case now
