### ISSUE TITLE
Chats aren't updated when switching between them

### ISSUE THREAD

**Issue by FrayxRulez** [UnigramDev/Unigram#1471]
This bug has been introduced by `Unigram.Infrastructure` submodule being out of sync with `master`.

**Comment by alex-fgsfds** [comment]
Can confirm, app is practically unusable with this. Blocker?

**Comment by FrayxRulez** [comment]
An update is on the way, hold on 😊
Already being processed by Microsoft store.

**Comment by beerisgood** [comment]
Can confirm that.

Glad to hear that the update is already pushed :) 👍

**Comment by FrayxRulez** [comment]
... and available
