### ISSUE TITLE
Develop branch looks broken-

### ISSUE THREAD

**Issue by kishorpise** [UnigramDev/Unigram#1472]
I cloned develop branch. I found Infrastructure folder is missing when downloaded. But when I see on web, I can see the files and foler unde it.

**Comment by FrayxRulez** [comment]
Wait for #1469

**Comment by kishorpise** [comment]
Can you suggest me any working branch meanwhile- 
I have visual studio 2019- Just want to compile and run ....

**Comment by FrayxRulez** [comment]
You should be able to do it now
