### ISSUE TITLE
Add "beginning" option in search by date

### ISSUE THREAD

**Issue by GameSpeck** [UnigramDev/Unigram#1474]
Telegram:
![image](https://user-images.githubusercontent.com/43648146/80790942-cf323a80-8bad-11ea-8271-3f344904a2f2.png)
Unigram:
![image](https://user-images.githubusercontent.com/43648146/80790961-e07b4700-8bad-11ea-96c4-ce2e71c9522d.png)

**Comment by FrayxRulez** [comment]
I can but I have no translation for this as Telegram for Android doesn’t support it

**Comment by GameSpeck** [comment]
> I can but I have no translation for this as Telegram for Android doesn’t support it

On Telegram for Android, you just select a really really old date to get to the first message so if that gets fixed then that'll be enough!

**Comment by MarcAnt01** [comment]
> I can but I have no translation for this as Telegram for Android doesn’t support it

We already have other options, I don't think it will be a problem

**Comment by FrayxRulez** [comment]
I'll close as I don't see the need to have a "Beginning" button!
