### ISSUE TITLE
Change behaviour of "Adaptive layout for wide screens"

### ISSUE THREAD

**Issue by GameSpeck** [UnigramDev/Unigram#1483]
Telegram: 
![image](https://user-images.githubusercontent.com/43648146/80805982-12ed6a00-8bd7-11ea-9c3a-7112f64a6796.png)

Unigram:
![image](https://user-images.githubusercontent.com/43648146/80805955-fea96d00-8bd6-11ea-8ec5-b649daf586be.png)
My message looks like it is in the center, it should be placed at the left

**Comment by MarcAnt01** [comment]
I don't understand the purpose of this ticket

**Comment by beerisgood** [comment]
Can't confirm this behaviour on 4K monitor/ with 4k resolution

**Comment by GameSpeck** [comment]
> I don't understand the purpose of this ticket

It's really weird to see my messages at the centre of the screen, leaving so much space on the right

**Comment by MarcAnt01** [comment]
You can disable adaptive layout. I still don't get if you are reporting a bug or suggesting an improvement

**Comment by GameSpeck** [comment]
> You can disable adaptive layout. I still don't get if you are reporting a bug or suggesting an improvement

I am suggesting it to make the same as Telegram, all messages at left.

**Comment by FrayxRulez** [comment]
My plan is to actually set a max width and align messages (including input field) to the center of the screen, as new Telegram web design suggests to do.
What do you think?

**Comment by cewbdex** [comment]
Duplicate of #1179
