### ISSUE TITLE
Emoji Set popup UI is outdated

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1488]
![image](https://user-images.githubusercontent.com/43090263/80824185-3962d380-8bde-11ea-8bad-d6e7400aadb4.png)

**Comment by FrayxRulez** [comment]
What's weird here?

**Comment by MarcAnt01** [comment]
> What's weird here?

They have a different ui if you compare them to other pop-ups

**Comment by MarcAnt01** [comment]
Do you want a comparison?

**Comment by GameSpeck** [comment]
![image_2020-05-02_17-54-36](https://user-images.githubusercontent.com/43648146/80864162-94f49600-8c9e-11ea-8f02-ee80041bbf72.png)
![image_2020-05-02_17-54-44](https://user-images.githubusercontent.com/43648146/80864164-9625c300-8c9e-11ea-95d2-bd2016d2b277.png)
I compared these two, looks the same to me @MarcAnt01

**Comment by FrayxRulez** [comment]
Most popups have this design, you might want to point out those that don’t

**Comment by MarcAnt01** [comment]
![image](https://user-images.githubusercontent.com/43090263/80866543-9074b100-8c8f-11ea-88e1-2914318c9044.png)

**Comment by MarcAnt01** [comment]
I prefer how emojis pop up look like, settings design is very nice, I think it simply doesn't fit pop-ups
