### ISSUE TITLE
Set background button does not work for custom color background

### ISSUE THREAD

**Issue by muznyo** [UnigramDev/Unigram#1489]
![Snímek obrazovky (3)_LI](https://user-images.githubusercontent.com/24987471/80824999-d40fe200-8bdf-11ea-9a4a-95567a7de9fb.jpg)
![Snímek obrazovky (6)_LI](https://user-images.githubusercontent.com/24987471/80824995-d114f180-8bdf-11ea-961b-76e092057270.jpg)

**Comment by hihain** [comment]
FYI: Background also do not get blurred.
