### ISSUE TITLE
Unable to install bundle because it does not have an appropriate application package for x64 architecture.

### ISSUE THREAD

**Issue by KilluaEnki** [UnigramDev/Unigram#149]
Hi, i have this problem, how can i fix it? Thanks in advance!

Unable to install bundle file:///C:/Users/Killua/Downloads/Unigram_0.1.64.122_ARM.appxbundle because it does not have an appropriate application package for x64 architecture.

**Comment by kesavaprasadarul** [comment]
@KilluaEnki The package you're trying to install is for phones. Please use the other package that has x86 in it's name.

**Comment by KilluaEnki** [comment]
sorry @kesavaprasadarul i don't find it

**Comment by KilluaEnki** [comment]
sorry @kesavaprasadarul  i don't find it

**Comment by larsschellhas** [comment]
just join the telegram channel "Unigram Development" by search or this Link: https://t.me/joinchat/ARAF8z851oqv-9A1XXIHJw

The build you are looking for is in the second last message and the necessary certificate is right beneath it.
