### ISSUE TITLE
Unhandled exception at sending file

### ISSUE THREAD

**Issue by beerisgood** [UnigramDev/Unigram#1491]
After select a file from file manager for sending it in chat, the file get (successfully) transmitted but also this error opens:
![Telegram Error](https://user-images.githubusercontent.com/9625159/80839447-8b662200-8bfb-11ea-8761-51b3e1f2a0ff.jpg)

**Comment by DjArt** [comment]
I have same issues too when trying to send files from shared disk.

**Comment by FrayxRulez** [comment]
Fixed!
