### ISSUE TITLE
Show discussion group url with mouse hover above discuss button

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1494]

**Comment by FrayxRulez** [comment]
But why

**Comment by GameSpeck** [comment]
It is not even present in official app, also it is kind of waste to implement because when you click the discuss button, you are redirected to the group without joining it so you already can see the group's URL and other information.

**Comment by MarcAnt01** [comment]
> But why

In the buttons generated by bots you've added the possibility to see the url with mouse hover, so I thought why not here, as well?

**Comment by MarcAnt01** [comment]
> It is not even present in official app, also it is kind of waste to implement because when you click the discuss button, you are redirected to the group without joining it so you already can see the group's URL and other information.

I know how it works, in fact it's marked as enhancement and not feature request
