### ISSUE TITLE
Broken "Ask a volunteer" button

### ISSUE THREAD

**Issue by GameSpeck** [UnigramDev/Unigram#1495]
Go to settings > Ask a question and click the "Ask a volunteer" button, it won't open anything.

**Comment by MarcAnt01** [comment]
It works for me

**Comment by MarcAnt01** [comment]
Have you started a conversation with them in the past?

**Comment by GameSpeck** [comment]
> Have you started a conversation with them in the past?

Yes, which was never answered.

**Comment by MarcAnt01** [comment]
Anyway, it's a duplicate of https://github.com/UnigramDev/Unigram/issues/753

**Comment by FrayxRulez** [comment]
Can you: 
- Click 10 times on app version in Settings
- Set Verbosity level to `Debug`

**Comment by GameSpeck** [comment]
It's closed and says fixed but it isn't.

**Comment by MarcAnt01** [comment]
> It's closed and says fixed but it isn't.

In these cases it's better to comment under the issue and Fela or I will reopen it.

**Comment by FrayxRulez** [comment]
Can you please:
- Go to Settings
- Click 10 times on app version
- Set Verbosity level to `DEBUG (4)`
- Click on "Ask a volunteer"
- Go back to the hidden settings and send the log file to me?

**Comment by GameSpeck** [comment]
I am sorry I am unable to reproduce the issue again for some reason. I don't know why and what happened. I will close this ticket. Sorry again! :(

**Comment by MarcAnt01** [comment]
No problem, feel free to open it again in case you manage to reproduce it again👍👍
