### ISSUE TITLE
Hamburger menu overlaps the search bar

### ISSUE THREAD

**Issue by GameSpeck** [UnigramDev/Unigram#1498]
How to reproduce:
1. Right click any chat and select it
2. Click the cancel button
3. This:
![image](https://user-images.githubusercontent.com/43648146/80864776-6973aa80-8ca2-11ea-89a2-a9ca22137aa5.png)

It also happens when you go into your archived chats and go back

**Comment by FrayxRulez** [comment]
This is fixed
