### ISSUE TITLE
Channel notifications are still unread if they are read in other Telegram clients

### ISSUE THREAD

**Issue by Marocco2** [UnigramDev/Unigram#1502]
Unigram does not sync unread channel messages, leaving counter visible until I view the unread message in Unigram

Steps to reproduce:
1. Receive a message from a unmuted channel
2. Read the message with an official Telegram client (Unigram must be closed?)
3. Open Unigram

Expected:
Unigram should know that I've read the channel message

Reality:
Unigram still marks the channel message unread

Windows 20H1, Slow ring, last build available of 2/5/2020

**Comment by FrayxRulez** [comment]
If you're using Telegram on your iPhone/Mac then the bug is there and not in Unigram

**Comment by Marocco2** [comment]
Understood. I'm closing this

**Comment by FrayxRulez** [comment]
I just got told that the issue should be fixed in 6.1.2

**Comment by larsschellhas** [comment]
Perfect, I just wanted to report this :D
