### ISSUE TITLE
Deadlock using Punto Switcher

### ISSUE THREAD

**Issue by FrayxRulez** [UnigramDev/Unigram#1503]
The app UI thread deadlocks while using Punto Switcher.
This only happens after sending a message, and it seems to be connected to a Update.

**Comment by FrayxRulez** [comment]
This is actually caused by `INotificationsService.PlaySound()` method.

**Comment by pantosha** [comment]
> This is actually caused by `INotificationsService.PlaySound()` method.

You are right! I have disabled "In-app sounds" and deadlock is not reproduced

**Comment by Dyaminigo** [comment]
@FrayxRulez, the problem has not been fully fixed, as after opening Unigram you can find a blocking of the user interface once or twice after sending messages, then everything becomes in order.
If you close the program and reopen, you need to wait out one or two UI locks again so that nothing hangs.

**Comment by MarcAnt01** [comment]
> @FrayxRulez, the problem has not been fully fixed, as after opening Unigram you can find a blocking of the user interface once or twice after sending messages, then everything becomes in order.
> 
> If you close the program and reopen, you need to wait out one or two UI locks again so that nothing hangs.

What is your Unigram version?

**Comment by Dyaminigo** [comment]
@MarcAnt01, Unigram 3.15.4756. Installed from the MS Store, updated automatically.

**Comment by MarcAnt01** [comment]
It is fixed in 4.x that is still in pre-release stage and will take a bit to reach the store

**Comment by Dyaminigo** [comment]
Thank you for the information. I'll wait.
