### ISSUE TITLE
Load all the images after clearing cache

### ISSUE THREAD

**Issue by Daksh777** [UnigramDev/Unigram#1507]
If you clear cache in settings by going to Data and Storage > Storage Usage, and go back to the main screen, all the images and see this (no profile picture until chat is opened):
![image](https://user-images.githubusercontent.com/43648146/80919994-99967880-8d8a-11ea-9409-3b3f86922df4.png)

Edit: Stickers won't load at all even if you click a sticker, it still won't load

**Comment by FrayxRulez** [comment]
This should be fixed 👌
