### ISSUE TITLE
App doesn't search #tags in group info

### ISSUE THREAD

**Issue by Daksh777** [UnigramDev/Unigram#1508]
![image](https://user-images.githubusercontent.com/43648146/80920134-73bda380-8d8b-11ea-9490-4413cd9ec75d.png)
For example, if you click the # link,  it should search for it but instead it does nothing. Also the /command should not be highlighted as a link because it is not highlighted in official app

**Comment by MarcAnt01** [comment]
> ![image](https://user-images.githubusercontent.com/43648146/80920134-73bda380-8d8b-11ea-9490-4413cd9ec75d.png)
> For example, if you click the # link, it should search for it but instead it does nothing. Also the /command should not be highlighted as a link because it is not highlighted in official app

Group link?

**Comment by GameSpeck** [comment]
> Group link?

@retromusicapp it is
