### ISSUE TITLE
Hide edit folder ui until they aren't supported

### ISSUE THREAD

**Issue by xmha97** [UnigramDev/Unigram#1509]
Hello
I can't edit folders
![8w79Q9Dj2a](https://user-images.githubusercontent.com/23485114/80920989-9d290000-8d88-11ea-9eac-df837bdfa971.gif)

**Comment by MarcAnt01** [comment]
At the moment, they aren't editable, marking as bug, since the options shouldn't be shown

**Comment by MarcAnt01** [comment]
Closed since it works now
