### ISSUE TITLE
Score bar Quiz set at 100% instead of 0% when no one answer

### ISSUE THREAD

**Issue by ROSSI-ICS** [UnigramDev/Unigram#1512]
#visual

When no one answer scores bar should not be set at 100%
But at 0% like all other clients

![image](https://user-images.githubusercontent.com/55099634/80948656-db5b0980-8df2-11ea-8c5b-8c22e700720e.png)

Also it should say "NO ANSWERS" rather than "VIEW RESULTS"

**Comment by MarcAnt01** [comment]
Can you tell me repro steps? I can't see the bar until I vote an option

**Comment by FrayxRulez** [comment]
> Can you tell me repro steps? I can't see the bar until I vote an option

Any quiz using @QuizBot
