### ISSUE TITLE
Unigram crashes when in recent actions someone stops a poll 

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1513]

**Comment by FrayxRulez** [comment]
As the current state of Recent Actions I’m not sure this is worth of a ticket, but I would add it to the bucket here: #638

**Comment by MarcAnt01** [comment]
> As the current state of Recent Actions I’m not sure this is worth of a ticket, but I would add it to the bucket here: #638

It's been already added, but none of the other missing stuff causes a crash and prevents to check recent actions

**Comment by FrayxRulez** [comment]
Then I didn’t understand what this ticket is about, subjects are a bit confused

**Comment by MarcAnt01** [comment]
I'll give repro steps

**Comment by MarcAnt01** [comment]
1) Go to a group you're admin in;
2) Start a poll;
3) Stop it;
4) Go to recent actions

**Comment by MarcAnt01** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/dd4dddd5fdeb1395e8095b31ed37b7f31581ab90
