### ISSUE TITLE
Swap "Pin to top" and "Archive" menu options  

### ISSUE THREAD

**Issue by olehmisar** [UnigramDev/Unigram#1515]
The "Archive" option is used more often than the "Pin to top" options, so it would be logical to swap these two options to improve UX.

![image](https://user-images.githubusercontent.com/29802592/80977558-93a5a380-8e2d-11ea-8ba2-9000f71590c4.png)

**Comment by MarcAnt01** [comment]
TD has them inverted, as well

**Comment by MarcAnt01** [comment]
@FrayxRulez I can do that, if you agree

**Comment by olehmisar** [comment]
> TD has them inverted, as well
Actually, no, it has not :)
![image](https://user-images.githubusercontent.com/29802592/80979713-60184880-8e30-11ea-9873-a850bd97f018.png)

**Comment by MarcAnt01** [comment]
@olehmisar I mean inverted to their actual position in Unigram

**Comment by FrayxRulez** [comment]
> @FrayxRulez I can do that, if you agree

Feel free!
