### ISSUE TITLE
Default scheduled time should be 5 minutes ahead

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1520]
When scheduling a message the time shown by default in the time picker is the actual one.
It would be better to set the default time 5 minutes ahead like the iOS app.

**Comment by CornyjK** [comment]
@MarcAnt01 Not sure about that, it is the same as on Android and I do not see a reason for setting a 5 minute delay, better to display current time imho.

**Comment by MarcAnt01** [comment]
@CornyjK Android app shows one minute delay, it could be an idea, too

**Comment by MarcAnt01** [comment]
Telegram Desktop 10 minutes delay lol

**Comment by CornyjK** [comment]
@MarcAnt01 As Fela stated, user is going to change it anyways, so I see no point of changing the default time to anything, I do not see a real reason for sending message exactly 5 or 10 minutes later.

**Comment by MarcAnt01** [comment]
> @MarcAnt01 As Fela stated, user is going to change it anyways, so I see no point of changing the default time to anything, I do not see a real reason for sending message exactly 5 or 10 minutes later.

Yes, it's going to changed anyway, but the default option could be used even if 1 time out of 100. The way it is now on Unigram, it won't be used.

**Comment by hihain** [comment]
How about being able to select a default value in the settings? Something useful to me would be sth. like a fixed hour: Example: Set to 7am in the settings. Now it is 10pm. So the preselected datetime would be tomorrow at 7am.
