### ISSUE TITLE
Action Center notification not going to source channel

### ISSUE THREAD

**Issue by Yuraconst** [UnigramDev/Unigram#1521]
Instead of source channel (such as Unigram-Insiders), it goes to the talk list with nothing opened when clicking a notification within the Action Center sidebar.

**Comment by MarcAnt01** [comment]
Do you mean that discussion group gets opened instead of the channel_

**Comment by Yuraconst** [comment]
no, NOTHING is opened except the app itself - it just stays at the app's list of contacts/channels.

**Comment by MarcAnt01** [comment]
> no, NOTHING is opened except the app itself - it just stays at the app's list of contacts/channels.

And is this behavior limited to channels with a discussion group?

**Comment by Yuraconst** [comment]
Any kind of channel - chatroom or news stream - does this if I click a notification while the client software is not currently open.

**Comment by MarcAnt01** [comment]
I don't understand

**Comment by Yuraconst** [comment]
Belarussian news stream that has NO discussion channel attached also does this stuff.

**Comment by Yuraconst** [comment]
There's no easy way for me to show this bug, sadly.
BTW, I'm on Windows 10 Home x64

**Comment by MarcAnt01** [comment]
So basically once you click on a notification with the app closed, Unigram doesn't redirect to the channel, right?

**Comment by Yuraconst** [comment]
Yes, exactly - if the app is closed, it only opens and does nothing else. If it's already open, clicking a notification properly moves to the source channel (chatroom or loudspeaker)

**Comment by MarcAnt01** [comment]
Please, try to see if it happens with the app open, too

**Comment by Yuraconst** [comment]
as I said, if it's open the source channel redirect happens correctly.

**Comment by MarcAnt01** [comment]
Ah, so it's related to push notifications

**Comment by MarcAnt01** [comment]
@FrayxRulez should I leave that open or move it to push notifications bugs list?

**Comment by Yuraconst** [comment]
probably move it to "push notification bugs" since Action Center is basically the Push Notification module of Windows 10.

**Comment by MarcAnt01** [comment]
> probably move it to "push notification bugs" since Action Center is basically the Push Notification module of Windows 10.

No, that's wrong, action centre works for in-app ones, too

**Comment by Yuraconst** [comment]
Action Center turns all in-app notifs into Push IIRC (tried to send via the gitbot but it's a total squalapeno)

**Comment by MarcAnt01** [comment]
No, you confuse toast notifications with push ones

**Comment by Yuraconst** [comment]
@MarcAnt01 it mixes old and new notifications. Not sure if the "rich" notifs (with icon and/or reply field) are actually toast or push, official Telg uses either its own lib or the Win32 lib (in latter case the notifs are text-only)

**Comment by MarcAnt01** [comment]
Toast notifications are the new notifications that appear as heads-ups and in the action centre. They can be push (syncing Telegram servers to Microsoft ones, that doesn't require the app to be open) or in-app (keeping the app open, a new notification is sent from the app)

**Comment by Yuraconst** [comment]
@MarcAnt01 oh, that makes the qualification of this issue as push or non-push kinda confusing...

**Comment by MarcAnt01** [comment]
It's clearly related to push ones, closing

**Comment by Yuraconst** [comment]
@MarcAnt01 Ah, but maybe keeping the tray agent would have been wiser and avoided this issue by counting the app as open by the tray agent, thus treating notifs as Toast, not Push?

**Comment by Yuraconst** [comment]
Perhaps this issue relates to discontinuation of the tray agent of the app?

**Comment by MarcAnt01** [comment]
> @MarcAnt01 Ah, but maybe keeping the tray agent would have been wiser and avoided this issue by counting the app as open by the tray agent, thus treating notifs as Toast, not Push?

Sure, Desktop Bridge would have been great if it didn't interfere with online status

**Comment by Yuraconst** [comment]
Well, that explains why it's been dropped, but it's kind of a sad deal. Also, on the chat channel of this project within Telg itself, I'd suggest switching the bot to digest mode if possible, because it gets messy otherwise.

**Comment by MarcAnt01** [comment]
What bot are you talking about?

**Comment by Yuraconst** [comment]
the issue notification / cross-talk bot.

**Comment by MarcAnt01** [comment]
> the issue notification / cross-talk bot.

Still don't get what bot you're referring to

**Comment by MarcAnt01** [comment]
> the github bot (t.me/githubbot)

I am not in the Insiders group, but I suggest you not to use it to comment issues, since it is very buggy

**Comment by Yuraconst** [comment]
ok, got it...
