### ISSUE TITLE
Handwriting with pen crashes the app

### ISSUE THREAD

**Issue by cewbdex** [UnigramDev/Unigram#1523]
Tap the chat with pen, handwriting panel appears, write a text, click _enter_ on the handwriting panel, the app crashes.
![image](https://user-images.githubusercontent.com/9021297/81233089-5e987d00-8ff6-11ea-8f52-d99b498cdee3.png)
Figure 1: Handwriting panel

**Comment by MarcAnt01** [comment]
You should report it to Microsoft, since it happens in very app when you use handwriting. I can confirm this bug, tho

**Comment by MarcAnt01** [comment]
@cewbdex looks like Microsoft has fixed the major issue I was reporting in all the apps recently

**Comment by MarcAnt01** [comment]
Anyway, I am marking as "needs investigation" since some times the hand writing panel auto-closes and some other times it crashes the whole app

**Comment by FrayxRulez** [comment]
The crash seems to happen on UWP side, not sure about how I'm supposed to fix this.

**Comment by ADeltaX** [comment]
@FrayxRulez I agree, I have the same issue with other UWP apps as well.

**Comment by MarcAnt01** [comment]
@ADeltaX can you tell me which apps?

**Comment by ADeltaX** [comment]
MS Store, Search

**Comment by MarcAnt01** [comment]
> MS Store, Search

They don't crash for me, but they used to a week ago. Maybe it's a problem related to Surface devices

**Comment by cewbdex** [comment]
I own a Lenovo Yoga 730-15ikb with partly working ink screen and I can tell only Unigram crashes for me at the moment, working apps: Maps, Calendar, Store, Search, Alarms and Clock, not sure what else should I test.
