### ISSUE TITLE
Elevated text in search

### ISSUE THREAD

**Issue by Daksh777** [UnigramDev/Unigram#1525]
If you search for a user's messages, the text you type gets raised/elevated
![image](https://user-images.githubusercontent.com/43648146/81281326-52083900-9077-11ea-8adc-4f516f8a3097.png)

**Comment by MarcAnt01** [comment]
![image](https://user-images.githubusercontent.com/43090263/81297996-6e56a680-9074-11ea-805c-2d241ec23223.png)

**Comment by MarcAnt01** [comment]
Unable to reproduce

**Comment by GameSpeck** [comment]
> Unable to reproduce

I am Unigram 3.15.4756 and the text is elevated

**Comment by FrayxRulez** [comment]
> I am Unigram 3.15.4756 and the text is elevated

Same here

**Comment by MarcAnt01** [comment]
Same version but nothing😅
