### ISSUE TITLE
Redirect to @links in sticker pack names

### ISSUE THREAD

**Issue by Daksh777** [UnigramDev/Unigram#1526]
![image](https://user-images.githubusercontent.com/43648146/81285912-db226e80-907d-11ea-9145-8d129ddbf2f6.png)
The @ link should redirect to the respected channel/person/group i.e., make the @ mention a link

**Comment by FrayxRulez** [comment]
Give me the pack link

**Comment by GameSpeck** [comment]
> Give me the pack link

https://t.me/addstickers/kangpackexe

**Comment by MarcAnt01** [comment]
Edit: it seems to be working now. The only issue is that it opens behind the sticker pack. The popup should close first

**Comment by makisukurisu** [comment]
A link to a working sticker pack for testing:
https://t.me/addstickers/BIGEMOJI_Alice

**Comment by MarcAnt01** [comment]
This has been implemented now
