### ISSUE TITLE
Change folders shortcut to CTRL+num

### ISSUE THREAD

**Issue by FrayxRulez** [UnigramDev/Unigram#1527]
**Why**
As `F7` key isn't overridable and Function keys aren't really made for this use it's better to move to a more standard shortctus.

**What**
Change folders switch shortcut to `CTRL+num`.

**Comment by FrayxRulez** [comment]
`CTRL+num` is currently used to switch between pinned chats.
Is it better to disable it or to replace it with `CTRL+Shift+num`?

**Comment by MarcAnt01** [comment]
> `CTRL+num` is currently used to switch between pinned chats.
> Is it better to disable it or to replace it with `CTRL+Shift+num`?

Switch pinned chats to shift or Alt + num

**Comment by MarcAnt01** [comment]
This as been added at a certain point
