### ISSUE TITLE
Send Images via Copy-Paste

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#153]
When inserting an image from the clipboard it doesn´t get recognized as an image to send, but gets insertet into the textfield itself.

![image](https://cloud.githubusercontent.com/assets/14281234/21991672/ccca4370-dc13-11e6-86b0-75905495ade5.png)

Actually it seems like you can only paste in pictures which are captured by the snipping tool..

Would be nice, if copy-paste of pictures would just work as drag´n´drop of them does.

**Comment by FrayxRulez** [comment]
Planned for the future
