### ISSUE TITLE
Two-step settings back button does not work

### ISSUE THREAD

**Issue by cewbdex** [UnigramDev/Unigram#1532]
I do not have 2-step verification setup, when I click the setting, I am unable to click the back button, have to click the item in left menu to get back.

![image](https://user-images.githubusercontent.com/9021297/81295239-6563d600-9070-11ea-9555-dedf394c34de.png)
Figure 1: Settings menu

![image](https://user-images.githubusercontent.com/9021297/81295377-9a702880-9070-11ea-92ed-69d9e89fa354.png)
Figure 2: Two-step setup menu

Note: happens only in latest commit, works in current release.

**Comment by MarcAnt01** [comment]
Added #1248
