### ISSUE TITLE
Self-destruction timer is available in secret/group chats and channels in new media UI

### ISSUE THREAD

**Issue by cewbdex** [UnigramDev/Unigram#1533]
Setting it to any value and sending it make the message disappear.

![image](https://user-images.githubusercontent.com/9021297/81296512-4e25e800-9072-11ea-808d-03d98c2595ef.png)
Figure 1: Self destruction timer in secret chat

**Comment by FrayxRulez** [comment]
This is implemented in https://github.com/UnigramDev/Unigram/commit/28403b0d3d15aa64c373af0ad091fdec0c6b43a9
