### ISSUE TITLE
Outdated screenshot and Store description

### ISSUE THREAD

**Issue by cewbdex** [UnigramDev/Unigram#1536]
Should be replaced with new ones with current look as well as MS Store screenshots, also MS Store contains obsolete description.

**Comment by MarcAnt01** [comment]
I have already written a new description for the store some months ago, don't know what happened to it @FrayxRulez

**Comment by MarcAnt01** [comment]
As for the screenshots I think it would definitely make sense once folder are added👍

**Comment by MarcAnt01** [comment]
Done
