### ISSUE TITLE
Copy URL to clipboard

### ISSUE THREAD

**Issue by AvrahamTsaban** [UnigramDev/Unigram#1538]
On the dialogue box that appears after clicking a link, I can press "OK" to open the link, but if I want to open it on non-default browser, it is a little bit complicated.
I think one of two solutions should be provided:

1. Add a "Copy URL" button to the dialogue box.
2. allow selecting text by mouse from the dialogue box (using double click) and copying it.

![Capture](https://user-images.githubusercontent.com/60095552/81305064-90f1bb00-9086-11ea-89d3-cb31bfcae9e0.PNG)

**Comment by MarcAnt01** [comment]
Isn't pressing right click on the link and copying enough?

**Comment by AvrahamTsaban** [comment]
Oh, I did not notice this option...
So, if this is enough, we may close this ticket.

**Comment by MarcAnt01** [comment]
Yes, you have to click twice in all of your suggestions like you have to do atm, so it's not really worthy to change something
