### ISSUE TITLE
"Removed users" shows the list of users if no users are removed

### ISSUE THREAD

**Issue by Daksh777** [UnigramDev/Unigram#1558]

**Comment by MarcAnt01** [comment]
Apparently iOS app does the same

**Comment by GameSpeck** [comment]
> Apparently iOS app does the same

I don't know but I think it looks weird that all the users are listed in the removed users section.

**Comment by MarcAnt01** [comment]
Sure, in fact it'd be better not to show this section if empty

**Comment by FrayxRulez** [comment]
I can't reproduce this issue
