### ISSUE TITLE
Unread message counter in app icon

### ISSUE THREAD

**Issue by GameSpeck** [UnigramDev/Unigram#1559]
![image](https://user-images.githubusercontent.com/43648146/81495165-de129e80-92cb-11ea-950c-f4f642fd7e5b.png)
Just like Telegram

**Comment by MarcAnt01** [comment]
It's already present, in the latest versions it's just buggy, but the version from source code has already fixed taskbar counter

**Comment by GameSpeck** [comment]
> It's already present, in the latest versions it's just buggy, but the version from source code has already fixed taskbar counter

Are you sure? I enabled "count unread messages" but the icon isn't displaying new unread non-muted notifications.

**Comment by MarcAnt01** [comment]
Yes, it's a way to prevent https://github.com/UnigramDev/Unigram/issues/1485
