### ISSUE TITLE
@links do not work in profiles but channel descriptions

### ISSUE THREAD

**Issue by GameSpeck** [UnigramDev/Unigram#1560]
Channels:
![image](https://user-images.githubusercontent.com/43648146/81495301-f2a36680-92cc-11ea-8884-a05df97c3c56.png)
Profiles:
![image](https://user-images.githubusercontent.com/43648146/81495326-25e5f580-92cd-11ea-85b9-54e56a60f701.png)

**Comment by MarcAnt01** [comment]
That's intended since bio isn't meant to spam
