### ISSUE TITLE
Unigram not working on Windows N

### ISSUE THREAD

**Issue by cvevik** [UnigramDev/Unigram#1562]
There is some problem on Windows LTSC, application cannot start (tries to open, shows empty unigram window and then crashes). I have tried same version on non LTSC Windows and all works fine. The same issue is when trying to develop:

![image](https://user-images.githubusercontent.com/54305427/81500794-28504b80-92dd-11ea-8b82-73696f32a57f.png)

P.S. I have installed store manually because it isn't included in LTSC version but I can launch different app without any issue (WhatsApp, VLC etc...).

**Comment by MarcAnt01** [comment]
Well, all the app you've mentioned aren't UWPs...

**Comment by MarcAnt01** [comment]
LTSC has some problems in running UWPs, the only way seems to use the store. By sideloading them, there are a lot of issues

**Comment by cvevik** [comment]
> LTSC has some problems in running UWPs, the only way seems to use the store. By sideloading them, there are a lot of issues

I thought they were but ok, nevertheless, using store also without success

**Comment by MarcAnt01** [comment]
A friend of mine has been able to have Unigram running fully, I can send you the guide if you're interested

**Comment by cvevik** [comment]
> A friend of mine has been able to have Unigram running fully, I can send you the guide if you're interested

Yes, it would be helpful if you. I want to get it work.

**Comment by MarcAnt01** [comment]
https://forums.mydigitallife.net/threads/guide-add-store-to-windows-10-enterprises-sku-ltsb-ltsc.70741/page-30#post-1468779

**Comment by cvevik** [comment]
> https://forums.mydigitallife.net/threads/guide-add-store-to-windows-10-enterprises-sku-ltsb-ltsc.70741/page-30#post-1468779

but it is guide how to install Microsoft store? I have it already installed.

**Comment by MarcAnt01** [comment]
> > https://forums.mydigitallife.net/threads/guide-add-store-to-windows-10-enterprises-sku-ltsb-ltsc.70741/page-30#post-1468779
> 
> but it is guide how to install Microsoft store? I have it already installed.

You're right, then probably something has changed in the meanwhile

**Comment by FrayxRulez** [comment]
Hello @cvevik! Sorry for the late reply.
Could you write to me on Telegram? My username is the same as here.
I would like to dig a bit more into this as you have Visual Studio installed. 

Thanks!

**Comment by FrayxRulez** [comment]
Quick follow up: as usual the problem is actually Windows N.

**Comment by MarcAnt01** [comment]
@FrayxRulez Windows 10 LTSC and N are different things, as for Windows 10 N we already have another ticket, tracking this issue

**Comment by aayushbhatia06** [comment]
Hey there, for anyone wondering for a solution, its simple. All you need to do is download the "Windows Media Feature Pack for N and KN versions" (Official by Microsoft, plenty of guides for your build of Windows available). That fixes the problem

**Comment by FrayxRulez** [comment]
Hi @aayushbhatia06, thanks. Are you actually sure? I heard people in the past that tried to but without success!

**Comment by aayushbhatia06** [comment]
Well it fixed it for me on two of my machines, one point of difference is I did add it from Windows Settings application and not the website. Dont know if that makes a difference. 
Amazing app BTW guys, major kudos.

**Comment by MarcAnt01** [comment]
@cvevik is the solution for Windows N working for you on LTSC?

**Comment by FrayxRulez** [comment]
> @cvevik is the solution for Windows N working for you on LTSC?

He's actually on N, LTSC is just something additional to that.

**Comment by MarcAnt01** [comment]
Ah, so he's running Windows 10 N LTSC, that explains why in standard LTSC it works properly

**Comment by cvevik** [comment]
> @cvevik is the solution for Windows N working for you on LTSC?

Actually, no, I have already got media feature pack and installation from windows store and non windows store doesn't solves issue for me. Launching source code directly also.

**Comment by aayushbhatia06** [comment]
Again, long shot here but did you add it from Settings < Apps < Optional Feature < Add a Feature < Media Feature Pack

Because that is what fixed it for me. Not the one from the website.

**Comment by cvevik** [comment]
Ah, I thought you was talking about Unigram app, not Media Feature Pack. I have no such feature in a list there.

**Comment by aayushbhatia06** [comment]
That shouldn't happen. It's usually last on the list and easy to miss. Maybe check again ? Also, what build are you running ?

**Comment by MarcAnt01** [comment]
> That shouldn't happen. It's usually last on the list and easy to miss. Maybe check again ? Also, what build are you running ? 

He seems to be using N LTSC, not simple N like you

**Comment by FrayxRulez** [comment]
So, https://github.com/UnigramDev/Unigram/commit/318d548baace2f5e9f96f75558723149052198cb and https://github.com/UnigramDev/Unigram/commit/15934e2ac79a207665c0d4bed2469a11c7d68c1c are the first steps to make Unigram compatible with Windows N. Compatible doesn't mean functional tho, as users won't be able to play any kind of media in the app (videos, GIFs, audio, voice messages and so on)

**Comment by FrayxRulez** [comment]
So I fixed few issues here in the last few months and now the app should at least start. It would be nice to have more specific tickets to fix further issues.
