### ISSUE TITLE
Live tile is buggy

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1565]
Read messages are still in the tile and some times unread ones don't appear

**Comment by beerisgood** [comment]
Can confirm.
Closing the window and reopen fix it

**Comment by cewbdex** [comment]
I guess it is not worth fixing, as almost no one uses them and Microsoft will probably remove them at some point.

**Comment by MarcAnt01** [comment]
Can’t agree, MS could drop them with W10X that isn’t supposed to take up standard W10 soon.
It’s not a problem of implementing them from scratch, just of fixing them

**Comment by FrayxRulez** [comment]
But that's how live tiles work: you can enqueue updates, but you can't delete a specific one (eg a specific message). I think it would make much more sense to remove the feature and to keep only the badge.

**Comment by MarcAnt01** [comment]
Yes, if it can't be fixed, that could be a solution

**Comment by MarcAnt01** [comment]
> But that's how live tiles work: you can enqueue updates, but you can't delete a specific one (eg a specific message). I think it would make much more sense to remove the feature and to keep only the badge.

I just tried to use Windows Mail and after reading a mail it disappeared instantly

**Comment by FrayxRulez** [comment]
It probably deletes any tile update, not just the one for the specific email.

**Comment by beerisgood** [comment]
> It probably deletes any tile update, not just the one for the specific email.

For me this would be enough

**Comment by MarcAnt01** [comment]
Yeah I agree with @beerisgood

**Comment by FrayxRulez** [comment]
F
