### ISSUE TITLE
GalleryView: ConvertOf function gets wrong index on opening an image

### ISSUE THREAD

**Issue by hihain** [UnigramDev/Unigram#1567]
The GIF shows that if you click on an individual image of a gallery it always shows "totalamount of total amount" and only if you change the image using the gallery control the index of the current image is correctly shown.
![ezgif-1-718fbe48f69b](https://user-images.githubusercontent.com/1473059/81550121-15428780-9380-11ea-8460-6133a735c0fc.gif)

**Comment by FrayxRulez** [comment]
This is mitigated in https://github.com/UnigramDev/Unigram/commit/19d7d9eac5d6bb2c254b5411776e3f84ee78a8bf

Remember however that the position is just a guessing till the last sent/received media is loaded by the gallery.
