### ISSUE TITLE
Replies to albums with a caption aren't shown

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1570]
Messages are shown, but without the quote to the album

**Comment by FrayxRulez** [comment]
I don’t understand

**Comment by MarcAnt01** [comment]
> I don’t understand

Have you read my updated description?

**Comment by FrayxRulez** [comment]
> Have you read my updated description?

Yes

**Comment by MarcAnt01** [comment]
A user sends an album containing but attaches a small description to it. If I answer to this message, I see the quote. Once I leave the chat and open it again, the message appears with no quote. Is that clear for you now?
