### ISSUE TITLE
Add a secret chat indicator when forwarding a message

### ISSUE THREAD

**Issue by cewbdex** [UnigramDev/Unigram#1572]
When forwarding a message to someone, who has a normal and a secret chat with you, it is not possible to determine which one is which when forwarding a message.

![image](https://user-images.githubusercontent.com/9021297/81608241-3b931200-93d6-11ea-8742-818945469fc8.png)
Figure 1: Forwarding message

**Comment by MarcAnt01** [comment]
Duplicate or #889
