### ISSUE TITLE
Glitched inline placeholer/text

### ISSUE THREAD

**Issue by GameSpeck** [UnigramDev/Unigram#1576]
![image](https://user-images.githubusercontent.com/43648146/81692420-00e3b500-947c-11ea-9bb0-702dc8f0ef49.png)
The inline text overlaps the bot's username

**Comment by MarcAnt01** [comment]
Please use the ticket for inline bots bugs

**Comment by GameSpeck** [comment]
> Please use the ticket for inline bots bugs

What do you mean?

**Comment by MarcAnt01** [comment]
https://github.com/UnigramDev/Unigram/issues/690

**Comment by MarcAnt01** [comment]
Move all your bug reports there

**Comment by GameSpeck** [comment]
> Move all your bug reports there

I don't know how to

**Comment by MarcAnt01** [comment]
> > Move all your bug reports there
> 
> I don't know how to

Just add them as comments (I'd suggest you to click edit, copy and paste)
