### ISSUE TITLE
Glitch when switching chats when an inline bot is used

### ISSUE THREAD

**Issue by GameSpeck** [UnigramDev/Unigram#1578]
How to reproduce:
1. Type any inline bot's name (for eg, [at]rextester_bot)
2. Don't type anything (You will only see the inline text placeholder)
3. Switch chats
4. This: 
![image](https://user-images.githubusercontent.com/43648146/81694232-b4e63f80-947e-11ea-8861-dd8fe97fcaf3.png)

**Comment by MarcAnt01** [comment]
Please use the ticket for inline bots bugs

**Comment by GameSpeck** [comment]
@MarcAnt01 What do you mean?

**Comment by MarcAnt01** [comment]
Already answered in the other ticket
