### ISSUE TITLE
Inline preview doesn't disappear when bot's name is removed

### ISSUE THREAD

**Issue by GameSpeck** [UnigramDev/Unigram#1579]
How to reproduce:
1. Use any inline bot (for eg, [at]rextester_bot)
2. Type anything and then quickly select all using ctrl+a and delete it
3. This: 
![image](https://user-images.githubusercontent.com/43648146/81694772-608f8f80-947f-11ea-8e07-175fc30ec20c.png)

**Comment by MarcAnt01** [comment]
Please use the ticket for inline bots bugs
