### ISSUE TITLE
Broken image preview in link tab

### ISSUE THREAD

**Issue by GameSpeck** [UnigramDev/Unigram#1580]
Unigram: 
![image](https://user-images.githubusercontent.com/43648146/81695282-0d6a0c80-9480-11ea-8e45-8149f609832d.png)

Telegram: 
![image](https://user-images.githubusercontent.com/43648146/81695344-1b1f9200-9480-11ea-91d1-0946af568dfe.png)

**Comment by MarcAnt01** [comment]
Duplicate of https://github.com/UnigramDev/Unigram/issues/944
