### ISSUE TITLE
Ping with notification to all members doesn't work

### ISSUE THREAD

**Issue by GameSpeck** [UnigramDev/Unigram#1581]
It instead pins without any notification to the members of the group

**Comment by FrayxRulez** [comment]
Fake news:
https://github.com/UnigramDev/Unigram/blob/a05616a184c050e2dff7ff59e918c3a5b7589e63/Unigram/Unigram/ViewModels/DialogViewModel.Messages.cs#L808

**Comment by MarcAnt01** [comment]
Yes, furthermore according to my tests it has always worked
