### ISSUE TITLE
Exception when sending a picture from in-app camera

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1583]
![image](https://user-images.githubusercontent.com/43090263/81712198-a135db80-9474-11ea-9251-c156de2f2dbd.png)

**Comment by cewbdex** [comment]
We have encountered, you can fix it by removing the if statement for the moment.

**Comment by MarcAnt01** [comment]
> We have encountered, you can fix it by removing the if statement for the moment.

Where?

**Comment by cewbdex** [comment]
If you start the app from VS with debugger attached, it will point you, but I guess not worth the time, will be probably fixed soon, otherwise it works perfectly.

**Comment by MarcAnt01** [comment]
> If you start the app from VS with debugger attached, it will point you, but I guess not worth the time, will be probably fixed soon, otherwise it works perfectly.

I usually don't use it, that's why I was asking, will wait for the fix at this point😄

**Comment by MarcAnt01** [comment]
I think @hihain commit fixed that

**Comment by cewbdex** [comment]
Works for me.
