### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by kakomato** [UnigramDev/Unigram#1585]
![immagine](https://user-images.githubusercontent.com/65250412/81732630-0b5c7980-9491-11ea-8030-b69f1d3f691e.png)

**Comment by kakomato** [comment]
![immagine](https://user-images.githubusercontent.com/65250412/81732729-31821980-9491-11ea-9ffd-60b311776aa1.png)

**Comment by MarcAnt01** [comment]
Kindly ask repro steps and a normal title

**Comment by kakomato** [comment]
hi, dont change section CONTACTS TEAM CHANNELS and BOT

**Comment by MarcAnt01** [comment]
So this exception is thrown when moving among filters, right?

**Comment by FrayxRulez** [comment]
No the exception is thrown when you open advanced settings

**Comment by FrayxRulez** [comment]
> hi, dont change section CONTACTS TEAM CHANNELS and BOT

Will fix it

**Comment by MarcAnt01** [comment]
> No the exception is thrown when you open advanced settings

Then why is that referred to the second picture?

**Comment by kakomato** [comment]
I thought that the error of the first and second photos were connected

**Comment by MarcAnt01** [comment]
> I thought that the error of the first and second photos were connected

Can you explain what's the problem in the second photo?

**Comment by kakomato** [comment]
the second image: you cannot change between bot group contacts

**Comment by kakomato** [comment]
> 
> 
> > hi, dont change section CONTACTS TEAM CHANNELS and BOT
> 
> Will fix it

thanksss

**Comment by FrayxRulez** [comment]
It fixes by itself on Microsoft.UI.Xaml 2.4
