### ISSUE TITLE
Can't migrate a basic group to supergroup

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1595]
Changing history visibility option works properly, but it seems to have no effect in changing the group type.

**Comment by FrayxRulez** [comment]
Migration happens properly here

**Comment by xperiandri** [comment]
Actually, it is not.
After I changed the history type, group history is no longer visible in Unigram
![image](https://user-images.githubusercontent.com/2365592/101477200-93d3c780-3957-11eb-9704-9644d0469c42.png)
And right after changing it displays a button to remove the group in place of chat message input.
