### ISSUE TITLE
Switching sound output during call (speakerphone)

### ISSUE THREAD

**Issue by benji2020** [UnigramDev/Unigram#1601]
Hi

An enhancement/mobile centric feature would be to have a speakerphone button during a voice call, at the moment the option is in the settings menu.

Using Windows 10 mobile, but could equally apply to any other form factor device.

Thanks.

**Comment by MarcAnt01** [comment]
Unigram does not support Windows 10 Mobile, so that doesn’t make sense on the other platforms

**Comment by benji2020** [comment]
> 
> 
> Unigram does not support Windows 10 Mobile

Does not support or is not supported on? Because it works quite well on it. Maybe I should keep quiet. :)

**Comment by MarcAnt01** [comment]
> > Unigram does not support Windows 10 Mobile
> 
> Does not support or is not supported on? Because it works quite well on it. Maybe I should keep quiet. :)

You are probably running an outdated version and, whatever, there's no support now, it has also been removed from the store
