### ISSUE TITLE
Incorrect text selection

### ISSUE THREAD

**Issue by GameSpeck** [UnigramDev/Unigram#1602]
![image](https://user-images.githubusercontent.com/43648146/82069986-bd927c00-96f1-11ea-9a2a-298740ab920d.png)
It even goes beyond the actual text

**Comment by FrayxRulez** [comment]
That part is reserved for the timestamp of the message.
Selectable area isn't customizable for developers, so there's no way to fix this.
I'm not sure it can even be considered a real issue, and it also happen with any message, not just mono.

**Comment by GameSpeck** [comment]
Oh okay. Although it is selected correctly in the official app but I am not sure if the case is different with Unigram

**Comment by FrayxRulez** [comment]
Unigram is built on top of UWP framework while Telegram Desktop is built on top of Qt, they are different platforms with different pros and cons

**Comment by FrayxRulez** [comment]
This is done here as a experimental feature: https://github.com/UnigramDev/Unigram/commit/b23668d6e8102b436d998f3a0097e9cfb4760202
