### ISSUE TITLE
New send media ui focus is on buttons instead of textbox

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1605]

**Comment by cewbdex** [comment]
I'd close this in favor of #1607, because this issue would not make sense.

**Comment by cewbdex** [comment]
Focuses on picture for me sometimes.

**Comment by FrayxRulez** [comment]
Done in https://github.com/UnigramDev/Unigram/commit/567514783847a03b473eca27424c3f8d91e7f1d5
