### ISSUE TITLE
Make previewing stickers better

### ISSUE THREAD

**Issue by Daksh777** [UnigramDev/Unigram#1611]
Currently what happens is when you view a sticker pack, and hold click on any of its stickers, it will only preview that sticker (also it takes a lot of time to preview one, might as well reduce it) despite the fact you are holding left mouse button and hovering over other stickers.
Just like in official app, you hold click on one of the sticker in the sticker pack and in like a second, it will preview it and you can hover your mouse over other stickers to preview other stickers too

Edit (better explanation, thanks to Zenexer):  If you preview one sticker, then drag your mouse to other stickers, the preview switches to the new sticker over which you’re now hovering. This allows you to preview multiple stickers quickly.

**Comment by MarcAnt01** [comment]
https://github.com/UnigramDev/Unigram/issues/546

**Comment by GameSpeck** [comment]
Uhh, should I post this in that issue?

**Comment by MarcAnt01** [comment]
I think that's a duplicate since sticker preview isn't working

**Comment by GameSpeck** [comment]
Sticker preview does work but its behaviour needs to be changed.
![image](https://user-images.githubusercontent.com/43648146/82124121-a2d80a00-97ba-11ea-91bf-8971ee6f224b.png)

**Comment by MarcAnt01** [comment]
Never had it working in any way

**Comment by GameSpeck** [comment]
> Never had it working in any way

What do you mean? It clearly works

**Comment by MarcAnt01** [comment]
> > Never had it working in any way
> 
> What do you mean? It clearly works

Not here and in the PCs of the people who commented that issue

**Comment by Zenexer** [comment]
On at least some official clients, like TDesktop, if you preview one sticker, then drag your mouse or finger to other stickers, the preview switches to the new sticker over which you’re now hovering. This allows you to preview multiple stickers quickly.

I believe that’s the behavior being requested here.

**Comment by GameSpeck** [comment]
Hmm, I am using a laptop so maybe that's the reason?

**Comment by MarcAnt01** [comment]
No

**Comment by GameSpeck** [comment]
> On at least some official clients, like TDesktop, if you preview one sticker, then drag your mouse or finger to other stickers, the preview switches to the new sticker over which you’re now hovering. This allows you to preview multiple stickers quickly.
> 
> I believe that’s the behavior being requested here.

Exactly, I wasn't able to put it in words property

**Comment by Zenexer** [comment]
#546 is about previewing stickers in a single sticker pack when one sticker is sent by someone else to a chat.

This ticket is requesting a change in behavior to previewing the stickers that have already been added prior to sending one.

Two different interfaces, two different issues. This isn’t a duplicate.

**Comment by MarcAnt01** [comment]
> #546 is about previewing stickers in a single sticker pack when one sticker is sent by someone else to a chat.
> 
> This ticket is requesting a change in behavior to previewing the stickers that have already been added prior to sending one.
> 
> Two different interfaces, two different issues. This isn’t a duplicate.

Yes, thanks to your explanation it's clear now

**Comment by GameSpeck** [comment]
Sorry, my English is poor, it was difficult for me to explain this.

**Comment by GameSpeck** [comment]
> No

Then how is it possible that it's working for me?

**Comment by MarcAnt01** [comment]
![image](https://user-images.githubusercontent.com/43090263/82124436-5206e800-979f-11ea-9f86-7c0ead181549.png)

**Comment by GameSpeck** [comment]
You should try holding the sticker for a bit long, it takes longer than the official app to preview the sticker

**Comment by MarcAnt01** [comment]
> You should try holding the sticker for a bit long, it takes longer than the official app to preview the sticker

Yep and it doesn't work

**Comment by Zenexer** [comment]
Again, you’re both talking about two different interfaces. One has the preview feature, the other probably doesn’t.

**Comment by MarcAnt01** [comment]
I don't think so, having repro steps maybe would help me to understand that better

**Comment by GameSpeck** [comment]
> I don't think so, having repro steps maybe would help me to understand that better

Should I record my screen and send it to show what am I talking about?

**Comment by MarcAnt01** [comment]
I know what is sticker preview from a pack, but cannot understand from where you're loading the pack,

**Comment by GameSpeck** [comment]
![gif](https://user-images.githubusercontent.com/43648146/82125076-09f8bd00-97c1-11ea-808d-e01be13bd40e.gif)
By clicking on one of the stickers in the chat to open the pack

**Comment by MarcAnt01** [comment]
@Zenexer not working from there 🤷‍♂️

**Comment by Zenexer** [comment]
No idea, then. Regardless, that’s a different issue, #546. This issue is about an enhancement to the existing functionality.

**Comment by MarcAnt01** [comment]
No doubt about that

**Comment by GameSpeck** [comment]
Do you need logs, because I am able to preview every sticker?

**Comment by MarcAnt01** [comment]
Not needed, thanks

**Comment by MarcAnt01** [comment]
Done in https://github.com/UnigramDev/Unigram/commit/93e0b60eb96bd77e7d2f6332359a4dd3648ddf1a
