### ISSUE TITLE
Options for video quality in the new media sender

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1614]

**Comment by cewbdex** [comment]
Thought I covered it by #1553

**Comment by FrayxRulez** [comment]
Yep, I have no plans to add video quality settings in the new UI, at least at the beginning. I’m quite sure that on desktop video compression isn’t needed.

**Comment by MarcAnt01** [comment]
> Thought I covered it by #1553

Haven’t seen the edit

**Comment by MarcAnt01** [comment]
> Yep, I have no plans to add video quality settings in the new UI, at least at the beginning. I’m quite sure that on desktop video compression isn’t needed. 

Yeah, I have just mentioned it, since the old media seder had it
