### ISSUE TITLE
Can't send pictures from browser

### ISSUE THREAD

**Issue by MattiaBLX** [UnigramDev/Unigram#1617]
**How to reproduce:**
Step 1: Copy a photo from internet (Tested on Edge/Chrome on Facebook)
Step 2: Paste it in chat.

Exception:
![image_2020-05-18_10-39-53](https://user-images.githubusercontent.com/36816061/82192783-bc7d6c80-98f4-11ea-9bfc-23fe7e8289cd.png)

**Comment by MarcAnt01** [comment]
Does that happen with every picture?

**Comment by FrayxRulez** [comment]
It happens with pictures that have an alt-text, probably in any Chromium browser
