### ISSUE TITLE
Spell checking always enabled

### ISSUE THREAD

**Issue by Iruwen** [UnigramDev/Unigram#1618]
Either I am missing an option or Unigram doesn't seem to honor the Windows app spell checking options. I disabled everything under Devices > Typing and when I'm typing a message it's still all underlined red (since I'm writing English on a German windows).

![image](https://user-images.githubusercontent.com/11341130/82218944-ef3b5b00-991c-11ea-8700-1102e10aa38c.png)

![image](https://user-images.githubusercontent.com/11341130/82219145-27db3480-991d-11ea-920e-3af579a91636.png)

**Comment by FrayxRulez** [comment]
This is a Windows bug :'( please report it in Feedback Hub.
I closed another issue about this yesterday. 
UWP apps can't look into your system settings because of all the "sandbox" thing and so on, so there's no way for me to fix this apart from adding a "Disable spellcheck" option in the app, to force disable it.

**Comment by REDLINK** [comment]
Oh, thanks only searched in open issues I guess. Such an option would be great as that's really super annoying for international users ;(

**Comment by Iruwen** [comment]
Oh, thanks I only searched in open issues I guess. That option would still be great as it's super annoying for international users as you can see ;(

**Comment by MarcAnt01** [comment]
> Oh, thanks only searched in open issues I guess. Such an option would be great as that's really super annoying for international users ;(

The option has been added in the source code, it will take some time to reach the Store version tho

**Comment by FrayxRulez** [comment]
> Oh, thanks I only searched in open issues I guess. That option would still be great as it's super annoying for international users as you can see ;(

I’m a international user as well, but for some reason on my PC those settings are respected

**Comment by Iruwen** [comment]
Underlining wouldn't be the worst part, but it actually autocorrects stuff, including German capitalization in the middle of sentences.
Maybe some privacy setting, there's none I'd consider related to this though.
