### ISSUE TITLE
Hide playing bar in GIFs in "full screen" view

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1620]

**Comment by FrayxRulez** [comment]
I think it's actually handy. I often want to pause GIFs to check a specific frame.

**Comment by MarcAnt01** [comment]
> I think it's actually handy. I often want to pause GIFs to check a specific frame.

No Telegram official client has this feature, moreover having the bar playing quickly (since GIFs are usually short) is annoying to me

**Comment by cewbdex** [comment]
Maybe the solution could be to not display it when you open the GIF/display it after a click?

**Comment by MarcAnt01** [comment]
Why not
