### ISSUE TITLE
Zoom low-resolution GIFs in "full screen" view

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1621]
Unigram 
![image](https://user-images.githubusercontent.com/43090263/82306445-5ad60480-99bf-11ea-8e3e-009111a1d159.png)
Telegram for iOS
![image](https://user-images.githubusercontent.com/43090263/82306474-632e3f80-99bf-11ea-8e6c-5ff2e6b4dc79.png)

**Comment by FrayxRulez** [comment]
Telegram iOS is optimized for small screens, Unigram is optimized for big screens, hence this doesn't really make sense

**Comment by MarcAnt01** [comment]
The GIF is bigger in my 4.7 iPhone 7 than in my 13.5 inches Surface Book 2
