### ISSUE TITLE
Do not select/highlight "OK" by default in clear history

### ISSUE THREAD

**Issue by GameSpeck** [UnigramDev/Unigram#1623]
![image](https://user-images.githubusercontent.com/43648146/82334151-3735ad00-9a05-11ea-81ed-e6bdcc8a1d90.png)
What if someone presses the enter button accidentaly and everything's gone?
Also clicking anywhere else on that popup still makes the "OK" button to remain highlighted

**Comment by cewbdex** [comment]
I am not sure that someone would "accidentally" right click a group, click leave group and then OK or enter.

**Comment by MarcAnt01** [comment]
> I am not sure that someone would "accidentally" right click a group, click leave group and then OK or enter.

Agree. Anyway, focus is automatically set on left button

**Comment by GameSpeck** [comment]
> I am not sure that someone would "accidentally" right click a group, click leave group and then OK or enter.

Yeah I agree but what if someone just clicks clear history option, and by mistakes clicks the enter button? Could be a small disaster for him.

**Comment by MarcAnt01** [comment]
Well, the alert itself is an additional protection

**Comment by cewbdex** [comment]
`Deletes account by mistake`

**Comment by MarcAnt01** [comment]
![C8D998B5-57DC-451C-8463-105ABF9DE29E](https://user-images.githubusercontent.com/43090263/82416531-794d0600-9a7a-11ea-9001-2da6bd4d2bb2.jpeg)
