### ISSUE TITLE
Exception when I go to "Advanced"

### ISSUE THREAD

**Issue by Sav22999** [UnigramDev/Unigram#1626]
If I go to "Advanced" in Settings it returns a message
![image](https://user-images.githubusercontent.com/32335378/82554208-ca85f400-9b65-11ea-8f8e-848e7e2b7779.png)

**Comment by MarcAnt01** [comment]
Hello, there's already a closed ticket about this bug. It has been fixed in the source code, it'll take a bit to reach Store version.
