### ISSUE TITLE
Focus on chats list when opening the app

### ISSUE THREAD

**Issue by Daksh777** [UnigramDev/Unigram#1629]
![image](https://user-images.githubusercontent.com/43648146/82635329-9968fa80-9c1d-11ea-8164-18398880c92c.png)

**Comment by MarcAnt01** [comment]
Where would you prefer the focus to be set?

**Comment by FrayxRulez** [comment]
> Where would you prefer the focus to be set?

I'm not sure it is even possible to choose where to set the focus

**Comment by MarcAnt01** [comment]
@FrayxRulez mail app does that on the first mail in chats list for example

**Comment by FrayxRulez** [comment]
> @FrayxRulez mail app does that on the first mail in chats list for example

Ask them how they do

**Comment by MarcAnt01** [comment]
No, I'm OK with it being set on the hamburger menu

**Comment by GameSpeck** [comment]
> Where would you prefer the focus to be set?

There shouldn't be focus on anything

**Comment by FrayxRulez** [comment]
> There shouldn't be focus on anything

Well that's not how it works 😂

**Comment by MarcAnt01** [comment]
That's not how it is supposed to work

**Comment by GameSpeck** [comment]
> That's not how it is supposed to work

I didn't know. Maybe focus on the first chat?

**Comment by FrayxRulez** [comment]
Done
