### ISSUE TITLE
Noise after voice messages

### ISSUE THREAD

**Issue by deltapir** [UnigramDev/Unigram#163]
There is a noise coming from the speaker of the smartphone after a voice message been played and it stops just some seconds later. Is it OS or Unigram related?

**Comment by larsschellhas** [comment]
the Speaker seems to stay activated for some more seconds, before stopping to play white noise

**Comment by larsschellhas** [comment]
@frayxrulez, do you have any ideas on this? I've just tested it and there is still a little peeeeeep for some seconds, but not as bad as I remembered it. 
Does not bother me at all anymore... So, should we close it?

**Comment by larsschellhas** [comment]
I think this can be closed. There is some sound for a few seconds but this can be related to the system and overall shouldn´t bother anyone anymore.
