### ISSUE TITLE
Error when changing account in Unigram

### ISSUE THREAD

**Issue by GameSpeck** [UnigramDev/Unigram#1634]
Changing from 2nd account to main account on Unigram v4.0.4893
![image](https://user-images.githubusercontent.com/43648146/82749211-35813600-9dc5-11ea-9566-4825f423851b.png)
![image](https://user-images.githubusercontent.com/43648146/82749216-39ad5380-9dc5-11ea-92d4-8f0917654401.png)

**Comment by FrayxRulez** [comment]
I think that this is actually the same as #1641, so I'm closing this
