### ISSUE TITLE
WWW folder remains even if deleted 

### ISSUE THREAD

**Issue by GameSpeck** [UnigramDev/Unigram#1635]
![image](https://user-images.githubusercontent.com/43648146/82749917-22bd3000-9dca-11ea-9998-56fcf8acddc3.png)
It appears again after restarting the app

**Comment by FrayxRulez** [comment]
Folders aren’t implemented, stated this so many times... 🤓

**Comment by GameSpeck** [comment]
Oh, I am sorry, I thought that they are because of the Folders option in settings

**Comment by adrianghc** [comment]
> Folders aren’t implemented, stated this so many times... 🤓

Even so, does that folder need to be there while we wait for folder functionality to be implemented? I'm not sure I see the point.

**Comment by adrianghc** [comment]
> Folders aren’t implemented, stated this so many times... 🤓

@FrayxRulez Even so, does that folder need to be there while we wait for folder functionality to be implemented? I'm not sure I see the point.

**Comment by MarcAnt01** [comment]
> > Folders aren’t implemented, stated this so many times... 🤓
> 
> @FrayxRulez Even so, does that folder need to be there while we wait for folder functionality to be implemented? I'm not sure I see the point.

Because it's a beta version and once TDLib support is ready Fela doesn't need to do anything more.

**Comment by adrianghc** [comment]
> > > Folders aren’t implemented, stated this so many times... 🤓
> > 
> > 
> > @FrayxRulez Even so, does that folder need to be there while we wait for folder functionality to be implemented? I'm not sure I see the point.
> 
> Because it's a beta version and once TDLib support is ready Fela doesn't need to do anything more.

Fair enough with the beta version. I think it would bother me less if it said "archived conversations" (which is what it shows right now) or something like that, rather than the somewhat obnoxious chain of W's. Though obviously I'm in no position to make any sort of demand.
