### ISSUE TITLE
Expand clickable area of go to bottom/mention symbol to the numeric badge

### ISSUE THREAD

**Issue by alighamari** [UnigramDev/Unigram#1642]
![image](https://user-images.githubusercontent.com/24440862/82764811-f1bf1880-9e26-11ea-9b3a-1f5d98accfc3.png)

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/7a8adbee1641451f04b7044f51d877e04a8bc86f
