### ISSUE TITLE
glitch on opening of new gifs panel with auto play 

### ISSUE THREAD

**Issue by alighamari** [UnigramDev/Unigram#1650]
for a frame gifs are like this and then it gets normal 
full gif:
![glitch](https://user-images.githubusercontent.com/24440862/82843454-63b06400-9ef2-11ea-95f4-0ef517e75f47.gif)
screenshot of that single frame 
![image](https://user-images.githubusercontent.com/24440862/82843474-72971680-9ef2-11ea-990b-1ac4ec83783d.png)
if you see the gif below 60fps it cant be seen

**Comment by MarcAnt01** [comment]
Do you experience that only the first time you open the panel or every time?

**Comment by FrayxRulez** [comment]
This should be fixed in https://github.com/UnigramDev/Unigram/commit/22dfcd3a865b041280c8ba1b0c89ece22b59a678
