### ISSUE TITLE
Add a check icon when forwarding to a user in search menu

### ISSUE THREAD

**Issue by GameSpeck** [UnigramDev/Unigram#1651]
![image](https://user-images.githubusercontent.com/43648146/82863908-f2e46880-9f40-11ea-9c19-3463f274229f.png)
When you click the search icon, it shows the People tab and when you click on the person to forward to, nothing happens (no check mark, no color change) so you don't know if that user is selected or not.
My suggestion is to add a check icon when the user is selected

Edit: Even in the recent tab there is no check icon

**Comment by MarcAnt01** [comment]
I have already reported that a year ago in this ticker https://github.com/UnigramDev/Unigram/issues/1149
