### ISSUE TITLE
Animated stickers and gifs in the panel don't autoplay if I don't scroll down a bit in the panel

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1653]
Scrolling a bit to the bottom makes them animated.

**Comment by FrayxRulez** [comment]
This should be mitigated by https://github.com/UnigramDev/Unigram/commit/bd4e3eced97e3a469e0a3f8cc9069dd615c84ad2

**Comment by MarcAnt01** [comment]
I don't experience this problem any longer
