### ISSUE TITLE
Animated sticker set thumbnail won't play

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1654]
Unigram
![image](https://user-images.githubusercontent.com/43090263/82881307-d3007500-9f3f-11ea-9a67-fde41bf67eb7.png)

Telegram Desktop
![image](https://user-images.githubusercontent.com/43090263/82881369-e7dd0880-9f3f-11ea-8225-b7293c8c7259.png)

**Comment by MarcAnt01** [comment]
In Unigram 7.9 they're not visible at all, meaning no thumbnail (even not animated) is present

**Comment by FrayxRulez** [comment]
Implemented in https://github.com/UnigramDev/Unigram/commit/02e1690431d573f5bd766e04d6b2758d4371dd50
