### ISSUE TITLE
Statistics are removed in Unigram Beta. Can return to the original Unigram?

### ISSUE THREAD

**Issue by ClassRoomm** [UnigramDev/Unigram#1655]
A feature has been removed in the [**Unigram Beta version**](https://www.microsoft.com/en-us/p/unigram-mobile-messenger-telegram-client/9nsd4t15qlfx) of Windows 10 Mobile. 

**1-)** I search in group messages. Search results statistics have been removed. This affects us negatively. Knowing the search statistics saves time. A word has been used 300 or 1000 times. I read the messages without knowing this. It's boring not knowing when the call will end. I would like this feature to be added again.

**2-)** Also, group statistics have been removed. How many files have been shared, how many links have been added. These don't have Unigram Beta. Respects.

**Note:** I attached two photos on the subject.
![search](https://user-images.githubusercontent.com/65954507/82898649-58951c80-9f62-11ea-8480-4cae3588f00c.jpg)
![group](https://user-images.githubusercontent.com/65954507/82898641-5632c280-9f62-11ea-94b6-e77ebf8b48ec.jpg)

**Comment by FrayxRulez** [comment]
Profile details page has been aligned to official apps design, where counters for shared media have been removed as well.

**Comment by ClassRoomm** [comment]
> 
> 
> Profile details page has been aligned to official apps design, where counters for shared media have been removed as well.

So, will these features no longer be added? Removed from space shortage in the new version. Did I get right.

**Comment by MarcAnt01** [comment]
Hello, you aren’t using Unigram, but Unigram mobile, please use their GitHub for future bug reports
