### ISSUE TITLE
Make image copy-able even when it is in full-screen

### ISSUE THREAD

**Issue by omfgnuts** [UnigramDev/Unigram#1656]
When you right-click on the image in chat, there is an option to copy it to buffer and then quickly paste it anywhere you want.

When you open that same image in full-screen mode, the option is not there  

:3

**Comment by alighamari** [comment]
there is a button now but Ctrl+C is broken
version 5056

**Comment by omfgnuts** [comment]
I also think it should be "Copy Image", rather than just "Copy"

**Comment by MarcAnt01** [comment]
@omfgnuts @alighamari I am moving this report to https://github.com/UnigramDev/Unigram/issues/731 since both shortcuts aren't working in the same condition. As for the "Copy Image" there's no string, so it would be untranslated for other languages
