### ISSUE TITLE
Icons are not aligned in sticker panel

### ISSUE THREAD

**Issue by Dum4G** [UnigramDev/Unigram#1658]
Stock W10 Scaling
FHD resolution
In-Unigram text scale is at 4/7
Size of the window/full screen doesn't make a difference
![image](https://user-images.githubusercontent.com/5430116/82913562-2215cc80-9f77-11ea-8ec6-7a7fd4f35996.png)
![image](https://user-images.githubusercontent.com/5430116/82913590-2a6e0780-9f77-11ea-9e1e-93f421516de3.png)

**Comment by FrayxRulez** [comment]
They are meant to scroll
