### ISSUE TITLE
Set focus on Send after pasting an image

### ISSUE THREAD

**Issue by omfgnuts** [UnigramDev/Unigram#1659]
When pasting an image, the focus stays on the image (see attached picture). It would be more convenient if the focus will be on [Send].

![image](https://user-images.githubusercontent.com/845482/82922085-d3216480-9f81-11ea-9ade-b2c70d4fe15f.png)

Thank you!

**Comment by MarcAnt01** [comment]
I have already made a ticket for that https://github.com/UnigramDev/Unigram/issues/1605
