### ISSUE TITLE
Open the app often leads to  the last opened chat

### ISSUE THREAD

**Issue by SirTuna** [UnigramDev/Unigram#166]
It often opens the last chat instead of  opening  the main menu

**Comment by FrayxRulez** [comment]
I don't understand what do you mean

**Comment by SirTuna** [comment]
When I open the app, often there is not the main page but the last chat, even if I returned to the main menu the last time I opened the app

**Comment by larsschellhas** [comment]
not sure wether this is still an issue, but it´s not Happening for me anymore.
