### ISSUE TITLE
Possibility to delete a sticker in the panel

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1661]
![image](https://user-images.githubusercontent.com/43090263/83062378-cde61780-a05e-11ea-90b6-1fa82cfe4b90.png)

**Comment by FrayxRulez** [comment]
I think that right click > View sticker set > Remove is convenient enough.

**Comment by MarcAnt01** [comment]
> I think that right click > View sticker set > Remove is convenient enough.

That's not implemented

**Comment by FrayxRulez** [comment]
It is, I have implemented it

**Comment by MarcAnt01** [comment]
Ah, I actually have to press on a sticker rather than on the pack icon, found it
