### ISSUE TITLE
Back button in creating new Theme does not work as expected

### ISSUE THREAD

**Issue by hihain** [UnigramDev/Unigram#1664]
I would expect the new dialogue to close and not to go back in my main view.
![ezgif-6-346d79d44ad9](https://user-images.githubusercontent.com/1473059/83132711-198dd500-a0e2-11ea-9a6a-d876a6a4b59a.gif)

**Comment by hihain** [comment]
Idk if I should open a new ticket: In the current Unigram version the button to confirm is gone.
![image](https://user-images.githubusercontent.com/1473059/90391116-e0378680-e08c-11ea-84ad-ad7b65049ad3.png)

**Comment by FrayxRulez** [comment]
This should have been improved
