### ISSUE TITLE
Small message corner results in error message

### ISSUE THREAD

**Issue by hihain** [UnigramDev/Unigram#1665]
Error message and chat does not get rendered:
![image](https://user-images.githubusercontent.com/1473059/83201394-ad44bd00-a145-11ea-853f-18769470116b.png)
Settings that triggers the error on opening a chat:
![image](https://user-images.githubusercontent.com/1473059/83201493-dfeeb580-a145-11ea-85d3-376e5280154b.png)
![image](https://user-images.githubusercontent.com/1473059/83201519-ee3cd180-a145-11ea-8646-f7a8cc5ff79c.png)

**Comment by FrayxRulez** [comment]
This is fixed in https://github.com/UnigramDev/Unigram/commit/df666ca49e39919f05da14dcce76967a9495e073
