### ISSUE TITLE
suggestion for place holder of emoji panel on channels and chats without writing permission

### ISSUE THREAD

**Issue by alighamari** [UnigramDev/Unigram#1666]
![image](https://user-images.githubusercontent.com/24440862/83248376-3564aa00-a1ba-11ea-9a28-42215a6a67d0.png)
you can show channel info there so it wont be empty
like this 
![1](https://user-images.githubusercontent.com/24440862/83249472-ddc73e00-a1bb-11ea-83e2-69483f4870ca.png)
or this if its possible
![2](https://user-images.githubusercontent.com/24440862/83249956-98efd700-a1bc-11ea-98a6-b4ff99774f12.png)
version 4932

**Comment by FrayxRulez** [comment]
This isn't technically doable

**Comment by FrayxRulez** [comment]
(Btw the missing sticker is actually a bug and it's definitely more important than this)
