### ISSUE TITLE
Unhandled exception when selecting uncompressed pattern backgrounds

### ISSUE THREAD

**Issue by adrianghc** [UnigramDev/Unigram#1668]
Selecting a certain default background picture (one of those styled similar to the default WA pictures where you can select a pattern, see further below) causes the following exception:

`System.IO.InvalidDataException: The archive entry was compressed using an unsupported compression method.`

![image](https://user-images.githubusercontent.com/11506007/83307064-13901500-a204-11ea-9bcc-639e0ad2bfb7.png)

When clicking OK, the same message appears again. It does not appear again after clicking OK a second time.

This is the background in question:

![image](https://user-images.githubusercontent.com/11506007/83307881-e5abd000-a205-11ea-8aff-f61a31d62cb3.png)

This is on 4.0.4945.

**Comment by FrayxRulez** [comment]
Nice to see that in app updates are working at least 😂

**Comment by adrianghc** [comment]
> Nice to see that in app updates are working at least 😂

Haha, yes, I was pleasantly surprised to find the small banner on the bottom left. 😊
