### ISSUE TITLE
A draft message written using an official telegram app always appears in the chat box in unigram when opening unigram.

### ISSUE THREAD

**Issue by deltapir** [UnigramDev/Unigram#167]

**Comment by larsschellhas** [comment]
When a draft is synched from the other telegram app and you delete it in Unigram it will reappear after closing and re-opening the Chat. 
Also, it will overwrite what you may have written into the text-field, before leaving the Chat.

BUT sending a message via Unigram deletes the draft Messages in all Clients.

**Comment by FrayxRulez** [comment]
Solved in 0.2.296
