### ISSUE TITLE
Notification badge sometimes gets stuck at 1, even when there are no unread messages.

### ISSUE THREAD

**Issue by Paclanc** [UnigramDev/Unigram#1670]
The notificacion badge on the icon at the taskbar sometimes doesn't dissapear and instead displays a "1" even when there are no unread messages. This is obviously annoying since I can't know if there's actually a new message or if the bug is showing. 

The only way for it to go away is to close the app and open it again.
![image](https://user-images.githubusercontent.com/25404951/83311932-5fc46080-a1d6-11ea-93ab-6205d8db36fd.png)

The new version (4.0.4945) also suffers from this problem
![image](https://user-images.githubusercontent.com/25404951/83315971-f26dfb00-a1e8-11ea-9a8e-b25cb4fe630d.png)

Related to this problem, the live tile also gets stuck at one
![image](https://user-images.githubusercontent.com/25404951/83316011-2ba66b00-a1e9-11ea-872a-606d5315ed27.png)

**Comment by MarcAnt01** [comment]
You can try to disable push notifications, it fixes the issue

**Comment by adrianghc** [comment]
> You can try to disable push notifications, it fixes the issue

That doesn't really seem like a fix if you have to give up one of the primary features. Or is there a way to get background notifications without them being push notifications?

**Comment by MarcAnt01** [comment]
> You can try to disable push notifications, it fixes the issue

There was with tray icon, but it's been removed since it created problem with online status

**Comment by Paclanc** [comment]
> You can try to disable push notifications, it fixes the issue

That didn't work.
I used the method described here:
https://github.com/UnigramDev/Unigram/issues/1206

But the badge still shows a 1 or whatever number of notifications I received that doesn't get marked as read by the badge.

**Comment by Paclanc** [comment]
Hi. I have some findings on the behavior of this issue:

-When the badge is not bugged (when it is working properly), I can tap "Mark as read" from the notificaion on my phone, and the notification badge dissapear. But when te bug is present, I can't do the same: tapping "Mark as read" doesn't make the badge dissapear, it gets stuck at whatever number it was.

-The only other way for the bug to go away (more precisely, to clear the notification badge), besides restarting the app, is to scroll up on a chat, receive a message and then clicking the arrow that gets to the bottom of the chat and to the new message.
![image](https://user-images.githubusercontent.com/25404951/83559494-4a9f4880-a4da-11ea-9aee-9fa3ded72584.png)

**Comment by Paclanc** [comment]
Other findings. 
-The bug seems to only appear when you receive a message and Unigram is either minimized or if it is the active window (as in you are using it). 

-The notification badge can also be cleared if the Unigram window is on the background or foreground (but not minimized), and then, (after you receive a message) you go to the unigram window making it the active window. In this scenario the notification badge goes away as it should.

**Comment by Kenya-West** [comment]
Can confirm. Live tile shows 1 unread notification even when you read all of them in app. While the app is running:

![Snag_12f67a66](https://user-images.githubusercontent.com/12271104/83593624-273ad300-a598-11ea-9c27-eeed11be719b.png)
![Snag_12f687a4](https://user-images.githubusercontent.com/12271104/83593629-29049680-a598-11ea-97a6-feee9190be8b.png)

Well, if you change size of the tile or unpin it and pin it back, you still got 1 notification unread.

**Comment by FrayxRulez** [comment]
Likely fixed by https://github.com/UnigramDev/Unigram/commit/93fce176096968d0a9ed5088cb033edd5b5edafd and will be available in version 4.0 (5018) or newer. If still present please comment on this ticket or open a new one!
