### ISSUE TITLE
Unhandled exception when opening the advanced settings

### ISSUE THREAD

**Issue by Paclanc** [UnigramDev/Unigram#1671]
This message will appear everytime I open the advanced settings.

![image](https://user-images.githubusercontent.com/25404951/83312064-c8134200-a1d6-11ea-8a7d-8257e5a9ec21.png)

**Comment by FrayxRulez** [comment]
Hey! At the moment the app in the store is quite outdated, as we’re preparing for some big release. If you want you could give it a try by downloading it from https://t.me/unigramappx 
Many bugs present in the store version are fixed already (including this one) and reports about new ones are more than welcome!
