### ISSUE TITLE
Suggestion to zoom images when they are on fullscreen by double-clicking

### ISSUE THREAD

**Issue by Paclanc** [UnigramDev/Unigram#1672]
Hi.

When images are on fullscreen, they can only be zoomed using ctrl+wheel. Once they are zoomed, there isn't a way to drag the image.

**Comment by MarcAnt01** [comment]
Hello, I have added your suggestion to this ticket https://github.com/UnigramDev/Unigram/issues/1304

**Comment by MarcAnt01** [comment]
Feel free to continue the discussion there
