### ISSUE TITLE
suggestion for archived chats place 

### ISSUE THREAD

**Issue by alighamari** [UnigramDev/Unigram#1673]
if you make "archived chats" look like like a folder with "Archived" tag it will look way better

**Comment by MarcAnt01** [comment]
Hello, Unigram design aims to follow the one of official apps, which don't have such thing

**Comment by alighamari** [comment]
> Hello, Unigram design aims to follow the one of official apps, which don't have such thing

so if its the case can we have "Ctrl+A" as shortcut for archived chats?

**Comment by MarcAnt01** [comment]
Ctrl + A is select all shortcut, do you have other ideas?

**Comment by FrayxRulez** [comment]
Why can't we stick with CTRL+9?

**Comment by MarcAnt01** [comment]
> Why can't we stick with CTRL+9?

Didn't know about it, but what if someone has 9 folders?

**Comment by cewbdex** [comment]
> Didn't know about it, but what if someone has 9 folders?

It works the same as in browsers, you have 1-8 accessible, so you put the tabs here you want to have accessible, don't see the point of having 100 accessible by a shortcut.

**Comment by alighamari** [comment]
i think we should have a shortcut page in advance settings so we can know what is shortcuts as i didn't knew the Ctrl+9 for saved messages

**Comment by MarcAnt01** [comment]
@alighamari there's a guide in the wiki even if we should update it, since it's quite outdated

**Comment by alighamari** [comment]
> there's a guide in the wiki

people don't read the wiki thats a fact

**Comment by MarcAnt01** [comment]
I highly doubt most people actually use shortcuts tbh

**Comment by MarcAnt01** [comment]
And the same applies to Telegram Desktop: they have a guide with all the shortcuts. Who would like to use them can read it

**Comment by alighamari** [comment]
> Who would like to use them can read it
never been this much satisfied with an answer

**Comment by MarcAnt01** [comment]
@alighamari feel free to suggest any better places to put the guide within the GH repo
