### ISSUE TITLE
Draft sync would causes input box withdrawal

### ISSUE THREAD

**Issue by Incisakura** [UnigramDev/Unigram#1679]
**Issue**
When typing messages for a long time, draft sync would withdrawal what I input just now. Withdrawal content would be lost.

**Environment**
Device: Surface Pro6
Windows OS Build: 19041.264
Unigram Version: 3.15.4756

**Reproduce**
1. Type in a message box.
2. (draft sync)
3. More typing...
4. (draft sync which would sync box to **2**)
5. What we input in **3** would be lost.

**Solution**
Stop draft sync for the current front ground chat.

**Comment by FrayxRulez** [comment]
This is a bit more complicated than this, because you actually want draft sync in some confusions. But I’m planning to fix this by next release!

**Comment by Incisakura** [comment]
Well, thank you.
