### ISSUE TITLE
Message text box overlaps GIF panel

### ISSUE THREAD

**Issue by Marocco2** [UnigramDev/Unigram#1685]
![image](https://user-images.githubusercontent.com/3944248/83357425-7c929c80-a36c-11ea-8c25-a7c12f27b3c7.png)

Clicking on gif button that happens. 

Expected behavior:
Message text box should not be over gif panel

Surface Pro 7 i5/256GB 
Windows 10 2004
Unigram 4.0.4966

**Comment by MarcAnt01** [comment]
Hi, there's already a ticket for that, thanks for reporting

**Comment by MarcAnt01** [comment]
Duplicate of https://github.com/UnigramDev/Unigram/issues/1586

**Comment by FrayxRulez** [comment]
That's not the same thing

**Comment by Marocco2** [comment]
![recording](https://user-images.githubusercontent.com/3944248/83360287-773f4d00-a380-11ea-85fc-74ea2343d1a0.gif)

**Comment by MarcAnt01** [comment]
Ah, it's clearer now, I thought it was the reply to a message
