### ISSUE TITLE
there is no profile name and online status in separate windows chat, as shown below

### ISSUE THREAD

**Issue by sudhegan** [UnigramDev/Unigram#1688]
![image](https://user-images.githubusercontent.com/65366543/83439731-5dc20200-a461-11ea-95a0-9659e55089b6.png)
![image](https://user-images.githubusercontent.com/65366543/83439762-69152d80-a461-11ea-8447-f660b6f69095.png)

**Comment by MarcAnt01** [comment]
Just found this old ticket with the same stuff. Added online status tho
