### ISSUE TITLE
Found Two crash (Separate chat)

### ISSUE THREAD

**Issue by sudhegan** [UnigramDev/Unigram#1689]
Found Two crash
1.Unigram crashes when opening separate window for chat (Shift+left click) when in restores size(some times in maximize also but restored window crashed every time)
2. It also crashes when opening chat that is opened in separate window (it should open the separate window but crashes)
3.after crash unigram starts in small window (in the size of separate chat)
enclosed three crash dumps compressed and video record

**Comment by FrayxRulez** [comment]
I think I fixed this one, will close the ticket later

**Comment by FrayxRulez** [comment]
I see that you don't like to close issues about fixed stuff, so I'll close it
