### ISSUE TITLE
Album send is broken 

### ISSUE THREAD

**Issue by WeFenFinit** [UnigramDev/Unigram#1690]
Add 2 images -> send -> posted only first image

no logs after sending

Build 4991

**Comment by MarcAnt01** [comment]
How are you sending the photos? Tried Windows Share and Drag&Drop and could not reproduce

**Comment by WeFenFinit** [comment]
Drag&Drop, ctrl+c + ctrl+v
Record: [link](https://drive.google.com/file/d/1AWo_OmVGMhC9bsxLOrhIFiT4K0UIKaEI/view?usp=sharing)

**Comment by FrayxRulez** [comment]
I can reproduce as well

**Comment by MarcAnt01** [comment]
It happens to me only when pasting a photo after one has already been added
