### ISSUE TITLE
Unhandled exception when selecting an advanced settings menu

### ISSUE THREAD

**Issue by banyrule** [UnigramDev/Unigram#1691]
# Summary
I get an "unhandled exception" message when I try to open the advanced settings menu.

![image](https://user-images.githubusercontent.com/14077902/83503687-a7f0c500-a4ed-11ea-8651-be1fd45ca4d7.png)

# Details
- Unigram 3.15.4756
- Windows 10.0.18363
- Multiple telegram accounts log-in

**Comment by MarcAnt01** [comment]
Hello, this bug is known and fixed in the beta version, will take a bit to reach store channel👍
