### ISSUE TITLE
Animated emojis have low frame rate

### ISSUE THREAD

**Issue by githubcatw** [UnigramDev/Unigram#1692]
Hello.
Animated emojis [in Unigram](https://www.youtube.com/watch?v=-5qnQJFjYMI) have lower frame rate than [in TDesktop](https://www.youtube.com/watch?v=3zBp-KA5D7g).
Unigram 4.0 (4991), Windows 10 v1909.

**Comment by FrayxRulez** [comment]
Mind specifying your hardware?

I'm afraid I can't do much more than running a timer every 33 milliseconds.

**Comment by githubcatw** [comment]
I'm using an HP OMEN 17 laptop

**Comment by FrayxRulez** [comment]
What about CPU usage during the stickers playback?

**Comment by githubcatw** [comment]
Haven't checked, will check and update now

**Comment by FrayxRulez** [comment]
Actually the 😂 sticker looks fine to me, just the 👍 looks broken, not only the framerate but as a whole, it even stops on the wrong frame.

**Comment by githubcatw** [comment]
To me the like one looked worse too.

**Comment by githubcatw** [comment]
Unigram was using ~2.5% (of ~30% total CPU usage) while rendering an animated emoji while TDesktop was using ~3.5% (of ~50% total).

**Comment by FrayxRulez** [comment]
> To me the like one looked worse too.

Did you have the stickers panel open on the side with 60 animated stickers playing in the meanwhile?

**Comment by githubcatw** [comment]
I closed it, besides the group I was testing in has stickers disabled for normal users

**Comment by FrayxRulez** [comment]
> Unigram was using ~2.5% (of ~30% total CPU usage) while rendering an animated emoji while TDesktop was using ~3.5% (of ~50% total).

So I guess it's really just the 👍. Did you check any other sticker before opening this issue?

**Comment by githubcatw** [comment]
I tested a few other emojis and stickers too, all of them have low framerates but more stable than the like

**Comment by FrayxRulez** [comment]
I am not sure if we're talking about the same thing, but in your videos 😂 sticker plays exactly at the same speed in Unigram and in TDesktop.

**Comment by githubcatw** [comment]
This might be because of my screen recorder recording at 30fps. The laugh sticker was smoother in Desktop.

**Comment by githubcatw** [comment]
In 3.15 the animated stickers were as smooth as in TDesktop. This started happening in 4.0

**Comment by FrayxRulez** [comment]
I made a comparison of the two videos you sent:
![https://media.giphy.com/media/Urn1ydkCepkOgbObhY/giphy.gif](https://media.giphy.com/media/Urn1ydkCepkOgbObhY/giphy.gif)

They look exactly the same to me.

**Comment by githubcatw** [comment]
It's because of my screen recorder. I [rerecorded the videos](https://1drv.ms/u/s!AukIzF1WiirUskIZiBuMMPje2P2J?e=u7Y1eb) with Game DVR and here you can see that Desktop is smoother.

**Comment by FrayxRulez** [comment]
But still 😂 looks completely fine. Unigram always played stickers at 30 fps rather than 60, this isn't a news.
Ok, 👍 looks slower than it should and I can see this, but 😂 absolutely doesn't. They both take the same amount of time to play, this means that there's no issue there.

**Comment by githubcatw** [comment]
OK. This seemed new to me.

**Comment by FrayxRulez** [comment]
To be clear: slow motion isn't correct and it shouldn't happen, so if you're reporting that all your stickers play in slow motion then this is a real issue. But if it's simply about stickers "not being as smooth" this is expected, as 60 fps stickers are actually player at 30 fps, by skipping a frame.
Now, at some point I would love to improve this, but I won't consider it a bug.
