### ISSUE TITLE
mark the message as read also when answering the message

### ISSUE THREAD

**Issue by chagai95** [UnigramDev/Unigram#1700]
right now it only marks it read when you click on mark as read from the notification popup and that is not how it is in the android app. It also just makes sense to mark a message as read (or a chat) when you answer a message...

**Comment by MarcAnt01** [comment]
Answer trough notification?

**Comment by chagai95** [comment]
> Answer trough notification?

yes through te notification pop up.
![image](https://user-images.githubusercontent.com/31655082/83806303-99eba180-a6b1-11ea-997a-246d59a898b2.png)

**Comment by FrayxRulez** [comment]
This is actually by design, but yes, this might make sense to groups only

**Comment by chagai95** [comment]
> This is actually by design, but yes, this might make sense to groups only

maybe it's best to add the option to the settings then? so you can choose? maybe one toggle for group and one for regular chats?

**Comment by hihain** [comment]
Or a third button? Send and mark as read?

**Comment by MarcAnt01** [comment]
I think it's better to mark as read automatically with chats once you send a message. A third button would look ugly

**Comment by chagai95** [comment]
> I think it's better to mark as read automatically with chats once you send a message. A third button would look ugly

Maybe a 3 button for groups only?

**Comment by chagai95** [comment]
@hihain thanks!
