### ISSUE TITLE
1500.0mb failed

### ISSUE THREAD

**Issue by razor91111** [UnigramDev/Unigram#1701]
The program cannot upload a file with a size of 1500.0mb (1,572,864,000 bytes) to the telegram server when trying to upload a file it shows an error, there is no such problem on the android or telegram on the desktop, please fix it

**Comment by FrayxRulez** [comment]
What error?

**Comment by razor91111** [comment]
[log.zip](https://github.com/UnigramDev/Unigram/files/4725078/log.zip)

**Comment by razor91111** [comment]
[log.zip](https://github.com/UnigramDev/Unigram/files/4725119/log.zip)

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/tdlib/td/commit/9c5c112733609318c4860479d59789e4ed69f21b
