### ISSUE TITLE
Cannot reply to messages with an image

### ISSUE THREAD

**Issue by githubcatw** [UnigramDev/Unigram#1702]
When I reply to something with an image my reply is sent as a normal message, not as a reply.
![gif](https://user-images.githubusercontent.com/17374742/83670552-698a0180-a5e4-11ea-8d08-1af49be15669.gif)

**Comment by FrayxRulez** [comment]
Hey Narek, please always specify which version of the app are you using, because this might be confusing in some circumstances.
Anyway the bug is fixed and the update will be available later today!

**Comment by githubcatw** [comment]
Thanks. I'm using Unigram 4.0.5002.0.
