### ISSUE TITLE
Extend title bar to folder sidebar

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1705]

**Comment by KiruyaMomochi** [comment]
![image](https://user-images.githubusercontent.com/65301509/83679129-76711a00-a611-11ea-9f93-feb5bf47484c.png)

However, **after extending the title bar, where should we place the title text**?
If we place the text in the sidebar, we may do not have enough space for something like **Connecting...**.

**Comment by FrayxRulez** [comment]
Done
