### ISSUE TITLE
Error while opening folders menu

### ISSUE THREAD

**Issue by sudhegan** [UnigramDev/Unigram#1706]
![image](https://user-images.githubusercontent.com/65366543/83681763-7ae10700-a600-11ea-8fd3-db788c6292be.png)

**Comment by FrayxRulez** [comment]
@sudhegan are you still able to reproduce this?

**Comment by sudhegan** [comment]
@FrayxRulez no now there is no error

**Comment by sudhegan** [comment]
@FrayxRulez s now again but not sure how

**Comment by FrayxRulez** [comment]
😭
