### ISSUE TITLE
In the proxy settings page before log in, there's no back button 

### ISSUE THREAD

**Issue by flamott** [UnigramDev/Unigram#1707]
App version: 4.0.5014.0

**Comment by ZeppLu** [comment]
Any update? Just downloaded from Microsoft Store, can confirm still lacks back button

**Comment by MarcAnt01** [comment]
If the ticket is still open, it means that the issue hasn't been solved 🙂

**Comment by FrayxRulez** [comment]
In the meanwhile, you can go back by Alt + Left arrow

**Comment by FrayxRulez** [comment]
Looks ugly but there's a back button now
