### ISSUE TITLE
missing animations

### ISSUE THREAD

**Issue by alighamari** [UnigramDev/Unigram#1710]
moving from (also to) "all chats" have a nice animation but moving between other folders have no animation
version 5025 (i don't know if i have latest build or not)

**Comment by FrayxRulez** [comment]
Animations are run just if the previous one is completed

**Comment by FrayxRulez** [comment]
> version 5025 (i don't know if i have latest build or not)
You can check this from Advanced settings (it is by the way)

**Comment by alighamari** [comment]
![animation](https://user-images.githubusercontent.com/24440862/83796922-0ae18800-a6b7-11ea-880d-32b9d7c913b5.gif)

**Comment by FrayxRulez** [comment]
Nice glitches, but what's the missing animations? 🤔 😂
