### ISSUE TITLE
"edited" label overlaps actual message

### ISSUE THREAD

**Issue by omfgnuts** [UnigramDev/Unigram#1715]
Once the message is edited, "edited" label overlaps the resulting text

![image](https://user-images.githubusercontent.com/845482/83808487-89d9bf00-a6bd-11ea-9b14-c924e14a3e81.png)

**Comment by FrayxRulez** [comment]
This is fixed by https://github.com/UnigramDev/Unigram/commit/22d39c31eb4d9009e66c912d02618d056fde7c4c
