### ISSUE TITLE
Show a error

### ISSUE THREAD

**Issue by Yaroslav08** [UnigramDev/Unigram#1716]
When i go to setting and next step click "advanced", a got a crash with next result:
![Req](https://user-images.githubusercontent.com/38474523/83809009-64998080-a6be-11ea-9017-e00efdabbc43.jpg)
Win10 Pro, x64, build 2004

**Comment by FrayxRulez** [comment]
Hallo, this is fixed in 4.0, but it will take a while to reach the Store. If you want you can give it a try from https://t.me/unigramappx
