### ISSUE TITLE
Improve GIF panel focus handling for GIF preview.

### ISSUE THREAD

**Issue by hihain** [UnigramDev/Unigram#1717]
If you click between the different categories in the GIF panel only some GIFs have a preview.
The user can only let Unigram lose focus and give it focus back to show all previews.

Seems like clicking the buttons for the categories make the GIFs believe that they should not play.

I'm not sure if #1699 means the same.
Clicking on trending:
![image](https://user-images.githubusercontent.com/1473059/83889602-9dcc0200-a74b-11ea-8993-5d03da6bb8ab.png)
Click on Taskbar and after that on Unigram again:
![image](https://user-images.githubusercontent.com/1473059/83889531-8c82f580-a74b-11ea-8449-50af6df8aadc.png)

**Comment by MarcAnt01** [comment]
@hihain that's mostly because those GIFs have to be downloaded first

**Comment by FrayxRulez** [comment]
No, Filippo, it’s because @gif bot doesn’t provide static thumbnails anymore, only animated ones

**Comment by MarcAnt01** [comment]
Yes and that's why the animated thumbnails take a bit to be played

**Comment by FrayxRulez** [comment]
Animated thumbnails aren't played at all.
