### ISSUE TITLE
Unigram not able to handle url:Telegram Link

### ISSUE THREAD

**Issue by mehulagg** [UnigramDev/Unigram#1718]
I tried to authorize gmail bot but unigram is not able to handle that request but telegram desktop is able to accept that request.

**Comment by FrayxRulez** [comment]
How does the url look like?

**Comment by FrayxRulez** [comment]
I just tried and I actually connected my Gmail account to Telegram without any problem?

**Comment by mehulagg** [comment]
![image](https://user-images.githubusercontent.com/53606356/83941217-55721a00-a807-11ea-996e-396d4744d68f.png)

When i click on open unigram button ,unigram opens but nothing happens in unigram.
but when i tried it with telegram desktop ,the gmail bot gets authorized.
