### ISSUE TITLE
Hamburger Menu vanishes if "Tabs on the left" and not on Chats page

### ISSUE THREAD

**Issue by hihain** [UnigramDev/Unigram#1720]
Chats Page:
![image](https://user-images.githubusercontent.com/1473059/83948168-ce7b6c80-a81b-11ea-9db7-d8a817403b0c.png)

Any other Page (here: Calls)
![image](https://user-images.githubusercontent.com/1473059/83948172-d5a27a80-a81b-11ea-8a13-87a17f5be0a0.png)

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/8c357a77c8a811d64e48903061636bc57510a302
