### ISSUE TITLE
Pasting from context menu Paste option does not always work

### ISSUE THREAD

**Issue by entdark** [UnigramDev/Unigram#1729]
What title says.
How I was able to reproduce that:
1. Visit: https://www.reddit.com/r/Telegram/comments/gwlwvo/video_editor_animated_photos_better_gifs_and_more/
2. Right click on the title and click Copy (title is a link that redirects to telegram.org)
3. Right click in any chat and click Paste.
4. Nothing happens.
5. Pasting with Ctrl+V will work though.

Expected behaviour:
On the 4th step it has to paste a content of clipboard.

P.S. if I copy a link with the context menu within Unigram itself then pasting via the context menu will work.

Versions:
Windows 10 Pro 1909 build 18363.836
Unigram 3.15.4756

**Comment by FrayxRulez** [comment]
I am not able, I am not sure about what "title" are you talking about. Would be also nice to know which browser are you using.

**Comment by FrayxRulez** [comment]
Might be this, let's see: https://github.com/UnigramDev/Unigram/commit/39c51c4812a03b44fce3a00cd0927ece0f766ee8

**Comment by entdark** [comment]
Fixed now, thanks.
