### ISSUE TITLE
Change stretching of preview after cropping

### ISSUE THREAD

**Issue by hihain** [UnigramDev/Unigram#1740]
Change the stretching of the preview after cropping to make the user understand that his cropping was saved.

Currently, everything is streched. As a result, many users react in a bewildered manner:
![ezgif-6-36f2b59c8587](https://user-images.githubusercontent.com/1473059/83977120-55087a80-a8fe-11ea-931b-e6f5ffa3edba.gif)

**Comment by FrayxRulez** [comment]
This is done in https://github.com/UnigramDev/Unigram/commit/28bf36ee733bc690194afe53db0f72172f8cece3
