### ISSUE TITLE
last_chat custom shortcut does not work like it should

### ISSUE THREAD

**Issue by makisukurisu** [UnigramDev/Unigram#1742]
last_chat opens last from curently "visible" chat list. In all chats it might not work as it should.

Probably, fixing this issue will increase memory consumption, but it maybe worth it?

![screen_1](https://user-images.githubusercontent.com/49622129/83977810-f77b2a80-a90b-11ea-9bc1-f38580a2538e.jpg)
_Chat opened after last_chat without scrolling trough chats_

![screen_2](https://user-images.githubusercontent.com/49622129/83977873-4628c480-a90c-11ea-8674-71c8cad2c9b4.jpg)
_But that is not actualy last one_

Thanks for reading.

**Comment by makisukurisu** [comment]
>What is last_chat command?

Shortcut command from [that file.](https://pastebin.com/S2Yae0UW)

**Comment by FrayxRulez** [comment]
There is no way that it can work as you ask for
