### ISSUE TITLE
Spell checker option on the context menu

### ISSUE THREAD

**Issue by Paclanc** [UnigramDev/Unigram#1745]
Rigth now there's no way to correct misspelled words using the spell checker. Right click only shows the telegram options
![image](https://user-images.githubusercontent.com/25404951/83982084-2cc25100-a8e9-11ea-96a5-a2005f7894fc.png)

Is it possible to add the native windows 10 Spell checker option on the context menu?
![image](https://user-images.githubusercontent.com/25404951/83982163-e15c7280-a8e9-11ea-9df2-fcb52c44baea.png)
The above picture shows the aforementioned feature on the mail app.

**Comment by FrayxRulez** [comment]
Added, not in the way I would like to have, but still
