### ISSUE TITLE
"Add to folder option" does not work

### ISSUE THREAD

**Issue by altwarg** [UnigramDev/Unigram#1746]
Adding chats or channels to a folder does not work. Added appears in folder settings but not in Unigram itself
![image](https://user-images.githubusercontent.com/34391398/84004095-b74f9280-a973-11ea-941b-7da67a2cf6c7.png)

**Comment by FrayxRulez** [comment]
Does switching to a different folder and back help?

**Comment by altwarg** [comment]
@FrayxRulez nope. And also, when I close the folder settings and open them again, new chats do not appear there

**Comment by altwarg** [comment]
Never met that issue again. Closing
