### ISSUE TITLE
Current chat stops updating eventually.

### ISSUE THREAD

**Issue by starbird64** [UnigramDev/Unigram#175]
Sometimes, doing nothing, inside a chat, you can send messages, but you're unable to see the received ones. New messages will be visible if you go to the chats list and return to the chat.

**Comment by larsschellhas** [comment]
I had a chat open on my phone and received messages both there and in TG Desktop. 
But when I answered in TG Desktop the messages were not shown on the phone in Unigram until I reopened the chat.

**Comment by ADeltaX** [comment]
@larsschellhas test

**Comment by larsschellhas** [comment]
@larsschellhas As soon as a new message from the chat partner is received, the chat gets updated again.

**Comment by FrayxRulez** [comment]
Can I consider this a duplicate of #71?
