### ISSUE TITLE
Adding chat to a folder via right click throws an exception error

### ISSUE THREAD

**Issue by s1-en** [UnigramDev/Unigram#1753]
Repro steps:
1. Right click on a folder on the sidebar
2. Select Add Chats
3. Select the chat to add
4. Click OK
5. You get this:

![image](https://user-images.githubusercontent.com/63731521/84026134-58176f80-a9bf-11ea-8f02-47310a42333e.png)

**Comment by s1-en** [comment]
New discovery. This is only an issue for folders with spaces in the name.

**Comment by FrayxRulez** [comment]
> New discovery. This is only an issue for folders with spaces in the name.

No that's completely unrelated, the issue is caused by something else and I can't manage to reproduce it

**Comment by s1-en** [comment]
> > New discovery. This is only an issue for folders with spaces in the name.
> 
> No that's completely unrelated, the issue is caused by something else and I can't manage to reproduce it

Another issue I found is that right clicking the folder that gets error and selecting "Edit Folder" will give a blank page as if I'm creating a new folder.

![image](https://user-images.githubusercontent.com/63731521/84050925-fd8f0b00-a9e0-11ea-8e46-c8b74c7aa99c.png)

**Comment by FrayxRulez** [comment]
It would be nice if you could:
- Reach Settings
- Click 10 times on the app version
- Change "Verbosity" to "Debug"
- Reproduce the issue
- Go back to diagnostics
- Change "Verbosity" to "Assert"
- Send the logs to me on Telegram

**Comment by FrayxRulez** [comment]
Hello @s1-en?

**Comment by s1-en** [comment]
Crud, I'm really sorry, I forgot to check GitHub! I messed up, because after I posted my last response, I thought about what you said with the space in the name not being the issue so I tried deleting the problematic folder and re-creating it and the issue went away, hence why I forgot to report back or see your instruction 😢
