### ISSUE TITLE
No horizontal scroll in image viewer

### ISSUE THREAD

**Issue by makisukurisu** [UnigramDev/Unigram#1754]
Using mouse wheel you can zoom in/out, scroll vertically, but not horizontally.
In most photo editing/viewing programs shift/alt+mouse wheel does scroll in vertical direction, so I think shift+scroll must do vertical scroll.

[Video with issue.](https://youtu.be/lv4IK3srONo)

**Comment by MarcAnt01** [comment]
Hi, we already have a ticket for this purpose. Feel free to comment it or suggest improvements there
https://github.com/UnigramDev/Unigram/issues/1304
