### ISSUE TITLE
UI glitch when switching between accounts with and without folders with folders sidebar

### ISSUE THREAD

**Issue by cewbdex** [UnigramDev/Unigram#1756]
It is broken for either first or second account, dependent which one is Unigram launched with.

![image](https://user-images.githubusercontent.com/9021297/84033067-964d6880-a998-11ea-8aaf-47d7fde6e222.png)
Figure 1: Variant one

![image](https://user-images.githubusercontent.com/9021297/84033241-d7de1380-a998-11ea-8b68-30c2d3038d02.png)
Figure 2: Variant two

**Comment by FrayxRulez** [comment]
Fixed
