### ISSUE TITLE
Splitter displays forever when it was just clicked

### ISSUE THREAD

**Issue by altwarg** [UnigramDev/Unigram#1761]
To reproduce: click on splitter. It will be displayed until it's position changed

Image:
![image](https://user-images.githubusercontent.com/34391398/84050455-72991b00-a9b6-11ea-922e-d75dcd3f019e.png)

GIF:
![ezgif-1-f76b1c16041e](https://user-images.githubusercontent.com/34391398/84050245-23eb8100-a9b6-11ea-9ad1-09c95fc2bd5b.gif)

**Comment by FrayxRulez** [comment]
This is fixed 🕺
