### ISSUE TITLE
How to add unigram to tray?

### ISSUE THREAD

**Issue by albirlak** [UnigramDev/Unigram#1762]
How to add unigram to tray?

**Comment by githubcatw** [comment]
You can't, just don't close unigram and you'll be fine

**Comment by albirlak** [comment]
I'm used to having telegrams in the tray, I must to give up unigram.

**Comment by beerisgood** [comment]
You can minimize unigram to taskbar.
Also remember that unigram is a lot more secure then official Telegram client as only unigram use isolation from AppContainer windows store app.
@albirlak

**Comment by FrayxRulez** [comment]
> I'm used to having telegrams in the tray, I must to give up unigram.

I suggest you to reach Microsoft and complain to them, they decided that UWP apps don’t need tray icon and this is the result.

**Comment by MarcAnt01** [comment]
Why is the tray icon really needed? UWP apps support push notifications, so you can receive them also when the windows is closed.

**Comment by albirlak** [comment]
> I suggest you to reach Microsoft and complain to them, they decided that UWP apps don’t need tray icon and this is the result.

I didn't know microsoft was responsible for this.

**Comment by albirlak** [comment]
I'm just used to seeing the icon on the right, it's more comfortable for me to work.

Too bad there is no solution.

![image](https://user-images.githubusercontent.com/31618040/84145472-99149000-aa62-11ea-8cdb-8b4b91489b7b.png)
