### ISSUE TITLE
Password lock for unigram unlocks if windows share is used

### ISSUE THREAD

**Issue by NotLT** [UnigramDev/Unigram#1763]
Make sure unigram is locked with a password.
Right click a file, click share, select Unigram.
Unigram unlocks without a password and no share UI appears, you are left with unlocked unigram chat list.

**Comment by cewbdex** [comment]
Looks like it is duplicate of #1270 after all.

**Comment by MarcAnt01** [comment]
@cewbdex I don't think it's the same issues. Window Share not working with Unigram closed was happening some versions ago (cannot reproduce any longer), while this one still happens

**Comment by cewbdex** [comment]
I think it's exactly the same issue, Unigram is closed, you click share to Unigram, Unigram does this.

**Comment by NotLT** [comment]
This is about unlocking unigram without password when it is password locked.

**Comment by MarcAnt01** [comment]
Yes and Share UI is loaded properly

**Comment by NotLT** [comment]
So  2 separate tickets need to be created ?

**Comment by MarcAnt01** [comment]
I don't know, maybe the other one could be edited to include this one, but unsure if it is due to the same reasons

**Comment by cewbdex** [comment]
It's exactly the same, even you said it.

![image](https://user-images.githubusercontent.com/9021297/84574804-4e1fb300-ada9-11ea-94b1-c51bf46ad27d.png)

**Comment by MarcAnt01** [comment]
I cannot reproduce it now, but I don't use Windows Hello login any longer

**Comment by NotLT** [comment]
The cameras turn and everything. But the dialog does not appear and unigram unlocks straight away.
