### ISSUE TITLE
Proxy settings not working before user login

### ISSUE THREAD

**Issue by MahdiGhiasi** [UnigramDev/Unigram#1764]
When trying to log in to a new user in Unigram, proxy settings doesn't seem to work. (Here in Iran, Telegram is not directly accessible, and needs some kind of proxy or VPN)

After adding a proxy via Proxy Settings, adding a proxy and selecting it will stay on "Connecting..." behind it, and does not connect.

However, after logging in to Unigram (I did it via a system-wide VPN, as direct access is not possible) proxies work properly. So this only affects the login experience.

Tested on Unigram 4.0.5098.

**Comment by MahdiGhiasi** [comment]
Forgot to add, this was tested with an MTProto proxy. The same proxy works after logging in.

**Comment by MahdiGhiasi** [comment]
Forgot to add, this only happens with MTProto proxies. (The same proxy works after logging in)

I also tested a SOCKS proxy on localhost, it works fine on login experience.

**Comment by levlam** [comment]
Could you change TDLib log verbosity level to DEBUG, reproduce the issue and send the log to @tdlib_bot in Telegram? TDLib log can be managed from Debug menu by clicking 10 times on Unigram version number.

**Comment by PufferBlue** [comment]
Year 2022 now, proxy still not working before user login.

**Comment by PufferBlue** [comment]
It seems that if you change proxy settings before login, when you exit the proxy settings page to the login page, the proxy setting is reset,
and if you try login first and then change the proxy settings, the login process is reset.
So this is the dead end, the only solution to use unigram in such situation is using some Layer 3 VPN to "bootstrap" the login process
