### ISSUE TITLE
"Flash window when receiving a notification" option (Desktop Bridge) still visible 

### ISSUE THREAD

**Issue by ghost** [UnigramDev/Unigram#1769]
![image](https://user-images.githubusercontent.com/37037814/84146367-fba16800-aa31-11ea-9612-09f2ffb21c81.png)

In Settings > Notifications & Sounds > Notifications in the App, there is a line (marked by the red arrow), which is not translated into Spanish.

**Comment by FrayxRulez** [comment]
Hello, Unigram uses official Android app translations from translations.telegram.org, but some of Unigram features aren't available on Android, and consequently it isn't possible to translate them.

In the case of this specific one, the option isn't actually working, as it requires the system tray component (that has been removed)

**Comment by FrayxRulez** [comment]
I believe that this open has been removed a long time ago

**Comment by lostmsu** [comment]
@FrayxRulez the tray component has been reintroduced. Can you reopen this issue?
