### ISSUE TITLE
Preview of Stickers in Chats

### ISSUE THREAD

**Issue by Leo300V** [UnigramDev/Unigram#1770]
Official Telegram for PC has this option, and it would be a good idea to have it on Unigram as well. 
The idea is that by placing the mouse cursor over a sticker and then clicking and holding (left mouse button) on the sticker, you can see a preview of it in big size, as shown in the attached video.

![2020-06-09 09-32-51_Trim](https://user-images.githubusercontent.com/37037814/84149850-79b43d80-aa37-11ea-8f87-c8d7e7901fa7.gif)

**Comment by FrayxRulez** [comment]
This has been added to the app exactly 1 hour ago: https://github.com/UnigramDev/Unigram/commit/93e0b60eb96bd77e7d2f6332359a4dd3648ddf1a
🕺
