### ISSUE TITLE
When viewing image, clicking on the image won't quit

### ISSUE THREAD

**Issue by clafiok** [UnigramDev/Unigram#1772]
In Telegram Desktop, when opening an image for full-screen view, clicking on the image will return to the chat window. But in Unigram, this doesn't work.

**Comment by cewbdex** [comment]
In Unigram it works by swiping the image up or down.

**Comment by FrayxRulez** [comment]
Yeah but it isn't the best behavior using a mouse. The gallery needs some improvements.

**Comment by cewbdex** [comment]
Duplicate of #995
