### ISSUE TITLE
Media counters in profile page

### ISSUE THREAD

**Issue by FrayxRulez** [UnigramDev/Unigram#1775]
As @cewbdex suggested it would be nice to have media counters in profile page

**Comment by hihain** [comment]
If I have not missed anything, there are the commits for my implementation in the fork. Might be easier for me to revert them after you implemented it or it might help you finding some places where changes might be necessary. I am not happy with the solution as the UI takes some time to update...

https://github.com/hihain/UnigramMobile/commit/d62e92be725d068db7c847cc4562cf8a63b96f78
https://github.com/hihain/UnigramMobile/commit/5a3da2b55d567d64e9be69c785af49852e584de1
https://github.com/hihain/UnigramMobile/commit/b92db8bd4750a7f2b0b43546eb6a1e9f40daf7eb

**Comment by MarcAnt01** [comment]
@hihain can we have some screenshots of the ui?

**Comment by hihain** [comment]
![image](https://user-images.githubusercontent.com/1473059/90335359-c6d30380-dfd4-11ea-9157-57ac50343612.png)

**Comment by MarcAnt01** [comment]
Looking good, thanks
