### ISSUE TITLE
Lock screen uses the wrong scaling with two monitors having different scaling

### ISSUE THREAD

**Issue by Auvere** [UnigramDev/Unigram#1776]
Having two monitors where my main monitor is at 125% scaling and secondary monitor at 100% scaling, then opening Unigram open on the secondary monitor confuses the lock screen UI and partially shows the unlocked client. You can interact, scroll and even chat (and use keyboard shortcuts) while this happens.
![image](https://user-images.githubusercontent.com/27517093/84175091-0ef41800-aab2-11ea-8c59-3e510d548fb1.png)

Edit: I'm using a laptop (main monitor on Windows) and an external monitor plugged in, both are 1080p so this setup probably isn't too uncommon

**Comment by FrayxRulez** [comment]
I can't reproduce the issue so I guess that it was fixed
