### ISSUE TITLE
Send icons overlaps voice message icon after chat switch while editing message

### ISSUE THREAD

**Issue by cewbdex** [UnigramDev/Unigram#1777]
Steps to reproduce: Edit message, switch to another chat with having the message being edited (also the changes are discarded without any notice).

![image](https://user-images.githubusercontent.com/9021297/84180698-38984980-aa88-11ea-8f38-45ab177d698f.png)
Figure 1: Described bug

**Comment by FrayxRulez** [comment]
No longer reproduced this
