### ISSUE TITLE
Too narrow message bubble when picture is tall

### ISSUE THREAD

**Issue by ad1Dima** [UnigramDev/Unigram#1784]
It's difficult to read message, when message contains tall picture (for ex iPhone 11 screenshot) and have a lot of text:
![image](https://user-images.githubusercontent.com/3244664/84258628-74431a00-ab41-11ea-81e0-18caa604435b.png)

i guess there is two thing that can solve this:
1) set MaxHeight for picture
2) Allow text to make message bubble wider than picture

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/b441aac6f3fbe7887b6379de56a12fdeecd66524
