### ISSUE TITLE
Mismatched colors in folders...

### ISSUE THREAD

**Issue by satanyachan** [UnigramDev/Unigram#1785]
Come on ... when I select the theme dark (blue), should the folders on the left part follow the theme color? I think so: /, would it be possible to implement this? (get inspired by the desktop telegram :) )

![image](https://user-images.githubusercontent.com/59765148/84260099-d5da9880-aaef-11ea-98ec-995348553b4e.png)

**Comment by MarcAnt01** [comment]
I don't like TD UI, it'd be better to tint the sidebar with the main color👍

**Comment by FrayxRulez** [comment]
Fixed
