### ISSUE TITLE
Chat-Thumbnails sometimes don't load

### ISSUE THREAD

**Issue by rabiet** [UnigramDev/Unigram#179]
This was an error send to me by a user:

On the current Release Preview Build (.726) chatimages sometimes don't show up.
Tested on a Lumia 640 (on which the UI looks also bad)

Screenshots:

![False](https://cloud.githubusercontent.com/assets/15967138/23020448/766dfe4e-f447-11e6-8f57-4af1b43f474a.png)

![correct](https://cloud.githubusercontent.com/assets/15967138/23020480/9808bbc0-f447-11e6-9222-3d14d13b2eb3.png)

**Comment by FrayxRulez** [comment]
I close this issue since the problem was related to an old Unigram build and it is now fixed
