### ISSUE TITLE
Double minus to em-dash

### ISSUE THREAD

**Issue by mikekosulin** [UnigramDev/Unigram#1793]
Please add the conversion for double minus "--" to em dash "—". 
And allow canceling on ESC.

**Comment by cewbdex** [comment]
I do not believe this is the right thing for Unigram to do.

**Comment by FrayxRulez** [comment]
> I do not believe this is the right thing for Unigram to do.

All telegram clients do for some reason 🙄 I honestly don’t like this feature.

**Comment by MarcAnt01** [comment]
Yeah, imagine if I want to tell a friend to `git push --force` . That conversion would be really bad in this scenario

**Comment by nahuelwexd** [comment]
@MarcAnt01 Telegram Desktop checks if the double dash is inside a code block. If it is, then the conversion is skipped.

**Comment by cewbdex** [comment]
> 
> 
> @MarcAnt01 Telegram Desktop checks if the double dash is inside a code block. If it is, then the conversion is skipped.

Not everyone want to always use a code block, it's impractical for a lot of scenarios.
