### ISSUE TITLE
Missing update of member list after adding a user

### ISSUE THREAD

**Issue by hihain** [UnigramDev/Unigram#1796]
Adding a user to a group or channel does not update the user list. You have to go back and reopen it to see the change.
Also, it would be nice if depending on the place the popup would use the corresponding term like channel for adding a user for the channel. The string for that seems to be `ChannelAddTo`.
![image](https://user-images.githubusercontent.com/1473059/84440263-f4e54180-ac39-11ea-8270-b55decd6ccd1.png)

**Comment by FrayxRulez** [comment]
Done
