### ISSUE TITLE
Basic groups: Add function to add administrators to groups

### ISSUE THREAD

**Issue by hihain** [UnigramDev/Unigram#1797]
Currently upon opening the administrator list for a group:
![image](https://user-images.githubusercontent.com/1473059/84491075-49bda200-aca4-11ea-99b8-c41fd7591578.png)

My wish is to have the same UI as for channels here:
![image](https://user-images.githubusercontent.com/1473059/84490986-2f83c400-aca4-11ea-9119-2dc4fd9ec0b2.png)

A "Promote to Admin" flyout would be nice, too. (Like it exists for channels) :)

**Comment by MarcAnt01** [comment]
I see it here
![image](https://user-images.githubusercontent.com/43090263/84491834-77571b00-aca5-11ea-9961-b11b01b9509c.png)

**Comment by cewbdex** [comment]
> 
> 
> I see it here
> ![image](https://user-images.githubusercontent.com/43090263/84491834-77571b00-aca5-11ea-9961-b11b01b9509c.png)

He meant non-supergroup settings.

**Comment by MarcAnt01** [comment]
Yeah, all his issues seem to affect only basic groups
