### ISSUE TITLE
Basic groups: Edit Admin Rights of a Group: Missing UI

### ISSUE THREAD

**Issue by hihain** [UnigramDev/Unigram#1798]
This is how it looks right now and it just confuses me. ;)
![image](https://user-images.githubusercontent.com/1473059/84491178-6eb21500-aca4-11ea-930a-ccfeedcfcaa5.png)

**Comment by MarcAnt01** [comment]
I see the tile here
![image](https://user-images.githubusercontent.com/43090263/84491982-b71e0280-aca5-11ea-8567-3e2546e54dd9.png)

**Comment by cewbdex** [comment]
> 
> 
> I see the tile here
> ![image](https://user-images.githubusercontent.com/43090263/84491982-b71e0280-aca5-11ea-8567-3e2546e54dd9.png)

Happens in non-supergroups only.
