### ISSUE TITLE
Basic groups: User Permissions Page of a Group: Missing UI / is not self explanatory

### ISSUE THREAD

**Issue by hihain** [UnigramDev/Unigram#1799]
Empty UI on top and Duration is not self explanatory before clicking it and also the user has to remember which member he selected...
![image](https://user-images.githubusercontent.com/1473059/84491483-e8e29980-aca4-11ea-85c9-664ebf713dab.png)

**Comment by MarcAnt01** [comment]
Weird, I can see them properly. Are you sure you're checking in a supergroup?

**Comment by cewbdex** [comment]
For everyone's information: it affects basic groups only.
