### ISSUE TITLE
Compact mode: Folder selection with mouse.

### ISSUE THREAD

**Issue by dmnmsc** [UnigramDev/Unigram#1806]
Right now we are unable to change folder using mouse. Would be nice to implement a menu when clicking on current folder. Something like:

![400016200618_203467](https://user-images.githubusercontent.com/8472142/84541272-5e775580-acf7-11ea-9870-cc2064dc7233.jpg)

I know this is not a priority request because we can use shortcuts.

**Comment by cewbdex** [comment]
Could you tell me how to reproduce it? Since Everything works nicely for me.

**Comment by MarcAnt01** [comment]
@cewbdex resize the chats list until you have only icons

**Comment by MarcAnt01** [comment]
This compact mode doesn't exist any longer

**Comment by FrayxRulez** [comment]
Merging this with #2611
