### ISSUE TITLE
Getting notifications of messages I already read on another device

### ISSUE THREAD

**Issue by chagai95** [UnigramDev/Unigram#1807]
This is the main reason I use telegram, no other app has its notifications system synced so well across all platforms, is there a good reason why this does not work on Unigram? is it an issue only on my Windows? maybe it's only because I chose native notifications? does Unigram just push all notifications or does it check to see if they have already been read? this does work well on telegram desktop but then again they don't use native windows notifications...

**Comment by FrayxRulez** [comment]
Unigram uses a database for your messages and this database needs to be synced when you open the app. When this happens some of the messages are erroneously considered new and notifications are delivered. I’ve been looking a lot into fixing this and I think (thought?) to have found a way to mitigate the issue. The beta at https://t.me/unigramappx already contains this changes, so maybe you could give it a try and let me know.

**Comment by FrayxRulez** [comment]
Should be mitigated even more by https://github.com/UnigramDev/Unigram/commit/d8a42000b07f15acb4cd43035e87871f4bfd5d94.
Let's see... :)

**Comment by chagai95** [comment]
What about revoking notifications? Is this possible on Windows? I know it is on Android.

**Comment by FrayxRulez** [comment]
Notifications should get revoked. There might be some problems for the one generated via WNS tho...
Btw the main fix should be included in 4.1 release in the Store, let me know if it works!

**Comment by MarcAnt01** [comment]
@chagai95 can you still see the issue? I usually don't get notifications while I am using my iPhone

**Comment by chagai95** [comment]
I'll try again.

**Comment by chagai95** [comment]
I believe it worked, but I'll keep you updated if I see something

**Comment by chagai95** [comment]
![image](https://user-images.githubusercontent.com/31655082/100326360-27a5ab00-2fca-11eb-9720-68628629d4f8.png)
still the same problem with notifications from windows

**Comment by chagai95** [comment]
I think it might only be happening when the app is closed, the notifications still arrive but do not disappear when read elsewhere. Also I can't change it to not have windows notifications, I think. like on the official client where it has a setting for this.
![image](https://user-images.githubusercontent.com/31655082/100326767-aac70100-2fca-11eb-86ee-7e691524aa7d.png)

**Comment by FrayxRulez** [comment]
I hope that this is fixed
