### ISSUE TITLE
Stickers panel opened by default once switched back from another view

### ISSUE THREAD

**Issue by AkazaRenn** [UnigramDev/Unigram#1816]
Like this:
![image](https://user-images.githubusercontent.com/8340896/84603647-eaa38d00-ae5d-11ea-8599-d63bf23ee3a5.png)

Steps to reproduce:
Open app in wide mode, open a chat, switch to another view (e.g. settings) and switch back, the stickers panel would show up all the time.

**Comment by FrayxRulez** [comment]
I believe I fixed this bug.
