### ISSUE TITLE
Activating PiP causes program to crash

### ISSUE THREAD

**Issue by incIined** [UnigramDev/Unigram#1817]
Unigram 4.0 5183
Windows 1709 build 16299.125

When clicking on the PiP button in a downloaded video, the program will crash to desktop.

Video of the crash: 
https://t.me/s/unigraminsiders/283415

**Comment by Paclanc** [comment]
Can confirm. After closing the PiP windows the app crashes.

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/d93908d68f61ed8a17cc56d1095bccb43e141c7a
