### ISSUE TITLE
In some parts of the app some elements are tinted with the accent color, while other elements are not

### ISSUE THREAD

**Issue by AkazaRenn** [UnigramDev/Unigram#1818]
This part:
![image](https://user-images.githubusercontent.com/8340896/84603715-803f1c80-ae5e-11ea-932e-cd82c69cab08.png)

Not sure if it's by design because the three-dot menu icon stays black, I think they should match by any means.

**Comment by MarcAnt01** [comment]
Refactoring this ticket to be more generic since there are mismatched colors also in other parts of the app👍

**Comment by FrayxRulez** [comment]
Not sure if to have all buttons blue or black now?

**Comment by MarcAnt01** [comment]
Using dark blue theme I'd rather have them black/white

**Comment by AkazaRenn** [comment]
@FrayxRulez I'd rather see them all black

**Comment by MarcAnt01** [comment]
Fixed in the latest beta
