### ISSUE TITLE
No symbol for chats pinned in the archive

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1819]
![image](https://user-images.githubusercontent.com/43090263/84639418-a44f3c00-aef8-11ea-838b-13f14667de44.png)
I suggest putting this symbol like it's already done for "all chats"

**Comment by FrayxRulez** [comment]
I can see it for my archived and pinned chats?

**Comment by MarcAnt01** [comment]
I cannot
![image](https://user-images.githubusercontent.com/43090263/84663680-c6a78080-af1d-11ea-8c46-eb973df82e63.png)

**Comment by FrayxRulez** [comment]
Well, that's because the chat is unread. Same applies to any other Telegram app.
