### ISSUE TITLE
pinned chats start moving around again

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#182]
Like the title says, the pinned Chats are just in order with all other Chats again..
They are still marked as pinned Chats but not anymore on the top.

Sadly I made no screenshot and also I found no way to reproduce it after I restarted the App.

**Comment by alighamari** [comment]
@larsschellhas Too in here

**Comment by larsschellhas** [comment]
@larsschellhas

**Comment by Marocco2** [comment]
Da: Lars Schellhas<mailto:notifications@github.com>
Inviato: domenica 26 febbraio 2017 15:31
A: UnigramDev/Unigram<mailto:Unigram@noreply.github.com>
Cc: Subscribed<mailto:subscribed@noreply.github.com>
Oggetto: Re: [UnigramDev/Unigram] pinned chats start moving around again (#182)


@larsschellhas<https://github.com/larsschellhas>
