### ISSUE TITLE
GIFs preview isn't closed with touchpad/mouse

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1820]
It basically happens every time the click is released with the cursor being outside of the GIFs panel (for example in chats list or within the chat)

**Comment by FrayxRulez** [comment]
This should be fixed, at least for GIFs, by https://github.com/UnigramDev/Unigram/commit/7916388c5423dbf9be2419c4126cfa83c046bb28

**Comment by MarcAnt01** [comment]
Can no longer reproduce
