### ISSUE TITLE
UI crashing when window maximized and emoji label open closed multiple times

### ISSUE THREAD

**Issue by tannmaysgupta** [UnigramDev/Unigram#1824]
UNIGRAM 4.0 (5098)
Windows 10 build 1909 

If I open a chat with the sticker panel enabled upon closing it, the whole UI crashes. Everything seems functional but the UI is crashing. 

![image](https://user-images.githubusercontent.com/26500944/84755556-62e58c00-afdf-11ea-8fa6-8f22b5fdcfbe.png)

This is not happening if I enable the adaptive layout or if I am using it in a smaller width size window with the sticker overlay

NOTE: Orange doodle is for sensitive information

**Comment by FrayxRulez** [comment]
4.1 is available in the store, while I don't think it would fix the issue, would be nice if you could update to the latest version. Thanks!

**Comment by tannmaysgupta** [comment]
Lemme try and will update the issue

**Comment by MarcAnt01** [comment]
@tannmaysgupta any update about the current situation?

**Comment by tannmaysgupta** [comment]
Haven't seen the error recently. I think we should close this issue :)

**Comment by FrayxRulez** [comment]
💪
