### ISSUE TITLE
Function keys not working on Unigram 4.x

### ISSUE THREAD

**Issue by sukiletxe** [UnigramDev/Unigram#1825]
In Unigram 4.x, pressing f1 through f7 doesn't filter chats as in previous versions. F7 only yields a dialog about selecting text with the keyboard (much like in Firefox).

**Comment by FrayxRulez** [comment]
FX shortcuts have been replaced by CTRL+number

**Comment by sukiletxe** [comment]
If I press ctrl+5 (which should, if I understand it correctly) filter by channels, I get no filters applied. Ctrl+6 (unread) doesn't work either. (Also the wiki is out of date). Do I need to add these to shortcuts.json (creating it first) or is the default behaviour this one (and hence something is broken)?

**Comment by MarcAnt01** [comment]
Filters are no longer a thing, shortcuts are linked to folders. If ctrl + 5 does nothing, that means that you have just 4 folders

**Comment by sukiletxe** [comment]
Ah, I see. Thing is I don't use folders. Would it be possible to bring filters back in some way? They are way more convenient, especially now that I don't know of any accessible way to create folders (accessible as in compatible with screen readers).

**Comment by MarcAnt01** [comment]
Filters aren't coming back, anyway you can easily create folders to be similar to filters from settings > folders. If you are having any problems with accessibility in this section, feel free to open a new ticket for that

**Comment by sukiletxe** [comment]
Ah thanks, kinda works with some patience.

**Comment by MarcAnt01** [comment]
That has to be done just once since folders are server side
