### ISSUE TITLE
GIF popup bottom corners

### ISSUE THREAD

**Issue by FinecoFinit** [UnigramDev/Unigram#1828]
![image](https://user-images.githubusercontent.com/22540805/84903497-ff875700-b0cf-11ea-86f3-505792590f82.png)

**Comment by FrayxRulez** [comment]
Hello. Can you explain what's the problem here?

**Comment by WeFenFinit** [comment]
@FrayxRulez not rounded corners, looks like another square block beneath or above

**Comment by FrayxRulez** [comment]
GIF popup corner radius respects the app design language corner radius for popups, hence it is not going to be changed.
