### ISSUE TITLE
Shortcut feature disappeared after upgrading

### ISSUE THREAD

**Issue by Jack-Works** [UnigramDev/Unigram#1835]
In the old version of Unigram, it is possible to press Ctrl+1 to "All chats", Ctrl+2 to "Contacts", Ctrl+7 to "Unread chats" etc. It no longer working in the latest version

**Comment by FrayxRulez** [comment]
Hello, you can now create your custom folders from Settings! 🕺 shortcuts will work the same with them

**Comment by MarcAnt01** [comment]
Hello, I think you confuse with function keys, in case there's already this ticket https://github.com/UnigramDev/Unigram/issues/1825

**Comment by Jack-Works** [comment]
> Hello, I think you confuse with function keys, in case there's already this ticket https://github.com/UnigramDev/Unigram/issues/1825

Oh yes, I mean F1 to F7 keys
