### ISSUE TITLE
Lag when gaining focus with displayed animated stickers

### ISSUE THREAD

**Issue by entdark** [UnigramDev/Unigram#1837]
The right panel with emoji, gifs and stickers is always presented now.
If the tab with stickers selected and there are bunch of animated sticker sets displayed then after switching off Unigram then switching back (Unigram window gains focus) then there is lag about 1-2 seconds in the input field. So you cannot start typing instantly. All the stickers have to start animating again and after that the input field becomes active again.

I am not sure about the solution, but is there a necessity to always display the right panel? I think it's too huge thing. If you tried to copy the TD behavior then they also have an option to hide that panel.

Anyways, I would like to not have any input lag when I switch to Unigram as it used to be before.
It also works fine if stickers are not animated.

**Comment by FrayxRulez** [comment]
Unigram already “copies” tdesktop behavior and you can close the panel in the exact same way.

**Comment by entdark** [comment]
Oh nice, that's even better for me. But the lag still persists in the always shown panel with animated stickers in case it still affects someone else.

**Comment by FrayxRulez** [comment]
It really depends on the hardware, I guess. I won’t suggest anyone to keep it open even on the most powerful PC.
