### ISSUE TITLE
[Request] Send Video as non file 

### ISSUE THREAD

**Issue by abh-oss01** [UnigramDev/Unigram#1839]
Add the ability to choose between sending the video as file OR as normal media (not as a file), to not retain the windows nomenclature and timestamps...

**Comment by MarcAnt01** [comment]
Hello, this feature is already present. The icon marked in blue is for sending as file, the one in green is for sending compressed.
![image](https://user-images.githubusercontent.com/43090263/84994139-85e07f00-b14a-11ea-9532-a4b6e137f6ba.png)
