### ISSUE TITLE
Visual bugs with extended formatting view and voice recoder

### ISSUE THREAD

**Issue by hihain** [UnigramDev/Unigram#1840]
Issues seem related:
- Buttons move down, but it does not give more space for writing in chat textbox
![image](https://user-images.githubusercontent.com/1473059/85036758-cd83fc80-b184-11ea-9f87-4e2ccd4edfe6.png)

- On Voice Message everything moves down for new voice message controls so chat textbox placeholder text overlaps with formatting buttons
![image](https://user-images.githubusercontent.com/1473059/85036736-c78e1b80-b184-11ea-81b4-b80263537820.png)

- If swiped to the left recording a voice message and locking for keep recording without having to hold the left mouse  button clicked. (mainly an issue in tablet mode on small screens - or on desktop having Unigram only use half the desktop space (depends on resolution)) ![ezgif-6-f2d399671d43](https://user-images.githubusercontent.com/1473059/85035707-c4466000-b183-11ea-8a3b-732cdcd1eb4d.gif)

**Comment by FrayxRulez** [comment]
This is gone
