### ISSUE TITLE
Switch between light/dark theme in hamburger menu

### ISSUE THREAD

**Issue by Serarg95** [UnigramDev/Unigram#1842]
I suggest introducing a button to switch between light/dark theme that works in the same way as the mobile apps one does. I think its a nice feature because sometimes "auto dark mode" is not enough and u may need switch between themes in differente situations during the day.

**Comment by MarcAnt01** [comment]
I don't see any switch apart from the one in settings in Telegram for iOS, can you be clearer?

**Comment by Serarg95** [comment]
> I don't see any switch apart from the one in settings in Telegram for iOS, can you be clearer?

Yeah. Telegram for Android 
![Screenshot_20200619_185731](https://user-images.githubusercontent.com/66536926/85160646-e2cd5980-b25e-11ea-8f6c-59ca3efb122a.jpg)

**Comment by MarcAnt01** [comment]
This has been implemented now
