### ISSUE TITLE
Cannot return to login after setting up proxy server

### ISSUE THREAD

**Issue by MarksonHon** [UnigramDev/Unigram#1843]
![Picture](https://user-images.githubusercontent.com/50002150/85189146-9d507100-b2de-11ea-9d9f-f028c2de9cc4.png)

There is no "back" bottom to return login after setting up proxy server, please fix it, thx.

**Comment by MarcAnt01** [comment]
Hello, we already have a ticket to keep track of that
Duplicate of https://github.com/UnigramDev/Unigram/issues/1707
