### ISSUE TITLE
Pinned message is not removable for groupmembers

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#185]
Not that @FrayxRulez wouldn´t know it yet, but just to remember it :D

If you are clicking on the "X" which is supposed to Close the banner of the pinned message, nothing happens. 

Actually if you hit it telling "SOS" in morse ( short short short break Long Long Long break short short short) Unigram sends you a private message, asking you for whats going on.

**Comment by FrayxRulez** [comment]
It is now possible to unpin messages for both users and admins
