### ISSUE TITLE
Unable to send a voice message

### ISSUE THREAD

**Issue by Paclanc** [UnigramDev/Unigram#1855]
I'm trying to send a voice message, but the button simply doesn't do anything. When I press the button nothing happens. In fact, if I press it several times, the app crashes. If I restart and press it a bunch of times more, it freezes windows.
![image](https://user-images.githubusercontent.com/25404951/85241266-e6004b00-b400-11ea-8a85-c47d7847304f.png)

 I already gave the app permission to use the mic.

**Comment by MarcAnt01** [comment]
Does Windows Voice Recorder work properly for you?

**Comment by MarcAnt01** [comment]
Duplicate of https://github.com/UnigramDev/Unigram/issues/1856
