### ISSUE TITLE
can't send audio messages using virtual microphones

### ISSUE THREAD

**Issue by sanslash332** [UnigramDev/Unigram#1856]
Hello guys,

A small problem that I've detected for send audio messages.

When I pick up a virtual microphone as my system default microphone, I can't press the record button (or press ctrl+r) to start the record a new audio message. But, the microphone is working well with any other aplication; like whatsapp web, discord, teams or audio recorders.

If I return my default microphone to a physical microphone (sound blaster board in my case) the button works again and you can sent audio messages.

I've checked that the virtual microphone is selected too in unigram settings, but it didn't work.

When I say  virtual microphone, I am talking about applications like ez mic https://www.ez-mic.com/
 or virtual audio cable https://vac.muzychenko.net/en/

Exist in unigram a limitation of the kind of microphones that you can use on the program? or any device recognized as microphone in the windows devices should work.

Both of these mentioned tools create a virtual device on the windows prefferences so are dettected as real hardware.

So well, thanks for your support! the client is awesome!

**Comment by MarcAnt01** [comment]
Rather than browsers and Electron apps, can you try to see if Windows Voice Recorder records anything?

**Comment by sanslash332** [comment]
@MarcAnt01 thanks for your answer :)

Interesting; I tested the microphones with win32 native applications like audacity, reaper, teamtalk classic or open broadcaster software, and they works fine, without problem. Next, I tested them with the windows10 skype application (not skype8 the electron app, the native windows10 application) and again it works fine. But with the store version of the windows sound recorder the application can't record.
When I press the record button, it stocked at pressed position and i can't press it again to stop recording, or appear a stop button, or an error. Simply the only that i can do is close the recorder.

Maybe is a problem between the virtual drivers and the permission layout of the store windows apps?

Anyway I checked the permissions of the recorder (and unigram) and both applications have enabled the access to the microphones; and when I checked it with the physical microphone of my laptop they works fine.

Thanks for your support! If you think another test I can do it without problems!

Thanks for your awesome program!

**Comment by MarcAnt01** [comment]
The fact that Windows Voice recorder isn't working explains that it's clearly something Windows-side. Skype app from Microsoft Store is Electron now btw

**Comment by sanslash332** [comment]
@MarcAnt01 thanks for your feedback!

Na, wasn't the store skype; is the skype that windows 10 has from the installation.

But, do you know if store apps restrict the interaction with non-signed drivers?

Apparently the drivers of ez mic and virtual audio cable, are non-signed drivers, so when you install them, windows ask you explicitly if you want allow the installation of them.

Maybe that is the reason.

:)

**Comment by MarcAnt01** [comment]
It's not connected to Store, but to uwp app model where a lot of stuff is handled by Windows rather than the app

**Comment by sanslash332** [comment]
OK @MarcAnt01 thanks for your feedback. Its extrange, but... well. is a problem between the driver and windows.
thanks :)

**Comment by MarcAnt01** [comment]
@sanslash332 I don't know how to help you to solve your problem, I guess you could try to use Feedback Hub, even if it's not the best place to report the bug, I don't have any other ideas sadly

**Comment by sanslash332** [comment]
yea, don't worry. Its only windows being windows :)
