### ISSUE TITLE
Stickers panel docking state is not kept

### ISSUE THREAD

**Issue by Sominemo** [UnigramDev/Unigram#1861]
## Steps to reproduce
1. Dock or undock the panel (state A)
2. Restart Unigram
3. Open a chat
4. Change panel docking state (state B)
5. Open chat information screen
6. Get back

## Expected behavior 
The stickers panel is in state B

## Actual behavior
The stickers panel is in state A

**Comment by FrayxRulez** [comment]
Is this fixed?

**Comment by FrayxRulez** [comment]
Yes

**Comment by Sominemo** [comment]
No
