### ISSUE TITLE
Show in Chat option in media player

### ISSUE THREAD

**Issue by ze0ss** [UnigramDev/Unigram#1863]
Add an option to show an audio file in chat from the now playing menu at the top directly (attached photo), instead of navigating to Group/Chat title --> Audio/Voice messages --> Right click and show in chat.

![](https://i.imgur.com/stqeLC0.jpg)

**Comment by FrayxRulez** [comment]
This is done in https://github.com/UnigramDev/Unigram/commit/ed71daec99ba4752e3e65b263beb2b9d5ba2e7ce
