### ISSUE TITLE
Taskbar unread message badge doesn't update after receiving push notification

### ISSUE THREAD

**Issue by dckface** [UnigramDev/Unigram#1867]
After receiving a push notification, I'd expect the taskbar badge to be updated, just like in case of Mail or Your Phone apps.

## Steps to reproduce
1. Enable push notifications.
2. Close Unigram app.
3. Receive a push notification.

## Expected behavior
After receiving a push notification, taskbar unread message badge should be updated.

## Actual behavior
The push notification is correctly shown, notification is stashed in Action Center, but the badge is not updated. Once the app is launched again, the taskbar correctly updates.

**Comment by FrayxRulez** [comment]
This is expected as Telegram servers don't provide a accurate count for the badge when sending push notifications...

**Comment by dckface** [comment]
Ah, that's fair. I suspected that might be the case, but I wasn't entirely sure.

Wouldn't it be possible to implement it in a way similarly to Skype? AFAIK, in case of Skype, the badge doesn't show unread messages, but number of unread chats. But I honestly don't know what exactly is Telegram's notification API providing. 

Alternatively, I feel like showing at least some kind of badge might be fairly useful, even if the number is incorrect (for example, always setting the badge to "1" after receiving a push notification), as it at least signals user that there is some message to read. But I understand that might be outside the range of desired behavior of the app.

**Comment by dckface** [comment]
Would there be interest in implementing the behaviour I described (i.e. showing at least anything on taskbar badge upon receiving push notifications)? I could try and look into it

**Comment by FrayxRulez** [comment]
Actually, the badge should get updated already, just the counter isn't accurate.

**Comment by dckface** [comment]
Ah, cool. Since which version does the badge update?

**Comment by FrayxRulez** [comment]
Theoretically, since ever

**Comment by dckface** [comment]
Well, for me, the badge was always showing if and only if Unigram was already running - either minimized on Taskbar, or, in older times, in form of a tray icon. What I meant was showing the taskbar badge if Unigram isn't running (but still has push notifications enabled), similarly how Mail, To-do or Your Phone apps are doing it.

**Comment by MarcAnt01** [comment]
Closing this, since push notification have been removed now
