### ISSUE TITLE
Autocomplete 👍 emoji

### ISSUE THREAD

**Issue by strollingHeifer** [UnigramDev/Unigram#1870]
I'm not sure if I mix this up with other messengers, but I feel like Unigram used to autocomplete '(Y)' into the the thumbs-up emoji (👍). It does not do that for me in v4.2. Other emojis like ':D' are still being autocompleted.

**Comment by MarcAnt01** [comment]
Done in https://github.com/UnigramDev/Unigram/commit/c5bf811234eb9b99bf00dcceececd9c83b7e5ce9
