### ISSUE TITLE
Opus audio is not playing in videos (mp4)

### ISSUE THREAD

**Issue by megapro17** [UnigramDev/Unigram#1871]
This audio codec is allowed in mp4 container, and you can play it in official telegram, but in unigram videos are completely silent, even when opus audio files are played correctly

**Comment by FrayxRulez** [comment]
Unigram, being a Windows only software and more specifically a UWP app, hosts a Microsoft [Media Foundation](https://en.wikipedia.org/wiki/Media_Foundation) component ([MediaPlayer](https://docs.microsoft.com/en-us/uwp/api/windows.media.playback.mediaplayer?view=winrt-19041)) to play videos.

**Comment by megapro17** [comment]
Can you say me a correct place to report this bug? Or it is impossible to fix any bugs in windows itself... maybe you'll add some workaround?

**Comment by FrayxRulez** [comment]
A workaround would consist in including a custom video player/codec just for this, and I don't think it's really the case.
I think that Feedback Hub might be the right place where to report this, but I'm not 100% sure...

**Comment by megapro17** [comment]
Ok, i created issue here, bump it pls https://aka.ms/AA8sbyk

**Comment by megapro17** [comment]
webm should be embedded too

**Comment by FrayxRulez** [comment]
@megapro17 Such as the one reported here
