### ISSUE TITLE
Add an option to set the cache size for stickers

### ISSUE THREAD

**Issue by entdark** [UnigramDev/Unigram#1873]
I was cleaning disk recently and found out that Unigram cached all the stickers to 3+ GB (folder size).
I think stickers are not worth that to take so much disk space and I'd like to limit how many bytes stickers are allowed to take.
So could you add such an option similar to Automatic media download option?

**Comment by hihain** [comment]
Perhaps integrate the cache size limits as in Telegram Desktop and make it more detailed, like adding maximum sticker cache size?
![image](https://user-images.githubusercontent.com/1473059/95795266-3837e580-0cea-11eb-8090-5ee024f7cb2b.png)

**Comment by FrayxRulez** [comment]
Non-accessed stickers are automatically cleaned up after three days, I believe this is enough.
