### ISSUE TITLE
Force close on startup if regional format is set to Chinese

### ISSUE THREAD

**Issue by Summon528** [UnigramDev/Unigram#1878]
```
Microsoft Windows [Version 10.0.19042.330]  (Version 20H2)
Unigram Version 4.2.5263.0
```
Force close on both my laptop and desktop, briefly shows an "Updating" screen and the app crashes, no error message.
Reinstall does not help, force close after signing in.

![image](https://user-images.githubusercontent.com/10328757/85943782-dc2c9980-b964-11ea-8ba2-09fedc8836be.png)

**Comment by FrayxRulez** [comment]
I would need to know your PC model, so that I can search this in the crash logs.
Would be nice if you could also turn on crash dumps for the app, to do so you must create a text file having this content:
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps\38833FF26BA1D.UnigramPreview_4.2.5263.0_x64__g9c9v27vpyspw]
"DumpFolder"=hex(2):25,00,4c,00,4f,00,43,00,41,00,4c,00,41,00,50,00,50,00,44,\
  00,41,00,54,00,41,00,25,00,5c,00,43,00,72,00,61,00,73,00,68,00,44,00,75,00,\
  6d,00,70,00,73,00,5c,00,33,00,38,00,38,00,33,00,33,00,46,00,46,00,32,00,36,\
  00,42,00,41,00,31,00,44,00,2e,00,55,00,6e,00,69,00,67,00,72,00,61,00,6d,00,\
  50,00,72,00,65,00,76,00,69,00,65,00,77,00,5f,00,34,00,2e,00,30,00,2e,00,35,\
  00,30,00,37,00,37,00,2e,00,30,00,5f,00,78,00,36,00,34,00,5f,00,5f,00,67,00,\
  39,00,63,00,39,00,76,00,32,00,37,00,76,00,70,00,79,00,73,00,70,00,77,00,00,\
  00
"DumpCount"=dword:0000000a
"DumpType"=dword:00000002
"DeveloperAppOnly"=dword:00000000
```

You must save it using `.reg` extension, and then you can double click to install it.

**Comment by Summon528** [comment]
My PC is a custom-built one:
```
CPU: AMD Ryzen 5 3600
MB: ASUS B450-I Strix
RAM: 32GB
GPU: AMD Vega56
```

Upon inspecting the core dump myself, I manage to narrow down the bug. The app crashes if I set `Regional format` to `Chinese (Traditional, Taiwan)` and works fine if it is set to `English (United States)`. If you still need the dump file I can PM you, I don't think posting a core dump file publicly is a good idea.

**Comment by FrayxRulez** [comment]
Yes, it would be nice if you could send it to me on telegram, username is the same as here. Thanks!

**Comment by FrayxRulez** [comment]
Can't reproduce the issue.

**Comment by Summon528** [comment]
Neither can I. Perhaps it  was fixed
