### ISSUE TITLE
Playing bar and icons are misaligned in PIP video player

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1886]
![image](https://user-images.githubusercontent.com/43090263/86218451-14102880-bb81-11ea-9f8e-79262f6f4196.png)

**Comment by cewbdex** [comment]
I was told it is a MS issue, impossible to fix.

**Comment by FrayxRulez** [comment]
Please redirect this issue to https://github.com/microsoft/microsoft-ui-xaml
