### ISSUE TITLE
Select the text when the focus in on a textbox

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1887]
Actual behavior
![image](https://user-images.githubusercontent.com/43090263/86250365-c57a8280-bbb0-11ea-9ca8-ba5f24ca8d06.png)

Expected behavior
![image](https://user-images.githubusercontent.com/43090263/86250420-d62af880-bbb0-11ea-957c-0328462607db.png)

**Comment by FrayxRulez** [comment]
That's not the expected behavior, as this kind of stuff is literally controlled by the system
