### ISSUE TITLE
Background pattern doesn't show up

### ISSUE THREAD

**Issue by githubcatw** [UnigramDev/Unigram#1889]
Hello. I use a pattern for my background:
![image](https://user-images.githubusercontent.com/17374742/86352701-44d28980-bc77-11ea-8deb-dc79a9875a56.png)
It shows up in the preview correctly:
![image](https://user-images.githubusercontent.com/17374742/86352748-5582ff80-bc77-11ea-880f-e7ca166a4435.png)
But when I go to an actual chat, the pattern is gone:
![image](https://user-images.githubusercontent.com/17374742/86352787-6895cf80-bc77-11ea-8902-5c74c4a21ddc.png)
Unigram 4.1 (5260), Windows 10 Home v1909.

**Comment by FrayxRulez** [comment]
Fixed
