### ISSUE TITLE
Jump back and forward in voice messages

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#189]
It would be good if we could jump to any point in a voice message by tapping on the audiograph or "drag and drop" the point of play.

I would label it as improvement, but I cannot label yet... :)

**Comment by MarcAnt01** [comment]
Another enhancement for vocal messages should be adding pause symbol, when it's paused

**Comment by larsschellhas** [comment]
I´ve reopened #298

**Comment by MarcAnt01** [comment]
Perfect👍

**Comment by FrayxRulez** [comment]
It is now possible using the player bar, maybe I'll add this to the messages themselves in the future, for now I'm closing this as the feature is actually available.

**Comment by MarcAnt01** [comment]
Player bar is still far fromworking as expected, because it's divided into some sections and I can go to the beginning of each one.
Don't know if it is better to reopen this or create a ticket with improvements for player bar.
