### ISSUE TITLE
Revert #1221 and remove shadow from icon

### ISSUE THREAD

**Issue by Sominemo** [UnigramDev/Unigram#1890]
New Start menu tiles don't need the shadow anymore, it looks ugly
![image](https://user-images.githubusercontent.com/19842935/86371529-a4399500-bc89-11ea-9e7d-27904c9ccd0c.png)
I suggest removal of the shadow (so revert #1221)

**Comment by MarcAnt01** [comment]
New start menu? I still see it here
![image](https://user-images.githubusercontent.com/43090263/86381035-2081a780-bc8d-11ea-9940-558957e55365.png)

**Comment by cewbdex** [comment]
> 
> 
> New start menu? I still see it in this way here
> ![image](https://user-images.githubusercontent.com/43090263/86381035-2081a780-bc8d-11ea-9940-558957e55365.png)

New Windows insider build

**Comment by MarcAnt01** [comment]
I have looked into and this feature is still being tested and rolled out to some users in the insider program, so it won't make sense in the actual stage
