### ISSUE TITLE
Custom font selection 

### ISSUE THREAD

**Issue by HamidRezaAshkiyan** [UnigramDev/Unigram#1893]

**Comment by FrayxRulez** [comment]
Sorry, but Unigram can't support custom font selection.

**Comment by HamidRezaAshkiyan** [comment]
Can I ask why?

**Comment by FrayxRulez** [comment]
We use a custom font already to allow you to use Apple emojis rather than Microsoft ones. Also I'm pretty sure that people would start to complain about the app not working properly, and that in the end the problem would actually be custom fonts.

**Comment by HamidRezaAshkiyan** [comment]
I see. What is the font you are using now? ( I love to have apple emoji in my apps too that's why i'm asking)

And is there any way to merge a good Persian font like (vazir, estedad,...) in unigram like what main telegram did.

**Comment by FrayxRulez** [comment]
We're using a custom font generated with a tool I made. No, it's not possible to use Vazir, as we can't specify two fonts (one for text, one for emojis)

**Comment by Sominemo** [comment]
@FrayxRulez Wait does UWP render that apple font correctly?

**Comment by FrayxRulez** [comment]
> @FrayxRulez Wait does UWP render that apple font correctly?

There's no Apple font involved in this.

**Comment by HamidRezaAshkiyan** [comment]
Can I ask what is the tool you made? And is there anyway to download it?
