### ISSUE TITLE
Support Persian Calendar

### ISSUE THREAD

**Issue by HamidRezaAshkiyan** [UnigramDev/Unigram#1895]
It is amazing if you add support for Alternative calendar.

I recommend Persian calendar first cause i need it : )

**Comment by MarcAnt01** [comment]
Do you need a different calendar just in the DatePicker?

**Comment by HamidRezaAshkiyan** [comment]
Wow it is amazing I just saw that all of my dates are in Persian calendar. I taught it is like telegram desktop and doesnt support. 
UWP date picker pick time from my local machine. 

but it would be nice if i could choose between different calendar. Just a suggestion.

**Comment by MarcAnt01** [comment]
It's useless, Windows already chooses the proper calendar 👍
