### ISSUE TITLE
Broken UI when deleting non-existant image in chat

### ISSUE THREAD

**Issue by DarthJahus** [UnigramDev/Unigram#1898]
This glitch can be reproduced consistently.

* Send 2 images (album)
* Select the 2 images (drag select)
* Delete them (for the other user too) using `Delete` button
* One of them remains
* Right click on it, press `Delete` (on Keyboard)

This shows:
![image](https://user-images.githubusercontent.com/7353366/86935159-6e3a5c00-c134-11ea-9ffe-145f73922997.png)

The issue isn't encountered if you use Delete from the context menu.

**Comment by FrayxRulez** [comment]
The bug is that non existent image stays in the chat, not that the UI to delete it is broken.
