### ISSUE TITLE
Unigram only forwards the first image instead of the full album in certain conditions

### ISSUE THREAD

**Issue by DarthJahus** [UnigramDev/Unigram#1901]
If you use the **Share button** next to a set of images, it forwards them **correctly**.

However, if you **right-click** the message (on message header, timestamp or empty space next to it) and use Forward from the **context menu**, it will only and always forward the **first image** of the set.

----

Of course, if you target a specific image with the right click, that image gets forwarded (probably the intended action, here, so no issue).

**Comment by DarthJahus** [comment]
@DarthJahus Here, Sara

**Comment by MarcAnt01** [comment]
Seems to still occur unfortunately

**Comment by MarcAnt01** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/4ac56de44f98b1dcb0718ce0035f2bfb9d180b82
