### ISSUE TITLE
Drag and drop in chat not working

### ISSUE THREAD

**Issue by HamidRezaAshkiyan** [UnigramDev/Unigram#1902]

**Comment by MarcAnt01** [comment]
@HamidRezaAshkiyan Drag and drop is already supported. Can you specify the type of files you are having issues with?

**Comment by HamidRezaAshkiyan** [comment]
Actually I have problem with every file I want to send.

**Comment by MarcAnt01** [comment]
I think it's a problem of your PC, because everything works fine here with 2004. Have you tried to reboot it by chance? In some cases it's enough to fix random issues.

**Comment by HamidRezaAshkiyan** [comment]
Do you mean resetting Unigram from setting? or rebooting my PC?

**Comment by HamidRezaAshkiyan** [comment]
I just installed in another pc and it worked fine. But I'm still experiencing same issue on my pc.

**Comment by MarcAnt01** [comment]
Can you test if it works on Mail app?

**Comment by HamidRezaAshkiyan** [comment]
That was a very good idea. I have same problem there too.

**Comment by MarcAnt01** [comment]
Then, it's due to Windows, not to Unigram. I advice you to try to post a feedback in Feedback Hub app saying that you can't drag and drop to UWP apps (that will probably ignored) or try a reset.

**Comment by HamidRezaAshkiyan** [comment]
Thanks

**Comment by HamidRezaAshkiyan** [comment]
If anyone have same issue by UWP apps: I have fixed this issue by using a windows iso. start exe in iso and upgrade windows (make sure select keep files and apps, otherwise everything will be deleted.) after windows upgrade completed issue should be gone.
