### ISSUE TITLE
Add a separator in chats list between pinned chats and non-pinned ones.

### ISSUE THREAD

**Issue by ze0ss** [UnigramDev/Unigram#1903]
Add a divider, such as a gap of 15 pts or just a blank gap between the pinned chats and non-pinned ones, to better differentiate between the same. Refer the image below for context, the yellow line is the location where it can be added :)

![image](https://user-images.githubusercontent.com/56572179/87124771-fb9dbd80-c2a6-11ea-82e5-e4778d0e94cb.png)

**Comment by FrayxRulez** [comment]
No plans to do this
