### ISSUE TITLE
Add option to customise "padding" in addition to "corners"

### ISSUE THREAD

**Issue by Sav22999** [UnigramDev/Unigram#1904]
It could be a nice feature could be able to customise also padding.
Personally I would like a more padding (internal margin) because the height of buttons is too small.

**Comment by MarcAnt01** [comment]
Hello, which elements do you think that should have more padding? Mind adding some screenshots?

**Comment by Sav22999** [comment]
E.g. For buttons:
![image](https://user-images.githubusercontent.com/32335378/87243227-a0013a80-c434-11ea-8849-ed910efba8c6.png)

**Comment by FrayxRulez** [comment]
While it makes sense to increase some paddings by default, an option to do this won't come any time soon
