### ISSUE TITLE
Add option to show the icon in "Tray"

### ISSUE THREAD

**Issue by Sav22999** [UnigramDev/Unigram#1905]
I would like opening (when it's in background) the app from icon in system-tray

**Comment by a13ph** [comment]
≡ Menu → Settings → Advanced → Show tray icon

**Comment by MarcAnt01** [comment]
Hello, Unigram used to have a tray icon,  but it lead to major issues, so it's been removed and it won't come back. The "problem" is that UWP apps aren't thought to work with a tray icon.

**Comment by MarcAnt01** [comment]
Whatever, notifications are received in background, so there's no need for such thing 😄

**Comment by Sav22999** [comment]
@MarcAnt01 yes, it works in background... but sometimes I need to open anyway Telegram

**Comment by MarcAnt01** [comment]
There are plenty of other ways to do it. For example I usually do it by Windows Search that pins the apps I use the most, otherwise you can pin it to the taskbar or to the start menu

**Comment by Sav22999** [comment]
Yup, but personally I prefer the Tray. Anyway, no problem, if it causes problems it's not a problems. Thanks anyway

**Comment by MarcAnt01** [comment]
Yeah, a lot of users (usually the ones who prefer Win32 apps over UWP) have asked for this feature, but adding it to UWP apps is a hack and with Unigram it was causing major issues like always being online.

**Comment by Sav22999** [comment]
Yup, I can understand. For now I've added it on the taskbar, but it's not the best, because I open often it accidentally 🤣
