### ISSUE TITLE
Some option missing when we click on 3 dots in channel

### ISSUE THREAD

**Issue by binamracode** [UnigramDev/Unigram#1911]
![image](https://user-images.githubusercontent.com/61900781/87423851-b527c600-c5fa-11ea-8c6f-65992d4f6b96.png)
As you can see this is the main telegram app and
![image](https://user-images.githubusercontent.com/61900781/87423893-ca045980-c5fa-11ea-82b3-673676950f67.png)
This is the *unigram app*. This is the option that comes when we click on three dots inside the channel.
In Unigram some options are missing like **Export channel history** and **leave channel**.

I think that should come soon in **Unigram**.

**Comment by MarcAnt01** [comment]
Exporting channel history is a Telegram Desktop only feature and it's not planned, but it would be nice to have the button to leave the channel in that place

**Comment by binamracode** [comment]
Oh, Ok but is there any problem while putting the export channel history feature.

**Comment by MarcAnt01** [comment]
https://github.com/UnigramDev/Unigram/issues/1010

**Comment by FrayxRulez** [comment]
That feature is designed for Telegram Desktop only.
