### ISSUE TITLE
Cannot manage Unigram to Unigram calls

### ISSUE THREAD

**Issue by Vas0sky** [UnigramDev/Unigram#1913]
I've been trying to call my girlfriend on Unigram for a while now (she also uses Unigram 4.2), but call are basicall miss or miss. We answer the call (either me or her) but the windows says "connecting" for a few seconds and then says "failed to connect". As a workaround I currently force close unigram from the task manager, the next call I recieve usually works and connects properly (until it randomly disconnects for no reason, but that's another issue).

**Comment by silenceleaf** [comment]
same issue here, can this be prioritized?

**Comment by matze19999** [comment]
Same problem here...

**Comment by MarcAnt01** [comment]
The developer is busy till September, so there's no way to prioritize that

**Comment by MarcAnt01** [comment]
In 7.0 this should be fixed, feel free to reopen the ticket if the issue persists
