### ISSUE TITLE
Application interface freezes

### ISSUE THREAD

**Issue by cawa-93** [UnigramDev/Unigram#1915]
Sometimes I find that the program interface is stuck. He stops reacting to any actions.

I've noticed that this happens when I switch to another desktop. When I return - the program is stuck. And to see her work you need to resize the window.

It's hard to explain what's going on, so I'm adding a demonstration video.
https://youtu.be/2wu_WSZmuCY

It is also strange that when the interface hangs and I resize the window, it seems to "double" for a second
![2020-07-15 12-15-21_Moment](https://user-images.githubusercontent.com/1662812/87528907-e2c24d00-c696-11ea-9268-1808d5c1b4d8.jpg)

**Comment by FrayxRulez** [comment]
This looks more like a Windows bug, to me.

**Comment by cawa-93** [comment]
I've stopped noticing this problem lately. Maybe it's outdated.

**Comment by melroyvandenberg** [comment]
I actually have this issue as well. It seems the app hangs.. not sure why. I can only kill it using task manager. But the UI is not responding under Windows at some moment in time (often after several minutes already).

**Comment by FrayxRulez** [comment]
> I actually have this issue as well. It seems the app hangs.. not sure why. I can only kill it using task manager. But the UI is not responding under Windows at some moment in time (often after several minutes already).

Hard to investigate without repro steps
