### ISSUE TITLE
Drag and drop files from the chat

### ISSUE THREAD

**Issue by TheNcar** [UnigramDev/Unigram#1916]
Adding an option to drag and drop files **from** telegram, just like the official version.

**Comment by MarcAnt01** [comment]
In which section are you able to drag and drop them from Telegram Desktop?

**Comment by TheNcar** [comment]
> In which section are you able to drag and drop them from Telegram Desktop?

Any file can be dragged and dropped from telegram (it will be copied).

**Comment by MarcAnt01** [comment]
From Telegram is vague, I am asking you from which section (shared media, chat, chat list etc.)

**Comment by TheNcar** [comment]
> From Telegram is vague, I am asking you from which section (shared media, chat, chats list etc.)

Every media in every place that displays media.

**Comment by MarcAnt01** [comment]
No, that's no true. With Telegram Desktop it just happens within the chat

**Comment by MarcAnt01** [comment]
In the other section it's not draggable

**Comment by TheNcar** [comment]
> In the other sections it's not draggable

Fine, for chat then

**Comment by FrayxRulez** [comment]
This was implemented
