### ISSUE TITLE
"Recent Actions" in Unigram mismatches with other Telegram clients

### ISSUE THREAD

**Issue by Marocco2** [UnigramDev/Unigram#1918]
For some reason, Unigram doesn't tell the truth.

Steps to reproduce:
1. Admin had to delete an other user's message in a public supergroup
2. Go to Recent Action

Expected behaviour:
It should say that Admin deleted that message
![immagine](https://user-images.githubusercontent.com/3944248/87768535-91dc6100-c81c-11ea-8560-ead454472d5d.png)

Actual behaviour:
![immagine](https://user-images.githubusercontent.com/3944248/87768572-a3256d80-c81c-11ea-92c5-701c29321be7.png)

Unigram 4.1.5260

**Comment by MarcAnt01** [comment]
This should be fixed in Unigram 4.2
