### ISSUE TITLE
loading newer messages jumps down to the most recent loaded message

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#192]
When you scroll down to the last yet shown message and Unigram loads the next "group" of messages, it jumps directly to the last of the new loaded messages, loads the next messages, jumps to the latest,loads the next, jumps,... And so on until you arrive to the real most recent message in the chat/channel.

**Comment by alighamari** [comment]
@larsschellhas I replied the First message of my chat and tapped on the last message botton reminding of messages made me very surprised and feels good

**Comment by dmnmsc** [comment]
I can replicate what  @larsschellhas says.

**Comment by dmnmsc** [comment]
I think you can close this. Working as expected here.

**Comment by hamedfwp** [comment]
Hi. This exactly happens to me on newest store build (0.8.666.0)
