### ISSUE TITLE
Invisible text after automatically stitching to dark mode

### ISSUE THREAD

**Issue by mrskycriper** [UnigramDev/Unigram#1920]
When Unigram automatically switches from light mode to dark mode on schedule, your messages background stays white and but text don't.
 
![photo_2020-07-19 13 40 57](https://user-images.githubusercontent.com/32013287/87872925-84160f80-c9c5-11ea-8d04-9f9d94b5c87a.jpeg) ![photo_2020-07-19 13 40 55](https://user-images.githubusercontent.com/32013287/87872939-b7589e80-c9c5-11ea-9072-a1b535406f5e.jpeg)
_**Light mode** and **Dark mode on schedule**_ 
***
But if i turn dark mode in manually, text is visible and message background is correct.
 
![photo_2020-07-19 13 40 59](https://user-images.githubusercontent.com/32013287/87872990-3d74e500-c9c6-11ea-8ce2-0394952d83fc.jpeg)
_**Manual dark mode**_
***
This is also a problem with shared media file names and every accent color.
 
![photo_2020-07-19 13 40 50](https://user-images.githubusercontent.com/32013287/87873088-0ce17b00-c9c7-11ea-96a7-ea5fe0c68263.jpeg)
**_Shared photos with default accent color in auto dark mode_**

**Comment by FrayxRulez** [comment]
This should be fixed at this point
