### ISSUE TITLE
Weird graphical glitch when the "@"and "#" picker shows up.

### ISSUE THREAD

**Issue by sourajitk** [UnigramDev/Unigram#1921]
There has been this weird graphical glitch when the "@" and "#" picker shows up. This happens even when the picker is empty as shows in the screen grab below.

![image_2020-07-19_19-04-12](https://user-images.githubusercontent.com/45220673/87887558-51374000-c9f4-11ea-8533-7cb9e118d9c6.png)

On a side note, been loving Unigram so far!

**Comment by MarcAnt01** [comment]
Hello, can you attach a screen recording or explain what kind of glitch?

**Comment by sourajitk** [comment]
> Hello, can you attach a screen recording or explain what kind of glitch?

![glitch](https://user-images.githubusercontent.com/45220673/88614341-8cbdb400-d05d-11ea-9471-ff44c51d0eff.png)
![glitch_2](https://user-images.githubusercontent.com/45220673/88614343-8d564a80-d05d-11ea-838a-6cfe5471f60c.png)
I have highlighted the affected areas.

![more](https://user-images.githubusercontent.com/45220673/88614558-fccc3a00-d05d-11ea-9a09-c836e8a26070.png)
The "@" and "#" picker show up even though there's nothing to pick here with the glitch mentioned above.


I hope this makes things a little more clear than before.

**Comment by MarcAnt01** [comment]
Wow, weird glitch, I cannot reproduce it, thanks for clarifying anyway
