### ISSUE TITLE
Deleted media does not get removed from shared media view and crashes app on trying to delete again

### ISSUE THREAD

**Issue by hihain** [UnigramDev/Unigram#1922]
Video example:
1. Delete media in shared media view -> no UI update
2. repeat ->app closes (gray screen until the GIF repeats...)

![ezgif-6-27458bcf3212](https://user-images.githubusercontent.com/1473059/87989332-262b1a00-cae2-11ea-83f3-bc42c6fb835b.gif)

Seach in code for:
`private async void MessagesDelete(Chat chat, IList<Message> messages)`

**Comment by FrayxRulez** [comment]
It doesn't crash anymore
