### ISSUE TITLE
Unigram crashes when trying to search a member inside remove user page

### ISSUE THREAD

**Issue by Marocco2** [UnigramDev/Unigram#1923]
unigram 4.2

Steps to reproduce:

1. Go to a group which you got admin rights
2. Edit group
3. Permissions
4. Blocked users
5. Remove user button
6. Try to search a member

At this point Unigram should crash

**Comment by Marocco2** [comment]
![image](https://user-images.githubusercontent.com/3944248/88035822-fa8c4c00-cb42-11ea-8247-ea13e34bdde4.png)

**Comment by hihain** [comment]
Perhaps it is the same problem while searching on the "Add Admin" page? It crashes there too. Unigram build 5406

**Comment by FrayxRulez** [comment]
Fixed fixed
