### ISSUE TITLE
"Block and delete user from group" action actually regains all revoked permissions

### ISSUE THREAD

**Issue by Marocco2** [UnigramDev/Unigram#1924]
Unigram 4.2

Steps to reproduce:

1. Go to permissions section of a group you have admin rights to
2. Select a user who is limited
3. Press "Block and delete user from group"

What happens is that it regains all permissions 
![image](https://user-images.githubusercontent.com/3944248/88035685-ce70cb00-cb42-11ea-85dc-dc9531bf1e6d.png)

**Comment by FrayxRulez** [comment]
Was the user restricted before the ban?

**Comment by Marocco2** [comment]
> 
> 
> Was the user restricted before the ban?
Yes

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/c591a78924b779c858ce6fb7026fc9f856df8c48
