### ISSUE TITLE
Crashes when GIF is replayed

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#1925]
Apparently when there is a gif in a chat, Unigram crashes as soon as the gif has been played once. 

You see it replay, then everything freezes and Unigram crashes. Had this issue for about a week now, I think.

![image](https://user-images.githubusercontent.com/14281234/88040119-be5bea00-cb48-11ea-892d-841c50396255.png)

**Comment by FrayxRulez** [comment]
I'm not able to reproduce.

**Comment by larsschellhas** [comment]
Apparently, I can't reproduce it anymore, either. :) 
I will close the issue therefore 👍
