### ISSUE TITLE
Fir background does not load, but blue color instead

### ISSUE THREAD

**Issue by hihain** [UnigramDev/Unigram#1927]
![ezgif-6-b246bcd33029](https://user-images.githubusercontent.com/1473059/88093677-a14c0900-cb92-11ea-8672-e3b691f13667.gif)

It is because the URI starts with a 2 digit string that can be interpreted as a hex code. 
In my test all color hex codes have at least 6 digits. So I made a fix I could upload as a pull request. Just let me know.

**Comment by FrayxRulez** [comment]
Duplicate of #1859
