### ISSUE TITLE
Cannot see sent locations properly

### ISSUE THREAD

**Issue by altwarg** [UnigramDev/Unigram#1929]
I received a geolocation mark:
![image](https://user-images.githubusercontent.com/34391398/88197515-45918680-cc4b-11ea-8ad1-99e090728f10.png)

Opened geolocation (button on right side not working):
![image](https://user-images.githubusercontent.com/34391398/88197588-5b9f4700-cc4b-11ea-8bcb-b471416a1966.png)

Actual geolocation mark is here (white number):
![image](https://user-images.githubusercontent.com/34391398/88197756-93a68a00-cc4b-11ea-885c-bf8cb80814a9.png)

**Comment by altwarg** [comment]
Any updates on this issue?

**Comment by MarcAnt01** [comment]
I am sorry, but I didn't manage to reproduce your issue. Have you uninstalled Windows Maps app by chance?

**Comment by altwarg** [comment]
@MarcAnt01, well... no. And also as far as I concerned, it is not possible to uninstall Windows Maps even with PowerShell.
