### ISSUE TITLE
Can't install in my computer

### ISSUE THREAD

**Issue by AkarinServer** [UnigramDev/Unigram#193]
Package failed updates, dependency or conflict validation.(0x80073cf3)

**Comment by ikarago** [comment]
Have your tried installing the dependencies for PC first before you tried to install Unigram?

**Comment by AkarinServer** [comment]
@ikarago How can I install them in my PC?

**Comment by ikarago** [comment]
Please carefully follow the instructions for Desktop here: http://telegra.ph/How-to-install-Unigram-03-10-2

;)

**Comment by AkarinServer** [comment]
@ikarago Thanks, just haven't install the relies.
