### ISSUE TITLE
Unigram is still not fully translated (Russian)

### ISSUE THREAD

**Issue by altwarg** [UnigramDev/Unigram#1930]
![image](https://user-images.githubusercontent.com/34391398/88198303-3d861680-cc4c-11ea-8815-b10edd1c6ae5.png)

![image](https://user-images.githubusercontent.com/34391398/88198561-8047ee80-cc4c-11ea-8c96-1c1b73997972.png)

![image](https://user-images.githubusercontent.com/34391398/88198603-8ccc4700-cc4c-11ea-84d5-875213bb7e94.png)

![image](https://user-images.githubusercontent.com/34391398/88198665-9ce42680-cc4c-11ea-8e7d-1cdd7171d68a.png)

![image](https://user-images.githubusercontent.com/34391398/88198850-d026b580-cc4c-11ea-907c-81afd8d18559.png)

![image](https://user-images.githubusercontent.com/34391398/88198974-f5b3bf00-cc4c-11ea-85c8-9cd30cc63a31.png)

![image](https://user-images.githubusercontent.com/34391398/88198990-fb110980-cc4c-11ea-857f-4e6cbca61683.png)

**Comment by MarcAnt01** [comment]
Hello, Unigram uses the official translations of the Android app. Untranslated options are strings that aren't available in the Android app
