### ISSUE TITLE
Duplicate chats in the list

### ISSUE THREAD

**Issue by ChungZH** [UnigramDev/Unigram#1933]
![image](https://user-images.githubusercontent.com/42088872/88496733-a7a60f00-cff0-11ea-9eea-15f220b1dea3.png)

They are the same channel!

**Comment by MarcAnt01** [comment]
Does that happen in chats list or in a folder? What is your Unigram version?

**Comment by ChungZH** [comment]
I remember it was chats list. It cannot be reproduced now. The version number is 4.2(5263)

**Comment by hihain** [comment]
It seems to be related to having a lot of new incoming messages that were not in the local cache. Like for example 100 new messages in 10 different chats.

If you only get few new messages on opening Unigram, you won't have a problem. Therefore only few users are affected.
If you let Unigram run in the background, it won't affect you either, it seems.

**Comment by ChungZH** [comment]
> It seems to be related to having a lot of new incoming messages that were not in the local cache. Like for example 100 new messages in 10 different chats.
> 
> If you only get few new messages on opening Unigram, you won't have a problem. Therefore only few users are affected.
> If you let Unigram run in the background, it won't affect you either, it seems.

Thanks!

**Comment by FrayxRulez** [comment]
Does this still happen?

**Comment by ChungZH** [comment]
No, Thanks
