### ISSUE TITLE
Increase file upload limit to 2GB

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1934]

**Comment by hihain** [comment]
It is just updating to TDLib 1.6.7...

**Comment by MarcAnt01** [comment]
@hihain does updating TDLib version already adds the features with nothing client-side?

**Comment by hihain** [comment]
Correctly. You could try it in Unigram Mobile (beta). ;)

**Comment by MarcAnt01** [comment]
Great, thanks for letting me know, closing this
