### ISSUE TITLE
Recent actions showing the wrong person performing each action

### ISSUE THREAD

**Issue by Zenexer** [UnigramDev/Unigram#1938]
Recent actions appears to be showing the wrong users—I deleted these messages, not the user listed here.  If user A deletes a message from user B, Unigram shows that user B deleted the message, rather than user A.

Unigram 4.2 (5263)

Apologies if any of the messages in this screenshot are offensive; I don't speak Russian.

![image](https://user-images.githubusercontent.com/504130/88604301-2c227d00-d045-11ea-894a-5740818703c3.png)

**Comment by FrayxRulez** [comment]
This was already fixed in source code, but I didn't manage to release an update to the store before vacations.
