### ISSUE TITLE
Crash on selecting pattern on color for chat background

### ISSUE THREAD

**Issue by yashpalgoyal1304** [UnigramDev/Unigram#1940]
### Reproducing Info

**Steps**
1. Settings > Chat Settings > Chat background
2. Set a color > Pattern
3. Select (click on) a pattern

**Additional Conditions:** I think none

**Reproducible:** Always

### Configuration
**Operating system:** Windows 10
**Version of Unigram:** Unigram 4.0 (5098)
**Installation source** - MS Store
**Used theme**: any

**Comment by yashpalgoyal1304** [comment]
I already had some pattern set before. And i have tried changing that to a photo, quitting uni, and then retrying, but still able to reproduce.

**Comment by MarcAnt01** [comment]
All right, reopening then

**Comment by yashpalgoyal1304** [comment]
@MarcAnt01 what did u delete?

**Comment by MarcAnt01** [comment]
@yashpalgoyal1304 I replied to the wrong ticket

**Comment by FrayxRulez** [comment]
I believe that this has been fixed

**Comment by yashpalgoyal1304** [comment]
@FrayxRulez in which unig version?
