### ISSUE TITLE
add search in web for selected part of message

### ISSUE THREAD

**Issue by behroozbc** [UnigramDev/Unigram#1941]
hi 
please add search on web in this part 
![image](https://user-images.githubusercontent.com/20381616/89119535-5c926d00-d4c4-11ea-9140-733e6091c86a.png)
I want open browser open on link https://www.bing.com/search?q="searched+item"
complete link should be like this "https://www.bing.com/search?q=json+to+typescript+class"
add any one can help me i contribute this

**Comment by makisukurisu** [comment]
@behroozbc Correct issue title. (wen => web)

Also, is it necessary to do this with bing, like Microsoft did?

*Maybe a solution for Google Chrome*
If it is possible to execute program like ' *default_browser.exe* "? search_request_string" '
Then it will make a search using default search engine, just like you typed same text in search bar.

**Comment by behroozbc** [comment]
@makisukurisu 
I don't know! my default search engine is bing and I dont  much link google

**Comment by MarcAnt01** [comment]
Thanks for the feature request, but no official client has this feature
