### ISSUE TITLE
When was Windows 10 Mobile support dropped?

### ISSUE THREAD

**Issue by ahorn42** [UnigramDev/Unigram#1944]
I recently noticed that Unigram seems to had silently dropped the support for Windows 10 Mobile. Can you tell which version breaks the compatibility? Or which one is the last one known to work on Windows 10 Mobile? While reading trough the release notes I couldn't find any hint about it.

By the way I am very sad about this :( and when reading other issues here, I am not the only one still using Unigram with Windows 10 Mobile. May you elaborate why the support for this platform has been broken up? Usually only minor changes are required to keep backwards compatibility alive.

Best regards!

**Comment by MarcAnt01** [comment]
3.13 is the latest version with support for Windows 10 Mobile. It's been dropped since Microsoft has stopped to support it. We advice you to move to iOS/Android or use use Unigram Mobile fork.

**Comment by ahorn42** [comment]
@MarcAnt01 thanks for the answer and thanks for pointing me at https://github.com/hihain/UnigramMobile :)
