### ISSUE TITLE
Videocalls

### ISSUE THREAD

**Issue by koloved** [UnigramDev/Unigram#1947]
Can it appears earlier than in the official desktop app ?

**Comment by FrayxRulez** [comment]
No as I'm currently in vacation until September and they should come to the official app earlier than this.

**Comment by koloved** [comment]
Got it! have a nice vacation!

**Comment by entdark** [comment]
Yeah, picking any possible video source would be nice.

**Comment by FrayxRulez** [comment]
Hi @hibas123, please create a specific ticket for screen sharing.

**Comment by MarcAnt01** [comment]
Videocalls have been added in 7.0 version
