### ISSUE TITLE
Pasted image is compressed right after pasting

### ISSUE THREAD

**Issue by revanmj** [UnigramDev/Unigram#1948]
As title says, right now it seems that image pasted into send field is compressed right after that as cropping it results in a crappy quality.

I have to paste image to Paint, crop it there and copy the result into Unigram to get a decent quality.

I think, that compression should be done just before sending, to avoid such issues when editing an image.

**Comment by hihain** [comment]
I guess it not just about pasting, but in general.

**Comment by MarcAnt01** [comment]
I don't understand the point of this ticket, is the cropped quality bad or the crop preview bad?

**Comment by revanmj** [comment]
> I guess it not just about pasting, but in general.

True, I mainly paste images instead of choosing them from explorer so haven't though about checking it :)

I attached screenshots showing what is the problem (those are images as received by the other side).

Cropped in Paint
![cropped_in_paint](https://user-images.githubusercontent.com/1777618/90319231-773dfa80-df36-11ea-97d2-b0ef2f7c831f.png)
Cropped in Unigram
![cropped_in_unigram](https://user-images.githubusercontent.com/1777618/90319232-77d69100-df36-11ea-86ed-d7b614812d40.png)

**Comment by hihain** [comment]
> I don't understand the point of this ticket, is the cropped quality bad or the crop preview bad?

It seems that the preview before editing is a copy of the original image in a lower resolution, perfect for sending the image with the original cut. So, if you crop the image it seems that the resolutions gets set to an appropriate one regarding the original image dimensions but the cropping is done on the low-res copy. As a result the sent cropped image is an upscaled version of the preview and therefore blurry.

**Comment by revanmj** [comment]
Now, when the edit preview is full screen, you can clearly see that screenshot is compressed right after pasting it (without doing any edits, it is already blurred)

**Comment by revanmj** [comment]
If version 7.1 (5471) was supposed to include this fix, then it doesn't work fully - image is still blurred after cropping it in Unigram as opposed to pasting and sending image cropped in other app.
