### ISSUE TITLE
Closing SendFilesPopup instead of EditMediaPopup: Tablet Mode Back Button or Any Keypress +  Esc

### ISSUE THREAD

**Issue by hihain** [UnigramDev/Unigram#1950]
- Send images
- Click the resize button of one image
- Type on your keyboard (e.g. a letter)
- Press "Esc" key

The SendFilesPopup gets closed. This happened to me sometimes if I want to close it and accidently press a key right before "Esc".
I guess it would be better if the key presses would not go to the description anymore, once the EditMediaPopup is in foreground.

### Tablet Mode
As above, but the bigger problem is using the back key at the bottom from windows. That key closes immediately the _SendFilesPopup_ instead of the _EditMediaPopup_.

**Comment by FrayxRulez** [comment]
This has been fixed at some point
