### ISSUE TITLE
zooming and moving images

### ISSUE THREAD

**Issue by horusra** [UnigramDev/Unigram#1954]
I'm using the latest version on Windows 10, and when I click on an image preview of a link to a jpeg, it opens the image, however if you want to zoom the image you have to use Ctrl+scroll but then you can't move the image to see the other parts. you are stuck on the place you zoomed into
Before zoom:
![image](https://user-images.githubusercontent.com/17074394/90339588-0c51f980-dff2-11ea-8982-d8207b35c1f7.png)
After zoom:
![image](https://user-images.githubusercontent.com/17074394/90339608-255aaa80-dff2-11ea-98e0-242fd68fb7c8.png)
now you can't move to see the rest of the image.
Scrolling without Ctrl after having used Ctrl+Scroll then moves the image only up and down, so you can't see anything left or right of the window, it makes no sense.

I suggest Scroll being for zooming in and out, arrow keys for previous/next image, and right-mouse drag to shift the image around after it's been zoomed in.

**Comment by horusra** [comment]
I should add that it makes little sense that clicking an image only opens it inside the boundaries of Unigram itself, instead of using the full screen. Usually people don't have their chat application in full screen on a desktop, usually it's a small window in one of the corners, so it would make sense to open images in full screen instead with a dark transparent background.

**Comment by MarcAnt01** [comment]
> I should add that it makes little sense that clicking an image only opens it inside the boundaries of Unigram itself, instead of using the full screen. Usually people don't have their chat application in full screen on a desktop, usually it's a small window in one of the corners, so it would make sense to open images in full screen instead with a dark transparent background.

There's already a ticket with this suggestion, thanks

**Comment by MarcAnt01** [comment]
As for the main ticket, it's been reported somehow in https://github.com/UnigramDev/Unigram/issues/1304. Feel free to add any details below that ticket.
