### ISSUE TITLE
tray icon?!?

### ISSUE THREAD

**Issue by horusra** [UnigramDev/Unigram#1955]
I read in an old issue on here that Unigram devs had trouble getting a tray icon to work and that it would eventually get fixed, but is anyone actually working on that? because it's kind of a big issue since everyone is used to chat apps closing to a tray icon instead of disappearing alltogether.

I know someone said that back then microsoft had done something that broke tray icons for UWP apps but I'm using many apps from the microsoft store, for example [EarTrumpet](https://www.microsoft.com/en-us/p/eartrumpet/9nblggh516xp) that has a tray icon and works fine!

Please give us Win10 users a working tray icon!

**Comment by MarcAnt01** [comment]
Hello, no-one is working on that, since the feature won't come back due to major bugs, see https://github.com/UnigramDev/Unigram/issues/1905

**Comment by horusra** [comment]
> Hello, no-one is working on that, since the feature won't come back due to major bugs, see #1905

but why does it introduce bugs in Unigram and not any other UWP app? Can you be specific so we can find a solution?

**Comment by riverar** [comment]
@MarcAnt01 What bugs are you seeing? I'd like to at least get them documented so we can pipe them to Microsoft.

**Comment by MarcAnt01** [comment]
Hello @riverar these are the issues connected with it:
https://github.com/UnigramDev/Unigram/issues/1117
https://github.com/UnigramDev/Unigram/issues/1388
