### ISSUE TITLE
Adding Search Feature to Members tab

### ISSUE THREAD

**Issue by ClassRoomm** [UnigramDev/Unigram#1956]
There is a members section in the group description section in the telegram. Unable to search in Members tab. There is no search box. But there is a search feature in other tabs. Other sections are Media, Files, Links, Audio and Voice Messages.

Please can a search feature be added to the members section?

**Comment by binamracode** [comment]
There is search box to search members too. When you are in members tab click on three dots and click on search members and start to search.

**Comment by MarcAnt01** [comment]
@ClassRoomm 
![image](https://user-images.githubusercontent.com/43090263/90376196-58468200-e076-11ea-9066-4b5a5a21e591.png)
