### ISSUE TITLE
MediaEditPopup: Crash if cropper thumbs are all in one corner and trying to pick and moving one

### ISSUE THREAD

**Issue by hihain** [UnigramDev/Unigram#1958]
- Dragging the thumb from left down to top right results in all thumbs jumping to the top left.
- Having all thumbs in a corner makes it impossible to pick one and resize it correctly. Instead, Unigram crashes.
![image](https://user-images.githubusercontent.com/1473059/90341895-f3524400-e003-11ea-9870-6498bb408246.png)

I guess there should be a minimum size of the rectangle

**Comment by FrayxRulez** [comment]
Doesn't seem to crash anymore
