### ISSUE TITLE
Follow system theme and accent color

### ISSUE THREAD

**Issue by woutervanoorschot** [UnigramDev/Unigram#1959]
As far as I can remember Unigram used to followed the system theme (dark/light mode and accent color).

I can't find the feature anymore, only switching dark mode scheduled by time/location or as a one time setting is listed under Settings->Chat Settings. The accent color is still an option, but it does not update when the Windows accent color changes.

I would like to request the option for Unigram to follow the system theme (dark/light), and the system accent color (the accent color is an option when selecting a color, but it does not update when the windows accent color updates).

Thanks for the amazing app, it makes using telegram on windows a very enjoyable experience.

**Comment by livejamie** [comment]
Would really appreciate this as well.

**Comment by pan-theis** [comment]
As somebody who switches between light and dark mode constantly, this is a must. Nowadays a modern application cannot lack this feature.

**Comment by FrayxRulez** [comment]
I recently reworked the themes code, and this should now be possible.
The app now remembers the last used light and dark theme, so that they can be switched back and forward.

Also, 7.1 beta offers a button in the hamburger menu to switch between them at any time:
![animation](https://media.giphy.com/media/jiTJVGQaphb9hDRQls/giphy.gif)

**Comment by FrayxRulez** [comment]
Dooone

**Comment by pan-theis** [comment]
Will Unigram adhere to the global theme now?

**Comment by AdamWrighter** [comment]
Having a button to switch between light/dark doesn't solve this issue. Unigram should have an option to follow Windows' dark mode setting. I have [Auto Dark Mode](https://github.com/Armin2208/Windows-Auto-Night-Mode) set up to switch everything to dark mode at 5pm, when I finish work. Virtually everything follow this - Discord, most websites either natively or with Dark Reader, all modern surfaces in Windows.

But not Unigram, and this isn't right. Unigram needs an option to follow system dark mode setting.

**Comment by alighamari** [comment]
@AdamWrighter 
![image](https://user-images.githubusercontent.com/24440862/124797169-380e0300-df67-11eb-8e7b-131bf7705a21.png)
enable this

**Comment by AdamWrighter** [comment]
> @AdamWrighter
> ![image](https://user-images.githubusercontent.com/24440862/124797169-380e0300-df67-11eb-8e7b-131bf7705a21.png)
> enable this

Oh, this _disappears_ if you already have a dark mode turned on. So I didn't see it. Strange behaviour. But thank you for pointing that out!
