### ISSUE TITLE
Auto Night Mode: Some UI parts stay white

### ISSUE THREAD

**Issue by hihain** [UnigramDev/Unigram#1960]
Stays after closing Unigram and starting it again. Here some impressions:
![image](https://user-images.githubusercontent.com/1473059/90448906-9da29800-e0e6-11ea-804c-7cc86ca98a66.png)
![image](https://user-images.githubusercontent.com/1473059/90448938-ab581d80-e0e6-11ea-83ab-8b7fada50fe1.png)

**Comment by FrayxRulez** [comment]
I can't see a selected theme in the screenshot? It looks like you're using a custom theme.

**Comment by hihain** [comment]
Interesting, you are right!

So the bug is that for custom theme it does not apply correctly. Clicking all options it seems to stay in auto night mode for every option but dark (expected that) and only the custom theme has the above mentioned problem.
![image](https://user-images.githubusercontent.com/1473059/92335113-37c98080-f094-11ea-99b2-294c549f3250.png)

I deleted all custom themes
![image](https://user-images.githubusercontent.com/1473059/92335148-9d1d7180-f094-11ea-8f7c-7e0244742f32.png)
and created a new one without changing anything. Then it works.
Changing the color of PageHeaderBackground to white results in the above behaviour again.
![image](https://user-images.githubusercontent.com/1473059/92335171-f2f21980-f094-11ea-9afa-3ad895132fbe.png)
If I disable Auto Night Mode everything goes to white, like expected.

So I guess the PageHeaderBackgroundBrush does not get replaced for custom themes if Auto Night Mode is on, for some reason.

Sorry for repeating me. I should sleep.^^

**Comment by FrayxRulez** [comment]
This should be fixed
