### ISSUE TITLE
"Automatic" text response to calls

### ISSUE THREAD

**Issue by hihain** [UnigramDev/Unigram#1964]
The Android App has the option in "Settings-> Data and STorage" for Calls to answer with a message.

I like the idea as many times I get the call on Windows and would like to say that I call back with just one click and not refusing the call and typing it all by myself after that.

In the Android app you can set different possible answers.

**Comment by FrayxRulez** [comment]
This is a very mobile specific option

**Comment by hihain** [comment]
For me it just saves time. I do not have a software installed the replaces some strings automatically, so I do not have to type so much. I am slow in typing. With that Telegram Desktop would have it. Or that I could disable receiving calls on specific clients only...

**Comment by MarcAnt01** [comment]
Closing this, since as Fela stated this is a mobile-oriented feature
