### ISSUE TITLE
Unigram Mobile Messenger for W10M AU 14393.x

### ISSUE THREAD

**Issue by pompili** [UnigramDev/Unigram#1968]
Please, release a version for Windows 10 Mobile Anniversary Update build 14393.x
Thanks

**Comment by hihain** [comment]
I guess you should post this in the project of the mobile fork [UnigramMobile](https://github.com/hihain/UnigramMobile) as Unigram has dropped support for mobile last year. There exists already an [RS1](https://github.com/hihain/UnigramMobile/tree/RS1) branch, but it is not finished yet.

**Comment by MarcAnt01** [comment]
I confirm what @hihain said. We don't support Windows 10 Mobile
