### ISSUE TITLE
Unigram crashes on startup after 2004 update (Windows N)

### ISSUE THREAD

**Issue by destiny14** [UnigramDev/Unigram#1971]
Hello!

My Unigram crashes after updating Windows to Version 2004. It just closes after displaying the splash screen. I have tried reinstalling it and replacing it with the current beta version, to no avail. I'm not quite sure about the connection to the Windows update since it runs fine on my other PC (which although was installed with 2004).

I've attached a related crash dump file. I couldn't get much info out of it, I hope it does help you more :)

[Unigram.exe.20216.dmp.zip](https://github.com/UnigramDev/Unigram/files/5181691/Unigram.exe.20216.dmp.zip)

**Comment by destiny14** [comment]
Okay this behavior occurs when the Media Feature Pack is missing on a Windows N edition.

**Comment by FrayxRulez** [comment]
We have a ticket already about Windows N...
