### ISSUE TITLE
does not install on windows server 2019

### ISSUE THREAD

**Issue by sdsdjr** [UnigramDev/Unigram#1972]
Hi ,
when I try to install it on "windows server 2019",  I faced this problem:

PS D:\> Add-AppxPackage -Path "D:\Users\  ...  \Downloads\Unigram_7.0.5286.0_x64.appxbundle"
Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF3, Package failed updates, dependency
or conflict validation.
Windows cannot install package 38833FF26BA1D.UnigramPreview_7.0.5286.0_x64__g9c9v27vpyspw
because this package depends on a framework that could not be found. Provide the framework
"Microsoft.UI.Xaml.2.4" published by "CN=Microsoft Corporation, O=Microsoft Corporation,
L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version
2.42005.18002.0, along with this package to install. The frameworks with name
"Microsoft.UI.Xaml.2.4" currently installed are: {}
NOTE: For additional information, look for [ActivityId] ceecd6e8-84cb-0001-b6d7-edcecb84d601 in
the Event Log or use the command line Get-AppPackageLog -ActivityID
ceecd6e8-84cb-0001-b6d7-edcecb84d601
At line:1 char:1
+ Add-AppxPackage -Path "D:\Users\  ... \Downloads\Unigram_7.0.5286.0_x6 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (D:\Users\ ... \..._x64.appxbundle:String) [Add-AppxPa
   ckage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.Add
   AppxPackageCommand

Best Regards

**Comment by MarcAnt01** [comment]
Hi, try to install this version https://t.me/unigraminsiders/293789

**Comment by MarcAnt01** [comment]
Install this .appx file https://www.dropbox.com/s/tvspay4cjokvl76/Microsoft.UI.Xaml.2.4.appx?dl=1
