### ISSUE TITLE
Screen sharing for video calls

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1973]

**Comment by FrayxRulez** [comment]
👯

**Comment by revanmj** [comment]
Is it implemented? Because I recently wanted to share screen in 1-on-1 call and didn't see option for it anywhere.

**Comment by FrayxRulez** [comment]
> Is it implemented? Because I recently wanted to share screen in 1-on-1 call and didn't see option for it anywhere.

This is only available in group calls currently

**Comment by SuperJMN** [comment]
Whoops. I had to install the official application due to this missing feature.

**Comment by AsrorbekDev** [comment]
@NotesOfReality mmh

**Comment by SuperJMN** [comment]
Is this going to be implemented?

**Comment by FrayxRulez** [comment]
@SuperJMN Yes
