### ISSUE TITLE
update to new version on windows server 2019

### ISSUE THREAD

**Issue by sdsdjr** [UnigramDev/Unigram#1977]
Hi,
I have install the previous version with the help of  Fela Ameghino who let me have link to Unigram_7.0.5286.0_Test.
when run install.ps1, the app installed smoothly.
now I want to update it to the Unigram_7.0.5296.0 but there is still dependency error:

**PS D:\> Add-AppxPackage -Path "Unigram_7.0.5296.0_x64.appxbundle"**

Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF3, Package failed updates, dependency
or conflict validation.
Windows cannot install package 38833FF26BA1D.UnigramPreview_7.0.5296.0_x64__g9c9v27vpyspw
because this package depends on a framework that could not be found. Provide the framework
"Microsoft.UI.Xaml.2.4" published by "CN=Microsoft Corporation, O=Microsoft Corporation,
L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version
2.42007.9001.0, along with this package to install. The frameworks with name
"Microsoft.UI.Xaml.2.4" currently installed are: {Microsoft.UI.Xaml.2.
Windows cannot install package 38833FF26BA1D.UnigramPreview_7.0.5296.0_x64__g9c9v27vpyspw
because this package depends on a framework that could not be found. Provide the framework
"Microsoft.UI.Xaml.2.4" published by "CN=Microsoft Corporation, O=Microsoft Corporation,
L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version
2.42007.9001.0, along with this package to install. The frameworks with name
"Microsoft.UI.Xaml.2.4" currently installed are:
{Microsoft.UI.Xaml.2.4_2.42005.18002.0_x86__8wekyb3d8bbwe
Microsoft.UI.Xaml.2.4_2.42005.18002.0_x64__8wekyb3d8bbwe}
NOTE: For additional information, look for [ActivityId] 620f6f4d-865b-0002-7b19-10625b86d601 in
the Event Log or use the command line Get-AppPackageLog -ActivityID
620f6f4d-865b-0002-7b19-10625b86d601
At line:1 char:1
+ Add-AppxPackage -Path "Unigram_7.0.5296.0_x64.appxbundle"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (D:\Unigram_7.0...._x64.appxbundle:String) [Add-AppxPa
   ckage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.Add
   AppxPackageCommand

Best regards

**Comment by FrayxRulez** [comment]
You can install this package: https://t.me/unigramappx/36
