### ISSUE TITLE
When (video)calling someone with Unigram it rings sounds also during connection (exchanging keys)

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1978]

**Comment by FrayxRulez** [comment]
@MarcAnt01 What sound should it make?

**Comment by MarcAnt01** [comment]
@FrayxRulez Tu ru tu tu

**Comment by MarcAnt01** [comment]
The iOS app plays a specific sound

**Comment by FrayxRulez** [comment]
This should be fixed in version 7.0 (5300) by commit https://github.com/UnigramDev/Unigram/commit/b08db31e2ab9fbb092d2c24b42552b7d0f3a1b7e, let me know if it's the case

**Comment by MarcAnt01** [comment]
Yes, it's all right now
