### ISSUE TITLE
When receiving a video call, the buttons overlap

### ISSUE THREAD

**Issue by jvlianodorneles** [UnigramDev/Unigram#1979]
### Steps to reproduce
1. To receive video call.

### Expected behaviour
To show action buttons.

### Actual behaviour
When receiving a video call, the buttons overlap.

### Configuration
**Operating system:** Windows 10 Home compilation 19041.264.

**Version of Unigram:** 7.0 (5299).

**Used theme**: Default.

![Incoming video call](https://i.imgur.com/axKMrfn.jpg)

**Comment by FrayxRulez** [comment]
This should be fixed in version 7.0 (5300) by commit https://github.com/UnigramDev/Unigram/commit/b08db31e2ab9fbb092d2c24b42552b7d0f3a1b7e, let me know if it's the case

**Comment by jvlianodorneles** [comment]
Solved. Thanks!
