### ISSUE TITLE
When leaving Call Settings panel, the device settings aren't being saved.

### ISSUE THREAD

**Issue by jvlianodorneles** [UnigramDev/Unigram#1980]
### Steps to reproduce
1. Open Call Settings panel.

### Expected behaviour
To keep speakers an headphones output device and camera input device settings saved.

### Actual behaviour
When leaving Call Settings panel, the device settings aren't being saved. Consequently, they are not loaded on the video call screen.

### Configuration
**Operating system:** Windows 10 Home compilation 19041.264.

**Version of Unigram:** 7.0 (5299).

**Used theme**: Default.

![Call Settings](https://i.imgur.com/k8kj6Gl.png)

**Comment by FrayxRulez** [comment]
This should be fixed in version 7.0 (5300) by commit https://github.com/UnigramDev/Unigram/commit/b08db31e2ab9fbb092d2c24b42552b7d0f3a1b7e, let me know if it's the case

**Comment by jvlianodorneles** [comment]
Solved. Thanks!
