### ISSUE TITLE
When caller cancels a call before being answered, a RETURN TO CALL button is shown at the top of the chat list

### ISSUE THREAD

**Issue by jvlianodorneles** [UnigramDev/Unigram#1981]
### Steps to reproduce
1. Receive a call.
2. Caller cancels the call before it is answered.

### Expected behaviour
Cancel the entire call receiving process.

### Actual behaviour
When the caller cancels a call (before being answered), a RETURN TO CALL button is shown at the top of the chat list, but it doesn't take any action. In addition, the camera remains on until the application is closed.

### Configuration
**Operating system:** Windows 10 Home compilation 19041.264.

**Version of Unigram:** 7.0 (5299).

**Used theme**: Default.

![RETURN TO CALL](https://i.imgur.com/3MNsSps.png)

**Comment by FrayxRulez** [comment]
This should be fixed in version 7.0 (5300) by commit https://github.com/UnigramDev/Unigram/commit/b08db31e2ab9fbb092d2c24b42552b7d0f3a1b7e, let me know if it's the case

**Comment by jvlianodorneles** [comment]
Solved. Thanks!
