### ISSUE TITLE
Need video disable icon

### ISSUE THREAD

**Issue by jvlianodorneles** [UnigramDev/Unigram#1982]
Regarding the buttons in call screen: they need to be better suited according to their status. For example, the microphone button changes to a highlighted color when it is muted and is always crossed out. Same thing with the camera button, but this is never crossed out.

My suggestion: highlighted color when activated and alternate the crossed out or not icon according to the status of the device.

**Comment by MarcAnt01** [comment]
The problem is the lack of an icon asset with crossed video
![image](https://user-images.githubusercontent.com/43090263/92990727-f47d7080-f4de-11ea-98f9-8824c9f13bf6.png)

**Comment by jvlianodorneles** [comment]
Same on microphone icon. When enabled, change the icon to a version without the "strike".

**Comment by jvlianodorneles** [comment]
Solved! ;)
