### ISSUE TITLE
(video)calls page need a colored titlebar

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#1989]

**Comment by FrayxRulez** [comment]
It got it right?

**Comment by MarcAnt01** [comment]
Not with dark blue theme
![image](https://user-images.githubusercontent.com/43090263/93709317-d0084080-fb3d-11ea-844a-9d46f0e319c2.png)

**Comment by FrayxRulez** [comment]
Looks fine to me

**Comment by MarcAnt01** [comment]
No, it should be the same as main window
![image](https://user-images.githubusercontent.com/43090263/93709934-dea52680-fb42-11ea-983b-cad9e7bb3fbc.png)

**Comment by MarcAnt01** [comment]
Done
