### ISSUE TITLE
"Message" placeholder superimposed on the Show formatting bar when recording a voice message

### ISSUE THREAD

**Issue by jvlianodorneles** [UnigramDev/Unigram#1999]
### Steps to reproduce
1. Start to record a voice message, with **Show formatting** bar active.

### Expected behaviour
Hide "Message" placeholder when recording a voice message.

### Actual behaviour
The "Message" placeholder is superimposed on the **Show formatting** bar.

### Configuration
**Operating system:** Windows 10 Home compilation 19041.264.

**Version of Unigram:** 7.0 (5309).

**Used theme**: Default.

![Message](https://i.imgur.com/Hrx4Lfq.png)

**Comment by FrayxRulez** [comment]
Duplicate of ##1840
