### ISSUE TITLE
Unigram force close when you click the disable camera button in the videocall window.

### ISSUE THREAD

**Issue by jvlianodorneles** [UnigramDev/Unigram#2001]
### Steps to reproduce
1. Start a video call.

### Expected behaviour
Disable the camera when you click the respective button in the videocall window.

### Actual behaviour
Unigram force close when you click the button to disable the camera in the videocall window.

### Configuration
**Operating system:** Windows 10 Home compilation 19041.264.

**Version of Unigram:** 7.0 (5312).

**Comment by MarcAnt01** [comment]
I cannot reproduce this issue

**Comment by jvlianodorneles** [comment]
It crashes when we press the End Call button too (but only in videocalls).

**Comment by FrayxRulez** [comment]
Still?

**Comment by jvlianodorneles** [comment]
Solved!
