### ISSUE TITLE
Nothing shows when typing name in the Send to... field

### ISSUE THREAD

**Issue by pibn** [UnigramDev/Unigram#2002]
ver: 7.0 (5312)

**Comment by MarcAnt01** [comment]
I cannot reproduce the crash, but it's non functional here

**Comment by pibn** [comment]
it's fixed in (5417)

**Comment by MarcAnt01** [comment]
Still no results for me, dunno if it's server-side tho

**Comment by pibn** [comment]
Another problem in forward menu
search didn't work
https://1drv.ms/u/s!AgkjVAf3XEBXmHVuWu_iHOfF-sQL?e=HdsEVd

**Comment by MarcAnt01** [comment]
Yeah, that's why I am keeping it open
