### ISSUE TITLE
Encrypt data stored by app

### ISSUE THREAD

**Issue by mehulagg** [UnigramDev/Unigram#2011]
Can you please implement data encryption like AES in unigram so that data can only be viewed in app and not viewable in file explorer ? If this type of encryption is possible with UWP and telegram.

**Comment by FrayxRulez** [comment]
Hi, Unigram database is encrypted, so users can't read your messages in cloud and secret chats.
Files however can't be encrypted, this would be too heavy for the app and system to access them.
