### ISSUE TITLE
New send media ui doesn't adapt to touch keyboard

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2016]
![image](https://user-images.githubusercontent.com/43090263/93586767-16786680-f9a9-11ea-8acc-4f524c8d4e9b.png)

**Comment by MarcAnt01** [comment]
![image](https://user-images.githubusercontent.com/43090263/115954164-c2f66a00-a4ef-11eb-926d-59ffb55d1045.png)
I am opening it again, sine I have noticed that it's aligned to the chat textbox instead of the popup one

**Comment by FrayxRulez** [comment]
No, that's absolutely correct

**Comment by MarcAnt01** [comment]
> No, that's absolutely correct

I have to close the keyboard to send a file, I don't think that's "absolutely correct"

**Comment by MarcAnt01** [comment]
Comparing with the screenshot in the initial discussion, it looks like the popup is just appearing a bit higher, could you consider it to raise the popup so that the buttons under the textbox are visible?
