### ISSUE TITLE
Unigram called party alignment on Xbox 

### ISSUE THREAD

**Issue by unigram1975** [UnigramDev/Unigram#2020]
After latest update on Xbox few days back when calling voice or video called party name plus status appears small in corner of screen

**Comment by MarcAnt01** [comment]
Can you attach a screenshot of the behaviour?

**Comment by unigram1975** [comment]
![1fa9a703-c4bb-4353-94ce-48c92b124a09](https://user-images.githubusercontent.com/71658622/93852892-880f2800-fcbb-11ea-836e-b103517c9cd7.JPG)

![dc81bd93-6fa5-4190-8250-b45950ac9991](https://user-images.githubusercontent.com/71658622/93852922-978e7100-fcbb-11ea-8697-88836af06674.JPG)

Also B-party doesnt hear the voice of the person calling from Xbox

**Comment by MarcAnt01** [comment]
Thanks for reporting, it looks like the whole calls have some specific problems from Xbox

**Comment by MarcAnt01** [comment]
@unigram1975 can you provide us some feedback? Does that still happen

**Comment by unigram1975** [comment]
> @unigram1975 can you provide us some feedback? Does that still happen

Yes the issue still the same since reporting it.

**Comment by FrayxRulez** [comment]
Hello! Could you reach me on Telegram? My username is the same as here.

**Comment by MarcAnt01** [comment]
Hi, this issue should be fixed, if you're still having issues, just comment down below and it'll be reopened
