### ISSUE TITLE
Unigram cannot connect to voice call (microphone access issue)  

### ISSUE THREAD

**Issue by ghost** [UnigramDev/Unigram#2026]
I cannot call a contact by voice call. Unigram hangs in "connecting" phase.

If contact call me then Unigram asks access to microphone and voice call work normally. Moreover after grant of access to microphone I can call the contact successfully. I think Unigram has bug. The application don't ask rights to microphone in out calls. Only for incoming calls.

**Comment by FrayxRulez** [comment]
Connecting isn't related to microphone access

**Comment by FrayxRulez** [comment]
Closing this as there was no updates for a long time and I'm pretty sure that this is fixed.

**Comment by MarcAnt01** [comment]
Yep, I can confirm calls have been working flawlessly for few months
