### ISSUE TITLE
Unigram closes on windows 10

### ISSUE THREAD

**Issue by AlexandrKozlovskiy** [UnigramDev/Unigram#2027]
When i runn unigram in windows 10 64 bytes,it's closes after several seconds. Reinstalling of the app from microsoft store not fix this problem. also there is no error messages at this time. Several hours ago all was ok. Thanks.

**Comment by FrayxRulez** [comment]
Which version of Windows 10 are you using?

**Comment by AlexandrKozlovskiy** [comment]
Very old. 😁,because i can't update my system. I use version 1803,but before unigram worked ok,but now not works.

**Comment by FrayxRulez** [comment]
Ok, today I will install 1803 and I'll try to fix it

**Comment by AlexandrKozlovskiy** [comment]
But may be it's only my issue. Can i find log file of crash of unigram to send to you?

**Comment by FrayxRulez** [comment]
The issue is fixed and a update should be already available in the Store 😉

**Comment by AlexandrKozlovskiy** [comment]
Thank you very much. Now it works ok. It's very interesting for me,why it crashed on old versions of system again. Thank you very much again.

**Comment by AlexandrKozlovskiy** [comment]
After update today it seems,what unigram become close again in windows 10 64 bytes 1803.

**Comment by FrayxRulez** [comment]
Hi, sorry, I'll investigate and fix ASAP. 
If you want you can ping me on Telegram (same username) and I will provide you a older version that doesn't crash.

**Comment by AlexandrKozlovskiy** [comment]
Ok,i will wait fix and update from you. It very interesting for me,why it's crash on old system?

**Comment by FrayxRulez** [comment]
This is fixed, you should receive a update tomorrow.
> Why it's crash on old system?
Windows 10 updates are kind of fragmented, every of them brings in some new API and some changes to the architecture of the framework itself.

**Comment by AlexandrKozlovskiy** [comment]
I get update today,but it still crash.

**Comment by AlexandrKozlovskiy** [comment]
Ok,if you can't fix or dont want to fix this issue,please send me old unigram on telegram with user name sashablr_1994. Thanks.

**Comment by FrayxRulez** [comment]
Which version of the app are you using?

**Comment by AlexandrKozlovskiy** [comment]
7.1.5426.0

**Comment by edn4ka** [comment]
i have windows 1803 and unigram 7.1.5410.0 but unigram doesn't working but yesterday morning he is working
