### ISSUE TITLE
Opening Photos/Videos won't work.

### ISSUE THREAD

**Issue by wobbleninja** [UnigramDev/Unigram#2028]
So this started today and I'm not sure if it's a bug or something's wrong with my PC but I did no changes to my PC (an update for example) or Unigram when this occurred.

Clicking on photos or videos from channels or chats they won't open so you can watch them. There's an animation like they open and they move to the top left corner and they disappear. There is sound on videos but no image at all.

I have the MS Store version and I checked if there's an update hopefully to fix this and since it was one I updated hoping but the issue still exists.

**Comment by FrayxRulez** [comment]
Hi, few questions:
- What's the exact Windows 10 version that you're using?
- Do you have multiple monitors connected to your PC?

**Comment by wobbleninja** [comment]
@FrayxRulez 

- I'm using the latest version 2004. OS Build 19041.508 if that matters.
- I don't use multiple monitors. I only have one monitor.

Yesterday everything was fine. I just shut down my PC and went to sleep until I opened it today to come up to this problem.

**Comment by FrayxRulez** [comment]
If you close and reopen the app the issue persists? Would you bother to reach me on Telegram? Same username as here.

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/f04b315423f5106558e0f88fb79e1f05c995ccf3
