### ISSUE TITLE
Allow switching back to opening images inside window boundaries

### ISSUE THREAD

**Issue by redesigndev** [UnigramDev/Unigram#2029]
The new update has changed the behavior of viewing images. Clicking on an image or video opens the content across the entire display. This makes it difficult when you're cross referencing the image with another application, cause all input is absorbed and Unigram occupies the entire screen. 

An option to switch back to the previous method of viewing images (displaying within window boundaries) should be added, for those trying to multitask on a single screen.

**Comment by FrayxRulez** [comment]
Would be a option in Appearance/Chat Settings good for you?

**Comment by redesigndev** [comment]
> Would a option in Appearance/Chat Settings be good for you?

Yes, that sounds perfect.

**Comment by riccardik** [comment]
> Would a option in Appearance/Chat Settings be good for you?

to me also would be a perfect option, i searched for it right in that place when i noticed the change :)

**Comment by FrayxRulez** [comment]
The option was added in Settings > Chat Settings!
