### ISSUE TITLE
Unigram cannot download photo and video in secret chats after hibernation/sleep

### ISSUE THREAD

**Issue by ghost** [UnigramDev/Unigram#2031]
And again critical bug. Unigram cannot download video and photo in secret chat from Telegram server. I click on thumbnail, but nothing to do. "X" mark changed to "arrow down", but Unigram cannot download media file.

However old photos in secret chats works normally.

I fixed this problem by restarting of Unigram. I think problem relating with hibernation in my laptop.  Unigram has wrong state after  it.

**Comment by FrayxRulez** [comment]
Could you send logs? You can find how to in the wiki.

**Comment by delmoster** [comment]
I don't see this problem again.
