### ISSUE TITLE
Copy operation don't work with images

### ISSUE THREAD

**Issue by ghost** [UnigramDev/Unigram#2035]
I you choose "copy" for image in messages list then nothing to copy.

**Comment by FrayxRulez** [comment]
I don't understand

**Comment by delmoster** [comment]
Repro steps
1. Open messages list
2. Point to image (don't left click on it)
3. Right click. Pop-up menu
4. Copy 

 Nothing to copy at step 4

However if you open image (left click) then copy operation will work

**Comment by FrayxRulez** [comment]
Are you clicking on "Copy" or "Copy image"? In a secret or normal chat?

**Comment by delmoster** [comment]
> Are you clicking on "Copy" or "Copy image"? In a secret or normal chat?

Copy, but on image

**Comment by zakharnurik** [comment]
@delmoster "Copy image" on message, "Copy" on image
