### ISSUE TITLE
Chat section's width is limited

### ISSUE THREAD

**Issue by sampadsams** [UnigramDev/Unigram#2036]
The screenshot is self-explanatory. 

![image](https://user-images.githubusercontent.com/71980466/94370005-00317f80-00fa-11eb-96e9-7ebd12c4e140.png)

**Comment by sukram230799** [comment]
That looks like the "Adaptive Layout for Wide Screens" option in the "Advanced" settings.

**Comment by sampadsams** [comment]
Yeah, it was on. and when I turned it off, it's at full width. 
**But shouldn't it be vice versa?! Because it says "adaptive layout", and it adapted to window size when it's off !!!**

**Comment by sukram230799** [comment]
Well the naming might not be ideal, but the reasoning behind it is, that you don't have to bounce with your eyes from left to right on a wide monitor while reading messages. If you don't have any further questions this issue can be closed.
