### ISSUE TITLE
Add Emojis to Stickers in Flyout/Panel

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#204]
Would be good to know, with which emoji the stickers are connected

**Comment by FrayxRulez** [comment]
Implemented emojis panel in https://github.com/UnigramDev/Unigram/commit/a0560413a837fbf7b800dbe6e034b8e634e349d0

**Comment by larsschellhas** [comment]
I think, that was not the meaning of this issue 🤔 
Also it seems that this is one of the features missing with Unigram X, so I would like to reopen this issue :)

**Comment by MarcAnt01** [comment]
@larsschellhas that feature is working now

**Comment by larsschellhas** [comment]
it isn´t @MarcAnt01.
Stickers have specific emojis associated with them and when you open the sticker panel you don´t see with which emojis a sticker is associated.

**Comment by MarcAnt01** [comment]
![image](https://user-images.githubusercontent.com/43090263/46245670-e9b09a80-c3f1-11e8-815c-0d69e3589ab2.png)

**Comment by MarcAnt01** [comment]
If you mean that emoji aren't connected to stickers, that would require sticker preview, that is unsupported so far

**Comment by larsschellhas** [comment]
There is a difference between 
1) suggested stickers based on a written emoji and
2) emojis shown beside the stickers in the sticker panel.

And of course it is unsupported so far, because otherwise I wouldn´t need to open this ticket. Thank you :)

**Comment by FrayxRulez** [comment]
None of the official apps actually show emojis in the stickers panel btw

**Comment by FrayxRulez** [comment]
We have this in the stickers dialog, the one you get when you click on a sent/received sticker

**Comment by MarcAnt01** [comment]
@larsschellhas I think you are confusing with Telegram desktop

**Comment by larsschellhas** [comment]
oh yes… Okay, I would like this to be in the sticker panel, too. But I´ll leave it to you, to close this issue, if you wouldn´t add it there.

**Comment by FrayxRulez** [comment]
I can add this to the full screen sticker preview, even if broken

**Comment by larsschellhas** [comment]
@FrayxRulez That would be nice. Would even give the sticker preview some sense right now 😂

**Comment by MarcAnt01** [comment]
@FrayxRulez How would it work with mouse/touchpad?

**Comment by FrayxRulez** [comment]
Right click

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/6b594dc641e2966d8ab886d1c36d044432d192a2
