### ISSUE TITLE
Camera switching is broken

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2043]
If I want to switch to the back camera of my Surface Book 2 it won't display anything

**Comment by danlkv** [comment]
Have similar issue on Surface book 3. *Only* back camera is working and I can't switch to front camera

**Comment by FrayxRulez** [comment]
It's pretty hard for me to look into this as I have a single camera... 🙃

**Comment by danlkv** [comment]
Well, that's fair:) Maybe I can run some logs for you or something?

**Comment by MarcAnt01** [comment]
> Have similar issue on Surface book 3. _Only_ back camera is working and I can't switch to front camera

In my Surface Book 2 it's the other way round lol

**Comment by danlkv** [comment]
Awesome!🎉

**Comment by danlkv** [comment]
@FrayxRulez I just updated Unigram 7.8, and camera switch still works strange. The other person sees the correct camera output, while the preview on my side shows a frozen image from other camera.
