### ISSUE TITLE
Increase the capacity of stickers' favorites from 5 to 20

### ISSUE THREAD

**Issue by sampadsams** [UnigramDev/Unigram#2047]
There are stickers that I plot to use in special moments, called favorite stickers, unlike _recently used_ which is for common conversations. Most of the time it's a matter of speed. So there's an essential need for favorite stickers at the nearest spot. And I must say, **5 is just not enough.**

And if it's possible, a setting option in _stickers and masks section_ for favorites and recent stickers' count would be great.

**Comment by MarcAnt01** [comment]
I agree that 5 is not enough, but unfortunately this is a limitation of Telegram servers. You should contact Telegram via Twitter and ask them to increase it.
