### ISSUE TITLE
Potential security leak - Folder with media cache. We need some improvements (more shorter time to cleanup cache)

### ISSUE THREAD

**Issue by ghost** [UnigramDev/Unigram#2049]
VERY dangerous security leak is folder with media cache. This content is not protected by any way. Everyone can access to files (in security chats too). The problem is more dangerous because Windows will use thumbnails and indexing database for this files. Surprise for many users is access to very secret files in Windows Search. 

I'm using Bitlocker encryption for entire disk. Also I'm using O&O Windows Shutup 10 utility for disable Windows indexing. However it's problem even for me. Applications are running under my rights can access to Unigram folder with secret files. Some viruses will find any photos in file system and copy it to remote servers. Most of users don't use Bitlocker and special security unities. Therefore Unirgram is dangerous for users as potential leak of media files.

I understand that it's hard to rewrite cache code for encrypted storage. We need to minimize this problem. Unigram has setting for autodelete media files from cache. We need this setting as short as possible. At least 1 hour for delete files from cache. May be 5 minutes. Now Unigram allow 3 days for cleanup cache. It' not enough. 

May be we need option to automatic deletion media files if autolock timer enabled.

Of cause Telegram for Android is using same architecture. However Android devices have encrypted file system and this is personal device without access multiple people to it. Bitlocker is feature of expensive Windows Professional version. Typically multiple people have access to single Windows machine.
  
PS. I see also very bad security rights for cache folder. Indexing is allowed. Also ALL administrators of the machine can access to cache folder. In other words. Your family members with account on sharing computer can search and open yours secret files from theirs accounts.

**Comment by FrayxRulez** [comment]
This is by design ands it isn't going to change any time soon.
