### ISSUE TITLE
Wallpaper is reset when switching from dark to light, and back

### ISSUE THREAD

**Issue by githubcatw** [UnigramDev/Unigram#2051]
So, when I start Unigram, I have the background I set:
![image](https://user-images.githubusercontent.com/17374742/94663365-9f34c200-031a-11eb-8ca1-fc7d5d76d8ee.png)
Then, when I click the hamburger menu dark/light button to switch to light theme, and again to switch back to dark, the wallpaper is reset:
![image](https://user-images.githubusercontent.com/17374742/94663456-becbea80-031a-11eb-8b29-a3976fab594a.png)
But, in the chat settings, the background is still there:
![image](https://user-images.githubusercontent.com/17374742/94663566-da36f580-031a-11eb-889e-c38860cfde8e.png)
The issue is fixed after I relaunch Unigram.

Unigram 7.1 (5388), Windows 10 2004.

**Comment by FrayxRulez** [comment]
This was fixed in a recent beta
