### ISSUE TITLE
Missing export chat feature (and related critical security issue) 

### ISSUE THREAD

**Issue by delmoster** [UnigramDev/Unigram#2058]
Unigram has big disadvantage in compare to standard Telegram desktop client. Missing standard export chat feature.

We can understand that this big security problem too. Main "export chat" feature use case is security related. You can export chat (and protect by any encrypted  archive). After it you can clear chat history without loss important information. Your dialog partner cannot access to old messages for any confidential info and he cannot use it against you in the future. At least he cannot prove that this messages really exists.

Unigram don't have export feature. It force users to store all message history. Also Unigram has security backdoor  though cache folder. If you cannot delete messages without losing info then yours cache folder will have more confidential information against you.  

PS. I described Unigram cache folder security leak in previous report.   Anyone who can logged to yours PC or remove yours HDD can access to yours private photos and etc. Be careful with usage of Unigram. It's dangerous in current version.

**Comment by FrayxRulez** [comment]
Unigram will not have export chat feature, as it is designed to be used from Telegram Desktop only.

**Comment by delmoster** [comment]
> Unigram will not have export chat feature, as it is designed to be used from Telegram Desktop only.

It's not true. Unigram can read messages and media in chats. So no problems for implementation export feature without additional API calls.

**Comment by FrayxRulez** [comment]
> It's not true. Unigram can read messages and media in chats. So no problems for implementation export feature without additional API calls. Moreover some "export" of messages and media placed in cache folder already.

Apps have rate limits on API calls. The app won't be able to require all the messages from all your chats without getting blocked. Security.

**Comment by delmoster** [comment]
> > It's not true. Unigram can read messages and media in chats. So no problems for implementation export feature without additional API calls. Moreover some "export" of messages and media placed in cache folder already.
> 
> Apps have rate limits on API calls. The app won't be able to require all the messages from all your chats without getting blocked. Security.

This limits are very big. Now in my Unigram cache I see thousands of messages. At last Unigram can convert its cache to readable format to ordinal people. Now it is good "export" for hackers.
