### ISSUE TITLE
[feature request] Move "call settings" to other settings menu.

### ISSUE THREAD

**Issue by m-alice** [UnigramDev/Unigram#2059]
Sorry, but I never found where it is

**Comment by MarcAnt01** [comment]
Any suggestions about the place? I think other settings is fine, also it's the same settings you can manage with the wheel icon during calls

**Comment by m-alice** [comment]
Something like:
≡ 
⚙ Settings 
✆ Call & Device Settings

**Comment by FrayxRulez** [comment]
They are in Advanced right now, and you can also reach them during calls pressing on ⚙

**Comment by m-alice** [comment]
Thx!

**Comment by m-alice** [comment]
The item disappeared again, but since it just duplicated w10 "App volume and device preferences" — I don't think I will miss it very much.

**Comment by makisukurisu** [comment]
@m-alice
