### ISSUE TITLE
Cannot add admins to a basic group

### ISSUE THREAD

**Issue by hihain** [UnigramDev/Unigram#2060]
It works in channels, but not in groups: The confirmation icon has no effect on clicking
![Unbenannt](https://user-images.githubusercontent.com/1473059/94986846-596a3a80-0562-11eb-94e8-d493d7c7aef8.PNG)

Unigram build 5406

**Comment by FrayxRulez** [comment]
Basic or supergroup?

**Comment by hihain** [comment]
Basic.

**Comment by FrayxRulez** [comment]
I would ask you to always provide this kind of information. It's vital to be able to fix issues.

**Comment by FrayxRulez** [comment]
Fixed
