### ISSUE TITLE
cannot select use proxy for calls

### ISSUE THREAD

**Issue by yuanshdn** [UnigramDev/Unigram#2063]
Hi
when using a proxy, I cannot select use proxy for calls
please fix this issue
![Screenshot 2020-10-04 100927](https://user-images.githubusercontent.com/61946187/95008772-b6510980-05d1-11eb-918c-7cda67e4d78d.png)

**Comment by yasershadan** [comment]
Hi the option cannot be selected
is there any solution? is it a bug?
thanks

**Comment by FrayxRulez** [comment]
The option has to be removed from the app as calls no longer support connection through proxy.
