### ISSUE TITLE
New comments counter shows wrong number

### ISSUE THREAD

**Issue by hihain** [UnigramDev/Unigram#2065]
I guess the new comments counter shows the number of new messages in the discussion group instead of the comments section.
![ezgif-6-5a327e75ead7](https://user-images.githubusercontent.com/1473059/95014499-a8d66680-0647-11eb-85b6-d281486f7ba7.gif)

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/5ba4f8f4850699e2dbe694224e22cfc71f21eeaa
