### ISSUE TITLE
New comments quotes invisible message

### ISSUE THREAD

**Issue by hihain** [UnigramDev/Unigram#2066]
Upon posting an animated emoj, there is a weird UI glitch that fixes itself after revisiting the same view. It's weird:
![image](https://user-images.githubusercontent.com/1473059/95014769-6150da00-0649-11eb-90ee-21846e881458.png)

![ezgif-6-225e10fdf992](https://user-images.githubusercontent.com/1473059/95014604-3c0f9c00-0648-11eb-96a0-2f1e42188315.gif)

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/ff25a1da001d4f37b7e54f8eb41f0398e7e99adb
