### ISSUE TITLE
Unigram switched off spellchecker or hangs during spellcheck for any language rather than English 

### ISSUE THREAD

**Issue by delmoster** [UnigramDev/Unigram#2067]
I'm using spellcheck in Russian

Unigram has several bugs around spellcheck. I think for another language rather than English Unigram never tested in spell check. 

All last builds have same incorrect behavior.  Unigram can hangs for 3-10 seconds for spellcheck next word or Unigram switched off  spellcheck without any actions from user. Sometimes helps choose Russian language again. Sometimes not.

I'm sure that same problem for all languages different from English.

However the bug is not simple. After first start Unigram works normally several hours or days. After it I see permanent spellcheck problem. So this bug is unstable for repro steps.

**Comment by FrayxRulez** [comment]
Spell check is provided by Windows, and Unigram offers a option to disable it. You can try that.
Any other report should be directed to Microsoft.

Also, this might be a problem caused by Punto Switcher as well.
