### ISSUE TITLE
Audio not working, microphone not working

### ISSUE THREAD

**Issue by n3me5is-git** [UnigramDev/Unigram#2069]
No audio when playing videos inside the chats/groups.
Impossible to record voice messages 
Impossible to do calls.

Inside call settings the only one audio device is selected for playback and recording.

I was using an old unigram version before (probably 1 year old) and everything related to audio was working (also the audio calls)

**Comment by FrayxRulez** [comment]
I'm pretty sure this isn't a problem with Unigram, but with your system.

**Comment by n3me5is-git** [comment]
Ok, did some tests, restarted PC, restarted audio devices. Now the most is working but I swill have some issues with audio related stuff.

What is completely working now:
- I can listen audio messages
- Audio calls and video calls are working

What is completely working with minor issues or strange behavior:
- I can view videos and listen related audio, but minor bugs with the UI that shows the volume bar under the main video bar, so it was tricky to increase the volume, see the attached picture below (you can see the gray volume bar semi-hidden on the left)
- I can record and send audio messages, but after the recording it takes up to 1m to send them (in my old version of months ago they were instant, don't know if it's an issue of my system or not, the feature maybe needs optimizations?)

What is not working:
- The video messages (those ones inside the circle) are always without audio. Tried many times. They can play but video only. I don't know if there is a setting somewhere to enable the related audio. On my smartphone they work (same videos, same channels). I need to save the video and open it with VNC to listen the audio. With my months-old unigram version I had before they were working. Can be this related to my settings or it's a known bug? 

Video volume bar:

![image](https://user-images.githubusercontent.com/68710094/95456193-434be800-096f-11eb-8e2f-957a7d899630.png)

Audio Message seems stuck, but waiting it works and get sent successfully 

![image](https://user-images.githubusercontent.com/68710094/95456666-f74d7300-096f-11eb-9971-4803ab52f499.png)

**Comment by FrayxRulez** [comment]
As a workaround for the volume bar, you can disable Full-screen gallery from Settings > Chat settings.
About video messages, I would ask you to create a specific ticket for that.

Thank you!
