### ISSUE TITLE
Play the next received voice message automatically

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#207]
Sometimes you have to send multiple voice messages directly after another. Because of this, you should play the next one automatically as soon as the previous has ended. 

This is already implemented in the iOS-Version of telegram.

**Comment by larsschellhas** [comment]
This could be limited to the group of messages which were received. I´m not totally sure, how it is solved in iOS/Android

**Comment by FrayxRulez** [comment]
This is fixed in https://github.com/UnigramDev/Unigram/releases/tag/v0.10.849
