### ISSUE TITLE
Unigram wont stay open

### ISSUE THREAD

**Issue by DarkGhost7** [UnigramDev/Unigram#2070]
On windows 10 unigram 7.1.5388.0 wont stay open after I log in. It loads the chats then closes the whole program. I was using for a few days before this just fine, but now work stay open or work at all. I am not running any antivirus but windows defender.

**Comment by FrayxRulez** [comment]
Hi, are you using a Strix laptop?

**Comment by FrayxRulez** [comment]
If that's the case, I should have fixed the issue: https://www.dropbox.com/s/x3df39jo278bvgf/Unigram_7.1.5410.0_x64.appxbundle?dl=1
If that's not the case, please update the app anyway.

**Comment by DarkGhost7** [comment]
Yes I am

**Comment by FrayxRulez** [comment]
Then update the app as the problem is fixed.

**Comment by DarkGhost7** [comment]
Wow works perfect! Thanks!
