### ISSUE TITLE
Single screen flickering at close ( long time black screen at crash )

### ISSUE THREAD

**Issue by sampadsams** [UnigramDev/Unigram#2072]
Seems like a real problem.

**Comment by FrayxRulez** [comment]
I don't understand.

**Comment by sampadsams** [comment]
whole monitor goes black at close.

**Comment by FrayxRulez** [comment]
I don't think this is related to Unigram, you might want to report this issue to Microsoft/your computer OEM.

**Comment by sampadsams** [comment]
Yeah, it wasn't Unigram's doing. It was another application causing it, but only when I was clicking Unigram.
Thanks anyway.
