### ISSUE TITLE
Touch keyboard is opened when it shouldn't within the chat

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2077]
- [ ] Attach menu;
- [ ] Long press in typing bar.

**Comment by FrayxRulez** [comment]
Can't reproduce

**Comment by MarcAnt01** [comment]
Having a touch screen and detachable keyboard or 360° hinges is required to reproduce, tablet mode is not enough

**Comment by FrayxRulez** [comment]
This is a Windows behavior
