### ISSUE TITLE
paste content via context menu from clipboard on a desktop PC opens freehand input and does not insert text

### ISSUE THREAD

**Issue by joerg-vandervlies** [UnigramDev/Unigram#2078]
Hi,

with the latest version I cannot paste text from the clipboard anymore. I'm using a desktop PC without any touch devices attached. If I attempt to paste something from the clipboard, then a popup for freehand input will appear and if I close it, the input field remains unchanged.

![image](https://user-images.githubusercontent.com/28155731/95680233-6f1dd680-0bd8-11eb-9e29-f8efad74def8.png)

![image](https://user-images.githubusercontent.com/28155731/95680295-dfc4f300-0bd8-11eb-8c8d-7c53f5eb2623.png)

![image](https://user-images.githubusercontent.com/28155731/95680244-8230a680-0bd8-11eb-8c62-b4faf68b5884.png)

Pasting text via keyboard shortcut works as expected.

kind regards
Jörg

**Comment by FrayxRulez** [comment]
Known, sorry, some experiment was in progress and I forgot to roll back :)
