### ISSUE TITLE
New messages retrieval strategy

### ISSUE THREAD

**Issue by bugada** [UnigramDev/Unigram#208]
When a channel or group has a lot of unread messages (i.e. 7000) and the connection is slow, if you press the last message arrow, shows the current last loaded message (i.e. 2000) and continues to update the chat till the real end is reached (sometime it requires 40 or 50 seconds).  In my opinion it should load nth messages from the end, and the others only if the user requests them by scrolling up the chat.

**Comment by FrayxRulez** [comment]
Should be fixed
