### ISSUE TITLE
Add delay on-hover for emoji button

### ISSUE THREAD

**Issue by Hexaae** [UnigramDev/Unigram#2083]
Please add a badly needed delay when on-hover the emoji button in the chat because is **VERY annoying** the immediate auto-pop-up, and/or add make it pop-up only on click and not on-hover.

**Comment by itowky3001** [comment]
@Hexaae Make it an optional function, not default setting

**Comment by MarcAnt01** [comment]
Well, the click opens the expanded panel, so it isn't really an option
