### ISSUE TITLE
pinned messages from previous groups are shown

### ISSUE THREAD

**Issue by sukiletxe** [UnigramDev/Unigram#2084]
This happens in latest beta. Steps:

1. Open a chat with a pinned message, then close it.
2. Open another chat with a pinned message.
3. Position yourself (with tab) in the back button.
4. Tab twice. 

Expected: first tab, a link (pressing enter on it moves you close to the pinned message), second tab, a button (I believe to remove the pin, locally).

Actual: the second tab lands on a pin of another group. If you press enter on it the list moves up to the date of the message, as if trying to move you to that pin (it can't since it is from another group).

**Comment by FrayxRulez** [comment]
I fixed this yesterday!
