### ISSUE TITLE
Crashes at startup on Windows 10 1709

### ISSUE THREAD

**Issue by sr1canskhsia** [UnigramDev/Unigram#2087]
Everything worked fine till yesterday. Now it just shows the blue logo then crashes. Tried completely uninstall and reinstall but couldn't get past the login screen.

Windows 10 Pro Version 1709 Build 16299.1087. Is it because my Windows 10 version is way too old?

**Comment by FrayxRulez** [comment]
Hi, yes, the app isn't tested on such old versions, but I will still try to fix it ASAP.

**Comment by FrayxRulez** [comment]
Hey, managed to find the issue, will fix and upload a new version to the Store/channel today.

**Comment by sr1canskhsia** [comment]
Works fine now! Thank you for keeping support such an old version of Windows 10
