### ISSUE TITLE
Proposal: adding colored notification badge

### ISSUE THREAD

**Issue by matyidenisz11** [UnigramDev/Unigram#2089]
![image](https://user-images.githubusercontent.com/50969017/96333932-957ac080-1075-11eb-8894-df8b3e65dd1f.png)
That would be nice if the badge was red when you receive a message from not muted group/chat or you are mentioned as it is in official client
Though there's a weird thing that the number of messages differs from each other, but i guess that's not a theme for this topic.
(I'm sorry if I did something wrong, never used Issues function in github before)

**Comment by MarcAnt01** [comment]
Hello, I am sorry, but UWP does not offer any customization for the numeric badge.
https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/badges

**Comment by itowky3001** [comment]
@MarcAnt01 oh jeez holy cow
