### ISSUE TITLE
Further improvements for touch keyboard handling

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2092]
- [ ] Don't rise the chat message texbox when using global and chat search
![image](https://user-images.githubusercontent.com/43090263/96370511-5bd1b480-115e-11eb-81c8-41e866f089b0.png);
- [ ] Close and reopen virtual keyboard when pasting a picture to prevent overlapping typing textbox

**Comment by FrayxRulez** [comment]
Both are not possible
