### ISSUE TITLE
Could you list features that are in TDesktop now?

### ISSUE THREAD

**Issue by SmartManoj** [UnigramDev/Unigram#2098]
So, it would be easy to compare.
https://github.com/UnigramDev/Unigram#features

**Comment by MarcAnt01** [comment]
Listing our features, is a good idea, in fact they are already in the readme, but listing the ones of a competitor isn't definitely.

**Comment by SmartManoj** [comment]
But it is an official app

**Comment by MarcAnt01** [comment]
That doesn't matter actually, we are a different app, we don't depend on Telegram Desktop.
