### ISSUE TITLE
DroidCamApp not working in Unigram

### ISSUE THREAD

**Issue by koloved** [UnigramDev/Unigram#2100]
the program can't detect this camera

**Comment by FrayxRulez** [comment]
UWP apps can only consume Media Foundation webcams, and virtual webcams (such as DroidCamApp) usually use DirectShow. This is something that can't be fixed/implemented by me.

**Comment by FrayxRulez** [comment]
As this issue can't be fixed I'm closing this ticket to give more visibility to the ones that can actually be worked on
