### ISSUE TITLE
Bio isn't updating

### ISSUE THREAD

**Issue by matiidenys** [UnigramDev/Unigram#2101]
When my bio is being changed by either my userbot or just phone, it's still the old one in unigram
I have to close the app and open again to get the newer bio.
https://youtu.be/JR2VWJ44Q8U
Here's a video with an example

**Comment by FrayxRulez** [comment]
Did you try to do the other way around? So to modify the bio in Unigram and see if it does update on Android?

**Comment by matyidenisz11** [comment]
> Did you try to do the other way around? So to modify the bio in Unigram and see if it does update on Android?

If I change the bio in Unigram, it changes right away in android

**Comment by MarcAnt01** [comment]
The same happens with phone number change, but I guess that's not relevant, since it's something not supposed to happen frequently

**Comment by FrayxRulez** [comment]
This is by design on TDLib, you can open an issue [here](https://github.com/tdlib/td) if you want!
