### ISSUE TITLE
If pined message bar is closed in a channel, that channel will display pinned messages from another channel

### ISSUE THREAD

**Issue by NotLT** [UnigramDev/Unigram#2102]
to reproduce, close the pin of a channel with the X, then go to another channel with a pin, and then back to that channel where you closed the bar.

**Comment by NotLT** [comment]
Also clicking on it will focus the chat on some random message, not the pinned one.

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/c8dd174ae8aadb028df2d1d657cb1c55e8512470
