### ISSUE TITLE
Unigram title bar doesn't go away in fullscreen mode.

### ISSUE THREAD

**Issue by xmha97** [UnigramDev/Unigram#2107]
Unigram title bar doesn't go away in fullscreen mode.
Use Win⊞+Shift⇧+Enter⤶ to full-screen any UWP app.
Please watch [Video.zip](https://github.com/UnigramDev/Unigram/files/5468404/Video.zip)

**Comment by MarcAnt01** [comment]
That's because Unigram titlebar is custom👍
