### ISSUE TITLE
Unigram always crashes when I open a particular chat

### ISSUE THREAD

**Issue by Neurrone** [UnigramDev/Unigram#2108]
As it says in the title. This has only started happening very recently (today), so I suspect that a recent message that was sent might be causing Unigram to crash. Works just fine if using the usual Telegram client.

Have also tried clearing cached stickers in hopes that would fix the crash but no luck.

Are crash logs stored anywhere so that I can provide more information?

**Comment by Neurrone** [comment]
Oh, after I restarted Unigram, I found that it automatically updated itself to v7.2 which appears to have fixed this issue. No longer reproducable, closing

**Comment by FrayxRulez** [comment]
Fiù... 7.2 aimed to fix this kind of issues, and seeing this ticket popping out scared me quite a lot 🙃
