### ISSUE TITLE
Bot Login Via Token

### ISSUE THREAD

**Issue by mktcockpit** [UnigramDev/Unigram#2111]
**Any plans on telegram desktop login with bot token ?..** 

So that we can know who is using the bot in a more user-friendly interface,  say we have bot hosted as per our requirement.. and we know many of bot subscribers are using it.. now to have more user-friendly interface if we get an option to log as a bot, it makes bot owner know what exactly users are facing issues while using it, or we will come to know the way we can improve...

**Comment by jacknicholson112** [comment]
Bump. This function is also very much needed. This feature has already been implemented in unofficial android applications such as telegraph (graph messenger) and Neko. The api method is also present in the telegram desktop. Here are the links to speed up the application. I'm really looking forward to it! 

https://play.google.com/store/apps/details?id=ir.ilmili.telegraph
https://github.com/LonamiWebs/Telethon/issues/36#issuecomment-287653377
https://github.com/telegramdesktop/tdesktop/blob/46d393ea0f5eca49ff14393dd28e12b0913d3fa1/Telegram/Resources/tl/api.tl#L1281

https://gitlab.com/Nekogram/Nekogram/-/blob/master/TMessagesProj/src/main/java/org/telegram/ui/LoginActivity.java#L268
https://github.com/DrKLO/Telegram/blob/master/TMessagesProj/src/main/java/org/telegram/ui/LoginActivity.java#L258

**Comment by Muaath5** [comment]
@jacknicholson112 Note that Unigram uses TDLib, Not Telegram API.

So links you sent isn't needed.

**Comment by jacknicholson112** [comment]
> 
> 
> @jacknicholson112 Note that Unigram uses TDLib, Not Telegram API.
> 
> So links you sent isn't needed.

Okay. Looking forward to this feature! It hasn't been found anywhere in desktop applications yet. Thanks for the answer.

**Comment by FrayxRulez** [comment]
I understand that this feature might sound appealing to some but the app would mostly not work, hence I'm closing this.
