### ISSUE TITLE
minor things 1 and 2 (pressing esc in archived chats and tapping tab names

### ISSUE THREAD

**Issue by heliumbaloon** [UnigramDev/Unigram#2114]
minor things..

1. would it be annoying if pressing esc in archived chats takes me to the top of the list first then to all chats instead of directly to all chats?

2. it would be handy if tapping f different tabs ...takes me to the top of the list if i am in that list instead of manually scrolling all the way up or changing to different tab and back to go to the top...

**Comment by FrayxRulez** [comment]
This has been implemented
