### ISSUE TITLE
Chat selection not persistent between folders

### ISSUE THREAD

**Issue by githubcatw** [UnigramDev/Unigram#2117]
When I select a chat and switch to a (different) folder that contains the chat, it becomes deselected.

To reproduce:
1. Add a chat to a folder.
2. Go to All Chats, or any other folder with the chat in it.
3. Select the chat.
4. Go to the folder you selected in Step 1.

Expected: chat is still selected
Actual: chat isn't selected

OS version: Windows 10 20H2
Reproducible on: Unigram 7.2 (5705) x64, 7.2 (5724) x64, 7.2 (5725) x64, 7.2 (5750) x64.
Video: [link](https://1drv.ms/v/s!AukIzF1WiirUsypMPMQ6_8_QdJRc?e=YdhN4f)

**Comment by githubcatw** [comment]
This bug is also reproducible on 7.2 (5750) x64.

**Comment by FrayxRulez** [comment]
This works now
