### ISSUE TITLE
No "Writing messages isn't allowed in this group" if you are not a participant

### ISSUE THREAD

**Issue by makisukurisu** [UnigramDev/Unigram#2118]
If it's forbidden to write messages to group, this group is linked to a channel and you open comment section while not being participant in that group there will be no message "Writing messages isn't allowed in this group"

Steps to reproduce: (temp, will add permanent if needed)

Go to https://t.me/BotNews, open comments to last post without joining linked chat (https://t.me/BotTalk)

Expected:
> No opportunity to write messages

Actually:
> No opportunity, but message box is present and can "send" messages.

**Comment by FrayxRulez** [comment]
Done
