### ISSUE TITLE
Delete multiple messages but it deleted the whole chat

### ISSUE THREAD

**Issue by Wolfrisger** [UnigramDev/Unigram#2119]
I cant reproduce this, I was deleting 2 messages i just sent because i sent to wrong person.
but then, the whole chat deleted just like the nuclear deletion.
I dont care those messages but still this feels terrible, so if possible please check on this, thanks.

Unigram version 7.2 (5665) / Win10 pro 19042.610

**Comment by MarcAnt01** [comment]
Are you actually sure that the other person hasn't deleted the whole chat? I think that's the case.

**Comment by Wolfrisger** [comment]
> 
> 
> Are you actually sure that the other person hasn't deleted the whole chat? I think that's the case.

Yes I'm sure that wasn't him, because the other person was sleeping and woke up 3 hours later after the deletion.
and this happens right after the deletion of 2 messages. (the whole chat closed and cant be found on the list.)

**Comment by FrayxRulez** [comment]
To delete selected messages you must right click those messages and click on "Delete Selected Messages", while I'm pretty sure that you clicked on the more options (...) button and selected "Delete chat". 
There is no way that Unigram could have deleted your chat without explicitly selecting that option.

**Comment by Wolfrisger** [comment]
> 
> 
> To delete selected messages you must right click those messages and click on "Delete Selected Messages", while I'm pretty sure that you clicked on the more options (...) button and selected "Delete chat".
> There is no way that Unigram could have deleted your chat without explicitly selecting that option.

hmmm after some thought I think you are right. since those 2 really has an almost same window on the deleting warning and i just woke up without coffee.

maybe a better or second warning would be nice but thats my fault, sorry for the disturbance.
