### ISSUE TITLE
unable to copy some links instant view

### ISSUE THREAD

**Issue by heliumbaloon** [UnigramDev/Unigram#2121]
im not able to copy some llinks in instantview eventhough a tooltip for the link appears to show the embedded link in the text

eg link in here in telegram https://t.me/r_technology/1643  or link alone https://www.eff.org/deeplinks/2020/11/riaa-abuses-dmca-take-down-popular-tool-downloading-online-video

 rightclicking links in the last part of the instant view of the article doesnt bring an option to copy them (theyre treated as simple text with just select all option available

**Comment by FrayxRulez** [comment]
Can't reproduce, was probably implemented at some point
