### ISSUE TITLE
Some quirks in "edit" menu in latest beta

### ISSUE THREAD

**Issue by sukiletxe** [UnigramDev/Unigram#2123]
Recently, a new edit menu has been introduced. This menu has some weird behaviours.

In text messages, we get "edit" option and edit menu. In the menu, we get "edit caption", "edit this photo" and "replace photo". The three of them edit the text. No idea about voice messages.

Also, the menu shows (empty) with other people's messages.

Thanks!

**Comment by FrayxRulez** [comment]
Hey, this is expected for now and fixed in source code. Thank you for the report!
