### ISSUE TITLE
Taskbar badge doesn't update, if Unigram is launched automatically on system start

### ISSUE THREAD

**Issue by dckface** [UnigramDev/Unigram#2125]
When Unigram is configured to be launched automatically in minimized state after system start, the taskbar badge is never updated, until the app is closed and opened again.

**Comment by FrayxRulez** [comment]
Sounds like a system bug to me, what's your Windows version?

**Comment by dckface** [comment]
I'm using Windows 10 Pro 20H2 preview (build 19042.610) from Insider Beta channel. It's happening on both of my machines with this system version. However, this wasn't working even before I started using Insider builds. Previously, I had the 20H1 update, so version 2004.

**Comment by FrayxRulez** [comment]
Which version of the app?
I have Unigram in auto-start as well, but I have more than 99 unread chats, so I only see "99+".
I see it kind-of-blinking on launch, so I thought it works.

**Comment by dckface** [comment]
The latest Store version (7.2.5665.0). I've tested it a bit more today and observed following. 

When someone sends me a message and Unigram is started automatically and minimized, the badge doesn't update, but the notification shows up (banner in action center). However, I'm quite sure the received notification is just a push notification, as it's received at the same moment as I get it on my phone. Once I restore Unigram's window, the badge suddenly shows up on taskbar and the notification for message is received again (this time it's not push notification but regular notification). After I minimize Unigram, the badge doesn't update again and I'm only receiving push notification. Moreover, this seems to affect not just taskbar badge, but also Unigram's live tile, since it doesn't update either under those conditions (only once I restore Unigram's window from minimized state).

Also, when Unigram starts automatically in minimized state, then every time Unigram is minimized, the Task Manager says that it's also in suspended.
![image](https://user-images.githubusercontent.com/3797371/98443789-00b43180-210e-11eb-94bb-c87c526c775e.png)
However, when I close Unigram, open it again and minimize it, it's never in suspended state, no matter how long it's been minimized.
![image](https://user-images.githubusercontent.com/3797371/98443856-7cae7980-210e-11eb-81fe-0ca15bab72bb.png)

Overall it seems like when Unigram starts automatically in minimized state, it's getting suspended upon its main window getting minimized, so it's only capable of receiving push notifications. However, as described in #1867, Unigram's taskbar badge never gets updated upon receiving push notifications (which apparently applies to live tile as well).

**Comment by MarcAnt01** [comment]
@dckface is this still the case now that Unigram is no longer sing push notifications?
