### ISSUE TITLE
Searchbar scrollable during search

### ISSUE THREAD

**Issue by mateiradu** [UnigramDev/Unigram#213]
Issue: searchbar is scrollable during a search and shows the chat list in that tiny space.

Replicate: search for anything using searchbar and use mouse wheel (or touch scroll) on the searchbar itself. See gif for example:
![p70326-012904](https://cloud.githubusercontent.com/assets/1713151/24327240/f4aacfdc-11c3-11e7-842a-bbde235003d1.gif)

Unigram version: 0.1.138.0 store release.

Suggestion: lock scroll of chat list when text is present in searchbar, re-enable scroll when searchbar is empty.

**Comment by FrayxRulez** [comment]
Fixed in 0.2.296
