### ISSUE TITLE
Crash when clicking sticker in message

### ISSUE THREAD

**Issue by Magentaize** [UnigramDev/Unigram#2131]
If I click any sticker sent by others or me, unigram is stun and force exits in about 3 seconds.
![image](https://user-images.githubusercontent.com/11793304/98895248-a1756900-24e1-11eb-89e1-2712f5939e0c.png)

Here is the event report:
>Faulting application name: Unigram.exe, version: 1.0.0.0, time stamp: 0x5fa9b441
Faulting module name: KERNELBASE.dll, version: 10.0.19041.572, time stamp: 0x1183946c
Exception code: 0xc000027b
Fault offset: 0x000000000010b65c
Faulting process id: 0x2ccc
Faulting application start time: 0x01d6b8aa47d9c1fb
Faulting application path: C:\Program Files\WindowsApps\38833FF26BA1D.UnigramPreview_7.2.5752.0_x64__g9c9v27vpyspw\Unigram.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 407ca536-1c9c-4a3c-a5fb-4e1d9c748482
Faulting package full name: 38833FF26BA1D.UnigramPreview_7.2.5752.0_x64__g9c9v27vpyspw
Faulting package-relative application ID: App

**Comment by FrayxRulez** [comment]
Hello, can you reach me out on Telegram? Same username as here!
