### ISSUE TITLE
Call window to stay on top

### ISSUE THREAD

**Issue by ImjuzCY** [UnigramDev/Unigram#2139]
Especially for video calls, it would be great if the call window can stay on top for multitasking. Like for example in Skype. Currently if I'm on a call and I need to open another window, the call window will go behind and I can't see the call.

**Comment by MarcAnt01** [comment]
Hi, thanks for your suggestions, I've already opened a ticket to keep track of that

**Comment by MarcAnt01** [comment]
Duplicate of https://github.com/UnigramDev/Unigram/issues/2039
