### ISSUE TITLE
Fatal crash upon first channel-joining attempt (though second time succeeded)

### ISSUE THREAD

**Issue by KeronCyst** [UnigramDev/Unigram#2140]
1. On my Windows 10 Home, I had Unigram v7.2.5639 open (or whatever version the Microsoft Store had on 2020-11-20)
2. I went to https://telegram.me/ideasfortelegram and followed the popup prompt to connect via Telegram
3. It died and yielded this: 
![image](https://user-images.githubusercontent.com/13827055/99853420-c39d6580-2b37-11eb-8e80-5d30a3e6501a.png)
4. I revisited that same URL while Unigram was _not_ open and then it went through successfully

🤔

**Comment by FrayxRulez** [comment]
If you search on the web for the error (0x80040904) you'll find out that this is a generic UWP error, likely caused by the system itself.
