### ISSUE TITLE
Stickers - Sidebar scalling

### ISSUE THREAD

**Issue by Acid-Crash** [UnigramDev/Unigram#2141]
Uningram seems to have a different smoothing/scaling option applied to the Stickers in the sidebar menu.
This leads to the 'pixelated' edges present in the majority (not all of them) of the sticker packs.
See example of the default sticker pack (Great minds).

TelegramDestop (left) - Unigram - Right.
![изображение](https://user-images.githubusercontent.com/32600318/99854481-8fed2a80-2b8d-11eb-8efc-ee5a639224a2.png)

Win10x64 GeForce 1060
Resolution 1920*1080 
Windows at 100% (default) scaling
Unigram 7.2 (5781)

**Comment by FrayxRulez** [comment]
This should have been improved a lot in https://github.com/UnigramDev/Unigram/commit/0dcead3fd42ce73afab1f7c82407709bb8316e11
