### ISSUE TITLE
The chat name is not pronounced correctly, there is an offset by one in the list

### ISSUE THREAD

**Issue by isaevs** [UnigramDev/Unigram#2143]
Hello.
program version 7.2 (5801) x 64,  if you open the chats tab and then place the cursor on the first chat, JAWS will say the name of the chat. Going down to the bottom with arrows, chat names will be pronounced with an error. So the first will be read correctly, the second as the first, the third as the second, and so on. In the opposite direction, vice versa, Always the shift of the correct chat name goes one position.
Version JAWS 2019.1904.60
NVDA reads chat names correctly
The problem appeared in the latest or penultimate version.
JAWS NVDA screen readers.

**Comment by FrayxRulez** [comment]
Hi, sorry but this project is English first. Could you translate your issue?

**Comment by isaevs** [comment]
Sorry for the mistake, I redid it

**Comment by isaevs** [comment]
> Привет, извините, но этот проект в первую очередь английский. Не могли бы вы перевести свой выпуск?

Sorry for the mistake, I redid it

**Comment by FrayxRulez** [comment]
Do you use any Unigram plugin for JAWS?

**Comment by isaevs** [comment]
> Вы используете какой-либо плагин Unigram для JAWS?
Hello, no

**Comment by kranid** [comment]
i have same problem.

**Comment by FrayxRulez** [comment]
Not our issue
