### ISSUE TITLE
Dragging and dropping a link into a chat does not send the link

### ISSUE THREAD

**Issue by Poopooracoocoo** [UnigramDev/Unigram#2145]
drag a link from a browser's site info icon into a chat to try to send it. It'll try to send a .url but fail.

:) love unigram. it's incredible. i would sponsor if i could!!!! <3 i searched for "drag link" and for "drop link"

**Comment by MarcAnt01** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/e7ed11a2b846727ea80c6be7da8dbd5a4da42fbd
