### ISSUE TITLE
Layout cycle detection when using inline bot for second time

### ISSUE THREAD

**Issue by dmnmsc** [UnigramDev/Unigram#216]
Happens with  @YouTube and @sticker. Use it once, type something but don't send. Remove your text, type something different. You will get an exception.
![photo_2017-03-26_21-43-47](https://cloud.githubusercontent.com/assets/8472142/24334602/58fc3616-126d-11e7-8011-c2ddb0255a13.jpg)

Desktop app is freezing here. You can type and send text (and it will work) but you won't see any change in your UI.

**Comment by Eweol** [comment]
@dmnmsc thanks for making an issue
