### ISSUE TITLE
Unigram seems to ignore "Enable audio enhancements" in Windows 10

### ISSUE THREAD

**Issue by lorenzo0932** [UnigramDev/Unigram#2163]
If you try to record an audio from unigram you don't have any of audio enhancements for microphone, so the produced audio file will be a horrible mess with very much noise and no eco reduction at all. 
I tested this problem in 3 different devices, 1 surface and 2 desktop with external microphone.
Also, is not a problem of windows apps because every other uwp apps that i use doesn't have this problem.
Telegram Desktop and Telegram Web seems to works as aspected. 
If you have a solution please tell me

PS. Sorry for my english

**Comment by FrayxRulez** [comment]
Hi Lorenzo, Unigram uses raw audio processing, as many users complained about the enhancement results. 
I will try to turn on again enhancements in the next update (that you can download from t.me/unigramappx if you don’t want to wait for a store release) and we’ll see what happens 😉

**Comment by lorenzo0932** [comment]
Thanks for reply!!
So, if i can ask, it would be difficult to implement something like a switch in advanced settings for set on or off raw audio processing?
I don't know much about implementing uwp program. I'm quite curious about it

PS. Sorry for my English Pt.2 😅

**Comment by FrayxRulez** [comment]
I believe that this was fixed at some point 👀 feel free to ping here if it's not the case!
