### ISSUE TITLE
Custom storage path stopped working

### ISSUE THREAD

**Issue by revanmj** [UnigramDev/Unigram#2164]
After one of the recent updates Custom storage path stopped working.

Once I set it to something (doesn't matter if its on C: drive or other), Unigram is unable to download and thus display (cancel and download buttons on thumbnails are constantly replacing each other) or send any attachments.

Windows 10 x64 (19042.630)

**Comment by FrayxRulez** [comment]
Version of the app is usually more important than version of the OS.

**Comment by revanmj** [comment]
Sorry, forgot about it: 7.2.5868

**Comment by FrayxRulez** [comment]
I just released a update that should fix the issue, let me know.

**Comment by revanmj** [comment]
Well, version 5873 fixed it partially - custom path works fine if it is on C: drive, but still fails same as before if it is on any other drive (I had it on D: originally).

**Comment by FrayxRulez** [comment]
What’s the problem exactly?
I tested extensively both C: and D: locations and they worked fine for me.

**Comment by revanmj** [comment]
I get this (X icon constantly switches with the download one) if I set the custom path to any drive other than C:

![Zrzut ekranu 2020-11-29 124135](https://user-images.githubusercontent.com/1777618/100540885-85dbc380-3240-11eb-99a4-14c5e8188b20.png)

If I try to send a file, it fails right away with the same X icon instead of the thumbnail.

I had switched HDD with SSD recently (custom path was originally set to this drive) and then issue occured for the first time, but it was fixed by setting the path again. Than today it occured again, but initially only default path worked and now with the fix only paths on C: drive work.

**Comment by FrayxRulez** [comment]
I'm just using the app now with download folder set to my D: drive and everything works as expected.
Could you enable and send me some logs?
Instructions are in the repository documentation.

**Comment by FrayxRulez** [comment]
Also, when receiving a picture, are you able to see the blurred thumbnail or you see nothing?

**Comment by revanmj** [comment]
Strange, after I set it once again (I wanted to catch setting path in logs too) it started working. 

As for the second question - first time I noticed the issue, there was a blurred thumbnail. But ever since I reset path to default and tried setting it again, there was nothing.

Left logs enabled for now in case issue occured again.

**Comment by FrayxRulez** [comment]
[TechiError](https://github.com/TechiError) opened this issue on May 24, 2021 · 7 comments
> 🐛:bug:
> **Describe the bug**
> When sending medias to any chat with editing with unigram editor the media upload fails if there is custom download folder.
> 
> **Expected behavior**
> The media should upload without any problem in the chat whether custom download folder or not.
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/75001577/119319558-3c70ac00-bc98-11eb-87b3-c84efbe56bd3.png)
>
> **Version Info**
>  - Unigram: 7.8 (6368) x64
>  - Windows: Windows 10 Pro 20H2 (OS Build 19042.985)

**Comment by FrayxRulez** [comment]
[aalberrty](https://github.com/aalberrty) opened this issue on Oct 8, 2022
> **Describe the bug**
> I have a NAS at home and it is mapped as a network drive F:, changing the download location to it stops the app from working even after restarting, it gives a blank dark blue screen where there isn't any button to press, need to reset app in settings to make it work again.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Press profile picture
> 2. Press 'Settings'
> 3. Go in to 'Data and Storage'
> 4. Change 'Storage Path' to a network drive F: (\\\192.168.50.150)
> 5. The app presents a dark blue screen where a reset is required to fix it.
> 
> **Expected behavior**
> The download location is changed and working properlly like the official version.
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/59857887/194703134-d1bde42a-bda5-4b46-9e87-dbfce282dae0.png)
> 
> **Version Info**
>  - Unigram: 9.0 (7780)
>  - Windows: Windows 11 Pro 22H2 22621.521

**Comment by FrayxRulez** [comment]
Starting from 9.6.3 (now available in beta) the app offers a new download management system that’s quite similar to what browsers do (as well as Telegram for macOS). 
All files are always downloaded to a temporary location “invisible” to the user, but documents, audios and videos are accessible through a chosen directory (default is Downloads\Unigram). The files that you manually download are immediately available in this location, while the ones that are downloaded automatically become available as soon as you open them from the app.
