### ISSUE TITLE
Unigram show you the possibility to ban/change permission of yourself (the owner)

### ISSUE THREAD

**Issue by mopitithomne** [UnigramDev/Unigram#2165]
STR:

- Create a simple channel
- Open the profile of the channel
- Press on "Removed users"
- Press on "Remove User"
- Press on yourself (the owner)
- You will be able to ban/change the permission

The app shouldn't show you the possibilty to change your permission since It is impossible to do that.

**Comment by FrayxRulez** [comment]
Fixed in 5440b8e41b253b9046837c58218cf718873084d9
