### ISSUE TITLE
Some pictures are cut in the media editor after rotation

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2167]
Picture to reproduce
![image](https://user-images.githubusercontent.com/43090263/100732093-90c35f00-33cc-11eb-8e5d-9e2180f79fd3.png)

**Comment by FrayxRulez** [comment]
Are you sure that's the original image?

**Comment by MarcAnt01** [comment]
Yes, but I cannot reproduce any longer now 😕

**Comment by MarcAnt01** [comment]
Yes, can't you reproduce it?
