### ISSUE TITLE
 inline result for bots 

### ISSUE THREAD

**Issue by alighamari** [UnigramDev/Unigram#2168]
inline result for bots(like t.me\Gachimuchikbot) doesn't contains all information that it should contain 

audios are not playable

images can't be previewed by click and hold

searching with @GIF normally should load beginning of gif and then on hold it should download full and show, but as I experienced it downloads all Gifs at full length 

good thing is it shows the duration of audios and I like it 

![image](https://user-images.githubusercontent.com/24440862/100941943-bb6a0080-350f-11eb-9a23-327664494386.png)
![image](https://user-images.githubusercontent.com/24440862/100941945-bc029700-350f-11eb-88af-283ff1c5f20f.png)

**Comment by FrayxRulez** [comment]
I think that inline bots are good as they currently are
