### ISSUE TITLE
App Scale

### ISSUE THREAD

**Issue by Dvaderfun** [UnigramDev/Unigram#2170]
Ok guys, UWP supports system scaling, but how I can make Unigram's UI bigger? I have 100% system scaling, but on my monitor Unigram's UI elements look small and this is uncomforrtable. Is there an option to make custom scaling for Unigram?

**Comment by FrayxRulez** [comment]
This scenario isn’t supported by UWP apps. 
Unigram elements have the same metrics of the rest of your system, consequently you can change your system scaling to 125%.

**Comment by FrayxRulez** [comment]
A slider for changing UI scaling from 100 to 225% has been added to Settings > Appearance.
