### ISSUE TITLE
Still get notifications about pinned messages when they was turned off

### ISSUE THREAD

**Issue by f242** [UnigramDev/Unigram#2172]
Still get notifications about pinned messages in group chats when they was turned off in "Notifications and sounds"

7.3 5893 x64

**Comment by Alexminator99** [comment]
Still get notifications about pinned messages in group chats when they was turned off in "Notifications and sounds"

7.8 6586 x64

PLS a little more priority on this, it most be very simple to fix. Thks

**Comment by FrayxRulez** [comment]
Duplicate of #2622

**Comment by MarcAnt01** [comment]
Still not working

**Comment by FrayxRulez** [comment]
TDLib
