### ISSUE TITLE
Overlay window for photo viewer

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2175]
It'd be nice to have a overlay small window also for photos, like the ones for videos. It could be really useful to check a photo while using another app

**Comment by FrayxRulez** [comment]
I don't think this feature is needed, as on a computer you can easily snap two windows next to each other.

**Comment by makisukurisu** [comment]
Another solution would be to use Power Toys, which allow to crop some portion of the app and put it on top.

Disregarding specialized software for such tasks 🙃

*since a window next to another window is not exactly the same as an overlay
