### ISSUE TITLE
Shared media thumbnails aren't loaded when setting custom download location

### ISSUE THREAD

**Issue by Jeidoz** [UnigramDev/Unigram#2180]
Media tab creates empty space per each image media, but do not show thumbnails and do not react on click. Render and react only at videos. Images are in media folder, and exists there. I think it is some bug of rendering this part or some incompatibility with my OS specifications or what?

How it looks in Unigram 7.2.5889.0 on Windows 10 version 1909 (build 18363.1256) downloaded from Microsoft Store

![image](https://user-images.githubusercontent.com/23425714/102293164-ccbb0000-3f46-11eb-8c65-b87d3abc5fab.png)

**Comment by FrayxRulez** [comment]
This depends on the download location, actually

**Comment by tschlienger** [comment]
Having the same problem here, and @FrayxRulez was right: Changing the default save location for media results in picture previews disappearing. Videos still work.
