### ISSUE TITLE
Screen readers can't read the member's list in a group

### ISSUE THREAD

**Issue by jpavonabian** [UnigramDev/Unigram#2183]
If you try read the list of members in a group, the screen reader reads a json.
Here an example:
chatMember {
  user_id = 6181988114
  inviter_user_id = 554197122
  joined_chat_date = 1608075032
  status = chatMemberStatusAdministrator {
    custom_title = "Hacker"
    can_be_edited = false
    can_change_info = true
    can_post_messages = false
    can_edit_messages = false
    can_delete_messages = true
    can_invite_users = true
    can_restrict_members = false
    can_pin_messages = true
    can_promote_members = false
  }
  bot_info = null
}

**Comment by FrayxRulez** [comment]
Hey, what’s the version of your Unigram? I think that you’re outdated.

**Comment by jpavonabian** [comment]
I'm sorry. I didn't realize that. I do have an unupdated version.
I have upgraded and the problem has been fixed.
A thousand apologies.
