### ISSUE TITLE
Does not load all image previes from inline mode (@pic)

### ISSUE THREAD

**Issue by Jeidoz** [UnigramDev/Unigram#2184]
I just searched image by inline mode of @pic bot and it does not show all thumbs, but they are clickable and send clicked image. Tried @gif command, and it showed all images. Why Unigram from Microsoft Store have such problems with images?

Unigram 7.2.5889.0 on Windows 10 version 1909 (build 18363.1256)

![image](https://user-images.githubusercontent.com/23425714/102494966-c5464480-4075-11eb-8efb-52a1cc4d3031.png)

**Comment by FrayxRulez** [comment]
This should be fixed
