### ISSUE TITLE
Rotate a video within the video player

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2189]

**Comment by FrayxRulez** [comment]
Duplicate of #1296

**Comment by MarcAnt01** [comment]
@FrayxRulez the issue you've referenced is about photos, this one is about video. Should I open this issue again or refactor the other one to be more generic?

**Comment by FrayxRulez** [comment]
I've already refactored the other one.

**Comment by MarcAnt01** [comment]
Perfect, I updated the description, as well
