### ISSUE TITLE
Use CommandBar instead of ellipsis button on top

### ISSUE THREAD

**Issue by prajjwaldimri** [UnigramDev/Unigram#219]
Command Bar is the UWP way of displaying overflow commands which could not fit into the top bar in UWP. Ellipsis or overflow icon is used in Android.

**Comment by FrayxRulez** [comment]
Mmh, I don't think that using the CommandBar overflow will make that big diffence.
Also, since Creators Update CommandBar secondary items (overflow) have support for icon too.

**Comment by prajjwaldimri** [comment]
Windows Phone users have been using CommandBar (as AppBar in Windows Phone times) so I think if you move the commands to the bottom, it is more easy to use and more native looking xD . I think you can give it a try on the main chat menu using A/B testing in store and ask the users for reviews

**Comment by mohsens22** [comment]
@FrayxRulez @frayxrulez Don't forget passcode lock 😉

**Comment by FrayxRulez** [comment]
Is already planned to move it to the bottom on mobile, at least for MainPage. But would be a problem in DialogPage.

**Comment by prajjwaldimri** [comment]
Yup it would look awkward in Chat view. And users have chances to accidentally tap the commands.

**Comment by MarcelBrusius** [comment]
You could also include the search in this bar as an icon to save some space in the chat list ;)
