### ISSUE TITLE
Playback speed control in the video player

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2190]
![image](https://user-images.githubusercontent.com/43090263/102647199-aaeb9400-4165-11eb-81d2-3b49da4e1dab.png)

**Comment by sukiletxe** [comment]
Does this apply to the audio (not voice messages) player too, or should I create another issue for this? In the audio player there is no playback speed button.

**Comment by MarcAnt01** [comment]
@sukiletxe I don't recall seeing this feature in official clients, so better to create a separated issue in case

**Comment by sukiletxe** [comment]
Seems I didn't explain myself well, I wanted #2209 fixed. If anybody wants the use case above they can report it if they want.

**Comment by MarcAnt01** [comment]
Added in https://github.com/UnigramDev/Unigram/commit/da02990e7b1b4dc15e7dda5612d509f945451d30
