### ISSUE TITLE
Video Volume Changer is faded

### ISSUE THREAD

**Issue by Jeidoz** [UnigramDev/Unigram#2193]
Yeah, I can change volume, by clicking, but it's faded and not noticeable...

![image](https://user-images.githubusercontent.com/23425714/102931670-1358af00-449f-11eb-8966-84524a9d86b3.png)

**Comment by FrayxRulez** [comment]
Duplicate of #2173
As a temporary workaround, you can disable full screen gallery from Settings > Chat settings
