### ISSUE TITLE
Add an option to enable restrictions on content

### ISSUE THREAD

**Issue by xmha97** [UnigramDev/Unigram#2199]
Hi, please add an option to enable restrictions on content. (like [NekoX](https://github.com/NekoX-Dev/NekoX))
![Nekogram](https://user-images.githubusercontent.com/23485114/103163838-9750c500-4818-11eb-82be-d0a7fb88fed7.png)

**Comment by FrayxRulez** [comment]
Sorry, but I am not going to implement this feature :/
