### ISSUE TITLE
Locking app using Windows Hello

### ISSUE THREAD

**Issue by prajjwaldimri** [UnigramDev/Unigram#220]

**Comment by prajjwaldimri** [comment]
@FrayxRulez I am going to start implementing this in my fork. Will create a pull request when done. Any rules I should keep in mind before starting?

**Comment by FrayxRulez** [comment]
Just write easily readable code, respecting spaces, indentation and so on.
When you're ready make a pull request and I'll be happy to review it :)

**Comment by prajjwaldimri** [comment]
@FrayxRulez The app is targeting 10.0.15063.0 and is not building without this SDK. However, I'm on the stable Windows 10 build (10.0.14393.0) and cannot install this SDK. Tried changing the Target version but all in vain. Any workarounds?

**Comment by FrayxRulez** [comment]
You can manually edit .csproj file, in particular this line: https://github.com/UnigramDev/Unigram/blob/development/Unigram/Unigram/Unigram.csproj#L14

**Comment by prajjwaldimri** [comment]
Yup, did that and the solution opened. However it is refusing to build. I think its because the Windows Desktop and Mobile Extensions which are targeting the insider SDK in references. Will try to remove them and add the suitable ones

**Comment by prajjwaldimri** [comment]
Alright, I updated the Windows Desktop and Mobile Extensions and the SDK problem is solved but I am still getting errors about these:
WebPImage
AnimatedImageSourceRendererFactory

VS is unable to resolve these even after package restore.

**Comment by FrayxRulez** [comment]
Contact me on Telegram @FrayxRulez
