### ISSUE TITLE
Microphone not working, but works on voice messages

### ISSUE THREAD

**Issue by Akyh** [UnigramDev/Unigram#2201]
Microphone doesnt work in voice chat but when I record one voice message then it work for only one session

2.5.2 beta

Here is video. 
https://t.me/TelegramDesktopTalk/54530

**Comment by FrayxRulez** [comment]
This is Unigram and not Telegram Desktop, the two apps aren’t related in any way to each other.

**Comment by Akyh** [comment]
Yeah, now I get it. Sorry
