### ISSUE TITLE
Admin role for anonymous admin messages

### ISSUE THREAD

**Issue by MattiaBLX** [UnigramDev/Unigram#2202]

**Comment by MarcAnt01** [comment]
Wdym? It has already been implemented
![image](https://user-images.githubusercontent.com/43090263/103350432-43581180-4aa0-11eb-84af-5a7fd8678cc7.png)

**Comment by MattiaBLX** [comment]
Fela already knows what I'm talking about

**Comment by MarcAnt01** [comment]
I think explaining the issue in a straightforward way would be helpful for the future
