### ISSUE TITLE
Cannot click appbar buttons in a on-going group call

### ISSUE THREAD

**Issue by Jack-Works** [UnigramDev/Unigram#2205]
![image](https://user-images.githubusercontent.com/5390719/103458056-6522f400-4d3f-11eb-997a-8a3915a421fb.png)

those three buttons are not clickable

**Comment by MarcAnt01** [comment]
Hello Jack, thanks for your report, but we already have a ticket to keep track of that

**Comment by MarcAnt01** [comment]
Duplicate of https://github.com/UnigramDev/Unigram/issues/2194
