### ISSUE TITLE
Number of items selected

### ISSUE THREAD

**Issue by ze0ss** [UnigramDev/Unigram#2207]
Add a feature to display number of items selected at the top right.

![Screenshot 2021-01-05 131540](https://user-images.githubusercontent.com/56572179/103620238-2a94a380-4f59-11eb-9d88-dedbffbb0c53.png)

**Comment by ze0ss** [comment]
Hey, any progress here?
It's been so long, it's a critical enhancement, and needs to be fixed/added right now.
It's very difficult for someone like me who wants to forward more than 10 messages from a channel, to another channel, it's impossible to know how many items have been selected so far once I scroll down a lot.

**Comment by FrayxRulez** [comment]
Done
