### ISSUE TITLE
Edit image option(?)

### ISSUE THREAD

**Issue by ze0ss** [UnigramDev/Unigram#2208]
There's no edit and resend images option in the context menu.

![500059200780_179212](https://user-images.githubusercontent.com/56572179/103620793-22893380-4f5a-11eb-9577-029bdceeaec1.jpg)

**Comment by FrayxRulez** [comment]
Hi @ze0ss, maybe you can provide a bit more context?

**Comment by ze0ss** [comment]
the quick image edit is a new feature [added by telegram](https://telegram.org/blog/voice-chats)

basically you can quickly re-edit and re-send the photo you or anybody else just posted.

**Comment by MarcAnt01** [comment]
Hi, it looks like it is a duplicate of #2271

**Comment by ze0ss** [comment]
@MarcAnt01 my issue was older smh

**Comment by FrayxRulez** [comment]
That’s true, @ze0ss, but Filippo’s is more straight to the point!
