### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by alopex-smartunit** [UnigramDev/Unigram#2212]
Hi! Please, help me.
While install Unigram_7.3.5945.0_x64.appxbundle on clean Windows 10 Pro 19042.685, without Windows Store, Microsoft.Dism.Commands.AddAppxProvisionedPackageCommand error was occurs.
WTF?

**Comment by MarcAnt01** [comment]
Hey, can you try to follow the procedure in the first message of mirror channel? https://t.me/unigramappx/49

**Comment by alopex-smartunit** [comment]
> Hey, can you try to follow the procedure in the first message of mirror channel? https://t.me/unigramappx/49

Hi! Thanx. But i did it.

**Comment by MarcAnt01** [comment]
Can you send a screenshot of the error, please?

**Comment by alopex-smartunit** [comment]
Of course.

![Снимок](https://user-images.githubusercontent.com/22536215/104120175-206b0e80-5378-11eb-9f4c-836ed90c959e.PNG)

**Comment by alopex-smartunit** [comment]
> add-appxprovisionedpackage : Неопознанная ошибка
> строка:1 знак:1

add-appxprovisionedpackage : Unrecovered error
string:1 char:1
