### ISSUE TITLE
Chat custom background image

### ISSUE THREAD

**Issue by kaptellyi** [UnigramDev/Unigram#2214]
After I set a custom image as background for chat, it gets replaced with dark color

**Comment by makisukurisu** [comment]
@kaptellyi Please add software info (if same do not)

Unigram 7.3 v5952 and windows 10 20H2 (maybe it's not so important)

*Side note*
Selecting picture from previous is working just fine

**Comment by kaptellyi** [comment]
I have reinstalled the app and it works fine
