### ISSUE TITLE
In-app music player has weird tooltips

### ISSUE THREAD

**Issue by cxinu** [UnigramDev/Unigram#2216]
The **volume button** says "Close audio player" 
The **reverse button** says "Shuffle" instead of reverse, see the images.
and there is no **shuffle button**.
![image_2021-01-13_07-30-37](https://user-images.githubusercontent.com/72374438/104397354-a8b50380-5572-11eb-81dc-e82990907c43.jpg)
![image_2021-01-13_07-33-38](https://user-images.githubusercontent.com/72374438/104397377-b23e6b80-5572-11eb-8f4d-bdaa02162f9b.jpg)

**Comment by MarcAnt01** [comment]
@FrayxRulez looks like there's no such string, wouldn't it be better to leave the button unlabeled at this point?

**Comment by FrayxRulez** [comment]
Volume tooltip has been fixed. Playback order one not, because Android misses that feature completely. I'm considering to remove it as well.
