### ISSUE TITLE
Master branch doesn't build, dev docs are missing details

### ISSUE THREAD

**Issue by riverar** [UnigramDev/Unigram#2217]
Attempting to build Unigram master, with TDLib 1.7.0, results in a litany of errors. There appear to be a bunch of references to a hardcoded path `C:\tgcalls`, as well as others. None of these folders are listed in [the dev docs](https://github.com/UnigramDev/Unigram/blob/develop/Documentation/Build-instructions.md).

Do you have updated guidance on building Unigram?

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0535	'MessageAlbum' does not implement interface member 'BaseObject.ToUnmanaged()'	Unigram	C:\Sources\Unigram\Unigram\Unigram\Common\TdExtensions.cs	2229	N/A
Error	CS0535	'MessageChatEvent' does not implement interface member 'BaseObject.ToUnmanaged()'	Unigram	C:\Sources\Unigram\Unigram\Unigram\Common\TdExtensions.cs	2345	N/A
Error	CS0535	'MessageHeaderDate' does not implement interface member 'BaseObject.ToUnmanaged()'	Unigram	C:\Sources\Unigram\Unigram\Unigram\Common\TdExtensions.cs	2376	N/A
Error	CS0535	'MessageHeaderUnread' does not implement interface member 'BaseObject.ToUnmanaged()'	Unigram	C:\Sources\Unigram\Unigram\Unigram\Common\TdExtensions.cs	2380	N/A
Error	C1083	Cannot open source file: 'C:\tgcalls\tgcalls\CodecSelectHelper.cpp': No such file or directory	Unigram.Native.Calls	C:\Sources\Unigram\Unigram\Unigram.Native.Calls\c1xx	1	
Error	C1083	Cannot open source file: 'C:\tgcalls\tgcalls\CryptoHelper.cpp': No such file or directory	Unigram.Native.Calls	C:\Sources\Unigram\Unigram\Unigram.Native.Calls\c1xx	1	
Error	C1083	Cannot open source file: 'C:\tgcalls\tgcalls\EncryptedConnection.cpp': No such file or directory	Unigram.Native.Calls	C:\Sources\Unigram\Unigram\Unigram.Native.Calls\c1xx	1	
Error	C1083	Cannot open source file: 'C:\tgcalls\tgcalls\Instance.cpp': No such file or directory	Unigram.Native.Calls	C:\Sources\Unigram\Unigram\Unigram.Native.Calls\c1xx	1	
Error	C1083	Cannot open source file: 'C:\tgcalls\tgcalls\InstanceImpl.cpp': No such file or directory	Unigram.Native.Calls	C:\Sources\Unigram\Unigram\Unigram.Native.Calls\c1xx	1	
Error	C1083	Cannot open source file: 'C:\tgcalls\tgcalls\LogSinkImpl.cpp': No such file or directory	Unigram.Native.Calls	C:\Sources\Unigram\Unigram\Unigram.Native.Calls\c1xx	1	
Error	C1083	Cannot open source file: 'C:\tgcalls\tgcalls\Manager.cpp': No such file or directory	Unigram.Native.Calls	C:\Sources\Unigram\Unigram\Unigram.Native.Calls\c1xx	1	
Error	C1083	Cannot open source file: 'C:\tgcalls\tgcalls\MediaManager.cpp': No such file or directory	Unigram.Native.Calls	C:\Sources\Unigram\Unigram\Unigram.Native.Calls\c1xx	1	
Error	C1083	Cannot open source file: 'C:\tgcalls\tgcalls\Message.cpp': No such file or directory	Unigram.Native.Calls	C:\Sources\Unigram\Unigram\Unigram.Native.Calls\c1xx	1	
Error	C1083	Cannot open source file: 'C:\tgcalls\tgcalls\NetworkManager.cpp': No such file or directory	Unigram.Native.Calls	C:\Sources\Unigram\Unigram\Unigram.Native.Calls\c1xx	1	
Error	C1083	Cannot open source file: 'C:\tgcalls\tgcalls\platform\tdesktop\DesktopInterface.cpp': No such file or directory	Unigram.Native.Calls	C:\Sources\Unigram\Unigram\Unigram.Native.Calls\c1xx	1	
Error	C1083	Cannot open source file: 'C:\tgcalls\tgcalls\platform\tdesktop\VideoCameraCapturer.cpp': No such file or directory	Unigram.Native.Calls	C:\Sources\Unigram\Unigram\Unigram.Native.Calls\c1xx	1	
Error	C1083	Cannot open source file: 'C:\tgcalls\tgcalls\platform\tdesktop\VideoCapturerInterfaceImpl.cpp': No such file or directory	Unigram.Native.Calls	C:\Sources\Unigram\Unigram\Unigram.Native.Calls\c1xx	1	
Error	C1083	Cannot open source file: 'C:\tgcalls\tgcalls\platform\tdesktop\VideoCapturerTrackSource.cpp': No such file or directory	Unigram.Native.Calls	C:\Sources\Unigram\Unigram\Unigram.Native.Calls\c1xx	1	
Error	C1083	Cannot open source file: 'C:\tgcalls\tgcalls\reference\InstanceImplReference.cpp': No such file or directory	Unigram.Native.Calls	C:\Sources\Unigram\Unigram\Unigram.Native.Calls\c1xx	1	
Error	C1083	Cannot open source file: 'C:\tgcalls\tgcalls\ThreadLocalObject.cpp': No such file or directory	Unigram.Native.Calls	C:\Sources\Unigram\Unigram\Unigram.Native.Calls\c1xx	1	
Error	C1083	Cannot open source file: 'C:\tgcalls\tgcalls\VideoCaptureInterface.cpp': No such file or directory	Unigram.Native.Calls	C:\Sources\Unigram\Unigram\Unigram.Native.Calls\c1xx	1	
Error	C1083	Cannot open source file: 'C:\tgcalls\tgcalls\VideoCaptureInterfaceImpl.cpp': No such file or directory	Unigram.Native.Calls	C:\Sources\Unigram\Unigram\Unigram.Native.Calls\c1xx	1	
Error		The "CompileXaml" task returned false but did not log an error.	Unigram	C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets	486	
Error	MSB4181	The "CompileXaml" task returned false but did not log an error.	Unigram.Native.Calls	C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets	486	
Error	CS0246	The type or namespace name 'MessageLiveLocationApproached' could not be found (are you missing a using directive or an assembly reference?)	Unigram	C:\Sources\Unigram\Unigram\Unigram\Controls\Messages\MessageService.cs	799	N/A
Error	CS0246	The type or namespace name 'StatisticsGraph' could not be found (are you missing a using directive or an assembly reference?)	Unigram	C:\Sources\Unigram\Unigram\Unigram\ViewModels\Chats\ChatStatisticsViewModel.cs	247	N/A
Error	CS0246	The type or namespace name 'StatisticsValue' could not be found (are you missing a using directive or an assembly reference?)	Unigram	C:\Sources\Unigram\Unigram\Unigram\Controls\ChatStatisticsOverview.xaml.cs	21	N/A
Error	CS0246	The type or namespace name 'StatisticsValue' could not be found (are you missing a using directive or an assembly reference?)	Unigram	C:\Sources\Unigram\Unigram\Unigram\Controls\ChatStatisticsOverview.xaml.cs	22	N/A
Error	CS0246	The type or namespace name 'StatisticsValue' could not be found (are you missing a using directive or an assembly reference?)	Unigram	C:\Sources\Unigram\Unigram\Unigram\Controls\ChatStatisticsOverview.xaml.cs	28	N/A
```

**Comment by FrayxRulez** [comment]
👋 you should use develop branch.
You should have WebRTC (m84) in C:\webrtc: https://github.com/microsoft/winrtc/tree/master/patches_for_WebRTC_org/m84
You should have tgcalls in C:\tgcalls: https://github.com/TelegramMessenger/tgcalls

Second repository requires some patches to be built, but I'm sure you can figure out yourself.

**Comment by riverar** [comment]
Develop branch doesn't build properly either
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MIDL2011	[msg]unresolved type declaration [context]: Telegram.Td.Api.GroupCallPayload [ Parameter 'payload' of Procedure 'Invoke' ( Delegate 'Unigram.Native.Calls.EmitJsonPayloadDelegate' ) ]	Unigram.Native.Calls	C:\Sources\Unigram\Unigram\Unigram.Native.Calls\VoipGroupManager.idl	5	
Error	MIDL2011	[msg]unresolved type declaration [context]: Telegram.Td.Api.GroupCallJoinResponse [ Parameter 'payload' of Procedure 'SetJoinResponsePayload' ( RuntimeClass 'Unigram.Native.Calls.VoipGroupManager' ) ]	Unigram.Native.Calls	C:\Sources\Unigram\Unigram\Unigram.Native.Calls\VoipGroupManager.idl	13	
Error		The "CompileXaml" task returned false but did not log an error.	Unigram	C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets	486	
Error	CS0006	Metadata file 'C:\Sources\Unigram\Unigram\x64\Debug\Unigram.Native.Calls\Unigram.Native.Calls.winmd' could not be found	Unigram	C:\Sources\Unigram\Unigram\Unigram\CSC	1	N/A
Error		Cannot resolve Assembly or Windows Metadata file 'C:\Sources\Unigram\Unigram\x64\Debug\Unigram.Native.Calls\Unigram.Native.Calls.winmd'	Unigram	C:\Sources\Unigram\Unigram\Unigram\Unigram.csproj		
```

Will investigate the other deps you just listed, thanks!

**Comment by forconz** [comment]
@FrayxRulez Second repository requires some patches to be built,  But how to do?

I am C#/React full-stack programmer, but poor C/C++.

**Comment by Yeldece** [comment]
What's the status, could you guys made it to work? I learned syntax of the c# to improve my programming skills and may be some improvements to this program, but i couldn't build it either.

**Comment by hpxiong** [comment]
@FrayxRulez can you please provide some guidance on how to patch tgcalls? The patched webrtc UWP repo has too many mismatches with tgcalls.

**Comment by FrayxRulez** [comment]
You don't need to patch it, just use `FrayxRulez/webrtc-uwp`, branch `m91`

**Comment by FrayxRulez** [comment]
Still, apart from patching part build instructions are the same as the official one

**Comment by IgorTheLight** [comment]
Unigram is a royal pain in the ass to build right now!
I wasted a few hours and it's still "almost working".
It's ok to build TDLib, but there are also a few non-documented libraries + patches to deal with... Too many places for something to brake.

**Comment by gus33000** [comment]
Managed to build Unigram today.

Some quick notes but nothing too concrete yet

- First of all current commit uses a private tdlib version, so I cherry picked commit [9ca612bc66c4e909cd92278d47517e7df9ea7758](https://github.com/UnigramDev/Unigram/tree/9ca612bc66c4e909cd92278d47517e7df9ea7758)
- Build tdlib for C#/UWP using the tdlib build instruction generator available here: https://tdlib.github.io/td/build.html
- Install resulting ```tdlib.vsix``` (note: this won't build you an arm64 compile as well, needs manual edits on the build script inside ```examples\uwp```)
- Clone the following commit for tgcalls under c:\tgcalls: https://github.com/TelegramMessenger/tgcalls/tree/f76a9290fa502a8df473dd872aedf9a553b089cc
- Clone ```https://github.com/FrayxRulez/winrtc.git``` under ```c:\winrtc```
- Setup WinRTC ver by running ```c:\winrtc\.pipelines\restore-acquiring_code.cmd``` (needs VS-2019 installed first)
- Delete ```c:\webrtc\src```
- Delete ```c:\webrtc\.gclient_entries```
- Edit ```c:\webrtc\.gclient``` to point to ```https://github.com/FrayxRulez/webrtc-uwp.git``` instead
- Clone ```https://github.com/FrayxRulez/webrtc-uwp.git``` under ```c:\webrtc\src```
- Checkout ```origin/m91``` branch
- Run gclient sync -D -R origin/m91
- The following part is important because we need some patches to submodules that gclient download
- Patch c:\winrtc\.pipelines\restore-applying_patches.cmd to not bail out on any failing command (this is easier this way, but you can alternatively only keep the patches for third_party libraries)
- Run ```c:\winrtc\.pipelines\restore-applying_patches.cmd```
- Now you're ready to build webrtc, run ```c:\winrtc\.pipelines\build.cmd```
- Once built, inside the unigram cloned repository, create ```\unigram\unigram\unigram\Constants.Secret.cs```
- Fill it in like so:


```csharp
namespace Unigram
{
    public static partial class Constants
    {
		static Constants()
		{
			Constants.ApiId = <your api id>;
			Constants.ApiHash = "<your api hash>";
			Constants.AppChannel = "<the user handle @ of a channel you will create, this hosts emojis app update packages etc>";
			Constants.AppCenterId = "<an optional appcenter id, from appcenter.ms, can be left blank>";
		}
	}
}
```

- Setup two environment variables on your machine:

```
    <WebRTC_Root>C:\webrtc\src</WebRTC_Root>
    <WebRTC_Output>C:\webrtc\src\out\msvc\uwp</WebRTC_Output>
```

- Open ```Unigram.sln```
- Switch the solution to ```Release/x64```
- First, attempt to build the ```Unigram.Native.Calls``` project, if you get failures, make sure you cloned under ```c:\tgcalls``` and ```c:\webrtc```.
- You might need openssl binaries in the path, you'll need to place include files under ```c:\tgcalls\tgcalls\openssl``` (use openssl ```1.1.1```, not 3.0.0 or higher)
- The following is to make building quicker down the line:
- Open ```Unigram.csproj``` once ```Unigram.Native.Calls``` is built
- Uncomment the following block:

```
  <ItemGroup>
    <Reference Include="Unigram.Native.Calls">
      <HintPath>$(SolutionDir)\Unigram.Native.Calls\$(Platform)\Unigram.Native.Calls.winmd</HintPath>
      <Implementation>Unigram.Native.Calls.dll</Implementation>
    </Reference>
    <ReferenceCopyLocalPaths Include="$(SolutionDir)\Unigram.Native.Calls\$(Platform)\Unigram.Native.Calls.dll" />
    <ReferenceCopyLocalPaths Include="$(SolutionDir)\Unigram.Native.Calls\$(Platform)\Unigram.Native.Calls.pri" />
  </ItemGroup>
```

- And comment the following one:

```
    <!--<ProjectReference Include="..\Unigram.Native.Calls\Unigram.Native.Calls.vcxproj">
      <Project>{fdd3c45d-4cff-4a90-8fef-16ca70ab00be}</Project>
      <Name>Unigram.Native.Calls</Name>
    </ProjectReference>-->
```

- Place built artifacts for ```Unigram.Native.Calls``` under ```$(SolutionDir)\Unigram.Native.Calls\$(Platform)``` so it matches the csproj
- Build Unigram

if everything goes well, you should end up here:

![image](https://user-images.githubusercontent.com/3755345/144727086-22beb795-5023-452b-8574-5df3a6cd581b.png)


Author note: __this might be different from how the app is built by the developer, and might be missing a few things, but this is the general idea/notes I took while doing this, I might try doing a more detailed, completed, and checked step by step guide later on, but hopefully this already helps you.__

**Comment by IgorTheLight** [comment]
Holy shit!
Thank you SO much!
I didn't tried that myself yet but this looks much more detailed. Still fiddly tho, but that's not your fault ;-)

**Comment by gus33000** [comment]
I have provided more details on how to build WebRTC here: https://gist.github.com/gus33000/7a7f310528082d5b7ba555fed6379e03

x86 UWP target still has some issue but x64 and arm64 are fine

**Comment by FrayxRulez** [comment]
Wow @gus33000 thanks a lot. I'll add this to the Readme. I actually made a nuget package for the webrtc fork used by Unigram, for now just x64: Unigram.WebRTC.x64.

**Comment by FrayxRulez** [comment]
Develop branch won't build because it's using a not yet public version of TDLib.

**Comment by gus33000** [comment]
> Wow @gus33000 thanks a lot. I'll add this to the Readme. I actually made a nuget package for the webrtc fork used by Unigram, for now just x64: Unigram.WebRTC.x64.

You're welcome! Figured out the issue with x86 for WebRTC so it should be fine now. Hope it helps others willing to build the app. I'm just wondering if the tgcalls commit I picked is the right one given I had to do some tiny modifications too last night (going to try again today, but just wanting to be sure)

**Comment by gus33000** [comment]
Updated the instructions with guidance on how to use your own built nuget package for WebRTC and enable ARM64/x86 Release compiles of Unigram.Native.Calls, should now be complete.

![image](https://user-images.githubusercontent.com/3755345/144759537-d30bc1e2-064e-4e2c-aeec-d302406ab0c0.png)

**Comment by IgorTheLight** [comment]
@gus33000 you are our hero!
@FrayxRulez you are also a hero (being a main developer and all...) but we definitely need a better building instructions. For now you more like a villain who created his Doomsday Device :-)

**Comment by gus33000** [comment]
TdLib finally updated so I think you should be able to build the latest source now. Haven't tested yet, but ignore the cherry picked commit hash for unigram only (keep cherry picking tgcalls commit hash).

**Comment by FrayxRulez** [comment]
@gus33000 can you make a PR adding the build instructions to the docs?

**Comment by FrayxRulez** [comment]
> I think you should consider improving the build situation before documenting this. Opening up project files, commenting lines out, and manually creating sources is ridiculous. 🤡

I don't care about other people being able to build the project. Code-related PRs are not welcome.

**Comment by riverar** [comment]
Then why would anyone care to submit a PR? You are terrible.

**Comment by FrayxRulez** [comment]
Additionally, I'm not sure that it's my fault if UWP environment sucks and you can't find common libraries such as WebRTC ready to be built or even pre-built?
Unigram can be easily built if everything is in place, still dependencies are not my responsibility.

**Comment by gus33000** [comment]
What work though? There's no work done by anyone currently on build documentation, and I do agree with @riverar that there should be ways to make it better (for a start, the c:\tgcalls folder being hardcoded is in unigram project, not in a dependency). Same for WebRTC. Also how do we know things didn't change again?

**Comment by Aquathing** [comment]
> What work though? There's no work done by anyone currently on build documentation
The clown emojis in unrespectful towards the entire projects, not just missing build instructions.

> and I do agree with @riverar that there should be ways to make it better
And I agree that build instructions would be cool, but using clown emojis and pretending them is wrong.

> Also how do we know things didn't change again?
If they change, they can be updated.

The thing here is that you all somehow feel entitled to request things as if you paid for Unigram

**Comment by gus33000** [comment]
> > What work though? There's no work done by anyone currently on build documentation
> 
> The clown emojis in unrespectful towards the entire projects, not just missing build instructions.
> 
> > and I do agree with @riverar that there should be ways to make it better
> 
> And I agree that build instructions would be cool, but using clown emojis and pretending them is wrong.
> 
> > Also how do we know things didn't change again?
> 
> If they change, they can be updated.
> 
> The thing here is that you all somehow feel entitled to request things as if you paid for Unigram

My message made no reference to the clown emojis, and I do not intend to comment on this issue, as it is irrelevant to our goals. You're free to discuss this with the concerned parties, but I'm not, and to me it looks like you just want to fuel fire here. It's just an unicode character.

I was requested to make a PR to provide build instructions, something I would happily do, but this would take me an entire weekend to recheck that everything works the way it already did, and making build instructions requiring to modify system files is ridiculous just to adapt to hardcoded paths that are once again present in the unigram repository itself, and none of the dependencies. Making build instructions involving what is commonly called hacks is not adequate, and would not match the project quality that everyone expects here.

I'm the one that made above's instructions in the first place, I have not said I would not do them, but I would kindly request that the hardcoded paths get resolved so we can make a pull request with the quality you expect from such a large scale project.

**Comment by FrayxRulez** [comment]
@gus33000 Modify system files? 🤨
The project is rebuildable, as you did rebuild it yourself.

**Comment by gus33000** [comment]
> @gus33000 Modify system files? 🤨 The project is rebuildable, as you did rebuild it yourself.

The GPLv3 license requires people to be able to rebuild the project and obtain identical binaries, we cannot be sure at this stage that the binaries we build ourselves match the binaries you build yourself, and that's a big problem

**Comment by FrayxRulez** [comment]
@gus33000 Report me to the authorities then

**Comment by gus33000** [comment]
> @gus33000 Report me to the authorities then

Not question of that, I do want to help by providing instructions to fix that issue, but I would love it if you could help us by just removing the hardcoded paths and making them relative to the project root...

**Comment by FrayxRulez** [comment]
@gus33000 Is it really needed? The problem with tgcalls is that the repository is private so I can’t add it as a submodule.

**Comment by gus33000** [comment]
Yes, because TGCalls is LGPL3, which requires to disclose source as well... https://github.com/TelegramMessenger/tgcalls/blob/master/LICENSE

**Comment by gus33000** [comment]
Thanks a lot for the submodule <3 Will try to do a PR tomorrow

**Comment by gus33000** [comment]
I tried building Unigram numerous times since my previous comment unfortunately the Unigram.Native project now depends on libraries that are not referenced in the repository as submodules, and seems to depend on a vcpkg configuration missing from my machine. I appreciate all submobules for various libraries being here but some libraries like zlib or ffmpeg are completely missing from the tree and simply adding them in folders under the library directory isn't enough to make the build succeed. Is there any tip/guidance/help that could be given here? Note: my list is non exhaustive there's more missing. I should also note a lottie animation cs file is entirely missing from the main app UWP project.

**Comment by AiseKaise** [comment]
@gus33000 🤔
