### ISSUE TITLE
Discuss button is visible also for channels without discuss group (channel info)

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2221]

**Comment by FrayxRulez** [comment]
Where?

**Comment by MarcAnt01** [comment]
![image](https://user-images.githubusercontent.com/43090263/104960196-0d89b700-59d4-11eb-8508-02ae1634fa76.png)

**Comment by FrayxRulez** [comment]
That opens the channel actually and it has always been there
