### ISSUE TITLE
Feature request : A way to disable autocorrect

### ISSUE THREAD

**Issue by abhitrueprogrammer** [UnigramDev/Unigram#2224]
Currently the autocorrect feature is quite nagging though nifty. I want an option to disable it so that my spelling mistakes are highlighted(red underline under incorrect text) instead of being automatically changed.

**Comment by makisukurisu** [comment]
@FrayxRulez , can you assign feature request label and close #2225 as duplicate of that issue?

**Comment by abhitrueprogrammer** [comment]
> 
> 
> @FrayxRulez , can you assign feature request label and close #2225 as duplicate of that issue?

Yeah sorry, I just edited the title such that "feature request" is removed from the title, to adhere to the guidelines, didn't knew it would open a new issue instead....

**Comment by FrayxRulez** [comment]
I think it makes more sense if you disable this option in your system directly.
Unigram already offers "Disable misspelled words highlight" option and it feels much redundant enough, I don't want to add one more, especially as they would be both _Disable_ and not _Enable_.
