### ISSUE TITLE
Any way to run it on Linux?

### ISSUE THREAD

**Issue by pgenderson** [UnigramDev/Unigram#2234]
Cutegram seems dead and I'd like to use Telegram with secret chats on desktop.

**Comment by makisukurisu** [comment]
Not possible, AFAIK.

**Comment by MarcAnt01** [comment]
We are sorry, but Unigram is build on top of UWP that supports only Windows 10

**Comment by arv69** [comment]
please make it for linux i only using windows because of unigram whenever you made it for linux i will shift to linux 
how much time i should expect

**Comment by dongle-the-gadget** [comment]
Never, or until further notice.

**Comment by arv69** [comment]
waiting for kali liux please make it availble  for liux fast

**Comment by mujeebcpy** [comment]
making an opensource client. which will not work in an open source Os. so sad :disappointed:

**Comment by FrayxRulez** [comment]
@mujeebcpy Microsoft recently open sourced WinUI 3 under a quite permissive license, so there are some chances that someone will port it to Linux.
