### ISSUE TITLE
use sonic for speedup voice messages

### ISSUE THREAD

**Issue by beqabeqa473** [UnigramDev/Unigram#2235]
hello.

i think it would be better to use sonic for speed up speech in voice messages.

as i heared, sonic is the best library in open source world which increases speed with minimal glitches.

sonic is at
https://github.com/waywardgeek/sonic

**Comment by FrayxRulez** [comment]
I've rolled back changes to voice messages playback in this commit: 1dd354eb
2x speed quality should be way better now.

**Comment by beqabeqa473** [comment]
Yes, i understand, but sonic itself has the best quality on high
speeds, and it is not too difficult to implement.
so, if you will have enough time, it will be great if you will look at it.

On 4/5/21, Fela Ameghino ***@***.***> wrote:
> I've rolled back changes to voice messages playback in this commit:
> 1dd354eb
> 2x speed quality should be way better now.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/UnigramDev/Unigram/issues/2235#issuecomment-813241344


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by FrayxRulez** [comment]
It is actually difficult to implement, because the whole context should aware of the playback speed, it's not just about applying the transformation to the audio.
