### ISSUE TITLE
"is speaking" indicator in group calls is inaccurate

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2240]
I often happen to see that no-one is talking from the members list, but there is one person or more people talking in that moment.

**Comment by FrayxRulez** [comment]
https://github.com/TelegramMessenger/tgcalls

**Comment by MarcAnt01** [comment]
@FrayxRulez not really, since from my iPhone there is no such problem 🤷

**Comment by ADeltaX** [comment]
I have the same issue, sometimes I see switching text very very fast from "listening" to "speaking"

**Comment by FrayxRulez** [comment]
> I have the same issue, sometimes I see switching text very very fast from "listening" to "speaking"

https://github.com/TelegramMessenger/tgcalls

**Comment by MarcAnt01** [comment]
It's working even on Telegram Desktop, so it's Unigram fault

**Comment by FrayxRulez** [comment]
You’re so annoying
