### ISSUE TITLE
Schedule multiple messages at each last one's scheduled day & time

### ISSUE THREAD

**Issue by KeronCyst** [UnigramDev/Unigram#2244]
Unigram 7.3 (5951) X64 on Windows 10 Home 20H2:

1. Schedule a message for a future time.
2. Open the calendar icon for scheduled messages, type up another scheduled message, and hit Enter.

* Expected result: the time setting box that shows up for this latest scheduled message prefills at whatever-the-scheduled-time-is for the most recent scheduled message above, in this calendar-icon view.
* Actual result: the time setting box that shows up for this latest scheduled message prefills at the current, immediate time (even when the queued messages are set for later).

**Comment by makisukurisu** [comment]
@KeronCyst

**Comment by makisukurisu** [comment]
@KeronCyst

**Comment by KeronCyst** [comment]
@makisukurisu did you comment on the wrong issue? It sounds completely off-topic. My issue has nothing to do with images, but rather scheduled messages of only text (at least, that's what I have in mind).
