### ISSUE TITLE
Audio playback bar shows wrong text tooltip when mousing over volume icon

### ISSUE THREAD

**Issue by KeronCyst** [UnigramDev/Unigram#2246]
Unigram 7.3 (5951) X64 on Windows 10 Home 20H2:

It says "Close audio player" instead of "Volume":

![image](https://user-images.githubusercontent.com/13827055/108529940-e1d74680-7289-11eb-8ef7-4482adbed4f5.png)

**Comment by makisukurisu** [comment]
A duplicate of #2216 (which also has a bit more misnomers)

**Comment by KeronCyst** [comment]
Oops, I had tried searching but didn't see that one! Thanks.
