### ISSUE TITLE
Mac Support

### ISSUE THREAD

**Issue by ogomez92** [UnigramDev/Unigram#2248]
Hello,
aRe there any plans for mac support?
as it stands there are no accessible clients for Mac at this time. I'm a mac developer and I would be willing to take a stab at it, have you guys ever tried?

**Comment by makisukurisu** [comment]
Probably not. Simply because Unigram is UWP app at the moment.

Only and when Microsoft will make UWP available for other platforms it will be possible.

**Comment by MarcAnt01** [comment]
> Hello,
> aRe there any plans for mac support?
> as it stands there are no accessible clients for Mac at this time. I'm a mac developer and I would be willing to take a stab at it, have you guys ever tried?

Hello, uwp (the framework Unigram is build onto) is limited to Windows 10, so there's no way to get it on Mac, we're sorry.
