### ISSUE TITLE
Unable to confirm entering the security code

### ISSUE THREAD

**Issue by Alaknar** [UnigramDev/Unigram#225]
After entering my country + phone number I get to the "Your code" screen. I paste in the code, press "Next" and nothing happens". Pressing [Enter] also doesn't provoke any reaction.

I then tried typing the code manually instead of copy-pasting it from Skype and noticed that right after typing the last digit the "Next" button blinks for a moment.

The "Next button is blue and "clickable" all the time, regardless of the code presence in the text field.

**Comment by FrayxRulez** [comment]
You might want to contact me on Telegram? @FrayxRulez

**Comment by Alaknar** [comment]
How? I can't set up an account. :) I won't be able to talk via the browser interface today.

Just tested setting it up on my mobile and I'm getting "408; MTProtoService: operation timed out (25s)" error.

**Comment by FrayxRulez** [comment]
Ah! That's explain everything. You must be already registered to use Unigram.

**Comment by larsschellhas** [comment]
If this doesn´t solve your Problem, feel free to reopen this issue.

**Comment by Alaknar** [comment]
Confirmed that all works fine.

I'd suggest adding a prompt for the user saying that they need to log in on Telegram's website first.

**Comment by FrayxRulez** [comment]
We're working on registration functionality (already available through the sources) that will be included starting from the next versions

**Comment by FrayxRulez** [comment]
Hi, I confirm you that the problem that was causing 408 error is solved server side
