### ISSUE TITLE
excessive CPU while recording voice message

### ISSUE THREAD

**Issue by valiant8086** [UnigramDev/Unigram#2250]
7.3.0.5951 when I press ctrl+r and begin recording a voice message, CPU jumps by more than 10 percent, and if the message goes on long enough for the battery meter to update, battery runtime is cut pretty much in half on a laptop. This is more than I expect from other similar programs. I don't know if there's a limitation with UWP causing this, but Skype UWP used to not use this much when in a call. Unigram also uses more than expected when in a voice chat even with just one other person.

Do we have a chance to improve this?

**Comment by makisukurisu** [comment]
I think this has something to do with animated circles around record button.
In background (record keeps on) usage reduces to sub 1% for me.

Try going to dev settings menu (click on version number multiple times) and switch off Bubble animations. Which is, oh... Not doing what I expected. (@FrayxRulez , what should it do?)

Well back to original Idea - collapse recording window and (if needed) open another window using shift+click on chat you need. This way you will have both (slightly, for me about 50%) CPU usage reduced and Unigram opened in front of your eyes.

Hope this helps.

**Comment by FrayxRulez** [comment]
@makisukurisu - minimizing the app prevents the app from recording, but not from drawing the bubble (that's still GPU accelerated, and consequently should have no impact on your CPU).

**Comment by FrayxRulez** [comment]
This is likely fixed by https://github.com/UnigramDev/Unigram/commit/593e3e9e7593e360717e3807df0eab4efcdc2c2f
