### ISSUE TITLE
The list of group call participants suddenly disappears after some minutes of call

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2251]
![image](https://user-images.githubusercontent.com/43090263/108593049-a31cbb80-7371-11eb-89ac-cd6a9cdcb0e6.png)

**Comment by FrayxRulez** [comment]
Is it still the case?

**Comment by MarcAnt01** [comment]
I'm sorry @FrayxRulez, but I haven't had the chance to test this feature from some weeks
