### ISSUE TITLE
When a new user appears in the voice call after some minutes I cannot hear him but other users do

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2252]

**Comment by valiant8086** [comment]
Check if the "new users can speak" option is enabled. It's under a button when you're in the voice chat and I think you have to be the owner of the group to change it. Otherwise, someone with sufficient powers can manually unmute them theoretically

**Comment by MarcAnt01** [comment]
> Check if the "new users can speak" option is enabled. It's under a button when you're in the voice chat and I think you have to be the owner of the group to change it. Otherwise, someone with sufficient powers can manually unmute them theoretically

If other call participants can call them, it doesn't depend on that

**Comment by agasoft** [comment]
I have the same issue.
For example, 10 people is  on voice chat.
However, I can here just specific batch. Sometimes 5, sometimes less. But If  someone using Unigram too, they will here selective people as well.
From phone Telegram app everything is working great.

**Comment by MarcAnt01** [comment]
The bug is still here and prevents to use voice calls, since the user would have to join and leave continuously

**Comment by MarcAnt01** [comment]
@agasoft we are trying to reproduce the issue, but without success any longer. Do you have some precise step in order to reproduce that to be sure it's fixed?

**Comment by MarcAnt01** [comment]
I'm pretty sure it was fixed at a certain point
