### ISSUE TITLE
How to install themes from Telegram Desktop

### ISSUE THREAD

**Issue by weeebdev** [UnigramDev/Unigram#2253]
It seems to me that I cannot install `tdesktop-theme` extension file from unigram. Is it even possible? Will you add compatibility?
Is there a channel or something with Unigram themes?

**Comment by BoolCube** [comment]
@weeebdev Unigram has a separate theme extension which is unigram-theme
And yes, there is a channel for Unigram themes: https://t.me/DMJ_UnigramThemes

**Comment by weeebdev** [comment]
> @weeebdev Unigram has a separate theme extension which is unigram-theme
> And yes, there is a channel for Unigram themes: https://t.me/DMJ_UnigramThemes

I found this, but unfortunately, there are only a few themes. Is it possible to port themes from Telegram Desktop?

**Comment by BoolCube** [comment]
@weeebdev You can always create your own themes

**Comment by MarcAnt01** [comment]
Hello, as @BoolCube if the available themes are not enough for you, you could consider making your own theme
