### ISSUE TITLE
After pushing any button Unigram returns to initial screen

### ISSUE THREAD

**Issue by strigov** [UnigramDev/Unigram#2254]
I'm experiencing an issiue when I click on any chat or menu that chat or menu opens for a few milliseconds and than returns to initial screen. I tried to reinstall the app and to install beta - same thing, now I can't even go firther "Start messaginf" screen. It looks like the issue started somewhere after I've downloaded and started to use official portable Telegram app, but deletion of it didn't help. Actually I haven't this issue on another PC with Win10. What could be the root of the problem?

**Comment by MarcAnt01** [comment]
Could you include your Windows 10 version? Anyway, I'm afraid that's something broken at system level, but it could also be just an old Windows 10 version

**Comment by FrayxRulez** [comment]
You might want to enable logs ([as mentioned here](https://github.com/UnigramDev/Unigram/blob/develop/Documentation/TDLib-logs.md)) and send them to at tdlib_bot on Telegram.
Make sure to link this issue as well. Thanks!

**Comment by strigov** [comment]
> Could you include your Windows 10 version? Anyway, I'm afraid that's something broken at system level, but it could also be just an old Windows 10 version

Выпуск	Windows 10 Pro
Версия	20H2
Дата установки	‎16.‎08.‎2020
Сборка ОС	19042.804
Взаимодействие	Windows Feature Experience Pack 120.2212.551.0

Last updates. And, in fact, the version is the same as an my 2nd PC.

**Comment by strigov** [comment]
> You might want to enable logs ([as mentioned here](https://github.com/UnigramDev/Unigram/blob/develop/Documentation/TDLib-logs.md)) and send them to at tdlib_bot on Telegram.
> Make sure to link this issue as well. Thanks!

The problem is I can't enter Diagnostic Menu 'cause I can't click the app version 10 times - app version is on the next to "Sart messaging" screen which I cannot reach(

**Comment by FrayxRulez** [comment]
Hey @strigov, sorry for the late reply. If you still have the issue, can you reach me on Telegram? Same username as here.

**Comment by strigov** [comment]
I've checked on previous week, problem is somehow solved. Maybe because of Windows and app updates.
