### ISSUE TITLE
When the formatting bar is visible, the attach button leaves a padding on the left.

### ISSUE THREAD

**Issue by eyuelz** [UnigramDev/Unigram#2255]
![image](https://user-images.githubusercontent.com/31063440/108736398-a0bd8b80-7542-11eb-92be-6d31de4778e3.png)

**Comment by FrayxRulez** [comment]
You are right, however reflowing the content would be pretty complex and I don't know how to deal with that.

**Comment by FrayxRulez** [comment]
Formatting bar is gone. Long live the formatting bar.
