### ISSUE TITLE
Voice recording may require additional codecs

### ISSUE THREAD

**Issue by pbsinnett** [UnigramDev/Unigram#2256]
Hi,

I was unable to record voice notes with Unigram until I installed the K-Lite Mega Codec Pack. Is there a way to add the necessary codecs, or direct the user to a download of just the ones needed when attempting to record for the first time? At first I didn't know why I was unable to record, but then I thought of trying to install K-Lite which seemed to have worked. I also just upgraded to 21H1, so I will have to do some further research to see what the exact solution is. If I figure it out before someone else, I will comment here.

**Comment by cewbdex** [comment]
Hello, do you have those installed?
![image](https://user-images.githubusercontent.com/9021297/111113163-aa467c00-8561-11eb-9962-f95133221cc2.png)

**Comment by FrayxRulez** [comment]
Recording voice notes shouldn't require any additional codec, as it's built-in in the app - Just playing them might require some.
