### ISSUE TITLE
webp images are presented as stickers when uploading as an image

### ISSUE THREAD

**Issue by stuarttempleton** [UnigramDev/Unigram#2258]
webp images are presented as stickers, even when they aren't used as stickers. Even the notification says they're stickers. 

I'm seeing this behavior on Unigram 7.3 (5951).

**Comment by makisukurisu** [comment]
![Unigram webp send](https://user-images.githubusercontent.com/49622129/109332090-54d25580-7866-11eb-906f-bfc80b6f497a.png)
![Telegam desktop webp send](https://user-images.githubusercontent.com/49622129/109332302-9400a680-7866-11eb-84da-45c1eee828f0.png)

As far as I can see - Uni and TD*** treats all webp images as stickers (and sends them accordingly). You can save it though (Right click - save as).
