### ISSUE TITLE
Cannot forward messages silently / on a schedule

### ISSUE THREAD

**Issue by KeronCyst** [UnigramDev/Unigram#2263]
Running:
Windows 10 20H2 (build 19042.844)
Unigram 7.5 (5961) X64

I don't actually know if this is possible even in the base Telegram desktop platform, but it'd be awesome to be able to forward messages silently or set them for forwarding at a future time/when the recipient comes online!

If this is already possible to do, I'd greatly appreciate a step-by-step tutorial, because I can't seem to figure out how to do it. Thanks in advance!

**Comment by MarcAnt01** [comment]
Hi, thanks for reporting, we already have an old ticket to keep track of that

**Comment by MarcAnt01** [comment]
Duplicate of https://github.com/UnigramDev/Unigram/issues/1858

**Comment by KeronCyst** [comment]
Sorry, I tried searching but couldn't find that one! Glad to know it's in the works.
