### ISSUE TITLE
Unigram muted all of my chats

### ISSUE THREAD

**Issue by Amirhossein10** [UnigramDev/Unigram#2267]
Hello
I downloaded and installed Unigram on Windows, but Unigram muted all of my chats. how can I unmute muted chats automatically?

**Comment by FrayxRulez** [comment]
Unigram didn’t automatically mute any of your chats: you muted them by playing around with notification settings.

**Comment by FrayxRulez** [comment]
(You should be able to unmute all of them by re-enabling notifications)

**Comment by Amirhossein10** [comment]
I don't want to see notifications and disabled it, but also I don't want to mute chats.

**Comment by BoolCube** [comment]
@Amirhossein10 Disabling notifications = muting chats.
