### ISSUE TITLE
Keep running in the background after being closed

### ISSUE THREAD

**Issue by gitlater** [UnigramDev/Unigram#2268]
As the title said, is there a way to make this app to keep running (to receive new messages) just like the official Telegram desktop app?

**Comment by MarcAnt01** [comment]
Hello, Unigram cannot run in background, but you can receive push notifications even if the app is closed. Atm there are some issues that prevent push notifications to be delivered sometimes.
Leaving https://github.com/UnigramDev/Unigram/issues/2210 for reference
