### ISSUE TITLE
Enter key doesn't switch between emojis, GIFs, or stickers

### ISSUE THREAD

**Issue by KeronCyst** [UnigramDev/Unigram#2269]
Unigram 7.5 (5961) X64 on Windows 10 20H2 (build 19042.844)

1. Place the cursor in the text field when chatting with someone/in a group
2. Press Tab twice and then Enter to access emoji/GIF/sticker media
3. Press Shift-Tab once to highlight the row of media types
4. Use the arrow keys and try to press Enter to select a different type of media

Expected result: It should switch to that medium.
Current result: Enter does nothing; only the space bar works here.

**Comment by FrayxRulez** [comment]
GIFs, emoji and stickers switches are not presented as list items, thus you can use arrow keys to switch between them
