### ISSUE TITLE
search results interfer with "forward to"-list

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#227]
If you have searched for a Chat and opened it, you will get the Screen below, if you try to Forward a message.

You can click the search bar, delete everything, so that the chat-list is shown again, but this is not ideal.
![wp_ss_20170328_0002](https://cloud.githubusercontent.com/assets/14281234/24415350/7ec85544-13e1-11e7-951e-13a2bf7bb9e2.png)

**Comment by FrayxRulez** [comment]
Fixed with the new forward UI
