### ISSUE TITLE
App does not work logged-in if system sorting method is Bopomofo. 

### ISSUE THREAD

**Issue by ztdu** [UnigramDev/Unigram#2270]
The Unigram app (both from Microsoft Store and beta channel) doesn't work properly. 

App version: store-- installed on Mar. 9, 2021; beta channel--Unigram_7.5.5959.0_x64.appxbundle
To re-create the environment : Windows 10 20H2. Control Panel > Clock and Region > Region > Additional settings... > Sorting > Select the sorting method as "Bopomofo". 

Once changed the sorting method to "stroke count", the app is all okay. (Stroke count is the system's default so most user may not facing this bug.)

Under such environment, the new-installed / reset app works until users  are logged in. Once logged-in, the app freezes on the contact permission request dialog. 
After closed and reopen, the app freezes on the launch screen, and after some time closes itself. 

According to the reviews on Microsoft Store, this issue existed as late as on Apr. 10, 2019 on Windows 10 1903. 

![Screenshot 2021-03-09 213340](https://user-images.githubusercontent.com/80333016/110480180-2d5e7100-8121-11eb-9344-a11597d6eb4a.png)

**Comment by FrayxRulez** [comment]
Well, I don't have "Sorting" tab at all :(

**Comment by ztdu** [comment]
> Well, I don't have "Sorting" tab at all :(

I’m not sure but I suppose if the system language is English, the only available sorting method is alphabetical so the tab is hidden. Could you please try to change system language to Chinese (Traditional, Taiwan)（中文-繁體-台灣）and look for the tab again?

**Comment by FrayxRulez** [comment]
Can you reach me on Telegram? Same username as here.
