### ISSUE TITLE
ARM64 package is missing

### ISSUE THREAD

**Issue by Alovchin91** [UnigramDev/Unigram#2272]
Hi,

I had to reinstall Windows on my Surface Pro X and noticed that ARM64 version of Unigram is gone from the Store, and the latest .appxbundle posted in the channel is x64 only.

What has happened to ARM64 version? And when is it going back?

Thanks!

**Comment by Alovchin91** [comment]
Hi @FrayxRulez do you have any plans to start publishing ARM64 packages for Unigram again? I cannot even reinstall the app now. Thanks!

**Comment by FrayxRulez** [comment]
It's back
