### ISSUE TITLE
Disable accepting secret chats

### ISSUE THREAD

**Issue by itskenny0** [UnigramDev/Unigram#2273]
Hi,
I use Telegram on multiple clients and Unigram will occasionally snatch up new chats and take it away from other devices.
Telegram Desktop does not have this issue as it does not support secret chats. Would it be possible to add an option to disable secret chats?
Thanks lots.

**Comment by MarcAnt01** [comment]
Hello, secret chats are made to be used in the device you are using at the moment, so if you're online on Unigram, you should chat from there. The same applies to Android and iOS apps
