### ISSUE TITLE
Accessibility: List Items for stickers need accessibility name

### ISSUE THREAD

**Issue by MarcoZehe** [UnigramDev/Unigram#2274]
The list items for stickers need the same treatment as other list items in Unigram for accessibility. They report as, for example, 'Unigram.ViewModels.Drawers.StickerSetViewModel'.

To reproduce, just open Unigram with a screen reader, open a conversation, for example Unigram Insiders, shift-tab from the input box a few times and make sure the Stickers radio button is selected. Shift-tab some more and hear the screen reader announce 'Unigram.ViewModels.Drawers.StickerSetViewModel'.

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/3b8aa553f276db8cb70e029f9a0b5be9e1b0e09b
