### ISSUE TITLE
"Delete and Exit" Button makes the user join to a channel

### ISSUE THREAD

**Issue by pokurt** [UnigramDev/Unigram#2277]
How to Reproduce:
Click on a private channel link, user will see "Delete and Exit", and when user press the button it will make the user join the chat.

Windows Version: Windows 10 Enterprise 20H2
Unigram Version: 7.5 (5971) x64

Note:
I am assuming its just a string mismatch

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/ea6c6b1e7ee7b752b179a7541f84d25c2d7962d9
