### ISSUE TITLE
The app automatically closes gallery view while doing nothing

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2280]
Sometimes for some obscure reasons, the app automatically closes gallery view while doing nothing

**Comment by MarcAnt01** [comment]
I haven't reproduced that for months, closing this

**Comment by MarcAnt01** [comment]
Unfortunately, I noticed this isn't really solved. Sometimes it closes out of nothing, after some minutes using the app, some other time after minimizing the windows I come back and it's gone :(

**Comment by FrayxRulez** [comment]
This happens when the message you opened the media from (not the currently displayed one, but the one your clicked on in the chat) gets deleted

**Comment by MarcAnt01** [comment]
I can still reproduce this and even with saved messages, so it's somehow unrelated

**Comment by MarcAnt01** [comment]
Furthermore I've noticed that it happens if the photo is opened from shared media section. If it's open directly from the chat, I cannot reproduce it

**Comment by FrayxRulez** [comment]
Re-closing this just in case
