### ISSUE TITLE
Lots of scrolling text when resuming from suspend

### ISSUE THREAD

**Issue by FidikVien** [UnigramDev/Unigram#2283]
When opening the laptop from suspend, I see lots of scrolling text as Unigram previews all the messages, I feel it should just jump to preview the latest message once it's completed it's download of missing information

**Comment by MarcAnt01** [comment]
Since Unigram has caching, it just downloads and loads all of the messages. The same happens in every Telegram app (except Telegram Desktop since it has no cache).
