### ISSUE TITLE
Select sticker from stickers bot crashes Unigram

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2284]

**Comment by FrayxRulez** [comment]
Maybe you should provide some description.

**Comment by MarcAnt01** [comment]
Is this enough?
![image](https://user-images.githubusercontent.com/43090263/112467904-e8b11780-8d67-11eb-91df-a8555215ab22.png)

**Comment by FrayxRulez** [comment]
I can't reproduce.

**Comment by MarcAnt01** [comment]
Probably depending on the sticker pack

**Comment by FrayxRulez** [comment]
Still?

**Comment by MarcAnt01** [comment]
No
