### ISSUE TITLE
Finished audio message cannot be replay back

### ISSUE THREAD

**Issue by SeanTolstoyevski** [UnigramDev/Unigram#2288]
1. Play a audio message  in any chat.
2. Play it again when the message is finished.

Nothing happens.

version: Unigram 7.5 (5972) X64

**Comment by SeanTolstoyevski** [comment]
And the automatic audio message switching doesn't work either.

**Comment by sukiletxe** [comment]
Partially duplicate of #2279

**Comment by MarcAnt01** [comment]
Thanks for your report, but we already have two tickets to keep track of that

**Comment by MarcAnt01** [comment]
Duplicate of https://github.com/UnigramDev/Unigram/issues/2279

**Comment by MarcAnt01** [comment]
Duplicate of https://github.com/UnigramDev/Unigram/issues/2278
