### ISSUE TITLE
Unigram Crash in windows 10 x86

### ISSUE THREAD

**Issue by MuhammadGagah** [UnigramDev/Unigram#2289]
Hi. Yesterday I update unigram to version 7.5, and I get unigram crash when I open groups or channel.
And today, I try to reinstall unigram, and can not open. When I open, unigram crash immediately.
Device info:
Windows 10 Pro 32-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Toshiba satelite L510.
                Processor: Pentium(R) Dual-Core CPU       T4400  @ 2.20GHz (2 CPUs), ~2.2GHz
                   Memory: 3072MB RAM
          DirectX Version: DirectX 12.

**Comment by jandrito88** [comment]
True. I have the same issue in two different devices and now I realise that what they have in common is that both are Windows 10 x86 devices.

You open Unigram, you can see the slash screen and even the chat list for a couple of seconds, and then the app closes itself.
![Captura de pantalla 2021-03-27 153215](https://user-images.githubusercontent.com/81476190/112724048-b9d6a500-8f11-11eb-94ef-5170149c46a5.png)

**Comment by valiant8086** [comment]
Confirmed on two separate AsusTeK T100TA-AM tablets running Win10 x86. As noted, the primary thing that is consistent about all of these is 32 bit. These devices have lousy specs by today's standard 2 gb of ram and Atom z3740 SoC but they run everything else if a little grudgingly.

**Comment by FrayxRulez** [comment]
@levlam is investigating into the issue.

**Comment by FrayxRulez** [comment]
Is anyone able to figure out when Unigram stopped working on x86? Like, the specific version.

**Comment by johnd0e** [comment]
@FrayxRulez 
I suppose it stopped to work in 7.5.

**Comment by MuhammadGagah** [comment]
@FrayxRulez Unigram 7.5 (5972) X86. Which is odd, when I disconnect internet, Unigram no crashes occur.

**Comment by jandrito88** [comment]
> Is anyone able to figure out when Unigram stopped working on x86? Like, the specific version.

It happened in the last versión (7.5), I always check for updates when I start my tablet.

However, I'm pretty sure that I was able to use this last version for some days until this bug started to occur.

**Comment by MuhammadGagah** [comment]
The Issue has been fix in version 7.6.6018.0, I'll close it. Thanks all.
