### ISSUE TITLE
Accessibility: Last button in settings is not tagged

### ISSUE THREAD

**Issue by makisukurisu** [UnigramDev/Unigram#2291]
So as Issue's title says:
![image](https://user-images.githubusercontent.com/49622129/112261465-99d68580-8c74-11eb-9351-f754ca9b0a98.png)
That "button" is simmply announced as button and nothing more. Probably it should at least announce version number, or say something about dev menu button. But, IMO first one is preferable.

That's it.
If there is issue with missing or wrong tags for stuff in Uni, feel free to mention it there and close this issue.

**Comment by sukiletxe** [comment]
Reported in #2178

**Comment by MarcAnt01** [comment]
Thanks for reporting @makisukurisu , but as @sukiletxe said there is already a ticket for that

**Comment by makisukurisu** [comment]
Thanks, didn't found it.
