### ISSUE TITLE
Use emogis instead of duplicating labels?

### ISSUE THREAD

**Issue by sukiletxe** [UnigramDev/Unigram#2292]
(Brought up (yesterday) by me in insiders group. Had no replies so I thought I might as well post it here.). 

Currently, there are several instances where labels are duplicated in Unigram, and where these labels don't point out the real purpose of the labeled thing. Think of the two "close audio player" buttons, one of which shows the volume control, or the multiple "open file" links in the photo and video viewers which to be honest I have no idea about what they do. It has been said multiple times that proper labels cannot be implemented because Telegram for Android doesn't provide translations for them. Until this is changed, or until Unigram allows localization by its users, I propose an idea:

Could emogis be used where labels are missing? I know for a fact that both NVDA and Narrator speak them (the actual unicode emogis, not their images, to be clear), though the things they say are different for some reason and this could be a problem. I have no idea about JAWS' behaviour.

**Comment by FrayxRulez** [comment]
I think that most of these instances have been fixed over time, if it's not the case please open a card on bugs.telegram.org specifying the exact places where buttons are mislabeled. Thank you!
