### ISSUE TITLE
A piece of the chat is under the typing bar while scrolling

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2293]
Starting happening with 7.6
![image](https://user-images.githubusercontent.com/43090263/112553711-4d4e8f80-8dc5-11eb-8c1e-d50068bb83c0.png)

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/841c5bf0d3a16815b25133886a0d5bc3d9e86d57
