### ISSUE TITLE
can not record voice messages using keyboard

### ISSUE THREAD

**Issue by sulaiman-alqusaimi** [UnigramDev/Unigram#2294]
Dear all.
In the recent version of unigram seems that there is an issue in regard to recording voice messages, specificly when using keyboard navigation and interaction as screen reader users do. 
I tryed to use both control + r and press and hold on the enter key above the record button and none of them seems to be working.

**Comment by sukiletxe** [comment]
This has been fixed in the latest beta, I don't know when the store version will be updated.

**Comment by MuhammadGagah** [comment]
yes, the Issues has been fix, just wait for update.
