### ISSUE TITLE
[accessibilit] - CTRL+R doesn't work

### ISSUE THREAD

**Issue by SeanTolstoyevski** [UnigramDev/Unigram#2295]
1. Open a new personal chat
2. Press **CTRL+R**.

I could not test this situation in groups chats. But shortcuts don't work in personal chats.

- Windows version: Windows 10, 64bit, 20h2
- Unigram version: 7.5.5972.0

**Comment by MarcAnt01** [comment]
This should be fixed in 7.5.6000.0

**Comment by SeanTolstoyevski** [comment]
The update is not yet visible in the store. I think it's at the approval stage.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
