### ISSUE TITLE
History of a private group before making the history public is duplicated

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2297]
At first it is displayed properly, but the issue starts to happen, in this way:
- Go to group info;
-  Go back to the chat
![image](https://user-images.githubusercontent.com/43090263/112809908-d4785d80-907a-11eb-8cda-c485478219d4.png)

**Comment by FrayxRulez** [comment]
This was fixed by splitting apart migrated groups history
