### ISSUE TITLE
Cannot open Unigram if a window of voice chat is already open

### ISSUE THREAD

**Issue by DanielRios549** [UnigramDev/Unigram#2299]
I have experienced a bug, to reproduce it is simple, open Unigram, enter in a voice chat, close Unigram. After that, you'll only be able to open Unigram again if you leave the voice chat.

**Comment by MarcAnt01** [comment]
For "Close Unigram" you mean close the main window, right?

**Comment by FrayxRulez** [comment]
This can be probably counted as a duplicate of #843.

**Comment by DanielRios549** [comment]
@MarcAnt01 Right, like this one referenced by @FrayxRulez, I didn't see this issue, but is the same thing
