### ISSUE TITLE
emoji-to-sticker-suggestions are showing the same sticker multiple times

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#230]
when I type an Emoji it Shows me the sticker suggestions and sometimes there is one (or multiple) sticker/s which is/are shown several times. 
I guess this effects only Stickers, which I have send before.

![wp_ss_20170326_0002](https://cloud.githubusercontent.com/assets/14281234/24416173/301b5ab0-13e4-11e7-80ba-4b37012b9b15.png)
![wp_ss_20170326_0001](https://cloud.githubusercontent.com/assets/14281234/24416171/30184aa0-13e4-11e7-8983-c8d996ab66c4.png)

**Comment by FrayxRulez** [comment]
I cannot replicate the issue

**Comment by larsschellhas** [comment]
Could you replicate it yet? Or find something which could cause this issue?
If not, is there anything I can do about it?

**Comment by larsschellhas** [comment]
either it does not exist anymore or I have to many sticker packs.
Probably first, but maybe second, too. :D
