### ISSUE TITLE
Incorrect label for "Voice chat" button

### ISSUE THREAD

**Issue by SurendraG1985** [UnigramDev/Unigram#2305]
Screen reader reads "Join voice chat" button as "Call" button, as it is labeled as such.

**Comment by MarcAnt01** [comment]
As you can see [here](https://github.com/UnigramDev/Unigram/blob/develop/Unigram/Unigram/Strings/en/Resources.resw) there's no such string

**Comment by FrayxRulez** [comment]
It’s literally here: https://github.com/UnigramDev/Unigram/blob/77bed86d74631ce1833d14deae8ac8acaa83670c/Unigram/Unigram/Strings/en/Resources.resw#L12962

**Comment by MarcAnt01** [comment]
lol, looks like I missed it
