### ISSUE TITLE
Spell checking for multiple languages

### ISSUE THREAD

**Issue by andreasfmwolf** [UnigramDev/Unigram#2306]
I write messages in 3 different languages, but the spell checking & auto-correct feature only works in one, which results in wrong auto-corrects, whenever I write in a language different than English. Would be great, if I can select multiple typing languages, so that I don't need to correct the auto-correct all the time ;) Or at least it would help, if I could de-activate the auto-correct.

Btw: superthankyou for an amazing desktop client - makes my life so much better!! <3

**Comment by FrayxRulez** [comment]
Hi Andreas,
Unfortunately spell check is provided by Windows, and I have no control over it. A solution in your case might be to disable spell-checking completely, from Settings > Chat settings > Disable spell-check.
