### ISSUE TITLE
Unpinning some out of multiple pinned messages doesn't immediately remove them from view

### ISSUE THREAD

**Issue by KeronCyst** [UnigramDev/Unigram#2307]
Unigram 7.6 (6020) X64 on Windows 10 Home 20H2: I'm not sure of whether this is intentional, but…

1. Pin multiple messages to a chat (and make sure they're pinned for all, if this is a factor; haven't tested)
2. Unpin one or more of the messages

Expected result: they should immediately disappear from the overview of pinned messages
Current result: They still show; you have to back out and revisit to see them leave

**Comment by FrayxRulez** [comment]
By "overview of pinned messages" you mean the extensive pinned messages list or the chat top banner?

**Comment by hihain** [comment]
Removing all pinned messages at once from the page listing them all does not remove them visually. Would make sense to return to the chat after clicking that button.
