### ISSUE TITLE
"Join Channel" does not work

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#231]
Like the title says, if I´m opening a channel and press "Join Channel", it is not joining it at all. 

![wp_ss_20170325_0003](https://cloud.githubusercontent.com/assets/14281234/24416545/6ee9b48e-13e5-11e7-8a3a-6ba1a7598043.png)

**Comment by FrayxRulez** [comment]
This feature has been added in a recent Unigram version
