### ISSUE TITLE
Deadlock somewhere somehow

### ISSUE THREAD

**Issue by siashaz** [UnigramDev/Unigram#2311]
unigram is not responding after a few minutes when it's opened. I could not scroll in chat or select any other chats. It's totally unresponsive and its not closing by itself, it stays like its hang for hours until I close it manually.

https://user-images.githubusercontent.com/81905627/113508664-e7090000-956e-11eb-8eb7-a5bb058ca0d1.mp4
windows version
![win](https://user-images.githubusercontent.com/81905627/113508677-f4be8580-956e-11eb-995e-9673fd5ac124.JPG)

**Comment by FrayxRulez** [comment]
Do you see any weird behavior in the task manager? (Like constant CPU usage or RAM usage increasing over and over)
