### ISSUE TITLE
":persevere" emoji invocation is misspelled as ":perserve"

### ISSUE THREAD

**Issue by KeronCyst** [UnigramDev/Unigram#2314]
Unigram 7.6 (6036) X64 on Windows 10 Home 20H2:

1. Try to invoke "😣" by typing ":persevere"
2. It can only be invoked by any amount of characters leading up to the string ":perserve" (which isn't a word)

**Comment by FrayxRulez** [comment]
You should report this here: https://translations.telegram.org/en/emoji
