### ISSUE TITLE
Unpinning a chat from a folder doesn't remove it from included chats

### ISSUE THREAD

**Issue by sukiletxe** [UnigramDev/Unigram#2317]
I have tested this with a folder which only includes unread chats (i. e. includes all filters but excludes read chats) . Steps:

1. Create such folder.
2. Pin some unread chat in it.
3. Unpin it.
4. Mark it as read, if it wasn't before step 3.

Expected: The chat, when unpinned and marked as read, should disappear from the folder.
Actual: The chat remains in the folder. If I go to the edit folder screen, the chat is in the included chats list.

**Comment by levlam** [comment]
Pinned chats = always included chats on a fixed position. When such chat is unpinned It is position isn't fixed anymore, but it is still always included. This behavior should be the same in all Telegram clients. For example, I have just tested it in Telegram Android.

**Comment by sukiletxe** [comment]
So are you saying that unpined chats still remain in other clients? Then I suppose that's the expected behaviour, though it's weird for me. If that's the case I'll close this.

**Comment by levlam** [comment]
Yes, this is expected behavior and it works so in all clients I've tested.

**Comment by sukiletxe** [comment]
OK, thanks! Closing then.
