### ISSUE TITLE
GIF playback

### ISSUE THREAD

**Issue by ReeceSX** [UnigramDev/Unigram#2318]
Animated gifs are not played back properly. 

It appears as though frames are blt'd during ::OnTick calls from LoopThreadPool arbitrarily. Frame times inside the MP4 container should be respected and respective frames should be acquired relative to the UI draw delta. The paradigm of using thread pools to BLT component views in place of proper culling and single thread presentation is at best questionable. A rewrite to cache framebuffers and appropriate time steps on a separate thread might be in order.

Known bad animation: https://user-images.githubusercontent.com/42358466/114111414-e0adb780-98d1-11eb-996c-ab1183054fb5.mp4
Known bad animation: https://user-images.githubusercontent.com/42358466/114111575-3eda9a80-98d2-11eb-9c40-1c5ab6277dc2.gif
Good gif: https://user-images.githubusercontent.com/42358466/114111534-279bad00-98d2-11eb-9fd8-932202c303e5.gif

Version: 7.6 6503

**Comment by FrayxRulez** [comment]
It's questionable until you don't have to play dozens of GIFs simultaneously on the screen.
In that case, spawning a specific background thread for every single GIF would have a noticeable impact on the app performances disrupting the user experience at best.

**Comment by ReeceSX** [comment]
tehe yes i too delegate dc draws to a thread pool and see no issue in ignoring the frame delta

**Comment by FrayxRulez** [comment]
How do you mean?

**Comment by ReeceSX** [comment]
Are you asking me how to computer? What frame pacing is having two threads sleeping for at least 33ms racing to consume a frame for each element

**Comment by ReeceSX** [comment]
Also dup of 
https://github.com/UnigramDev/Unigram/issues/555
https://github.com/UnigramDev/Unigram/issues/1692

**Comment by FrayxRulez** [comment]
Listen here, try to be less arrogant yourself because you’re starting here on the wrong foot and I don’t bother to deal with fuckers like you in me free time. 
So, our you try to be a bit more respectful and to actually help rather than wasting my time or you can get the fuck out of here.

**Comment by ReeceSX** [comment]
> So, or you try to be a bit more respectful and to actually help rather than wasting my time or you can get the fuck out of here.

You literally responded to the issue parodying what I said[1], [despite acknowledging your implementation isn't perfect](https://github.com/UnigramDev/Unigram/issues/1692#issuecomment-637463434). Ironically, you are the one wasting my time with nonsense about how many gifs are playing back at the same time, when in reality your support library just sucks. 

[1] `It's questionable until you have to play dozens of GIFs simultaneously on the screen.`

**Comment by FrayxRulez** [comment]
Open a pull request and fix it then, or explain me how you would do. 

You took care of pick some old and closed tickets and read into the code, but you didn’t even notice that the problems mentioned in the tickets have been solved over the past three years, and that you’re referring to something different.

**Comment by FrayxRulez** [comment]
This should be a place where to pacifically discuss topics and to find together a solution.
If you suppose to have more knowledge than me on this topic (and this is absolutely possible) then elaborate, rather than throwing shit at other people work the way you did.

**Comment by ReeceSX** [comment]
> but you didn’t even notice that the problems mentioned in the tickets have been solved over the past three years, and that you’re referring to something different

Also not true
https://github.com/UnigramDev/Unigram/commit/c2bbf41ff715dccf1488f5141bf5202c3e60ae8b#diff-30a51cb3a8e6822b38e4c7e1759db8931317baf4e5dc346abe5a9e4d7281b1cdR339

> Open a pull request and fix it then, or explain me how you would do.

Defer to ` I don’t bother to deal with fuckers like you in me free time.`

**Comment by FrayxRulez** [comment]
Then fuck off
