### ISSUE TITLE
When promoting someone to administrator, the promoter is said to be the person who added him / her to the group instead of the person who promoted him

### ISSUE THREAD

**Issue by sukiletxe** [UnigramDev/Unigram#2321]
How can I explain this? Let's imagine a group with 2 members, A and B. A is the owner and administrator, B is an administrator but cannot promote people.

Suppose that B adds C, and A promotes C to administrator. In the administrators tab, C is said to be "promoted by B", though that's impossible. This happens when reviewing with a screen reader, as always. I can confirm that in iOS this is announced correctly (C would be "promoted by A", in this case).

Hope I made myself clear.

**Comment by FrayxRulez** [comment]
I can't reproduce the issue:
I tried to add user C from user A, and to promote user C from user B.
I correctly see "promoted by B".

**Comment by sukiletxe** [comment]
Strange, can you try with narrator to see if that's the issue?

**Comment by FrayxRulez** [comment]
It can't be that. Unigram is only aware about the last actor user (to say, if you have been invited, the inviter, if you've been promoted, the promoter, and so on). Maybe it was just some cache issue. Or you can still reproduce it?

**Comment by sukiletxe** [comment]
I can reproduce it in two groups currently. In both groups, the person who adds doesn't have the permision to promote people, but it appears as if he promoted the added person.

**Comment by FrayxRulez** [comment]
Are them basic or super groups?

**Comment by sukiletxe** [comment]
Both are small groups. One has voice chat so I think it's a supergroup. I don't know about the other one, I know it has a link to join (but no username).

**Comment by FrayxRulez** [comment]
Check your private messages!
