### ISSUE TITLE
A way for Unigram to show unread message badge on top of folders like Tg Desktop does?

### ISSUE THREAD

**Issue by Bestulo** [UnigramDev/Unigram#2324]
Right now, I can't use Unigram because I talk a lot and don't know if I have anything unread, and if I do, I don't know where the unreads are. Tg Desktop is the only one that reports this with the unread badges on top of folders.

Is there a way to enable unread badges on folders and on the taskbar?

![](https://user-images.githubusercontent.com/78047001/114878368-2dabf500-9dce-11eb-896f-8f6f8efb6968.png)

**Comment by FrayxRulez** [comment]
Both should be available already. Are you sure that you didn't disable notifications/badge in Unigram?

**Comment by Bestulo** [comment]
Could you tell me where this setting is? I MAY have disabled it, but I don't recall doing it, and I don't know where to look for this setting. I've been enabling and disabling some stuff in order to see if I can enable badges, but have accomplished nothing so far.

**Comment by FrayxRulez** [comment]
Settings > Notifications & Sounds.
If you disable notifications for a chat type, then that chat type isn't going to be included in the counter.

**Comment by FrayxRulez** [comment]
You can try to enable logs as explained [here](https://github.com/UnigramDev/Unigram/blob/develop/Documentation/TDLib-logs.md) and play a bit with the app, then disable and send them and send them to tdlib_bot, explaining the reason (or linking this issue)

**Comment by Bestulo** [comment]
Ok so I tested and it works perfectly with all my chats except my default/first account for some reason. I'll log out and log in again, maybe that'll solve it.

**Comment by Bestulo** [comment]
IT doesn't XD

**Comment by FrayxRulez** [comment]
So as I asked you could send logs to me or tdlib_bot on Telegram.

**Comment by Bestulo** [comment]
I don't send logs with identifying information, and the problem solved itself after 2 hours without my knowing intervention, so I'm not interested in pursuing this any further. Thank you for your help.
