### ISSUE TITLE
option to disable Unigram animations

### ISSUE THREAD

**Issue by Bestulo** [UnigramDev/Unigram#2326]
Currently running Unigram on a very slow machine and clicking to open sidebar, settings, chats, opening notifications, right clicking messages, etc., all take a little while because it's loading the animation. It would be cool if I could accelerate the whole process by doing away with the animations, which I don't really care about (speed > slow)

**Comment by ransagy** [comment]
+1.
Even when not running on particularly slow machines the chat bubble animation itself, for example, is quite janky. I'd really like an option to do away with it as it more bothers than helps IMO.

**Comment by YukinoHayakawa** [comment]
I also stand for this request for accessibility concerns. The animations can be very distracting for visually impaired people.

**Comment by noiob** [comment]
seconding! Especially for animated stickers, they're annoying

**Comment by MarcAnt01** [comment]
> seconding! Especially for animated stickers, they're annoying

These are totally unrelated, since they are a feature of Telegram

**Comment by FrayxRulez** [comment]
@noiob You can disable them from looping from settings

**Comment by noiob** [comment]
> @noiob You can disable them from looping from settings

I hadn't found that feature, thank you

**Comment by vitaminj** [comment]
It pays attention to your system settings to reduce motion and disables a lot of things - type "animation effects" into Start to get to the right settings page then turn them off

**Comment by MarcAnt01** [comment]
Hello, from power saving settings, animations are now disableable

**Comment by lynxtaa** [comment]
I don't think it's solved. I want to disable Unigram UI animations (for example when opening the sidebar or right clicking a message) permanently and don't see any new options regarding this

**Comment by FrayxRulez** [comment]
@lynxtaa Unfortunately the amount of work required to disable all the animations in the app is massive and would leave a lot of stuff broken. You can still disable many of the animations (eg, hamburger one) system wide (probably under accessibility, but not sure)

**Comment by lynxtaa** [comment]
Oh, I see.. Anyway thanks for this awesome app :) Will hope someday it'll be solved since it's actually an accessibility issue, animations can trigger discomfort for those with [vestibular motion disorders](https://www.a11yproject.com/posts/understanding-vestibular-disorders/)
