### ISSUE TITLE
TLKeyboardButtonSwitchInline is not fully implemented

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#233]
Well, most of them do work. Like in this case the "Update results", "vote", "Close" and "delete".

Only clicking on "publish poll" does nothing at all...

![wp_ss_20170328_0003](https://cloud.githubusercontent.com/assets/14281234/24416847/718f283a-13e6-11e7-9fc9-ae3b938a45a2.png)

**Comment by FrayxRulez** [comment]
TLKeyboardButtonSwitchInline is not yet supported
