### ISSUE TITLE
playing voice msgs brokes Unigram's functionality 

### ISSUE THREAD

**Issue by cxinu** [UnigramDev/Unigram#2330]
unigram 7.7 (6133) X64

there's a bug after playing a voice message, can't select a thing in current chat, can't render/load other chats, search bar doesn't work anymore. basically brokes functionality

**Comment by MarcAnt01** [comment]
I cannot reproduce your issue

**Comment by Muaath5** [comment]
Add more info about what did you do EXACTLY to get this error.

**Comment by FrayxRulez** [comment]
Yeah, it would be nice to get a bit more context here...

**Comment by FrayxRulez** [comment]
This was fixed here: https://github.com/UnigramDev/Unigram/commit/e3a3b3ca1d5929f924f87e62ea971a4c857caee5
