### ISSUE TITLE
hello fela and dissdesk 

### ISSUE THREAD

**Issue by amirmahdifard0** [UnigramDev/Unigram#2331]
I Am created github account!

**Comment by amirmahdifard0** [comment]
@amirmahdifard0 now comment?

**Comment by MarcAnt01** [comment]
Tickets on GithHub are made for bug reports/feature requests, please don't use it to spam

**Comment by FrayxRulez** [comment]
Hi Amir! Welcome to GitHub 👋

**Comment by amirmahdifard0** [comment]
@MarcAnt01 I do not intend to do so. This is my first time joining GitHub and to try it out, and because I was so happy, I registered a case and then closed it. You destroy my artistic taste.

**Comment by amirmahdifard0** [comment]
@FrayxRulez hi! I hope I can report problems here and they will be fixed soon. I love you very much and thank you for tolerating all my insistence and solving accessibility problems for blind users. You are very kind and good and I love you my best friend!
