### ISSUE TITLE
Cannot install on windows 10 Enterprise

### ISSUE THREAD

**Issue by regchanuk** [UnigramDev/Unigram#2333]
Cannot install on windows 10 enterprise as its missing the store aspect and this is permenant 

is there an EXE version of the installer  or msi

**Comment by MarcAnt01** [comment]
UWP apps do not have a msi or exe file, if the Microsoft Store is missing you might give it a try through the .appxbundle installer from [here](https://t.me/unigramappx)

**Comment by regchanuk** [comment]
Will there be an EXE avalible though

**Comment by MarcAnt01** [comment]
I have already told you several times that this is not possible. If you want to use Unigram, install a clean Windows 10 version

**Comment by FrayxRulez** [comment]
It is absolutely possible to use Unigram on Windows 10 Enterprise.

**Comment by MarcAnt01** [comment]
> It is absolutely possible to use Unigram on Windows 10 Enterprise.

I know on LTSC/LTSB it is possible, but isn't Enterprise non LTSB/LTSC different from them?
