### ISSUE TITLE
calling friend the app just closed after saying yes 

### ISSUE THREAD

**Issue by regchanuk** [UnigramDev/Unigram#2334]
application just crashed after clicking accept would you like to use mic yes no 

then app crashed while making the call

**Comment by amirmahdifard0** [comment]
@regchanuk What version of the app are you using?

**Comment by regchanuk** [comment]
7.6(6054 x64

**Comment by amirmahdifard0** [comment]
@regchanuk Please update the app to the latest version (7.7)

**Comment by amirmahdifard0** [comment]
@regchanuk My unigram version is 7.7.6105.0

**Comment by regchanuk** [comment]
im now 7.7 6136 x64 crashed again but after first crash seems to work again

**Comment by regchanuk** [comment]
seems to be a little buggy ringing cut out this time round testing calls to a friend using unigram too

**Comment by regchanuk** [comment]
but all in all a good app for the secret chats

**Comment by amirmahdifard0** [comment]
@regchanuk unigram is the best informal telegram for Windows

**Comment by regchanuk** [comment]
make it an .exe and we be all good

**Comment by amirmahdifard0** [comment]
@regchanuk If you know how to install it, appxbundle is better.

**Comment by regchanuk** [comment]
i cant install appx bundle as missing packages with win 10 enterprise mainly the windows store

**Comment by MarcAnt01** [comment]
> make it an .exe and we be all good
> 
> 

Uwp apps do not support exe packaging, it's not us not willing to help you, but a platform limitation. It you have Enterprise LTSB/LTSC there are some guides to get back MS Store anyway

**Comment by MarcAnt01** [comment]
> make it an .exe and we be all good
> 
> 

We cannot. Uwp apps do not support .exe packaging, it is a platform limitation, not us not willing to help you. The only way would be install MS Store on Enterprise LTSB/LTSC
