### ISSUE TITLE
unable to re start group call

### ISSUE THREAD

**Issue by regchanuk** [UnigramDev/Unigram#2335]
Group calls bug cant start group call after leaving group call and ending call no way to start call again unless using

 main telegram app  to start group call

**Comment by MarcAnt01** [comment]
Hello, just go to group settings/start group call. It worked for me

**Comment by regchanuk** [comment]
not avalible after i ended call

**Comment by regchanuk** [comment]
![image](https://user-images.githubusercontent.com/46360316/115220549-96fa7380-a100-11eb-89aa-4a36f5eff470.png)


dont see options to start the call

**Comment by FrayxRulez** [comment]
You must click on "..." button.

**Comment by regchanuk** [comment]
![image](https://user-images.githubusercontent.com/46360316/115220735-ce692000-a100-11eb-9e0f-fa86b459b805.png)

**Comment by FrayxRulez** [comment]
No, "..." button in the profile page.

**Comment by regchanuk** [comment]
found it and a bug no tick on the time 
![image](https://user-images.githubusercontent.com/46360316/115220921-096b5380-a101-11eb-86fc-6c1bb94127e5.png)

**Comment by FrayxRulez** [comment]
That's known!

**Comment by regchanuk** [comment]
thanks for the help
