### ISSUE TITLE
Will there be an EXE avalible though

### ISSUE THREAD

**Issue by regchanuk** [UnigramDev/Unigram#2336]
Will there be an EXE avalible though ever 

_Originally posted by @regchanuk in https://github.com/UnigramDev/Unigram/issues/2333#issuecomment-822361567_

**Comment by amirmahdifard0** [comment]
@regchanuk You have opened two new issues for this topic. Please close them.

**Comment by regchanuk** [comment]
the other person closed the other one

**Comment by MarcAnt01** [comment]
Duplicate of  https://github.com/UnigramDev/Unigram/issues/2333#issuecomment-822361567

**Comment by regchanuk** [comment]
it still a requirement tho

**Comment by MarcAnt01** [comment]
There's already an issue open on Project Reunion (UWP/Win32 evolution basically) asking for non MSIX packaging, that's what you are asking for. Having a ticket open here for this purpose makes no sense at all, since it does not depend on us

**Comment by amirmahdifard0** [comment]
@regchanuk What you want is useless and bothers the developers. Therefore, close this issue as well.

**Comment by MarcAnt01** [comment]
@amirmahdifard0 everyone has their own needs and it's fine, but I already told @regchanuk that it's not possible due to uwp limitation. I hope they'll understand that.

**Comment by amirmahdifard0** [comment]
@MarcAnt01 His request is completely useless. appxbundle has no problems and is the best. In my opinion, anyone who makes such a request is useless.

**Comment by wodim** [comment]
"appxbundle has no problems and is the best" well now that's an argument!
