### ISSUE TITLE
Restrictions on group links are not available to blind users.

### ISSUE THREAD

**Issue by amirmahdifard0** [UnigramDev/Unigram#2337]
Blind users can not use the ability to restrict the group link. I checked it, screen reeder does not show us any options related to this feature. There is only one revoke link button that we can use to delete the current link.

**Comment by sukiletxe** [comment]
Confirmed. Only the revoke button is present. When accessing the revoke screen I can only access copy, share and revoke. Right clicking in the link only shows a "select all" button, left clicking does nothing. Right clicking the revoke buttons and other buttons does nothing either.
