### ISSUE TITLE
Cannot switch camera in video call

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#2338]
On my Surface Book 3, I have a front and a rear camera. When I start a video call, my rear camera is automatically selected. Clicking on the "settings" menu in the call, I can see that Unigram offers me both cameras to chose from. However, when I click on the other camera, it does not switch to the selected camera.

**Comment by MarcAnt01** [comment]
Duplicate of https://github.com/UnigramDev/Unigram/issues/2043
