### ISSUE TITLE
Unigram some times shows blank window when starting

### ISSUE THREAD

**Issue by angelo-montes** [UnigramDev/Unigram#2343]
![uni1](https://user-images.githubusercontent.com/77357171/115964621-112a5e00-a52e-11eb-8b58-54e42f4bf486.png)
![uni2](https://user-images.githubusercontent.com/77357171/115964625-11c2f480-a52e-11eb-8ac0-ec49052970ec.png)
There is some nav panel left, by i can't interacе with settings or other paragraph. Closing Unigram don't fix this problem. only reboot.
Windows 10 Pro, last update. Unigram also last version.

**Comment by FrayxRulez** [comment]
Hi! Is it Windows 10 N?

**Comment by GermannPerutskij** [comment]
> Hi! Is it Windows 10 N?

Idk, how can i find it?

**Comment by krustykrab950** [comment]
@GermannPerutskij Press the Windows and R keys on your keyboard at the same time. A Run window will open, type "winver" without quotes and hit Enter. Attach a screenshot of the window which opens.

**Comment by GermannPerutskij** [comment]
> @GermannPerutskij Press the Windows and R keys on your keyboard at the same time. A Run window will open, type "winver" without quotes and hit Enter. Attach a screenshot of the window which opens.

![win](https://user-images.githubusercontent.com/77357171/115967635-640b1200-a53c-11eb-94f6-4344a437a738.png)

**Comment by FrayxRulez** [comment]
Can you then write to me on Telegram? Same username as here!

**Comment by FrayxRulez** [comment]
Closing this, I don't think it's still the case. Feel free to reopen.
