### ISSUE TITLE
Option to disable the notification sound that's played every time a message is received

### ISSUE THREAD

**Issue by kamild1996** [UnigramDev/Unigram#2345]
Title - unless I missed that option somehow.
This sound still plays even if the window is not focused - one has to minimise the app or close the chat to stop the sounds from playing, which is annoying if you just want to keep track of messages on the second monitor while doing something else in the meantime.

**Comment by MarcAnt01** [comment]
Hello @kamild1996 I think you're looking for this option
![image](https://user-images.githubusercontent.com/43090263/115989586-5f3b7200-a5bf-11eb-8b6f-fe09d7a546f4.png)

**Comment by kamild1996** [comment]
I think the polish translation missed this key word "In-App" since I understood that this option would also disable sound notifications when I'm mentioned...
Thank you :)
