### ISSUE TITLE
Numbers aren't displaying after any Arabic letter or text

### ISSUE THREAD

**Issue by Muaath5** [UnigramDev/Unigram#2346]
When you write **ANY** Arabic text e.g. (`أبجد`), Then write **ANY** number in **ANY** _Input field_, after that you'll **NOT** see any number in the input field, and the text cursor (caret) position not changing.

See the Message input, And see the Draft!!

<img src="https://user-images.githubusercontent.com/60256639/116059728-cf162f00-a689-11eb-83a6-2d036327c790.png" alt="Error numbers aren't displaying after any Arabic letter or text" width="500px">

And if you didn't trust me, Try it yourself.

[Video in Unigram group](https://t.me/unigraminsiders/337715)

**Comment by FrayxRulez** [comment]
I think this was fixed, I don't know
