### ISSUE TITLE
Ctrl + A selects chats, but does not increment the counter

### ISSUE THREAD

**Issue by AlekseyKlimyatich** [UnigramDev/Unigram#2348]
![Безымянный](https://user-images.githubusercontent.com/57356669/116112673-f862a980-a6e1-11eb-8a1e-b9d6cb92f997.jpg)

**Comment by FrayxRulez** [comment]
Ctrl + A is not supposed to select all chats, so I'm closing this (but I'll keep this behavior anyway)
