### ISSUE TITLE
"Notifications and sound"-toggle-switch doesn´t work

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#235]
If used on the Details page of a channel or Group it Returns to the previous state right after you left the Details page.

If used on the Details page of a single-Person-Chat it stays on the new set state, but seems not to affect the chat-notifications or at least does not synchronize with other telegram-Clients.

**Comment by FrayxRulez** [comment]
This feature has been added in a recent Unigram build
