### ISSUE TITLE
Support two options when pressing Enter in keyboard in message input

### ISSUE THREAD

**Issue by Muaath5** [UnigramDev/Unigram#2350]
Default shortcut in sending messages in Unigram (and other desktop clients):
| Shortcut | Result |
|-----------|--------| 
|`Enter`|Send a message|
|`Shift+Enter`|New line|

Alternative shortcut (Supported by Telegram desktop, Telegram web & WebZ):
| Shortcut | Result |
|-----------|--------| 
|`Enter`|New line|
|`Ctrl+Enter`|Send a message|

And in other clients, you can choose between them.
But in Unigram, you don't have an option to choose.

**So, I suggest add ability in Unigram to change the send message shortcuts.**

Also the choose of these should be in _Chat Settings_ section.

**Comment by FrayxRulez** [comment]
This feature is already available and it's literally in chat settings.
