### ISSUE TITLE
Unigram crashes again on x86

### ISSUE THREAD

**Issue by MuhammadGagah** [UnigramDev/Unigram#2352]
Hi, same as #2289 , Unigram crashes when open group or channel. I am using Unigram 7.7 version 6170 X86.
I can send tdlib_log.txt if needed

**Comment by MuhammadGagah** [comment]
fix on version 7.7.6179.0.
Thank you, and I close this issue.

**Comment by FrayxRulez** [comment]
Hey, sorry, I didn't see your previous comment, glad that the issue is fixed

**Comment by amirmahdifard0** [comment]
@MuhammadGagah My friend, who uses Windows 32bit, told me this problem was fixed in version 7.7.6172.0.
