### ISSUE TITLE
All chat messages are transparent. v7.7

### ISSUE THREAD

**Issue by JoseluDAM2000** [UnigramDev/Unigram#2354]
Apparently all my chats have been affected by this error. 
The messages are "transparent" and I can only send messages, although once sent I cannot read anything.

All I did was create chat folders...

![imagen](https://user-images.githubusercontent.com/22506382/116759824-97094600-aa13-11eb-8444-2f28b2998c63.png)

**Comment by headware** [comment]
Same issue occurred this morning.

**Comment by FrayxRulez** [comment]
Hey, just update the app from the Store!
