### ISSUE TITLE
Qr login strings are untranslated

### ISSUE THREAD

**Issue by Muaath5** [UnigramDev/Unigram#2355]
## Actual behavior
Unigram detects my language (Arabic), But in QR-Code page it displays some English text with some Arabic text!!
While the English text has a translation in [translations.telegram.org](https://translations.telegram.org/)..

**Green:** English text.
**Red:** Arabic text, that means Unigram detects my language!
<img src="https://user-images.githubusercontent.com/60256639/116801539-9d7ee700-ab13-11eb-8302-db20b06a871f.png" alt="Sign in page with translation error" width="90%">

## Expected behavior
All text is in English (If the app didn't detect my language), Or all text is in Arabic (if Unigram detects). 

## Way to fix
I think it's by using TDesktop translations in these texts in QR-code page only.

### Linked pages:
[`SignInPage.xaml`](https://github.com/UnigramDev/Unigram/blob/develop/Unigram/Unigram/Views/SignIn/SignInPage.xaml)

**Comment by MarcAnt01** [comment]
Hi @Muaath5 , we rely on Telegram for Android strings and translations and there's nothing for the qr code part, since it's a Desktop feature

**Comment by Muaath5** [comment]
> 
> 
> Hi @Muaath5 , we rely on Telegram for Android strings and translations and there's nothing for the qr code part, since it's a Desktop feature

I know that, So I suggest using TDesktop translations in this page only.

**Comment by FrayxRulez** [comment]
Now they are
