### ISSUE TITLE
Scaling for Unigram broken

### ISSUE THREAD

**Issue by Tiberius1OOO** [UnigramDev/Unigram#2357]
Trying to explain the normal Telegram Client had a scaling option so that I could make everything bigger. 

The Unigram client dosen`t have that ony text sice which is absolutly uselees for me and my family. We need to be able to scale Unigram higher.

NO we do not want to scale EVERYTHING in windows higher since everythign else is fine but Unigram is just to small to read for us.

We really love the program but this is really a feature the old one had that the new one is missing immensly.

**Comment by MarcAnt01** [comment]
Hello @Tiberius1OOO we are sorry that you miss this feature, but we believe this is not necessary. You can see in https://github.com/UnigramDev/Unigram/issues/2287 the reasons of that

**Comment by Tiberius1OOO** [comment]
> Hello @Tiberius1OOO we are sorry that you miss this feature, but we believe this is not necessary. You can see in #2287 the reasons of that

No this is absolutly no solution because if I use the system setting absolutly everything will be scaled by windows and we do not want that. We have a working eviroment and everything is absolutly working fine. Unigram is such an amazing tool but that is limiting the use case extremely.

**Comment by FrayxRulez** [comment]
> NO we do not want to scale EVERYTHING in windows higher since everythign else is fine but Unigram is just to small to read for us.

I know that default font size for Win32 apps is 12px, while for UWP apps it is 14px.
Unigram is a UWP app so it uses 14px, that's 2 pixels more than most of the softwares on your PC.

**Comment by MarcAnt01** [comment]
Also if you want you can increase the text size from settings

**Comment by Tiberius1OOO** [comment]
> Also if you want you can increase the text size from settings

I explained in the main thread why this is a bad thing and even the highest setting of the textsice dose not upscale names and interface
