### ISSUE TITLE
Using "delete" key in keyboard for elimination of focused messages

### ISSUE THREAD

**Issue by rbakhshi72** [UnigramDev/Unigram#2358]
### I think that using :Delete" key in keyboard is better for elimination a message instead of using write click  and choosing the item of "Delete" in context menu.

**Comment by MarcAnt01** [comment]
I tried and del key worked for me

**Comment by MuhammadGagah** [comment]
yeah i tried it too, and worked for me.

**Comment by rbakhshi72** [comment]
@MarcAnt01 It is so strange! It doesn't work for me. Where did you try it exactly?

**Comment by rbakhshi72** [comment]
@MuhammadGagah Can you explain more information? Have you tried on messages or chat list? It doesn't work for me enywhere.

**Comment by MuhammadGagah** [comment]
First, please press the application on the message you want to delete, then find select using the arrow keys. Well, now you try to press delete, its work. It's not a bug, but it's the same as the original telegram version. So, you must first select the message to delete.

**Comment by rbakhshi72** [comment]
@MuhammadGagah I didn't write that the item of "delete" doesn't work. I suggested that to use Delete key on keyboard as a shortcut for removing a message. by using this shortcut, we can remove a message so fast.

**Comment by MuhammadGagah** [comment]
Ah, its not possible, that feature is not in the original telegram.

**Comment by FrayxRulez** [comment]
You can delete the message by ESC key, but only if the message is selected. Focused isn't enough. 
Will take a look into this.
