### ISSUE TITLE
Error 408

### ISSUE THREAD

**Issue by pejman84** [UnigramDev/Unigram#236]
MTProtoService operation timed out (25s)
Every time I try I get this message.

**Comment by FrayxRulez** [comment]
Tried to close and open the app again? Do you get your phone code prefilled when you open the app?

**Comment by pejman84** [comment]
yes tried to close and open the app, and yes my phone code is prefilled (+98) for my country code.

**Comment by FrayxRulez** [comment]
We're working on registration functionality (already available through the sources) that will be included starting from the next versions

**Comment by FrayxRulez** [comment]
I can confirm you that 408 was a temporary issue with Datacenter 4 (the one your phone number connects to).

**Comment by pejman84** [comment]
Still having this error (408) tried now.

**Comment by FrayxRulez** [comment]
If you try with official Telegram app you'll notice that 99% the same will happen (Well, you don't get an error message, but your request will timeout without the ability to login.)

**Comment by pejman84** [comment]
Ok I'm not sure about Telegram because every time I try I will login without problem, but I failed for every try on Unigram without any success,  anyway I'll keep trying and I hope the bug fixes.

**Comment by FrayxRulez** [comment]
Hi, I confirm you that the problem that was causing 408 error is solved server side
