### ISSUE TITLE
Removing chats from a folder is a bit tricky

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2360]
At the moment to remove a chat from a folder we basically have to click on "Add chat" and then untick the selected chat.
Telegram Desktop instead has a small "x" through which you can easily remove the chat
![image](https://user-images.githubusercontent.com/43090263/117285618-8409d200-ae68-11eb-8ed7-91faad887ba0.png)

**Comment by FrayxRulez** [comment]
It looks like that you don't like right clicking

**Comment by MarcAnt01** [comment]
Well, that's counter-intuitive and adding adding a menuflyout just for one item doesn't seem a good idea to me. I'll take care of that when I have more time anyway

**Comment by FrayxRulez** [comment]
Not doing this
