### ISSUE TITLE
Add a shortcut to delete folders faster from folders settings

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2361]
If I go to settings > folder I cannot delete a folder.
I'm aware of the fact that I can easily delete them right clicking on them, but an option should be present from settings, as well
Telegram Desktop for example has a delete button
![image](https://user-images.githubusercontent.com/43090263/117285956-e793ff80-ae68-11eb-850b-00ac68c0f7de.png)

**Comment by FrayxRulez** [comment]
Title is misleading

**Comment by FrayxRulez** [comment]
Right click > Delete is fast enough
