### ISSUE TITLE
Error while converting a private group to public supergroup and add description

### ISSUE THREAD

**Issue by Muaath5** [UnigramDev/Unigram#2362]
When I created a private group.

I wanted to make it public, add a description, And add _slow mode_ timer.

Then, I found (Delete this group) button at the bottom!!

See [this video](https://t.me/unigraminsiders/339633) in Unigram insiders group

**Comment by Muaath5** [comment]
What about this, @FrayxRulez ?

**Comment by MarcAnt01** [comment]
Just take into account that there are other 333 open issues 🙂
