### ISSUE TITLE
Untranslated text in photo message context menu

### ISSUE THREAD

**Issue by Muaath5** [UnigramDev/Unigram#2363]
**Untranslated text in photo messages in a channel with comments section under message.**
The texts below, Are untranslated while it has a translations in [Translations platform](https://translations.telegram.org/)
* Report ([translation link](https://translations.telegram.org/ar/android/groups_and_channels/ReportChat))
* Forward ([translation link](https://translations.telegram.org/ar/android/general/Forward))
* Copy ([translation link](https://translations.telegram.org/ar/android/private_chats/Copy))
* Copy Link ([translation link](https://translations.telegram.org/ar/android/private_chats/CopyLink))

## Screenshots
<img src="https://user-images.githubusercontent.com/60256639/117339089-02d22f80-aea8-11eb-8fe8-f84ab288263d.png" alt="Photo message context menu">

**Comment by makisukurisu** [comment]
@Muaath5 Also select. There is translation for Telegram X but not for Telegram Android(

**Comment by Muaath5** [comment]
I tried this after sometime, It was fixed.
