### ISSUE TITLE
Notification counter with small taskbar.

### ISSUE THREAD

**Issue by igoralebar** [UnigramDev/Unigram#2365]
I didn't know there was notification counter, then thought it wasn't working, until I switched off small taskbar.
Is it possible to implement this?

**Comment by MarcAnt01** [comment]
Hello, unfortunately as Fela told you UWP apps cannot override the system taskbar badge counter behavior, if you'd like that to be possible you might try to open a ticket at Project Reunion [here](https://github.com/microsoft/ProjectReunion) to ask to override the behavior or to allow that via the badge provided by the system
