### ISSUE TITLE
Login - Proxy settings lost after selecting "or log in using your phone number"

### ISSUE THREAD

**Issue by KiruyaMomochi** [UnigramDev/Unigram#2367]
## Reproduce steps
1. Add a proxy in _proxy settings_
 ![image](https://user-images.githubusercontent.com/65301509/117580461-99158800-b12a-11eb-8e3a-102c04be9873.png)
2. Select "or log in using your phone number"
  ![image](https://user-images.githubusercontent.com/65301509/117580476-adf21b80-b12a-11eb-8ef6-3cf090f9546f.png)
3. Reopen _proxy settings_, and you will find the proxy settings are lost.

* I'm using 2FA.

**Comment by Tamarindo94** [comment]
I don't use a proxy, but had a similar problem where I lost all saved chats after selecting "or log in using your phone number"

**Comment by KiruyaMomochi** [comment]
Looks like it's fixed
