### ISSUE TITLE
Focus the emoji selection when type ":something"

### ISSUE THREAD

**Issue by Sav22999** [UnigramDev/Unigram#2370]
When you type ":" followed by something (for example lol, so `:lol`), I think it would great that emoji would focussed, so you could select another emoji, in the list, just with arrows (exactly like in the Telegram Desktop). Now, to get the focus, you need to press once "down arrow")

Now (Unigram):
![immagine](https://user-images.githubusercontent.com/32335378/117976120-af406580-b32f-11eb-8991-78e6cb557e8e.png)

Now (Telegram Desktop):
![immagine](https://user-images.githubusercontent.com/32335378/117976189-c41cf900-b32f-11eb-921b-0f0d28f01a23.png)

What Unigram should be:
![immagine](https://user-images.githubusercontent.com/32335378/117976268-e0209a80-b32f-11eb-953c-28cf7c4441dc.png)

**Comment by FrayxRulez** [comment]
It's the case because there's the chance that you only want to send `:lol` and not to insert the first emoji in the list...
In that case you won't be able to (and think about people who use :s, :o and similar emoticons)

**Comment by Sav22999** [comment]
Yeah, in fact you can just press "space" to send ":lol".
:lol was just an example

**Comment by FrayxRulez** [comment]
Recently done
