### ISSUE TITLE
Sending stickers from the 'Skull' Sticker pack make the app unusable

### ISSUE THREAD

**Issue by kabirnayeem99** [UnigramDev/Unigram#2371]
The moment I send any sticker from this particular sticker pack, the animation is shown in an overlay mode and I have no option to cancel or remove the overlay. 
![image](https://user-images.githubusercontent.com/39023212/117991649-11b15a00-b360-11eb-9c25-bed70857e9eb.png)

**Comment by FrayxRulez** [comment]
Mouse or touch screen?

**Comment by kabirnayeem99** [comment]
Mouse. Windows 10. 21H1. Device model: Thinkpad T440P.

**Comment by FrayxRulez** [comment]
I don't think this is still the case
