### ISSUE TITLE
[bug] When edit a message, in the textbox remains the "Done" button

### ISSUE THREAD

**Issue by Sav22999** [UnigramDev/Unigram#2372]
How to reproduce it:

1. ![immagine](https://user-images.githubusercontent.com/32335378/118011343-343b7700-b350-11eb-960d-6758eae719b7.png)
2. ![immagine](https://user-images.githubusercontent.com/32335378/118011079-e7f03700-b34f-11eb-84cb-e78324dc52c1.png)
2. ![immagine](https://user-images.githubusercontent.com/32335378/118011122-f5a5bc80-b34f-11eb-91ae-d61b471698e9.png)
3. ![immagine](https://user-images.githubusercontent.com/32335378/118011203-0c4c1380-b350-11eb-9ebb-03f7fbdec212.png)

**Comment by FrayxRulez** [comment]
This was fixed in https://github.com/UnigramDev/Unigram/commit/e25157f89d6ef39cd2277884e4a9fb307d3301a8
