### ISSUE TITLE
Code blocks get wrapped when there's enough width on screen.

### ISSUE THREAD

**Issue by igoralebar** [UnigramDev/Unigram#2377]
Official client seems to not have a max message bubble width limit for code blocks, can this be implemented in Unigram?

**Comment by MarcAnt01** [comment]
Hello, thanks for your bug report. I'm afraid it's already been reported

**Comment by FrayxRulez** [comment]
@MarcAnt01 you literally just linked the same issue...

**Comment by MarcAnt01** [comment]
Duplicate of https://github.com/UnigramDev/Unigram/issues/2376

**Comment by FrayxRulez** [comment]
It's absolutely unrelated

**Comment by MarcAnt01** [comment]
I'm sorry, I have just realized this one is specific for code blocks

**Comment by MarcAnt01** [comment]
I'm closing this one, since the other ticket, despite being newer, explains the request in a more straightforward way
