### ISSUE TITLE
Some chats profile tabs are moved by one

### ISSUE THREAD

**Issue by sukiletxe** [UnigramDev/Unigram#2378]
Sorry for vague title. Since the empty tabs in entity profiles were discarded, when there are discarded tabs, the rest appear moved by one (or at least that's what NVDA says).

So, for example, if I have a chat with just files and groups, at first it starts fine, but then the tabs are reversed (if I click on groups files are shown and the other way around). If I have more than 2 tabs, the first tab's header corresponds to the second tab, the second to the third, etc., until it cycles and the last corresponds to the first one.

I am not sure now, but I think that once tabs even appeared mixed too.

**Comment by FrayxRulez** [comment]
This was fixed in https://github.com/UnigramDev/Unigram/commit/1796e86bcac08fa506736f7c41a4ab0cf7eb1909

**Comment by FrayxRulez** [comment]
By the way, I added labels to the tabs themselves (that I think they were unlabeled at the moment), let me know if you prefer like this or the way it was before

**Comment by FrayxRulez** [comment]
So the thing is that visually it looks like the same thing, but in the UI tree tabs and the actual pages are two separate trees.
Before the numbered tabs there's the visual ones.
With the next update even numbered ones will have a label!
