### ISSUE TITLE
Japanese text in text bubble overlaps with time

### ISSUE THREAD

**Issue by roxk** [UnigramDev/Unigram#2382]
**Screenshots**
Japanese (incorrect):
![image](https://user-images.githubusercontent.com/16918354/119214379-08ab5000-baf9-11eb-910a-67612419797b.png)
Chinese (correct):
![image](https://user-images.githubusercontent.com/16918354/119214386-182a9900-baf9-11eb-8332-1c2d0ba7349a.png)
English (correct):
![image](https://user-images.githubusercontent.com/16918354/119214399-2d072c80-baf9-11eb-970c-4f00f08e11dd.png)

**Version Info**
##### Unigram
7.7 (6247) X64

#### Windows
Windows 10 21H1 Desktop, although the bug had existed since 20H1 I believe

Off-topic: Maybe could use some github template for bug report?

**Comment by FrayxRulez** [comment]
You are right, I should prepare a template. 
May I ask you to send me some of those messages so that I can try myself?

**Comment by roxk** [comment]
Seems like a font substitution/fallback issue, as this cannot be reproduced reliably. For example, it doesn't happen on my surface go 2. It is observed that the font in system where this is not reproducible is different that those in which this is reproducible. Will close.
