### ISSUE TITLE
Proposal: Add max width settings to Adaptive Layout for Wide Screens

### ISSUE THREAD

**Issue by roxk** [UnigramDev/Unigram#2383]
**Description**
Currently, Unigram provides two chat layout options where the chat screen would:
(1) use all available width when "Adaptive Layout for Wide Screens" is off, or
(2) has a maximum width when said option is on

Option (2) works perfectly in certain scenarios where users had chosen a high display scale, or the monitor is in portrait mode, or when the window is within a certain size. A chat list with max-width does improve readability and reduce fatigue.

However, the max width can seem a little too narrow when the window becomes wider if users had chosen a lower display scale, or are using an ultra wide monitor (or equivalent).

**Rationale**
##### Comparison with other UX
![image](https://user-images.githubusercontent.com/16918354/119214962-32667600-bafd-11eb-88c7-da32e421f150.png)

As you can see, due to a number of layout constraints (padding for each side, maximum height while maintaining aspect ratio etc, consistent maximum width for text bubble, I guess?), the available width for chat bubble is even shorter than twitter's media preview _and_ text. I think for media preview, the limited preview size is fine. But the similar limitation is there for text only as well, so the overall width available for text is smaller than that of twitter _when twitter itself has a smaller total feed list width than unigram chat list width_.

There are multiple ways to improve the situation for users who have lots of screen real estate (like me :p), e.g. allow text chat bubble to have different max width than media preview, etc. But these are nice-to-have and doesn't improve the situation once and for all.

Ultimately, depending on how the padding etc are coded, I believe binding chat list's max width to a user-provided max width is the easiest way to satisfy the most users with the least effort (Conceptually, just an `x:Bind ViewModel.ChatMaxWidth`, with the max width settings stored in `LocalSettings` or `RoamingSettings`. Might need some input validation but that shouldn't be too time-consuming with C#).

**Proposal**
| Scope | Priority |
|---|---|
| Allow user to customize the max width used for Adaptive Layout for Wide Screens | Must |
| Allow text and media chat bubble to have different max width  | Could |

**Design Mock Up**
![image](https://user-images.githubusercontent.com/16918354/119215441-4eb7e200-bb00-11eb-8f3d-37e96cdd4664.png)

Might need to leave room for error message below the text block.

**Comment by FrayxRulez** [comment]
Sorry, but I don't see this happening any time soon...
