### ISSUE TITLE
Edited medias not uploading with custom download folder

### ISSUE THREAD

**Issue by TechiError** [UnigramDev/Unigram#2385]
🐛:bug:
**Describe the bug**
When sending medias to any chat with editing with unigram editor the media upload fails if there is custom download folder.

**Expected behavior**
The media should upload without any problem in the chat whether custom download folder or not.

**Screenshots**
![image](https://user-images.githubusercontent.com/75001577/119319558-3c70ac00-bc98-11eb-87b3-c84efbe56bd3.png)

**Version Info**
 - Unigram: 7.8 (6368) x64
 - Windows: Windows 10 Pro 20H2 (OS Build 19042.985)

**Comment by luccascomvoce** [comment]
I can reproduce this bug in version 9.0 7771.  I can't replace videos.


https://user-images.githubusercontent.com/65538684/191520766-434bf4bc-1e6e-44f9-b030-35d8a9f5ae03.mp4

**Comment by jvlianodorneles** [comment]
@luccascomvoce Same here.

Unigram 9.0 7771

Windows 11 Home Single Language
21H2
22000.1042

**Comment by makisukurisu** [comment]
@luccascomvoce , the report is about a different issue :sweat_smile: 

It's about editing media before sending it

Also your media doesn't update at all, haven't you noticed?

**Comment by luccascomvoce** [comment]
@makisukurisu I thought it was similar 😅 I'll open another ticket then

Thanks

**Comment by TechiError** [comment]
Umm, is the issue fixed?

**Comment by makisukurisu** [comment]
Could not reproduce on 9.3 7955, Windows 11 22H2 (22621.963)

**Comment by FrayxRulez** [comment]
Merging with #2164
