### ISSUE TITLE
voice chat

### ISSUE THREAD

**Issue by ngxu** [UnigramDev/Unigram#2389]
can you guys please set that start voice chat option to other users in a group and not only administrators?
I know Unigram Insiders have this.

**Comment by ngxu** [comment]
![image](https://user-images.githubusercontent.com/81410731/119331882-72268c80-bcba-11eb-9ee0-be4606d980bd.png)

**Comment by FrayxRulez** [comment]
Only admins are allowed to start a new voice chat, users can only participate to already existing ones!
