### ISSUE TITLE
Long group titles overlap buttons in small windows

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2390]
![image](https://user-images.githubusercontent.com/43090263/119782034-fd2aa100-becb-11eb-9c2d-10f6219ebd07.png)

**Comment by FrayxRulez** [comment]
Ma vai a cagare

**Comment by FrayxRulez** [comment]
Anyway the issue was fixed in https://github.com/UnigramDev/Unigram/commit/06535ae630f748aaade27f96effa5f83bcd7981e
