### ISSUE TITLE
Image preview problem in dual screen

### ISSUE THREAD

**Issue by CuteCatXiao** [UnigramDev/Unigram#2391]
![bandicam 2021-05-28 17-41-37-369](https://user-images.githubusercontent.com/62191675/119966052-81207e00-bfdd-11eb-9a10-72e74e0ef4c7.gif)
2nd screen↑ ----- 1nd screen↑
When I preview images in dual screen , the biger images will appear in 2nd screen not the 1st screen witch is the Unigram app at.

**Comment by FrayxRulez** [comment]
Hey, as a workaround I would suggest you to disable full screen gallery in Settings > Chat settings until I find a solution.

**Comment by FrayxRulez** [comment]
This was fixed in https://github.com/UnigramDev/Unigram/commit/2c2016dc83f64efb1909fdcfaba6b1e608cc660c
