### ISSUE TITLE
Time display problem

### ISSUE THREAD

**Issue by CuteCatXiao** [UnigramDev/Unigram#2392]
![image](https://user-images.githubusercontent.com/62191675/120011685-29036f00-c011-11eb-8a85-88beb7da4251.png)
The time display position isn't correctly, It's blocked by the top message.

**Comment by FrayxRulez** [comment]
This has been fixed in https://github.com/UnigramDev/Unigram/commit/29ced8ac03676dc2d09354d0ecdffdb5e1326f7d
