### ISSUE TITLE
Message send time display porblem

### ISSUE THREAD

**Issue by CuteCatXiao** [UnigramDev/Unigram#2393]
![image](https://user-images.githubusercontent.com/62191675/120055936-c095ab80-c06b-11eb-9523-463e89187621.png)
The end part of main text is been blocked by the message send time so I can't see both item clearly.

Unigram 7.8(6431) X64
Windows 10 Enterprise Version 21H1 19043.1023

**Comment by FrayxRulez** [comment]
This seems quite similar to #2382. @roxk
