### ISSUE TITLE
The bot start massage problem

### ISSUE THREAD

**Issue by CuteCatXiao** [UnigramDev/Unigram#2394]
![bandicam 2021-05-29 17-05-37-789](https://user-images.githubusercontent.com/62191675/120064765-8692cc80-c0a0-11eb-9370-ee0827b79393.gif)
When I press the start button, the first message of the bot will not appear although the sidebar already show that I have a unread message.  Until I switch to another channel then switch back, the meeage appear .

Unigram 7.8(6431) X64
Windows 10 Enterprise Version 21H1 19043.1023

**Comment by FrayxRulez** [comment]
Hey, I believe that this was actually related to a different issue that has been now addressed.

**Comment by TsinJu** [comment]
Still there in 2024

**Comment by FrayxRulez** [comment]
@TsinJu You could open a new ticket and explain what’s the problem.

**Comment by TsinJu** [comment]
> @TsinJu You could open a new ticket and explain what’s the problem.

It's a Bug since, at least, 2021, still there it seems none cares...

Also: "Please do not report bugs or make suggestions/feature requests through issues on GitHub. We have moved to https://bugs.telegram.org/ , please refer to the README for further information."

**Comment by FrayxRulez** [comment]
@TsinJu It’s not a bug since at least 2021, as I clearly remember to have fixed it. 
Code changes over time and bugs can be reintroduced. Follow instructions or your report will be ignored.

**Comment by TsinJu** [comment]
Sry, but I give a 💩
Why wasting ma Time if I just can use a different Client that works fine

**Comment by makisukurisu** [comment]
@TsinJu But you were the one who wrote about the bug being present in the app in 2024 in the first place.

If you were willing to spend a few minutes of your time to complain about the issue, and few more before that to find the issue, you probably could invest just a few more and report the problem properly to help fix the problem 🤷‍♂️

If you really did not care, you would just switch clients without any comments and/or research, wouldn't you?
