### ISSUE TITLE
Unread messages don't get marked as read

### ISSUE THREAD

**Issue by Guariel** [UnigramDev/Unigram#24]
If a conversation has unread messages, opening it doesn't mark them as read.

**Comment by LuKePicci** [comment]
You should only mark them as read when you scroll to the bottom of the conversation, just see how tdesktop does.

**Comment by marcel93b** [comment]
Doesn't work either. The only way to make them marked as read is to receive a message when in the conversation.

**Comment by larsschellhas** [comment]
Or write one by yourself.

**Comment by MarcelBrusius** [comment]
The badge on the Taskbar (on PC) shows notifications although there aren't any (unmuted) ones.

**Comment by LuKePicci** [comment]
In other words, unread message counter badge on taskbar icon is not updated when messages are read. It should be better to open a new different issue.
