### ISSUE TITLE
Reply from notification isn't always sent

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#240]
Sometimes the replies from notifications aren´t send.
I guess it´s due to bad Network, but it´s really bad anyway.
It seems like, if the message could not be send immediately, it´s lost.

Would be good, if Unigram would quere the message and tries to send it as soon as a good enough Network Connection is established - or if this is not possible, send a new notification, that the message could not be sent. For example you could click on the notification to retry.

**Comment by gilmishal** [comment]
+1

**Comment by Jack-Works** [comment]
+1
