### ISSUE TITLE
Emoji panel is getting unpinned

### ISSUE THREAD

**Issue by ghost** [UnigramDev/Unigram#2400]
**Describe the bug**
The emojis panel is getting unpinned if the app will be resized and then maximized back

**To Reproduce**
1. Pin emoji panel
2. Minimize the app
3. Maximize it back

**Expected behavior**
The emojis/stickers/gifs panel should stay pinned

**Version Info**
 - Unigram: [7.8 (6488) x64]
 - Windows: [21h1]

**Comment by MarcAnt01** [comment]
@kkhizir thanks for reporting, but you need to fill every field and not only the first two.

**Comment by kkhizir** [comment]
> @kkhizir thanks for reporting, but you need to fill every field and not only the first two.

Sorry, I have not seen there are more fields cause I didnt scroll down
