### ISSUE TITLE
After editing any message, the "edit" circle-checkmark remains in the bottom-right instead of reverting

### ISSUE THREAD

**Issue by KeronCyst** [UnigramDev/Unigram#2403]
Unigram 7.7 (6247) X64 on Windows 10 Home 21H1:

1. Edit any message and hit Enter
2. Continue to see the circle-checkmark in the bottom-right, even after the message has already been edited

It should revert immediately back to the non-editing buttons, though.

**Comment by MarcAnt01** [comment]
@KeronCyst thanks for reporting, but bug reports are required to follow the template
