### ISSUE TITLE
Messages forwarded to saved messages are sent straight away

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2406]
**Describe the bug**
If you forward a message to any chat, you're able to select more than one, pick send as copy and remove options

**To Reproduce**
1. Pick a message;
2.  Forward it to saved messages

**Expected behavior**
A click should select and  should be able to confirm trough send option, eventually picking send as copy and remov captions options

**Version Info**
 - Unigram: 7.8.6524 x64
 - Windows:21H1

**Comment by FrayxRulez** [comment]
This is by design

**Comment by MarcAnt01** [comment]
I have seen the iOS app does that, as well, but I honestly prefer how it used to behave in previous Unigam versions, having a consistent behavior with forwarding to standard chats
