### ISSUE TITLE
unigram crashes after opening a link from a group in which you were banned

### ISSUE THREAD

**Issue by JorggeHernandez** [UnigramDev/Unigram#2411]
Describe the bug
When trying to open a link from a group in which it was banned, unigram crashes after a few seconds

To Reproduce
1 I open a link where I was banned.
2 back off.
3 reopen the link.
4 back off.
5 I wait a few seconds

Version Info
Unigram: [7.8.6524 x64]
Windows 10 21H1 (64-bit) build 19043.1023

**Comment by FrayxRulez** [comment]
Pretty sure that this is rather related to tooltips and this is a Windows issue, so I'm closing this ticket.
