### ISSUE TITLE
Make message bubble wider when there is code inside

### ISSUE THREAD

**Issue by ad1Dima** [UnigramDev/Unigram#2413]
When you send some `code`, message bubble is too narrow to read it comfortable.
Compare screenshots below
Unigram:
![image](https://user-images.githubusercontent.com/3244664/121654486-f903a380-cac7-11eb-967e-a0fbeb0cf510.png)
Telegram:
![image](https://user-images.githubusercontent.com/3244664/121654394-e1c4b600-cac7-11eb-89bd-8cc581a8db8d.png)

**Comment by igoralebar** [comment]
I'd say not just make it wider, but give unlimited max width.
