### ISSUE TITLE
Gray type of background remains even after deselecting message and releasing mouse.

### ISSUE THREAD

**Issue by binamralamsal** [UnigramDev/Unigram#2415]
Whenever I select messages and go back to the initial stage and release my mouse then also the gray type of background remains there. It is not shown when you go out of that message area. It is just shown when you are inside the message area and when you go to the initial stage.

**To Reproduce**
1. Select messages that you want
2. Go back to the initial message from where you started selecting. So, that all messages will be deselected.
3. Release your mouse
Now, you will see a gray type of background even though you released your mouse. It will instantly go if you go outside of the message area.

**Expected behavior**
It should not show that gray type of background after releasing the mouse.

https://user-images.githubusercontent.com/61900781/121779436-562c5180-cbbb-11eb-8e68-b4baa05eefe1.mp4

**Version Info**
 - Unigram: 7.8 (6524)
 - Windows: Build 21390.1000

**Comment by FrayxRulez** [comment]
This was probably fixed
