### ISSUE TITLE
Ghost Mode

### ISSUE THREAD

**Issue by rusagent** [UnigramDev/Unigram#2416]
Is there something like Ghost Mode implemented? So like - when the app is open other people can't see my online status? Like in BoomChat for Andoid?

**Comment by Aquathing** [comment]
![image](https://user-images.githubusercontent.com/81624781/121787979-db1e6780-cbc9-11eb-9dca-a6167198341a.png)
https://core.telegram.org/api/terms

**Comment by MarcAnt01** [comment]
Hello, as pointed out by @Aquathing , this goes against Telegram TOS, so it won't be taken into account
