### ISSUE TITLE
Automatic unasked auto-completion after sending a message

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2417]
**Describe the bug**
If I write /s and there's a bot command starting with /s like /stat@combobot it'll be automatically completed, but just once it's sent, before pressing enter it still appears as "/s"

**To Reproduce**
1. Add combobot to a group
2. Type /s and press enter without adding a space

**Expected behavior**
No autocomplection or at least perform it in a way that I'm aware it happened

**Version Info**
 - Unigram: 7.8.6524 x64
 - Windows: 10 21H1

**Comment by FrayxRulez** [comment]
This is pretty much the standard behavior of all desktop apps

**Comment by MarcAnt01** [comment]
> This is pretty much the standard behavior of all desktop apps

Telegram desktop doesn't do that actually

**Comment by Aquathing** [comment]
> > This is pretty much the standard behavior of all desktop apps
> 
> Telegram desktop doesn't do that actually

Uh, actually, it does :D

**Comment by MarcAnt01** [comment]
> > > This is pretty much the standard behavior of all desktop apps
> > 
> > 
> > Telegram desktop doesn't do that actually
> 
> Uh, actually, it does :D

I followed the repro steps and didn't happen for me...

**Comment by Aquathing** [comment]
https://user-images.githubusercontent.com/81624781/122614202-7b6f0300-d086-11eb-8d52-6154996e1959.mp4

**Comment by MarcAnt01** [comment]
Try combot + group.
That's what I am talking about

**Comment by Aquathing** [comment]
https://user-images.githubusercontent.com/81624781/122617531-bbd17f80-d08c-11eb-86f0-ff485ce75318.mp4

**Comment by FrayxRulez** [comment]
Can I close this?

**Comment by MarcAnt01** [comment]
In my opinion it should stay open unless you have a particular reason for this to happen

**Comment by FrayxRulez** [comment]
Users expect this behavior to be consistent across apps
