### ISSUE TITLE
Two Step Verification page issues

### ISSUE THREAD

**Issue by makisukurisu** [UnigramDev/Unigram#2418]
**Describe the bug**
Some things are broken in 2FA page.
For instance:

- Email formatting
- Some strings are in brackets (when submitting email)
- Continue button (in confirm) not proceeding
- "change email" button not working
- "Back" button not working

**To Reproduce**
Just set up 2FA as usual.

**Expected behavior**
Continue button to proceed, back to revert, change email to allow change email, strings without [ ] around them and email formatted.

**Screenshots**
![image](https://user-images.githubusercontent.com/49622129/122065274-7a29a600-cdfa-11eb-8e16-3147c742d747.png)
brackets and formatting issue.

**Version Info**
 - Unigram: v 7.8.6524
 - Windows: 21H1 (doesn't affect)

**Additional context**
Video: https://t.me/htgkjl/178 (just 0.7 mb larger then GH allows)
Probably not much of a bug actually.

**Comment by cewbdex** [comment]
![image](https://user-images.githubusercontent.com/9021297/145211414-5f7e55bf-65bb-4f81-9a0b-7011231218fe.png)
Button is out of screen area.

**Comment by FrayxRulez** [comment]
We have this on bugs.telegram.org now
