### ISSUE TITLE
Cannot mention people without a nickname

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2419]
**Describe the bug**
Cannot mention people without a nickname in groups

**To Reproduce**
1. Get in a group with someone with no username;
2. Try to mention him (you'll get a horrible color that should highlight th emention, but that's not the point of the ticket);
3. Send the message and see that no mention has been actually added

**Expected behavior**

**Version Info**
 - Unigram: 7.8.6524 x64
 - Windows: 10 21H1

**Comment by thisisartman** [comment]
@MarcAnt01 lmao that horrible color is an issue in and of itself

**Comment by MarcAnt01** [comment]
> @MarcAnt01 lmao that horrible color is an issue in and of itself

There should already be a ticket somehow somewhere
