### ISSUE TITLE
Missing cache system

### ISSUE THREAD

**Issue by no-nevis** [UnigramDev/Unigram#242]
When your network is slow and unigram cant load all of the message list, you can feel the need of a cache system that saves all messages and only load new messages when updating.

**Comment by Jack-Works** [comment]
And sometimes, after unigram connected to the server, message list will be empty, and I need to search the chat I want to start my chat

**Comment by bugada** [comment]
Sometimes it happens to me too, as a workaround i click on the 'go to last message' arrow, and the chat appears without leaving it.

**Comment by Jack-Works** [comment]
![image](https://user-images.githubusercontent.com/5390719/29551769-edd99e42-8746-11e7-8036-57dfe1b597f2.png)
Every time I open unigram it will be blank, and after I connected to the server, only chat related to the new message received will be displayed in chat list. It is not quite usable.
![image](https://user-images.githubusercontent.com/5390719/29551820-31e7c622-8747-11e7-872b-34e43375695f.png)

**Comment by Jack-Works** [comment]
@bugada where is the "go to last message" arrow?

**Comment by Jack-Works** [comment]
Any progress on this? Without this feature, Unigram is almost not usable in the slow network (using the proxy).
Thanks
@larsschellhas

**Comment by Charmandrigo** [comment]
I mean the Skype app does this, meaning is not impossible to integrate a cache

**Comment by FrayxRulez** [comment]
The fact that is possible doesn’t mean that is east :) also Skype content is quite simple compared to telegram entities

**Comment by Jack-Works** [comment]
Oh, but Skype has a very good connectivity, telegram has none. CN users have to use unstable proxy to access telegram

**Comment by FrayxRulez** [comment]
That’s due to China government, not due telegram servers.

**Comment by Jack-Works** [comment]
Okay, I'm sorry to bother you. give up to track this issue.

**Comment by FrayxRulez** [comment]
Well, what I'm saying is that everyone knows that a local messages database is important, but no one here is able to implement it.

**Comment by callummoffat** [comment]
@Jack-Works It's not that we don't recognize the importance of a local cache. It's just that no one here currently has the skillset to implement it. Telegram's API has a non-trivial data model setup - Skype is simple by comparison.

I believe the intent is to implement at some point. But because no-one has the requisite skillset, we can't really do anything at this time.

**Comment by Jack-Works** [comment]
Oh.. I'm sorry for my offensive language. Just, feel sad.

**Comment by callummoffat** [comment]
Don’t worry, I’m not offended at all. I understand your frustration completely, and I’m sure Fela can relate also.

We’d implement it immediately if we could, but unfortunately we can’t. If we ever get to the point where implementing a full local cache is feasible, I’ll try and make sure you’re the first to know.

**Comment by Jack-Works** [comment]
Emm. Can we make it step by step? Like, make message list first cached without any message cached?
At least there will no more blank screen.

**Comment by callummoffat** [comment]
Same problem. If you take a look at the code, I think you’ll find that even a partial cache implementation for Unigram (i.e. one that doesn’t fully cache all data) is rather complex.

Simple answer: unfortunately not.

**Comment by Jack-Works** [comment]
Wow, the new version handle this problem well! Good job!

**Comment by FrayxRulez** [comment]
This is going to be solved with X update: https://t.me/unigram/162
