### ISSUE TITLE
Screen Sharing on Xbox

### ISSUE THREAD

**Issue by HitaloM** [UnigramDev/Unigram#2421]
Unigram 7.8 will support screen sharing in voice chats, will this feature be available on Xbox? Some apps support this as the Twitch app.

**Comment by FrayxRulez** [comment]
Graphics capture APIs | Windows.Graphics.Capture is not supported for Xbox.

https://docs.microsoft.com/en-us/uwp/extension-sdks/uwp-limitations-on-xbox

**Comment by FrayxRulez** [comment]
Considering that there's absolutely nothing that can be done here I will close this ticket
