### ISSUE TITLE
Cannot copy user info with touch

### ISSUE THREAD

**Issue by xperiandri** [UnigramDev/Unigram#2422]
**Describe the bug**
On a user info page (where a user name and phone located) if I long tap on the phone or user name nothing happens.

**To Reproduce**
1. Go to any user details by clicking on its name in the chat
2. Long tap on a user name or phone
3. Nothing happens

**Expected behavior**
Either context menu opens as with right-click.
On a single tap or mouse left-click the info item is copied to the clipboard and a notification about that appears.

**Version Info**
 - Unigram: 7.7.6247 x64
 - Windows: May 2021 update

**Comment by MarcAnt01** [comment]
Hello @xperiandri , I cannot reproduce this on Unigram 7.8.x
Can you try and see if this persists in https://t.me/unigramappx/145?

**Comment by xperiandri** [comment]
I'll check

**Comment by MarcAnt01** [comment]
Any news @xperiandri ?

**Comment by xperiandri** [comment]
Now it works
