### ISSUE TITLE
[ru] Missing strings (localization)

### ISSUE THREAD

**Issue by VladWinner** [UnigramDev/Unigram#2423]
1) Unigram/Unigram/Unigram/Strings/ru/Additional.resw
[Additional.resw.zip](https://github.com/UnigramDev/Unigram/files/6679143/Additional.resw.zip)

2) Unigram/Unigram/Unigram/Views/Settings/SettingsAdvancedPage.xaml
```
"Adaptive Layout for Wide Screens"
→lng_settings_adaptive_wide→
"Выравнивание для широких экранов"

"Try connecting through IPv6"
→lng_connection_try_ipv6→
"Пытаться подключаться через IPv6"

"Show Tray Icon"
→lng_settings_workmode_tray→
"Показывать значок в области уведомлений"
```

3) Unigram/Unigram/Unigram/Controls/StartupSwitch.xaml
```
"Launch Unigram when system starts"→
"Запускать Unigram вместе с системой"

"Launch minimized"
→lng_settings_start_min→
"Запускать в свёрнутом виде"
```

4) Unigram/Unigram/Unigram/ViewModels/Settings/SettingsAdvancedViewModel.cs
```
"Check for Updates"
→lng_settings_check_now→
"Проверить обновления"

"You have the latest version of Unigram."→
"У вас установлена свежая версия Unigram."

"Please update the app to get the latest features and improvements."
→/macos/settings/AppUpdate.NewestAvailable→
"Чтобы пользоваться всеми новыми возможностями, обновите приложение."

"Downloading... {0} / {1}"→
"Загрузка... {0} / {1}"

"Retrieving Information..."
→/macos/settings/AppUpdate.RetrievingInfo→
"Загрузка информации..."
```

5) Unigram/Unigram/Unigram/Views/Popups/SettingsEmojiSetPopup.xaml.cs
```
"Emoji Set"
→/android_x/settings/Emoji→
"Набор эмодзи"

"Downloading"→
"Загрузка"

"Current Set"
→lng_emoji_set_active→
"Текущий набор"

"Downloaded"
→lng_emoji_set_ready→
"Загружен"
```

6) Unigram/Unigram/Unigram/Views/Settings/SettingsAppearancePage.xaml
```
"Emoji Set"
→/android_x/settings/Emoji→
"Набор эмодзи"

"Enable full-screen gallery"→
"Галерея в полноэкранном режиме"

"Disable mispelled words highlight"→
"Не выделять слова с ошибками"

"Replace Emojis"→
"Заменять эмодзи"
```

7) Unigram/Unigram/Unigram/Views/Popups/SelectColorPopup.xaml
```
"Use system accent color"→
"Взять цвет из системы"
```

8) Unigram/Unigram/Unigram/Views/Settings/SettingsPrivacyAndSecurityPage.xaml
```
"Sensitive Content"
→lng_settings_sensitive_title→
"Материалы деликатного характера"

"Display sensitive media in public channels on all your Telegram devices."
→lng_settings_sensitive_about→
"Отображать материалы деликатного характера в публичных каналах на всех устройствах."

"Disable Filtering"
→lng_settings_sensitive_disable_filtering→
"Выключить ограничения"
```

9) Unigram/Unigram/Unigram/Views/Folders/FoldersPage.xaml
```
"Tabs view"→
"Вид вкладок"

"If you have many folders, try moving tabs on the left."
→/macos/chat_list/ChatList.Filter.TabBar.Desc→
"Если папок много, попробуйте передвинуть панель влево."

"Tabs at the top"
→/macos/chat_list/ChatList.Filter.TabBar.OnTheTop→
"Панель вверху"

"Tabs on the left"
→/macos/chat_list/ChatList.Filter.TabBar.OnTheLeft→
"Панель слева"
```

10) Unigram/Unigram/Unigram/Controls/FormattedTextBox.cs
```
"Spelling"
→lng_spellchecker_submenu→
"Проверка орфографии"

"Formatting"
→lng_menu_formatting→
"Форматирование"

"Edit link"
→lng_menu_formatting_link_edit→
"Изменить ссылку"

"Hide formatting"→
"Скрыть панель"

"Show formatting"→
"Показать панель"

"Undo"
→lng_wnd_menu_undo→
"Отменить"

"Redo"
→lng_wnd_menu_redo→
"Повторить"

"Cut"
→lng_mac_menu_cut→
"Вырезать"

"Copy"
→lng_mac_menu_copy→
"Копировать"

"Paste"
→lng_mac_menu_paste→
"Вставить"

"Delete"
→lng_mac_menu_delete→
"Удалить"

"Select All"
→lng_mac_menu_select_all→
"Выбрать всё"
```

**Comment by MarcAnt01** [comment]
Thanks for your accurate report, Unigram anyway uses strings from the Android app and the correlated official Telegram translations, missing strings are the ones which are not in the Android app, so currently there are no plans to localize additional strings unless @FrayxRulez changes his mind.

**Comment by VladWinner** [comment]
![image](https://user-images.githubusercontent.com/13555921/122621386-0f989480-d09e-11eb-8b87-91d45637f6b4.png)
TDesktop (left) → Unigram (right)

It's just an example.

**Comment by MarcAnt01** [comment]
> ![image](https://user-images.githubusercontent.com/13555921/122621386-0f989480-d09e-11eb-8b87-91d45637f6b4.png)
> 
> TDesktop (left) → Unigram (right)
> 
> 
> 
> It's just an example.

It's easy for Telegram Desktop since they have their own translations platform where they can put all the strings that they want

**Comment by VladWinner** [comment]
> It's easy for Telegram Desktop since they have their own translations platform where they can put all the strings that they want

In my first message I added source string IDs taken from [translations.telegram.org](https://translations.telegram.org/) where possible. All localizations accumulate there and freely available, don't they? 😟

**Comment by MarcAnt01** [comment]
They are freely available, but it's very complex to build a structure with multiple localization and sources, not saying that it's not possible.

**Comment by FrayxRulez** [comment]
Hey @VladWinner, currently Unigram translations are stored in cloud, as I use Telegram APIs to retrieve Android langpack.
To make this possible, the app must subscribe for a langpack to Telegram servers, so that they can notify it when there's any change.
Unfortunately this logic doesn't allow to use multiple langpack simultaneously (Android was chosen because text-wise it is the most complete).

**Comment by MarcAnt01** [comment]
Since the strings have been added via that commit, I guess this can be closed

**Comment by VladWinner** [comment]
@MarcAnt01 But there are still some strings without translation.
![image](https://user-images.githubusercontent.com/13555921/187508490-f6d9f412-de22-4cd9-85c6-db8a8c696a90.png)
![image](https://user-images.githubusercontent.com/13555921/187508525-abaddda5-ab16-4275-8a48-618db5696bfd.png)

**Comment by VladWinner** [comment]
Missing lines were added via https://translations.telegram.org/ru/unigram/
