### ISSUE TITLE
Displacement of comment section for video notes

### ISSUE THREAD

**Issue by makisukurisu** [UnigramDev/Unigram#2424]
**Describe the bug**
When video note is posted in channel with comments enabled "comments" button is placed to the right of video note.

**To Reproduce**
1. Go to https://t.me/unitestacces/5
2. See wrong displacement

**Expected behavior**
Comment button right under video note, or in small circle to the right of vn

**Screenshots**
![image](https://user-images.githubusercontent.com/49622129/122637286-6d58cb00-d0f6-11eb-93e9-1df8d6847e5f.png)

**Version Info**
 - Unigram: v7.8.6540
 - Windows: 21H1 (doesn't matter)

**Additional context**
Thanks to @jorge_hdez for [pointing out this issue](https://t.me/unigraminsiders/354312)

**Comment by makisukurisu** [comment]
"Quick" note, same seems to happen to everything that is not bounded by "message box" sort of speak.
So [this ](https://t.me/unitestacces/6) (and [that](https://t.me/unitestacces/7)) is (are) also having same trouble with displacement

**Comment by FrayxRulez** [comment]
Fixed
