### ISSUE TITLE
Map scrolling scrolls page too

### ISSUE THREAD

**Issue by makisukurisu** [UnigramDev/Unigram#2432]
**Describe the bug**
When you zoom out on a map (send location for eg) you also scroll down the content of whole layout.

**To Reproduce**
1. Go to chat
2. Click on "Attach media"
3. Choice "Location"
4. Scroll down on map -> here you are

**Expected behavior**
To either: 

- only map react on scroll (inside the map)

- not zoom map without ctrl

**Version Info**
 - Unigram: v7.8.6540
 - Windows: 21H1

**Additional context**
Comment: I'm 70% sure this is something that can't be fixed, but still it would be great, if it is.
Thanks

When said "not zoom map without ctrl" this would be handy to see:
![image](https://user-images.githubusercontent.com/49622129/122821333-5deba480-d2e5-11eb-8e01-98ee836d0f50.png)

**Comment by FrayxRulez** [comment]
Map has been removed
