### ISSUE TITLE
Unigram has started loosing some messages

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2433]
**Describe the bug**
Some messages do not appear in the chat of a group
**To Reproduce**

I don't have repro steps unfortunately

**Expected behavior**
See the whole history
**Screenshots**
Example 1
![image](https://user-images.githubusercontent.com/43090263/122901919-501e3980-d34e-11eb-84ed-2163fef6cc6b.png)
![image](https://user-images.githubusercontent.com/43090263/122902034-69bf8100-d34e-11eb-931b-4a11ddc691dc.png)

Example 2
![image](https://user-images.githubusercontent.com/43090263/122903027-4ba65080-d34f-11eb-9d1d-98d3dec4cfd0.png)
![image](https://user-images.githubusercontent.com/43090263/122903053-5234c800-d34f-11eb-98a0-57e4b394d257.png)

**Version Info**
 - Unigram: 7.8.6540
 - Windows: 10 21H1

**Comment by FrayxRulez** [comment]
This should be reported to Telegram/TDLib.
