### ISSUE TITLE
Don't show share button when there's no associated sticker pack

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2434]
**Describe the bug**
If there's no associated sticker pack, because it's been deleted

**To Reproduce**
1. Use Telegram gold meme sticker
2. Click on it
3. See the pop-up

**Expected behavior**
Don't show it in this scenario

**Screenshots**
![image](https://user-images.githubusercontent.com/43090263/122940958-38a67700-d375-11eb-8faa-47f9664df09c.png)

**Version Info**
 - Unigram: 7.8.6540 x64
 - Windows: 10 21H1

**Comment by FrayxRulez** [comment]
Done
