### ISSUE TITLE
Screen sharing in 1-on-1 calls

### ISSUE THREAD

**Issue by revanmj** [UnigramDev/Unigram#2439]
Screen sharing is only available in group calls, but not in 1-on-1 calls (while in my case, I need it more in the latter case).

**Comment by MarcAnt01** [comment]
Hello, unfortunately Telegram designed screen sharing feature to be available only on group calls

**Comment by binamracode** [comment]
@MarcAnt01 Is this really possible?

**Comment by MarcAnt01** [comment]
Done in https://github.com/UnigramDev/Unigram/commit/954811f9dc56aed62a3f2eb757583fc9928e4cc1
