### ISSUE TITLE
Can't set profile picture

### ISSUE THREAD

**Issue by VadimMuhtarov** [UnigramDev/Unigram#2440]
**Describe the bug**
I can't set profile picture in Unigram 

**To Reproduce**
Go to settings, press "photo" button, select picture, press Set. Nothing happens

**Version Info**
 - Unigram 7.8.6567 x64
 - Windows 10 21H1 19043.1081

**Comment by MarcAnt01** [comment]
@VadimMuhtarov can you still reproduce this issue?

**Comment by VadimMuhtarov** [comment]
I don't use Windows anymore
