### ISSUE TITLE
Multiaccount adding bug

### ISSUE THREAD

**Issue by neilideal** [UnigramDev/Unigram#2441]
**Describe the bug**

**To Reproduce**
1. Go to 'navigation menu'
2. Add an account (with login)
3. Add same account

**Expected behavior**
When adding an account to the beta version, the same account can be added several times.

**Version Info**
 - Unigram: [e.g. 7.8.6583 x64]
 - Выпуск	Windows 11 Pro Build	22000.51
![5393455699813577966_121](https://user-images.githubusercontent.com/62957728/123858197-e8f31d00-d92b-11eb-9ef1-3b710bf1702b.jpg)

**Comment by FrayxRulez** [comment]
Did you login via QR code?
