### ISSUE TITLE
Message counter "messages" hides after resizing window back

### ISSUE THREAD

**Issue by makisukurisu** [UnigramDev/Unigram#2442]
**Describe the bug**
If you resize window so "*N* messages" => "*N*" when selecting messages, and then resize window back to state where it can be as first app will keep using short form. 

**To Reproduce**
1. Go to chat, select messages (from 1)
2. Resize chat so counter only consists of number of selected messages
3. Resize it back
4. See that counter is still in short form

**Expected behavior**
Counter text to return to long form of "*N* messages"

**Screenshots**
No, but video is in additional.

**Version Info**
 - Unigram: v 7.8 6589 x64
 - Windows: 21H1

**Additional context**
[Video](https://t.me/htgkjl/189)

**Comment by makisukurisu** [comment]
Edit. You don't need to select messages before you resize. Just resizing (to sizes where "messages" doesn't appear) the app is enough to make this bug occur. So - you can resize it, don't select anything, resize it back to big window and only then select messages, and counter will consist only of number.

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/75e81f5dbab20aa3f13360e43012a71590abbfc8
