### ISSUE TITLE
When deselecting messages "selection" layout may stay

### ISSUE THREAD

**Issue by makisukurisu** [UnigramDev/Unigram#2443]
**Describe the bug**
If you deselect all messages and release mouse over non chat area like selection bar or chat list, or outside the window selection layout will stay until you click on chat area again.

**To Reproduce**
1. Go to any chat/group
2. Select messages
3. Deselect all messages but release mouse button over area which is not chat area (where messages are and which bounds you can see by selecting last message)
4. See layout still present
5. Get rid of layout by clicking X button or clicking inside chat are once.

**Expected behavior**
Layout to disappear no mater where mouse was released if no messages are selected.

**Screenshots**
![image](https://user-images.githubusercontent.com/49622129/123914657-4cab3380-d988-11eb-9d02-8e27d0c3186c.png)

**Version Info**
 - Unigram: v 7.8 6583
 - Windows: 21H1

**Additional context**
[Video](https://t.me/htgkjl/190)

**Comment by FrayxRulez** [comment]
It's ok
