### ISSUE TITLE
Camera switching in private calls

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2445]
Now that group calls have the ability to switch the camera, I'd like to see this feature as well for private calls since mobile apps have it too. It could make sense also to add a straightforward "flip camera" button

**Comment by FrayxRulez** [comment]
It's already available in private calls.

**Comment by MarcAnt01** [comment]
> It's already available in private calls.

It doesn't seem to be working

**Comment by MarcAnt01** [comment]
While in group calls it's working properly

**Comment by FrayxRulez** [comment]
Feel free to fix the bug then
