### ISSUE TITLE
[suggestion] fast way of answering messages

### ISSUE THREAD

**Issue by ctwoon** [UnigramDev/Unigram#2448]
Official Telegram client has button which allows to answer message in a fast way. To answer message using Unigram you have to do right click and then do another click. It would be cool if there was another way of answering messages (for example - double click on bubble).

**Comment by makisukurisu** [comment]
@ctwoon Double click outside the bubble is a thing. Also you can reply to recent messages using ctrl+up/down

**Comment by MarcAnt01** [comment]
@ctwoon in Unigram you can double click to answer a message, just not on the bubble, but next to it

**Comment by ctwoon** [comment]
thanks.
