### ISSUE TITLE
Message prefixes //accessibility

### ISSUE THREAD

**Issue by Yeldece** [UnigramDev/Unigram#2449]
Hello,
There is a nondecable prefix problem going on since a while.
First I want to show how it was and how it changed.
Beginning of the unigram, message prefixes were as follows:
Groups:
Person 1. this is my first message 
this is my second message
hello person 1 I am an blind unigram user and this is my first message, I am the sender.
hello person 1 I am an blind unigram user and this is my second message, I am the sender.
///as you see there was no prefix for the unigram user.
Then it changed to:
Groups/private all prefixed:
person 1. This is my first message
person 1. This is my second message
unigram user (sender view). this is my first message
unigram user (sender view). this is my second message
Currently prefixes are as follows:
Groups:
person 1. This is my first message
person 1. This is my second message
hello person 1 I am an blind unigram user and this is my first message, I am the sender.
hello person 1 I am an blind unigram user and this is my second message, I am the sender.
Private chat literaly no prefix!:
this is my first message I gues my name is not important at all.
this is my second message
hello person 1 I am an blind unigram user and this is my first message, I am the sender.
hello person 1 I am an blind unigram user and this is my second message, I am the sender.

So, current view is wrong, because:
In a private chat, I never have to keep in my mind who send which message nor I don't have to wait listening end of the message to hear received or sent, as requested to people.
Received/sent tag is not that easy in every language
Not every message include only "lol" which you can easly hear received or sent tag
In groups, it makes a bit sense, but people often changing their name to misterous letters which can't read by every senthesiser so sender should get a tag like "you"
I'm glad to share, current system unigram uses, never used, or using by any other instant messaging app which shows how wrong it is.

How it should be?
There is two logical solution I am aware of
1: Telegram iOS 
Person 1, this is my first message 
Person 1, this is my second message
Your message, hello person 1 I am an blind telegram iOS user and this is my first message, I am the sender.
Your message, and this is my second message, I am the sender.
SAME FOR BOTH GROUP AND PRIVATE!
2: Older telegram web (current one got wrecked), my personal preference, but less logical I agree that.
Person 1. this is my first message 
this is my second message
Your username, hello person 1 I am an blind telegram web  user and this is my first message, I am the sender.
and this is my second message, I am the sender.
SAME FOR BOTH GROUP AND PRIVATE!

Thanks for your time and reading this.

**Comment by MarcAnt01** [comment]
Hello @Yeldece thanks for reporting that, since this is a bug report when creating a new issue you should select "bug report" and not "anything else" and fill the template in every field.

**Comment by MarcAnt01** [comment]
Please create a new issue as I said, so that I can close this one
