### ISSUE TITLE
Keyboard area still present after hiding keyboard. Missing stickers panel as well because replymarkup keyboard

### ISSUE THREAD

**Issue by dmnmsc** [UnigramDev/Unigram#245]
Using development build:
Open keyboard on mobile and hide it. You will see a black space where the keyboard was. Opening stickers panel shows that black space as well (replymarkup keyboard area).

**Comment by larsschellhas** [comment]
I cannot reproduce this issue. Could you provide us with a screenshot?

**Comment by FrayxRulez** [comment]
Fixed
