### ISSUE TITLE
Unknown item in the tab list, before a voice message

### ISSUE THREAD

**Issue by Yeldece** [UnigramDev/Unigram#2452]
**Describe the bug**
In the message list when you press tab on a voice message, an unknown item appears just before the play link.
**To Reproduce**
Enable any screen reader,
press tab on a voice message 
**Expected behavior**

**Screenshots**

**Version Info**
 - Unigram: 7.8 (6583) X64 Debug
 - Windows: Windows 10 20H2 (64-bit) build 19042.1052

**Additional context**

**Comment by FrayxRulez** [comment]
Fixed
