### ISSUE TITLE
Unavailable to connect the system proxy in Windows 11

### ISSUE THREAD

**Issue by CuteCatXiao** [UnigramDev/Unigram#2453]
![image](https://user-images.githubusercontent.com/62191675/124345812-b2f4b800-dc0d-11eb-9fd7-f606ccc70182.png)
![image](https://user-images.githubusercontent.com/62191675/124345823-c142d400-dc0d-11eb-8078-e8d53f90bd41.png)
Using Clash For Windows. Other apps like edge is able to surf on google so system proxy is working properly , China user.

**Comment by makisukurisu** [comment]
You have to enable local proxy using this command in PowerShell:
`Get-AppxPackage | %{$_.PackageFamilyName} | where{$_ -match "unigram"} | %{CheckNetIsolation LoopbackExempt -a -n="$_"}`

Comment if it will work thereafter.

**Comment by CuteCatXiao** [comment]
Yep. I'm an stupid idot. I don't expected the UWP Loopback will unfunctioning during update to Windows 11...

**Comment by nd4y** [comment]
> You have to enable local proxy using this command in PowerShell: `Get-AppxPackage | %{$_.PackageFamilyName} | where{$_ -match "unigram"} | %{CheckNetIsolation LoopbackExempt -a -n="$_"}`
> 
> Comment if it will work thereafter.

For Windows 10 LTSC where there is no Get-AppxPackage cmdlet

```
Get-ChildItem "HKCU:\Software\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppModel\Repository\Families" |
  Select-Object -ExpandProperty PSChildName |
  Where-Object {$_ -match "unigram"} |
  ForEach-Object { CheckNetIsolation LoopbackExempt -a -n="$_" }

```
