### ISSUE TITLE
Chat field's context menu does not close via Esc if invoked when quoting

### ISSUE THREAD

**Issue by KeronCyst** [UnigramDev/Unigram#2456]
**Describe the bug**
When a quote/reply + the context menu are simultaneously active while drafting a message, Unigram prioritizes closing the quote first, and then the context menu gets ignored entirely and can't be keyboarded back to to close mouse-less-ly

**To Reproduce**
1. Open any chat
2. Press Ctrl-Up or right-click to quote/"Reply" to any message
3. Press Apps Key (or right-click in the text field) to bring up the context menu
4. Press Escape twice to try to close the context menu
5. The quote gets closed but the context menu stays open

**Expected behavior**
The first press of Escape should close the context menu first, and _then_ any next Escape should cancel the quote

**Screenshots**
N/A

**Version Info**
Unigram 7.8 (6567) X64
Windows 10 Home 21H1

**Additional context**
We like our keyboards!

**Comment by thisisartman** [comment]
YES!!!!!!!!!!!!!! Same!!! Good call pointing this out.
Attaching a recording for reference. the key presses are me obliterating my ESC button. Also, ignore those background voices.
https://user-images.githubusercontent.com/85949613/124389750-35f93980-dd06-11eb-857a-5d63175df324.mp4

**Comment by xperiandri** [comment]
Indeed!
