### ISSUE TITLE
Unable to write capital ż letter

### ISSUE THREAD

**Issue by AveoCross** [UnigramDev/Unigram#2459]
**Describe the bug**
I don't know if its a bug but i cannot write capital letter Ż from Polish QWERTY (right shift + right alt + z). Every other app works without a problem.

**To Reproduce**
1. Go to message writing field
2. Try to write capital Ż while using Polish language (right shift + right alt + z)

**Expected behavior**
Able to write capital Ż. 

**Version Info**
 - Unigram: [e.g. 7.8 (6567) x64]
 - Windows: 21H1 / 19043.1081

**Comment by FrayxRulez** [comment]
I want to provide some context here as this is somehow ridiculous.
The app handles some shortcuts by itself (obviously), and one of them is `Ctrl+Shift+Z`, that is used to redo changes, as this behavior is not provided by the platform.
To do this, the app listens for `Z` key to be pressed, and then uses the system call `CoreWindow.GetKeyState` to verify if `Control` and `Shift` keys are down.
Now, the interesting thing is that if you hold your `Right Alt` key, `GetKeyState` will report `Control` to be also pressed, causing the shortcut to be executed and text changes to be ignored.
The solution is quite simple and it's actually to make sure that `Alt` is not also pressed while checking for the redo shortcut, yet this is clearly a patch to a system bug.
