### ISSUE TITLE
Better commit messages

### ISSUE THREAD

**Issue by auchri** [UnigramDev/Unigram#246]
Hi,

please write better commit messages!

This is especially important for new contributors, which have to comprehend why some code has been added or written like that.

If I take a look at the recent commits of this project, there are a lot of commits which have no meaningful message:

 * ![image](https://cloud.githubusercontent.com/assets/5092164/24578638/a214a70e-16e4-11e7-9ed5-9d06f51ecd0a.png)
* ![image](https://cloud.githubusercontent.com/assets/5092164/24578641/afa47e94-16e4-11e7-886c-c689b7997e17.png)
* ![image](https://cloud.githubusercontent.com/assets/5092164/24578643/bd7cb144-16e4-11e7-8f53-06218890a8fc.png)
* ![image](https://cloud.githubusercontent.com/assets/5092164/24578645/c8960864-16e4-11e7-87b2-9b2e8c385eea.png)
* ![image](https://cloud.githubusercontent.com/assets/5092164/24578647/d1059a32-16e4-11e7-9a67-62932ee1bed9.png)
* ![image](https://cloud.githubusercontent.com/assets/5092164/24578654/eac5485a-16e4-11e7-84ce-7c20a2d9aa55.png)

How to Write a Git Commit Message: https://chris.beams.io/posts/git-commit/

**Comment by franzalex** [comment]
I think this should be stated clearly in the contribution rules.
In addition, pull requests of such nature should not be merged until users have updated their commit messages to something more reasonable.

**Comment by theweavrs** [comment]
The commit messages are awful, I agree and should be changed. They are just amazingly funny though.

**Comment by auchri** [comment]
![image](https://cloud.githubusercontent.com/assets/5092164/26253342/5723ff70-3cb3-11e7-853d-bf11eb092d3e.png)

**Comment by Lonami** [comment]
Useful and atomic commits are important. We should forward this issue to @DrKLO while we're at it.

**Comment by ikarago** [comment]
We tried to improve our commit messages (some of the samples included were originally part of some poking fun at each other I eternally) and I think the messages are quite clear nowadays. That's why I'm closing this issue.

Feel free to open a new issue if you guys disagree, but don't expect a complete log each commit message that goes into deep detail. We have the Files Changed tab for that ;)
