### ISSUE TITLE
User mention button is out of borders when sending media to chat

### ISSUE THREAD

**Issue by makisukurisu** [UnigramDev/Unigram#2461]
**Describe the bug**
When you mention someone in caption to media the "button" with name and nickname is stretched beyond textbox and media itself, so it's above padding of whole window.

**To Reproduce**
1. Go to any chat where you can send messages
2. Paste some media ([cat](https://img.webmd.com/dtmcms/live/webmd/consumer_assets/site_images/article_thumbnails/other/cat_relaxing_on_patio_other/1800x1200_cat_relaxing_on_patio_other.jpg) s are good example)
3. Enter @ 

**Expected behavior**
Those buttons should end where textbox ends on X axis (horizontally)

**Screenshots**
![How it looks](https://user-images.githubusercontent.com/49622129/124901876-15bdc900-dfeb-11eb-8331-e46bb5b2a9ce.png)
How it looks right now ⬆️ 
How I'd like to see it ⬇️ 
![How I see it](https://user-images.githubusercontent.com/49622129/124902232-6b927100-dfeb-11eb-8d89-ee7e3ee07cd9.png)

**Version Info**
 - Unigram: v 7.8 6583
 - Windows: 21H1

**Additional context**
I'd like to ask - if it's possible to also make first button rounded on top. Would be nice, but if it will overcomplicate things - not needed.
Also - note that content (username) is not shown even to my imagined border.

**Comment by FrayxRulez** [comment]
Done
