### ISSUE TITLE
secret chat hotfix date

### ISSUE THREAD

**Issue by kolomenkin** [UnigramDev/Unigram#2462]
@FrayxRulez , could you tell approx. the date when the followinf hotfix will get released in Windows?

https://github.com/UnigramDev/Unigram/issues/2451

https://github.com/tdlib/td/commit/bed2650b4c52b54a009a2df5d40be16497467f59

**Comment by makisukurisu** [comment]
@kolomenkin Don't create an issue for question.
You can comment under #2451 issue (also, use # to mention specific issue of same repository) or write in chat.

**Comment by MarcAnt01** [comment]
Hello, please follow what @makisukurisu said and keep in mind that this is a foss project, so the devs aren't required to give an eta for everything

**Comment by kolomenkin** [comment]
@makisukurisu, sorry, what chat did you mention?

**Comment by makisukurisu** [comment]
@kolomenkin https://t.me/unigraminsiders

That one.

**Comment by FrayxRulez** [comment]
The hotfix was released today in the store

**Comment by kolomenkin** [comment]
@FrayxRulez Wow! Thanks a lot for you job and help!

@makisukurisu, thank you too for pointing the chat!
