### ISSUE TITLE
Back button overlapping unmute icon when selecting chats

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2464]
**Describe the bug**
Back button overlapping unmute icon when selecting chats

**To Reproduce**
1.Select a chat

**Expected behavior**
Overlapping are never intended

**Screenshots**
![image](https://user-images.githubusercontent.com/43090263/125064027-7c58ea80-e0b0-11eb-9918-b2fe898176b0.png)
**Version Info**
 - Unigram: 7.8.6583
 - Windows: 11 Insider preview

**Comment by makisukurisu** [comment]
Also it doesn't work (at least for me, at the time), so it may be a bug that it's shown at all.

**Comment by MarcAnt01** [comment]
> Also it doesn't work (at least for me, at the time), so it may be a bug that it's shown at all.

That's probably caused by the overlapping

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/aaa34f6c0333560ff590bd26fcd06082f8c9ebb0
