### ISSUE TITLE
Unigram crashes when making a audio call. it will crash twice and on the third time it would work. crashes every day.

### ISSUE THREAD

**Issue by iHarryPotter178** [UnigramDev/Unigram#2468]
**Describe the bug**
When I try to make a audio call, Unigram crashes, I open it again, and make the call it crashes again, and when I open it again and make a call, the call goes through. It happens all the time, everyday. but not always. it will definitely crash when making the call for the first time after turning on the pc. after a call goes through, it may not crash for subsequent calls, not always.

**To Reproduce**
1. Go to 'restart pc, then go to any chat in unigram'
2. Click on 'the audio call button, it happens when making video call too, but I make less video call'
4. it will crash

**Expected behavior**
it should not crash. 

**Screenshots**
not applicable.
**Version Info**
 - Unigram: [e.g. 7.8.6339 x64] and previous version to. there was a version which didn't crash as frequently but forgot which one.
 - Windows: 10 21H1 and Windows 11 build 22000.65

**Additional context**
The official Telegram desktop client never crashes. sometimes when I have to make a call quickly I open the desktop version and it works like a charm.

**Comment by makisukurisu** [comment]
Can you update an app and reproduce bug? I'm on 6583 and I can't reproduce this issue.

Maybe it's due to Windows 11. If it's true - I'm not sure if there is a way to solve issue right away since (from what I've heard) crash reports are different and useless from Win 11 to Win 10.

Thanks for letting us know about the issue, try purposed step and write a comment.

**Comment by FrayxRulez** [comment]
I'm not able to reproduce the issue. A crash dump might be helpful.

**Comment by iHarryPotter178** [comment]
I can't reproduce the issue either. Just checked a few times. It's working fine without any issues.
