### ISSUE TITLE
No way to disable gamepad/controller navigation

### ISSUE THREAD

**Issue by KeronCyst** [UnigramDev/Unigram#2469]
Unigram 7.8 (6586) X64 on Windows 10 Home 21H1:

I can't seem to find any way to disable controller navigation. It automatically detects when I'm moving the joystick around, etc. on an Xbox-formatted USB gamepad/controller, but I'm using a [program](https://github.com/Tylemagne/Gopher360) that already changes the gamepad's behavior (into a virtual mouse).

I would very much appreciate an option to disable recognition of gamepad input. Thank you so much!

**Comment by makisukurisu** [comment]
This program doesn't prevent your gamepad's signal of "stick up" or "button *x* pressed", it just makes "stick up" -> (program)  -> "stick up _and mouse up_". Thus you have both - stick navigation and mouse moving. I think there is no way to prevent it, except to modify controller's drivers completely, but that's outside of Unigram's scope.

Also you can experience same in Start Menu and Weather app.

Thanks for opening an issue! You can close it or wait for someone in power to close it for you.

**Comment by FrayxRulez** [comment]
AFAIK this isn't technically possible, also I'm not sure about how to present this to the user and how much useful this would be.
In my opinion this setting should be available in the software you're using to override the controller behavior and not vice versa.
