### ISSUE TITLE
Use Segoe UI Variable in Windows 11

### ISSUE THREAD

**Issue by Jeepeo** [UnigramDev/Unigram#2470]
Apparently Unigram still uses Segoe UI in Windows 11 instead of Segoe UI Variable (https://aka.ms/SegoeUIVariable), which is being used by new Store, Settings, and lot of system UI surfaces now, yes, it's new system font.

[from official docs for new typography  ](https://docs.microsoft.com/en-us/windows/apps/design/signature-experiences/typography)
>Segoe UI Variable is the new system font for Windows. It is a refreshed take on the classic Segoe and uses variable font technology to dynamically provide great legibility at very small sizes, and improved outlines at display sizes.

**Comment by FrayxRulez** [comment]
I believe that the app will automatically use it as soon as Microsoft releases a stable Windows 11 SDK.

**Comment by VladWinner** [comment]
Currently, 'Segoe UI Variable' font is still in development and does not contain some glyphs from original Segoe UI, which causes visual artifacts due to font fallback mechanism. Therefore, you should wait for a stable build.

**Comment by fitojb** [comment]
Segoe UI Variable now appears to have glyph parity with the older Segoe UI; the only thing missing now are italic styles.

**Comment by sabbyX** [comment]
Windows 11 SDK (stable) is now available — https://developer.microsoft.com/windows/downloads/windows-sdk/

**Comment by FrayxRulez** [comment]
> Windows 11 SDK (stable) is now available — https://developer.microsoft.com/windows/downloads/windows-sdk/

I just updated the SDK but I can't really see any difference between before and after...

**Comment by FrayxRulez** [comment]
Ohhh maybe yes, but the difference is so subtle :D it's ridiculous

**Comment by VladWinner** [comment]
The new font looks just bad when compared directly, at least at 100% scale:
![01](https://user-images.githubusercontent.com/13555921/136465960-b4b42207-a83b-4a14-b566-1578f15e9fd3.gif)![02](https://user-images.githubusercontent.com/13555921/136465966-c2bae5d5-03b3-4430-a774-80669e117640.gif)

**Comment by fitojb** [comment]
@VladWinner  That is because you have selected the Display variant, which as the name says it’s intended for large sizes. You must compare the old Segoe static fonts with Segoe UI Variable Text.

**Comment by FrayxRulez** [comment]
Should be the case now
