### ISSUE TITLE
The new default wallpaper for dark theme doesn't have enough contrast

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2472]
**Describe the bug**
I used to prefer the current wallpaper that looks very anonymous and ugly to me, but other than that it doesn't have enough contrast with the bubbles of messages from other people, making it hard to focus on the content of the bubble.

**Expected behavior**
Have a decent contrast

**Screenshots**
![image](https://user-images.githubusercontent.com/43090263/125699528-56ad176f-e2e7-4725-bfe4-58eeb61eb667.png)

**Version Info**
 - Unigram: 7.8.6583
 - Windows: 11 Insider

**Comment by FrayxRulez** [comment]
Just changed it in https://github.com/UnigramDev/Unigram/commit/0a293b807392ff4d3c5271daadc095d88a454abe
