### ISSUE TITLE
Multiple chat background patterns are displayed at time

### ISSUE THREAD

**Issue by Kofiy** [UnigramDev/Unigram#2473]
**Describe the bug**
If chat background has turned on pattern then there are appearing other patterns causing that chat background is looking like some mess of colors and drawings.

**To Reproduce**
1. Go to Settings>Chat Settings>Chat Background
2. Select any color background or create new one
3. Start picking different patterns
4. Some patterns will have that error, other ones won't

**Expected behavior**
There should be displayed only one pattern at time

**Screenshots**
![image](https://user-images.githubusercontent.com/37085105/125943172-41acd597-27e4-4eaf-bf96-e90b8cb2ac82.png)
![image](https://user-images.githubusercontent.com/37085105/125943175-2955e3b2-2485-4675-9f41-e274d34bfb8a.png)
![image](https://user-images.githubusercontent.com/37085105/125943183-740f38e3-1fa4-483a-8ebc-160842cb2610.png)
![image](https://user-images.githubusercontent.com/37085105/125943190-484159b1-fdf4-4d8a-b9a2-9d42d31dc39c.png)
![image](https://user-images.githubusercontent.com/37085105/125943195-e4500a6f-1cc1-441b-a6f5-fc2599aa648e.png)

**Version Info**
 - Unigram: 7.8.6586 x64
 - Windows 10 Pro: 20H2 (Build 190**42**)

**Additional context**
I'm using one monitor with 4K UHD resolution, but bug is still here after changing the resolution to 1080p FHD.
Some patterns aren't affected by that bug *(3rd screenshot)*
Multiple patterns are displayed in "Background Preview", Message text size preview and in actual chats. *(1st, 2nd and 5th screenshots)*
But in backgrounds gallery everything is ok. *(1st screenshot)*
After restarting the app selected background becomes normal. But other backgrounds are still buggy. Changes in background pattern causes that bug again. 
Pattern intensity affects all patterns *(4th screenshot)*

**Comment by FrayxRulez** [comment]
This is a DirectX bug and I have no clue about how to fix it...

**Comment by FrayxRulez** [comment]
I believe that this was fixed!
