### ISSUE TITLE
search result number is shown with false data

### ISSUE THREAD

**Issue by alighamari** [UnigramDev/Unigram#2475]
**Description of the bug**
if you search something the 49th result is what you get and if you search older messages 49 as the number of result is shown even though its something like 15454th result 
**To Reproduce**
1. Go to a very big chat with lots of messages 
2. Click on search
3. type something
4. See the number of result

**Expected behavior**
it should go to nearest result and show the number accordingly 

**Version Info**
 - Unigram: 6583
 - Windows: 20H1 (19043.1110
 
**Additional context**
additional of option to type the result number like a number input could be 
really handy

**Comment by FrayxRulez** [comment]
Fixed
