### ISSUE TITLE
Unigram crashes when your companion ends call

### ISSUE THREAD

**Issue by makisukurisu** [UnigramDev/Unigram#2476]
**Describe the bug**
When in voice/video private call, if the other side ends call Unigram will crash.

**To Reproduce**
1. Go to a chat with someone
2. Make a call
3. Ask to end call

**Expected behavior**
Call window to collapse/show "Call ended"

**Screenshots**
None

**Version Info**
 - Unigram: v 7.8 6583
 - Windows: 21H1

**Additional context**
Thanks to @OfficialDjJohn for telling about this [issue](https://t.me/unigraminsiders/359662)

If you will make a call from your second account make sure to log out from it on device where you accept call, or you may not connect.

**Comment by FrayxRulez** [comment]
I'm not able to reproduce the issue

**Comment by makisukurisu** [comment]
> I'm not able to reproduce the issue

Same here 🤷‍♂️
Should I close this issue?

**Comment by makisukurisu** [comment]
Resolved. Maybe it was some server side issue.
