### ISSUE TITLE
Creating theme or Editing theme will crash Unigram + side note

### ISSUE THREAD

**Issue by makisukurisu** [UnigramDev/Unigram#2477]
**Describe the bug**
If you create a new theme using corresponding button in theme menu Unigram will crash. Check additional content for "+ side note"
Same will happen if you will press on theme to open editor.

**To Reproduce**
1. Go to Settings->Chat settings
3. Press "Create new theme"
Alternate route:
1. Go to Settings->Chat settings
2. Click on "Show all themes"
3. Right click on
4. Select "Edit"
5. Get crash

**Expected behavior**
Get theme editor in both cases. Not just a new theme.

**Version Info**
 - Unigram: v 7.8 6583
 - Windows: 21H1

**Additional context**
Side note - it seems that themes are selected in some strange manner [(for eg - check video)](https://t.me/htgkjl/197), maybe it's a little key for this problem. Themes in Russian were: Classic and Dark correspondingly, they were not changed a bit from their parents because of crash, so maybe it's not a key at all.
And another note - you can't create theme from Day and Night, they are redirected to Classic and Dark correspondingly.

Thanks to @Smka67 for telling about this issue [there](https://t.me/unigraminsiders/359678), and to all the others before and after him/her/whatever.

**Comment by FrayxRulez** [comment]
This should be fixed
