### ISSUE TITLE
Silent push notification are not silent

### ISSUE THREAD

**Issue by Marocco2** [UnigramDev/Unigram#248]
**Build 155**

I use @MasterTagAlertBot for my personal purpose and I set it to send me silent notifications.
While Telegram Desktop is doing well, Unigram sends them as normal notifications

**Comment by Marocco2** [comment]
@Marocco2

**Comment by Marocco2** [comment]
Build 152. The issue is not fixed.

**Comment by larsschellhas** [comment]
@frayxrulez what do you say? Is this fixed or not? Do we need to reopen it/?

**Comment by Marocco2** [comment]
Still have this issue
