### ISSUE TITLE
Remember windows size of call overlay window (in-call too)

### ISSUE THREAD

**Issue by m-alice** [UnigramDev/Unigram#2484]
Default now is, 720x572 but i want minimum:-(
![2021-07-27_12-42-16](https://user-images.githubusercontent.com/7101860/127133078-75233bce-73a4-4db9-876f-cb595de771d5.png)

**Comment by m-alice** [comment]
Not fixed, still resets to same position and size.

**Comment by FrayxRulez** [comment]
Unfortunately there isn't a way for us to properly deal with this stuff, so I'll close the ticket.
It may be possible with WinUI 3, but we'll think about it later on.
