### ISSUE TITLE
Video Messages in low FPS

### ISSUE THREAD

**Issue by CrashXBETAX** [UnigramDev/Unigram#2487]
**Describe the bug**
Telegram Desktop displays the video message at 30 fps normally, but Unigram displays it at approximately 15 fps. I noticed the problem 1 year ago when I started using it, but I was hoping someone would fix it, but nobody seems to notice this problem.

**To Reproduce**
1. Go to any conversation, group and channel that have a video message. Remember this is not a normal video, it is a circle shaped video message.
2. Click on video message to play and you will notice that it is running at low FPS. 

**Expected behavior**
Unigram should play video message at 30 FPS as Telegram Desktop

**Screenshots**
I recorded a video to compare with Telegram Desktop. Left is Telegram Desktop. Right is from Unigram
https://user-images.githubusercontent.com/61560882/127731462-ad1c72bc-13fa-4799-ae06-f8050bbfd092.mp4

**Version Info**
 - Unigram: 7.8 (6586) x64 

 - Windows: 21H1 (OS Build 19043.1149)

**Comment by VladWinner** [comment]
I think it may also be related to the system component that was mentioned in answer to my review https://github.com/UnigramDev/Unigram/issues/1272?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDY2NzQzMzQ1NDoxMzU1NTkyMQ==#issuecomment-851786678

**Comment by CrashXBETAX** [comment]
I just auditioned like you did a video before. Here "normal mode" video and popup run normally at 60fps, except thumbnails or previews, I agree that you said that video message is related to thumbnails. My graphics card is AMD Radeon RX 580.

**Comment by FrayxRulez** [comment]
FPS should be fixed
