### ISSUE TITLE
https://share.public.com/Octokit

### ISSUE THREAD

**Issue by dezanewoods3** [UnigramDev/Unigram#2493]
https://share.public.com/Octokit

__Originally posted by @dezanewoods3 in https://github.com/cli/cli/pull/4019#discussion_r683725640__

**Comment by makisukurisu** [comment]
Spam.

**Comment by MarcAnt01** [comment]
@makisukurisu I have closed it, @FrayxRulez should proceed with its deletion since I don’t have the proper permission to handle it
