### ISSUE TITLE
Fullscreen gallery works only on main display

### ISSUE THREAD

**Issue by jwdotpark** [UnigramDev/Unigram#2495]
**Describe the bug**
Fullscreen gallery works only on main display among multiple displays, regardless of Unigram placed in . When click the picture, fullscreen gallery is launched on main display. 

**To Reproduce**
1. Go to conversation
2. Click on any picture while full screen gallery is opted in
3. You can see the picture placed in main display

**Expected behavior**
Picture modal should be placed in the display where Unigram is placed.

**Version Info**
 - Unigram 7.8 (6586) X64
 - Windows 11 22000.120 beta channel

**Additional context**
I know the OS's in beta channel but I believe it was exact same behavior on Windows 10 stable channel. It's not breaking bug but nice to fix I believe. 

Thank you for the great app!

**Comment by FrayxRulez** [comment]
This should have been fixed at some point by using Win32 APIs instead of UWP ones...
