### ISSUE TITLE
Exception when leaving photo viewer

### ISSUE THREAD

**Issue by MarcelBrusius** [UnigramDev/Unigram#250]
only received it on desktop.

screenshot follows.

**Comment by MarcelBrusius** [comment]
![screenshot 2](https://cloud.githubusercontent.com/assets/22997398/24840562/559a2d0e-1d6f-11e7-83aa-d0c728c11a83.png)

**Comment by FrayxRulez** [comment]
Version and steps to reproduce? 
Thank you

**Comment by MarcelBrusius** [comment]
Version. 150 as of today
Steps. I only left the image viewer and got this exception presented (happend 3-5 times already)

I'll keep an eye on it.

**Comment by MarcelBrusius** [comment]
[Unigram Animation Bug Photo Viewer 2.zip](https://github.com/UnigramDev/Unigram/files/908506/Unigram.Animation.Bug.Photo.Viewer.2.zip)

Here is a video presenting my steps. First it leaves photo viewer without an error, then on second try it fails.
sorry for .zip extension, but GitHub doesn't allow avi (and my program only supports this format)
