### ISSUE TITLE
Pinned chats are not always synced properly

### ISSUE THREAD

**Issue by ferferga** [UnigramDev/Unigram#2500]
**Describe the bug**
Pinned chats are not synced properly if they were changed when the app was not opened. *This doesn't happen always and doesn't have exact steps to reproduce*.

**To Reproduce**
1. Close Unigram.
2. Change pinned chats.
3. Reopen Unigram.

**Expected behavior**
Pinned chats are synced as expected

**Version Info**
 - Unigram: 7.8.6586 x64
 - Windows: 21H1 19043.1165

**Additional context**
I don't usually use Telegram in my computer so, normally, when I open Unigram it's after huge periods of time, it has to sync lots of messages.

Commenting this as it might be one of the reasons why Unigram fails to sync pinned chats, as it gets overwhelmed by the amount of messages to sync. Closing and reopening it after a huge message sync doesn't fix the issue and the pinned chats will be stuck until you manually rearrange or unpin them.

**Comment by FrayxRulez** [comment]
Synchronization is fully handled by [TDLib](https://github.com/tdlib/td).
