### ISSUE TITLE
The Chinese period appears to overlap with the time it appears

### ISSUE THREAD

**Issue by chengnan049** [UnigramDev/Unigram#2502]
**Describe the bug**
When entering six Chinese periods, the last period will overlap with the time.

**To Reproduce**
1. Go to 'Any Dialog'
2. Type '。。。。。。'
3. See error

**Expected behavior**
I hope the Chinese period and time no longer overlap

**Screenshots**
![image](https://user-images.githubusercontent.com/46060083/130010502-5c88e131-d533-4e8f-a2e9-6b42d1483f99.png)

**Version Info**
 - Unigram: 7.9.6595 X64 Debug

**Comment by makisukurisu** [comment]
Hello, can you provide some extra info on your settings?

**Comment by makisukurisu** [comment]
Hello, can you provide some extra info on your settings:

Windows scale setting (probably is not needed but, just to make sure)
Unigram "Message text scale" setting

I have default 125% in windows and default one (3rd position
![image](https://user-images.githubusercontent.com/49622129/130031590-d40977ec-0dda-47b5-88fb-8034a1e616d8.png)
)
And it works just fine:
![image](https://user-images.githubusercontent.com/49622129/130031645-15b4be08-b725-4626-a77f-f9b7f7e6dac2.png)

And just to confirm that you've pasted same symbol - can you check if @UnicodeInfoBot responds to your 。。。。。。with:
`U+3002 IDEOGRAPHIC FULL STOP`

**Comment by chengnan049** [comment]
![image](https://user-images.githubusercontent.com/46060083/130054336-eaa9a8b6-def3-4978-af5a-dcac8cac7ec1.png)

![image](https://user-images.githubusercontent.com/46060083/130054349-acdd3edd-267c-480a-89c2-1b8360a087ab.png)

U+3002 IDEOGRAPHIC FULL STOP

**Comment by makisukurisu** [comment]
@chengnan049 So you are on windows 11?

I don't have one, maybe someone can confirm this issue.

Thanks for additional information

**Comment by chengnan049** [comment]
Yes, the version number is 22000.132, and I also found that the first time I changed the font size of Unigram to the maximum, I also got overlapping fonts.

![image](https://user-images.githubusercontent.com/46060083/130057314-3a6b2c3b-013e-49c7-bd26-5473138b6991.png)

**Comment by jupiterbjy** [comment]
![image](https://user-images.githubusercontent.com/26041217/132816326-af297293-75b8-433b-98b7-0ec131dfecb6.png)

Same issue with korean. Display scaling 100%

**Comment by makisukurisu** [comment]
@jupiterbjy setting Unigram's font size to any other value them default one will result in overlap or too big message size. Default value is third position. Unigram uses window's scaling and this settings overrides it, so it's not recommend to change this scale. If text looks small in Unigram it's (probably) small in any other system app, and other apps using system scale.

**Comment by jupiterbjy** [comment]
@makisukurisu I see, thanks for reply

Due to Graphic tablet driver issue (Only accept 100% scale or breaks)  I can't set scale, but I think I can settle with overlapping text :)
