### ISSUE TITLE
Direct ScreenSharing doesn't work

### ISSUE THREAD

**Issue by iMonZ** [UnigramDev/Unigram#2506]
**Describe the bug**

After people Sharing their screen in a private call, this doesn't work

**To Reproduce**
Calling someone. 
This person enabled screen sharing

**Expected behavior**
The screen should be viewable on Unigram

**Version Info**
 - Unigram: 7.8
 - Windows: 22000

**Comment by MarcAnt01** [comment]
@iMonZ please don't remove sections from the template, information like Windows release and Unigram version are needed

**Comment by iMonZ** [comment]
> @iMonZ please don't remove sections from the template, information like Windows release and Unigram version is needed


Currently, I don't have Windows installed. It's just for a friend, but I added the missing information.

**Comment by iMonZ** [comment]
Actually, this bug is already fixed: https://github.com/UnigramDev/Unigram/commit/954811f9dc56aed62a3f2eb757583fc9928e4cc1

But It's still not released

**Comment by MarcAnt01** [comment]
> Actually, this bug is already fixed: [954811f](https://github.com/UnigramDev/Unigram/commit/954811f9dc56aed62a3f2eb757583fc9928e4cc1)
> 
> But It's still not released

I'm not sure if this is an option to share it or to see other people's one honestly

**Comment by FrayxRulez** [comment]
They, this was implemented but never added to the interface, I'll try to take care of this soon.

**Comment by FrayxRulez** [comment]
Implemented in https://github.com/UnigramDev/Unigram/commit/d1eba145c2ba4c83bdf2e8aac7744abe60e8d500
