### ISSUE TITLE
Ability to change bitrate and framerate in screen sharing in voice chats

### ISSUE THREAD

**Issue by Yardanico** [UnigramDev/Unigram#2507]
Both tdesktop and Unigram use the tgcalls library which has a very low default bitrate and framerate for streaming. I wanted to make a feature request to add an ability to change it to higher values which do actually work and allows to stream videos/games with watchable framerates.

You can look at a tgcalls patch that does this (adds an enableHDVideo option to tgcalls) here - https://github.com/TDesktop-x64/tgcalls/commit/96a01845d7ab6812379dcb3e64cc18ed2689c55e. Apart from changing the max bitrate to 20Mbps it also changes the max framerate to 60.

That said, I don't know if this is safe to do and if Telegram can restrict accounts or something similar for streaming with higher bitrates (although I didn't have any issues using this patch in normal tdesktop for more than 2 weeks).

**Comment by FrayxRulez** [comment]
This is definitely an interesting topic but I don't think that this is the right approach. Apps should be able to choose the right bitrate depending on network conditions etc.

**Comment by Akyh** [comment]
> This is definitely an interesting topic but I don't think that this is the right approach. Apps should be able to choose the right bitrate depending on network conditions etc.

but even on good network bitrate is too low and quality bad

**Comment by FrayxRulez** [comment]
Closing this ticket as the parameters are still restricted by the backend
