### ISSUE TITLE
The last message propic is sometimes assigned to the wrong person

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2508]
**Describe the bug**
In a group the last message propic is sometimes assigned to the wrong person, the title is set properly, usually by scrolling up and down it gets fixed by itself

**To Reproduce**
I don't have repro steps, but it seems to happen specifically when while scrolling down new messages arrive

**Expected behavior**
Display the right propic

**Screenshots**
![image](https://user-images.githubusercontent.com/43090263/131683691-774b83ca-064e-4d06-ab12-d3459a3ce2e7.png)

**Version Info**
 - Unigram: 7.9.6585
 - Windows: 11 Insider

**Comment by MarcAnt01** [comment]
It seems to assign the picture to the person just above and happens to assign also the propic if I send the last message. My guess is this being caused by the scrolling animation

**Comment by FrayxRulez** [comment]
Sticky heads have been removed as this bug can't be fixed due to the asynchronous nature of ListView.
