### ISSUE TITLE
Why does the project require VS2017?

### ISSUE THREAD

**Issue by r2d2rigo** [UnigramDev/Unigram#251]
I have forked the project to contribute on some not-yet-implemented features, but I can't build it due to it targeting VS2017 and the Creator's SDK. Is there any reason why this is required?

**Comment by theweavrs** [comment]
You could just change the SDK version.

Change these two lines in all the .csproj files:
```xml
    <TargetPlatformVersion>10.0.15063.0</TargetPlatformVersion>
    <TargetPlatformMinVersion>10.0.14393.0</TargetPlatformMinVersion>
```
To:
```xml
    <TargetPlatformVersion>[YOUR PREFERRED SDK VERSION]</TargetPlatformVersion>
    <TargetPlatformMinVersion>[YOUR PREFERRED MINIMUM SDK VERSION]</TargetPlatformMinVersion>
```
These are the values for all the SDKs:
```
Windows 10: 10.0.26624.0
November Update: 10.0.10586.212
Anniversary Update: 10.0.14393.795
Creator's Update: 10.0.15063.0
```

Assuming the app doesn't strongly depend on the latest C# version (C# 7) or on the latest sdk, all should work beautifully. Of course, you would have to exclude the modified .csproj files whenever you push the updates so as not to cause conflicts and issues.

**Comment by FrayxRulez** [comment]
The app strongly depends on C# 7 and Anniversary Update to work

**Comment by theweavrs** [comment]
@FrayxRulez Then it's hopeless at least to try it out on Visual Studio 2015 but changing the Target SDK version on Visual Studio 2017 to Anniversary Update won't break anything. Am I right?

**Comment by FrayxRulez** [comment]
Yes. At the moment should not be a problem. But I can't understand why one should not install latest SDK version (that will be used soon, by example to implement implicit animations)

**Comment by r2d2rigo** [comment]
@theweavrs I'll try that, however C++ projects need the tools version changed too.

@FrayxRulez Composition implicit animations are available since Anniversary: http://blog.robmikh.com/uwp/xaml/composition/2016/08/18/exploring-implicit-animations.html

**Comment by FrayxRulez** [comment]
You can downgrade them to v140. 
Not implicit animations triggered by visibility, that are the ones we'll use most

**Comment by r2d2rigo** [comment]
I managed to install VS2017 and work with it, so I'll close this issue.
