### ISSUE TITLE
Account was banned, then unbanned, but I couldn't sign in due to sending codes to my inaccessible account. No SMS code was ever sent.

### ISSUE THREAD

**Issue by ClairelyClaire** [UnigramDev/Unigram#2510]
Last night, my account was abruptly and inexplicably forcibly logged out of all my clients, and I was informed that my phone number had been banned. My account didn't actually show up as deleted or banned to others, and less than 24 hours later, I was able to attempt to log in again, without getting the "PHONE NUMBER BANNED" error.

The problem here is that I was unable to log in to my account, because every single client - Unigram, Telegram's own official Windows, MacOS, and Android clients - wanted me to enter a code sent to my Telegram account...which I couldn't access.

I was finally able to get in using TelePORTS, a third party client for Ubuntu Touch, because it sent an SMS code when I attempted to access my account. Without the SMS code, I was permanently locked out of my account.

This API seems relevant:
https://core.telegram.org/method/auth.sendSms

Is it possible for Unigram to enable sending SMS codes for authentication, so that when issues like this arise, users can access their recently-unbanned accounts without issue? With TelePORTS, it sent an SMS code almost immediately. I don't know if that was triggered by anything, and TelePORTS doesn't let me see my logged-in sessions. I won't be able to see what other clients are logged in until around noon PST tomorrow, when my account is unlocked and I can attempt logging in again.

**Comment by makisukurisu** [comment]
@ClairelyClaire Currently sending sms for auth on desktop and web is"forbidden" hence no sms messages. You have to log in on your mobile first.

**Comment by ClairelyClaire** [comment]
Well, then is there a way for Unigram on mobile to do this?

I know mobile isn't supported anymore, but if not for my stupid PinePhone64, I would have been permanently locked out of my account with zero recourse.

**Comment by FrayxRulez** [comment]
Unfortunately this is by design and it will not be changed.
