### ISSUE TITLE
Unigram crashes on deleting multiple chats from archive

### ISSUE THREAD

**Issue by yashpalgoyal1304** [UnigramDev/Unigram#2511]
**Describe the bug**
Unigram crashes (auto closes without any notice) on deleting multiple (5) chats from archive

**To Reproduce**
1. Go to 'archived chats'
2. Right Click on any chat
3. Select multiple chats (i chose 5, update: not reproduced when 4 chats were selected)
3. Click delete
4. See that unigram auto closes

**Expected behavior**

**Screenshots**

**Version Info**
 - Unigram: 7.8.6586 x64
 - Windows: 10 20H2

**Additional context**

**Comment by makisukurisu** [comment]
@yashpalgoyal1304 Cannot reproduce on 7.9 beta. But there was no work done to archive afaik.

If you get this consistently consider enabling vebose logs.
If you are willing to and don't know how, I'll send you "instructions" though I'm not sure if logs will help at all in that case.

**Comment by yashpalgoyal1304** [comment]
i am willing - so, do send the instructions. BUTTT, i wont be able to do the testing at this moment - it's a bit busy time here. Will do next month.

P.S. cute and nice pfp. i liked it.

**Comment by yashpalgoyal1304** [comment]
also, any tips on how can i create dummy chats will be welcome too. 'cz i dont have any chats that can be deleted atm.

**Comment by makisukurisu** [comment]
Ok. So basically you have to go to settings and click on version number 10 times. Then you can see "hidden menu", now you can go to TDLib Logs section.
![image](https://user-images.githubusercontent.com/49622129/131886923-4314ff1f-aa20-4d22-9bbe-aa10afe3b9a2.png)

Select Verbosity Level and set it to "Verbose". Then you restart the app (just to make sure, afaik it's not needed), go to archive and repeat all steps needed to crash the app. After a crash (or even if it didn't happen) go to settings, set Verbosity Level back to "Error" and restart the app once again. After that return to TDLib Logs section one more time, click on "tdlib_log.txt" and send it to Fela. He then may give you additional tasks, if such are needed.

Thanks for your report! If you can and want - you may also try to reproduce this issue on a newer version of an app, also by the time of a month even 7.9 may become outdated, so just make sure to update when it's possible.

P.S you can get an old crashdump.reg file [here](https://t.me/unigraminsiders/342637) then you will need to edit it so last folder name is same as Unigram's.

![image](https://user-images.githubusercontent.com/49622129/131888248-c9217bc7-44c6-4aa3-9bbb-e8c9137b599e.png)
Eg. The red parts should be same. Rest shouldn't be changed. (You can get correct Unigram path by pressing "show in folder" for any media, and then going up to a top of Unigram's hierarchy)

**Comment by makisukurisu** [comment]
To create some chat's you can make a group with you and bot in it. Any bot, like @qwasderfasdwe_PC_Wake_UP_bot, for example. Or any other.

**Comment by MarcAnt01** [comment]
Hey @yashpalgoyal1304 could you please provide the needed data, please?

**Comment by yashpalgoyal1304** [comment]
Hi,

* Sorry for the delay in providing any conclusion. I totally forgot about
it.
* No, I am no longer using unigram, so, i wont be able to provide any
further inputs.
* All issues filled by me for Unigram can be closed.

Thanks

Filippo Fedeli wrote:
