### ISSUE TITLE
File sending is often broken both with Windows Share and drag and drop

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2515]
**Describe the bug**
The last beta broke the possibility to send files both with Windows share and with drag&drop. No pop-up is being shown when it doesn't work (90 per cent of the times). When I use drag and drop I see the dragging icon in Unigram, but then nothing happens

**To Reproduce**
1. Drag and drop a file to a chat or use Windows share;
2. Enjoy

**Expected behavior**
Send files properly

**Version Info**
 - Unigram: 8.0.6606 x64
 - Windows: 11 Insider

**Comment by FrayxRulez** [comment]
Nothing has changed, works properly here.

**Comment by MarcAnt01** [comment]
Cannot reproduce any longer
