### ISSUE TITLE
Could not see any other group video chatters' video

### ISSUE THREAD

**Issue by KeronCyst** [UnigramDev/Unigram#2516]
**Describe the bug**
Their video boxes are empty whenever they turn on their video (and I confirmed in the same video chat that Telegram Desktop shows them correctly)

**To Reproduce**
1. Start/join a video chat with other people who have their video on
2. Their video boxes are empty

**Expected behavior**
Their webcam, phone camera, etc. video should fill their boxes

**Screenshots**
![image](https://user-images.githubusercontent.com/13827055/132430063-34ec5c39-1081-45d9-8459-83ccf99c1cd2.png)

**Version Info**
Unigram 7.8 (6586) x64
Windows 10 Home 21H1, OS Build 19043.1202

**Comment by FrayxRulez** [comment]
This should be fixed
