### ISSUE TITLE
Creating poll option X visual bug

### ISSUE THREAD

**Issue by makisukurisu** [UnigramDev/Unigram#2518]
**Describe the bug**
When creating an option in a pool you have two overlapping X'es to remove option you are editing at the moment

**To Reproduce**
1. Go to Chat
2. Click on Attach Pool
3. Add new option
4. See two X'es

**Expected behavior**
To see only one of them

**Screenshots**
![image](https://user-images.githubusercontent.com/49622129/132843137-42f1a0da-82c9-46c1-80a7-fecd6a94017d.png)

**Version Info**
 - Unigram: v 8.0 6606 x64 Debug
 - Windows: 21H1

**Comment by makisukurisu** [comment]
Still applicable in v 9.3 7966 x64 😔

**Comment by FrayxRulez** [comment]
Fixed
