### ISSUE TITLE
UI overlapping / ordering issue

### ISSUE THREAD

**Issue by jupiterbjy** [UnigramDev/Unigram#2519]
**Describe the bug**
A. Regardless of content, any message overlaps with typing area.
B. When sending image, Send button is overlapped by some white box, and text is not visible. It became visible only when holding the button

**To Reproduce**
Getting issue from fresh install.

**Screenshots**

![image](https://user-images.githubusercontent.com/26041217/132850640-f128493d-cdf2-471d-8e85-e2eda1725f2f.png)

![image](https://user-images.githubusercontent.com/26041217/132850707-97786d1b-b835-4c19-98f2-689d7608f297.png)

- Not clicked
![image](https://user-images.githubusercontent.com/26041217/132850900-d67005d1-8c41-41eb-a747-a20bf14c2498.png)

- holding click
![image](https://user-images.githubusercontent.com/26041217/132850909-c34d2150-239c-4681-bf9b-7e6f20cdc714.png)

**Version Info**
 - Unigram: 7.8 (6586) x64
 - Windows: WIn10 Edu 20H2 19042.1165

**Comment by makisukurisu** [comment]
Typing area shouldn't be transparent, can you tell if this still persists in newest versions? Thanks.

**Comment by jupiterbjy** [comment]
Just installed again, and most of visual glitches are fixed, I'll close this issue - finally time to ditch the official client :)
