### ISSUE TITLE
Color picker for the design

### ISSUE THREAD

**Issue by jp-weber** [UnigramDev/Unigram#252]
It would be cool, if future update will bring a chossable color design, for example "MessageBackgroundBrush".

**Comment by MarcAnt01** [comment]
Now, it's possible to pick Windows accent to use it as color, it's not a total color customization, but it's enough, will close this ticket

**Comment by jp-weber** [comment]
@MarcAnt01 That's a pity, I had hoped that in the future you might be able to adapt the desing like Android. I don't like the chat colors of the answers at all.

**Comment by MarcAnt01** [comment]
Go to Windows 10 settings and choose the color you prefer and tick the option to set system accent

**Comment by jp-weber** [comment]
@MarcAnt01 I don't like to set only my answers, I want to change the color of the answers at all. The best way is to implement custom themes like: https://telegram.org/blog/android-themes

**Comment by FrayxRulez** [comment]
Creating custom themes has been available in Unigram for a year or so and it has been removed (I think, I can’t remember if this is still available) recently. As a result no one in this year asked for this feature and no one of the people that knew about it created any theme...

**Comment by jp-weber** [comment]
I didn't know that and I have never seen this option in the settings. For me personally, this is an important function that I also used to personalize my messenger client.
