### ISSUE TITLE
Crashes when trying to edit created theme

### ISSUE THREAD

**Issue by r00tl34k** [UnigramDev/Unigram#2520]
When creating a theme, it crashes. When trying to edit it, the same thing happens. It closes completely.

1. Open Unigram.
2. Chats > Themes > Create theme = Unigram closes and remains closed.
3. Re-open. Chat > Themes > Edit theme = Crash. Same result.

I really don't know what it can be. I've already tried resetting and reinstalling the program multiple times from the Windows Store.

 - Unigram 7.8 (6586) x64
 - Windows 11 21H2 (22000.184)

Thanks.

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/1b721afa149137848a3cea8a94dd868789714d89
