### ISSUE TITLE
Transferring Bots with Unigram [Windows]

### ISSUE THREAD

**Issue by jainamoswal** [UnigramDev/Unigram#2521]
**Describe the bug**
We can't transfer ownership using Unigram when user have 2FA enabled in account.

**To Reproduce**
- Create a bot.
- Set 2FA.
- Transfer the bot to other user.

**Expected behavior**
Bot should be transferred  to other user.

**Screenshots**

**Version Info**
 - Windows:

**Additional context**
The option to prompt for Password for transferring the bot is not displaying. So the bots can't be transferred.

**Comment by jainamoswal** [comment]
I just tried with Mobile client and discovered that I had logged in recently. 🤦
So the issue needs to be closed and no longer exists.

But I must suggest that it needs a pop-up regarding that.

Thanks.

**Comment by makisukurisu** [comment]
@jainamoswal Well, you might want to rename it, and reopen (but, you, probably) cant. Thanks for you report.
