### ISSUE TITLE
Link join information

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2524]
The iOS client has a feature that shows in the section of the invite link some information about how the link has been used
![image](https://user-images.githubusercontent.com/43090263/134330173-2be47476-8953-4e0c-b869-c1217e973499.png)

![image](https://user-images.githubusercontent.com/43090263/134330123-e4bf3473-60fe-462d-94aa-26dd453cfbcd.png)

**Comment by FrayxRulez** [comment]
Done
