### ISSUE TITLE
Automatically opens ForceReply keyboard

### ISSUE THREAD

**Issue by AnotiaWang** [UnigramDev/Unigram#2526]
**Describe the bug**
Unigram automatically opens the keyboard with `Reply to...` in a group. And even I closed the reply panel, it pops up again the next time I switch to the group.

**To Reproduce**
I don't know exactly why, since my bot hadn't send the reply request yet. Unigram just acted like the request came out from nowhere.

**Expected behavior**
Unigram shouldn't open the reply panel since my bot haven't send the request yet! And even the bot with [ForceReply](https://core.telegram.org/bots/api#forcereply) asks other group members to reply, Unigram asks me to reply too.

**Screenshots**
![bandicam 2021-09-23 08-17-36-073](https://user-images.githubusercontent.com/62269186/134439082-d15ed42e-954b-49bc-8d72-6d511866b1fc.gif)

**Version Info**
 - Unigram: 8.1 (6635)
 - Windows: Windows 11 22000.194

**Additional context**
This issue doesn't happen on other Telegram clients like TD, Nekogram X and Telegram Messenger.

And btw, the placeholder won't disappear after a reply message is sent.

**Comment by FrayxRulez** [comment]
This was likely fixed
