### ISSUE TITLE
Joining private groups from browser doesn't work

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2529]
**Describe the bug**
Joining private groups from browser doesn't work. Public ones do, Unigram shows "this chat doesn't seem to exist"

**To Reproduce**
1. Copy a t.me/joinchat/blablablablablablabla in the browser address bar
2. Open it with Unigram

**Expected behavior**
Show the join pop-up

**Version Info**
 - Unigram: 8.1.6636
 - Windows: 11 Insider

**Comment by amirmahdifard0** [comment]
@MarcAnt01 Hello everybody how are you I hope you will be good actually lee6 link that you sent is already expired did you know that

**Comment by MarcAnt01** [comment]
Hello, that's not a proper link,just an example of the format

**Comment by MarcAnt01** [comment]
@FrayxRulez can we mark this as critical. After months this still doesn't work and I think it's a pretty basic functionality?
