### ISSUE TITLE
Bug involving edit of emoji-only message

### ISSUE THREAD

**Issue by KeronCyst** [UnigramDev/Unigram#2532]
Unigram 8.1 (6638) x64 on Windows 10 Home 21H1:

1. Send a message consisting purely of one or more emoji
2. Edit that message and add more (or delete some existing) emoji (deleting any spaces between/after them)
3. The message shows edited in the chat overview, but you still only see the prior version until you exit and return to the chat

**Comment by FrayxRulez** [comment]
This was fixed
