### ISSUE TITLE
Playing a mkv video with subtitles will not show subtitle and keep freezing or lagging

### ISSUE THREAD

**Issue by BraveSail** [UnigramDev/Unigram#2535]
**Describe the bug**
If there are subtitles in a mkv video, the video will keep freezing or lagging when switch to different subtitles. And the video player won't show the subtitles unless switch to Picture-in-picture mode. And these problems will not exist in picture-in-picture mode. But the picture-in-picture mode cannot adjust the window size, it can only be kept in a small window.

**To Reproduce**
1. Go to https://t.me/archive_tmp/2
2. Play that test video
3. Try to switch subtitle to english
4. The video will keep freezing or lagging
5. Play that video in Picture-in-picture mode
6. The video player works fine but cannot adjust the window size, it can only be kept in a small window.

**Expected behavior**
Playing mkv video with subtitles normally.

**Screenshots**
The reproduction will see how the problem happened.

**Version Info**
 - Unigram: 8.1.6635 x64
 - Windows: Windows 11 22463.1000

**Additional context**

**Comment by LegendModzYT** [comment]
I seem to have the same problem although I have it with .mp4 files. I tried messing around with the width of the screen when the video is being played and depending on the width the video will lag, when reaching a similar width to that of the PiP width it seems to stop. 

This is also "_fixed_" via playing the footage in PiP which baffles me as I can't seem to find a solution to this and don't quite know if this has been fixed or just forgotten about. I am on Windows 10 Build 19043.

**Comment by FrayxRulez** [comment]
@LegendModzYT This is something that can’t be fixed as the player is external to Unigram. You can check if your GPU supports video playback acceleration in your GPU control panel (and you can try to play in general with the settings there) or you can simply download the videos and play them using some “real” video player rather than the built in one

**Comment by LegendModzYT** [comment]
> @LegendModzYT This is something that can’t be fixed as the player is external to Unigram. You can check if your GPU supports video playback acceleration in your GPU control panel (and you can try to play in general with the settings there) or you can simply download the videos and play them using some “real” video player rather than the built in one

I'm using a GTX 1060, I'm not too sure what player is being used then to display the videos. If it is external to Unigram maybe it is a problem within it but without knowing what it is I won't be able to try and fix it. The normal Windows Films and TV media player works fine it's just the one that is being used for Unigram. Downloading the videos to just watch them can be a bit tedious as I'd prefer not to do that, I was only using Unigram for its translate feature but normal Telegram works fine nonetheless. 
Thanks for your quick reply,
Regards, Legend.

**Comment by FrayxRulez** [comment]
The only officially supported video format is MP4, so no improvements are going to happen here
