### ISSUE TITLE
Layout bug after changing language

### ISSUE THREAD

**Issue by AnotiaWang** [UnigramDev/Unigram#2538]
**Describe the bug**
The "Info" page of chats will be blank.

**To Reproduce**
1. Go to Settings
2. Change a language for the App

**Screenshots**
![image](https://user-images.githubusercontent.com/62269186/136770148-071b4cf0-b04b-4765-a262-6c1a570a7d53.png)

https://t.me/unigraminsiders/371126

**Version Info**
 - Unigram 8.1 (6659) X64 Direct
 - Windows 11

**Extra**
Restarting the App will fix it (temporarily).

**Comment by FrayxRulez** [comment]
Sidebar was removed, long live to the sidebar

**Comment by pratyakshm** [comment]
@FrayxRulez :(
