### ISSUE TITLE
Settings navigation back-stack broken

### ISSUE THREAD

**Issue by ronell1292k** [UnigramDev/Unigram#2539]
Description:
Pressing the back button (arrow button on the top left) in any settings screen navigates directly to the chats screen without following the navigation back-stack

1. Go to 'Settings' from the hamburger menu
2. Click on any option and navigate to any nested setting, eg Settings > Chat Settings > Chat background
3. Click the back arrow located on the top left
4. Instantly get navigated to the Chats screen

Expected behavior:
Follow the navigation LIFO stack on each click of the back button, eg Chat background > Chat Settings > Settings > Chats

Version Info:
 - Unigram:  8.1.6659.0 x86_64
 - Windows 11 21H2 22000.194

**Comment by FrayxRulez** [comment]
You have two back buttons, the one on the master column (left) is for the main navigation. Hence it is expected from settings to go straight to the chats list. To navigate backward within settings you should use the other back button.
