### ISSUE TITLE
`Show in Chat` from new profile sidebar doesn't work

### ISSUE THREAD

**Issue by gotenksIN** [UnigramDev/Unigram#2541]
**Describe the bug**
`Show in Chat` from new profile sidebar doesn't work

**To Reproduce**
1. Go to any chat
2. Click on open its profile sidebar
3. Go to any media or link and click show in chat 
4. Doesn't do anything

**Expected behavior**
It should take me to the message where it was sent

**Version Info**
 - Unigram: [8.1 6659 x64]
 - Windows: 10 21H2

**Comment by FrayxRulez** [comment]
Sidbar was removed, long live to the sidebar
