### ISSUE TITLE
The back key in navigation bar doesn't work properly

### ISSUE THREAD

**Issue by CuteCatXiao** [UnigramDev/Unigram#2542]
![1](https://user-images.githubusercontent.com/62191675/137136617-681df09d-db4f-418e-8532-c02837b4b5ad.gif)
The back key in navigation bar doesn't working in the minimum window . But it return normally when I pull the window up again.

Windows  11 - 21H2 22000.194 | Unigram 8.1 6659 x64

**Comment by CuteCatXiao** [comment]
And now I found that in normal size of window the `back key` doesn't work perfectly either. The first click will let message list return to the top. Then the second click will finally let chat closed. I don't think it's a feature.

**Comment by MarcAnt01** [comment]
Fixed in the latest beta
