### ISSUE TITLE
Link opening is totally broken with touch/pen

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2545]
**Describe the bug**
Link opening is totally broken with touch/pen since some updates. I can reproduce it from chat messages and group/chat description

**To Reproduce**
1. Click on any link in a message from chat;
2. Enjoy

**Expected behavior**
Open the link

**Version Info**
 - Unigram: 8.1.6659
 - Windows: 11 21H2

**Comment by FrayxRulez** [comment]
Report to Microsoft

**Comment by MarcAnt01** [comment]
> Report to Microsoft

Well, if the issue is "Microsoft" please provide some helpful context and specify it's something related to the os/winui/uwp/whatever I cannot reach out to Microsoft and tell and say "Fela said it's your fault"

**Comment by MarcAnt01** [comment]
I am a simple user who spent 5 minutes investigating this problem and opening this issue, also after other people complained about it. This affects in a crucial way touch users, since they cannot open a simple link and I don't understand why you are behaving in a so mad way for a simple report.

**Comment by FrayxRulez** [comment]
I'm not behaving in a mad way, I'm just saying that's definitely not Unigram problem and some other users have confirmed that the problem appeared after a specific Windows 11 update.
As you're a UWP developer yourself you should know that UWP apps don't handle directly touch input in most scenarios and that click events are processed seamlessly by the operating system regardless from the source itself.
"Since some updates" is also completely meaningless, considering that just three updates have been released since June.

**Comment by MarcAnt01** [comment]
> I'm just saying that's definitely not Unigram problem and some other users have confirmed that the problem appeared after a specific Windows 11 update

This should've been the reply since the beginning. I'm in the beta channel and considering the short amount of Unigram updates, it makes more sense to think about Windows 11  rather than Unigram or WinUI, since I would've most likely reported the issue after the Unigram update.

**Comment by xperiandri** [comment]
Then we need to vote for my report https://aka.ms/AAf9ns8

**Comment by MarcAnt01** [comment]
This is a proper report instead https://github.com/microsoft/microsoft-ui-xaml/issues/6513

**Comment by BreeceW** [comment]
You can fix this bug by adding `<x:Boolean x:Key="HyperlinkUnderlineVisible">False</x:Boolean>` on top of the WinUI 2 styles.

**Comment by BreeceW** [comment]
The other way to fix this is to set, when you create the `Hyperlink` inline, `UnderlineStyle = UnderlineStyle.None`. So you can easily fix the problem using either underline style without any changes to Windows or WinUI 2, all on your own.
