### ISSUE TITLE
"show in chat" feature is broken since updated profile sidebar

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2552]
**Describe the bug**
Show in chat doesn't work

**To Reproduce**
1. Make sure the sidebar is enabled;
2. Click "show in this chat"

**Expected behavior**
Jump to the point of the chat where the media has been shared

**Version Info**
 - Unigram: 8.1.6659
 - Windows: Windows 11 21H2

**Comment by FrayxRulez** [comment]
Sidebar was removed, long live to the sidebar
