### ISSUE TITLE
Sometimes chat sidebar breaks

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2553]
**Describe the bug**
Sometimes nothing is shown in the sidebar, it's basically empty. After it's broken to have it working again it's necessary to close the app and reopen it again, couldn't find a way to restore it neither by changing the chat-

**To Reproduce**
1. Change language of the app
2. Change account, and return to first one

**Screenshots**
![image](https://user-images.githubusercontent.com/43090263/138711177-e2eeb62b-e826-4bff-9ed6-4fe0525dc49a.png)

**Version Info**

- Unigram: 8.1.6659
- Windows: Windows 11 21H2

**Comment by FrayxRulez** [comment]
Sidbar was removed, long live to the sidebar
