### ISSUE TITLE
The program window does not restore its last size and position

### ISSUE THREAD

**Issue by cawa-93** [UnigramDev/Unigram#2555]
**Describe the bug**
If you resize the window by pressing it to the edge of the screen then the window does not save this size for the next run.

**To Reproduce**
1. Open App
2. Minimize its size.
3. Use `Win+→` or drag window to the right edge of the screen. The window should resize and take up half of your screen.
4. Restart app.
5. After restarting the application does not restore the window size and position - the right half of the screen

**Screenshots**

https://user-images.githubusercontent.com/1662812/138762350-8a2ca416-ba75-4cff-a329-3a5815ea663c.mp4

**Version Info**
 - Unigram: 8.1.6643 x64
 - Windows: Windows 10 Pro 21H1
 - Screen: 1920x1080

**Comment by FrayxRulez** [comment]
Window size and position is handled by the system, so the failure here it's unfortunately not on our end

**Comment by FrayxRulez** [comment]
By the way - I believe that no software in general saves the docked position, because it's not a standard window state.
Standard states are windowed and maximized, and those are stored correctly.
