### ISSUE TITLE
Double Clicking on (inside) a message doesn't trigger a reply

### ISSUE THREAD

**Issue by sharunkumar** [UnigramDev/Unigram#2556]
**Describe the bug**
When double clicking on a message in a chat, reply option doesn't come up. Only works when double clicking outside the message bubble

**To Reproduce**
1. Open a chat
2. Double Click on a message

**Expected behavior**
Reply option should be triggered on the message that was double-clicked

**Version Info**
 - Unigram: 8.1 (6643 X64)
 - Windows: Windows 11 21H2

**Additional context**
This works in both cases on the official client. In unigram, only clicking on the outside works

**Comment by FrayxRulez** [comment]
This is pretty much by design, as messages contain mostly interactive elements, so there would be just really small area for interaction anyway

**Comment by sharunkumar** [comment]
> as messages contain mostly interactive elements

then clicking on the uninteractive elements should still work right?

even in official client double clicking on a link in a message would open the link instead of triggering reply

I had just suggested it as it would be the same functionality as official client

**Comment by quandolerterakmente** [comment]
@sharunkumar functionality first, double clicking inside a text body will highlight the text and i find myself wanting to do that quite often

**Comment by sharunkumar** [comment]
@quandolerterakmente that already works in the official client that way

**Comment by quandolerterakmente** [comment]
@sharunkumar A reminder that on TDesktop right clicking outside of the actual message bubble will not let you run quick actions on it, whereas on any other client it works anywhere within the actual message area

**Comment by sharunkumar** [comment]
@quandolerterakmente Though that's unrelated to this issue right?

**Comment by sharunkumar** [comment]
@quandolerterakmente Currently, in the official client, double clicking on the message triggers a reply. Double clicking on text in a message selects the message. The functionality you had described is working as intended already in the offical client

**Comment by StuckDuck7710** [comment]
Yeah, that's what Unigram does too
