### ISSUE TITLE
Be able to scroll through zoomed images sideways via Shift-scroll

### ISSUE THREAD

**Issue by KeronCyst** [UnigramDev/Unigram#2557]
Unigram 8.1 (6643) x64 on Windows 10 Home 20H2:

1. View any image sent by you/anyone
2. Hold Ctrl to scroll in quite a bit
3. Hold Shift and try to scroll

Expected result: It should scroll horizontally
Current result: Shift doesn't affect the scroll wheel

**Comment by FrayxRulez** [comment]
Hi, you can report this to Microsoft in microsoft-ui-xaml repository.
