### ISSUE TITLE
Gifs in @gif are cut

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2559]
**Describe the bug**
Gifs in @gif are cut

**To Reproduce**
1. Open a chat;
2. Write "@gif" + some words

**Screenshots**
Telegram Desktop

![image](https://user-images.githubusercontent.com/43090263/141084303-640cec3d-767b-4a4c-8e09-b104b3f6d669.png)

Unigram

![image](https://user-images.githubusercontent.com/43090263/141084398-fa1287b5-adbc-430c-8d67-4bc4edb4e62b.png)

**Version Info**
 - Unigram: 8.1..6643]
 - Windows: 11 21H1

**Comment by FrayxRulez** [comment]
You can search for GIFs from the GIFs drawer

**Comment by MarcAnt01** [comment]
> You can search for GIFs from the GIFs drawer

That one is broken for touch

**Comment by FrayxRulez** [comment]
> That one is broken for touch

Use a mouse

**Comment by MarcAnt01** [comment]
> > That one is broken for touch
> 
> Use a mouse

![image](https://user-images.githubusercontent.com/43090263/141085665-db00c98d-2f34-4d08-823e-055c4bf2fbcf.png)

**Comment by FrayxRulez** [comment]
Then you're out of luck, I really don't bother to rewrite the inline bots to use a ListView instead of a ItemsRepeater

**Comment by pratyakshm** [comment]
@FrayxRulez OOF

**Comment by MarcAnt01** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/7fb9544571030f373f5b8405a2274f8fc7a331c4
