### ISSUE TITLE
Underscore is missing at message posting

### ISSUE THREAD

**Issue by m-alice** [UnigramDev/Unigram#2560]
**Describe the bug**
Today I tried to send a link to a friend and discovered that it for some reason was reduced.

**To Reproduce**
1. Copy this string `v_nee_vliubilas_starshaia_sestra__a_ei_vse_ravno__A5274`
2. Paste in the text input
3. Post it
4. Some underscores is missing

**Expected behavior**
Correct link, of course

**Screenshots**
![2021-11-25_11-21-48](https://user-images.githubusercontent.com/7101860/143405138-9185a049-b07d-45de-b3d4-de9ab81d079b.png)
![2021-11-25_11-23-20](https://user-images.githubusercontent.com/7101860/143405349-0a9b1301-a0d7-4c73-8864-859a3530dde4.png)

**Version Info**
- Unigram 8.1 6643 x64 (ms store)
- Windows 10 2004 19041.1348

**Additional context**
It seems to me that the string is spoiled right on the fly, just after "alt+tab" before posting
Full link is https://readmanga.io/v_nee_vliubilas_starshaia_sestra__a_ei_vse_ravno__A5274
Test in telegram desktop 3.0.1 not revealed this behavior

**Comment by StuckDuck7710** [comment]
It's not a bug. It's just markdown:

`__this is italic__` will result in _this is italic_ (on Telegram, italic uses 2 underscores and bold uses 2 stars, while on most other markdown flavors it's one underscore for italic and two stars for bold)

I suggest you enclose the text you want to copy in back ticks `\`like this\``, which corresponds to mono text.
