### ISSUE TITLE
Drop WPF

### ISSUE THREAD

**Issue by iMonZ** [UnigramDev/Unigram#2562]
it would be great to drop the WPF support and replace it with dotNet MAUI or Avalonia.
It’s more future proof and cross platform so everyone has something from it.

MAUI is using XAML either so the switch shouldn’t be very hard.

thanks anyway

btw MAUI is using winUI 3 for Windows

**Comment by MarcAnt01** [comment]
Hello, this app is not using WPF, but UWP.
The goal is to migrate to WinUI, but the migration isn't going to happen soon, but when it is more mature and feature-complete.

**Comment by MaxG-Enpal** [comment]
Hey can the issue be please reopen.

If Unigram switch to Win UI 3 then the background will work better right?

And dotnetMAUI is using WinUI 3 either, so it would be really great to use this instead.
Since it supports other platforms either.

**Comment by MarcAnt01** [comment]
@MaxG-Enpal Unigram will switch to WinUI 3 + WASDK in the future, in the present Uwp is a more performant, complete and reliable solution. Maui won’t be used since the project doesn’t aim to be cross-platform

**Comment by MaxG-Enpal** [comment]
> @MaxG-Enpal Unigram will switch to WinUI 3 + WASDK in the future, in the present Uwp is a more performant, complete and reliable solution. Maui won’t be used since the project doesn’t aim to be cross-platform

All right sounds great!
Would be really great if Unigram could switch.
I would like to use Unigram in the background.
Currently if the UWP app is closed no notifications are coming :(

**Comment by makisukurisu** [comment]
@MaxG-Enpal However notifications do arrive, and Unigram works in background thanks to Desktop Bridge. You might want to update your app and enable "Show tray icon" in advanced settings.

**Comment by MaxG-Enpal** [comment]
> @MaxG-Enpal However notifications do arrive, and Unigram works in background thanks to Desktop Bridge. You might want to update your app and enable "Show tray icon" in advanced settings.

The Desktop bridge needs to be separately installed, right?

**Comment by makisukurisu** [comment]
@MaxG-Enpal No, I think it's a technology, or something similar. It's built-in.

**Comment by MaxG-Enpal** [comment]
All right, thanks, removing the checkbox and checking it afterwards solved the tray problem.
I hope it will work now!

**Comment by AqlaSolutions** [comment]
2 years later. Now it's really time to migrate.

**Comment by FrayxRulez** [comment]
@AqlaSolutions to what?

**Comment by AqlaSolutions** [comment]
@FrayxRulez  WinUI 3 of course

**Comment by FrayxRulez** [comment]
@AqlaSolutions I didn’t see so many improvements done to WinUI 3 over the last two years, so still no.
