### ISSUE TITLE
Plz Add Unseen/Secret Option

### ISSUE THREAD

**Issue by TareqAbAmawi** [UnigramDev/Unigram#2563]
Thanks ..
Please add privacy and protection options for chats as
Unseen
Hide Typing
Hide Online States
...

**Comment by pratyakshm** [comment]
@TareqAbAmawi I don't think Unigram will add that. Some of these features might go against Telegram's usage policy.

**Comment by MarcAnt01** [comment]
Hi, our "privacy and protection" features are indeed Telegram TOS violations, so won't be considered
