### ISSUE TITLE
Can't install on mobile anymore

### ISSUE THREAD

**Issue by lukasb-vfx** [UnigramDev/Unigram#2564]
Hello, I currently have two window phones ( a Lumia 640 and a 950XL), on my 640 the Unigram app still runs perfectly, and I use it as my daily driver.

But it started crashing on my 950XL, then I decided to uninstall and reinstall it, and for my surprise the Windows Store isn't allowing me to install it anymore. It's possible to manually install an old version, or migrate the app folders from my 640?

Thanks!

**Comment by MarcAnt01** [comment]
Unigram is no longer available for Windows 10 Mobile
