### ISSUE TITLE
Bot commands

### ISSUE THREAD

**Issue by AsrorbekDev** [UnigramDev/Unigram#2570]
**Describe the bug**

**To Reproduce**
1. Go to '  any Telegram bot.'
2. Click on '.left side command'
3. See error " send as "

**Expected behavior**

**Version Info**
 - Unigram: [e.g. lates 8.3 x64]
 - Windows: [e.g. 21H2 update]

**Additional context**
Ot shouldbe only tg groups.

**Comment by quandolerterakmente** [comment]
@AsrorbekDev Please fill out the expected info or just get rid of them if you're not gonna use them.

**Comment by MarcAnt01** [comment]
> @AsrorbekDev Please fill out the expected info or just get rid of them if you're not gonna use them.

Actually filling all the information, is required for creating a bug report issue. A proper title and bug description are required, too
