### ISSUE TITLE
unigram background feature (notifications)

### ISSUE THREAD

**Issue by ScoppyTech** [UnigramDev/Unigram#2571]
hi, i want notifications from unigram as in background. same of WhatsApp beta UWP

**Comment by ScoppyTech** [comment]
sorry for my bad english, i'm italian

**Comment by MarcAnt01** [comment]
Hello, this is known

**Comment by MarcAnt01** [comment]
Duplicate of https://github.com/UnigramDev/Unigram/issues/2210
