### ISSUE TITLE
unable to pin Emoji/Gif/Sticker panel

### ISSUE THREAD

**Issue by Spacelag** [UnigramDev/Unigram#2572]
**Describe the bug**
The sidebar for emojies/gifs/stickers won't stay open when I click on the button that opens the popup on hover. 

**To Reproduce**
1. Go into a chat
2. Click on the emojie/gif/sticker button
3. See error: Nothing happens, just stays open in that popup form

**Expected behavior**
The emojie/gif/sticker sidebar should get pinned / stay open as a sidebar

**Version Info**
 - Unigram: 8.3 (6772) X64
 - Windows: Windows 10 Pro 21H2 19044.1387

**Additional context**
It worked before I updated to 8.3

**Comment by crashinz** [comment]
came to make the same complaint

**Comment by Tiberius1OOO** [comment]
Same problem, this affekts 20 users on our side, since we use a specific sticker pack for our bot programming reactions and testing atm it is super sad that we can not pin that pannel atm.

**Comment by Tiberius1OOO** [comment]
came here as well this also affects windows 11 on the newest update.

**Comment by FrayxRulez** [comment]
This is by design: pinned sticker panel caused a lot of performance issues in the app and that's why it has been repoved

**Comment by Spacelag** [comment]
How can I downgrade to the previous version? This is completely unusable for me as a heavy user of stickers. At least give the option to enable it, because otherwise I can't keep using your app

**Comment by FrayxRulez** [comment]
You can't downgrade. Feel free to leave!

**Comment by Spacelag** [comment]
Glad to be supporting Kotatogram instead :)

**Comment by FrayxRulez** [comment]
There's a lot of ways to send stickers in a fast way without relying on that pinned panel abomination.

**Comment by Spacelag** [comment]
None of which work even remotely as quickly.

**Comment by FrayxRulez** [comment]
> None of which work even remotely as quickly.

I believe that having a more responsive app is better than saving half a second when sending a sticker.

**Comment by Spacelag** [comment]
If you only send one sticker at a time, yea maybe. Not everyone uses your app the way you do, you could've just left an option to enable it with a "causes performance issues" note or smth. Instead of being straight up rude about it and telling me to f*ck off basically

**Comment by FrayxRulez** [comment]
> If you only send one sticker at a time, yea maybe. Not everyone uses your app the way you do, you could've just left an option to enable it with a "causes performance issues" note or smth. Instead of being straight up rude about it and telling me to f*ck off basically

I didn't mean to be rude, and removing this was a pondered decision. Not everything can end up hidden under a toggle and this one of the things that just won't fit there: maintaining this thing actually required a lot of effort, it's not something I can forget about...

**Comment by MarcAnt01** [comment]
I honestly understand the concern behind the feature removal, but I still don't like the current ux, apart from the sever bugs with touch/pen that do affect this design, I prefer to have something steady and put somewhere then something working only on hover and ready to disappear as soon as the cursor slightly moves

**Comment by crashinz** [comment]
boo not a bug, will switch back to the regular telegram for now. thanks for letting us know

**Comment by Tiberius1OOO** [comment]
This saddens me and 3 other friends, sad that this could not be done outside of a toogle because now my telegram redownloads stickers everytime I open it upo instead of leving it in the cache. Switching away as well thanks for the work so far.

**Comment by FrayxRulez** [comment]
@Tiberius1OOO LOL nothing is being redownloaded

**Comment by Tiberius1OOO** [comment]
> @Tiberius1OOO LOL nothing is being redownloaded

reloads I am sorry for the problem, everytime I open telegram and open the gif or sticker section it reloads everything now. which makes it hard to search for anything if you have 20+ gifs (We have written a bot that reacts to specific gifs and stickers) so we use thoes a LOT in 2 of our channels. sorry for the misspronauciation.

**Comment by rawpie2** [comment]
This is a issue i am also having, and it will prevent me and friends from using this amazing app until its implemented
