### ISSUE TITLE
Calls Are Silent

### ISSUE THREAD

**Issue by Elshara** [UnigramDev/Unigram#2573]
**Describe the bug**
When you call someone, after granting Microphone access. The last sound you here before everything in Unigram is just completely dead silent, is the connecting call sound when the other party joins.

**To Reproduce**
First make a telegram call. Doesn't matter if it's voice or video. Wait for the other person to answer. Then try to say something. You can't hear them, and they can't hear you. Even if they're calling from their mobile phone. The reason is because of your sample rate in both playback and recording devices set higher than 44100HZ. This was tested using a sound card supported Windows standard, 192000HZ, 24bit, Studio Quality Stereo sound card.
1. Go to 'Unigram'
2. Click on 'a contact'
3. Scroll down to 'their call screen'
4. Make a call after applying 192000HZ to your sound card under preferences.

**Expected behavior**
Calls to work like they used to. In previous versions of Unigram, prior to December 2021, joining a call, voice or video, with your playback device and recording device set to 192000HZ worked without any trouble. Other modern calling apps like Discord, Skype and Nextcloud Talk have no problem transcoding the audio codec internally if necessary. Telegram can do this natively as well. This is a unigram specific bug in the latest 3 versions, with this one being the most recent.

**Screenshots**
No video, no sound, but the call screen hangs. You can change your speakers, microphone, but no device outputs the caller's microphone or vice versa. Instead, see supporting logs.

**Version Info**
 - Unigram: [8.3.6775.0_x64]
 - Windows: [11 build 10.22523.1000]

**Additional context**
Both the Windows store and the side loaded versions of Unigram face this issue particularly in the previous 3 builds. They were released back to back in December 2021. It is impossible to revert back to an older version of Unigram unless you previously saved the file on your computer. I personally use Unigram for business meetings and to connect with family and friends. As an aside note, I use a screen reader to connect which is the reason I wish to get work done faster while joining conferences on PC compared to using my phone with a touch keyboard, over a physical one. Please fix this issue as soon as possible.
[tdlib_log.txt](https://github.com/UnigramDev/Unigram/files/7739218/tdlib_log.txt)
[tgcalls_group.txt](https://github.com/UnigramDev/Unigram/files/7739220/tgcalls_group.txt)
[tgcalls.txt](https://github.com/UnigramDev/Unigram/files/7739219/tgcalls.txt)

**Comment by serrebi** [comment]
I am experiencing this on windows 10, Version 21H2 (OS Build 19044.1415)

**Comment by Elshara** [comment]
@Elshara

**Comment by Elshara** [comment]
@Elshara Update: issue caused by sample rate of audio device not capturing audio. Specifically, at a soundcard supported level of 192000KHZ

**Comment by Elshara** [comment]
@Elshara

**Comment by Elshara** [comment]
@Elshara

**Comment by Elshara** [comment]
@Elshara

**Comment by Elshara** [comment]
Supporting logs.
[tdlib_log.txt](https://github.com/UnigramDev/Unigram/files/7739184/tdlib_log.txt)
[tgcalls.txt](https://github.com/UnigramDev/Unigram/files/7739185/tgcalls.txt)
[tgcalls_group.txt](https://github.com/UnigramDev/Unigram/files/7739186/tgcalls_group.txt)

**Comment by Elshara** [comment]
Correct supporting logs.
[tdlib_log.txt](https://github.com/UnigramDev/Unigram/files/7739208/tdlib_log.txt)
[tgcalls.txt](https://github.com/UnigramDev/Unigram/files/7739209/tgcalls.txt)
[tgcalls_group.txt](https://github.com/UnigramDev/Unigram/files/7739210/tgcalls_group.txt)

**Comment by FrayxRulez** [comment]
This should be fixed
