### ISSUE TITLE
Cannot open emojis/gifs/stickers with the pen since the sidebar removal

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2576]
**Describe the bug**
Before removing the sidebar the pen touch used to open the sidebar, now nothing happens, it just appears for some millisecs like if it was on hover.

**To Reproduce**
Try to open the panel using a pen

**Expected behavior**
Open properly like with mouse and touch

**Version Info**
 - Unigram: 8.3.6675
 - Windows: 11 21H2

**Comment by FrayxRulez** [comment]
Fixed
