### ISSUE TITLE
Unigram does not use translations for GIFs

### ISSUE THREAD

**Issue by cewbdex** [UnigramDev/Unigram#2579]
Strings seem to be hardcoded, as my Android version has them translated. String IDs `FeaturedStickers`, `FavoriteStickersShort` (mouse hover) and `FavoriteStickers`.

![image](https://user-images.githubusercontent.com/9021297/146671284-cf56192d-c494-43c2-90ed-0e182fe3ced5.png)

**Comment by FrayxRulez** [comment]
Czech translation doesn't even exist in the app: https://github.com/UnigramDev/Unigram/tree/develop/Unigram/Unigram/Strings
