### ISSUE TITLE
Even if an image is downloaded there is still this shaded circle inside it

### ISSUE THREAD

**Issue by MarcelBrusius** [UnigramDev/Unigram#258]
image viewer:
![2017-05-02 1](https://cloud.githubusercontent.com/assets/22997398/25622788/e706c4bc-2f55-11e7-812d-a7fe6ceadaec.png)

in chat view:
![2017-05-02](https://cloud.githubusercontent.com/assets/22997398/25622787/e6962248-2f55-11e7-9ef0-4fecdb4b0205.png)

**Comment by MarcelBrusius** [comment]
And if it's not yet downloaded clicking on the download button (said circle), nothing happens. Only pressing anywhere else on an image opens it in image viewer.

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/a688c3576ca5e3b75654c0f1ad14708af93e2836

**Comment by MarcelBrusius** [comment]
Amazing :)
