### ISSUE TITLE
A List Of Things That Likely Won't Happen But Are Hyperbole

### ISSUE THREAD

**Issue by Elshara** [UnigramDev/Unigram#2582]
I put this list of things together, for the express purpose of things Unigram could excell at that haven't been made yet. Knowing full well this issue will likely get closed and archived.
But with the entourage of bug reports coming in, despite the potential developmental nightmare these would likely be to implement. Consider this, a scrap board of potentials we could have built for Unigram as a fun way to enjoy the app.
Comment below to add to this list. This is the one and only scrap them or add them thread for Unigram!
1. Multi-platform support. Other telegram services delivered in the form of an interface or app, such as https://tweesecake.app/ have made this happen already. No the app itself isn't popular, but the idea that one app can connect to several services, is nothing new.
2. Support Discord, Skype and other messaging services. The draw here would be, that where ever an open API standard exists to make a good interface better than on a website. Let it be done with a name like Unigram. It's a fun way to think about one less app taking up storage space on your computer you use to get work done. Zoom in particular would be the most useful edition for business meetings if such were implemented in the far distant future if at all.
3. Support exclusive in app features. One way to make Unigram popular, would be to provide exclusive features no other telegram client has. Like for instance, the ability to collaborate together in a document by being able to see each letter someone is typing or every stroke of the pencil an other artist is drawing in real time. Yes it's a knock off of what https://www.cometchat.com/ can do for websites. But it's never the less, useful for people to unlock their creative potential.
4. Add the ability to stream media in calls. This is more useful for live presentations mostly, but Skype has this feature already to broadcast output sound. Unigram could take this one step further, and provide the ability for any audio device connected to your computer or remotely via an internet stream to act as an additional input source while the call is going.
5. Provide the ability to input and output to more than one audio device at the same time, if your computer supports it. This could be extremely useful, if you're a gamer or a podcaster. And you have crazy cable wires going all throughout your house. Or you're just in audio production and have multiple sound cards used for different things. That way it could also be used as a diagnostics tool to test to see which microphone you have is best, and automatically select the one closest to an audio source that can detect spoken word if possible. The major draw for this feature, is purely based for novous computer users who may not know what microphone or speakers to select when they first join a call.
6. Provide the ability to select multiple camera sources. This is similar to number five, but uses cameras instead of microphones to achieve perhaps, a 360 degree angle of your environment. This would particularly be useful to achieve a wider field of view around you. And, although it would not be as useful connected to a stationary PC. It would give PC users a reason to choose Unigram as a potential way to make PC chatting cool again. As their mobile phone has such a tiny screen to be able to do the same while on the go. One useful feature for a multi-camera set up, if you have multiple web cameras, is auto focus if you're moving around the house or the room  but you want people to still see you.
7. Add the ability to upload your own emojis or stickers and animated images. This one is pretty basic, but it expands on the idea that in Discord, server owners can have the ability to post their own images. Unigram could expand on this feature, on the user level. Those who have custom images connected to their different accounts, will be able to wow their perspective audience or contacts with exclusives.
8. Add video messages to Unigram. Voice messages are good, but they don't let you see who is talking to you. Providing the ability to add a camera to the message you're recording, just might insure people remain connected a little longer on their computer in ways that are both captured and memorable.
9. Add custom ringtones support. That plus custom sound files, will give people a better way to see who is calling them by assigning a contact, a specific sound just for them. It's mostly a user based feature, but for business meetings, you know right away if you have to answer it or not if someone's calling you based on the caller music assigned to a particular contact or group.
10. Enable the ability to downgrade a unigram version. As with many other apps, when updates break services, people need a reliable way to stay connected. This way you'll be able to collect statistics based on what version of Unigram people are using. Don't pull a Skype here, if you can at all help it.

**Comment by MarcAnt01** [comment]
1/2 The proposal is out of the scope of the scope of the project that is limited to Telegram
3/7 The goal of Unigram is to be inline with official apps, so "exclusive in app features" aren't likely to be included
4/5/6 Telegram works in a certain way, they cannot be tweaked with specific features like you are suggesting
8 Feel free to upvote https://github.com/UnigramDev/Unigram/issues/1284
9 Feel free to upvote https://github.com/UnigramDev/Unigram/issues/619
10  You can store every .msixbundle manually and eventually downgrade, but you cannot expect an app to easily allow downgrades, since users will be stuck in different versions of the app
