### ISSUE TITLE
Add "Send a message or tap the greeting bellow"

### ISSUE THREAD

**Issue by makisukurisu** [UnigramDev/Unigram#2583]
Would be great to have a thing like this. I doubt it's possible because of what is a chat window in Unigram, but if it is - it would be great to have this one as well.

(Maybe you can add an inline message with a button to send some random suggested sticker?)

So instead of seeing this:
![image](https://user-images.githubusercontent.com/49622129/146688740-ebc07998-c301-4dd6-b147-542aa3b18f62.png)

I'd like to see something like this:
![image](https://user-images.githubusercontent.com/49622129/146688760-8e602d9c-d206-45fe-b4cb-670daf928e56.png)

**Comment by FrayxRulez** [comment]
Done
