### ISSUE TITLE
Unigram stopped working

### ISSUE THREAD

**Issue by Jonikster** [UnigramDev/Unigram#2586]
Today, Unigram stopped working.
After starting, the Unigram window opens, but after a few seconds it closes.
There was no action with Unigram.
I tried to install the version 8.3.6802.0, but it still doesn't work.
I should also add that this problem today not only for me. I know other people also received this problem today.

**Comment by FrayxRulez** [comment]
What's your Windows version?

**Comment by Jonikster** [comment]
> What's your Windows version?

Windows 10 LTSC 2019

**Comment by Elshara** [comment]
@Jonikster This version of Unigram works for me. The previous 6 do not in an ideal manner. I'm using Windows 11 build 10.22523.1000.

**Comment by Jonikster** [comment]
@Elshara I'm happy, but how it can help me?

**Comment by Elshara** [comment]
@Jonikster What version of Windows do you use? Have you tried installing the version directly from the Unigram Insiders group posted as a file?

**Comment by Jonikster** [comment]
@Elshara Read above please, Windows 10 LTSC 2019
Yes, I tried

**Comment by Jonikster** [comment]
So, I think that the problem appeared after yesterday's UNIGRAM update.
How can I download the previous version so that Microsoft Store doesn't update it?

**Comment by MarcAnt01** [comment]
Hello @Jonikster please for future bug reports don't delete the template, otherwise we have to ask manually for every information

**Comment by Jonikster** [comment]
So what about this problem?
Is this connected with Windows 10 LTSC 2019?
Will it be fixed?

**Comment by FrayxRulez** [comment]
Does [this](https://t.me/unigramappx/167) work for you?

**Comment by Jonikster** [comment]
@FrayxRulez yes! Thank you!
