### ISSUE TITLE
Wrong messages accent color in chat

### ISSUE THREAD

**Issue by Marocco2** [UnigramDev/Unigram#2587]
**Describe the bug**
After 6802 update, background color of messages sent and received are forcefully blue, even if accent color is different 

**To Reproduce**
1. Go to Settings - Chat and change color of the chat
2. Click on a chat

**Expected behavior**
You should see the color selected for the messages

**Screenshots**
![immagine](https://user-images.githubusercontent.com/3944248/147007772-c1bd0ff9-8554-4fb6-97aa-f8c6383dd21d.png)

**Version Info**
 - Unigram: 8.3.6802 x64
 - Windows: 11 build 378

**Comment by FrayxRulez** [comment]
@Marocco2 Oh no

**Comment by sprainbrains** [comment]
Agree! Have the same bug in my case. 
Unigram, last version from Microsft store (ver.8.2.6793 x64)

**Comment by kurmachu** [comment]
Have this as well, Unigram 8.3 (6793) X64 on Windows 11

**Comment by Marocco2** [comment]
Fixed with 6814
