### ISSUE TITLE
When I reply to a notification from another device, the notification doesn't disappear

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2588]
**Describe the bug**
I mostly use my laptop to message, when both my iPhone and laptop are available, anyway the few times I reply from my iPhone the notification doesn't get automatically removed and stays there even for a week.

**To Reproduce**
1. Send a message with another account to yourself;
2. Reply from the other device
3. Continue using Unigram for one day as if nothing had happened
4. The notification will always be there :(

**Expected behavior**
I expect those message to be removed, otherwise it's just annoying

**Version Info**
 - Unigram: 8.3.6802
 - Windows: Windows 11 21H2 22000.37

**Comment by MaxG-Enpal** [comment]
+1

**Comment by FrayxRulez** [comment]
Still?

**Comment by MarcAnt01** [comment]
> Still?

Yes, some notifications do get stuck in the action center or whatever it's been renamed in W11
