### ISSUE TITLE
Weird text when clicking the join request topbar

### ISSUE THREAD

**Issue by Cikappa2904** [UnigramDev/Unigram#2589]
**Describe the bug**
When clicking the join request top bar on a group, the text says "TITLE, Telegram.Td.Api.ChatJoinRequest, Button1, Button2"

**To Reproduce**
1. Go to a group where you can see pending join requests
2. Click on the join request top bar
3. See error

**Expected behavior**
Text that makes sense

**Screenshots**
![image](https://user-images.githubusercontent.com/49496033/147101169-cbaf34c1-5801-4a78-a388-fe3784c16fd2.png)

**Version Info**
 - Unigram: 8.3.6793 x64
 - Windows: Windows 11 21H2 - 22000.376

**Comment by StuckDuck7710** [comment]
It seems to be a common issue in dialogs like this. I've seen broken text in the theme applier as well. I'll investigate and maybe make a PR

**Comment by FrayxRulez** [comment]
Fixed
