### ISSUE TITLE
Unigram is not opened in Windows 10.

### ISSUE THREAD

**Issue by wingspreader** [UnigramDev/Unigram#2592]
Bug is simple.
Whenever I try opening Unigram, it shuts down immediately.

I reinstalled in MS store, and re-reinstall with download version, reboot few times.

Newest version of Windows 10.

**Comment by makisukurisu** [comment]
Ok, can you enable this ⬇️ file
https://t.me/unigraminsiders/383591

Then - try to open the app again.
After that - go to %LOCALAPPDATA%\CrashDumps using explorer or Win+R

![CrashDumps folder](https://user-images.githubusercontent.com/49622129/147204662-041ed512-6306-4fd7-9f9e-0316f3ed0499.png)

You will see something like this. Sort files by date and send latest one (with Unigram in it's name) to @FrayxRulez (on telegram) with best description you can get. (Eg - windows version from Winver, Ungiram version (can find in settings or MS Store), etc.)

Thanks for your report.

**Comment by MarcAnt01** [comment]
Closed for not following the template, you need to fill every information before reporting a bug
