### ISSUE TITLE
Unigram not able to connect

### ISSUE THREAD

**Issue by dmad** [UnigramDev/Unigram#2594]
Sometimes Unigram (any recent version in the last six months) keeps on showing the "Connecting..." progress bar in its titlebar. 

![image](https://user-images.githubusercontent.com/550064/147248313-125a46d5-1d7e-44b1-ad1a-8870c45bc75e.png)

If this happens sending/receiving messages, making calls, ... don't work.

Restarting doesn't work either, waiting (sometimes days) is the only thing that works.

Note: I'm not using any kind of proxy.

**Comment by StuckDuck7710** [comment]
@dmad What version of Unigram are you currently running? I had this same problem a while ago, but it got fixed as soon as i updated. I would figure it's some sort of connection problem on your end though.

**Comment by dmad** [comment]
@StuckDuck7710 Currently I'm using Unigram 8.3 (6793) X64 (~ latest from the MS Store). About possible connection issues on my end: any other kind of connection works without problem, and my firewall is setup to allow any egress connection (both over  IPv4 and IPv6), ingress only established ones are allowed. Is there a way to see logs and/or increase the log verbosity for this kind of troubleshooting. Note: My settings have "Try connecting through IPv6" enabled, can this have something to do with it?

**Comment by MarcAnt01** [comment]
Closed for not following the bug reporting template, when creating new issues every field has to filled

**Comment by makisukurisu** [comment]
Yes, try disabling it. I don't think your ISP gave you dedicated IPv6 address

**Comment by FrayxRulez** [comment]
> Note: My settings have "Try connecting through IPv6" enabled, can this have something to do with it?

Yes, that's definitely the cause of your issue. The option is definitely mislabeled at the moment and it should rather be called "Use IPv6 instead of IPv4", as at the moment if IPv6 is not available the app will simply not connect.

**Comment by StuckDuck7710** [comment]
> Note: My settings have "Try connecting through IPv6" enabled, can this have something to do with it?

AFAIK, using that will not fallback to IPv4 is no IPv6 connection can be established. So you can try disabling it if you don't have an IPv6 address

**Comment by dmad** [comment]
I have IPv6 prefix delegation on my internet connection, and it is working correctly (e.g. I have a /56 subnet assigned to each of my LANs and using curl or any other network tool i automatically use IPv6 if my destination has IPv6 connectivity). This works even when Unigram keeps "Connecting..." so it is not related to that, and other times Unigram works fine (even with this setting on). But ok, I'll turn it off, and start troubleshooting the IPv6 aspect of it, maybe I'll find something related. Are there some logs available, or a way to enable logging?

**Comment by StuckDuck7710** [comment]
> Are there some logs available, or a way to enable logging?

Click 10 times on the version string in the Settings menu, that should allow you to enable TDLib logs. Try verbose mode if you can't find any useful info

**Comment by dmad** [comment]
> > Are there some logs available, or a way to enable logging?
> 
> Click 10 times on the version string in the Settings menu, that should allow you to enable TDLib logs. Try verbose mode if you can't find any useful info

Thank you, will do this.

**Comment by StuckDuck7710** [comment]
@dmad You're welcome! :)

**Comment by AsrorbekDev** [comment]
@StuckDuck7710 It closes unexpectedly on its own when I click some message

**Comment by AsrorbekDev** [comment]
okay

**Comment by yirgster** [comment]
I have this "Connecting ..." message twice in the last 4 or 5 days.  Settings does NOT have "Try connecting through IPv6" set.

This is from the windows unigram client app which I started using when although the telegram app now started appearing in the task bar but no window would show!
