### ISSUE TITLE
button in settings

### ISSUE THREAD

**Issue by khebar** [UnigramDev/Unigram#2596]
a button in settings is in the bad position

**To Reproduce**
1. Go to settings
2. Click on your phone number
3. the button is in the bottom and dont move 

![image](https://user-images.githubusercontent.com/96617826/147344969-a577d90f-fb78-4da6-9636-4e48da4d9f83.png)

**Version Info**
 - Unigram: 8.3
 - Windows: 10 21H1

**Comment by makisukurisu** [comment]
Partial duplicate of #2591

**Comment by FrayxRulez** [comment]
Fixed
