### ISSUE TITLE
Broken folder with group chats

### ISSUE THREAD

**Issue by LjubisaB** [UnigramDev/Unigram#2597]
**Describe the bug**
Folder "Groups" (based on groups; the folder name is irrelevant) is broken, the first click on it disable all folders and can't access any chat/folders until restart the app.

**To Reproduce**
1. Just click on folder "Groups" (horizontal or vertical, doesn't matter)

**Expected behavior**
List of chats that belong to this folder.

**Screenshots**
![20211224_145236](https://user-images.githubusercontent.com/29507336/147358383-94e4e8cb-1883-42b6-bc38-9a4b22929990.jpg)

**Version Info**
 - Unigram 8.3 (6832) x64 Direct (all 8.3 versions)
 - Windows 10 Pro 21H2 OS build: 19044.1415

**Additional context**
I tested many times, and all other folders work as expected.
Folder "Groups" contain group chats only.

**Comment by FrayxRulez** [comment]
Can you show the configuration of the folder in question?

**Comment by LjubisaB** [comment]
![20211224_153345](https://user-images.githubusercontent.com/29507336/147359582-41997249-935f-4b79-95ed-b0e43db95b50.jpg)
![20211224_153518](https://user-images.githubusercontent.com/29507336/147359584-5f172579-d42a-488d-9e5d-6cfa6e370bfb.jpg)

First is from Unigram, second is from TDesktop. On TDesktop I see one empty group (without photo and name of a group) - I don't know what is it.

**Comment by FrayxRulez** [comment]
This helps way more than you think. Thank you a lot!

**Comment by LjubisaB** [comment]
I removed "empty" group from the list (that I see only on tdesktop) and works fine for now. I never added anything except visible regular groups.

**Comment by FrayxRulez** [comment]
Well now we can't fix the issue any longer, but glad that it doesn't happen to you anymore :D

**Comment by makisukurisu** [comment]
Guess this can be closed?
