### ISSUE TITLE
Button "Add Account" disappear when adding multi account

### ISSUE THREAD

**Issue by MrTonyK37** [UnigramDev/Unigram#2598]
![image](https://user-images.githubusercontent.com/96656172/147386826-5e0cbf42-2a3b-40b1-8de8-2ce70a314f07.png)

![image](https://user-images.githubusercontent.com/96656172/147386817-7c3545d2-fb04-4d11-8ff3-79c1f0a7fcfa.png)
Unigram 8.3 (6832) X64 Direct
Windows 10 Pro 21H1 19043.1348

**Comment by StuckDuck7710** [comment]
@MrTonyK37 Not a bug! Since commit 4d0b7fc, only a maximum of 3 accounts are allowed per client instance. Users with more than that will not be logged out or affected, however.
