### ISSUE TITLE
bug in change no. orientation

### ISSUE THREAD

**Issue by Uday1272** [UnigramDev/Unigram#2599]
**Describe the bug**

**To Reproduce**
1. Go to ''
2. Click on 'settings.'
3. click on phone no.
![image](https://user-images.githubusercontent.com/86022769/147503230-134d2132-6577-4861-a9a8-a00edf370a0f.png)

**Expected behavior**
that change no. button

**Screenshots**

**Version Info**
 - Unigram: [e.g. 7.8.6339 x64]
 - Windows: [e.g. October 2018 update]

**Additional context**

**Comment by FrayxRulez** [comment]
Fixed
