### ISSUE TITLE
Keyboard shortcut to create a text-link is broken

### ISSUE THREAD

**Issue by vcprocles** [UnigramDev/Unigram#2600]
**Describe the bug**
Ctrl+K to create link in text doesnt work in the last few versions, and in 8.3 switches focus to global search. Ctrl+Shift+K doesn't work either.

**To Reproduce**
1. Type any message
2. Select a text
3. Press Ctrl+K
4. Global search appears on the left bar

**Expected behavior**
"Create Link" popup should've appeared.

 - Unigram:  8.3.6833 x64 and 8.3.6832 Direct x64 from the beta channel
 - Windows: 10 21H2

**Comment by AsrorbekDev** [comment]
@vcprocles yes i have this issue alsi

**Comment by MarcAnt01** [comment]
The shortcut has been changed to global search, but I don't know if a new shortcut has been assigned for creating a link

**Comment by rodrigost23** [comment]
Ctrl+K is a universal shortcut for creating links, it works in many editors. Shouldn't the shortcut for global search be Ctrl+Shift+F?

**Comment by pratyakshm** [comment]
@rodrigost23 +1

**Comment by vcprocles** [comment]
Ctrl+K seems to be Discord shortcut, where there aren't any hotkeys to create a link. Maybe devs should consider Ctrl+Shift+F (as said above), or maybe copy Outlook/Teams shortcut for that (Ctrl+E)

**Comment by vcprocles** [comment]
Fixed as of version 8.5
