### ISSUE TITLE
Spoiler tag doesn't hide emoji

### ISSUE THREAD

**Issue by Marocco2** [UnigramDev/Unigram#2605]
**Describe the bug**
Adding an emoji inside a spoiler markdown will remain visible.

**To Reproduce**
1. Go to a chat and find a message with spoiler tag and a emoji or DIY

**Expected behavior**
Emoji should be hidden by spoiler tag

**Screenshots**
![immagine](https://user-images.githubusercontent.com/3944248/147840497-50b5d209-a4c8-4636-84d1-95a35d760a8b.png)

**Version Info**
 - Unigram 8.4.6849 x64
 - Windows: 11

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/24b5b2a6015e480690140c50ad092c78ae373543
