### ISSUE TITLE
Select Contacts menu UI doesnt adapt dynamically.

### ISSUE THREAD

**Issue by sabbyX** [UnigramDev/Unigram#2606]
**Describe the bug**
The Select Contacts menu UI doesnt seem to adapt as per the result, instead the number of the contacts user has, this causes subsequent issues, like, if there's no contacts, the global search results wont be shown at all, or, if user has only one contact present, the search results' list view is likely very small, and affects the UX.

**To Reproduce**
I used a Test DC account, denied when asked to sync the contacts right after logging in.
1. Create a new group
2. Click on 'Add Members'
3. Search for, say, "test"
4. See error.

**Expected behavior**
Expects the UI to adapt dynamically instead of size of menu stuck with number of contacts user has.

**Screenshots**
![image](https://user-images.githubusercontent.com/61574665/147847207-5bb311eb-8e2d-4cf9-bb38-3abfff4274b1.png)

**Version Info**
 - Unigram: 8.4 (6849) x64 Direct
 - Windows: (11) 22000.348

**Comment by FrayxRulez** [comment]
Fixed 🎉
