### ISSUE TITLE
Improvements to the Russian translation

### ISSUE THREAD

**Issue by mxkmn** [UnigramDev/Unigram#2607]
Hi. Just a small translation improvement.

There is a button at the bottom for setting notifications in channels:
<img width="306" alt="image" src="https://user-images.githubusercontent.com/75564533/147851881-0d89ddd5-7e7d-4a14-845e-9faf7780d69c.png">
<img width="307" alt="image" src="https://user-images.githubusercontent.com/75564533/147851887-6d36a1b7-991d-4c49-90c5-0cadedc34ed8.png">
This is not a very correct designation of the setting, while in vain abbreviated in the first case. I suggest improvements:
Вкл. звук -> Включить уведомления
Убрать звук -> Выключить уведомления

**Comment by makisukurisu** [comment]
@mxkmn Unigram uses Android's translations, so you might want to suggest this on:

https://translations.telegram.org/ru/android/chat_list/ChatsMute

And similar for unmute. Not sure what string it's exactly, but I guess suggestions to all might help.

(Also provided solutions are long, how about Вкл. Уведомления (уведомл.), Выкл. Уведомления (уведомл.). Imho two shortened are too much, so ignore words (in those) )

Thanks for your report.
