### ISSUE TITLE
No Notification on new Message

### ISSUE THREAD

**Issue by JaggerJo** [UnigramDev/Unigram#261]
Plattform: Windows Phone 1607 (Build 10.0.14393.1066)
App Version: 0.1.152.0

Often when the app is in the background or closed, no Notifications pop up when messages are received.

**Comment by larsschellhas** [comment]
Are you sure that notifications are enabled everywhere, you are not using battery saver and W10M allows Unigram to run?

**Comment by Imma93** [comment]
I 've had this Problem on PC for some time now, although it works on my Surface. Already tried reinstalling, went through all the Settings, even after clean install of FCU (1709) there are still no Notifications for me. Which is weird cause Life Tile works properly

**Comment by Ewindar** [comment]
> some
same here.
No notification until I open the app, use MTProto Proxy.
