### ISSUE TITLE
Very high GPU % when displaying chats

### ISSUE THREAD

**Issue by Marocco2** [UnigramDev/Unigram#2613]
**Describe the bug**
During usage of Unigram, displaying chats with a minimum of 1 image element (no GIFs or videos sent) DWM.exe will rapidly use 50% of my GPU power (Surface Pro 7 i5) or worse depending how many media elements are on screen (AutoPlayback on/off isn't relevant). This isn't a normal behavior at all, compared to most applications installed on my system (MS Edge, myTube, etc.) which don't use as much power as Unigram

**To Reproduce**
1. Go to a chat with some media elements
2. Open Task Manager and check DWM.exe GPU usage
3. Open other applications and compare this value

**Expected behavior**
It shouldn't use so much GPU power to display media elements (Hardware decoding issue? Overdraw? Other bugs?)

**Version Info**
 - Unigram: 8.4.6868 x64
 - Windows: 11 build 22000.376

**Additional context**
I use Transparency effects on Windows which would explain some of this GPU usage. I could try to trace a performance profiler on Unigram if there are any instructions.

**Comment by FrayxRulez** [comment]
I have pretty low GPU usage even with the stickers/gifs panel open, around 4% I would say, using integrated GPU.
This kind of low level stuff is usually handled by the system, so I would search for the causes in a recent Windows or driver update.

**Comment by Marocco2** [comment]
I did run some tests: apparently a major contributor of high GPU usage is background image blurred effect for chats. Disabling only that would drop DWM.exe GPU usage from 50% to 10% which is pretty good

**Comment by AsrorbekDev** [comment]
@Marocco2 yes

**Comment by AsrorbekDev** [comment]
@Marocco2 new repo

**Comment by Marocco2** [comment]
New discovery: using "Adapt layout for large screens" massively help app performance. Maybe there are wasted resource usage when x coordinate of chat window is too large. In theory this is noticeable with ultrawide monitors

**Comment by FrayxRulez** [comment]
@Marocco2 Resources are handled by windows
