### ISSUE TITLE
app doesnt take input after switching windows

### ISSUE THREAD

**Issue by ai94iq** [UnigramDev/Unigram#2619]
**Describe the bug**
When I switch to another app with Alt+Tab and back to Unigram, sometimes it doesn't take any input after that switch
I have to minimize and maximize Unigram, or close/open it, then write down whatever I wanted to say

**To Reproduce**
1. have another app open, in my case Chrome
2. Switch to the other app with Alt+Tab
3. Switch back to Unigram
4. Try to input, it won't type anything
5. switch again or minizine it, and try to input again, it will work this time 

**Expected behavior**
no matter how many times I switch apps, I expected all of them to accept input whenever I start typing

**Actual behavior**
Unigram just stops taking input sometimes, and its really annoying 

**Screenshots**
https://streamable.com/u90x8u

**Version Info**
Unigram: 8.4.6853 (Store build)
Windows: 11 21H1 Update 22000.376

**Additional context**
it doesn't happen always, you have to switch more than once to get it, or copy a link from chrome and switch back
it happens often enough to be noticeable for me

**Comment by donut2008** [comment]
@ai94iq are you using unigram provided in the telegram channel or from the store?

**Comment by ai94iq** [comment]
@donut2008 store build

**Comment by donut2008** [comment]
@ai94iq i guess you have to wait for next store update

**Comment by ai94iq** [comment]
@donut2008 so latest insider build is fine ?

**Comment by donut2008** [comment]
@ai94iq yep, latest telegram channel build is fine

**Comment by ai94iq** [comment]
@donut2008 Thanks, I will try it out

**Comment by ai94iq** [comment]
@ai94iq it affects latest Beta/Insider 8.4.6873 also

**Comment by rodrigost23** [comment]
In my experience, this always happens when switching to Unigram via the ALT+Tab shortcut. Then, it's like the ALT key gets stuck, so text input doesn't work.

If I press ALT again, text input is fine.

If I switch to Unigram via other means (such as clicking on its icon on the task), this error doesn't occur.

I use US International as keyboard layout, maybe that affects it?

**Comment by makisukurisu** [comment]
Could not reproduce. There was Windows 11 update, can you tell if that helped. I suppose that this is Windows issue/UWP issue, because it looks like pointer was frozen too.

**Comment by ai94iq** [comment]
I could not reproduce also, seems to be fixed running the latest store build 6.5 (6982)

**Comment by pexch** [comment]
Currently have this error too. Any fix?
