### ISSUE TITLE
Chat/Conversation doesn't get updatet when a new message is received

### ISSUE THREAD

**Issue by JaggerJo** [UnigramDev/Unigram#262]
Plattform: Windows Phone 1607 (Build 10.0.14393.1066)
App Version: 0.1.152.0

Chat/Conversation doesn't get updatet when a new message is received. Must be reloaded manually => Leave Chat (back), enter/load again

**Comment by larsschellhas** [comment]
Already known #183

**Comment by JaggerJo** [comment]
oh, I must have overlooked thoose
