### ISSUE TITLE
The date of the advertisement is January 1, 1970

### ISSUE THREAD

**Issue by isntrui** [UnigramDev/Unigram#2620]
**Describe the bug**
The displayed year of the Telegram advertisement message is January 1, 1970, if no content was uploaded to the channel during the day.
**To Reproduce**
1. Go to a channel with advertising from Telegram, which has not posted content for the day.
2. Click on: -
3. Scroll down to the end 
4. See error (date of adversting msg is 1 Jan 1970)

**Expected behavior**
The date of the advertisement message is January 1, 1970.

**Screenshots**
[*Click me*](https://i.imgur.com/lwzLjHc.png) (The last message is an advertisement)
**Version Info**
 - Unigram: 8.4.6853 x64
 - Windows:
Release: Windows 11 Home for single language
Version: 21H2
Installation date: 26.‎10.‎2021
Build of OS: 22000.376
Interaction: Windows Feature Experience Pack 1000.22000.376.0

**Comment by ataolla** [comment]
Bro help Instagram Telegram 

,

id:?
