### ISSUE TITLE
The quoted photos/videos appear black

### ISSUE THREAD

**Issue by subvitte** [UnigramDev/Unigram#2621]
In any conversation, the photos that are quoted in a message (shown above in small size) appear black.

 - Unigram: 8.4 (6853) x64
 - Windows: 10 21H1

![Sin título](https://user-images.githubusercontent.com/62108536/149429792-70850e5b-33b3-4bb9-8853-1031c3798e8b.jpg)

**Comment by makisukurisu** [comment]
@subvitte You might want to update your app. It's from 2017/2018? Also for bugs there is a template, please, use it to report bugs.

Cannot reproduce on 8.4 ****

**Comment by subvitte** [comment]
@makisukurisu It is the version of the Microsoft store.  I downloaded it just yesterday

**Comment by makisukurisu** [comment]
Most likely because you've changed download path. Can you tell if have or haven't?

**Comment by FrayxRulez** [comment]
Was fixed
