### ISSUE TITLE
Bug in Fixed Messages tab

### ISSUE THREAD

**Issue by subvitte** [UnigramDev/Unigram#2622]
After removing the "pinned messages" tab and closing the program. When you start the program again, the tab automatically appears checked.

 - Unigram: 8.4 (6853) x64
 - Windows: 10 21H1

![Sin título2](https://user-images.githubusercontent.com/62108536/149430353-352f106c-5a41-41d6-ad11-ff1fa5f183b1.jpg)

**Comment by makisukurisu** [comment]
Can confirm. Even if you have this one deselected on other clients (I suspected it had something to do with overrides). Though Notifications about Joined users can be deselected, this one doesn't save state.
