### ISSUE TITLE
More customization in notifications

### ISSUE THREAD

**Issue by subvitte** [UnigramDev/Unigram#2623]
I want to suggest the option to disable the sound of notifications, without having to deactivate visual notifications.

To be able to do it independently in channels, groups or chats.

Also, it would be nice to be able to select custom sounds for notifications.

Thanks.

**Comment by makisukurisu** [comment]
@subvitte As far as I know, it's not possible, as window's limitation.

**Comment by MarcAnt01** [comment]
This is double from Windows settings
![image](https://user-images.githubusercontent.com/43090263/150652222-7ab45e30-92cb-4f48-8b1c-665c22993818.png)
As for custom notifications sounds there's already an open ticket
https://github.com/UnigramDev/Unigram/issues/619
