### ISSUE TITLE
Can’t create a hyperlink in caption

### ISSUE THREAD

**Issue by TigerCubDen** [UnigramDev/Unigram#2626]
**Describe the bug**
When I type words in photo's caption, I can't create hyperlink to these. The link edit interface only show after closing.

**To Reproduce**
1. Upload a photo
2. Type words in caption
3. Ctrl + k create a hyperlink

**Expected behavior**
No link edit interface until closing caption.

**Version Info**
 - Unigram: 8.4.6853 x64
 - Windows: 21H2 22000.466 X64

**Additional context**
For video of reproduce, see https://t.me/unigraminsiders/356309

**Comment by makisukurisu** [comment]
There is a workaround for now, you have to send a message and edit it afterwards. It was explained that's it's a technicality of UWP. It does not allow showing one more popup on top of existing one.

**Comment by FrayxRulez** [comment]
A workaround was introduced in https://github.com/UnigramDev/Unigram/commit/736a07377268a419bcd761b460d8540b2f362f61. You can now create a hyperlink in caption by selecting the target text and pasting the link to it.
