### ISSUE TITLE
The unread counter in the taskbar is misbehaving with multiple accounts

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2631]
**To Reproduce**
1. Get some messages with Unigram minimized

**Expected behavior**
Update the badge accordingly

Version Info
- Unigram: 8.4.6885 x64
- Windows: 11 21H2

**Additional context**
I have started to notice this behavior in some weeks, so after 8.4

**Comment by FrayxRulez** [comment]
@MarcAnt01 Lies

**Comment by MarcAnt01** [comment]
It seems to be working now, have to understand if it was random or it happens under certain conditions before closing this

**Comment by FrayxRulez** [comment]
Congratulations, that's the perfect screenshot to send to Microsoft

**Comment by MarcAnt01** [comment]
Not really, since it seems to happen when there are unreads on both accounts (still needs investigation)

**Comment by meh7an** [comment]
@MarcAnt01 One way to reproduce is to have an account with no counter and switch the account. As long as you don't open a chat with counters (even muted) taskbar counter won't get updated.

The fix may be to update the counter as soon as account is switched.

**Comment by MarcAnt01** [comment]
Thanks for the detail, in fact I was noticing it coming back after a while.
Definitely not something to send at Microsoft imho @FrayxRulez

**Comment by MarcAnt01** [comment]
Unigram 8.5.6924. I can still reproduce the bug, furthermore the tray icon doesn't show the badge right now
![image](https://user-images.githubusercontent.com/43090263/154708739-3700deea-bb60-4684-a70c-c9a7eca7ce20.png)
