### ISSUE TITLE
Inline mode sticker answer make unigram crash

### ISSUE THREAD

**Issue by codehz** [UnigramDev/Unigram#2632]
**Describe the bug**
If a bot use inline mode for sticker search, and it provide a invalid sticker (width / height > 512px), the unigram crash silent.

**To Reproduce**
1. open my sticker bot (marked [commit](https://github.com/codehz/stickerbot/commit/09ced105e344414eb4f4d90e140d95abc4ae63f3) since I may limit input length in future) `@TextStickerMakerBot`
2. type `/start create` `steam` `tiny` `a really long texta really long texta really long text`, and then tap the send button select a chat
3. the unigram crash

**Expected behavior**
NO CRASH AT ALL

**Screenshots**
<img width="242" alt="image" src="https://user-images.githubusercontent.com/13158903/151743188-2d4ae5d3-9bdd-4922-9b55-5f1c39d44cf2.png">
(The sticker size is invalid, but it can be shown as normal message)
(and the crash has no screenshot)

**Version Info**
 - Unigram: 8.4 (6853)
 - Windows: win11

**Additional context**

**Comment by FrayxRulez** [comment]
Ahhhhhhh... 😂

**Comment by makisukurisu** [comment]
Was fixed, as I can see. If it's not - comment here again. Thanks.
