### ISSUE TITLE
One click on the tray icon should be enough to open Unigram

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2633]
With Unigram two clicks are necessary, Telegram Desktop, OneNote etc. and any other software I have in my device requires only one click.

**Comment by FrayxRulez** [comment]
Only one click causes the tray icon to be clicked even if you right click to open the context menu and then you click outside, that's why you need two clicks.

**Comment by atbug** [comment]
> Only one click causes the tray icon to be clicked even if you right click to open the context menu and then you click outside, that's why you need two clicks.

Is this a technological limitation of UWP apps?

**Comment by MarcAnt01** [comment]
> > Only one click causes the tray icon to be clicked even if you right click to open the context menu and then you click outside, that's why you need two clicks.
> 
> Is this a technological limitation of UWP apps?

Definitely not uwp, since uwp itself doesn't support tray icons. The tray icon is made with Winforms if I'm not mistaken. Maybe @FrayxRulez can provide more context if you are interested
