### ISSUE TITLE
reaction flyout bug.

### ISSUE THREAD

**Issue by kinopikopapa** [UnigramDev/Unigram#2634]
Scrolling the reaction flyout outside the main window of unigram will leave flyout.

![image](https://user-images.githubusercontent.com/84464712/151825095-3060aa92-db96-4120-a286-4c3f29f2570f.png)

**Comment by FrayxRulez** [comment]
@kinopikopapa Maybe you could attach a video because I don't understand.

**Comment by kinopikopapa** [comment]
It seems to happen when I right click and then click on the desktop.

https://user-images.githubusercontent.com/84464712/151838724-fb49e5f6-0219-4302-8b0e-740b4ceae9a2.mp4

**Comment by kinopikopapa** [comment]
It was solved in the latest version.
