### ISSUE TITLE
can't finish the translation

### ISSUE THREAD

**Issue by kinopikopapa** [UnigramDev/Unigram#2635]
I can't finish the translation. It works fine in the store version.
![image](https://user-images.githubusercontent.com/84464712/151841783-9f1bf47d-35f8-487c-9a4c-c5201d231355.png)

https://user-images.githubusercontent.com/84464712/151841830-8b9012f0-56ba-4e55-b5f8-81c77d833ed5.mp4

**Comment by MarcAnt01** [comment]
@kinopikopapa please follow the ticket template. Every section is important, in this case repro steps and Windows version are missing

**Comment by kinopikopapa** [comment]
sorry.
It was solved in the latest version.
