### ISSUE TITLE
Double vs single click on tray icon

### ISSUE THREAD

**Issue by atbug** [UnigramDev/Unigram#2636]
At this moment, to bring out the main unigram window, I have to double click on the system tray icon. However, all other applications require only a single click. This sometimes confuses me.

Is it reasonable to consider the other behavior: single click brings out the main window?

**Comment by MarcAnt01** [comment]
Hello, thanks for your issue, there's an identical ticket with a reply from the developer

**Comment by MarcAnt01** [comment]
Duplicate of https://github.com/UnigramDev/Unigram/issues/2633
