### ISSUE TITLE
Context menus to show who has reacted is missing some features

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2637]
- [ ]  Show the propic of who has reacted;
- [ ] Go to the profile of who has reacted on click
- [ ] Hide the menu for channels

**Comment by FrayxRulez** [comment]
Done in https://github.com/UnigramDev/Unigram/commit/3dbe571090f678b5b4134504e5210bea2055bc77

**Comment by amirmahdifard** [comment]
hello, is this also accessible for blind people too now? thanks for answering.

**Comment by FrayxRulez** [comment]
@amirmahdifard No, it is still not technically possible to make this menu accessible.

**Comment by amirmahdifard** [comment]
@FrayxRulez oh, how sad: do you have a plan to recode this later so you can aalso make this accessible for blind people too, i hope you do: thanks for answering: also, i sent a message in private to you, please check if possible: thanks.
