### ISSUE TITLE
Reactions should enlarge (for touch-friendliness) when the context menu is clicked with touch

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2638]
Mouse/pen
![image](https://user-images.githubusercontent.com/43090263/152149253-e4220762-2522-416c-ac03-38922ce3d33d.png)

Touch
![image](https://user-images.githubusercontent.com/43090263/152149282-b2b10998-fefe-44e1-87d1-a5d2f8fa1088.png)

**Comment by FrayxRulez** [comment]
Done in https://github.com/UnigramDev/Unigram/commit/3dbe571090f678b5b4134504e5210bea2055bc77
