### ISSUE TITLE
Unigram doesn't consider members with last seen hidden in the online count for small groups

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2639]
**Describe the bug**
Members with last seen disabled doesn't seem to be counted in the online members. So the count in any Telegram app is different from the one in Unigram

**To Reproduce**
A small group with some members with last seen disabled is enough

**Expected behavior**
Have a consistent count 

**Screenshots**
![image](https://user-images.githubusercontent.com/43090263/152245981-8b01cdc0-8e9d-4d9e-9a8c-0772a58f9bdb.png)
![image](https://user-images.githubusercontent.com/43090263/152245998-ab71a6ef-2cb9-478c-a7d1-dbb66667d2e7.png)

**Version Info**
 - Unigram: 8.5.6921 x64
 - Windows: Windows 11 21H2

**Additional context**
I'm available if more information is needed for the type of groups and the settings

**Comment by FrayxRulez** [comment]
@MarcAnt01 @levlam this is for you

**Comment by levlam** [comment]
This is intended. The number of online users in small groups is more precise than in big ones. Apps shouldn't count all users with hidden online status as online.

**Comment by MarcAnt01** [comment]
@lev
