### ISSUE TITLE
Add emoji picker for keyboard users

### ISSUE THREAD

**Issue by adrianghc** [UnigramDev/Unigram#264]
There is no straightforward way to type emoji when typing on a PC with hardware keyboard instead of the touch keyboard. Telegram Desktop has a button to insert emoji from a list for the user's convenience. Unigram should do this as well.

**Comment by Alexmitter** [comment]
@adrianghc Microsoft has to do that. MS IME keybords like Pinyin already have a emoji button.

**Comment by adrianghc** [comment]
Why does Microsoft need to do that? Telegram Desktop has its own emoji picker, after all.

**Comment by mateiradu** [comment]
Microsoft is actually working on an Emoji panel for hardware keyboard users that can be opened with a keyboard shortcut.

More information in this [Windows blog post](https://blogs.windows.com/windowsexperience/2017/06/08/announcing-windows-10-insider-preview-build-16215-pc-build-15222-mobile).

![](https://winblogs.azureedge.net/win/2017/06/2bb944819ff519ff31fab8d9734be022.png)

**Comment by larsschellhas** [comment]
Because of that, we'll close this issue.

Emoji-Picker for PC comes with the Fall Creators Update ;)

**Comment by shmykelsa** [comment]
Windows 10 FCU is out, emoji window is not working on every Language (it works 100% on EN-US), but it disappears after just one emoji tapped. Unconvenient. 

Maybe it's the case to have an own emoji bar.

**Comment by FrayxRulez** [comment]
Since some Unigram versions you can search for emojis by typing `:`

**Comment by Triang3l** [comment]
The on-screen keyboard button can be enabled by right-clicking the notification bar. I don't know if it would be a good idea to hardcode all emoji ranges, since new emoji can be added in future updates. Though there's no taskbar in fullscreen mode :(

**Comment by KamistixX** [comment]
Almost 2018, and I am still unable to use emojis via a panel. What are Microsoft doing for other keyboard layouts as en-US ? I am using AZERTY and cannot use this new feature promised in the 1709 Fall Creators Update.

A good alternative in Unigram would be an integrated combined GIF/Stickers/emojis panel, similar to Telegram Desktop or Telegram macOS native app.

[Illustration](http://www.aggiornamentilumia.it/wp-content/uploads/2017/05/Telegram-Desktop-1.1.png)

**Comment by adrianghc** [comment]
The emoji panel is arriving with the next version of Windows (1803) for a number of new layouts, including fr-FR if I recall right. This said, you can already search for emojis on Unigram and Telegram by typing a colon :

**Comment by SerpentDrago** [comment]
This is dumb , i get i can hit win +  ;  key to pull it up , but just add a stupid button the app , THE OFFICAL telegram app has one , why does this one not ?

**Comment by FrayxRulez** [comment]
It’s not just about “add a stupid button”, it’s about implementing the emojis panel with skin tone selector and so on, and this requires days of work.

**Comment by FrayxRulez** [comment]
Implemented emojis panel in https://github.com/UnigramDev/Unigram/commit/a0560413a837fbf7b800dbe6e034b8e634e349d0
