### ISSUE TITLE
Non-clickable links in messages when using touch or pen

### ISSUE THREAD

**Issue by dargow** [UnigramDev/Unigram#2643]
**Describe the bug**
Non-clickable links in messages when using touch or pen, because Unigram understands it as highlighting text. With mouse no probem.

**To Reproduce**
1. Go to any message with link
2. Click (touch) on link
3. The link does not open, highlight icon appears

**Expected behavior**
--

**Screenshots**
![image](https://user-images.githubusercontent.com/12033844/152534516-05fa8a5b-5c89-4a57-8684-b645a516b0ac.png)

**Version Info**
 - Unigram: [8.5 (6920) x64]
 - Windows: [11, 21H2 22000.469]

**Additional context**
---

**Comment by AsrorbekDev** [comment]
@dargow say: imaybe windws 11 bug

**Comment by MarcAnt01** [comment]
WinUI/Windows bug. Feel free to upvote here https://github.com/microsoft/microsoft-ui-xaml/issues/6513
