### ISSUE TITLE
Reactions in private chats shouldn't display the propic

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2649]
Unigram
![image](https://user-images.githubusercontent.com/43090263/153424350-68f15862-7e46-48ea-ba84-d5db193531ea.png)
Any other client (TD in this case)
![image](https://user-images.githubusercontent.com/43090263/153424471-080e83ed-5739-43a0-9572-930faf442004.png)

**Comment by FrayxRulez** [comment]
@MarcAnt01 Who said that

**Comment by MarcAnt01** [comment]
Because it's clear that the other person reacted to a message, isn't it? Whatever, I'd be ok if other clients wouldn't do that, since the behavior is not show it in private chats in Telegram desktop/iOS, I'd rather Unigram to behave in the same way

**Comment by AiseKaise** [comment]
@MarcAnt01 unigram is different 😩

**Comment by MarcAnt01** [comment]
> @MarcAnt01 unigram is different 😩

No, Unigram is pretty similar in all features, since they are implemented in a similar way to official clients

**Comment by AiseKaise** [comment]
@MarcAnt01 what do you think, unigram should have a unique feature like only unigrams has that non other client like a feature turn on read receipts in dms

**Comment by makisukurisu** [comment]
Maybe Instagram like approach is better.
![image](https://user-images.githubusercontent.com/49622129/153668946-92a56f31-ecbd-43d8-9b01-81764447565c.png)

So I thought of:
Just replacing profile picture with nothing
![image](https://user-images.githubusercontent.com/49622129/153669462-a389ebd5-10d5-4c4d-b7e1-55bf9586e5e1.png)
Shrinking bubble size and centering emoji in this ellipse (Well, I haven't centered it)
![image](https://user-images.githubusercontent.com/49622129/153669892-9c9c043d-13df-42f9-9baa-f54cc1e026e8.png)

**Comment by FrayxRulez** [comment]
Now it's good to go
