### ISSUE TITLE
Self-Destruct media allows to screenshot or record video it

### ISSUE THREAD

**Issue by makisukurisu** [UnigramDev/Unigram#2650]
**Describe the bug**
If you open a self-destruct media (video or photo) and take a screenshot or recording of it, you wont get black screen, as you would in chats where it's prohibited to forward content and secret chats.

**To Reproduce**
1. Go to your friend/your other account
2. Receive/Send self-destruct media
3. Take a screenshot of your screen/part of screen
4. See media

**Expected behavior**
Showing black screen for whole app.

**Screenshots**
![image](https://user-images.githubusercontent.com/49622129/153490881-a75e3f4a-3485-47cd-961b-d4473cd088a8.png)
This, this is not ok

**Version Info**
 - Unigram: v8.5 6938 x64 Directly pointing out that this template should be updated
 - Windows: Windows 11 22000.434

**Additional context**
You might want to check Version info

Thanks to @mhpusin for pointing out this one

**Comment by FrayxRulez** [comment]
This is fixed
