### ISSUE TITLE
Unigram shows "Transfer ownership" and "dismiss admin" button to current owner of group

### ISSUE THREAD

**Issue by makisukurisu** [UnigramDev/Unigram#2651]
**Describe the bug**
Transfer ownership button is shown for current owner of the group, the same applies for "dismiss admin"

**To Reproduce**
1. Go to your own group
2. Go to Manage Group->Administrators
3. Select yourself

**Expected behavior**
Not show this button, or make it gray.

**Screenshots**
![Image.img.png.jpg](https://user-images.githubusercontent.com/49622129/153601948-489862b7-e37c-4b78-961a-147117a4cd67.png)

**Version Info**
 - Unigram: v8.5 6938 x64 Direct
 - Windows: 11 22000.434

**Additional context**
[From this message](https://t.me/unigraminsiders/399502)
Thanks to @ProVITian for reporting

**Comment by meh7an** [comment]
@makisukurisu Add dismiss button too
