### ISSUE TITLE
Feature Proposal: allow choosing the network interface to use

### ISSUE THREAD

**Issue by NotesOfReality** [UnigramDev/Unigram#2652]
Would you please add an option (in the "Advanced" sections of the settings) to choose which network interface Unigram should "listen on"?

My humble concept is a list drop-down menu with all the available net. interf. , just like [QBitTorrent](https://github.com/qbittorrent/qBittorrent/wiki/Explanation-of-Options-in-qBittorrent#qbittorrentspecific-configuration) (_maybe_ [this](https://github.com/qbittorrent/qBittorrent/blob/78eaa49cd6b3b59c064cd461fe6d30eceaeac770/src/gui/advancedsettings.cpp#L68) could be a useful "start"?) 
![image](https://user-images.githubusercontent.com/11523796/153656277-c6b1eeb2-a191-4b0a-9d4e-b4607d82d0c3.png)

Unfortunately I have to keep my VPN connection active and its split-tunnelling driver fails _so hard_ at avoiding to route Unigram by its net. interf. and all my tries to manually bind Unigram to my main ("non-VPN") net. interf. failed too.
I have no experience with proxy and IPv6, if anyone could suggest me a workaround which leverages either or both of these two techs, please let me know.

**Comment by NotesOfReality** [comment]
Done, hopefully this issue doesn't simply die 😄

**Comment by FrayxRulez** [comment]
I'll close it here since we have it on TDLib as well
