### ISSUE TITLE
Video Played in wrong direction

### ISSUE THREAD

**Issue by codehz** [UnigramDev/Unigram#2654]
**Describe the bug**
All video played in wrong direction in one of my machines (which screen has been rotated in 90 deg (counterclockwise), but the video is rotated as 270 deg (counterclockwise) that's weird)

**To Reproduce**
1. (Maybe) rotate your screen to 90 deg
2. playing a video (not as preview)

**Expected behavior**
no rotate

**Screenshots**
![image](https://user-images.githubusercontent.com/13158903/153755732-e96b2195-e083-4e59-ad64-d08712aae689.png)

![image](https://user-images.githubusercontent.com/13158903/153755536-50c493f2-49a0-49a1-8912-42bc5c91c7a8.png)

**Version Info**
 - Unigram: 8.5(6920)
 - Windows: win11 insider build 22543

**Additional context**

Those videos can be played in correct direction in another application including built-in video app and vlc. so I don't think it related to the video itself.

**Comment by donut2008** [comment]
@codehz 220122?

**Comment by codehz** [comment]
@donut2008 sorry, it is 22543.rs_prerelease.220122-2315

**Comment by tommy071306** [comment]
220122-2315

**Comment by FrayxRulez** [comment]
Considering that the player was replaced with VLC, I think we can safely assume that this bug is gone.
