### ISSUE TITLE
Emoji Set personalisation should show the Windows 11 emoji thumbnail

### ISSUE THREAD

**Issue by vivaanmathur** [UnigramDev/Unigram#2657]
Unigram Settings > Chat Settings > Emoji Set > Microsoft shows a thumbnail of the Windows 10 emojis. 
It is not a major issue, but it could be misleading for some.
Microsoft has updated Windows 11 with new emoji now, so it should be the right time to change this.
![image](https://user-images.githubusercontent.com/42546935/154052594-49b8e7ce-6315-45e7-846b-9464b4fdaa30.png)

**Comment by FrayxRulez** [comment]
Design was changed and this is no longer needed
