### ISSUE TITLE
Partial drag of "Record voice message" button causes recording UI to soft-lock

### ISSUE THREAD

**Issue by makisukurisu** [UnigramDev/Unigram#2661]
**Describe the bug**
If you drag (Click then release when it's up) "Record voice message" only a part of needed distance to lock, instead of sending recorded message or canceling recording if it's too small (like on mobile)

**To Reproduce**
1. Go to any chat where you can send voice messages
2. Click and hold on "Record voice message" Button
3. Pull it up just a bit
4. Release
5. You've got recording bar soft-locked until you reopen the app/change account

**Expected behavior**
Stop recording, or send recorded part of voice message, or lock at any height that's higher than message bar.

**Screenshots**
![image](https://user-images.githubusercontent.com/49622129/154339879-0b1085d1-edb1-4754-bacb-71efc162e31b.png)

Also a video of it [here](https://t.me/unigraminsiders/401910)

**Version Info**
 - Unigram: v 8.5 6984 x64 Direct (pls update the template)
 - Windows: 11 22000.527 21H2 (at least Windows version, since it's going to be unsupported with release of 8.6 stable or next direct build)

**Additional context**
Thanks to @HibikiShuhasu for reporting this problem [here](https://t.me/unigraminsiders/401901)

**Comment by makisukurisu** [comment]
*additional note - if you return to same account without resetting the app it actually still records message, and to send next you have to record a "new" message (it won't show UI, even if you drag or press and hold, or press Ctrl+R), if you then click again to send it - you will have a whole recording from the moment you started it before switching accounts.

So it's also expected to stop recording if you switch accounts and reset the cache.

**Comment by FrayxRulez** [comment]
I think I fixed it, reopen it if not
