### ISSUE TITLE
Shift + Click Chat stopped opening separate chat tab

### ISSUE THREAD

**Issue by polyphia** [UnigramDev/Unigram#2667]
Before the option in the context menu it was possible to open a chat in a new window using shift + enter

**Comment by makisukurisu** [comment]
@TriptonPt You can open chat in separate window by right clicking on it and selecting "Open in new window" option.

**Comment by TriptonPt** [comment]
@makisukurisu tyvm I didn't notice that . 

So does that mean there no longer is a shortcut for this action ?

**Comment by TriptonPt** [comment]
@makisukurisu definiitely , it was much more convenient that way . 

ANyway, this will do for time being, thanks again ! :)

**Comment by TriptonPt** [comment]
Would just like to add that if you search for a channel it is not possible to right click it and bring the menu to open it a new tab . 

WHen shift + click worked it was possible to run the action on a channel found through search . 

1 more reason to justify having shift + click back

**Comment by Sly-Ozc-34** [comment]
- - [ ]

**Comment by Sly-Ozc-34** [comment]
Ben

**Comment by FrayxRulez** [comment]
The option to open a chat to a new window has been moved to the context menu and I'd prefer not to have the shift shortcut for this anymore

**Comment by xperiandri** [comment]
> The option to open a chat to a new window has been moved to the context menu and I'd prefer not to have the shift shortcut for this anymore

Why not?
