### ISSUE TITLE
Can't save Test Server account after restart

### ISSUE THREAD

**Issue by zhanghua000** [UnigramDev/Unigram#2669]
**Describe the bug**
Can't save Test Server account info after restart program

**To Reproduce**
1. Add a Test Server account
2. Exit Unigram
3. Start Unigram

**Expected behavior**
Test Server account is saved so I don't need to login again

**Screenshots**
![image](https://user-images.githubusercontent.com/17194552/155945551-6f988f37-8110-478f-890f-353c22e42bcb.png)

**Version Info**
 - Unigram: 8.5.6982.0 x64
 - Windows: Windows 11 Insider Dev Channel, version 22563.1

**Additional context**
It seems that the place where account should be is empty after restart.

**Comment by makisukurisu** [comment]
Don't use Test DC is my reply, but yeah, that's some sort of bug. I assume that Test DC don't respond with something Unigram likes. So it shows nothing instead.
