### ISSUE TITLE
Log In by phone number page visual bug

### ISSUE THREAD

**Issue by makisukurisu** [UnigramDev/Unigram#2670]
**Describe the bug**
If QR-code was not generated when you pressed "Log In using your phone number" you will get empty page when it will be loaded.

**To Reproduce**
1. Go to Add Account
2. Click on Log in using your phone number BEFORE QR-code was generated
3. Wait a few seconds

**Expected behavior**
Don't interrupt page content

**Screenshots**
[Screen recording](https://t.me/unigraminsiders/405927)

**Version Info**
 - Unigram: v 8.6 7008 x64 Direct
 - Windows: Windows 11 21H2

**Additional context**

Thanks to @orezraey for this report

**Comment by FrayxRulez** [comment]
This was fixed in https://github.com/UnigramDev/Unigram/commit/1aad334be6a7a4086d7222f1d2864f04d0768c91
