### ISSUE TITLE
Add ability to add contact to a folder from it's menu

### ISSUE THREAD

**Issue by xperiandri** [UnigramDev/Unigram#2671]
When you open the chat in a new Window it is very inconvenient that you cannot add or remove it from the folder using the menu
![image](https://user-images.githubusercontent.com/2365592/156202595-c40710af-c4c2-46c5-ae35-ccb451f81abe.png)
Or maybe from this menu
![image](https://user-images.githubusercontent.com/2365592/156202811-9709a28c-88c8-4c22-8b9b-8a7d39fabb07.png)

**Comment by makisukurisu** [comment]
If you want to remove a user from a group, or add a user to a group - use group menu:

![image](https://user-images.githubusercontent.com/49622129/156204997-41063299-8308-46f2-86ea-896ccdb5fb12.png)

On top - to add a user, or using context menu in members list to remove a user from group.

If you are not fluent in English - you can DM me in telegram to tell what problem you have in either - Ukrainian or Russian, so I can add a proper description to your issue. [My profile](t.me/Man_with_name)

Thanks for the report

**Comment by xperiandri** [comment]
Sorry, I mean folders, not groups

**Comment by MarcAnt01** [comment]
Folders are made to organize chat lists, so putting the option inside the chat makes no sense in my opinion

**Comment by xperiandri** [comment]
Imagine the scenario:
1. I opened the chat from contact the first time.
2. I've been in the chat for a while. New messages came so that chat went somewhere down.
3. I decided that I need to add this chat to a folder
Then I need to scroll somewhere down and look for that chat in order to do that. Why can't I do that from the chat menu?

**Comment by MarcAnt01** [comment]
I think the solution would be to show the context menu from search, certainly not put it in the chat part

**Comment by xperiandri** [comment]
From search is a good option. I like it.

**Comment by MarcAnt01** [comment]
All right, then I'm closing this
You can find my ticket for having the context menu from search here https://github.com/UnigramDev/Unigram/issues/2395
