### ISSUE TITLE
Forwarding multiple media from Chat Info

### ISSUE THREAD

**Issue by makisukurisu** [UnigramDev/Unigram#2673]
**Describe the bug**
If you attempt to forward multiple media/files/links/anything from chat Info view you will find that you cannot.

**To Reproduce**
1. Go to Chat Info (click on bar at the top, that one with chat name and picture)
2. Click Media tab
3. Right click on media, press "Select" (see image 1)
5. Select a few media elements (see image 2)
6. Right click on selection once more and see image 3
7. Nothing changed - right click once more just to make sure click did something (see image 4)
8. Click on "Forward Selected"
9. Get only media you clicked on.

**Expected behavior**
Get option to forward after step 5, or on image 3. Right after you selected a few images - it should show not "Select" button, but "Forward", "Clear selection", etc.

**Screenshots**
**Image 1**
![image](https://user-images.githubusercontent.com/49622129/156373502-a60a7c92-fc17-4708-8bcd-d96c2db58805.png)

**Image 2**
![image](https://user-images.githubusercontent.com/49622129/156373612-0a4b4d40-a27b-4154-9549-dee5b49dd0d4.png)

**Image 3**
![image](https://user-images.githubusercontent.com/49622129/156373778-787e83f0-275a-422f-b1d0-10dd93d51ba4.png)

**Image 4**
![image](https://user-images.githubusercontent.com/49622129/156373826-42868b67-f7fd-489e-826a-7fddf16b1782.png)

**Version Info**
 - Unigram: v 8.6 7017 x64 Direct
 - Windows: Windows 11 21H2

**Additional context**
Pretty long one, hope it's easy to understand.

P.S. Context Menu with only "Select" option is shown when selection mode is one and you click on an element which is not the one which triggered selection mode. (So if you click to select on element no. 4 and then select 1-3, they will have only "Select" option, but menu of 4th will always show "Forward", "Delete" and "Clear" selection)

**Comment by m-alice** [comment]
Also, if you have a message with multiple pictures, you forward only first.

1. Paste three or more pictures (ctrl+v)
2. Send it to contact1
3. Right-click this message and forward to contact2
4. Contact2 receive only one (first) picture

But if you use _select_ menu, all three is sent correctly
_Sorry, if you consider this as hijacking_

**Comment by FrayxRulez** [comment]
Done
