### ISSUE TITLE
When the message sent by the bot has a large number of selection blocks, it will cause stuttering

### ISSUE THREAD

**Issue by iiijam** [UnigramDev/Unigram#2674]
**Describe the bug**
When the message sent by the bot has a large number of selection blocks, it will cause stuttering

**To Reproduce**
1. Go to '[...](https://t.me/mengxblog/10528)'
2. Click on 'OPEN UNIGRAM'
3. Scroll down to the message

**Expected behavior**
When the message sent by the bot has a large number of selection blocks, it will cause stuttering

**Screenshots**
<img width="228" alt="image" src="https://user-images.githubusercontent.com/16839488/157050612-20b0b447-13d6-4b78-bd16-524d6570704f.png">

**Version Info**
 - Unigram: [e.g.8.5 6982 x64]
 - Windows: Windows 11

**Additional context**

**Comment by makisukurisu** [comment]
@iiijam It's because Acrylic elements can drag performance. To me it doesn't stutter, just FPS is lower. You can "fix" this by disabling transparency in Windows settings 🙂

**Comment by makisukurisu** [comment]
@FrayxRulez , what should be done with this one? Close it, or are you planning to change how inline buttons are done?

**Comment by FrayxRulez** [comment]
@makisukurisu I have no plans but I feel that if the app stutter just because of some basic UI effect you might want to disable those in your system (and probably Microsoft should improve their low hardware detection

**Comment by iiijam** [comment]
I’m using Legion Slim 7 with AMD Ryzen™ 7 5800H  and NVIDIA GeForce® RTX™ 3060, is it a low hardware?

**Comment by FrayxRulez** [comment]
@iiijam I use a PC that’s definitely less powerful than your (at least in terms of graphics) and I don’t experience any stuttering at all

**Comment by FrayxRulez** [comment]
@FrayxRulez Telegram iOS stutters tho 🤣

**Comment by iiijam** [comment]
I tried telegram web and telegram iOS. telegram for iOS also appears shuttered when loading this emoji minesweeper, but very slightly😂

**Comment by makisukurisu** [comment]
Guess I can close this one.

If you feel like this needs to be reopened - feel free to comment.

> @makisukurisu I have no plans but I feel that if the app stutter just because of some basic UI effect you might want to disable those in your system (and probably Microsoft should improve their low hardware detection)

But since this was said - most likely it won't change anyways.
P.S. _(You can disable transparency in system settings to reduce lag from those messages)_
