### ISSUE TITLE
How to automatically select available proxies

### ISSUE THREAD

**Issue by xingleiwu** [UnigramDev/Unigram#2675]
I am working with an agent. Every time I open Unigram, I need to manually select the local agent to send and receive messages. How can I automatically select the available agent every time I open Unigram?

**Comment by makisukurisu** [comment]
It selects last chosen one, doesn't it? Can you add details like your Unigram version (Go to settings and scroll to bottom)

Thanks for report, but please - don't create issues for questions, go to t.me/unigraminsiders for such purposes.

**Comment by makisukurisu** [comment]
You haven't replied in 16 days. I'll close the issue, feel free to comment if you still have this problem.
