### ISSUE TITLE
wide (normal) scrollbar width

### ISSUE THREAD

**Issue by barn852** [UnigramDev/Unigram#2678]
It's pretty hard to grab the narrow scrollbar on the chat window (right). Since scrollbar is autohide by default, no need for autohide and being narrow together.
Is it possible to make an option to set it to normal size?
(ps: just to be clear, I am using mouse)

**Comment by FrayxRulez** [comment]
@barn852 System settings > Accessibility > Visual effects > Always show scrollbars

**Comment by barn852** [comment]
Do you mean windows system settings? I do not want to do that, I don't want to change systemwide. And it does not change the fact that it's just too narrow for grabbing. But thanks anyway.

**Comment by FrayxRulez** [comment]
> Do you mean windows system settings? I do not want to do that, I don't want to change systemwide. And it does not change the fact that it's just too narrow for grabbing. But thanks anyway.

The scrollbars used by Unigram are literally the ones provided by Windows :D you can find them in any non-legacy software.
If they annoy you in Unigram they must annoy you in other softwares as well, and even more Unigram has no control over the behavior of the scrollbars.

**Comment by barn852** [comment]
OK, thanks for the quick response.
