### ISSUE TITLE
crash on Opening channel 

### ISSUE THREAD

**Issue by behroozbc** [UnigramDev/Unigram#2679]
**Describe the bug**
When i want open channel unigram crashing channel like https://t.me/vigiatonet

**To Reproduce**
1. open uigram
2. click on channel in list of messages 

**Expected behavior**
Open the channel and show the contents 

**Version Info**
 - Unigram: 8.6 (7180) X64
 - Windows: Windows 10 19044.1586

**Comment by FrayxRulez** [comment]
Hi, this is known and an update is rolling out... Sorry for the inconvenient!

**Comment by behroozbc** [comment]
Hi @FrayxRulez, thanks for your great application and support 😄

**Comment by m-alice** [comment]
just crashing randomly in channel. WE logs attached, maybe it will be helpful 
[windows_events.zip](https://github.com/UnigramDev/Unigram/files/9004779/windows_events.zip)
