### ISSUE TITLE
Drag 'N Drop files into chats not working at all - Is this a supposed behaviour?

### ISSUE THREAD

**Issue by dariopedroniDEV** [UnigramDev/Unigram#2681]
Windows 10 64-bit, Version 21H1 build 19043.1586
I am not able to drag 'n drop into any conversation on Telegram any kind of file from File Explorer, which is something I can normally do on the official Telegram client.

Is this an expected behaviour?

**Comment by FrayxRulez** [comment]
Drag and drop is controlled by Windows UAC, and if it doesn't work it typically means that you disabled it.

**Comment by dariopedroniDEV** [comment]
> Drag and drop is controlled by Windows UAC, and if it doesn't work it typically means that you disabled it.

Enabling UAC again did the trick, thank you.
Do you have any documentation/page explaining why this happens? I am just curious.

**Comment by makisukurisu** [comment]
Cannot find it in documentation about D&D on Microsoft docs. Anyways - allow me to close the issue. You can still comment if you have anything to add or ask.

Thanks for your report.
