### ISSUE TITLE
When I click into the channel info to view the comment, it doesn't jump to the first comment

### ISSUE THREAD

**Issue by mccrena** [UnigramDev/Unigram#2682]
When I click into a post with more than 30 comments (approximately), I jump to the post in the middle (as you can see from the scrollbar position on the right), not the first comment.
I have to use the mouse wheel or click the pinned post to get back to the first comment.

**To Reproduce**
1. Click into a channel message with more than 30 comments.
2. Then you will find that you jump to the comment in the middle position.

**Expected behavior**
Jumps to the first comment when clicking on a comment on channel information regardless of how many comments there are.

**Version Info**
 - Unigram: [8.6.7179 x64]
 - Windows: [Windows10 21H2]

**Comment by FrayxRulez** [comment]
Fixed
