### ISSUE TITLE
[ARM64] Gifs: non-fullscreen view shows yellow lines / rendering errors

### ISSUE THREAD

**Issue by null-von-sushi** [UnigramDev/Unigram#2686]
**Describe the bug**
When havings .GIF images either in the gif search (emoji / sticker panel) or in a conversation, they have yellow stripped lines and do not render correctly. They might still animate despite the rendering error however. Opening the gif in fullscreen view by clicking on it however shows the gif normally without issues.

**To Reproduce**
1. Go to any chat
2. Click on gif/stickers/emojis next to the voice-message recording button
3. Search for any gif.
4. [Observe the (inconsistent) reliability of rendering in the search results.](https://user-images.githubusercontent.com/13616397/158985370-26fb9edb-a5d0-461c-9911-dc502d9e2226.png)
5. Post a gif. 
6. [Observe the rendering issue in the chat](https://user-images.githubusercontent.com/13616397/158985522-b0c202b2-336d-42d6-aa25-488e57693bd7.png)

**Expected behavior**
GIF files should either at least correctly render the first frame as the preview, or play the actual animation correctly in the chat. Either way, the yellow lines are a bug.

**Screenshots**
Some screenshot attached as links in the steps to reproduce. Aditionally check [this image of the gif panel without searching](https://user-images.githubusercontent.com/13616397/158985899-f8426151-d532-4973-9342-42006af678bf.png). 

**Version Info**
 - Unigram: 8.5 (6982) **ARM64**
 - Windows: Windows 11 Pro (21H2), OS build	22000.588

**Additional context**
It seems the bug does not always happen. I'd say it happens to 80%-90% of all new gifs, and around 60%-80% of all previously-posted (cached?) gifs. If the other person sends me a new gif, it happens 99% of the time.
Please note this is on an ARM64 Device.

**Comment by makisukurisu** [comment]
It may be a driver issue, or a GPU issue, but still need triage. Any Unigram ARM user out there?

Can you also tell which device or SoC do you have? It may be helpful.

**Comment by null-von-sushi** [comment]
I am on a Surface Pro X (with Microsoft's "Microsoft SQ1" processor.

**Comment by FrayxRulez** [comment]
Can you try to update 8.6? I guess that nothing will change but still...

**Comment by null-von-sushi** [comment]
I updated but as you suspected, it does not fix the issue 
![image](https://user-images.githubusercontent.com/13616397/161522917-711fd01a-3af3-46bd-a2f4-d9a4976dd0bf.png)

**Comment by thirtndev** [comment]
@null-von-sushi did you changed the default path of Unigram Downloads ?

**Comment by FrayxRulez** [comment]
I guess that this was fixed by updating to the latest ffmpeg
