### ISSUE TITLE
Cannot open urls with user and password

### ISSUE THREAD

**Issue by sukiletxe** [UnigramDev/Unigram#2687]
**Describe the bug**
When a url contains a user and password (in the format protocol://user:pass@hostname[:port][/path], Unigram will not open it.

**To Reproduce**
I don't have any url to test this that I can send, but if I click on a link with this format Unigra won't react.

**Expected behavior**
The url should open on the default browser.

**Version Info**
 - Unigram: Unigram 8.6 (7045) X64 Direct
 - Windows: Versión 21H2 (compilación de SO 19044.1586)

**Comment by FrayxRulez** [comment]
Links that contain user:pass are considered as a security threat by the system:
`System.Runtime.InteropServices.COMException: 'A security problem occurred. (Exception from HRESULT: 0x800C000E)'`

**Comment by FrayxRulez** [comment]
I think it makes sense to close this issue as it's not addressable by me.
