### ISSUE TITLE
Support Unicode 14.0

### ISSUE THREAD

**Issue by mahmoudhossam** [UnigramDev/Unigram#2688]
**Describe the bug**
Emojis that are part of Unicode 14.0 don't display correctly

**To Reproduce**
1. Send [one of these emojis](https://emojipedia.org/emoji-14.0/) from a device that supports them (e.g. iOS 15.4)
2. Try to view it on Unigram

**Expected behavior**
Emoji appears

**Screenshots**
Unigram:
![image](https://user-images.githubusercontent.com/619795/159163683-7e1508eb-7b9f-4548-a91f-de6936b75620.png)

iOS 15.4:
![IMG_1794](https://user-images.githubusercontent.com/619795/159163834-a415f14a-7fbf-4d2d-a6c3-0b4e11d24dc3.jpeg)

**Version Info**
 - Unigram 8.5 (6982) x64
 - Windows 11 21H2

**Comment by FrayxRulez** [comment]
This was done in https://github.com/UnigramDev/Unigram/commit/cef12fcca6e5cfc89746a26c95fd2fbafc431c78
