### ISSUE TITLE
Mark chat as read by context menu

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#269]
It would be nice to have a "mark as read" option in the context menu in the chat list.

**Comment by larsschellhas** [comment]
![wp_ss_20170513_0001_li](https://cloud.githubusercontent.com/assets/14281234/26098289/81212e58-3a27-11e7-96e7-ec890e698ae0.jpg)

**Comment by TobiVanHelsinki** [comment]
Also a "mark all as read" would be cool.

**Comment by larsschellhas** [comment]
@TobiVanHelsinki Telegram isn´t supposed to work that way... If you are marking chats as read, when not reading them, it would be better to just leave them.
At least that´s the policy of Telegram

**Comment by FrayxRulez** [comment]
Sorry but I’m going to close this for now :(

**Comment by FrayxRulez** [comment]
Done in vnext branch
