### ISSUE TITLE
Wrong time adjustment

### ISSUE THREAD

**Issue by ArnyminerZ** [UnigramDev/Unigram#2692]
**Describe the bug**
Here in Spain the time has just been advanced one hour. This is, tonight, at 2am the time was changed to 3am. This is not getting applied in Unigram. It's 17:04 right now, but the time displayed is 16:04.

My computer is showing the correct time, btw.

**To Reproduce**
1. The time was adjusted.
2. The time is not being displayed correctly.

**Expected behavior**
The summer time displacement should be applied.

**Version Info**
 - Unigram: 8.6 (7182) x64
 - Windows: Windows 11 Home 21H2 (22000.556)

**Comment by makisukurisu** [comment]
@ArnyminerZ Have you reopened the app since then? Can you sync clock and reopen the app just to make sure. Because I also had a time change today, but time is displayed correctly RN.

**Comment by ArnyminerZ** [comment]
I have synchronized the time, and rebooted the device, and the problem persists. However it must have something to do with my system. Clock is showing correctly on the taskbar, but on the settings app it's displayed incorrectly.

My "Change time automatically according to summer time" toggle is grayed out, so something is clearly wrong on my system.

Closing issue since it has nothing to do with Unigram. Thanks anyway.

**Comment by FrayxRulez** [comment]
@ArnyminerZ Did you try to turn it off and on

**Comment by ArnyminerZ** [comment]
> @ArnyminerZ Did you try to turn it off and on

Yep, tried rebooting, turning on and off... Nothing works. May have to contact MS for this one.

**Comment by FrayxRulez** [comment]
@ArnyminerZ Make sure your time zone settings are right in system options. Some times they “look” correct but they’re still not passed correctly to apps

**Comment by ArnyminerZ** [comment]
Nothing seems to work, opened an issue at Feedback Hub https://aka.ms/AAgg0k9
