### ISSUE TITLE
Buttons overlap in deatched chats

### ISSUE THREAD

**Issue by makisukurisu** [UnigramDev/Unigram#2693]
**Describe the bug**
If you open a chat in separate window (Using "Open in new window" option in context menu) you will have system's control elements (close, hide, max/mini-mize) overlapping with chat action buttons (search, profile picture ... menu, etc)

**To Reproduce**
1. Go to chat list
2. Open context menu and open a chat in a separate window
3. See error

**Expected behavior**
Control elements should not overlap

**Screenshots**
[There is a video](https://t.me/unigraminsiders/416530)
![image](https://user-images.githubusercontent.com/49622129/160334791-79efcb9f-cba5-4042-89fa-003c5e774fc6.png)

**Version Info**
 - Unigram: 8.6 7275 Direct
 - Windows: Not sure which @GodsPro has, if it's related - will ask

**Additional context**
I guess that's because a row was removed or smth
Oh, and thanks to @GodsPro for reporting this one

**Comment by null-nick** [comment]
@makisukurisu windows version is "Windows 11

**Comment by VladWinner** [comment]
![image](https://user-images.githubusercontent.com/13555921/168168638-263d7bee-4451-47d5-80a1-d5eb0926f503.png)
Unigram: 8.7 (7363) X64 Direct
Windows 11

**Comment by FrayxRulez** [comment]
Fixed
