### ISSUE TITLE
Not install latest beta of unigram on windows 11

### ISSUE THREAD

**Issue by AlexandrKozlovskiy** [UnigramDev/Unigram#2694]
When i try to install latest beta of unigram via update menue,i get an error:

Сбой установки Unigram—Telegram for Windows. Сбой установки приложения. Сообщение об ошибке: Произошел сбой операции развертывания Add с конечным томом C: для пакета TelegramFZ-LLC.Unigram_8.6.7275.0_neutral_~_1vfw5zm9jmzqy из  (8.6.7275.0.msixbundle) . Ошибка: 0x8000FFFF. Для получения справки по диагностике проблем с развертыванием приложений см. страницу http://go.microsoft.com/fwlink/?LinkId=235160. (0x8000ffff).

I read,what this error happened when we install apps from microsoft store,but i haven't microsoft store on windows 11,so i dont know,how to fix this issue.

**Comment by MarcAnt01** [comment]
This seems a catastrophic failure due to Windows, I am not sure about how we could help you to get Unigram installed through msix

**Comment by AlexandrKozlovskiy** [comment]
@MarcAnt01 But before all was ok. Why now we have this problems?

**Comment by FrayxRulez** [comment]
Something has changed on your side. You can still follow the instructions in the link that you attached here to get more details.

**Comment by FrayxRulez** [comment]
From the documentation that you linked:
![image](https://user-images.githubusercontent.com/8152849/160877404-c6bd19c7-1068-4aa9-bd60-aa7d8149fd79.png)

**Comment by chenshaoju** [comment]
This issue (error code 0x8000ffff ) may cause by a Windows permission problem, in my case, for solve this issue, try starting PowerShell (NOT cmd.exe) as administrator, And using `Add-AppPackage` to install Unigram,for example:
```
Add-AppPackage -path "D:\Unigram_8.9.7456.0_x64.msixbundle"
```

**Comment by FrayxRulez** [comment]
Thank you for the workaround @chenshaoju, closing this ticket.

**Comment by FrayxRulez** [comment]
@makisukurisu @MarcAnt01 would be maybe cool to mention this somewhere in the repository. I mean how to install using PowerShell.

**Comment by MarcAnt01** [comment]
> @makisukurisu @MarcAnt01 would be maybe cool to mention this somewhere in the repository. I mean how to install using PowerShell.

I don't think suggesting to install through Powershell is a good idea, since the users need to go to the process at every Unigram update. A guide to install AppInstaller seems to be a better idea to me. Your thoughts?

**Comment by AlexandrKozlovskiy** [comment]
O know. Again this error. Via pwsh it not installed too.

Microsoft Windows [Version 10.0.22000.613]
(c) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

C:\Users\ksash>pwsh
PowerShell 7.2.10
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

   A new PowerShell stable release is available: v7.3.3
   Upgrade now, or check out the release page at:
     https://aka.ms/PowerShell-Release?tag=v7.3.3

Warning: PowerShell detected that you might be using a screen reader and has disabled PSReadLine for compatibility purposes. If you want to re-enable it, run 'Import-Module PSReadLine'.

PS C:\Users\ksash> Add-AppPackage -path "C:\Users\ksash\AppData\Local\Packages\TelegramFZ-LLC.Unigram_1vfw5zm9jmzqy\LocalState\0\documents\Unigram_9.5.8144.0_x64.msixbundle"
Add-AppxPackage: Сбой развертывания с HRESULT: 0x80073CF9, Сбой установки. Обратитесь к поставщику программного обеспечения.
Произошел сбой операции развертывания Add с конечным томом C: для пакета TelegramFZ-LLC.Unigram_9.5.8144.0_neutral_~_1vfw5zm9jmzqy из  (Unigram_9.5.8144.0_x64.msixbundle) . Ошибка: 0x80004005. Для получения справки по диагностике проблем с развертыванием приложений см. страницу http://go.microsoft.com/fwlink/?LinkId=235160.
ПРИМЕЧАНИЕ. Чтобы получить дополнительные сведения, найдите [ActivityId] 62ea8d35-6b14-0005-2bb0-ea62146bd901 в журнале событий или введите в командной строке Get-AppxLog -ActivityID 62ea8d35-6b14-0005-2bb0-ea62146bd901.

PS C:\Users\ksash> Get-AppxLog -ActivityID 62ea8d35-6b14-0005-2bb0-ea62146bd901

Time                      ID           Message
----                      --           -------




































PS C:\Users\ksash>

May be it better to use .exe extension,if some users can have this problem?

**Comment by AlexandrKozlovskiy** [comment]
again this error. Probably i'll report it at bugs.telegram.org if i not find any solution.

**Comment by FrayxRulez** [comment]
@AlexandrKozlovskiy the error has likely nothing to do with Unigram but most likely to your system. In the ticket you as well posted at least three different error messages in your previous comments. None of them were directly related to Unigram.
