### ISSUE TITLE
Padding of Accounts button in left-sided tabs is not correct

### ISSUE THREAD

**Issue by prakharb5** [UnigramDev/Unigram#2696]
**Describe the bug**

**To Reproduce**
1. Enable tabs on left side
2. Click on profile icon in bottom left
3. Notice unequal padding on top of button

**Expected behavior**
The padding should be uniform

**Screenshots**
![image](https://user-images.githubusercontent.com/51435948/160760900-33e73e00-2426-4cdc-b55c-6ded246cd160.png)

**Version Info**
 - Unigram: 8.6 (7275)
 - Windows: 22581.200

**Additional context**

**Comment by FrayxRulez** [comment]
Done
