### ISSUE TITLE
Back button in top-left corner not working correctly for Settings pages

### ISSUE THREAD

**Issue by Cyberdroid1** [UnigramDev/Unigram#2698]
**Describe the bug**
When I have opened a settings category, pressing back should bring me back to the settings page, not chat list.

**To Reproduce**
1. resize window (reduce width) to just show the chat or chat list and enable tabs on left
2. click on settings, and click on a settings category (for example, chat settings)
3. click on back button on top left
4. notice that you are back to chat list, instead of settings page

**Expected behavior**
Pressing "back" should bring me back to settings category page, not chat list

**Screenshots**

https://user-images.githubusercontent.com/51435948/160762665-ba5d6b41-d233-48a7-9b1d-cdfc7c8d96b3.mp4

**Version Info**
 - Unigram: 8.6 (7275)
 - Windows: 22581.200

**Additional context**

**Comment by FrayxRulez** [comment]
Should be fixed in https://github.com/UnigramDev/Unigram/commit/505214e805358665e5153d6be36bb0e20b6ece51
Available in version 7285.
