### ISSUE TITLE
little UI glitch when replying

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#270]
When replying to someones message, this "slide to cancel" from voice Messages appears.
I´m not sure, wether it was previously reported in the Group, but it wasn´t here.

![wp_ss_20170515_0001_li](https://cloud.githubusercontent.com/assets/14281234/26098375/cbe211e6-3a27-11e7-913a-9f1526bfd66c.jpg)

**Comment by FrayxRulez** [comment]
Should be already fixed in development
