### ISSUE TITLE
animation for the last or single picture when scrolling with the mouse

### ISSUE THREAD

**Issue by f242** [UnigramDev/Unigram#2701]
Plz change the animation for the last or single picture when scrolling with the mouse. Now the picture scrolls from left to right and is displayed again. I suggest making a shake animation for this case.

**Comment by megapro17** [comment]
This is actually a bug, because it shouldn't show any animations

**Comment by FrayxRulez** [comment]
This was finally fixed in https://github.com/UnigramDev/Unigram/commit/3126a79bbc4323ade7638bc614fa88eae03d9020
