### ISSUE TITLE
The back button of the navigation bar does not work properly in some cases

### ISSUE THREAD

**Issue by MiaoLuoNa** [UnigramDev/Unigram#2704]
When you enter a "reply Interface",the "back" icon and it's real function seems to be not match
unigram 8.6(7333) 

https://user-images.githubusercontent.com/62191675/161544508-ac90a719-ce32-40a5-a7fe-c8fdf8be5c8d.mp4

**Comment by FrayxRulez** [comment]
That's not a back button, that's the chat profile picture

**Comment by CuteCatXiao** [comment]
It doesn't seem right I think.
Normally,click the icon which look like "reply" will not pop up a chat profile picture.

**Comment by FrayxRulez** [comment]
> It doesn't seem right I think. Normally,click the icon which look like "reply" will not pop up a chat profile picture.

Yeah the problem is that it opens up the chat profile picture, but it's not a back button either :D

**Comment by FrayxRulez** [comment]
Duplicate of #2718
