### ISSUE TITLE
Switching folders with the keyboard focuses the button which does nothing

### ISSUE THREAD

**Issue by sukiletxe** [UnigramDev/Unigram#2705]
**Describe the bug**
When you switch folders using the arrow keys, the focus goes to the button which does nothing instead of staying in the list.

**To Reproduce**
1. Enable Narrator.
2. Focus the list of folders with tab.
3. Switch to any other item using the arrow keys.
4. The focus will be moved to the "nothing to see here, tab further" button.

**Expected behavior**
The focus should stay in that same list. The selected item does change, as expected.

**Screenshots**

**Version Info**
 - Unigram: Unigram 8.6 (7342) X64 Direct
 - Windows: Versión 21H2 (compilación de SO 19044.1586)

**Additional context**
I believe the previous beta version worked correctly, either that one or the penultimate one.

**Comment by makisukurisu** [comment]
Using shortcuts for switching folders solves this problem

Shortcut it - Ctrl+Number of a folder (starting from 1 and up to 8, number 9 opens archived chats and Ctrl+Zero opens saved messages)

Not sure if it's possible/it's going to be fixed

**Comment by sukiletxe** [comment]
And this got fixed! (Now I have to untrain muscle memory, but that's my problem 🤣 )
