### ISSUE TITLE
Animation bug of inline result button

### ISSUE THREAD

**Issue by AnotiaWang** [UnigramDev/Unigram#2706]
**Describe the bug**
The top button in inline query result (which is called `switch_pm_text` in Bot API) sends a deep-linking parameter to bots when pressed. When searching in the chat with bot, the animation looks weird.

**To Reproduce**
Say, testing with `@oiTubeBot`
1. Go to `@oiTubeBot`
2. Type `@oiTubeBot` in the input area and a space
3. Click the top button of the results the bot shows

**Expected behavior**
The behavior, when searching in a different chat from the bot, is to close the inline result list, go to bot chat and send `/start` with deep-link params. Hence, I think the behavior when searching in the bot chat should be consistent with the former.

**Screenshots**
- Example of `switch_pm_text` button
![image](https://user-images.githubusercontent.com/62269186/162361027-465b6968-2870-4225-ae35-ee443fb333ce.png)

- Screen recording
![bandicam 2022-04-08 11-38-49-970](https://user-images.githubusercontent.com/62269186/162361072-330fdb27-d47e-4048-8f0d-90a7105c6f49.gif)

**Version Info**
 - Unigram: 8.6.7342 x64
 - Windows: Build 22000.593

**Comment by makisukurisu** [comment]
![image](https://user-images.githubusercontent.com/49622129/187273798-912e117e-47c2-4db2-a2e8-5d484b1f9d8b.png)

Also this button now has text with color of background, unless you hover on a button
