### ISSUE TITLE
Compact mode title bar overlapping (with vertical folders on) 

### ISSUE THREAD

**Issue by makisukurisu** [UnigramDev/Unigram#2707]
**Describe the bug**
If you enable vertical folders and shrink Unigram to a compact mode, when you open any chat Unigram's name and will be cut off.

**To Reproduce**
1. Enable vertical folders
2. Open a chat
3. Shrink it till only chat is visible (aka "compact mode")

**Expected behavior**
Hide Unigram icon and extend the button so it's touching borders of chat acrylic or make it so Acrylic is shorter in compact mode (so it ends where info ends (both ideas will be illustrated bellow)

**Screenshots**
![image](https://user-images.githubusercontent.com/49622129/162573917-73a146ac-f6e0-4597-afef-e98a08721769.png)
How the bug looks

![image](https://user-images.githubusercontent.com/49622129/162574216-0d271fbe-0246-4d26-bdd1-a954a1ad3525.png)
Idea no. 1

![image](https://user-images.githubusercontent.com/49622129/162574580-e507e273-7068-41e4-9e36-9bacd6d78ad4.png)
Idea no. 2

**Version Info**
 - Unigram: 8.6 7342
 - Windows: 11 21H2

**Comment by FrayxRulez** [comment]
Fixed
