### ISSUE TITLE
Trying adding user that left a group doesn't show error message

### ISSUE THREAD

**Issue by megapro17** [UnigramDev/Unigram#2710]
**Describe the bug**
If user has left a group, and you're trying to add him back, nothing happens and error doesn't show

**To Reproduce**
1. User should join any group
2. Then he needs to leave.
3. Another user should try to add him back.
4. Nothing happens and user is not added.

**Expected behavior**
It should display an error like this:
> Sorry, if a person is no longer part of a group, you need to be in their Telegram contacts to add them back.

https://translations.telegram.org/en/android/groups_and_channels/GroupUserLeftError

**Screenshots**
![image](https://user-images.githubusercontent.com/16743370/162641765-f52fd87c-ad7b-4b91-b767-f3a1883aa618.png)

**Version Info**
 - Unigram: 8.6
 - Windows: 11 22H2

**Comment by MarcAnt01** [comment]
Hi, thanks for reporting, but this is already part of https://github.com/UnigramDev/Unigram/issues/649
