### ISSUE TITLE
Changing text size doesn't affect quote text size

### ISSUE THREAD

**Issue by megapro17** [UnigramDev/Unigram#2711]
**Describe the bug**
Quoted text is too small, and size doesn't change

**To Reproduce**
1. Go to settings - chat settings and increase text size
2. Open any chat
3. Answer to someone message and you will see that qouted message is too small, and doesn't scale like the other text

**Expected behavior**
Quoted text must scale like the main text

**Screenshots**
![image](https://user-images.githubusercontent.com/16743370/162642027-5a34e333-fdba-4a48-af26-255ea89002fb.png)

**Version Info**
 - Unigram: 8.6
 - Windows: 11 22H2

**Comment by FrayxRulez** [comment]
This is actually by design

**Comment by megapro17** [comment]
That's bad design, you can't see quotes if you monitor is big and you increase text size

**Comment by FrayxRulez** [comment]
@megapro17 Maybe you could consider increasing the font in system settings? Unigram uses standard metrics for text.

**Comment by megapro17** [comment]
No, text in any other program is fine

вс, 4 сент. 2022 г., 14:56 Fela Ameghino ***@***.***>:

**Comment by ti-bone** [comment]
@megapro17 Send us a screenshot of the trouble.

**Comment by megapro17** [comment]
@ti-bone 

<details>
<summary>Details</summary>

![image](https://github.com/UnigramDev/Unigram/assets/16743370/cc2fbb06-8713-4e85-a022-5859611c5c97)


</details>

In telegram desktop quote and it's box size is the perfect size, you can read it easily. On unigram it is too small
But if you make text a little bit bigger it's getting absolutely terrible, you can't see anything at all!

<details>
<summary>Details</summary>

![image](https://github.com/UnigramDev/Unigram/assets/16743370/1de1b55d-b2c6-4b06-8e51-1d6e91002399)


</details>

You can make text bigger and it's even worse, quote doesn't change font size and it's impossible to see what's in it. On a web version it's perfect, not only text is bigger, but the quote itself, and it's proportional to entire text box

Changing a dpi is not a solution, the quote size becomes fine, but everything else becomes too big. the ratio of quote size to everything else is too small, and this is exacerbated by the fact that the text in the quote remains minuscule

> This is actually by design

How it can by design if it doesn't replicate in any other telegram client? It doesn't look right, it's strains the eye. It caught my eye before, on a 21.5 monitor, and it catches my eye on a 32 now

It's not only quoted text size, it's also last seen, reposted message author, link description, time, so many elements that are hard to see.

**Comment by megapro17** [comment]
It still a problem and looks afwul
