### ISSUE TITLE
Update version on Github

### ISSUE THREAD

**Issue by iMonZ** [UnigramDev/Unigram#2712]
Hey,
on the release page of this github repo the latest version is a bit outdated.
Could you please update it so we can see which version is the latest one and see the changelog?
Thanks!

**Comment by MarcAnt01** [comment]
We don't provide msix files for releases any longer, if you want to install the version out of the store, the best option available is to use the beta. You can find it here https://t.me/unigramappx

**Comment by iMonZ** [comment]
> don't provide msix files for releas

You dont have to. Could you just provide the release log?

**Comment by FrayxRulez** [comment]
@iMonZ Yes, I will
