### ISSUE TITLE
Failed posting of comments in chat from personal account

### ISSUE THREAD

**Issue by TurboPlanner** [UnigramDev/Unigram#2719]
**Describe the bug**
Unigram failed to post comment in chat from personal account but allow from chat or channel account

**To Reproduce**
1. Create chat
2. Create channel
3. Assign chat to channel
4. Switch to personal account in chat 
5. Try to post - FAILED
6. You can call retry and message will posted

**Expected behavior**
Personal account should works in chat comments 

**Screenshots**
![failed](https://user-images.githubusercontent.com/92896692/165091710-81b83ff1-6155-4174-b400-fefa30da574c.jpg)

**Version Info**
Version of Unigram - 8.7 (7352) I have auto update to new version

OS
Edition Windows 10 Enterprise
Version 21H1
OS build 19043.1586
Experience Windows Feature Experience Pack 120.2212.4170.0
Updated to last cumulative fixes

**Comment by FrayxRulez** [comment]
Most likely a backend issue. Would be great if you could reproduce the issue with logs turned on ([instructions here](https://github.com/UnigramDev/Unigram/blob/develop/Documentation/TDLib-logs.md)). You can then send the logs file (logs have to be disabled to be able to send them through the app) to tdlib_bot on Telegram.

**Comment by TurboPlanner** [comment]
I cannot send td_lib log (see another bug about outdated version in Unigram)

Also I cannot see log file in described folder
C:\Users\Admin\AppData\Local\Packages\38833FF26BA1D.UnigramPreview_g9c9v27vpyspw\LocalState

However before debug mode I can open small Td_lib log by sending to another account

IMHO, documented directory of log is incorrect

**Comment by makisukurisu** [comment]
Can someone confirm if the problem was fixed or not?

It looks like it is to me. (8.9 7605 x64)
Please, reopen the issue if the problem is still there
