### ISSUE TITLE
Crash on launch on build 16193 in first run

### ISSUE THREAD

**Issue by ben-zen** [UnigramDev/Unigram#272]
I'm seeing a crash in the following stack on launch on Desktop:

Windows_UI_Xaml!CImageSource::DecodeToRenderSize+0x133 
Windows_UI_Xaml!CImageSource::RequestDecode+0x65
Windows_UI_Xaml!CCoreServices::FlushImageDecodeRequests+0xce
Windows_UI_Xaml!CCoreServices::NWDrawTree+0x737 
Windows_UI_Xaml!CCoreServices::NWDrawMainTree+0xe3
Windows_UI_Xaml!CWindowRenderTarget::Draw+0x73
Windows_UI_Xaml!CXcpBrowserHost::OnTick+0x112
Windows_UI_Xaml!CXcpDispatcher::Tick+0x8c Windows_UI_Xaml!CXcpDispatcher::OnReentrancyProtectedWindowMessage+0x54 
Windows_UI_Xaml!CXcpDispatcher::ProcessMessage+0x64 
Windows_UI_Xaml!CXcpDispatcher::WindowProc+0xc6 
user32!UserCallWinProcCheckWow+0x293

This is a 100% reproducible crash, on several devices. It's not clear what has changed that could cause this.

**Comment by vitorgrs** [comment]
@ben-zen Is RS3 fault.

**Comment by FrayxRulez** [comment]
As @vitorgrs says the exception is RS3 fault, and it is caused by this line of code:
https://github.com/UnigramDev/Unigram/blob/development/Unigram/Unigram/Views/SignIn/SignInWelcomePage.xaml#L120

Unigram seems to not be the only affected app at the moment.

**Comment by FrayxRulez** [comment]
Does the app works on 16199?

**Comment by rabiet** [comment]
The App does work again on 16199!

**Comment by FrayxRulez** [comment]
Great!

**Comment by FrayxRulez** [comment]
Seems that this has not yet been fixed in 16199

**Comment by hezmekiah** [comment]
If I press "welcome" immediately, I can access the app. Just waiting at the welcome screen leads to the crash. This is before having signed in

**Comment by omfgnuts** [comment]
Tried pressing welcome immediately before. Didn't work. Crashes anyway

**Comment by FrayxRulez** [comment]
Patched in https://github.com/UnigramDev/Unigram/commit/df5f9d1a8bf8da2730ecc091a92c9d5ccaabe936
