### ISSUE TITLE
Failed to send td_lib log 11 mb to bot or another account. TdLib reported about outdated version

### ISSUE THREAD

**Issue by TurboPlanner** [UnigramDev/Unigram#2720]
**Describe the bug**
td_lib reported that Unigram is using outdated version of td_lib
"This message is not supported by your version of Telegram. Update the app to view: https://telegram.org/update" 

**To Reproduce**
1. Enable verbose logging
2. Collect log with size 11 mb or more
3. Try to send the log file to @tdlib_bot or another account
4. td_lib reported that Unigram don't have new tdlib library for posting this attachment

**Expected behavior**
Post 11 mb text file to bot or another account

**Screenshots**
![tdlib](https://user-images.githubusercontent.com/92896692/165101959-34c22c8d-636a-46f2-a50d-e296ae0bb687.jpg)

**Version Info**
Version of Unigram - 8.7 (7352) I have auto update to new version

OS
Edition Windows 10 Enterprise
Version 21H1
OS build 19043.1586
Experience Windows Feature Experience Pack 120.2212.4170.0
Updated to last cumulative fixes

**Additional context**
Small logs below 1 mb posted successfully

**Comment by FrayxRulez** [comment]
@TurboPlanner […] [logs have to be disabled to be able to send them through the app](https://github.com/UnigramDev/Unigram/issues/2719#issuecomment-1108534320) […]

**Comment by FrayxRulez** [comment]
As I mentioned in the other ticket, I mentioned here again, and I mentioned in the TDLib logs documentation you must disable the logs to be able to send them:
```
To send logs through the app you must disable them first: Navigate to the Diagnostics settings, select Verbosity level and set it to Assert. You can now click on the item below (marked as tdlib_log.txt): a dialog will open and you will be able to pick a chat where to send the file.
```
