### ISSUE TITLE
Unigram don't support "I don't want to read" feature for Archive chats as standard Telegram application

### ISSUE THREAD

**Issue by TurboPlanner** [UnigramDev/Unigram#2722]
Unigram don't support "I don't want to read" feature for Archive chats as standard Telegram application.

Unigram display notification for new messages for archive chats always. However standard Telegram app has advanced logic in notification.  If a user move a chat to an archive, then he is not very interested in it and does not want the chat to distract his attention.  Standard Telegram application has additional "low interest" flag for archive chats. 

First, the standard application  displays a notification about chats in the archive as Unigram do. If the user opens the chat list, but does not open the message lists in some chats, then the chats where the user has not looked at the message lists receive the "low interest" flag and are no longer displayed in notifications.

This is an important feature, since users usually have a lot of chats in the archive, the Unigram archive notification is actually useless, because one or another chat displays a notification. Therefore, the user is forced to constantly open the list of chats, even if there is spam. At the same time, the user wants to view some chats with some interest in new messages.

PS. It's not TDLib feature. This is client app feature. I tested it. If you reinstall standard Telegram app then archive chats show notifications again before this chat assign "low interest" flag again. This flags stored locally. 

PSS. I tested again standard app. I see that standard App has more complex logic than simple "low interest" flag. The app remember previous actions with chats and show notification depend on activity with archive chats. Chats with low active usage don't create general notification. However how the App decide that this chat as "low active" is complex. Based on user actions.  

![arch](https://user-images.githubusercontent.com/92896692/165497538-f99c5d63-c2cf-440e-8d07-11e631775cfc.png)

![Arch1](https://user-images.githubusercontent.com/92896692/165498563-07d6e5f7-aff8-416a-852a-94c24988dd3d.png)

**Comment by pratyakshm** [comment]
@TurboPlanner

**Comment by MarcAnt01** [comment]
I don't understand if the whole ticket is about notifications, also I have no clue about what you mean by "low interest flag"

**Comment by TurboPlanner** [comment]
It's about unread counter. 

About low interest flag (LIF). See how standard App calculate "unread counter".
Example in abstract programming language
....
If Chat (N).user.someaction then Chat(N).LIF=1
...
while N<MaxN
UnreadCounter = UnreadCounter+ Chat(N).UnreadCounter*Chat(N).LIF
 N=N+1
...

**Comment by FrayxRulez** [comment]
There's no such thing as `interest flag (LIF)` on Telegram.
