### ISSUE TITLE
Number of views of forwarded channel post renders over message text

### ISSUE THREAD

**Issue by Jeidoz** [UnigramDev/Unigram#2724]
**Describe the bug**
Render comparison (Unigram left, Telegram official client right)
![image](https://user-images.githubusercontent.com/23425714/165550221-7dc0feb9-abf0-4007-90c7-96be52a5cbe3.png)

**To Reproduce**
1. Find any text only channel post
2. Forward/Share it into group
3. End of messages is unreadable.

**Version Info**

Unigram: 8.6.7182 x64
Windows: 10 Pro 21H2

**Comment by FrayxRulez** [comment]
Can't reproduce. Forwarding a message is not enough.

**Comment by makisukurisu** [comment]
![image](https://user-images.githubusercontent.com/49622129/183306019-f2dd4ed0-1764-435b-84d5-74dbbeda1164.png)
It doesn't matter if the message was forwarded or not, as I can see. I'd assume it has something to do with formatting (notice how third from the top message is formatted as Normal and is rendered correctly).

Sample message:
https://t.me/ru2ch_news/51550

Screen settings:
1920x1080 Landscape, 125% scaling in Windows
![image](https://user-images.githubusercontent.com/49622129/183306138-88629565-2a59-45e0-86fd-3369fb889f81.png)
Those settings in Unigram
Unigram is opened in full screen, chat list width doesn't affect this.

**Comment by makisukurisu** [comment]
Now that DirectX accounts for formatting entities this problem should cease to exist :)

At least it's not happening with post I've provided

If the problem persists, please - reopen the issue
