### ISSUE TITLE
unigram doesn't connect when VPN on

### ISSUE THREAD

**Issue by yirgster** [UnigramDev/Unigram#2726]
**Describe the bug**
When using unigram with vpn is doesn't connect, showing "Connecting ..." forever.

**To Reproduce**
A.
1. start VPN client and sign in
2. start unigram
3. Error: see "Connecting ..." forever (see attached screenshot)

Or:

B,
1, start unigram 
2. unigram now runs OK
3. start vpn client and sign in
4. click on a name in the contact in the unigram left panel
5. Error: see "Connecting ..." forever (see attached screenshot)

**Expected behavior**
unigram should work with or without VPN

**Screenshots**
See attached screenshot

**Version Info**
 - Unigram: 8.6 (7182) X64
 - Windows: Edition	Windows 10 Pro
        Version	21H2
        Installed on	‎6/‎5/‎2020
       OS build	19044.1645
       Experience	Windows Feature Experience Pack 120.2212.4170.0
- Cisco AnyConnect Secure Mobility Client, Version 4.10.02086

![unigram problem](https://user-images.githubusercontent.com/46745006/166851712-4263e7a0-af3d-43f5-b237-bd020fc4e56d.JPG)

**Comment by makisukurisu** [comment]
@yirgster Perhaps you need to enable loopback.

Taken from here: https://t.me/unigraminsiders/352180

Execute it in PowerShell

Get-AppxPackage | %{$_.PackageFamilyName} | where{$_ -match "unigram"} | %{CheckNetIsolation LoopbackExempt -a -n="$_"}

**Comment by yirgster** [comment]
Pls forgive my ignorance but why would installing (it's not there now) a loopback network device  and configuring it on my PC deal with this issue? How is absence of a loopback device interfering with unigram working on VPN?

**Comment by makisukurisu** [comment]
I guess that most VPNs use loopback. Also it's not the absence of device, but the fact that UWP apps don't have access to them by default.

Can you tell if this problem was solved? If it was not - maybe we can help you, reopen the issue.
