### ISSUE TITLE
Pressing ctrl+a no longer selects all loaded messages in Unigram beta

### ISSUE THREAD

**Issue by Simon818** [UnigramDev/Unigram#2728]
Unigram 8.7 (7363) X64 Direct

**Describe the bug**
In previous Unigram versions, ctrl+a would select all the currently-loaded messages in a conversation when selection mode was enabled. This no longer works.
**To Reproduce**
1. Open any conversation with two or more messages in it.
2. Right-click and choose "select..."
3. If keyboard focus is not already in the message list, tab or shift+tab as needed.
4. Press ctrl+a
**Expected behavior**
Unigram should select all the messages that are currently loaded. This worked in previous Unigram versions, but in the current beta, nothing happens.

**Comment by MarcAnt01** [comment]
Hi @Simon818 we're sorry, but  what the app used to was select all the loaded messages, not every message in the chat, this was a bad ux and it was present only because it was a system component, for this reason this is not going to be implemented

**Comment by Simon818** [comment]
Understood, but being able to load all messages and then select all was still useful, both for copying and for deleting. Is it still possible to do this?
