### ISSUE TITLE
After switching back from rich emoji select menu, the main context menu becomes non-clickable

### ISSUE THREAD

**Issue by Kenya-West** [UnigramDev/Unigram#2729]
**Describe the bug**
Found a bug - after switching back from rich emoji select menu, the main context menu becomes non-clickable.

**To Reproduce**
1. Open any chat with reactions enabled
2. Right click a message to react with
3. Expand reaction picker
4. Collapse it
5. You cannot interact with context menu, it hides at any click. Hovering context menu elements neither works

**Expected behavior**
You can interact with context menu after collapsing rich reaction picker.

**Screenshots**

https://user-images.githubusercontent.com/12271104/167110764-6e0ef7af-ed1d-44b1-a218-6ced38ab7777.mp4

**Version Info**
 - Unigram: 8.6 (7182) x64
 - Windows 11 latest stable

**Comment by makisukurisu** [comment]
And well, in 8.9 7605 this happens:
https://user-images.githubusercontent.com/49622129/187270531-cb3414d5-e1f7-4cf0-b5c2-5508f7f77010.mp4
