### ISSUE TITLE
Taking a screenshot clears recent pictures block

### ISSUE THREAD

**Issue by andremacareno** [UnigramDev/Unigram#273]
Didn't see a similar issue, so I've decided to open this one.
Steps to reproduce:
1. Tap at the attach icon
2. Take a screen shot

Expected behaviour: new screen shot adds to right of camera icon.
What it does: all recent pictures gone.
These two pictures show a state before and after taking a screenshots respecitvely.
![2017-05-17 07 08 34](https://cloud.githubusercontent.com/assets/5407142/26164235/bb415974-3b34-11e7-8a02-d3751c9a1267.jpg)
![2017-05-17 07 08 25](https://cloud.githubusercontent.com/assets/5407142/26164239/beb53418-3b34-11e7-896b-042d8dbf5a57.jpg)

**Comment by FrayxRulez** [comment]
Since there's no way when the event is raised to know if files were added or removed the right behavior is to repeat the files query.
