### ISSUE TITLE
Code formatting resets after you attach a media

### ISSUE THREAD

**Issue by Kenya-West** [UnigramDev/Unigram#2730]
**Describe the bug**
If you have a message with some _cursive_, **bold** or `code` formatting and then you attach a media (doesn't matter what way), all the formatting is reset.

**To Reproduce**
1. Open some chat where you can type a message
2. Type a message
3. Format some parts of it with hotkeys, context menu or by marks \*\*bold\*\*, \_\_cursive\_\_, or \`code\`
4. Attach a media (picture, video/gif, music, file, you choose it)
5. After the media has attached, formatting is gone

**Expected behavior**
After the media has attached, formatting should stay.

**Screenshots**
https://user-images.githubusercontent.com/12271104/167111999-fe5ef696-085a-408f-ad49-0b53ebeac39f.mp4

**Version Info**
- Unigram: 8.6 (7182) x64
- Windows 11 latest stable

**Comment by FrayxRulez** [comment]
This only happens with monospace text.
