### ISSUE TITLE
Hide "All chats" folders option

### ISSUE THREAD

**Issue by InsertCoinPls** [UnigramDev/Unigram#2732]
Hi everyone!

In my opinion, it would be very nice to have an option to hide the "all chats" folder, would make the UX cleaner. Is very annoying that when I open telegram, the folder that comes by defect is "all chats". There is no point in having all my chats sorted if when I start telegram they are all mixed up. At least, it could be added an option to make other folder the default folder.

Thank you team!!!

**Comment by amirmahdifard0** [comment]
@InsertCoinPls hello, but this option was needed, because if you having some folders, you need all chats, so it can use your all chats, not only one folder.

**Comment by amirmahdifard** [comment]
@amirmahdifard0 i am sorry, but i am testing my github account, really sorry for this comment

**Comment by InsertCoinPls** [comment]
@amirmahdifard0 I understand your point but, for example I have all my chats sorted in multiple folders, so "all chats" just mess the sort. I understand that not everyone would like to hide this folder, thats what I said to have the option, so people like me that doesnt need the "all chats" folder could remove it, and people that use it could have it. There is some telegram apps that have this option like nekogram in android and katogram in desktop.

**Comment by amirmahdifard** [comment]
@InsertCoinPls i understand, but as unigram only working like the main telegram, and only adding an ibility to unigram if telegram have added them,, so, telegram  didn't added this ability yet, i think this option should bee here, and also, this option isn't bothering peopl so they needed to turn off, i think, if we havving some folders, the all chats option is very best option when its neare other folders

**Comment by FrayxRulez** [comment]
There are no plans to hide "All chats" folder. With Telegram Premium it is now possible to use a different folder as the default folder, and this is the recommended way to do this.
