### ISSUE TITLE
accessibility

### ISSUE THREAD

**Issue by amirmahdifard** [UnigramDev/Unigram#2733]
in open navigation menu, the (show / hide accounts button) isn't accessible for screen readers. note: this option is accessible in old vershens, but because you changed the desine of this section, this option isn't accessible in this menu anymore. please make this button accessible for screen readers as new desine, because this bug is causing a problem for people who need this button to add another account to they accounts list.

**Comment by MarcAnt01** [comment]
Please add a title, add repro steps, Unigram version, Windows version, otherwise this will be closed
