### ISSUE TITLE
accessibility

### ISSUE THREAD

**Issue by amirmahdifard** [UnigramDev/Unigram#2734]
when we trying to switch between folders list, it jumps to the (Nothing to see here, tab further  button). note: we can hold the control button and then switch between folders list by using the arrow keys, but when we doing that, the folder isn't selected, so we have to press the enter key evry time when we switch between folders.

**Comment by MarcAnt01** [comment]
Please add a title, add repro steps, Unigram version, Windows version, otherwise this will be closed

**Comment by amirmahdifard** [comment]
@MarcAnt01 I canot edit this post again, because i'm not an admin, I think you can understand this one, if my post having a problem edit them yourself, and don't take your angry and personality problems to my GitHub tikits, thanks.

**Comment by makisukurisu** [comment]
You can edit the issue on a github page. Anyways, you can add all the required information in your next comment.

Plus, you can use Ctrl+Number to select a floder, as was mentioned in shortcuts document and sometime in a group.

In short:
Ctrl+1 - All chats
Ctrl+2 and to Ctrl+8 - second, third, etc. floder
Ctrl+9 - Archive
Ctrl+0 - Saved messages chat

**Comment by amirmahdifard** [comment]
@makisukurisu bro, I told you I did that, but I can't edit them.

**Comment by amirmahdifard** [comment]
@amirmahdifard i asked admin if he can do that or not

**Comment by MarcAnt01** [comment]
If you cannot edit this, I'm closing the issue. Feel free to create a new ticket, but please follow the template this time
