### ISSUE TITLE
Select with two fingers with touch UX

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2735]
Recently the Telegram mobile apps introduced the possibility of quickly selecting messages/chats with touch, by swiping with two fingers. It'd be handy to have the same selection UX on Unigram

**Comment by FrayxRulez** [comment]
I don't think this is technically feasible because of `ScrollViewer` already handling the event and all the consequences of this.
Also this isn't a common UX on Windows so it won't be used by the vast majority of users
