### ISSUE TITLE
Download sub-folder for groups and channels

### ISSUE THREAD

**Issue by amuagarwal** [UnigramDev/Unigram#2741]
Its really good to have media sub-folder for groups and channels as there are many channels which have lot of media which i need to keep them separate.

The macro for group/channels to save media in separate fodder. e.g video\group1 and so on

**Comment by MarcAnt01** [comment]
Thanks for your feature requests, but Unigram aims at offering a similar experience to official apps, so this feature isn't going to be considered unless Telegram implements it in one of its major updates
