### ISSUE TITLE
batch download possible? 

### ISSUE THREAD

**Issue by deroverda** [UnigramDev/Unigram#2742]
Hi, 

Is it possible to batch download all the videos posted in a certain group? If not, does anyone know of any other tool that can do this?

**Comment by ggoraa** [comment]
@deroverda the closest it can get to downloading everything together and simultaneously is data export feature of tdesktop

**Comment by FrayxRulez** [comment]
@ggoraa suggestion is a good workaround. Another option is to enable automatic downloads for any file size and just scroll through the channel.
