### ISSUE TITLE
I found the answer thanks

### ISSUE THREAD

**Issue by tgcallsproject** [UnigramDev/Unigram#2743]
I found the answer thanks

**Comment by makisukurisu** [comment]
@tgtglove You might want to take a look at next repositories:
https://github.com/TelegramMessenger/tgcalls (I guess here are the files you are looking for)

Perhaps even:
https://github.com/MarshalX/tgcalls (this is a realization sorta speak)

Unigram has some dependencies, including calls, so, you also may want to look at documentation folder for Unigram project, where you will find instructions to get all the components for Unigram.

Hope this helps you with your question!
P.S. This is not an issue, so, if you don't mind, I'll close it. If you want to have a bit of tech talk - you may want to join us at https://t.me/unigraminsiders (though other apps are not a topic of the group, maybe you can find some help there)

**Comment by tgtglove** [comment]
seems it`s here

https://github.com/UnigramDev/Unigram/blob/develop/Unigram/Unigram/Services/CallsService.cs

and it used names like **CallStateDiscarded**
insttread of **td::CallStateDiscarded** 

like 
https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1call_state_discarded.html
