### ISSUE TITLE
Adding a "Recent actions" for chat administrators

### ISSUE THREAD

**Issue by adivvkvns** [UnigramDev/Unigram#2745]
Hello. Could you add a feature "Recent actions" to Unigram for chat admins? I guess that alternative Telegram messenger was released a long time ago.
But in the fact that thing is very cool, pleases the design of Windows 11 and smoothness.
Like as the administrator of one of the telegram chats, i really would need this function to be. Is it feasible to implement? Thank you.

**Comment by Aquathing** [comment]
It's already implemented. You can find it in Edit > Administrators > Recent Actions.

**Comment by adivvkvns** [comment]
> It's already implemented. You can find it in Edit > Administrators > Recent Actions.

Thank you didn't see it omg😁😁😁😁😁
