### ISSUE TITLE
Cannot enable "talk anonimously" permission for myself from Unigram

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2748]
**Describe the bug**
Even if I set it properly, it doesn't apply, without showing any message

**To Reproduce**
1. Go to a group to which you're the owner;
2. Enable talk anonymously permission
3. Confirm
4. Click done to save group settings edit

**Version Info**
 - Unigram: 8.7.7363
 - Windows: 11 22H2

**Comment by FrayxRulez** [comment]
I'm not really able to reproduce this issue...

**Comment by FrayxRulez** [comment]
Considering that I was not able to reproduce this and there was no updates on this ticket over the last year I'll just close it
