### ISSUE TITLE
Unigram often crashes when closing a long individual videocalls

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2749]
**Describe the bug**
After a quite long individual videocall (10 minutes) in 70% of the cases, clicking on the close button leads to a crash of the app

**To Reproduce**
Cannot give repro steps, unfortunately :/

**Version Info**
 - Unigram: 8.7.7363
 - Windows: 11 22H2

**Comment by FrayxRulez** [comment]
I think this is fixed, if not, please ping pong me
