### ISSUE TITLE
Improve resource usage during group videocalls

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2750]
As soon as I start a group videocall even if with no participant in and no camera on the gpu usage goes up to 60/70 per cent in a second and even task manager has a hard time computing it, if there are cameras on screen/sharing etc. it can go up to 90/95 per cent making Unigram unusable, with the chat textbox taking like 10 seconds to process the input and my camera preview being like 5fps.
Individual videocalls don't seem to have this issues

**Comment by FrayxRulez** [comment]
Done
