### ISSUE TITLE
Not possible to forward/delete multiple messages from inside the chat

### ISSUE THREAD

**Issue by tissole** [UnigramDev/Unigram#2755]
**Describe the bug**
Users cannot forward/delete multiple messages from inside the chat, because only one message can be selected.

**To Reproduce**
Click the top bar, a window appears with tabs for media, files, music. Click on the file tab and then search for a certain word or tag, the result is shown in a window. It is not possible to select multiple msgs from that window for delete/forward msgs.

It actually shows the box checked, but the msgs are not actually selected, when you right-click it says select, the menu to delete/forward does not appear. When you select the msg, only that msg is selected, it is not possible to select multiple msgs.

**Expected behavior**
Should be able to select multiple messages.

**Version Info**
 - Unigram 8.7.7363 x64 Direct
 - Windows 10 Enterprise LTSC 21H2

**Comment by Elshara** [comment]
This is still an issue for me. I rely on this function for a few reasons.

**Comment by makisukurisu** [comment]
This was fixed in future versions

**Comment by makisukurisu** [comment]
Reopening because of #2857, can someone check this one?

**Comment by tissole** [comment]
Hello! This issue is not fixed, unfortunately.

**Comment by makisukurisu** [comment]
I'd suggest renaming this issue to something like "Can't forward multiple messages from Chat Info view)
