### ISSUE TITLE
Upload m4b files as audio files (streamable files)

### ISSUE THREAD

**Issue by tissole** [UnigramDev/Unigram#2757]
Currently, these type of files are only uploaded as files (non-streamable), but in some chats I see that these files are sometime streamable. I would like to be able to upload them as audio files.

**Comment by makisukurisu** [comment]
@FrayxRulez , correct me, if I'm wrong, please.

As far as I know - Unigram is using "file-type determiner" from system. And this means that system decides weather or not file should be sent as media or as file.
And as I can see - Windows doesn't know what m4b format is.

**Comment by FrayxRulez** [comment]
Also, can even Windows, macOS, iOS and Android play m4b natively?
