### ISSUE TITLE
Add the ability for screen readers to speak the names of the available reactions in the message when the user scrolls through the list using the Tab key.

### ISSUE THREAD

**Issue by DraganRatkovich** [UnigramDev/Unigram#2758]
**Describe the bug**

Currently, when there is a reaction left on a message, on pressing the Tab key, the screen reader only says "Toggle button pressed" if there is only one reaction and numbers when there are several reactions in a channel or group message.

**To Reproduce**

1. Turn on NVDA (This issue also affects the built-in Windows screen reader);
2. React to someone's message or let them react to a message;
3. Press the Tab key to move through the list of messages, you will notice that the screen reader says "toggle button pressed" instead of the name of the reaction.

**Expected behavior**

Screen readers should say the name of the reaction, not the button and numbers.

**Version Info**

 - Unigram: This issue affects both Unigram 8.6, which is available from the Microsoft Store, and Unigram_8.7.7386.0, which is available from the Unigram Mirror channel. Both versions are X64-bit
 - Windows: Windows 10 21H2

**Additional context**
@FrayxRulez @beqabeqa473 Please consider this issue, it is really important in terms of accessibility.

**Comment by svfleytin** [comment]
I vote for this. It is really a serious problem for any blind UniGram user.

**Comment by FrayxRulez** [comment]
@DraganRatkovich I’ve added this in commit https://github.com/UnigramDev/Unigram/commit/02d04bf090caccb9083e33f4f59e4ec1b24dcef8

**Comment by DraganRatkovich** [comment]
@FrayxRulez That's good, will you include this commit in the next version of Unigram publicly, and when do you plan to publish all these changes in the MSStore version?

**Comment by FrayxRulez** [comment]
@DraganRatkovich I will publish the update to the Microsoft store in a week or so

**Comment by DraganRatkovich** [comment]
@FrayxRulez Hopefully the mentioned commit will also be included.

**Comment by DraganRatkovich** [comment]
Closed in 02d04bf

**Comment by yastrebilya2018** [comment]
It would be really cool if they fix it.
And reactions will finally start to sound normal in screen readers!
Thank you, dear developer, for making a convenient telegram program.

**Comment by MarcAnt01** [comment]
@Ancientlizard in case it wasn't clear, this has already been week. You just need to wait for the update to be published in the store
