### ISSUE TITLE
Need NUGET package for this repo.

### ISSUE THREAD

**Issue by zydjohnHotmail** [UnigramDev/Unigram#2760]
Hello:
I want to try this repo.  I downloaded the Unigram-8.3.zip, uncompressed it, but I found most of the codes were in C++, which I don't have experience.
I am using C# on Windows 10.  I want to know if you can release a NUGET package, so it will be much easier for people using C# to run your repo.
Thanks,

**Comment by FrayxRulez** [comment]
Hey, Unigram isn't a library but an app, I think that you're looking for https://github.com/tdlib/td
