### ISSUE TITLE
Removing an opened folder results in empty chatlist

### ISSUE THREAD

**Issue by makisukurisu** [UnigramDev/Unigram#2764]
**Describe the bug**
If you remove opened folder - you will get an empty chat list for all the folders until you reopen the app. (Or change accounts)

**To Reproduce**
1. Create a spare folder
2. Select this folder
3. Right click on it and select "Delete"

**Expected behavior**
Choose either a neighboring folder (either one to the left, or one to the right), or select first folder in a list. 

**Screenshots**
Two gifs for two possible folder positions:
On top
![On top](https://user-images.githubusercontent.com/49622129/175386364-0b34f37c-301b-4aa2-81f5-6aaad129c144.gif)

On the side
![Side](https://user-images.githubusercontent.com/49622129/175386396-46b1617c-8c9c-4d35-896f-7c315ffc10b3.gif)

**Version Info**
 - Unigram: v 8.8 7410 x64 Direct
 - Windows: 11 (22H2)

**Additional context**
It doesn't matter where the folder is located (like if it's last one, or not). (Tested just in case Unigram tried to get next folder)

**Comment by AsrorbekDev** [comment]
@makisukurisu lol faster bug  found after relaease
