### ISSUE TITLE
Profile, Settings and Instant View pages don't use the full window width

### ISSUE THREAD

**Issue by yume-chan** [UnigramDev/Unigram#2765]
**Describe the bug**
They behave like they have a max width limit, and don't grow with window after a certain point.

**To Reproduce**
1. Open https://t.me/unigram in App
2. Click the top bar to open profile page
3. It leaves blank at right:

![175769865-97f67cda-bbcf-462e-82ba-75badd554854](https://user-images.githubusercontent.com/1330321/175770202-32486d9e-2b88-4232-a184-6e13b76e36c9.png)

5. Open https://t.me/unigram/229 in App
6. Click "Instant View" button at the bottom of message
7. It leaves blank at right

![175769903-06f43844-b8e6-443e-b6b9-b662c4c339cc](https://user-images.githubusercontent.com/1330321/175770215-32969664-2959-4aa0-8365-8dfe1e12a867.png)

9. Click avatar at top left
10. Select "Settings"
11. Open any setting page
12. It leaves blank at right

The "Stickers and Emoji" panel is the worst one:

![175769560-b78ec73d-aaf2-4cb6-be6c-85a1866d8043](https://user-images.githubusercontent.com/1330321/175770218-61f22d59-ffd0-4b7e-a7e1-d0d12903cafb.png)

**Version Info**
 - Unigram: 8.8 (7415)
 - Windows: Windows 11 Pro Insider Preview 22H2 25145.1000

**Comment by FrayxRulez** [comment]
> They behave like they have a max width limit, and don't grow with window after a certain point.
This is by design.
