### ISSUE TITLE
About the problem of incomplete text display under certain circumstances

### ISSUE THREAD

**Issue by CuteCatXiao** [UnigramDev/Unigram#2766]
![image](https://user-images.githubusercontent.com/62191675/175778271-9894b368-05bb-4ee7-9100-85a4eb57f732.png)

Unigram 8.8 7430

**Comment by MarcAnt01** [comment]
@CuteCatXiao please create a new ticket following the template and trying to explain the issue. This issue is unintelligible

**Comment by CuteCatXiao** [comment]
> @CuteCatXiao please create a new ticket following the template and trying to explain the issue. This issue is unintelligible

new ticket is issued,I believed it's more intelligible

**Comment by MarcAnt01** [comment]
Definitely, thank you
