### ISSUE TITLE
Opening the Unigram News channel closes Unigram

### ISSUE THREAD

**Issue by Vivelin** [UnigramDev/Unigram#2778]
**Describe the bug**
After I updated to 8.8 from the Microsoft Store, the UI closes automatically (crashes?) when trying to view the Unigram news channel. It loads for a brief second before Unigram closes. The system tray icon remains. When opening Unigram again, the channel is not visible.

**To Reproduce**
1. Go to https://t.me/unigram
2. Click on 'View in Telegram'
3. If prompted by Windows, open the link in Unigram

**Expected behavior**
The channel stays open and I can read the messages.

**Version Info**
 - Unigram 8.8 (7431) X64
 - Windows 11 21H2 (OS Build 22000.739)

**Additional context**
The same issue also happens if I open the Unigram News channel by searching in Unigram itself or by clicking the News link in the Unigram menu.

I don't know if this issue occurred before this version or not. I haven't joined any channels. I can view other channels without this crash issue.

**Comment by KeronCyst** [comment]
It's not just the news channel; it appears to be affecting almost all groups and channels. This is now one of the few I could find that don't crash it: https://t.me/NekogramX

**Comment by makisukurisu** [comment]
Is this still a thing? If it is - please, comment/reopen the issue
