### ISSUE TITLE
Reaction emojis are now invisible

### ISSUE THREAD

**Issue by KeronCyst** [UnigramDev/Unigram#2781]
**Describe the bug**
Reaction emojis are now invisible and only show the mouse turning into a pointing hand when mousing over where they normally are, but nothing else. They also don't display properly in conversations.

**To Reproduce**
1. Try to react or see chat reactions

**Expected behavior**
The emojis should be visible in the menu and in chats with reactions

**Screenshots**
![image](https://user-images.githubusercontent.com/13827055/176042205-d73eec9f-f2c8-4eb4-a8f2-0e81743f171d.png)

**Version Info**
 - Unigram: 8.8 (7438) x64
 - Windows: Windows 10 Home 21H2

**Comment by feiercrack** [comment]
..same here

**Comment by wobbleninja** [comment]
Same problem here. Reactions invisible. Also stickers invisible. And gifs invisible. Gifs though appear when you send them. The rest don't

**Comment by MarcAnt01** [comment]
> Same problem here. Reactions invisible. Also stickers invisible. And gifs invisible. Gifs though appear when you send them. The rest don't
> 
> Edit: I have added my 2nd account too and on my 2nd account everything seems to be working fine. I basically texted my 2nd account from my first account a sticker and a gif. And I reacted on a message. On my 2nd account I can see everything normally but on first I see only the GIF and no sticker or reaction.

This is probably unrelated to this issue

**Comment by makisukurisu** [comment]
@wobbleninja , can you try to go through this video:
https://t.me/unigraminsiders/437476

Second part of that video should help.
Also Fela said that this is going to be fixed in future versions of Unigram.

**Comment by FrayxRulez** [comment]
@makisukurisu This was fixed in TDLib upstream: https://github.com/tdlib/td/commit/72bc28563758be854c27eee6b85d620c3240019c
Some additional checks need to be added to Unigram as well, I expect this to happen in a couple of days

**Comment by wobbleninja** [comment]
@makisukurisu Yeah thanks. That helped for now

**Comment by FrayxRulez** [comment]
Fixed on my side as well
