### ISSUE TITLE
Display an alert about a reaction to a message.

### ISSUE THREAD

**Issue by ProxiDoz** [UnigramDev/Unigram#2784]
**Display an alert about a reaction to a message.**
Display an alert about a reaction to a message, after skip alert.

1. Open chat with alert.
2. Click on alert.
3. Scroll to message.
4. Alert don't hide.
![Screenshot_2](https://user-images.githubusercontent.com/13611942/176420746-13eaeadb-d70f-4cca-ab45-e7946ffbe24a.png)

**Version Info**
 - Unigram: 8.8
 - Windows: 16.‎05.‎2022 version 21H2

**Comment by FrayxRulez** [comment]
If this still exists, it's likely in TDLib, but this is probably fixed.
