### ISSUE TITLE
Certain group chats do not show up in the search result for forwarding menu

### ISSUE THREAD

**Issue by eiarhabi** [UnigramDev/Unigram#2786]
**Describe the bug**
Some group chats I joined do not show up in the search result for forwarding menu

**Screenshots**
![image](https://user-images.githubusercontent.com/27269666/177015746-2508d4fe-759a-442f-aded-8fc7f3b47d30.png)
![image](https://user-images.githubusercontent.com/27269666/177015748-8c3ab12c-759b-43dc-9616-5c6c361cbe02.png)
Some groups are missing from the search result when trying to forward a message.

**Version Info**
 - Unigram: 8.8(7440) x64
 - Windows: 25151.1000

**Comment by MarcAnt01** [comment]
It seems to happen with a specific chat for me too

**Comment by FrayxRulez** [comment]
> It seems to happen with a specific chat for me too

Which one?
