### ISSUE TITLE
Attachment falsely disappears when adding a caption to a multi-attachment message

### ISSUE THREAD

**Issue by KeronCyst** [UnigramDev/Unigram#2788]
**Describe the bug**
When editing a multi-attachment message to add a caption, one of the attachments appears to disappear until Unigram is restarted.

**To Reproduce**
1. Attach two PDFs, and send them to a one-on-one chat with no message/text/caption
2. Edit the two-PDF message and add any message/text/caption
3. See error

**Expected behavior**
You should see both PDFs with your edited message and not see one of them disappear

**Screenshots**
N/A

**Version Info**
 - Unigram: Unigram 8.8 (7438) x64
 - Windows: 10 Home 21H2

**Additional context**
N/A

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/6528bdc7c40577afd0424ebc2a92707d61542162
