### ISSUE TITLE
IV Contest links don't open

### ISSUE THREAD

**Issue by Marocco2** [UnigramDev/Unigram#279]
When I try to open this link (for example https://t.me/iv?url=http://www.formulapassion.it/2017/05/indy500-alonso-pista-nelle-prove-libere-8-live-streaming/&rhash=05d581eeda9e9b ) I get an error

![image](https://cloud.githubusercontent.com/assets/3944248/26319368/0784ddf4-3f1f-11e7-99fd-f16e69814dee.png)

Unigram Store version (W10M)

**Comment by FrayxRulez** [comment]
This is expected since when the Store version was released iv links were not existent.
Development branch already supports this and telesco.pe feature since weeks.

**Comment by Marocco2** [comment]
Thanks a lot!
