### ISSUE TITLE
Notification avatar disappeared

### ISSUE THREAD

**Issue by NalCol** [UnigramDev/Unigram#2790]
**Describe the bug**
Avatar in notification gone after a day passed

**To Reproduce**
I don't know why it became like this
But I moved Unigram from C:\ to D:\ with System Settings

**Expected behavior**
Show avatar like before

**Screenshots**

Before:
![Before](https://user-images.githubusercontent.com/58576200/179471389-aa09f76b-bea1-4f21-9537-a3d6541b762a.jpg)
After:
![After](https://user-images.githubusercontent.com/58576200/179471576-70a17a31-edee-4393-82c7-be851bafe8be.png)

**Version Info**
 - Unigram 8.8 (7438) X64
 - Windows 11 Pro 22000.795

**Comment by makisukurisu** [comment]
Is it not just a different type of notification?

You don't have answer button and field on second one.

Can you clear notifications and send message to yourself again?

**Comment by NalCol** [comment]
it is a example, before DM and channels will have avatar, now every notifications don't have avatar.
this problem appeared for a long time, i tried Unigram on muitiple computers and most of them won't have avatar after some days

**Comment by makisukurisu** [comment]
@NalCol Technically this will help, but that is not the issue. You have "+2 other" notifications from Unigram, that's why you don't have avatar, because it's a list, not a single message.

**Comment by NalCol** [comment]
everything is working as usual except avatar

**Comment by NalCol** [comment]
I just get a screenshot from DM
![image](https://user-images.githubusercontent.com/58576200/179477143-2a8ef9c9-912c-4cb7-bfb3-7b40a3653b92.png)

**Comment by NalCol** [comment]
Will move Unigram to other disk like D:\ break notification?
I only made this change after yesterday shutted down computer.

**Comment by makisukurisu** [comment]
Can confirm - I have same account in two apps - Direct in C, and Store in D (with Store in C everything worked as normal)

![image](https://user-images.githubusercontent.com/49622129/182222644-a998bca9-9ad8-4ad3-927c-a30997fe3b62.png)

**Comment by NalCol** [comment]
> Can confirm - I have same account in two apps - Direct in C, and Store in D (with Store in C everything worked as normal)

My Unigram is from store, I found a most possible reason of this bug just now
I tried to **move back Unigram from D: to C:** ( the disk installed Windows )
and it works! now avatar show up as usual.
## Why the bug appears
I think it is a path bug lead the avatar resource can't be found by Notification Center
If you move the app, the AppData file will be stored in Disk:\WpSystem\
Not same path with the OS Installed disk.
## Possible way to fix it
move back Unigram from D: to C: ( the disk installed Windows )
## Screenshot here
![image](https://user-images.githubusercontent.com/58576200/182276683-aaf3d546-5e01-40df-b016-acbdda0c6b78.png)

I am not a native English speaker, if you can't understand my words, please tell me.

**Comment by FrayxRulez** [comment]
Unfortunately I have no control over system shell, so I believe that this issue must be addressed to Microsoft, and not to us.
The app obviously uses the special path format requested by the system when showing a notification: [NotificationsService.cs#L449](https://github.com/UnigramDev/Unigram/blob/abe509e2496664111289c6b0c6bc5d9bf492d8eb/Unigram/Unigram/Services/NotificationsService.cs#L449)

**Comment by NalCol** [comment]
> Unfortunately I have no control over system shell, so I believe that this issue must be addressed to Microsoft, and not to us. The app obviously uses the special path format requested by the system when showing a notification: [NotificationsService.cs#L449](https://github.com/UnigramDev/Unigram/blob/abe509e2496664111289c6b0c6bc5d9bf492d8eb/Unigram/Unigram/Services/NotificationsService.cs#L449)

At least everybody know why it isn't working now :)
