### ISSUE TITLE
 if you change the resolution of the screen, the scale of the application does not change

### ISSUE THREAD

**Issue by ost4k** [UnigramDev/Unigram#2793]
**Describe the bug**
With the new version of Unigram, if you change the resolution of the screen, the scale of the application does not change

**To Reproduce**
1. connect a higher resolution display
2. the unigram interface has become small
or
0. restart the application so that the scale adapts to the display size
1. disconnect a higher resolution display
2. the unigram interface has become bigger

**Expected behavior**
In older versions of the application, when you connect or disconnect the high resolution display, Unigram itself adapts to these changes, it was not necessary to restart

**Version Info**
 - Unigram: 8.9 (7454)
 - Windows: 11 22h2

**Comment by FrayxRulez** [comment]
@ost4k This sounds like a system issue as Unigram has no control over the scaling.

**Comment by ost4k** [comment]
I don't know how, but the problem went away... The interface is adaptive again on different resolutions. if the problem occurs again I will let you know
