### ISSUE TITLE
Show premium badge in more places

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2796]
- [ ] poll results
- [ ] forward menu
- [ ] chat (near the propic)
- [ ] add members popup

**Comment by MarcAnt01** [comment]
I guess this ticket can be refactored in a general one, with all the places where it's missing

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/cbb2a4d7032a36b3e9b93c141592dd9ab06785a7
