### ISSUE TITLE
No audio in videomessages

### ISSUE THREAD

**Issue by nomadedge** [UnigramDev/Unigram#2799]
**Describe the bug**
Then someone sends me a video message (these round videos) I can play them and see the video but not hear it cuz there's no audio. 
 If right-click on video and select "Open in..." and open it in Movies & TV (default windows player) I can hear the audio.

**To Reproduce**
Open any chat where you received a video message and play it.

**Expected behavior**
To hear the audio.

**Version Info**
 - Unigram: 8.8 (7438) X64
 - Windows 11 Pro 21H2

**Comment by makisukurisu** [comment]
Can I ask you to play this one:
https://t.me/unigraminsiders/446435

If it doesn't work probably some more info is required.

**Comment by FrayxRulez** [comment]
Duplicate of #2247

**Comment by agaspb1** [comment]
Bug is still being reproduced on all videos.

Unigram: 11.5.3 X64
Windows 11 Pro 23H2
