### ISSUE TITLE
Can't read dark mode QR code 

### ISSUE THREAD

**Issue by tiagoad** [UnigramDev/Unigram#2800]
Hi devs,

I would like to propose showing the login QR code black-on-white even when on dark mode. I'm not being able to read the white-on-black code on my telegram app, and a quick invert on paint.exe made it read instantly.

Thanks for your consideration.

**Comment by MarcAnt01** [comment]
I did some tries and the qr code in dark mode is read properly both on Android and iOS, so I think it's a problem due to your mobile client (the one from which you're scanning the qr code from to be clear)

**Comment by FrayxRulez** [comment]
@MarcAnt01 Android can’t read it properly depending on the Google Play Services version

**Comment by tiagoad** [comment]
> I did some tries and the qr code in dark mode is read properly both on Android and iOS, so I think it's a problem due to your mobile client (the one from which you're scanning the qr code from to be clear)

I'm using whatever Unigram is embedding within itself, I was given no choice. @FraixRulez suggestion seems plausible. I did numerous tests and indeed the black code could never be read (Oneplus9 Pro, stock android 11)

**Comment by redactedscribe** [comment]
I also had this problem. I was about to give up.

My android device does _not_ have Google Play Services installed and the official Telegram Android app always fails to read Unigram's QR code, no matter the angle or orientation used. Only after taking a screenshot of the QR code and inverting the image will Telegram's app be immediately able to read it.

If we could click the QR code to show a black on white variant then these additional steps wouldn't be necessary.

Unigram 8.9
Telegram 8.9.3 (Android)

**Comment by makisukurisu** [comment]
@redactedscribe You can just change your system's theme from dark to white temporarily.

**Comment by redactedscribe** [comment]
Right, that's one possibility. The problem remains however that nothing indicates to the user that toggling the system's theme or inverting the QR code image is what they need to do to proceed.
