### ISSUE TITLE
Media editor: the enter button leads the client to perform an incorrect action

### ISSUE THREAD

**Issue by kuogi** [UnigramDev/Unigram#2802]
**Describe the bug**
The enter button leads the client to perform an incorrect action in the media editor.

**To Reproduce**
1. Attach a photo (using ctrl+v or attach button)
2. Click on the edit icon
3. Make some changes (resize, brush or other)
4. Click enter button on keyboard

**Expected behavior**
The enter key should have the same behaviour as if the success icon was pressed
![image](https://user-images.githubusercontent.com/60541000/183635613-934140d9-dfa2-46b1-a6f9-ea21bb998157.png)

**Video**
https://user-images.githubusercontent.com/60541000/183635259-9f21c5e3-3550-4ad6-a505-275ec4065347.mp4

**Version Info**
 - Unigram: 8.9 7527 x64
 - Windows 10 21H2 19044.1706

**Comment by makisukurisu** [comment]
Use Shift+Enter in order for this to work. same applies to all other buttons you can select in "Send message" dialog

**Comment by makisukurisu** [comment]
Yep, should've looked at it before commenting.
I thought you have tabbed to the "Save/Confirm/Whatever" button.

Thanks for the report, hope it's possible to enhance this aspect of the app.

**Comment by kuogi** [comment]
> Yep, should've looked at it before commenting. I thought you have tabbed to the "Save/Confirm/Whatever" button.
> 
> Thanks for the report, hope it's possible to enhance this aspect of the app.

It could, from a certain point of view, also be a bit of a security issue: a person could possibly obscure sensitive information from a photo and then end up sending the original photo by mistake using the enter key. I hope this is resolved or in any case implemented soon

**Comment by FrayxRulez** [comment]
I actually find quite interesting that in a UI where you fully interact using your mouse (because you can't draw or crop otherwise) you try to finally confirm the action using the keyboard 😅

**Comment by FrayxRulez** [comment]
Anyhow I believe that this can be considered a duplicate of #1544
