### ISSUE TITLE
Allow to ban people from group in Recent Actions

### ISSUE THREAD

**Issue by makisukurisu** [UnigramDev/Unigram#2803]
**Describe the feature request**
When you open Recent Actions of some group - there should be a possibility to ban a person from there.

**Use Case**
1. Go to Recent Actions of some group
2. Right click on a message of someone you want to ban
3. Select "Ban from the group"
4. Person is banned, case closed.

*Additional Information:*
String for "Ban From The Group" is present in TG for Android, just so you know.

**Comment by FrayxRulez** [comment]
This is available
