### ISSUE TITLE
how to change audio device?

### ISSUE THREAD

**Issue by feiercrack** [UnigramDev/Unigram#2804]
cant find anything to change current audio device.

Normally i can listen to the videos / voices / streams via my desktop loudspeakers.

but when my headset is plugged in / bluetooth, even when it´s shut-off and loading only, it´s automatically and still routed to the headset. why?

please add an audio control inside the app.
thanks^^

**Comment by MarcAnt01** [comment]
Unigram uses the default device for playing audio, so just go to system settings > System > sound 
For calls you have the possibility to adjust them even during the call from the options menu
