### ISSUE TITLE
Heavy graphics glitches with AMD RDNA2 GPUs when GIFs/stickers/telemoji are on screen

### ISSUE THREAD

**Issue by Marocco2** [UnigramDev/Unigram#2805]
**Describe the bug**
AMD RDNA 2 family GPUs display very noticeable glitches on Unigram UI while is trying to render GIFs, stickers and telemojis. Latest drivers at the timing of writing (22.7.1 and 22.8.1) present this issue. Older drivers haven't been tested so far

**To Reproduce**
Only AMD RDNA 2 owners are affected 
1. Go to sticker panel and watch for UI glitches

**Expected behavior**
No glitches

**Version Info**
 - Unigram: 8.9.7550 x64
 - Windows: 11 21H2

**Comment by Marocco2** [comment]
Newer driver released by AMD (22.8.2) fixed the issue

**Comment by FrayxRulez** [comment]
@Marocco2 A bumbazza
