### ISSUE TITLE
Remove premium stickers on stickers menu

### ISSUE THREAD

**Issue by 734F96** [UnigramDev/Unigram#2808]
Hello,
Why did you decide since version 8.9 to display the premium stickers for non-premium users, without the possibility to hide them?
I think you have taken this feature from the official Android version, but it has been criticized by the community [1] (Along with the display of premium emojis [2]), and would apparently be a bug according to Telegram developers [3].

![Sitckers menu](https://user-images.githubusercontent.com/50321866/185617199-403d151f-d09b-46ed-8a7e-c0ee92d3edd5.png)

So I think that the premium stickers should be hidden by default, especially since it was a bug on the Android version, which has been fixed (Tested on version 8.9.3 from the Play Store).
Thanks for reading, and have a nice  day !

[1] https://www.reddit.com/r/Telegram/comments/wnaeaw/90_paywall_locked_premium_stickers_put_in_front/
[2] https://www.reddit.com/r/Telegram/comments/wqx3zs/i_cant_buy_the_premium_and_i_dont_want_my_emoji/
[3] https://twitter.com/telegram/status/1558426278063230976

PS: I have edited this post several times to make it cleaner. I'm sorry about the first version where I was pretty upset.

**Comment by kenvix** [comment]
These premium features is really annoying. It would be better if there was an option to disable premium features like stickers.
