### ISSUE TITLE
How to change the ringtone for incoming messages? 

### ISSUE THREAD

**Issue by EightStrings** [UnigramDev/Unigram#2809]
How to change the ringtone for incoming messages?
If I can do it, how should I do it?

**Comment by MarcAnt01** [comment]
Hello, the is not possible

**Comment by FrayxRulez** [comment]
You can change incoming messages ringtone from Settings > Notifications and Sounds > Private chats / Groups / Channels > Sound.

**Comment by makisukurisu** [comment]
Sadly this doesn't affect sound of notification 😢 

Should this be a feature request?
