### ISSUE TITLE
Crashes Upon Opening

### ISSUE THREAD

**Issue by hezmekiah** [UnigramDev/Unigram#281]
I am installing Unigram on my laptop after a fresh install. It freezes on the welcome screen then crashes after a few seconds.

**Comment by FrayxRulez** [comment]
Duplicate: https://github.com/UnigramDev/Unigram/issues/272

**Comment by hezmekiah** [comment]
If I press "welcome" immediately, I can access the app. Just waiting at the welcome screen leads to the crash. This is before having signed in

**Comment by FrayxRulez** [comment]
Can you use the other post? Thank you
