### ISSUE TITLE
Add "Show more" for search results

### ISSUE THREAD

**Issue by makisukurisu** [UnigramDev/Unigram#2810]
If you search for some channel/group in search field there should be a way to see more than 3 public groups/channels results.

Ex. Search for "Word"

![image](https://user-images.githubusercontent.com/49622129/186498751-e2b8cfe3-be46-46e1-b530-cfa5c833bcb1.png)

Unigram shows 3 results only.
On Android you can press "Show More"

![image](https://user-images.githubusercontent.com/49622129/186499020-e98bed07-da33-468d-b223-ca6548e6b4cc.png)
Click on "Show more"
![image](https://user-images.githubusercontent.com/49622129/186499056-b4ae7373-0f0c-4cfa-b6ba-e1005da31422.png)
Get more

_Not sure if Android shows all possible results, but it's more than 3 for sure._

**Comment by FrayxRulez** [comment]
Unigram now always shows the maximum amount of results right away
