### ISSUE TITLE
Hitting Enter when emoji suggestions pop up should insert the first suggestion

### ISSUE THREAD

**Issue by khalibloo** [UnigramDev/Unigram#2811]
When typing a message, and emoji suggestions are brought up, I'd expect that hitting enter should insert the first one. However, hitting enter just sends the message instead.

**Comment by FrayxRulez** [comment]
@khalibloo Different users have different opinions on this. Someone could argue that they want their message to be sent as it is, and not to be edited with an emoji. What you can to is to hit tab and then enter.

**Comment by khalibloo** [comment]
Good point. I would argue that when suggestions are offered, I should be able to confirm that suggestion by saying "ok", and that usually means enter on a keyboard. And this is also how the official telegram app behaves. But yeah it's not a universal rule even if a lot of apps work that way.

The feature is definitely hard to use as it is now. tab then enter is not intuitive. I never would have figured that out. And in dark mode, it's near impossible to see which emoji is highlighted, so i cant use arrow keys either. right now, i have to grab my mouse and click. then return to typing

**Comment by FrayxRulez** [comment]
@khalibloo Other than tab you can use right arrow

**Comment by MarcAnt01** [comment]
I agree with @FrayxRulez .In every messaging app enter sends the message, in my opinion arrows are more than enough and I'm using emoji autosuggest on daily basis

**Comment by khalibloo** [comment]
I wouldn't say every messaging app. Discord, telegram desktop, teams, slack, all behave the way I described. If an emoji suggestion is offered, hitting enter inserts the suggestion. In other situations, enter sends the message.

**Comment by FrayxRulez** [comment]
This was done in https://github.com/UnigramDev/Unigram/commit/a67706e8302dca03502449574bde715d530712ba
