### ISSUE TITLE
I can't install unigram in windows 2019 LTSC

### ISSUE THREAD

**Issue by mchridz** [UnigramDev/Unigram#2814]
**I can't install unigram in windows 2019 LTSC, i installed all the requirements ( [Microsoft.NET.Native.Framework]  [Microsoft.NET.Native.Runtime] [Microsoft.UI.Xaml.2.7] [Microsoft.VCLibs.140.00] )
but when i try to install unigram i get this error** 

Add-AppxPackage : Deployment failed with HRESULT: 0x80073CFD, A Prerequisite for an install could not be satisfied.
`Windows cannot install package TelegramFZ-LLC.Unigram_8.8.7446.0_x64__1vfw5zm9jmzqy because this package is not `compatible with the
`device. The package requires OS version 10.0.18362.0 or higher on the Windows.Universal device family. The device is currently
`running OS version 10.0.17763.3287.
`NOTE: For additional information, look for [ActivityId] 4b073120-b0a8-0001-fc28-0c4ba8b0d801 in the Event Log or use the `command
`line Get-AppPackageLog -ActivityID 4b073120-b0a8-0001-fc28-0c4ba8b0d801
`At line:1 char:1
+ Add-AppxPackage Unigram_8.8.7446.0_x64.msixbundle
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Users\paimen..._x64.msixbundle:String) [Add-AppxPackage], Exception
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

**and this what i get after i did Get-AppPackageLog -ActivityID 4b073120-b0a8-0001-fc28-0c4ba8b0d801**

PS C:\Users\paiment\Downloads\filesuwp> Get-AppPackageLog -ActivityID 4b073120-b0a8-0001-fc28-0c4ba8b0d801

Time                      ID           Message
----                      --           -------
28/08/2022 09:19:05       603          Started deployment Add operation on a package with main parameter
                                       Unigram_8.8.7446.0_x64.msixbundle and Options 0 and 0. See
                                       http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues.
28/08/2022 09:19:05       164          The app bundle signature was validated for core content of the app bundle published by
                                       CN=Telegram FZ-LLC, O=Telegram FZ-LLC, POBox=501, L=Dubai, C=AE, OID.2.5.4.15=Private
                                       Organization, OID.1.3.6.1.4.1.311.60.2.1.3=AE, SERIALNUMBER=94349. App packages won't be
                                       validated until they are read.
28/08/2022 09:19:05       216          App manifest validation warning: Declared namespace
                                       http://schemas.microsoft.com/appx/2018/bundle is inapplicable, it will be ignored during
                                       manifest processing.
28/08/2022 09:19:05       216          App manifest validation warning: Declared namespace
                                       http://schemas.microsoft.com/appx/2019/bundle is inapplicable, it will be ignored during
                                       manifest processing.
28/08/2022 09:19:05       391          The bundle streaming reader was created successfully for bundle
                                       TelegramFZ-LLC.Unigram_8.8.7446.0_neutral_~_1vfw5zm9jmzqy.
28/08/2022 09:19:05       10002        Creating Resiliency File C:\ProgramData\Microsoft\Windows\AppRepository\762ee8a0-ce8d-441b-b53
                                       b-66f0db36e8cb_S-1-5-21-725280954-3363733201-2296926997-1001_16.rslc for Add Operation on
                                       Package TelegramFZ-LLC.Unigram_8.8.7446.0_neutral_~_1vfw5zm9jmzqy.
28/08/2022 09:19:05       607          Deployment Add operation on package TelegramFZ-LLC.Unigram_8.8.7446.0_neutral_~_1vfw5zm9jmzqy
                                       has been de-queued and is running for user SID S-1-5-21-725280954-3363733201-2296926997-1001.
28/08/2022 09:19:05       614          Bundle Uri file:///C:/Users/paiment/Downloads/filesuwp/Unigram_8.8.7446.0_x64.msixbundle
                                       contains packages: "UnigramPackage_8.8.7446.0_x64.msix":
                                       TelegramFZ-LLC.Unigram_8.8.7446.0_x64__1vfw5zm9jmzqy
                                       "UnigramPackage_8.8.7446.0_language-ar.msix":
                                       TelegramFZ-LLC.Unigram_8.8.7446.0_neutral_split.language-ar_1vfw5zm9jmzqy
                                       "UnigramPackage_8.8.7446.0_language-be.msix":
                                       TelegramFZ-LLC.Unigram_8.8.7446.0_neutral_split.language-be_1vfw5zm9jmzqy
                                       "UnigramPackage_8.8.7446.0_language-ca.msix":
                                       TelegramFZ-LLC.Unigram_8.8.7446.0_neutral_split.language-ca_1vfw5zm9jmzqy
                                       "UnigramPackage_8.8.7446.0_language-cs.msix":
                                       TelegramFZ-LLC.Unigram_8.8.7446.0_neutral_split.language-cs_1vfw5zm9jmzqy
                                       "UnigramPackage_8.8.7446.0_language-de.msix":
                                       TelegramFZ-LLC.Unigram_8.8.7446.0_neutral_split.language-de_1vfw5zm9jmzqy
                                       "UnigramPackage_8.8.7446.0_language-es.msix":
                                       TelegramFZ-LLC.Unigram_8.8.7446.0_neutral_split.language-es_1vfw5zm9jmzqy
                                       "UnigramPackage_8.8.7446.0_language-fa.msix":
                                       TelegramFZ-LLC.Unigram_8.8.7446.0_neutral_split.language-fa_1vfw5zm9jmzqy
                                       "UnigramPackage_8.8.7446.0_language-fi.msix":
                                       TelegramFZ-LLC.Unigram_8.8.7446.0_neutral_split.language-fi_1vfw5zm9jmzqy
                                       "UnigramPackage_8.8.7446.0_language-fr.msix":
                                       TelegramFZ-LLC.Unigram_8.8.7446.0_neutral_split.language-fr_1vfw5zm9jmzqy
                                       "UnigramPackage_8.8.7446.0_language-hu.msix":
                                       TelegramFZ-LLC.Unigram_8.8.7446.0_neutral_split.language-hu_1vfw5zm9jmzqy
                                       "UnigramPackage_8.8.7446.0_language-id.msix":
                                       TelegramFZ-LLC.Unigram_8.8.7446.0_neutral_split.language-id_1vfw5zm9jmzqy
                                       "UnigramPackage_8.8.7446.0_language-it.msix":
                                       TelegramFZ-LLC.Unigram_8.8.7446.0_neutral_split.language-it_1vfw5zm9jmzqy
                                       "UnigramPackage_8.8.7446.0_language-ko.msix":
                                       TelegramFZ-LLC.Unigram_8.8.7446.0_neutral_split.language-ko_1vfw5zm9jmzqy
                                       "UnigramPackage_8.8.7446.0_language-ms.msix":
                                       TelegramFZ-LLC.Unigram_8.8.7446.0_neutral_split.language-ms_1vfw5zm9jmzqy
                                       "UnigramPackage_8.8.7446.0_language-nl.msix":
                                       TelegramFZ-LLC.Unigram_8.8.7446.0_neutral_split.language-nl_1vfw5zm9jmzqy
                                       "UnigramPackage_8.8.7446.0_language-pl.msix":
                                       TelegramFZ-LLC.Unigram_8.8.7446.0_neutral_split.language-pl_1vfw5zm9jmzqy
                                       "UnigramPackage_8.8.7446.0_language-pt.msix":
                                       TelegramFZ-LLC.Unigram_8.8.7446.0_neutral_split.language-pt_1vfw5zm9jmzqy
                                       "UnigramPackage_8.8.7446.0_language-ru.msix":
                                       TelegramFZ-LLC.Unigram_8.8.7446.0_neutral_split.language-ru_1vfw5zm9jmzqy
                                       "UnigramPackage_8.8.7446.0_language-sk.msix":
                                       TelegramFZ-LLC.Unigram_8.8.7446.0_neutral_split.language-sk_1vfw5zm9jmzqy
                                       "UnigramPackage_8.8.7446.0_language-tr.msix":
                                       TelegramFZ-LLC.Unigram_8.8.7446.0_neutral_split.language-tr_1vfw5zm9jmzqy
                                       "UnigramPackage_8.8.7446.0_language-uk.msix":
                                       TelegramFZ-LLC.Unigram_8.8.7446.0_neutral_split.language-uk_1vfw5zm9jmzqy
                                       "UnigramPackage_8.8.7446.0_scale-100.msix":
                                       TelegramFZ-LLC.Unigram_8.8.7446.0_neutral_split.scale-100_1vfw5zm9jmzqy
                                       "UnigramPackage_8.8.7446.0_scale-125.msix":
                                       TelegramFZ-LLC.Unigram_8.8.7446.0_neutral_split.scale-125_1vfw5zm9jmzqy
                                       "UnigramPackage_8.8.7446.0_scale-150.msix":
                                       TelegramFZ-LLC.Unigram_8.8.7446.0_neutral_split.scale-150_1vfw5zm9jmzqy
                                       "UnigramPackage_8.8.7446.0_scale-400.msix":
                                       TelegramFZ-LLC.Unigram_8.8.7446.0_neutral_split.scale-400_1vfw5zm9jmzqy.
28/08/2022 09:19:05       157          The app package signature was validated for core content of the app package published by
                                       CN=Telegram FZ-LLC, O=Telegram FZ-LLC, POBox=501, L=Dubai, C=AE, OID.2.5.4.15=Private
                                       Organization, OID.1.3.6.1.4.1.311.60.2.1.3=AE, SERIALNUMBER=94349. Payload won't be validated
                                       until the files are read.
28/08/2022 09:19:05       216          App manifest validation warning: Declared namespace
                                       http://schemas.microsoft.com/developer/appx/2015/build is inapplicable, it will be ignored
                                       during manifest processing.
28/08/2022 09:19:05       170          The streaming reader was created successfully for app package
                                       TelegramFZ-LLC.Unigram_8.8.7446.0_x64__1vfw5zm9jmzqy.
28/08/2022 09:19:05       157          The app package signature was validated for core content of the app package published by
                                       CN=Telegram FZ-LLC, O=Telegram FZ-LLC, POBox=501, L=Dubai, C=AE, OID.2.5.4.15=Private
                                       Organization, OID.1.3.6.1.4.1.311.60.2.1.3=AE, SERIALNUMBER=94349. Payload won't be validated
                                       until the files are read.
28/08/2022 09:19:05       170          The streaming reader was created successfully for app package
                                       TelegramFZ-LLC.Unigram_8.8.7446.0_neutral_split.language-ar_1vfw5zm9jmzqy.
28/08/2022 09:19:05       157          The app package signature was validated for core content of the app package published by
                                       CN=Telegram FZ-LLC, O=Telegram FZ-LLC, POBox=501, L=Dubai, C=AE, OID.2.5.4.15=Private
                                       Organization, OID.1.3.6.1.4.1.311.60.2.1.3=AE, SERIALNUMBER=94349. Payload won't be validated
                                       until the files are read.
28/08/2022 09:19:05       170          The streaming reader was created successfully for app package
                                       TelegramFZ-LLC.Unigram_8.8.7446.0_neutral_split.language-fr_1vfw5zm9jmzqy.
28/08/2022 09:19:05       157          The app package signature was validated for core content of the app package published by
                                       CN=Telegram FZ-LLC, O=Telegram FZ-LLC, POBox=501, L=Dubai, C=AE, OID.2.5.4.15=Private
                                       Organization, OID.1.3.6.1.4.1.311.60.2.1.3=AE, SERIALNUMBER=94349. Payload won't be validated
                                       until the files are read.
28/08/2022 09:19:05       170          The streaming reader was created successfully for app package
                                       TelegramFZ-LLC.Unigram_8.8.7446.0_neutral_split.scale-100_1vfw5zm9jmzqy.
28/08/2022 09:19:05       854          Successfully added the following uri(s) to be processed:
                                       file:///C:/Users/paiment/Downloads/filesuwp/Unigram_8.8.7446.0_x64.msixbundle file:///C:/Users
                                       /paiment/Downloads/filesuwp/Unigram_8.8.7446.0_x64.msixbundle\UnigramPackage_8.8.7446.0_x64.ms
                                       ix file:///C:/Users/paiment/Downloads/filesuwp/Unigram_8.8.7446.0_x64.msixbundle\UnigramPackag
                                       e_8.8.7446.0_language-ar.msix file:///C:/Users/paiment/Downloads/filesuwp/Unigram_8.8.7446.0_x
                                       64.msixbundle\UnigramPackage_8.8.7446.0_language-fr.msix file:///C:/Users/paiment/Downloads/fi
                                       lesuwp/Unigram_8.8.7446.0_x64.msixbundle\UnigramPackage_8.8.7446.0_scale-100.msix.
28/08/2022 09:19:06       778          Windows cannot install package TelegramFZ-LLC.Unigram_8.8.7446.0_x64__1vfw5zm9jmzqy because
                                       this package is not compatible with the device. The package requires OS version 10.0.18362.0
                                       or higher on the Windows.Universal device family. The device is currently running OS version
                                       10.0.17763.3287.
28/08/2022 09:19:06       605          The last successful state reached was BundleProcessed. Failure occurred before reaching the
                                       next state Indexed. hr: 0x80073CFD
28/08/2022 09:19:06       401          Deployment Add operation with target volume C: on Package
                                       TelegramFZ-LLC.Unigram_8.8.7446.0_neutral_~_1vfw5zm9jmzqy from:
                                       (Unigram_8.8.7446.0_x64.msixbundle)  failed with error 0x80073CFD. See
                                       http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues.
28/08/2022 09:19:06       404          AppX Deployment operation failed for package
                                       TelegramFZ-LLC.Unigram_8.8.7446.0_neutral_~_1vfw5zm9jmzqy with error 0x80073CFD. The specific
                                       error text for this failure is: Windows cannot install package
                                       TelegramFZ-LLC.Unigram_8.8.7446.0_x64__1vfw5zm9jmzqy because this package is not compatible
                                       with the device. The package requires OS version 10.0.18362.0 or higher on the
                                       Windows.Universal device family. The device is currently running OS version 10.0.17763.3287.

**Comment by FrayxRulez** [comment]
Hey 👋 as the error suggests, Unigram requires a new version of Windows to be installed. If you want to stay on LTSC, then you need version 2021:
> The package requires OS version 10.0.18362.0 or higher on the
Windows.Universal device family. The device is currently running OS version 10.0.17763.3287.
