### ISSUE TITLE
Up/Down arrow keys should navigate to start/end of line when typing a message

### ISSUE THREAD

**Issue by khalibloo** [UnigramDev/Unigram#2818]
When typing a new message and the cursor is on the first line, pressing the up arrow key typically takes the cursor to the beginning of the first line. And when on the last line of the text, pressing the down arrow should take the cursor to the end of the text.

I think it's a little odd that Unigram doesn't behave that way. This behavior can be seen in browser text inputs and textarea, and pretty much every chat app I can think of. Discord, Teams, Slack, Telegram Desktop, and so on.

**Comment by FrayxRulez** [comment]
@khalibloo Unfortunately Unigram uses a system component as main the input field and this component doesn’t provide the requested behavior. I’m not sure if it’s technically possible to achieve what you’re asking for.

**Comment by FrayxRulez** [comment]
It was easier than expected 😁
