### ISSUE TITLE
Instant View Issue: Unable to follow links in 'https://t.me/iv?url=' format

### ISSUE THREAD

**Issue by VladWinner** [UnigramDev/Unigram#2820]
**Describe the bug**
When clicking on the above link, the error "Username not found." appears.
UPD: A similar issue #279 was closed back in 2017, but apparently something was deleted or rewritten during development.

**To Reproduce**
1. Find any link in `https://t.me/iv?url=` format (e.g.  )
2. Try to follow this link

**Expected behavior**
Telegram's Instant View page should open.

**Screenshots**
![image](https://user-images.githubusercontent.com/13555921/187492845-088f1483-3c20-4cd6-986a-4984b1cb35cd.png)

**Version Info**
 - Unigram: 8.9.7605.0 x64
 - Windows: 11 22H2 22622.586

**Comment by makisukurisu** [comment]
I guess you forgot to provide an example in (e.g. ) section. May I ask you to add one?

**Comment by VladWinner** [comment]
@makisukurisu You can check absolutely any IV link.
E.g. link used from aforementioned #279: https://t.me/iv?url=http://www.formulapassion.it/2017/05/indy500-alonso-pista-nelle-prove-libere-8-live-streaming/&rhash=05d581eeda9e9b

**Comment by luccascomvoce** [comment]
I tried to open a suggestion link on the Telegram platform and Unigram closes . Is it the same bug or should a new ticket be created?

https://bugs.telegram.org/c/20573

**Comment by luccascomvoce** [comment]
https://user-images.githubusercontent.com/65538684/190358485-fa4e1c7a-b60e-46cf-a7a4-60d6777aa142.mp4

**Comment by FrayxRulez** [comment]
I'm closing this ticket as the issue lives in TDLib and not in Unigram.
