### ISSUE TITLE
Video preview volume bar can't be seen as a normal overlay, even invisible

### ISSUE THREAD

**Issue by PostboxRetinal** [UnigramDev/Unigram#2821]
**Describe the bug**
When watching/streaming videos at any channel or group the volume bar seems to show behind the video, not as a normal overlay, like in background

**To Reproduce**
1. Open Unigram
2. Play a random video
3. Try to adjust its volume
4. Volume bar will be faded on background, can't be seen as a normal volume overlay bar. Even invisible
5. See error

**Expected behavior**
See the volume bar's overlay as normal

**Screenshots**
embbeded

**Version Info**
 - Unigram 9.9 (7574) x64
 - Windows 10 21H2 19044.1949

![Unigram_04_03_39_PM](https://user-images.githubusercontent.com/78338192/187542918-b293a2f8-91a4-4de8-81da-ceae5f368eda.gif)

**Comment by farazfallah** [comment]
@PostboxRetinal Unigram 9.9?

**Comment by PostboxRetinal** [comment]
> @PostboxRetinal Unigram 9.9?

Sorry 8.9

**Comment by PostboxRetinal** [comment]
>     * Unigram 9.9 (7574) x64
Sorry 8.9

**Comment by PostboxRetinal** [comment]
Fixed on latest update
Tested on Unigram 8.9 (7687) Windows Store version

**Comment by PostboxRetinal** [comment]
Fixed on latest update
Tested on Unigram 8.9 (7687) Windows Store version
