### ISSUE TITLE
I wish I could increase my account limit.

### ISSUE THREAD

**Issue by sH1222J** [UnigramDev/Unigram#2824]
limited to three. Can you increase it a little more?

**Comment by AsrorbekDev** [comment]
@sH1222J Hello it is restricted by Telegram. The only way is buy Telegram premium +1 !

**Comment by farazfallah** [comment]
@sH1222J It's not possible

**Comment by MarcAnt01** [comment]
Actually it's possible, purchase Premium in one of your account to get a forth account, by getting Premium to two other account you can get to the limit of six accounts.
