### ISSUE TITLE
Audio separates from video in video messages

### ISSUE THREAD

**Issue by distrair** [UnigramDev/Unigram#2828]
**Describe the bug**
When video messages autoplays and after some time click on the video message to play audio, the audio begins to play but the video do not start from beginning.
**To Reproduce**
1. Find/Record a video message
2. Wait until it plays a little bit
3. Click on video message to play a sound

**Expected behavior**
Video should start from beginning to sync with the videomessage's audio

**Version Info**
 - Unigram: 7.9 (7682) x64
 - Windows: 11 

**Additional context**
Saw that nobody pointed it out

**Comment by FrayxRulez** [comment]
@distrair Hey, this bug has been fixed in the upstream and the fix will be available in a update soon!

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/613b625b980e8961d4a3abaf7bcc0f9a9cdbf734
