### ISSUE TITLE
Call Window is blank

### ISSUE THREAD

**Issue by Animakozak** [UnigramDev/Unigram#283]
Whether it's me calling or accepting, it's just blank with no controls.
However, they showed up once when I restarted the app when the call has already ended.
Checked on both of two of my desktop devices.

![image](https://cloud.githubusercontent.com/assets/14003875/26522336/032d89e0-4307-11e7-8dba-d82154779097.png)

**Comment by larsschellhas** [comment]
I don´t think, that this issue still is around.
