### ISSUE TITLE
Freezes after the last last voice message in a chat is played

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#2830]
**Describe the bug**
Sometims, when the last voice message in a chat is played, the whole app freezes when the voice message ends.
I have encountered this a couple of time now, and it always happens with the last message in the chat. However, I wasn't able to consistently reproduce the behaviour unfortunately.
The window becomes completely unresponsive, and cannot be changed in size for example.

**To Reproduce**
1. Go to a chat
2. Play the last voice message
3. Watch what happens when it ends

**Expected behavior**
I expect the app not to freeze.

**Version Info**
 - Unigram: 8.0 (7687) x64
 - Windows: Windows 11 (10.0.22000)

**Comment by FrayxRulez** [comment]
Still?

**Comment by FrayxRulez** [comment]
I guess not :)
