### ISSUE TITLE
Ctrl + c - ctrl + v does not work

### ISSUE THREAD

**Issue by Ni4ellas** [UnigramDev/Unigram#2831]
Ctrl + c - ctrl + v does not work when copying (from the desktop) a photo or video format. 

https://youtu.be/QeSvOMUdiac

**Version Information**
 - Unigram 9.0 7744 x64
 - Windows 11 21H2 22000.318

**Comment by FrayxRulez** [comment]
@Ni4ellas Did you disable Windows UAC?

**Comment by AsrorbekDev** [comment]
@FrayxRulez 4 views

**Comment by Ni4ellas** [comment]
yes

**Comment by FrayxRulez** [comment]
> yes

UAC must be enabled for Unigram to access files on your system.

**Comment by Ni4ellas** [comment]
But the standard telegram works without UAC and hotkeys work fine there

**Comment by Ni4ellas** [comment]
But the standard telegram works without UAC and hotkeys work fine there
