### ISSUE TITLE
String not translated in context menu of Unigram in "HIDE ICONS" of taskbar

### ISSUE THREAD

**Issue by luccascomvoce** [UnigramDev/Unigram#2833]
**Describe the bug**
Unigram context menu strings in hidden icons are not translated. The strings are:

Open Unigram
Quit Unigram

**To Reproduce**
1. Go to the Unigram icon on the Windows taskbar, in the hidden icons area.
2. Right click to see Unigram context menu
3. The strings will be in English even if the app is using "Português (BR) language

**Expected behavior**
Strings must be translated according to the application language

**Screenshots**
![image_2022-09-15_01-33-34](https://user-images.githubusercontent.com/65538684/190315409-881c3e3c-04cd-4d48-ae55-35ba1bc2edde.jpg)

**Version Info**
 - Unigram: 8.9(7687) x64
 - Windows: 10 21H2
 - Language: Portuguese (Brazil)

**Comment by FrayxRulez** [comment]
Those strings can't be translated as they're outside of Unigram application
