### ISSUE TITLE
消息翻译失败

### ISSUE THREAD

**Issue by xingleiwu** [UnigramDev/Unigram#2834]
**Describe the bug**
消息翻译失败 最新版本
![image](https://user-images.githubusercontent.com/13015600/190848746-487f1295-ea0c-48b9-938d-a30efe68a00e.png)
![image](https://user-images.githubusercontent.com/13015600/190848792-68588e0b-e031-48be-8577-e9b07db989b7.png)
![image](https://user-images.githubusercontent.com/13015600/190848816-437b9452-4bea-4117-a989-9c1f21449bad.png)

**Comment by MarcAnt01** [comment]
@xingleiwu hi, no-one speaks Chinese here, you're kindly asked to translate it in English

**Comment by xingleiwu** [comment]
> @xingleiwu嗨，这里没有人会说中文，请你把它翻译成英文

Message translation failed Latest version

**Comment by MarcAnt01** [comment]
This is not enough for us to understand anything, furthermore you haven't followed the issue template for bug reports

**Comment by FrayxRulez** [comment]
@xingleiwu I believe that the issue is probably that you reached the rate limit for translations. I would recommend you to try again later.

**Comment by xingleiwu** [comment]
> 



> This is not enough for us to understand anything, furthermore you haven't followed the issue template for bug reports which contains important info such as repro steps

![image](https://user-images.githubusercontent.com/13015600/190849311-10ca50e6-af29-4d11-b0f9-3c354300cdeb.png)
![image](https://user-images.githubusercontent.com/13015600/190849336-118d935c-bb91-425c-b374-9d78927988ea.png)

The latest version of

**Comment by xingleiwu** [comment]
> @xingleiwu I believe that the issue is probably that you reached the rate limit for translations. I would recommend you to try again later.
It's been a long time since I couldn't translate it, it's been over a month

**Comment by keyang556** [comment]
翻譯功能需要梯子才能使用，確定您是否可以連接google翻譯服務。
