### ISSUE TITLE
Please add socks5 proxy setting

### ISSUE THREAD

**Issue by ZeekoZhu** [UnigramDev/Unigram#284]
Using Telegram is not allowed in my country, I can't access Telegram server without Shadowsocks..
Please add proxy settings like Telegram for PC.

**Comment by FrayxRulez** [comment]
Hey! Windows native socket implementation doesn't actually support SOCKS5, so I'm going to close this issue. 

You can try to use the app through a VPN network instead than a proxy.

**Comment by mohsens22** [comment]
@FrayxRulez Sucks ?

**Comment by FrayxRulez** [comment]
Reopening this since we started working on SOCKS5 support: https://github.com/UnigramDev/Unigram/commit/be7a93ce5b42b4c58a6c5bc6ec615b5da94d220a

**Comment by FrayxRulez** [comment]
Proxy has been implemented: https://github.com/UnigramDev/Unigram/commit/d10180f0cf3803993b86c761deb91403c207047c

**Comment by ZeekoZhu** [comment]
Thank you!
