### ISSUE TITLE
This text destroys the app UI on Windows

### ISSUE THREAD

**Issue by sepsol** [UnigramDev/Unigram#2841]
**Describe the bug**
This specific text is rendered outside its parent UI component.

**To Reproduce**
1. Copy this text: Cum
2. Paste it in a chat in Telegram and send it
3. View it on official Telegram clients and compare the results with Unigram
4. See how the text bleeds its parent container on Unigram

**Expected behavior**
The text should be contained inside the parent component.

**Screenshots**
![image](https://user-images.githubusercontent.com/47871887/191440535-8ac44f19-63b7-41ab-8188-b50f40a2bad8.png)
<img width="915" alt="Screen Shot 2022-04-25 at 3 52 55 PM" src="https://user-images.githubusercontent.com/47871887/191441429-8201fb6a-25ad-4ef3-937f-25fc849bbb8b.png">

**Version Info**
 - Unigram: 8.9 (7687) X64
 - Windows: 11 Version 22H2 (OS Build 22621.382)

**Additional context**
N/A

**Comment by FrayxRulez** [comment]
No plans to fix this
