### ISSUE TITLE
Media replace does not work

### ISSUE THREAD

**Issue by luccascomvoce** [UnigramDev/Unigram#2844]
Cannot replace media. Just nothing happens.

1. On any uploaded media, tap Edit
2. Upload new media or edit existing media
3. Confirm
4. Nothing happens

Unigram 9.0  7771
Windows 10 21H2

https://user-images.githubusercontent.com/65538684/191526627-283c6727-88f7-46fd-aa59-ac03c0b1c0a2.mp4

https://user-images.githubusercontent.com/65538684/191526656-3cc2c45f-58cd-4de5-864c-fe27285ba8bc.mp4

**Comment by carlosmg2** [comment]
Ihave just installed Unigram and see the same issue. I can edit a sent media, put can't replace it.

**Comment by luccascomvoce** [comment]
Still reproducible in version 9.0 7796 x64 Windows 10 21H2
