### ISSUE TITLE
Add retry option/button for failed uploads

### ISSUE THREAD

**Issue by jordyamc** [UnigramDev/Unigram#2847]
Sometimes when uploading multiple files there are 1-2 files that fails, the message keeps with loading animation, and if the message has multiple files it doesn't send it, in those cases you need to manually cancel the file and upload it again, it usually resume with the same progress when it failed, it's possible to add an option to manually retry the upload?

**Comment by MarcAnt01** [comment]
Hello, actually from the context menu (right click) there's a retry option. Can you see it?

**Comment by jordyamc** [comment]
No, when the upload fails it only keeps with the uploading animation and only gives the cancel option, maybe the upload fails but the program don't show it like failed?

**Comment by jordyamc** [comment]
![imagen](https://user-images.githubusercontent.com/6831873/192685750-6a04b761-4a81-4206-ad5d-44a0d001957c.png)
Like this, it says failed, but it only gives me the option to delete

**Comment by MarcAnt01** [comment]
> No, when the upload fails it only keeps with the uploading animation and only gives the cancel option, maybe the upload fails but the program don't show it like failed?

This isn't failed upload, but stuck upload. When the upload fails a red flag appears next to it

**Comment by FrayxRulez** [comment]
> This isn't failed upload, but stuck upload. When the upload fails a red flag appears next to it

No, it doesn't.

> Like this, it says failed, but it only gives me the option to delete

If no "Retry" option is available, it means that the upload can't be retried.

**Comment by jordyamc** [comment]
> If no "Retry" option is available, it means that the upload can't be retried.
But why? I have never seen a failed upload with a retry option, the file is fine, I can send the file again and the upload will resume with the same progress it had before, which are the conditions for a file to be retryable?

**Comment by FrayxRulez** [comment]
@jordyamc The real question is: why does the upload fail in the first place? That’s not expected, and I’m not sure it ever happened to me.

**Comment by amirmahdifard** [comment]
@FrayxRulez if you want to expirience this, try to use iran's internet lol

**Comment by FrayxRulez** [comment]
Closing this as stale
