### ISSUE TITLE
Animation bugs in folder settings

### ISSUE THREAD

**Issue by MrFredber** [UnigramDev/Unigram#2849]
**Describe the bug**
Overlaping pictures in animation

**To Reproduce**
1) Open settings
2) Go to "folders" section

**Expected behavior**
Animation with no bugs

**Screenshots**

https://user-images.githubusercontent.com/33953266/192794285-ce029545-cf67-4f69-9ffe-f23b68288559.mp4

**Version Info**
 - Unigram: 9.0 (7771) x64 Direct
 - Windows: Windows 10 21h2 (19044.2075)

**Additional context**

**Comment by FrayxRulez** [comment]
Fixed
