### ISSUE TITLE
No animation in Custom Folders

### ISSUE THREAD

**Issue by MrFredber** [UnigramDev/Unigram#2850]
**Describe the bug**
No animation in Custom Folders

**To Reproduce**

**Expected behavior**
Same animation like in Standart Folders

**Screenshots**

https://user-images.githubusercontent.com/33953266/192795400-5d73a12d-7e8c-46a3-acb6-9c322f532f70.mp4

**Version Info**
 - Unigram: 9.0 (7771) x64 Direct
 - Windows: Windows 10 21h2 (19044.2075)

**Additional context**

**Comment by FrayxRulez** [comment]
Done
