### ISSUE TITLE
Gif flickering on scroll and Gif Empty in search

### ISSUE THREAD

**Issue by Milor123** [UnigramDev/Unigram#2851]
**Describe the bug**
Gif flickering
Gif Empty when in search, black screen (it is not my windows theme)

**To Reproduce**

Gif flickering:

https://user-images.githubusercontent.com/14153649/192893808-b5f2918b-f25f-482d-ba8c-0589696ae246.mp4

Gif Empty when in search:

https://user-images.githubusercontent.com/14153649/192893881-9f31a457-9cf4-4d91-b4bb-c6bfee7521f5.mp4

**Expected behavior**
Dont flickering and search normally the gifs, In many occasions i cant search because appear 2 or 3 gif and the other show as empty

**Version Info**
Unigram 8.9 (7687) X64
Windows 10 x64: 21H2
Tested with GPU RX 6600xt and GTX 1050 ti

**Additional context**

**Comment by FrayxRulez** [comment]
Both should be fixed
