### ISSUE TITLE
Highlighted Search Text After Closing Search

### ISSUE THREAD

**Issue by rei-zero246** [UnigramDev/Unigram#2854]
**To Reproduce**
Steps to reproduce the behaviour:
Perform a search and close the search bar. It does not always happen.

**Describe the bug**
After closing the search bar, there is still highlighted text based on the search criteria.

![image](https://user-images.githubusercontent.com/66904012/194754933-edbab1ad-c88a-4e0a-8461-52574bb145ca.png)

**Expected behaviour**
Upon closing the search bar, there should be no highlighted text.

**Version Info**
Windows 11 22H2
Unigram 9.0 (7780)

**Additional context**

**Comment by MarcAnt01** [comment]
@rei-zero246 thanks for your bug report, but for bugs you need to fill the bug reporting template, while you opened a blank issue

**Comment by rei-zero246** [comment]
> @rei-zero246 thanks for your bug report, but for bugs you need to fill the bug reporting template, while you opened a blank issue

Strange that the template never opened then the way it does now.

**Comment by MarcAnt01** [comment]
Np, the issue is all right now

**Comment by rei-zero246** [comment]
![image](https://user-images.githubusercontent.com/66904012/196652368-439133a1-e200-4877-8943-c1591bce9be2.png)

![image](https://user-images.githubusercontent.com/66904012/196652406-d48aa0b2-7a2c-47cd-866c-af0caf3f0eae.png)

@FrayxRulez

**Comment by FrayxRulez** [comment]
@rei-zero246 Hi, there’s no need to remember us after every single update that an issue has not been worked on. If the issue will be fixed, this will be mentioned here and the ticket will be closed 👍

**Comment by FrayxRulez** [comment]
@rei-zero246 In this case, no updates have been released after the fix was pushed to GitHub.

**Comment by rei-zero246** [comment]
> @rei-zero246 Hi, there’s no need to remember us after every single update that an issue has not been worked on. If the issue will be fixed, this will be mentioned here and the ticket will be closed 👍

Oh sorry.

**Comment by rei-zero246** [comment]
I thought I would still mention I have the problem in the case because the post is closed.

**Comment by FrayxRulez** [comment]
@rei-zero246 It’s ok, no worries, the post gets closed as soon as the code reaches GitHub, but to reach you a new update has to be released
