### ISSUE TITLE
Enhanced Search

### ISSUE THREAD

**Issue by rei-zero246** [UnigramDev/Unigram#2855]
**To Reproduce**
Steps to reproduce the behaviour:

CTRL+F in the chat window or manually selecting the search option and enter criteria for the search.

**Expected behaviour**
The search results should show the criteria only and not produce partial results.

**Describe the bug**
Telegram Desktop and Mobile do not produce meaningful search results generally; I think the web version does a better job. I am saying this to ask for an improved search if possible because the search results from the desktop and mobile are similar to Unigram on Windows.

![image](https://user-images.githubusercontent.com/66904012/194755194-4db183af-5bac-48ac-9ee5-d79e8abbf8cf.png)

In this case, Hebrews is part of the search query, which can be argued, but it is not even highlighted.

There are cases when word is not search but the number. Maybe I am not performing the search properly and there needs to be specific formatting?

**Version Info**
Windows 11 22H2
Unigram 9.0 (7780)

**Additional context**

**Comment by FrayxRulez** [comment]
Search happens on the server, as the app can't download all the messages in a chat to search if they match your query. This is the case for all Telegram apps, including Unigram and Telegram Web.
