### ISSUE TITLE
Add enhanced support for grouping files as album

### ISSUE THREAD

**Issue by tissole** [UnigramDev/Unigram#2859]
In Unigram, if the number of files you upload is 10 as most you can upload them as an album, but if the number exceeds 10 you cannot group files as an album and only send them separated. Please add support for grouping files on an album even if the number of files exceeds 10 like in the official client. 

For example, if you upload 17 files, they are grouped in 2 albums of 10 and 7 files respectively.

**Comment by Gor80hd** [comment]
I would mark it as an bug even. After all, it works in the original clients

**Comment by MarcAnt01** [comment]
> I would mark it as an bug even. After all, it works in the original clients

 Bugs label is for something that does not work as intended, if something has not been implemented it's not a bug

**Comment by NoodlesStamps** [comment]
it would be useful to this feature, especially when uploading large amounts of files

**Comment by Micheeeel111** [comment]
Hopefully one day this feature will be implemented
