### ISSUE TITLE
Uploaded files cannot be accessed after deleting them from device

### ISSUE THREAD

**Issue by tissole** [UnigramDev/Unigram#2862]
**Describe the bug**
After uploading the files as album and delete them from the device, the files cannot be downloaded from chat using Unigram.

**To Reproduce**
- Upload a file.
- Delete the file from the device or move them to another folder.
- Go to chat and access the file.

**Expected behavior**
Users should be able to download files.

**Screenshots**
This is how it looks on Unigram
![Unigram](https://user-images.githubusercontent.com/78413495/194918813-9a06120d-92c8-4755-9f42-c41f07a815b8.png)

**Version Info**
 - Unigram 9.0 (7796) X64 Direct
 - Windows 11 Enterprise Insider Preview 22H2 

**Additional context**
I tried with different type files, mp4, pdf, mp3. I also tried to restart the client, clear cache, same results, cannot access the files. The files cannot be accessed from Unigram, only from the official client, as the screenshot shows. The "save as" doesn't work, neither clicking the files, it does nothing, the files could not be downloaded.

**Comment by Elsayed-A** [comment]
how to get unigram to ask download path for each file

**Comment by MarcAnt01** [comment]
@Elsayed-A please stop spamming support requests, this is not the right place and if it keeps happening, consider that we have the ability to ban you
