### ISSUE TITLE
Reaction Emojis Incorrectly Being Displayed

### ISSUE THREAD

**Issue by rei-zero246** [UnigramDev/Unigram#2863]
**Describe the bug**
Reaction emoji set choice does not display the correct set.

**To Reproduce**
Steps to reproduce the behaviour:
Right-click on a message, expand the emoji sets to see them all, and choose a reaction emoji set.

**Expected behaviour**
Clicking on the reaction emoji set should show the corresponding emojis.

**Screenshots**
![Screenshot 2022-10-09 085441](https://user-images.githubusercontent.com/66904012/195035134-be3df231-7660-4e09-9414-ff6a6eb9393a.png)

![Screenshot 2022-10-09 085404](https://user-images.githubusercontent.com/66904012/195035197-40245330-bd2b-430f-9eee-b43649ca679a.png)

![Screenshot 2022-10-09 085333](https://user-images.githubusercontent.com/66904012/195035236-a0ca5926-eca8-400e-ad59-c7535c318bd0.png)

**Version Info**
 - Unigram 9.0 (7780)
 - Windows 11 22H2

**Additional context**

**Comment by rei-zero246** [comment]
![image](https://user-images.githubusercontent.com/66904012/196650534-48e88464-ab55-4f48-a668-6083cfcb9e76.png)

![image](https://user-images.githubusercontent.com/66904012/196650606-f5109539-ef58-4784-9581-f74a644db4a8.png)

![image](https://user-images.githubusercontent.com/66904012/196650672-39e2947a-c1b4-47d4-b254-a83788160183.png)

![image](https://user-images.githubusercontent.com/66904012/196650746-b7e9ae8b-dcc7-4f17-ad2c-03157ecf08e6.png)

**Comment by FrayxRulez** [comment]
Fixed
