### ISSUE TITLE
Crash when opening a chat

### ISSUE THREAD

**Issue by m-alice** [UnigramDev/Unigram#2864]
**Describe the bug**
Unigram's windows just become non-interactive, freezes on 5..6 seconds, then becomes "solid background color", then just close itself.

**To Reproduce**
1. A new message notification appears
2. You opens the telegram
3. Click on chat, where a new message is
4. This happens

**Screenshots**
-

**Version Info**
 - Unigram: 9.0.7778 x64
 - Windows: 2004 19041.1348

**Additional context**
I want to attach windows events report, but it contents sensitive information (e-mail). How i can securely send it to the devs?

**Comment by FrayxRulez** [comment]
Does this happen in a specific chat?

**Comment by m-alice** [comment]
> Does this happen in a specific chat?
Any, random chat.

**Comment by FrayxRulez** [comment]
Would be good to have a crash dump

**Comment by MarcAnt01** [comment]
Does this still happen?
