### ISSUE TITLE
Can't be used for 22h2?

### ISSUE THREAD

**Issue by treemoons** [UnigramDev/Unigram#2866]
-  My computer's info(SURFACE PRO 7 16G)
-  Windows version: Windows11 professional 22h2 22621.674 

-  The software which had downloaded from Mircosoft store was opened ,status:
 1. Can't click any button(proxy settings,back icons and login using your phone)
 2. Can't show any else form,just the only one broken window
![](http://m.qpic.cn/psc?/V51Og77M2Y10vs1mExf44Ec5tc1LehAT/bqQfVz5yrrGYSXMvKr.cqXFXMqhga*lqZ3t6mmk2Ut5VFfKSd9FPyCF2Z1a383P3aJ19OG4RMFJtK1jSaJ6Tvxh6LkQ*.l0S9IkAdAMaucg!/b&bo=rwU4BAAAAAADF6Q!&rf=viewer_4)

 When it was maximumed:
![](http://m.qpic.cn/psc?/V51Og77M2Y10vs1mExf44Ec5tc1LehAT/bqQfVz5yrrGYSXMvKr.cqUG5RsoN3X1vhJ3foUxfwYMk1Bf9U2WHQdB7s05uIhZswI6Xd3oXVKMDGYkgyvGYED24nLJS3Rt1VrNlDk7Gz1M!/b&bo=UwY4BAAAAAADB0s!&rf=viewer_4)

**Comment by LeonWong0609** [comment]
+1 same here, 22h2
