### ISSUE TITLE
OBS virtual camera not shown in the Cameras list

### ISSUE THREAD

**Issue by piskov** [UnigramDev/Unigram#2868]
**Describe the bug**
OBS Studio allows to share anything as Virtual Camera. This virtual camera is not shown in the sources list of Unigram (but is shown anywhere from Telegram to Skype).

**To Reproduce**
1. Go to OBS
2. Click on Start Virtual Camera
3. Open Unigram and call someone.
4. OBS Virtual Camera is not shown in the video sources list.

**Expected behavior**
Show OBS Virtual Camera as one of the sources.

**Version Info**
 - Unigram: 9.0 (7796)
 - Windows: Windows 11 Pro N 22H2 22621.674

**Additional context**

While I’m at it: it would be great to show call settings (mic and video sources) in app settings. Currently you have access to those only while calling someone (which makes it harder to debug and change without asking the caller to wait).

Why is this useful: I use external pro video camera, shoot in HLG3 and apply LUT to correct the colors inside OBS. Then I “stream” the final picture as virtual camera source that can be used in any program expecting simple webcam.

**Comment by FrayxRulez** [comment]
Virtual cameras are not compatible with the framework used to build Unigram and Microsoft said that they have no plans to support them any time in the future
