### ISSUE TITLE
Unable to react with the heart reaction specifically

### ISSUE THREAD

**Issue by xezrunner** [UnigramDev/Unigram#2869]
**Describe the bug**
Clicking/tapping on the heart react in any state of the reactions tray yields no results. The reaction does not register.

**To Reproduce**
1. Right-click or long press on a message.
2. Try clicking/tapping the heart reaction.

**Expected behavior**
The reaction should be registered, just like other reactions.

**Screen recordings**

https://user-images.githubusercontent.com/8061077/196225978-9eda363d-cd2b-4cb1-b1a5-fe46e8fd100d.mp4

**Version Info**
 - Unigram: 9.0 (7802) x64
 - Windows: 11 Insider Preview 22H2 Dev Channel (25217.1010)

**Additional context**
Most users do not seem to have this issue. This might be a one-off bug, perhaps something went wrong during an app update?

**Comment by MarcAnt01** [comment]
Merging with #2872 that is a bit more general compared to this one. Thanks for reporting
