### ISSUE TITLE
Modifications to the custom themes are not saved after closing the client

### ISSUE THREAD

**Issue by tissole** [UnigramDev/Unigram#2874]
**Describe the bug**
I created a custom theme and I modified some colors in GUI. I saved them all, and they were applied, but after restarting the client they were lost,

**To Reproduce**
Go to Settings, Appearance and create a new theme. Modify some colors on different elements. Save the modifications and restart the client.

**Expected behavior**
Modifications should be kept after restart.

**Screenshots**
The GUI modified
![1](https://user-images.githubusercontent.com/78413495/196642771-fcf5593c-6528-46e8-8ca6-24c6b60c4c8b.png)

After the restart

![2](https://user-images.githubusercontent.com/78413495/196642799-62b5b098-6ab2-42b1-9736-448b72cb31fe.png)

**Version Info**
 - Unigram: 9.0 7802 X64 Direct
 - Windows: 11 Enterprise 22H2

There is an easy way to modify the theme? I find very difficult to guess the visual elements after their names. It is more trial and error because the names are not always revealing. There is a guide somewhere? I'm interested to change the background color of the folder tabs and the color of those icons.

**Comment by FrayxRulez** [comment]
To save changes to the theme you must click on the ✔️ Done button.
No, there's not guide nor better UX to edit the themes :/
