### ISSUE TITLE
Automatic Spelling

### ISSUE THREAD

**Issue by x011** [UnigramDev/Unigram#2875]
**Version Info**
 - Unigram: 9.0 (7797) x64
 - Windows

Automatic Spelling was present on  the last version but now is gone. How can I enable it?

**Comment by FrayxRulez** [comment]
Spellcheck is provided by the system and can be disabled from app Settings > Appearance > Disable misspelled words highlight.
It can't be forcefully enabled by the app if the system doesn't provide it.
System options for this can be found in System settings > Time & language > Typing.
