### ISSUE TITLE
Feature request: Live streams in chats and channels

### ISSUE THREAD

**Issue by jag-k** [UnigramDev/Unigram#2876]
Hi, what about a live streams like in original Telegram?

- In channels:
  - With custom stream app: 
     ![Stream with other app pop-up from original Telegram app](https://user-images.githubusercontent.com/30597878/197117422-7fd7bedb-ec4f-4770-8113-7b7176c19b9e.png)
  - Select menu of stream options:
    ![Select menu of stream options dropdown in original Telegram app](https://user-images.githubusercontent.com/30597878/197117587-6b7a01d2-b33d-448a-bcad-7f5d3d2018ac.png)

- In chats:
  - In video/audio call:
     ![Screencast button then calling in original Telegram app](https://user-images.githubusercontent.com/30597878/197117819-435ada8e-6b0e-4370-8064-fe56703a7b49.png)

**Comment by makisukurisu** [comment]
This feature is present in Unigram:
![image](https://user-images.githubusercontent.com/49622129/197118794-ddb071f9-f498-4b41-a605-3584632c7a79.png)

(For some reason accounts haven't loaded 🤷 )
