### ISSUE TITLE
Video calls do not work

### ISSUE THREAD

**Issue by Arpolend** [UnigramDev/Unigram#2878]
**Describe the bug**
The call UI becomes unresponsive every time after making the connection. Neither sound nor video get through although camera indicator does turn on.

**To Reproduce**
1. Make any video call
2. The call UI becomes unresponsive
3. The timer does start
4. Neither sound nor video get through, the preview is black

**Expected behavior**
Video calls should work :)

**Screenshots**

**Version Info**
 - Unigram: 9.0.7803 ARM64
 - Windows: 22621

**Additional context**

**Comment by MarcAnt01** [comment]
Hello @Arpolend are you referring to individual or group calls?

**Comment by Arpolend** [comment]
I checked only individual. Probably neither

**Comment by MarcAnt01** [comment]
There have been some fixes regarding videocalls in the recent weeks. Could you confirm this is still the case?

**Comment by Arpolend** [comment]
Seems fixed, thx
