### ISSUE TITLE
Clear chat history not always working

### ISSUE THREAD

**Issue by mateiradu** [UnigramDev/Unigram#288]
When using right mouse button > Clear history, history is always cleared locally but not always on other devices.

1. Right click on a 1-on-1 chat
2. Select "Clear history"
3. Confirm action by clicking "Delete"
4. Notice that on other clients the history _might_ not get cleared

Here is a screenshot, Unigram on left side, Telegram Desktop on the right:
![2017-05-31 13_31_29-](https://cloud.githubusercontent.com/assets/1713151/26630253/35ca2a0a-4606-11e7-81f6-5e770417eacb.png)

The bottom two were cleared on both Android and web clients, but the top most chat was cleared only for the Unigram instance.

This event happened other two times doing these same steps.

My configuration:
Unigram build: 0.2.157.0
Windows build: 15063.296 Desktop

**Comment by gmy77** [comment]
Same here 

Telegram Desktop 3.8.2437
Windows 10 (Latest release) no INSIDER PROGRAM ACTIVATED.

1) Delete Chronology
2) Leave Channel

but any time i start Unigram, i add my personal code, i re-find the same things i delete latest time.
