### ISSUE TITLE
Support Telegram's tg link

### ISSUE THREAD

**Issue by WindowsRegedit** [UnigramDev/Unigram#2883]
Like the title,I like Unigram's theme.But I got annoyed when I received telegram's invite link and need to first open in the telegram web than into unigram.I think it's not convenient.So I hope unigram can add this link.

**Comment by MarcAnt01** [comment]
Not sure about what you're talking about. If you receive any invite link from the browser or any other program running in your device you should be able to open it through Unigram

**Comment by FrayxRulez** [comment]
Unigram already handles both tg protocol and t.me links
