### ISSUE TITLE
Unigram crashes on start

### ISSUE THREAD

**Issue by Knantro** [UnigramDev/Unigram#2887]
**Describe the bug**
When I try to start Unigram, it crashes, but Unigram still work until authorization.

**To Reproduce**
1. Start Unigram
2. Authorize in your any account
3. It crashes and closes.

**Expected behavior**
Unigram don't closes and get

**Version Info**
 - Unigram: 9.0.7863.0 x64
 - Windows: 10.0.19042

**Additional context**
I know this problem has already been discussed, but it didn't help me

**Comment by FrayxRulez** [comment]
@Knantro This problem has not been discussed

**Comment by Knantro** [comment]
@FrayxRulez Hmm, I've already seen the same issues, but the solutions there didn't help me

**Comment by FrayxRulez** [comment]
@Knantro If you seen the same issue it would be a good practice to comment there, instead of opening a new ticket.
Anyway, I'm not aware of this issue and I can't reproduce this.

**Comment by Knantro** [comment]
@FrayxRulez They are all closed and I thought it was worth creating a new one.

Can I provide any necessary data? Maybe I can find logs somewhere? I couldn't find them on my own.

**Comment by FrayxRulez** [comment]
@Knantro The file "tdlib_logs.txt" could give an hint about what the problem is, if it doesn't I will ask for further info. You can find logs in %LOCALAPPDATA%\Packages\38833FF26BA1D.UnigramPreview_g9c9v27vpyspw\LocalState

**Comment by Knantro** [comment]
@FrayxRulez 

```
[ 1][t 0][1667807158.342664480][Logging.cpp:152][&client]	Unhandled exception:
System.Exception: Неопознанная ошибка (Exception from HRESULT: 0x80004005)
[ 1][t 5][1667807160.845980167][Td.cpp:3153][#1][!Td][&td_init]	Create Global
[ 1][t 5][1667807160.852845907][Td.cpp:4102][#1][!Td][&td_init]	Begin to set TDLib parameters
[ 1][t 5][1667807160.852881669][Td.cpp:4079][#1][!Td][&td_init]	Fix files_directory
[ 1][t 5][1667807160.852887392][Td.cpp:4083][#1][!Td][&td_init]	Fix use_chat_info_db
[ 1][t 5][1667807160.852891206][Td.cpp:4087][#1][!Td][&td_init]	Fix use_file_db
[ 1][t 5][1667807160.852894783][Td.cpp:4124][#1][!Td][&td_init]	Create MtprotoHeader::Options
[ 1][t 5][1667807160.852907896][Td.cpp:2995][#1][!Td][&td_init]	Begin to open database
[ 1][t 1][1667807160.853818893][TdDb.cpp:404][#1][!RunOnSchedulerWorker][&td_init]	Start binlog loading
[ 1][t 1][1667807160.858741521][TdDb.cpp:407][#1][!RunOnSchedulerWorker][&td_init]	Finish binlog loading
[ 1][t 1][1667807160.858754634][TdDb.cpp:410][#1][!RunOnSchedulerWorker][&td_init]	Finish initialization of binlog PMC
[ 1][t 1][1667807160.858758449][TdDb.cpp:412][#1][!RunOnSchedulerWorker][&td_init]	Finish initialization of config PMC
[ 1][t 1][1667807160.858768224][TdDb.cpp:438][#1][!RunOnSchedulerWorker][&td_init]	Start to init database
[ 1][t 1][1667807160.862131834][TdDb.cpp:441][#1][!RunOnSchedulerWorker][&td_init]	Finish to init database
[ 1][t 1][1667807160.862143993][TdDb.cpp:455][#1][!RunOnSchedulerWorker][&td_init]	Create concurrent_binlog_pmc
[ 1][t 1][1667807160.862150907][TdDb.cpp:460][#1][!RunOnSchedulerWorker][&td_init]	Create concurrent_config_pmc
[ 1][t 1][1667807160.862159252][TdDb.cpp:470][#1][!RunOnSchedulerWorker][&td_init]	Create concurrent_binlog
[ 1][t 1][1667807160.862170696][TdDb.cpp:473][#1][!RunOnSchedulerWorker][&td_init]	Init concurrent_binlog_pmc
[ 1][t 1][1667807160.862218141][TdDb.cpp:475][#1][!RunOnSchedulerWorker][&td_init]	Init concurrent_config_pmc
[ 1][t 5][1667807160.862267971][Td.cpp:3577][#1][!Td][&td_init]	Successfully inited database
[ 1][t 5][1667807160.862288713][Td.cpp:3719][#1][!Td][&td_init]	Create StateManager
[ 1][t 5][1667807160.862322330][Td.cpp:3736][#1][!Td][&td_init]	Create OptionManager
[ 1][t 5][1667807160.862512588][Td.cpp:3752][#1][!Td][&td_init]	Create ConnectionCreator
[ 1][t 5][1667807160.862567424][Td.cpp:3742][#1][!Td][&td_init]	Create TempAuthKeyWatchdog
[ 1][t 5][1667807160.862576723][Td.cpp:3746][#1][!Td][&td_init]	Create ConfigManager
[ 1][t 5][1667807160.862666606][Td.cpp:3605][#1][!Td][&td_init]	Create NetQueryDispatcher
[ 1][t 5][1667807160.863697767][Td.cpp:3614][#1][!Td][&td_init]	Create AuthManager
[ 1][t 5][1667807160.863743543][Td.cpp:3787][#1][!Td][&td_init]	Create FileManager
[ 1][t 5][1667807160.863798856][Td.cpp:3853][#1][!Td][&td_init]	Create Managers
[ 1][t 5][1667807160.865895271][Td.cpp:3628][#1][!Td][&td_init]	Send binlog events
[ 1][t 5][1667807160.865931034][Td.cpp:3699][#1][!Td][&td_init]	Ping datacenter
[ 1][t 5][1667807160.866043329][Td.cpp:3710][#1][!Td][&td_init]	Finish initialization
[ 1][t 5][1667807160.866051673][Td.cpp:3554][#1][!Td][&td_init]	Continue to execute 2 pending requests
```

**Comment by Evengard** [comment]
Having same problem. Weird thing - it started not immediately after updating, but after a while - I guess until some weird message or smth was sent to me. When resetting the app, I can scan the QR code to login, but when it pulls my messages from the server - it crashes again. And keeps crashing on restart.

Feels like it can't process something from the server and crashes.

**Comment by FrayxRulez** [comment]
@Evengard What’s the app version?

**Comment by Knantro** [comment]
@FrayxRulez Good evening, I'm sorry, but do you know anything about my problem? Is it possible to solve this somehow, or maybe additional data is needed?

**Comment by Evengard** [comment]
> @Evengard What’s the app version?

9.1.7877.0 as reported by MS Store...
Weird, just got an update from MS Store, the version seems to be not changed, yet the bug seems to gone?

**Comment by FrayxRulez** [comment]
Still happening?

**Comment by cpCr4zy** [comment]
I have the same problem. App crashes on start. 
Unigram: 9.0.7840.0 x64 (installed from Unigram_9.0.7840.0_x64.msixbundle)
Windows: 10 21H2

Log:

[ 1][t 5][1670008116.737766981][Td.cpp:3153][#1][!Td][&td_init]	Create Global
[ 1][t 5][1670008116.740650892][Td.cpp:4102][#1][!Td][&td_init]	Begin to set TDLib parameters
[ 1][t 5][1670008116.740668058][Td.cpp:4079][#1][!Td][&td_init]	Fix files_directory
[ 1][t 5][1670008116.740670680][Td.cpp:4083][#1][!Td][&td_init]	Fix use_chat_info_db
[ 1][t 5][1670008116.740672826][Td.cpp:4087][#1][!Td][&td_init]	Fix use_file_db
[ 1][t 5][1670008116.740674972][Td.cpp:4124][#1][!Td][&td_init]	Create MtprotoHeader::Options
[ 1][t 5][1670008116.740682125][Td.cpp:2995][#1][!Td][&td_init]	Begin to open database
[ 1][t 1][1670008116.741255044][TdDb.cpp:404][#1][!RunOnSchedulerWorker][&td_init]	Start binlog loading
[ 1][t 1][1670008116.743723630][TdDb.cpp:407][#1][!RunOnSchedulerWorker][&td_init]	Finish binlog loading
[ 1][t 1][1670008116.743741273][TdDb.cpp:410][#1][!RunOnSchedulerWorker][&td_init]	Finish initialization of binlog PMC
[ 1][t 1][1670008116.743744134][TdDb.cpp:412][#1][!RunOnSchedulerWorker][&td_init]	Finish initialization of config PMC
[ 1][t 1][1670008116.743751049][TdDb.cpp:438][#1][!RunOnSchedulerWorker][&td_init]	Start to init database
[ 1][t 1][1670008116.751341819][TdDb.cpp:441][#1][!RunOnSchedulerWorker][&td_init]	Finish to init database
[ 1][t 1][1670008116.751352310][TdDb.cpp:455][#1][!RunOnSchedulerWorker][&td_init]	Create concurrent_binlog_pmc
[ 1][t 1][1670008116.751387834][TdDb.cpp:460][#1][!RunOnSchedulerWorker][&td_init]	Create concurrent_config_pmc
[ 1][t 1][1670008116.751394033][TdDb.cpp:470][#1][!RunOnSchedulerWorker][&td_init]	Create concurrent_binlog
[ 1][t 1][1670008116.751399517][TdDb.cpp:473][#1][!RunOnSchedulerWorker][&td_init]	Init concurrent_binlog_pmc
[ 1][t 1][1670008116.751401901][TdDb.cpp:475][#1][!RunOnSchedulerWorker][&td_init]	Init concurrent_config_pmc
[ 1][t 5][1670008116.751431226][Td.cpp:3577][#1][!Td][&td_init]	Successfully inited database
[ 1][t 5][1670008116.751447916][Td.cpp:3719][#1][!Td][&td_init]	Create StateManager
[ 1][t 5][1670008116.751468896][Td.cpp:3736][#1][!Td][&td_init]	Create OptionManager
[ 1][t 5][1670008116.751596927][Td.cpp:3752][#1][!Td][&td_init]	Create ConnectionCreator
[ 1][t 5][1670008116.751624822][Td.cpp:3742][#1][!Td][&td_init]	Create TempAuthKeyWatchdog
[ 1][t 5][1670008116.751629114][Td.cpp:3746][#1][!Td][&td_init]	Create ConfigManager
[ 1][t 5][1670008116.751679897][Td.cpp:3605][#1][!Td][&td_init]	Create NetQueryDispatcher
[ 1][t 5][1670008116.752239704][Td.cpp:3614][#1][!Td][&td_init]	Create AuthManager
[ 1][t 5][1670008116.752261400][Td.cpp:3787][#1][!Td][&td_init]	Create FileManager
[ 1][t 5][1670008116.752289295][Td.cpp:3853][#1][!Td][&td_init]	Create Managers
[ 1][t 5][1670008116.759969234][Td.cpp:3628][#1][!Td][&td_init]	Send binlog events
[ 1][t 5][1670008116.759994745][Td.cpp:3699][#1][!Td][&td_init]	Ping datacenter
[ 1][t 5][1670008116.760071039][Td.cpp:3710][#1][!Td][&td_init]	Finish initialization
[ 1][t 5][1670008116.760075569][Td.cpp:3554][#1][!Td][&td_init]	Continue to execute 1 pending requests
[ 0][t 5][1670008116.760245561][LogEvent.h:137][#1][!NetStatsManager][&version() < static_cast<int32>(Version::Next)]	Wrong version 43

**Comment by FrayxRulez** [comment]
@cpCr4zy This is because you downgraded your app, using the latest version would solve the issue.

**Comment by Knantro** [comment]
My problem is solved! Thanks for more!
