### ISSUE TITLE
Cannot paste/send a presumably long message into group chat

### ISSUE THREAD

**Issue by roman380** [UnigramDev/Unigram#289]
The message was around 4200 characters long. Pasted into group, it showed as accepted but status icon kept showing clock. Later I realized it was not seen by anyone else. I retried, with the same result. When pasted via Telegram Desktop, the message was split automatically, and last paragraph was sent as a separate message. This way it worked well.

**Comment by FrayxRulez** [comment]
Reminder (for me): message max length is `4096`

**Comment by FrayxRulez** [comment]
This is fixed in Unigram X
