### ISSUE TITLE
@gif no longer working

### ISSUE THREAD

**Issue by horrorslice** [UnigramDev/Unigram#2897]
**Describe the bug**
Unable to search for gifs using the @gif operator

**To Reproduce**
1. Go to any chat
2. Type @gif 
3. Add search text

**Expected behavior**
Typing @gif and adding a search phrase after pulls up gifs to add to chat

**Screenshots**
![Bug 1](https://user-images.githubusercontent.com/18153431/201486008-884d1228-83fd-47a6-83fe-b7d8310b22bb.png)
![Bug 2](https://user-images.githubusercontent.com/18153431/201486010-358ad947-9227-4a53-8313-4886e8a257cc.png)

**Version Info**
 - Unigram: 9.1 (7877) x64
 - Windows: Windows 11 Home, 22H2, 22621.819 

**Additional context**
I solely use @gif for sending gifs in a chat, but starting yesterday I believe it no longer appears to function. 

My apologies. I tried to look for a template for submitting it, but I missed it apparently. I updated the main post, hopefully it's correct now. :)

**Comment by Marocco2** [comment]
Neither @vid or any inline-bot as far as I'm aware

**Comment by makisukurisu** [comment]
Please, use template for reporting bugs.

If you are not going to recreate this one - please, provide details in a reply, or initial message (hit ... button, choose edit)
Things like Unigram version, Windows version, etc. are crucial for bug-fixing.

(You can copy-paste template and fill in the details from "New issue"=>"Bug Report", or create a new one using same template)

**Comment by MarcAnt01** [comment]
It looks like all inline bots that require a text input from the typing textbox are not working
@horrorslice as a workaround you can go in the gifs panel and perform the search from there. The returned results are the same

**Comment by MarcAnt01** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/b5d936fa6b9bcfa5fb8566d991fbf2793c7c8f13
