### ISSUE TITLE
RTL: Close button and back button overlap

### ISSUE THREAD

**Issue by mrg0lden** [UnigramDev/Unigram#2898]
**Describe the bug**
The 3 windows buttons overlap with Unigram's back button.
![image](https://user-images.githubusercontent.com/8347078/201608577-0e676826-b6f5-491f-ad94-c152f800937a.png)

And this is the other side where Unigram's name is
![image](https://user-images.githubusercontent.com/8347078/201608649-792ae47b-f0db-4052-ba7c-6344cbb88079.png)

**To Reproduce**
1. Have a Window Version with an RTL language e.g. Arabic (install or change the language of an existing installation)
2. Install Unigram
3. Log in
4. Open Settings
5. Hover over the close button

**Expected behavior**
The button should be on the right in this case, I guess?

**Screenshots**
Attached above

**Version Info**
 - Unigram: 9.1 (7877) x64
 - Windows: 11 22H2 22621.819 (Arabic)

**Additional context**
I don't have any, but if you need any more info I'll be happy to provide them.

Thank you for your efforts, this app is truly great.

**Comment by FrayxRulez** [comment]
This was fixed
