### ISSUE TITLE
Unigram crashes when sending voice messages.

### ISSUE THREAD

**Issue by ThiagoGamer2007** [UnigramDev/Unigram#2902]
When you try to send a voice message that you were already recording, the app crashes and there is no other way to fix it than to reinstall it completely.
**To Reproduce**
1. Go to a chat.
2. press ctrl+r
3. say hi!
4. press ctrl+r again.
Done!
**Version Info**
Unigram latest, 9.0, windows 11 22h2 22621819

**Comment by FrayxRulez** [comment]
This was fixed!
