### ISSUE TITLE
Unable to find and install Unigram in Microsoft Store China

### ISSUE THREAD

**Issue by staoran** [UnigramDev/Unigram#2904]
![image](https://user-images.githubusercontent.com/7844538/203327159-66d6e7c2-4e01-433c-ba77-2fd36cb5d229.png)
There is no Get button in my region.

![image](https://user-images.githubusercontent.com/7844538/203328439-e9641725-cecc-453a-81be-12d69e7cd41b.png)
Is this a limitation of Microsoft? Can Unigrams be uploaded to Winget if Microsoft's policy is irresistible.

winget search unigram Hint: No package found that matches the entered criteria.

**Comment by makisukurisu** [comment]
Hey there, you can use packages from [unigramappx](https://t.me/unigramappx), they have an auto-update feature, so it's pretty comfortable.

**Comment by staoran** [comment]
Thanks, I installed it from here.
Just the Microsoft Store or winget would make the first-time install experience a lot friendlier.😁

> Hey there, you can use packages from [unigramappx](https://t.me/unigramappx), they have an auto-update feature, so it's pretty comfortable.
