### ISSUE TITLE
Add icon of secret chat when fordwarding message

### ISSUE THREAD

**Issue by Aokromes** [UnigramDev/Unigram#2909]
when fwarding i have one contact with secret chat on 2 devices and a non secret chat, idk witch of the 3 is a secret chat, can you add lock icon there? :)

**Comment by MarcAnt01** [comment]
Thanks for opening this ticket, but there's already a similar ticket

**Comment by MarcAnt01** [comment]
Duplicate of https://github.com/UnigramDev/Unigram/issues/889

**Comment by Aokromes** [comment]
oh i opened because fela told me xd
