### ISSUE TITLE
Clicking directly on the menu button did not work

### ISSUE THREAD

**Issue by Mabisi** [UnigramDev/Unigram#2912]
**Describe the bug**

**To Reproduce**

**Expected behavior**
### **Sorry, my English is not very good, please see GIF**
**Screenshots**
![(20221205)19 00 34](https://user-images.githubusercontent.com/19968269/205622617-620b5e47-5ade-46c6-b68b-355ec51914f5.gif)

**Version Info**
###  - Unigram: [v9.2.7931 x64]
 - Windows: [e.g. October 2018 update]

**Additional context**

**Comment by makisukurisu** [comment]
As a temporary solution - enter / on your keyboard. I guess the fix will be available soon :thinking:
