### ISSUE TITLE
Add post count to "delete all" option of dialog that appears when group administrator right-clicks "Delete" on a group message

### ISSUE THREAD

**Issue by jb-20-a11y** [UnigramDev/Unigram#2913]
If an administrator of a Telegram group right-clicks a specific message in that group and chooses the "Delete" option, a dialog appears in Unigram with three checkboxes of additional options from which the administrator may choose: Ban user, Report as spam, and Delete all messages from that user inside the group. While the mobile Telegram client appears to mirror this behavior, the desktop version of the Telegram client also displays the number of posts made by that user in the group next to the "Delete all" checkbox in that dialog. This feature request is to add that equivalent functionality to Unigram.

**Comment by FrayxRulez** [comment]
Done
