### ISSUE TITLE
Chat theme resets when opened in a new window.

### ISSUE THREAD

**Issue by valsoray-dev** [UnigramDev/Unigram#2917]
**Describe the bug**
When I open a chat in a new window, the chat theme is resets until I click on the chat info and return.

**To Reproduce**
1. Right-click on the chat.
2. Select “Open in new window”.
3. See a different background.

**Expected behavior**
The chat theme should be the same as in the main window.
This is fixed by following these steps:
1. In the new window, click on the name of the chat.
2. Press the back button (Esc).

**Screenshots**
![image](https://user-images.githubusercontent.com/77742707/206666022-6fffe8cc-d72b-4190-b0a8-72871de0ee48.png)

**Version Info**
 - Unigram: 9.2 (7947) X64 Direct
 - Windows: 11 Pro 22623.1028

**Comment by makisukurisu** [comment]
Can I ask you to see if this is still applicable in latest version of Unigram (9.3 7967 at the moment)

I could not reproduce this issue.

**Comment by makisukurisu** [comment]
![image](https://user-images.githubusercontent.com/49622129/213724964-edf72718-79db-4876-8ddb-8bb67d03c2a4.png)

Just to clarify:
Seemingly same pink-orange-yellow background works no problem - it'll be shown right away if you open a new widow.
But the one with an X on it does not apply properly (if you tweak settings - they won't matter after you hit "Set" button - it'll still show you "default" preset)

**Comment by FrayxRulez** [comment]
This seems to be fixed to me
