### ISSUE TITLE
Glitched groups with topics

### ISSUE THREAD

**Issue by punteroanull** [UnigramDev/Unigram#2918]
Since telegram released this new feature, some groups with topics are unable to interact with. It doesn't show the different topics and there is a message with "slide to left to reply someone". 

One screenshot is from Unigram and the other one from Telegram Desktop

![telegrambug]
(https://user-images.githubusercontent.com/94837530/208253654-c535c0be-718a-41e9-90c2-5f9e328bbfb6.png)
![telegramok]
(https://user-images.githubusercontent.com/94837530/208253768-7f836e1e-13d0-4a21-9ef5-f485cbffcbab.png)

**Comment by OneCrazyRussian** [comment]
Since the 9.3 update groups with topics can be "opened" even though they don't show any topics and now they don't even let you read the messages (before the update you'd see them as a single chat - with no ability to reply or post)
![image](https://user-images.githubusercontent.com/3639846/210406007-a92f0636-a7d9-4a57-afaf-b77f9aea8cc3.png)

**Comment by SOI7** [comment]
Apparently this issue happens only in Dark mode, although the group doesn't remove the unread messages badge and if you write something it keeps the message as a raw

**Comment by makisukurisu** [comment]
Please update your app and tell if you still have this problem

**Comment by punteroanull** [comment]
As @SOI7 said, the bug is still present in Dark Mode. Also, I'm not able to read message from this chat (the original chat group which splited in topics later), again, one pic is from Unigram another one from Telegram:
![imagen](https://user-images.githubusercontent.com/94837530/212754828-1e0d6678-c9b6-41ce-b659-7f9d4bff8a08.png)
![imagen](https://user-images.githubusercontent.com/94837530/212755140-a189fb7e-03e9-40d2-9d5a-6477e11bce8a.png)

**Comment by makisukurisu** [comment]
I'd consider closing this issue and opening a new one for General topic specifically, because now it doesn't depend on theme (and Topics are shown in the app).

But, I guess it's up to Fela to decide.

**Comment by punteroanull** [comment]
> I'd consider closing this issue and opening a new one for General topic specifically, because now it doesn't depend on theme (and Topics are shown in the app).
> 
> But, I guess it's up to Fela to decide.

Dunno, topics aren't shown in the app in Dark Mode (it doesn't display any topic at all, if you click in some of the supposed invisible topics, Unigram changes to another conversation), so the original bug is still here. But yes, I'm agree with you, General Topic could be a different issue.
![imagen](https://user-images.githubusercontent.com/94837530/212755920-ea6911d8-b7d2-453a-9125-b747a33a6362.png)

**Comment by makisukurisu** [comment]
@punteroanull , perhaps you have Microsoft Store release?

There was recently an update for Direct users of Unigram (v 7967), which resolved issue with dark theme. If you still have this issue with this version - please, let us know.

Microsoft Store users will get this fix/update later (Fela may give some details on this matter)

**Comment by punteroanull** [comment]
@makisukurisu yep, once again, you're right. I'm using the MS release. I guess I will have to wait to test ^^
