### ISSUE TITLE
(REQUEST) Change Temp folder

### ISSUE THREAD

**Issue by CrazyBytesVE** [UnigramDev/Unigram#2919]
Great app. Is there a way to change the path of the temporary files when downloading files? Change them from appdata to another location? Because I use SSD disk and constantly writing information degrades it

**Comment by makisukurisu** [comment]
You can change downloads location like this:
![image](https://user-images.githubusercontent.com/49622129/212756203-bcf796cc-440f-48d7-b16f-ec610372a727.png)

(Open settings, Data and Storage, go to "Storage Path" option and select a location you like)


However this can, and most likely will bring some pesky bugs with media previews or some other of Unigram.
As far as I know - nothing critical. But if you find something that directly affects your experience with the app - please, report it there.
