### ISSUE TITLE
UnigramBridge.exe not running as ARM64

### ISSUE THREAD

**Issue by matze19999** [UnigramDev/Unigram#2922]
UnigramBridge is running as x86 on my SPX.

Are there any plans to make it run native on ARM64?

![image](https://user-images.githubusercontent.com/13684520/209476449-be62c23c-4a19-4f15-9822-cfda3a677d8f.png)

**Comment by AbyssallArmy884** [comment]
Kenapa tidak bisa

**Comment by FrayxRulez** [comment]
The stub process is actually compiled as Any CPU at the moment...

**Comment by FrayxRulez** [comment]
Also, considering that even the equivalent process for the Microsoft Store is the same... 😁
