### ISSUE TITLE
Support Japanese language for Unigram

### ISSUE THREAD

**Issue by onein528** [UnigramDev/Unigram#2925]
# Description

As the title

# Motivation

This is the milestone for supporting Japanese. This will be achieved by creating a new PR

**Comment by makisukurisu** [comment]
@onein528 Since Unigram uses Android language pack - you can improve (currently) beta translation, or add it as is:

https://translations.telegram.org/ja/?start=1

**Comment by MarcAnt01** [comment]
Thanks for your interest, please follow @makisukurisu 's suggestion. A PR would not be merged, since all the languages packs come from Android language packages.
