### ISSUE TITLE
Markdown strikethroughs don't work right on Unigram

### ISSUE THREAD

**Issue by CLCK0622** [UnigramDev/Unigram#2927]
**Describe the bug**
The strikethrough lines of Markdown aren't aligned center on a message. 

**To Reproduce**
1. Go to any talks
2. Enter `~~1111~~`
3. Send the message

**Screenshots**
![image](https://user-images.githubusercontent.com/36215258/210223293-382de1ca-f58e-4b8a-9332-27c47857458b.png)

**Version Info**
 - Unigram: Newest one
 - Windows 11

**Comment by FrayxRulez** [comment]
This is by design

**Comment by aeilot** [comment]
But I'm afraid [the official Telegram client](https://desktop.telegram.org/) shows the strikethroughs in a way that is different from that shown in Unigram. And I'm not sure if this is their design.

Taking the macOS client as an example, 

<img width="175" alt="Screen Shot 2023-01-02 at 7 21 56 PM" src="https://user-images.githubusercontent.com/25583228/210224714-b37e6585-a10b-4e2f-b1f4-de308096caa1.png">

Shown above is what `~~1111~~` looks like on the official Telegram client, where the strikethrough is vertically centered.

**Comment by FrayxRulez** [comment]
@aeilot The strikethrough line position  and thickness is provided by the font itself, so it’s by design.

**Comment by FrayxRulez** [comment]
@FrayxRulez This is because different position can affect the font readability, and supposedly the one provided by the font is optimized for the readability of the font itself.

**Comment by CLCK0622** [comment]
> @FrayxRulez This is because different position can affect the font readability, and supposedly the one provided by the font is optimized for the readability of the font itself.

Gotcha. Many thanks for your explanation.

**Comment by aeilot** [comment]
> @FrayxRulez This is because different position can affect the font readability, and supposedly the one provided by the font is optimized for the readability of the font itself.

Alright, I see. Thank you for the timely replies.
