### ISSUE TITLE
UNIGRAM - SECRET CHAT - "EMPTY" when sending files

### ISSUE THREAD

**Issue by Jonathanarielarg** [UnigramDev/Unigram#2929]
when I send file via secret chat, the other person only recieve a word: "EMPTY" insted of the file to open or download. In regular chat the files came ok yo the other person, the problem is in secret chats.

**Comment by Jonathanarielarg** [comment]
sorry, unigram 9.3 (7953) x64 recently installed from de store.

**Comment by MarcAnt01** [comment]
Thanks for reporting @Jonathanarielarg , bug reports are required to follow the template which include many information crucial for fixing the issue. Please, open a new ticket with the bug template and fill every field

**Comment by Jonathanarielarg** [comment]
> Thanks for reporting @Jonathanarielarg , bug reports are required to follow the template which include many information crucial for fixing the issue. Please, open a new ticket with the bug template and fill every field

thank you @MarcAnt01 for you reply, where is the template? 
regards,

**Comment by makisukurisu** [comment]
@Jonathanarielarg , I've created an issue #2930 - feel free to add to it.

You can see a template when you hit on "New issue" button on Issues page:
![image](https://user-images.githubusercontent.com/49622129/210631866-de0d149f-7dba-40b1-94f0-6c4f63e6d835.png)

**Comment by FrayxRulez** [comment]
The bug is caused by Telegram Android 9.3

**Comment by Jonathanarielarg** [comment]
> The bug is caused by Telegram Android 9.3

Than you @FrayxRulez I have an android with telegram v9.3.3 (3026) and is the last versión available in the playstore. Do you mean that the problem is the app? or maybe the other side that have previouse version of telegram? Do you know if with the latest version of the playstore the problem persist or was solutionated?
Best regards!
thank you!

Mobile moto with android 10.
