### ISSUE TITLE
Add black/white system background for chat background

### ISSUE THREAD

**Issue by revan1199** [UnigramDev/Unigram#293]
It would be nice, if a black/white background could be chosen.

**Comment by FrayxRulez** [comment]
You can choose a while/black image from your device.

**Comment by revan1199** [comment]
@FrayxRulez Not the best solution. As an alternative, how would it be, if we disable the background by a setting? So that the system background color is visible and not the picture.

**Comment by FrayxRulez** [comment]
I don't want to have tons of (redundant) options
