### ISSUE TITLE
If you send a file in secret chat other party will recieve a text message "Empty"

### ISSUE THREAD

**Issue by makisukurisu** [UnigramDev/Unigram#2930]
**Describe the bug**
If you send some file (csv file in my case) in a secret chat, from Unigram to TG Android (also in my specific case) - party on Android receives (localized, meaning - it's translated to a client's locale) message saying "Empty"

Recreated from #2929  

**To Reproduce**
1. Go to "📝" menu, press on "New Secret Chat"
2. Select some contact willing to participate
3. Select "Send file"
4. Other party received message with text "Empty"  

**Expected behavior**
They get a file

**Version Info**
 - Unigram: v 9.3 7955 X64 Direct
 - Windows: 22H2 - 22621.963

**Additional context**
Only tried with Android 9.3 and Unigram 9.3. Don't have other options tbh.
Haven't tried other way around too.

**Help wanted**
If you have other devices, or can test other way around - please comment there.

**Comment by FrayxRulez** [comment]
The bug is caused by Telegram Android 9.3
