### ISSUE TITLE
App window show up in taskbar on startup (even with tray icon enabled)

### ISSUE THREAD

**Issue by nitin2953** [UnigramDev/Unigram#2932]
Hide the app window on startup if "Show tray icon" is enabled

![image](https://user-images.githubusercontent.com/34852979/210945491-1b8fb9c6-2e3f-4ef5-96a2-ebea9cb9abe7.png)

**Comment by makisukurisu** [comment]
Works as expected. You have a tray icon.

App should be opened on startup. (Otherwise it won't start receiving updates)

**Comment by nitin2953** [comment]
But the official app opens then close itself from taskbar & resides in tray

**Comment by makisukurisu** [comment]
It's a technical disadvantage of UWP framework. It's just not possible to make it work like TD does.

**Comment by nitin2953** [comment]
It's annoying, I have to close the unigram window after every startup/reboot

Is there no way to fix this ?
