### ISSUE TITLE
Not able to edit message on Unigram

### ISSUE THREAD

**Issue by Tareiah** [UnigramDev/Unigram#2934]
Hey, I'm having an issue where I'm not able to edit messages sent in unigram. I have just downloaded it recently. I right click as I did on Telegram but does not display option to edit? Anyway to edit?

Thanks!

**Comment by makisukurisu** [comment]
@Tareiah Can you show where you are clicking, and what exactly do you get?

You are supposed to click right next to a message, or on it, or on the media (like gif/image), if you sent a grouped media message.

**Comment by makisukurisu** [comment]
Please, provide details either there, or on unigraminsiders.t.me

Closing ticket because it's lacking details.
