### ISSUE TITLE
msix installed failed Class Not Registered

### ISSUE THREAD

**Issue by Nofated095** [UnigramDev/Unigram#2935]
**Describe the bug**
Got an error when installing Unigram via GitHub releases.
`Class Not Registered` Error Code `0x80040154`

**To Reproduce**
1. Install `.msix` and got error.

**Screenshots**
![image](https://user-images.githubusercontent.com/49985975/211232008-de332c38-c57e-40c9-8f78-32fc8da8a21f.png)

**Version Info**
 - Unigram: [e.g. 9.0.7840.0 x64]
 - Windows: [e.g. 2009 `OS Build 19042.631`]

**Comment by makisukurisu** [comment]
Ask Microsoft:
https://answers.microsoft.com/en-us/msoffice/forum/all/error-code-0x80040154-class-not-registered/c5f947dc-4ed7-40b3-8cc4-957794600ca4

This is an error in your system.
Do you, perhaps use Windows 10 x86?

**Comment by Nofated095** [comment]
No, I am very sure I am using the x64

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Pavel Pohorieltsev ***@***.***>
发送时间: Monday, January 9, 2023 3:54:42 PM
收件人: UnigramDev/Unigram ***@***.***>
抄送: Nofated ***@***.***>; Author ***@***.***>
主题: Re: [UnigramDev/Unigram] msix installed failed Class Not Registered (Issue #2935)


Ask Microsoft:
https://answers.microsoft.com/en-us/msoffice/forum/all/error-code-0x80040154-class-not-registered/c5f947dc-4ed7-40b3-8cc4-957794600ca4

This is an error in your system.
Do you, perhaps use Windows 10 x86?

―
