### ISSUE TITLE
Why do you wanna kill Windows 10 mobile?

### ISSUE THREAD

**Issue by Pedro1234-code** [UnigramDev/Unigram#2936]
Ok, I will be clear: WHY DO YOU WANNA KILL WINDOWS 10 MOBILE?

There is just one option of messaging on WP: Unigram Mobile. Ok, it works and bla bla bla, but we all know the truth: it isn't getting updated and at any moment it can stop working. Basically, when it happens, the entire community will be like: "omg our so loved phone now doesn't even have a messager option", and it is just one person's fault: yours. You simply said: now I am gonna kill Unigram on W10M and that is it and f*** the community and everyone that made took a lot of time making WUT and guides and other things. Now, official Telegram is dead, Unigram Mobile is almost dead, and everybody knows that there is no smartphone without messager app. You guys simply decided to kill an entire community and didn't even thinked on the responsibility of that action. It was just a simple task: create an arm32 build of the app, but no, you decided to kill the community, even if it was not an immediate action but when Windows phone die, some big part of the responsibility will be yours. Just keep in mind, I am really asking for you to bring back support for W10M, not even full support like issues or things like that, but at least an arm32 build to don't let the community die, please.

**Comment by makisukurisu** [comment]
Because Microsoft discontinued this operating system a long time ago.

Unigram just won't work on this OS in the current state.

No one is killing it.

**Comment by MarcAnt01** [comment]
Hi, Microsoft discontinued Windows phone years ago. As for Unigram, the Windows Mobile support was discontinued  more than three years ago, because it implied a lot of additional mantainance. Our suggestion is to use Telegram web to stay up-to-date or update to an Android/iOS smartphone
