### ISSUE TITLE
Translation button

### ISSUE THREAD

**Issue by issayev1997** [UnigramDev/Unigram#2937]
Please add a "Translate" button. She is very helpful. Any language translates to the language of the system. Such an implementation is in the Nekogram client
![image](https://user-images.githubusercontent.com/72961920/211499250-159415f9-db78-43de-9058-3a88c4631387.png)

https://user-images.githubusercontent.com/72961920/211499372-82308dd5-f400-4995-a6d2-0d2f1d2c9ab2.mp4

**Comment by makisukurisu** [comment]
@issayev1997 It's already there!

Go to Settings, Language and toggle a switch to enable the translation feature.
