### ISSUE TITLE
Unigram link preview is different from official apps

### ISSUE THREAD

**Issue by Marocco2** [UnigramDev/Unigram#2938]
**Describe the bug**
Sometimes, certain link previews like Twitter/Youtube etc. are different/partial between Unigram and Telegram official apps

**To Reproduce**
1. Go to Saved Messages or a chat
2. Post a link with a preview (eg. https://twitter.com/tomwarren/status/1612812416131244034)
3. Check preview between telegram clients

**Expected behavior**
Unigram should show the same preview as the other official telegram apps (Android tested here).

**Screenshots**
Telegram Android:
![Android](https://user-images.githubusercontent.com/3944248/211602042-5273fc54-4009-44d2-8dfb-ff9cd0dfdcd5.png)
Unigram: 
![Unigram](https://user-images.githubusercontent.com/3944248/211601787-f9699a0c-893e-4780-a622-33612dcc0c5c.png)

**Version Info**
 - Unigram: 9.3.7966 x64
 - Windows: 11 22H2

**Comment by makisukurisu** [comment]
Apparently every Telegram app has different limits for previews.

You can see a few in this screenshot (Telegram for android also has a different limit from all of the above)

![image](https://user-images.githubusercontent.com/49622129/212754271-bd281190-2584-4b63-9863-d9b30998d0bc.png)

Some clients even change preview length depending on size of the window.
