### ISSUE TITLE
Edit Contact > Set photo for user doesn't apply

### ISSUE THREAD

**Issue by TKIPisalegacycipher** [UnigramDev/Unigram#2940]
**Describe the bug**
The "Set photo for" feature lets you select a photo/emoji/sticker, but no matter what you pick, it doesn't actually apply. 

**To Reproduce**
1. Go to a contact > Edit Contact
2. Click on 'Set photo for <user name>"
3. Click "Choose photo or video"
4. Pick a photo, confirm crop, click save (check button)
5. Save contact

Actual result is no obvious change to the user's photo.

**Expected behavior**
The contact photo is set and appears in all appropriate contact photo locations for that contact.

**Screenshots**
![image](https://user-images.githubusercontent.com/3820074/212528420-cc3ef374-8493-446c-b097-94ef470283a8.png)

**Version Info**
 - Unigram: 9.3 x64
 - Windows: 11

**Additional context**
N/A

**Comment by TKIPisalegacycipher** [comment]
Hi @FrayxRulez this is still broken :(

**Comment by FrayxRulez** [comment]
> Hi @FrayxRulez this is still broken :(

Should be fixed in beta. What's your app version?

**Comment by TKIPisalegacycipher** [comment]
9.6 (8531) X64

**Comment by TKIPisalegacycipher** [comment]
[I think I fixed this upstream](https://github.com/tdlib/td/pull/3605), but the PR hasn't yet been merged.
