### ISSUE TITLE
Bring back the duration of an individual call

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2942]
Before the redesign of calls, in individual calls it was possible to see the duration of the call. Mobile clients do display it.

**Comment by FrayxRulez** [comment]
Where?

**Comment by MarcAnt01** [comment]
I would suggest putting it in the titlebar, because there is not a particular part of the interface where it looks good. Your thoughts?

Before the redesign it was available together with the caller name, but it was a bit intrusive to be displayed over the other caller's video

**Comment by FrayxRulez** [comment]
My question was where is it missing, because I can see it

**Comment by MarcAnt01** [comment]
It's missing as the other caller turns on their video

**Comment by MarcAnt01** [comment]
As long as the video is off, it is displayed properly
