### ISSUE TITLE
Copyright tweak

### ISSUE THREAD

**Issue by riverar** [UnigramDev/Unigram#2943]
https://github.com/UnigramDev/Unigram/commit/daca3373992eaf547c4c8ded851b3396d8dc397d introduces copyright headers. But with 210 PRs or so under your belt, this repository holds code owned by others.

May I suggest a small tweak to your headers?

```diff
//
-// Copyright Fela Ameghino 2015-2023
+// Copyright ©️ 2015-2023 Fela Ameghino and Contributors
//
// Distributed under the GNU General Public License v3.0. (See accompanying
// file LICENSE or copy at https://www.gnu.org/licenses/gpl-3.0.txt)
//
```

**Comment by gus33000** [comment]
Bumping this old issue that remains untriaged and is of high interest.

**Comment by FrayxRulez** [comment]
@gus33000 The issue will not be addressed.

**Comment by gus33000** [comment]
> @gus33000 The issue will not be addressed.

Have you consulted with previous contributors if they were ok with the license header change though? That's usually the go to when doing such things

**Comment by riverar** [comment]
@FrayxRulez I hope you reconsider. It is my understanding that submitting code here does not transfer copyright. That would mean these headers are incorrect and could pose future licensing headaches. Thanks!

**Comment by gus33000** [comment]
(for ref) Section 11 of the GPL v3 license this project is licensed under

> A "contributor" is a copyright holder who authorizes use under this
License of the Program or a work on which the Program is based.  The
work thus licensed is called the contributor's "contributor version".

**Comment by FrayxRulez** [comment]
@gus33000 there were no changes in the license, the previous model has just been made explicit in the copyright header.

**Comment by gus33000** [comment]
> @gus33000 there were no changes in the license, the previous model has just been made explicit in the copyright header.

It is my understanding the previous model consisted only of the GPL v3 LICENSE present at the root of this repository, which never mentioned your name. And according to the GPL v3 license, contributor work is licensed under their own terms (while remaining GPL v3 licensed). It sounds reasonable to include other people in

**Comment by gus33000** [comment]
To put this into a clearer perspective, if one forks your repository at the following state (https://github.com/UnigramDev/Unigram/commit/57adfe9000d20b70bb613cab3c4fcbe6463309bc) and then does a new commit adding license headers like you did, albeit, without your name, it obviously would sound unfair. The GPLv3 obviously requires retaining a clear history of changes and copyright headers / credits. I don't see how the reverse wouldn't be true either

**Comment by FrayxRulez** [comment]
"& Contributors" has been added to all the C# files in the repository that have any active contribution that isn't mine, this is 52 files out of 988.

**Comment by gus33000** [comment]
Thank you for reconsidering ❤️🥰
