### ISSUE TITLE
Add shortcut for accepting and rejecting calls

### ISSUE THREAD

**Issue by makisukurisu** [UnigramDev/Unigram#2944]
Proposed by @Slonobass:
https://t.me/unigraminsiders/460648

Add a shortcut to accept a call (perhaps - two, for accepting with video and without video) and a shortcut to reject a call (+- to end an ongoing call).

Examples of shortcuts in other apps:

- Ctrl+Shift+P and Ctrl+Shift+H are used by Skype;
- Ctrl+Enter and Escape by Discrord;
- Ctrl+Shift+A/S and Ctrl+Shift+D are used by MS Teams;

If it's possible to use system-wide shortcut it (if possible) should not interfere with other apps.
If a shortcut could be used only when the app is in focus, I guess any will do.

**Comment by FrayxRulez** [comment]
Shortcuts have been added
