### ISSUE TITLE
An option to do input language per chat?

### ISSUE THREAD

**Issue by lostmsu** [UnigramDev/Unigram#2946]
I have contacts speaking at least 2 different languages. It would be nice for Unigram to remember the input languages as one switches between chats and optionally remember them between program launches.

Not sure about UWP, but WinAPI has [ActivateKeyboardLayout](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-activatekeyboardlayout?redirectedfrom=MSDN)

**Comment by FrayxRulez** [comment]
As stated in the page that you linked itself: `Minimum supported client | Windows 2000 Professional [desktop apps only]`

**Comment by lostmsu** [comment]
@FrayxRulez I don't think this means it is not available in UWP, since that would mean even OpenFile is not available. Let me check when I get home.

**Comment by FrayxRulez** [comment]
@lostmsu It does work, but it won’t be approved by Microsoft

**Comment by FrayxRulez** [comment]
@lostmsu Because the API that you liked say that the API is only available to desktop apps, hence it’s not allowed for UWP apps in the Microsoft Store, the submission would get rejected.

**Comment by FrayxRulez** [comment]
@lostmsu Yes, as I develop Windows 10 apps since 2015 I got quite a lot of rejections about APIs marked as “Desktop only”
