### ISSUE TITLE
Instant view doesn't use the full space available

### ISSUE THREAD

**Issue by cdimauro** [UnigramDev/Unigram#2947]
**Describe the bug**
Instant view doesn't use the full space available: it always leaves an empty part to the right side.

**To Reproduce**
1. Open a page (for example: https://telegra.ph/Juventus-Scanavino-Sentenza-iniqua-giustizia-federale-sommaria-01-22 ) with enough content/text which can fill the horizontal space available and that wraps down.
4. A box to the right said is always left empty, even if the content can use it.

**Expected behavior**
All available space should be used in the Instant Preview page.

**Screenshots**
![image](https://user-images.githubusercontent.com/4763177/213939790-4f71f5ce-a447-454d-8ecb-396456283511.png)
Se the empty space between the text and the scroll bar to the right (the small vertical white line which is visible to the rightmost side.

**Version Info**
 - Unigram: 9.3 (7965) x64
 - Windows: Windows 11 Pro 22H2

**Comment by makisukurisu** [comment]
This is not a bug, but a feature*.

Few updates ago it was common design choice in Windows 11 UI (settings for example did this)
Now that it's same idea, but centered - I believe it's better to follow the trend, and center settings right panel and instant view as well.

**Comment by cdimauro** [comment]
> This is not a bug, but a feature*.
> 
> Few updates ago it was common design choice in Windows 11 UI (settings for example did this) Now that it's same idea, but centered - I believe it's better to follow the trend, and center settings right panel and instant view as well.

But Instant view isn't a settings panel, rather it's a container for displaying content.

Microsoft Store, for example, is a Windows 11 UI, but fully utilizes the available space.

**Comment by FrayxRulez** [comment]
This is by design as a text spanning for more than 1000px on your screen would become pretty hard to read

**Comment by cdimauro** [comment]
> This is by design as a text spanning for more than 1000px on your screen would become pretty hard to read

Give the chance to customize the instant view settings (e.g.: use a different font / size) and you'll appreciate the possibility to read the content fully using the available space, especially having large monitors.

I've "just" a FullHD monitor and even using the maximum font size for all contents (which isn't good: the chat window doesn't necessarily need a big font) the right side of the instant view is empty and it's an eyesore.

Plus, large tables are split and look broken:
![image](https://user-images.githubusercontent.com/4763177/226106409-9ab85291-50f0-4576-8fcd-d8fc898ace24.png)

I've no problem if you like the current layout, but giving the user the possibility customize their is experience shouldn't hurt your freedom of choice.
