### ISSUE TITLE
Instant view doesn't render "pageBlockAudio" properly

### ISSUE THREAD

**Issue by makisukurisu** [UnigramDev/Unigram#2949]
**Describe the bug**
Unigram doesn't show a box with audio (at least for Wikipedia) in Instant View, but instead - it shows some sort of dictionary representing it.

**To Reproduce**
1. Find some instant view page with audio block in it, like [this](https://ru.wikipedia.org/wiki/%D0%A6%D0%BE%D0%B9,_%D0%92%D0%B8%D0%BA%D1%82%D0%BE%D1%80_%D0%A0%D0%BE%D0%B1%D0%B5%D1%80%D1%82%D0%BE%D0%B2%D0%B8%D1%87);
2. Click "⚡Instant View" button; 
3. Scroll down to audio block;
4. See text instead of audio.

**Expected behavior**
Unigram renders working audio block, just like one you can see on Wikipedia.

**Screenshots**
Image of the problem:
![image](https://user-images.githubusercontent.com/49622129/214050887-bfed5363-94d8-4271-948e-7efef5b5d295.png)

What should be shown instead:
![image](https://user-images.githubusercontent.com/49622129/214051069-5879f4da-0f9e-4433-930c-d067cc9b64de.png)

**Version Info**
 - Unigram: 9.3 7967 X64 Direct
 - Windows: 11 22H2 (22621.1105)

**Comment by FrayxRulez** [comment]
We definitely have an issue about this already

**Comment by MarcAnt01** [comment]
> We definitely have an issue about this already

Yes, probably this one https://github.com/UnigramDev/Unigram/issues/1394

**Comment by FrayxRulez** [comment]
Duplicate of #1394
