### ISSUE TITLE
You should be able to select text in chat messages from the chat history

### ISSUE THREAD

**Issue by adrianghc** [UnigramDev/Unigram#295]
You should be able to select text in chat messages from the chat history, first to simply copy only part of the message manually but ideally you'd also be able to quote parts of messages this way later on (by right-clicking the selection and clicking a "quote" option).

**Comment by alighamari** [comment]
@adrianghc I'm agree with that but that way hike is using not like web pages

**Comment by FrayxRulez** [comment]
It is not possible to allow text selection because the message TextBlock includes an hidden span at the end that contains the sent time (and other infos) to get the "wrap around" effect. So enabling it would let the user select that span too.

**Comment by alighamari** [comment]
@FrayxRulez You can delete it from showing text

**Comment by adrianghc** [comment]
Well would it really be a problem if you could select that hidden span?

**Comment by rabiet** [comment]
@adrianghc I'd say yes...

**Comment by adrianghc** [comment]
Because of the way the selection itself would look or because of the content you could copy?

**Comment by FrayxRulez** [comment]
I'd say both... :D

**Comment by adrianghc** [comment]
Well, what content would there be besides the sent time?
