### ISSUE TITLE
Scroll to first unread message

### ISSUE THREAD

**Issue by roman380** [UnigramDev/Unigram#2951]
Sometimes chat view opens at previously saved position and unread messages start somewhere down the list (e.g. some newer messages were read from another device, and then further messages were added). 

Is there any way to scroll to first unread message?

It looks like other clients, on other platforms handle arrow button click in the way that first you get to first unread, and next click (when first unread is NOT below the current view) gets you to the bottom and last message. In Unigram it seems that the button immedately gets to the bottom and loses the beginning of unread messages.

**Comment by roman380** [comment]
Actually, there is associated feature suggestion.

There are some highly active channels where once you open it, you're in the middle of reading and if you switch you're always unsure whether you can continue reading from the same point - because unread message position will be reset.

Can we possibly have a user defined bookmark set per chat? It could be displayed similarly to "unread messages" header and user would be able to quickly navigate there with a hotkey and/or a menu item.

Such bookmark would be kept infinitely until user resets it or moves himself to a new chat item.

**Comment by FrayxRulez** [comment]
Scrolling position is restored whenever the last unread message doesn't change in between. As is, if you open a chat, scroll to some place, close it and open it again you will be back there. If after closing it you pick your phone, open the chat and read some messages, the scrolling position will be dropped.

**Comment by roman380** [comment]
It works the described way indeed, but once in a while this behavior is damaged. If I happen to catch a pattern, I will mention it. It might be something about opening another chat via external link, so that when you are back to original chat, the position is lost. Either way, I am seeing this regularly that read position is lost.

**Comment by FrayxRulez** [comment]
This was implemented
