### ISSUE TITLE
Volume control is not visible in fullscreen gallery mode

### ISSUE THREAD

**Issue by voed** [UnigramDev/Unigram#2955]
**Describe the bug**
Looks like #2821 but for fullscreen gallery.

**To Reproduce**
1. Check 'Enable fullscreen gallery'
2. Open video
3. Click on volume control button
4. Nothing happens

**Screenshots**
<img width="311" alt="image" src="https://user-images.githubusercontent.com/10352360/215565560-76cf2de1-6781-4a18-aefe-dbb44b386b95.png">

**Version Info**
 - Unigram: 9.3.7968 x64 Direct
 - Windows: 11 22H2

**Comment by makisukurisu** [comment]
Just asking - is Unigram not taking full width of the screen horizontally at this moment?

**Comment by voed** [comment]
Not sure what do you mean. I guess it is, but i am using surface laptop with its weird 3:2 aspect ratio:
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/10352360/216509946-44a706a6-6db8-4d15-b9d1-3e4e1e740b0f.png">

**Comment by FrayxRulez** [comment]
This is fixed in the latest beta
