### ISSUE TITLE
Bug: Unigrams does not make a multi-line monospace-formatted text clickable, Android client does

### ISSUE THREAD

**Issue by Kenya-West** [UnigramDev/Unigram#2956]
**Describe the bug**
When you format multi-line text with \`code\` (aka `monospace`) formatting, the text becomes non-clickable. You cannot copy the text.
If you do the same in Android Telegram app, the text is clickable and you can copy the `monospace`-formatted text.
If you edit Unigram's message with Android's official Telegram app, `monospace` text becomes clickable. 

**To Reproduce**
1. Post a message with multi-line `monospace`-formatted text
2. See the code is non-clickable.

**Expected behavior**
The code should be clickable.

**Screenshots**
https://user-images.githubusercontent.com/12271104/215728059-80066e1c-cee8-4053-8848-8fba6cac1452.mp4

**Version Info**
 - Unigram: 9.3 x64
 - Windows 11 latest stable

**Comment by FrayxRulez** [comment]
@Kenya-West That’s by design
