### ISSUE TITLE
Replacing a file by editing, deletes the captions

### ISSUE THREAD

**Issue by poliandro** [UnigramDev/Unigram#2957]
**Describe the bug**
When I click on a file to replace it with another file in a chat, doing so removes the caption of the file

**To Reproduce**
Right-click on a file, select edit, search for a new file on PC, then click done. The new file is uploaded, but all previous captions are deleted

**Expected behavior**
The captions should not be deleted.

**Version Info**
 - Unigram: 9.3 (7968) x64 Direct
 - Windows 11

**Comment by FrayxRulez** [comment]
Fixed in 9833b729bc66896b48f47350e6a9540d3dcfb773

**Comment by ppOo4321** [comment]
لغة عربية
