### ISSUE TITLE
App information completely disappeared

### ISSUE THREAD

**Issue by monnolo** [UnigramDev/Unigram#2960]
**Describe the bug**
Empty app screen when opening it after the last update.

**To Reproduce**
1. Go to https://github.com/UnigramDev/Unigram
2. Download and install the version 9.0.7840.0
3. Set the language to ENG, change the default download folder to external NAS one, add translate button, close and reopen

**Expected behavior**
App data (chat, groups, etc.) to appear.

**Screenshots**
![Immagine 2023-02-02 115110](https://user-images.githubusercontent.com/77438414/216305172-4076906d-a8b9-48b4-bb47-cc66b8edb94f.png)

**Version Info**
 - Unigram: [9.0.7840.0 x64]
 - Windows: [MS Windows 11 business 10.0.22621 build 22621]

**Comment by makisukurisu** [comment]
If I remember chat correctly - that's a "won't fix"?
