### ISSUE TITLE
Unigram with full topics support does not show topic id 

### ISSUE THREAD

**Issue by Kenya-West** [UnigramDev/Unigram#2961]
**Describe the bug**
The topic id is just a hyperlink to the service message of particular topic creation.

**To Reproduce**
1. Go to chat with topics enabled;
2. Click on topic info
3. There should be a link to topic, not a link to the entire chat.

**Expected behavior**
Topic link should be present when clicking to the topic info.

**Screenshots**
| Unigram | Official client (Android)|
|:-------------------------:|:-------:|
| ![image](https://user-images.githubusercontent.com/12271104/216808439-b9555630-16b6-433a-acfb-e429f636d33a.png) | ![image](https://user-images.githubusercontent.com/12271104/216808451-8864fbf9-0bd6-456e-9606-52bba623bdfd.png) |

**Version Info**
 - Unigram: 7.9 7370 x64
 - Windows: 11 latest stable

**Additional context**

**Comment by makisukurisu** [comment]
Added to #2953, I'll close the issue if you don't mind.
