### ISSUE TITLE
Unigram does not allow to send media messages to topics silently

### ISSUE THREAD

**Issue by Kenya-West** [UnigramDev/Unigram#2964]
**Describe the bug**
In latest Unigram version 9.3 (7970), it is not possible to send a message silently to any topic. It is actual for groups that enabled "Topics" (aka "Forum") feature.

**To Reproduce**
1. Go to any groups with topics enabled, open any topic;
2. Try to send a media message: just send any file;
3. You will see there is no button to send the media message silently.

**Expected behavior**
The app should allow silent message for media content.

**Version Info**
 - Unigram: 9.3 (7970) x64
 - Windows: 11 latest stable

**Comment by makisukurisu** [comment]
I've added this to #2953, but not closing this issue because it needs triage, IMO.
