### ISSUE TITLE
Unigram with full Topics support does not allow to send to a specific topic

### ISSUE THREAD

**Issue by Kenya-West** [UnigramDev/Unigram#2965]
**Describe the bug**
Try to forward a message to a group with "Topics" feature enabled. It will only send to a main topic and will not allow to choose which topic to forward to.

**To Reproduce**
1. Forward any message to a group with "Topics" feature enabled;
2. See the forwarded message appears in main topic.

**Expected behavior**
App should first provide a list of the destination group topics to choose which topic the message should be forwarded to.

**Version Info**
 - Unigram: 9.3 (7970) x64
- Windows: 11 latest stable

**Comment by makisukurisu** [comment]
Added to #2953, if you don't mind - I'll close this issue because #2953 is an aggregation of topic issues.

Thanks for your report!
