### ISSUE TITLE
 support Chinese translation

### ISSUE THREAD

**Issue by xin67** [UnigramDev/Unigram#2969]
Friends， can support Chinese translation？
This feature is very important to us

**Comment by makisukurisu** [comment]
@xin67 Unigram uses Telegram Android translations.

So you can ask for an official Chinese translation on https://translations.telegram.org/

Also - you can use an unofficial pack like that one:
https://t.me/setlanguage/zh-hans-beta

**Comment by MarcAnt01** [comment]
Duplicate of https://github.com/UnigramDev/Unigram/issues/2836
