### ISSUE TITLE
Update the app icon resources to remove the blue background

### ISSUE THREAD

**Issue by prakharb5** [UnigramDev/Unigram#2970]
The app logo of Unigram appears with a blue background in apps like App Installer, Fluent Search, etc. or the dark grey background (Microsoft Powertoys)
Please update them to match the same icon used for taskbar/start menu icon.

![image](https://user-images.githubusercontent.com/51435948/218273061-709a3201-6bf6-4952-bb09-857fa3f5182c.png)

![image](https://user-images.githubusercontent.com/51435948/218273076-65524a3d-3700-463a-a0a8-7c0fdd1a0788.png)

![image](https://user-images.githubusercontent.com/51435948/218273151-4d5a80f1-ddbe-4e48-b89b-44fb15dfe15c.png)

**Comment by FrayxRulez** [comment]
Sorry, but this is not planned

**Comment by prakharb5** [comment]
But it can just make all the components of the app more consistent.
