### ISSUE TITLE
Duplicated service message in chat history

### ISSUE THREAD

**Issue by MrFredber** [UnigramDev/Unigram#2971]
**Describe the bug**
Something is happened and chat have the endless "special messages".

**To Reproduce**
idk. I deleted other person's messages and this happened. Application reboot doesn't help.
In other Telegram client all works perfectly

**Screenshots**
![image](https://user-images.githubusercontent.com/33953266/218406616-aacc8a9d-01cb-4a21-bc4b-34ee32ba242a.png)
![image](https://user-images.githubusercontent.com/33953266/218406687-ac2df904-3c32-4d34-a3b6-ab6faeabc5ba.png)
![image](https://user-images.githubusercontent.com/33953266/218407845-52bf419e-d969-4e07-b844-bc1a5b8c6515.png)

**Version Info**
 - Unigram: 9.3 (7968) X64 Direct
 - Windows: 10 22H2 (19045.2546)

**Comment by FrayxRulez** [comment]
This is not a pub.

**Comment by MrFredber** [comment]
I didn't understand you.

**Comment by FrayxRulez** [comment]
> I didn't understand you.

Write a proper title for the issue or I'll close it.
