### ISSUE TITLE
Unigram does not show popup for restricted accounts

### ISSUE THREAD

**Issue by Kenya-West** [UnigramDev/Unigram#2972]
**Describe the bug**
When your Telegram account is being restricted (for a week, usually) because of spam messages, the official Android client shows a popup that explains what is going on and why you cannot send messages to some chats.

When restricted, you cannot send messages to:
1. People that have not added you to their contacts;
2. Group chats whose admin does not know you;
3. Discussion chats linked to channels;
4. Newly created groups or the groups you were recently been added to.

**To Reproduce**
1. Send spam, talk shit, especially to the people that did not know you;
2. Eventually get your account restricted;
3. Try to send message to the chats that described above;
4. See that no popup explanation of restrictions appears.

**Expected behavior**
The app should display such popup. Currently, it just shows that messaged is failed to send.

**Screenshots**
| Official client (Android) | Unigram |
|:-------------------------:|:-------:|
| ![Screenshot_2023-02-18-13-28-20-143_org telegram messenger](https://user-images.githubusercontent.com/12271104/219848173-bc58eee5-9921-46f4-8155-3dd04e1ea2c0.jpg) | ![image](https://user-images.githubusercontent.com/12271104/219848184-902fe601-c506-44db-bad2-8e1a861bab12.png) |

**Version Info**
 - Unigram: 9.3 (7970)
 - Windows: 11 latest stable

**Comment by 525226463** [comment]
D mula as cafe alor setar kedah malaysia.....crew amira dan amirul

**Comment by MarcAnt01** [comment]
Added to https://github.com/UnigramDev/Unigram/issues/649
