### ISSUE TITLE
Old Microsoft emojis shown in preview

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#2974]
**Describe the bug**
The emoji style selection previews the old version of Microsoft emojis and should be updated to fit the new Microsoft emojis.
<img width="303" alt="image" src="https://user-images.githubusercontent.com/14281234/219870309-cf01e78c-2589-42eb-94ab-0e3aab79f873.png">

Maybe it would be worth to set it to standard as well now? :D

 - Unigram: 9.3 (7970) X64
 - Windows: Windows 11 Pro (10.0.22621)

**Comment by 525226463** [comment]
Prank...amira dan amirul d mula as cafe alor setar kedah malaysia

**Comment by FrayxRulez** [comment]
Preview has been removed in https://github.com/UnigramDev/Unigram/commit/c4f3c86524861b3c95b1a2bfbcf67840b1bf3285
