### ISSUE TITLE
Deleting secret chats fails

### ISSUE THREAD

**Issue by loxia01** [UnigramDev/Unigram#2975]
**Describe the bug**
When trying to delete secret chats Unigram app minimizes after about one second of count-down and deletion fails.

**To Reproduce**
Select a secret chat, right-click and then left-click on Delete.

**Expected behavior**
After the count down icon has counted down 5 seconds the secret chat should be deleted. 

**Screenshots**

**Version Info**
 - Unigram: 9.3.7970.0
 - Windows: 10 22H2 

**Additional context**
I believe that this issue not only affects secret chats but also for example leaving a channel, but I have encountered it mostly when trying to delete secret chats.

After trying several times and waiting perhaps 12 hours deletion will succeed (after trying again).

**Comment by FrayxRulez** [comment]
@loxia01 Great bug report

**Comment by loxia01** [comment]
sorry
