### ISSUE TITLE
Unigram crashes on launch (for authenticated users)

### ISSUE THREAD

**Issue by dongle-the-gadget** [UnigramDev/Unigram#2976]
**Describe the bug**
Unigram only shows the splash screen with the app icon in the middle (if the user has authenticated before) or briefly showing the chat list (if the user has just authenticated) before crashing.

**To Reproduce**
1. Authenticate to TDLib using either QR or code.
2. Observe the chat list briefly showing up before crashing.
3. Notice that subsequent launches also crash.

**Expected behavior**
The program shouldn't crash.

**Version Info**
 - Unigram: 9.3.7970.0 x64
 - Windows: 11 Insider 25300

**Additional context**
Launching the app in Native Only debug in Visual Studio shows that `Unigram.Native.dll` is crashing the app - though I'm not able to trace which function was causing the crash.
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/29563098/220702253-c5e58d53-bcb5-42b6-a847-640d22c1c36d.png">

**Comment by dongle-the-gadget** [comment]
@FrayxRulez here's the relevant stack trace of the exception: 

<img width="798" alt="image" src="https://user-images.githubusercontent.com/29563098/222739399-ca5cc9c7-78f7-48b4-baa3-64f3ff88f739.png">

The WinRT exception thrown reads: "The specified device interface or feature level is not supported on this system."

**Comment by FrayxRulez** [comment]
@dongle-the-gadget My guess is that there's some issue initializing DirectX... But hard to say what just from that 😕

**Comment by dongle-the-gadget** [comment]
Yup, that's my guess too.

**Comment by dongle-the-gadget** [comment]
Update: just upgraded my GPU driver and now Unigram works.

**Comment by FrayxRulez** [comment]
@dongle-the-gadget What’s the GPU brand?

**Comment by FrayxRulez** [comment]
Attempt to fix this: https://github.com/UnigramDev/Unigram/commit/9b66e124b8e8344c9904cc0927dcc84668d98d1e
