### ISSUE TITLE
Add Mica option as chat background

### ISSUE THREAD

**Issue by pan-theis** [UnigramDev/Unigram#2978]
Currently the "instant view" uses the Mica background and it gives a very coherent, seamless and pleasant user experience. 

It would be great if the normal chat backgrounds would apply the same mica background effect. Currently you have to choose between opaque pictures and colored patterns.

![mica unigram](https://user-images.githubusercontent.com/45819088/221850957-b66fcaae-0a15-45de-80cc-f7d6751f7afa.png)

**Comment by makisukurisu** [comment]
@pan-theis You can set a transparent image.

Like that one:
https://t.me/unigraminsiders/459081

**Comment by makisukurisu** [comment]
Then Unigram will look like this

![image](https://user-images.githubusercontent.com/49622129/221851792-841c896e-e75c-42c3-9a50-3127f1f8b34d.png)

**Comment by pan-theis** [comment]
Wow! Thank you for the workaround! Can you make it as an default option in Unigram?

**Comment by FrayxRulez** [comment]
As there's a basic workaround for this I don't think I'm going to add a specifically, also because I don't see any obvious way to introuce thi UX-wise

**Comment by emvaized** [comment]
> I don't see any obvious way to introuce thi UX-wise

Probably a good solution would be to add "alpha" slider for chat backgrounds, which would let user to set transparency for any background, either color or built-in

**Comment by ghost** [comment]
the last unigram update overrode my wallpaper to the default ugly ones. Even when setting it anew with the 1x1 transparent png, it will be overwritten with every start of Unigram. 

Please reconsider offical support for acrylic and mica wallpapers!

**Comment by FrayxRulez** [comment]
> the last unigram update overrode my wallpaper to the default ugly ones. Even when setting it anew with the 1x1 transparent png, it will be overwritten with every start of Unigram.
> 
> Please reconsider offical support for acrylic and mica wallpapers!

I can't reproduce the issue.
