### ISSUE TITLE
Closing the group calls crashes Unigram

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2979]
**Describe the bug**
If I end a group call with the leave call button sometimes it will crash Unigram

**To Reproduce**
1. Open/start a videocall
2. Leave it closing it

**Expected behavior**
Not crash

**Version Info**
 - Unigram: 9.4.7994
 - Windows: 11 Preview 22623.1325

**Additional context**
Logs sent via private chat

**Comment by FrayxRulez** [comment]
Closing it as? Closing the window?

**Comment by MarcAnt01** [comment]
> Closing it as? Closing the window?

Clicking with "end call" button. Closing the window doesn't cause any issues

**Comment by FrayxRulez** [comment]
Are you sharing your screen, video, audio?

**Comment by MarcAnt01** [comment]
Probably, will give further information + logs when it happens again

**Comment by FrayxRulez** [comment]
Crash dumps are needed.

**Comment by FrayxRulez** [comment]
Closing this as no further details have been provided.
