### ISSUE TITLE
Pause/Play voice messages

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#298]
Right now, if you press the "pause"-button, you will actually stop the message.
Because of that you have to start from the beginning all over again.

When pausing a voice message it should start again from that Point, if you press Play again.

**Comment by FrayxRulez** [comment]
This should be fixed in https://github.com/UnigramDev/Unigram/releases/tag/v0.9.726

**Comment by larsschellhas** [comment]
I´m afraid, we have to reopen this issue for now

**Comment by larsschellhas** [comment]
If you press play a voice message starts. If you press it again it start over from the beginning.
The normal/expected behaviour is the play button to turn into a pause button and if pressed the replay should pause and the button should turn back into the play button. If you press that one the voice message should continue from where you paused it.

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/bcdeac005d9843a2cd807c57998b914b30a67225
