### ISSUE TITLE
Changing "display me as" from group to individual results in duplicated entries

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#2980]
**Describe the bug**
If I start a group call being displayed as a group and then I switch to my personal account, both show up in the group members list

**To Reproduce**
1. Start a videocall as a group
2. Switch to your account
3.  See the bug

**Expected behavior**
Update the entry in the list or remove the "group" from calls members

**Screenshot**
 
![image](https://user-images.githubusercontent.com/43090263/222399167-759a732d-ac27-4bcd-9ddb-bf7ce89b3078.png)

**Version Info**
- Unigram: 9.4.7994
- Windows: 11 Preview 22623.1325

**Additional context**
Logs sent via private chat

**Comment by FrayxRulez** [comment]
A "crash" is when the process unexpectedly quits, this isn't a crash.
