### ISSUE TITLE
notable to compile on vs2022 17.5.0

### ISSUE THREAD

**Issue by mzayarnyuk** [UnigramDev/Unigram#2982]
error on x64 config (x86 and arm) (tdlib 1.8.0 builded in vsix and installed)
#include "flatbuffers/flatbuffers.h"
at \Unigram\Libraries\libtextclassifier\lang_id\common\flatbuffers\embedding-network_generated.h
hav downloaded packages that vs adviced with vcpckg but still that error....

pls add it to src;
or make lookup uni or add intro move/install where and what version....

**Comment by FrayxRulez** [comment]
@mzayarnyuk You can try to install flat buffers from vcpkg

**Comment by mzayarnyuk** [comment]
I tried develop branch; missed that it' fork;
but to be sure with fresh trie ddiff. uwp versions;
looks like it feet; but table func need 3 params; - not sure what that align do....
will try 16, if will not work or crash will try that old commit;
tgcalls is outdated too - tryied fork commit from main branch for now;
_____
currently lookup where actual libutf with needed files; fork links is dead....

**Comment by mzayarnyuk** [comment]
found similar hash on android

**Comment by mzayarnyuk** [comment]
now lookup

**Comment by mzayarnyuk** [comment]
'libavformat/avformat.h': No such file or directory (compiling source file CachedVideoAnimation.cpp)	Unigram.Native	\VideoAnimation.h	15	
'libavformat/avformat.h': No such file or directory (compiling source file VideoAnimation.cpp)	Unigram.Native	\VideoAnimation.h	15	
'opus/opus_defines.h': No such file or directory (compiling source file Opus\OpusOutput.cpp)	Unigram.NativeOpus\OpusOutput.h	5	

ineterst 'main' branch in same state or not

**Comment by FrayxRulez** [comment]
@mzayarnyuk Did you follow build instructions?

**Comment by mzayarnyuk** [comment]
this steps go before compile ffmpeg or webrtc is nt described in intro;
added ffmpeg - later will try special config replace; 
looks like it should resolve libav format and opus issues;

**Comment by mzayarnyuk** [comment]
open this [https://github.com/UnigramDev/Unigram/tree/develop/Unigram/Libraries](https://github.com/UnigramDev/Unigram/tree/develop/Unigram/Libraries)
and ypu will see in develop only latboofers commit exists;
libutf and tgcalls moved;
in 'main' branch exists tgcalls fork commit link;

**Comment by mzayarnyuk** [comment]
good zlib and openssl already cached

**Comment by FrayxRulez** [comment]
@mzayarnyuk Very good

**Comment by mzayarnyuk** [comment]
fresh vcpkg error on build release ffmpeg x64-uwp
-- Building Release Options: --enable-optimizations
-- Building ffmpeg for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: D:/src/vcpkg/downloads/tools/msys2/893f8801e7c30cbd/usr/bin/bash.exe ./build.sh
    Working Directory: D:/src/vcpkg/buildtrees/ffmpeg/x64-uwp-rel
    Error code: 2
    See logs for more information:
      D:\src\vcpkg\buildtrees\ffmpeg\build-x64-uwp-rel-config.log
      D:\src\vcpkg\buildtrees\ffmpeg\build-x64-uwp-rel-out.log
      D:\src\vcpkg\buildtrees\ffmpeg\build-x64-uwp-rel-err.log

Call Stack (most recent call first):
  ports/ffmpeg/portfile.cmake:596 (vcpkg_execute_required_process)
  scripts/ports.cmake:147 (include)

**Comment by mzayarnyuk** [comment]
maybe bash problems or I run main like  vcpkg.exe install ffmpeg[opus,vpx]:x64-uwp lz4:x64-uwp openssl:x64-uwp zlib:x64-uwp libwebp:x64-uwp libogg:x64-uwp opus:x64-uwp

**Comment by atrdev-rgb** [comment]
There are lucky people who were able to assemble the project. Do not share the instructions. Since the assembly instructions are old. Some files are no longer there, for example Views/VoIPPage.xaml

**Comment by FrayxRulez** [comment]
@atrdev-rgb Views/Calls

**Comment by atrdev-rgb** [comment]
![Screenshot_2023-06-08-20-27-03-189_com android chrome](https://github.com/UnigramDev/Unigram/assets/34670899/9766d924-f8fb-42b8-8ab9-9db33b57930a)
Voippage.xaml not found. Please update your instructions

**Comment by FrayxRulez** [comment]
@atrdev-rgb Remove the whole folder

**Comment by atrdev-rgb** [comment]
Telegram.Native.Calls remove too?
