### ISSUE TITLE
Record voice messages without holding the button all the time

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#299]
Telegram for iOS has this Feature since a few weeks now.
When you record a voice message, swipe your finger up to "lock" the record-button. Press again, when you are ready with your record.

**Comment by larsschellhas** [comment]
Do you have any ideas on this? Maybe you could connect it to the abort-swipe? Just to the other direction? :)

**Comment by FrayxRulez** [comment]
Done in https://github.com/UnigramDev/Unigram/commit/d0608f75b4bf7d2e5b466b012e92af0b1cbeb02a
