### ISSUE TITLE
The "viewed by" functionality is broken

### ISSUE THREAD

**Issue by x0x00044** [UnigramDev/Unigram#2990]
**Describe the bug**
The "viewed by" function is clearly borken. It works in like 1/50 messages. In the rest it shows "nobody viewed" through someone already viewed the message for sure.

**To Reproduce**
1. Send a message to any small group
2. Click on the check marks
3. "nobody viewed" through someone viewed it for sure (reacted to the message in some way)

**Expected behavior**
It shows who viewed the message

**Screenshots**
![image](https://user-images.githubusercontent.com/98318975/224486424-3b881089-5798-40af-ad6d-d0b24ad2272e.png)

**Version Info**
 - Unigram: 9.5.7995.0
 - Windows: Windows 10 22H2

**Comment by amirmahdifard** [comment]
haa? @x0x00044 are you the x0 that i'm thinking of? or you are another x0? thanks.

**Comment by x0x00044** [comment]
Seems fixed in latest version as of 15.03.2023
