### ISSUE TITLE
Unable to join a video chat through the profile page

### ISSUE THREAD

**Issue by luccascomvoce** [UnigramDev/Unigram#2992]
**Describe the bug**
Unable to join a video chat through the profile page

**To Reproduce**
1. Go to a group with active video chat
2. Go to the group's profile page and tap the "Video Chat" button
3. Nothing happens

**Expected behavior**
User must be able to join video chat

**Screenshots**

https://user-images.githubusercontent.com/65538684/224523964-ed71e718-4d4b-4d7e-ac48-add1b1e0c9be.mp4

**Version Info**
 - Unigram: 9.5 7997
 - Windows: 11 Pro 22H2 22621.1344

**Additional context**
It is possible to enter the video chat using the button at the top in the chat. 
![image](https://user-images.githubusercontent.com/65538684/224524076-89c6bdd3-c706-4169-ba05-4c388cc57857.png)

**Comment by FrayxRulez** [comment]
I'm not able to reproduce the issue, furthermore the two buttons execute exactly the same code...

**Comment by FrayxRulez** [comment]
Never mind, figured out
