### ISSUE TITLE
"Nobody viewed", but my message saw everyone

### ISSUE THREAD

**Issue by MrFredber** [UnigramDev/Unigram#2993]
**Describe the bug**
New system to see, who saw your message, introduced by telegram is not working

**To Reproduce**
Just open any group, type new message and see the bug

**Expected behavior**
A new appearance of this list

**Screenshots**
![image](https://user-images.githubusercontent.com/33953266/224542731-1ce3f227-de79-4ea4-bb75-aa27c35142db.png)

**Version Info**
 - Unigram: 9.5 (7997) X64 Direct
 - Windows: 10 22H2 (19045.2546)

**Comment by MarcAnt01** [comment]
Thanks for reporting this, if you update the app you will be able to get the fix
