### ISSUE TITLE
Suggestion: Option to choose whether to play all audio files in a conversation or only the selected one.

### ISSUE THREAD

**Issue by StormProductionsMusic** [UnigramDev/Unigram#2994]
Hello there,

I am writing to suggest a feature for Unigram that I think would be very useful to many users, including myself. Currently, when playing audio files in a conversation, Unigram automatically plays the other audio files after the current one ends. While this can be helpful in some cases, it can also be distracting if you only want to listen to a specific audio file.

Therefore, my suggestion is to add a toggle in the app settings that would allow users to choose whether they want to play all audio files in a conversation or only the selected one. This would be particularly helpful when you want to focus on a specific audio file without being interrupted by others.

Thank you for considering my suggestion. I hope it can be implemented in a future update.

**Comment by MarcAnt01** [comment]
Hi, you can disable it from the playing bar
![image](https://user-images.githubusercontent.com/43090263/225884438-b842a49e-09da-43a9-a5a2-f82d508224ba.png)

**Comment by MarcAnt01** [comment]
Closing this, since we didn't hear anything from you. If you have further issues, feel free to let us know
