### ISSUE TITLE
Add a function can make the video saves as other path by right click on it.

### ISSUE THREAD

**Issue by MafiaAce** [UnigramDev/Unigram#2995]
Hello,
Thank you for reading my suggestion. I think make the video save as other path by right click on it is a useful function of users, we needn't to open the video, then click the three points, click the "save as" button. I think the function is convenient.
Hope to adopt it.
p.s. Sorry, my english is poor.

**Comment by MarcAnt01** [comment]
Hello, thanks for your feature request. We believe that the functionality of "save as" is more than enough and it's the de-facto paradigm for allowing users to save files in non-default path.

**Comment by MarcAnt01** [comment]
Btw, if you do not see "save as" it means you haven't downloaded file yet, do it and it will show up
