### ISSUE TITLE
Suggestion: Tray enhancements

### ISSUE THREAD

**Issue by rjindael** [UnigramDev/Unigram#2996]
Hello,

I was wondering if the following two features could be added;
1. Minimizing Unigram to tray on system startup, similar to how Discord handles it, and;
2. Making the Unigram tray icon white (to match other applications)

Thank you!

**Comment by MarcAnt01** [comment]
Hi, thanks for your feature requests.
1. Is already being tracked in https://github.com/UnigramDev/Unigram/issues/2689
2. It used to be white, but it was changed to be colored, since the majority of apps (even Microsoft ones) have colored tray icons (for example OneDrive, Teams)
