### ISSUE TITLE
When you select a group chat/channel with specific name pattern, selection in chat list does not change

### ISSUE THREAD

**Issue by Kenya-West** [UnigramDev/Unigram#2998]
**Describe the bug**
Select a chat in chat list, try to search specific group `VkNet. NETStandard2.0 и .NET6`. Select the chat you searched for and Unigram opens the chat, but selection in chat list does not change.

**To Reproduce**
1. Select any chat in chat list
2. Try to search specific group with name `VkNet. NETStandard2.0 и .NET6`
3. Select this chat
4. Unigram opens the chat, but selection in chat list does not change

**Expected behavior**
Selection in chat list should change in favor of `VkNet. NETStandard2.0 и .NET6` chat.

**Screenshots**

https://user-images.githubusercontent.com/12271104/226088656-a1384a3b-4672-4750-8137-f2c879a3660e.mp4

**Version Info**
 - Unigram: 9.3 (7970) x64
 - Windows: 11 latest stable

**Additional context**
With any other chat name, it works properly. With this `VkNet. NETStandard2.0 и .NET6` one - the bug happens.

**Comment by Kenya-West** [comment]
@FrayxRulez is it resolved or not confirmed?

**Comment by FrayxRulez** [comment]
![image](https://user-images.githubusercontent.com/8152849/228614094-12391419-342d-43a2-956a-2852ced94267.png)
