### ISSUE TITLE
Overlapping strings after swipe and release to record voice

### ISSUE THREAD

**Issue by luccascomvoce** [UnigramDev/Unigram#3000]
**Describe the bug**
Texts overlap after swipe and release to record a voice message.

**To Reproduce**

1. Open a chat with permission to record audio
2. Quick swipe and release button to record audio
3. You might see overlapping strings if you go fast enough

**Expected behavior**
The display should be cohesive, the text next to the "cancel" button shouldn't appear

**Screenshots**

https://user-images.githubusercontent.com/65538684/226264469-20e6fd00-b450-4402-aee0-7b32d3011b1f.mp4

**Version Info**
 - Unigram: 9.5 8035
 - Windows 11 PRO 22H2

**Additional context**
Sometimes it happens, sometimes it doesn't

**Comment by FrayxRulez** [comment]
This has been fixed at some point
