### ISSUE TITLE
Suggestion: Support for the larger photo resolution

### ISSUE THREAD

**Issue by TigerCubDen** [UnigramDev/Unigram#3002]
As for Telegram, they used value of 1280 (HD Resolution) for the maxWidth and maxHeight parameters in the past. And from now, the value increased to 2560 px. That's better for Unigram to keep pace with Telegram client and bring better experience for users.

**Comment by FrayxRulez** [comment]
@TigerCubDen This didn't happen yet.

**Comment by TigerCubDen** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6520

**Comment by FrayxRulez** [comment]
@TigerCubDen That's just an experimental setting. That's disabled by default.

**Comment by megapro17** [comment]
This setting has worked perfectly for over 2 years. It doesn't make any difference to normal clients either, absolutely no problems. But for those who have it enabled, it gives a huge advantage in image quality. This resolution should be the default! 1280 image is incredibly low quality
