### ISSUE TITLE
Version is not copyable

### ISSUE THREAD

**Issue by xperiandri** [UnigramDev/Unigram#3007]
**Describe the bug**
Cannot copy Unigram version

**To Reproduce**
1. Go to Settings
2. Rigth click on version below the Confidential Policy item

**Expected behavior**
Context menu with Copy item appears

**Screenshots**
![image](https://user-images.githubusercontent.com/2365592/227912854-88d35b85-83e9-4ded-83dc-358f27b7ef3b.png)

**Version Info**
 - Unigram: 9.3.7070 x64
 - Windows: 10.0.22621.1265

**Comment by MarcAnt01** [comment]
I think it'd be a great enhancement to allow to copy also the Windows version from there. In this way the section for bug reports wouldn't have to be filled manually
