### ISSUE TITLE
Delete messages doesn't always work

### ISSUE THREAD

**Issue by Fernandus91** [UnigramDev/Unigram#301]
As title says, I was trying to delete some messages/videomessages from a chat, using also "delete for..." option, and apparently it worked. When I re-entered that chat, the messages was there.

App build: 0.2.317.0
OS version: Windows 10 Mobile (14393.1358) on NOKIA Lumia 830

**Comment by Hachinamio** [comment]
I also have this issue. I deleted messages conversation on my laptop. When i open app on my phone, conversation still there.

**Comment by FrayxRulez** [comment]
I need more infos because I'm not able to reproduce this.

**Comment by Fernandus91** [comment]
@FrayxRulez Just yesterday I tried exiting and deleting a group from Unigram (last version), but in Telegram on my laptop it was still there, and after a while it was again in Unigram too.

**Comment by FrayxRulez** [comment]
I thought you were talking about single messages and not full chats. 
There is a huge difference, can you be more precise?

**Comment by Fernandus91** [comment]
The problem still persists for single messages, but it is also present for full chats. And it is quite simple, just as I wrote: when you want to delete a message or a full chat, Unigram apparently does the action, but effectively it does not (I tried to be more precise as I can, but my english can fail me. If you have any doubt, can I write this in italian?).

**Comment by FrayxRulez** [comment]
I can understand, but... A chat? A channel? A group? A supergroup? Same for the message.

**Comment by Fernandus91** [comment]
I've tested it this way: 
- tried deleting a single message in a random chat, and it did not work
- tried deleting full random chat and again, it did not work
- tired exiting a group and deleting the chat, same (and in this case, i am in the group yet)

**Comment by FrayxRulez** [comment]
I'm closing this. Now you can leave a _normal group_ (Delete and exit) without problems.
I can't still reproduce the single message deletion in any situation (user chat, group chat, supergroup chat, channel, messages sent or received, always deleted without problems)
