### ISSUE TITLE
Recent actions are not working any longer

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#3011]
**Describe the bug**
If I go to recent actions of a group, nothing is being displayed 

**To Reproduce**
1. Choose a group where you're an admin
2. Go to edit section
3. Go to admins section
4. Go to recent actions

**Expected behavior**
See recent actions

**Screenshots**
![image](https://user-images.githubusercontent.com/43090263/229183250-83d6d565-e97b-4347-83a0-943493820671.png)
![image](https://user-images.githubusercontent.com/43090263/229183842-9e868484-1dce-4330-8c3a-fdeab3bec9b0.png)

**Version Info**
 - Unigram: 9.5 (8095) X64 Direct
 - Windows: 11 Pro 22624.1470

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/7be0275b4e8e3b2c0565e9febbbe5a84a5c276c8
