### ISSUE TITLE
Cannot apply custom language packs.

### ISSUE THREAD

**Issue by ArakawaHenri** [UnigramDev/Unigram#3012]
**Describe the bug**
After upgrading to the latest version of Unigram, support for custom language packs is likely problematic.

**To Reproduce**
Any of these language packs listed are not appliable:
https://t.me/setlanguage/taiwan
https://t.me/setlanguage/zhcncc
https://t.me/setlanguage/classic-zh-cn

**Expected behavior**
Language packages normally applied.

**Screenshots**
![image](https://user-images.githubusercontent.com/17510335/229368100-3f5cd0b5-5cf6-4cb2-9566-9e7aa2cb524c.png)

**Version Info**
 - Unigram: [e.g. 9.5.8102 x64]
 - Windows: [e.g. Windows 11 22H2 22621.1485]

**Additional context**
btw, "Telegram Android" seems to be a typo.

**Comment by FrayxRulez** [comment]
Custom langpacks at the moment are not supposed to work, but they should be enabled some day in the future. (Typo fixed)

**Comment by FrayxRulez** [comment]
Hi, you can now add Unigram to the custom langpacks from translations.telegram.org.
