### ISSUE TITLE
Is it possible to stop unigram from automatic updates?

### ISSUE THREAD

**Issue by YoYspoon** [UnigramDev/Unigram#3015]
Been liking the app for a long time but just not a fan of auto updates in general. So wondering if it's possible to turn that feature off?

**Comment by FrayxRulez** [comment]
@YoYspoon If you want to disable auto updates you can download the app from the Microsoft Store.

**Comment by FrayxRulez** [comment]
We have this card on the bug tracker: https://bugs.telegram.org/c/27318
