### ISSUE TITLE
Spaces do not show in text field in latest update

### ISSUE THREAD

**Issue by bzarky** [UnigramDev/Unigram#3016]
**Describe the bug**

spaces do not show in text field, but are still sent. began happening immediately after update. 

**To Reproduce**
Type in message text field, space character does not show when typing, but is still sent in messages. 

**Expected behavior**
Would be nice to see spaces between words 

**Version Info**
 - Unigram: Unigram 9.5 (8130) X64 Direct 
 - Windows: 10 22H2

**Comment by bzarky** [comment]
looks like status messages (like "user is typing* also are missing spaces

**Comment by FrayxRulez** [comment]
What's your app and keyboard language?

**Comment by FrayxRulez** [comment]
@bzarky Can you try to set the emoji style to Microsoft? Settings > Appearance > Stickers > Emoji > Emoji style

**Comment by bzarky** [comment]
US English, and emoji style is already microsoft

**Comment by bzarky** [comment]
Here is a video showing the issue in action. 
[https://imgur.com/a/Wimqj6Q](url)

**Comment by bzarky** [comment]
In the mean time, is there a way i can roll back a version?

**Comment by FrayxRulez** [comment]
@bzarky Then can you try Apple?

**Comment by bzarky** [comment]
Hi, Switching emoji style seemed to have fixed it? 
I switched to apple emoji style, and the issue went away, and then I switched back to microsoft and the issue does not seem to be present anymore. 
I'm not really gonna pretend i know what I'm talking about, but what was the issue?

**Comment by bzarky** [comment]
I have some new information, If i close the window and reopen it while the program is still running, the issue recurs and i have to change the emoji style again to fix it.

**Comment by bzarky** [comment]
I completeley deleted and reinstalled Unigram and all its user data and the issue still recurs.

**Comment by FrayxRulez** [comment]
@bzarky Yeah deleted and reinstalling Unigram and all its user data rarely solves an issue, especially if its a graphical one connected to a font.

**Comment by FrayxRulez** [comment]
The workaround until an update is released is to use Apple emoji.

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/52711b2d451652cd6ed7bdecc09ef0593e4f6fd7. An update will be released later/tomorrow.

**Comment by bzarky** [comment]
OK thank you.
