### ISSUE TITLE
Line height of messages is incorrect in latest update

### ISSUE THREAD

**Issue by Dustin-Jiang** [UnigramDev/Unigram#3017]
**Describe the bug**
After latest update to v9.5 (8130), the line height of multiline text message is too compat to read comfortably, especially under CJK (Chinese, Korean, Japanese) environment. 

**To Reproduce**
1. Go to a chat window
2. Send a multiline text message or a long message that occurs line wrap
3. You may find the line height is not comfortable to read because it is too compat. 

**Expected behavior**
A comfortable and normal line height

**Screenshots**
![图片](https://user-images.githubusercontent.com/56217843/230708363-3fc46802-7462-497d-8ebb-e72d3822af29.png)

You can see that in the first example message, the `g` and the `l` at the next line glued together; and nearly every Chinese character is also too close vertically to read

**Version Info**
 - Unigram: 9.5 (8130) x64 direct
 - Windows: Windows 10 21h2 1904

**Comment by Dustin-Jiang** [comment]
Sorry for complainant.

But I think it **IS** a significant and annoying UI/UX issue that SHOULD NOT have any reply after a week. 

Isn't this issue reproducible? If so, I'll try reinstalling the app on my device and close this issue. 

Sorry again.

**Comment by FrayxRulez** [comment]
@Dustin-Jiang The issue was fixed pretty on the same day you reported it. Did you try to update the app?

**Comment by Dustin-Jiang** [comment]
Oh my bad.

I haven't check it yet. Hope the issue has been fixed and I'll close this issue. 

Sorry again :)
