### ISSUE TITLE
Issue to test GitHub integration in @unigraminsiders

### ISSUE THREAD

**Issue by makisukurisu** [UnigramDev/Unigram#3018]
Does it work? If no – please, add the integration.

*Please, remove the issue afterward.

**Comment by depriGeo** [comment]
> Does it work? If no – please, add the integration.
> 
> *Please, remove the issue afterward.

**Comment by makisukurisu** [comment]
Ping

**Comment by makisukurisu** [comment]
@makisukurisu Pong

**Comment by AsrorbekDev** [comment]
@makisukurisu The end.
