### ISSUE TITLE
Opening contact from People app does not select it in Unigram

### ISSUE THREAD

**Issue by xperiandri** [UnigramDev/Unigram#302]
1. Open contact in People app
2. Click on Unigram icon or Send message item
3. Unigram opens but contact is not being selected

**Comment by FrayxRulez** [comment]
Duplicate of #297

**Comment by xperiandri** [comment]
But when I do this no exception message appear. Is it swallowed?

**Comment by FrayxRulez** [comment]
It's the same issue, with error message or not, this ticket might be more generic, but I keep the other one as older
