### ISSUE TITLE
Unigram crashed or not working

### ISSUE THREAD

**Issue by ragul-19** [UnigramDev/Unigram#3026]
I downloaded unigram through windows store and I changed the download storage path to another drive, it just stopped working just blank screen and crashes. if I reset and restore to old settings it works fine but if I change again same thing happens again.

**Comment by FrayxRulez** [comment]
@ragul-19 This is somehow expected with some external hard drives. I recommend you to either fully move the app to it from your system settings, or to keep Unigram in the main drive.

**Comment by makisukurisu** [comment]
Hello!
Thanks for your report, but, it's best to report bugs on [Telegram's bugs/suggestions platform](https://bugs.telegram.org).

You probably have to send [tdlib log (-s)](https://github.com/UnigramDev/Unigram/blob/develop/Documentation/TDLib-logs.md), preferably to [Fela](https://frayxrulez.t.me) describing (or linking) the issue.

But, as far as I know, changing the downloads path is generally not a good thing on Unigram. It causes all sorts of problems, so it's recommended to stick to the default one.

However - you can try (though there are no guarantees for any improvements) to [change the system path for Windows/Microsoft Store apps](https://support.msecure.com/en/support/solutions/articles/36000130212-install-or-move-microsoft-store-apps-on-separate-drive).
This way Unigram and other "modern" apps will be installed (perhaps a reinstall is required), and their data will be stored, on the desired disk.

**Comment by ragul-19** [comment]
@FrayxRulez This is not a external drive it is partition in the main drive.

**Comment by FrayxRulez** [comment]
@ragul-19 Yeah anyway, UWP is very restrictive with file permissions and there’s nothing that can be done

**Comment by ragul-19** [comment]
Now it works but crashes when try to scroll in channel

**Comment by FrayxRulez** [comment]
@ragul-19 I don’t think that’s a good idea to set a custom download path, I will just remove the option. Fully move the app to that drive.
