### ISSUE TITLE
I can install "apple.ttf" on Windows?

### ISSUE THREAD

**Issue by niksavc** [UnigramDev/Unigram#3028]
im getting error for installing my windows.

**Comment by FrayxRulez** [comment]
You probably can, but I'm not sure whether is it supported everywhere or not. Take a look [here](https://github.com/perguto/Country-Flag-Emojis-for-Windows).

**Comment by niksavc** [comment]
![image](https://user-images.githubusercontent.com/58150480/235978634-ab810629-a801-497f-90b0-83572d6f18d9.png)
why are they square?

**Comment by FrayxRulez** [comment]
Because as I said I'm not sure if the font is supported everywhere or not. Looks like not.

**Comment by FrayxRulez** [comment]
What are you trying to do?

**Comment by niksavc** [comment]
I'm testing the font on Windows to see if it works. Unfortunately, it does not support it.

**Comment by niksavc** [comment]
![image](https://user-images.githubusercontent.com/58150480/235999056-1d307c04-3613-4284-bf55-0c2c1f455490.png)
how2fix?

**Comment by FrayxRulez** [comment]
It can't be fixed, the font is not made to be installed right away, we use it with DirectX in our app code
