### ISSUE TITLE
Display user name in People app

### ISSUE THREAD

**Issue by xperiandri** [UnigramDev/Unigram#303]
It would be nice to see Telegram user name in a contact card of People app

**Comment by FrayxRulez** [comment]
I've just took a look and it is just possible to add a generic `Nickname` field.
I tried, in the doubt, but after adding it
1) it isn't shown anywhere in the People app
2) other Unigram integrations with the app are evanished

So for the moment I'm closing this

**Comment by xperiandri** [comment]
OK, if you fix the ability to open a chat from People app it would be nice.

**Comment by FrayxRulez** [comment]
Already fixed in source code (Y)
