### ISSUE TITLE
Add support .exe installer

### ISSUE THREAD

**Issue by dedsecproyt** [UnigramDev/Unigram#3030]
Pls add .exe for win installer like default exe telegram installer and tdata folder for account session's

**Comment by MarcAnt01** [comment]
Hi, UWP apps do not support .exe installers. You can find the .mxis installer [here](https://unigramdev.github.io/)

**Comment by dedsecproyt** [comment]
but it can fork and made exe installer

**Comment by MarcAnt01** [comment]
> but it can fork and made exe installer

Since 2015 no-one has managed to do that, you can try

**Comment by FrayxRulez** [comment]
@MarcAnt01 Creating an exe installer over a msixbundle is not a problem, neither to make an exe installer that just registers the app from the layout. But in the end it won’t be any different than running the msixbundle directly so I see very little value in doing this.
