### ISSUE TITLE
Strange post width

### ISSUE THREAD

**Issue by specblades** [UnigramDev/Unigram#3031]
Can minimum post width be set to smtn like 40-60% of window size or any other solve?

See how it strange
![image](https://github.com/UnigramDev/Unigram/assets/113993746/5fdd93c7-23b0-45e6-b8b8-0bccc09e7116)

**Comment by MarcAnt01** [comment]
There is a huge banner telling not to report bugs on GitHub

**Comment by MarcAnt01** [comment]
Whatever, this is also a duplicate of https://github.com/UnigramDev/Unigram/issues/1784
