### ISSUE TITLE
Can't build webrtc - patch doesn't apply

### ISSUE THREAD

**Issue by AqlaSolutions** [UnigramDev/Unigram#3038]
![image](https://github.com/UnigramDev/Unigram/assets/3465565/dd2149d0-235d-4add-896a-b22ac8f75e9b)

**Comment by FrayxRulez** [comment]
What patch are you trying to apply and how do you apply it?

**Comment by AqlaSolutions** [comment]
This patch is applied inside `acquire.cmd`. Also build instructions say to run `acquire-m108.cmd` which is not present in the folder, only `acquire.cmd` is.

**Comment by atrdev-rgb** [comment]
on start -> Libraries/webrtc/acquire.cmd

Hook 'download_from_google_storage --directory --recursive --num_threads=10 --no_auth --quiet --bucket chromium-webrtc-resources src/resources' took 123.01 secs
Hook 'vpython3.bat src/testing/generate_location_tags.py --out src/testing/location_tags.json' took 34.79 secs
Running hooks: 100% (30/30), done.

Adding forked Telegram+UWP upstream
error: pathspec 'm112' did not match any file(s) known to git
error: patch failed: boringssl/BUILD.gn:65
error: boringssl/BUILD.gn: patch does not apply
error: patch failed: crc32c/BUILD.gn:40
error: crc32c/BUILD.gn: patch does not apply
error: patch failed: libvpx/BUILD.gn:55
error: libvpx/BUILD.gn: patch does not apply
error: patch failed: pffft/BUILD.gn:7
error: pffft/BUILD.gn: patch does not apply
error: patch failed: include/libyuv/convert.h:910
error: include/libyuv/convert.h: patch does not apply
error: patch failed: source/convert_to_i420.cc:27
error: source/convert_to_i420.cc: patch does not apply
error: patch failed: vp9/encoder/arm/neon/vp9_diamond_search_sad_neon.c:220
error: vp9/encoder/arm/neon/vp9_diamond_search_sad_neon.c: patch does not apply
