### ISSUE TITLE
Sort and group contacts

### ISSUE THREAD

**Issue by xperiandri** [UnigramDev/Unigram#304]
Add contacts sorting and grouping them by first letter. As it is impossible to find a one in a an unsorted list

**Comment by larsschellhas** [comment]
The contact list is sorted by the recent activity. You can find all your contacts via the search bar, quick and easy :)

We discussed this topic often and came to the conclusion, to keep it that way :)

**Comment by xperiandri** [comment]
Like this?
It does not work
![image](https://user-images.githubusercontent.com/2365592/27332000-bd3b5370-55c8-11e7-8439-9ff2050c6377.png)

Whereas his chat is here
![image](https://user-images.githubusercontent.com/2365592/27332029-d82b711a-55c8-11e7-8617-49f0410019d9.png)

**Comment by FrayxRulez** [comment]
We have some transliteration issues right now

**Comment by xperiandri** [comment]
Finally I can't find a contact neither within app nor open it from People app which is ridiculous!
