### ISSUE TITLE
Release: can't build solution in VS - diifferent zlib1.dll

### ISSUE THREAD

**Issue by AqlaSolutions** [UnigramDev/Unigram#3043]
When I try to build, it says that these files are different so it can't continue:

* x64\Release\Telegram.Native\zlib1.dll
* zlib1.dll from Telegram.Td nuget package

It works ok when I switch Telegram.Native project to Debug while leaving everything else in Release configuration.

Can you help with this, please?

**Comment by FrayxRulez** [comment]
@AqlaSolutions You can just replace one of the two zlib1.dll with the other.

**Comment by AqlaSolutions** [comment]
It doesn't work if I just replace it in the output folder (it's replaced by the compiler several times during build). I need to figure out where Telegram.Native takes its zlib1.dll but I didn't find the original where it should be replaced. May be it's taken somewhere from the system.

I don't want to replace it in the nuget package because then I have to put the original back each time I build in Debug.

**Comment by FrayxRulez** [comment]
@AqlaSolutions If you followed the build instructions zlib1.dll is taken from vpkg (you compiled it in one of the dteps)
The idea is that if you compile everything yourself zlib is the same in all the projects, while if you use an existing tdlib nuget package then you’re using my zlib.

**Comment by AqlaSolutions** [comment]
I compiled everything myself but I could use several different instances of vpkg because previously I tried to compile tdlib independently from another directory. This might be the cause. Ok, then I guess I have to replace it in my nuget package. I hope tdlib will work with the replaced zlib.dll.

**Comment by FrayxRulez** [comment]
@AqlaSolutions Yeah it’s better if Unigram and TDLib use the same vcpkg directory, so they can share all libraries and avoid this kind of issues. I’ll try to update the documentation to make it clear
