### ISSUE TITLE
Is it possible to move all existing code to class library?

### ISSUE THREAD

**Issue by AqlaSolutions** [UnigramDev/Unigram#3044]
I'm developing a fork and I want to speed up compilation. I tried to move existing code into a class library so that it doesn't need to be recompiled along with my changes but I encountered an issue. 

Could you check this please? 

https://stackoverflow.com/questions/76694179/launch-uwp-app-from-class-library-project

**Comment by FrayxRulez** [comment]
Code that you don't change isn't recompiled.

**Comment by AqlaSolutions** [comment]
I can't agree with you. The whole project is recompiled with xaml generation stage even with 1 line change in the source.

**Comment by FrayxRulez** [comment]
@AqlaSolutions This is a bug in the XAML compiler. As a workaround you can copy Visual Studio installation folder\VC\Tools\MSVC\14.xx\bin\Hostx64\x64\vcmeta.dl to Visual Studio installation folder\Common7\IDE\VC\bin\amd64\vcmeta.dll. 
If the folder “amd64” doesn’t exist, you can simply create it.
