### ISSUE TITLE
How to open message link from the command line?

### ISSUE THREAD

**Issue by snowman** [UnigramDev/Unigram#3045]
I tried:

```sh
$ where Telegram.exe
C:\Users\<user_name>\AppData\Local\Microsoft\WindowsApps\Telegram.exe

$ Telegram.exe -- 'https://t.me/<channel_name>/<message_id>'
$ Telegram.exe -- 'tg://resolve?domain=<channel_name>&post=<message_id>'
```

but not luck.

**Comment by FrayxRulez** [comment]
Simply opening the `tg` link without specifying the process should do the trick.

**Comment by snowman** [comment]
When open `tg` link, it opens `Telegram`, *NOT* `Unigram`.

I use `ahk` to simulate:
1. Save `tg` link to clipboard
2. Open Unigram
3. Press `Ctrl+0` go to `Saved Messages`
4. Send clipboard content
5. Click on `tg` link jump to the message

**Comment by makisukurisu** [comment]
Go to settings, and set default app for tg links:
![image](https://github.com/UnigramDev/Unigram/assets/49622129/d999994a-4a13-448e-aef2-4ca0011498d5)

For some reason, it was set to TD*** on my system too.

**Comment by FrayxRulez** [comment]
> For some reason, it was set to TD*** on my system too.

When you have multiple apps that handle the same protocol, the user will ask you which one you want to use until you check the option not to get asked anymore.

**Comment by snowman** [comment]
Thanks for helping.

Now after change `Choose default apps by protocol` settings,
![image](https://github.com/UnigramDev/Unigram/assets/16096559/1f8a5c11-1816-4d73-844e-059853a2f1af)
Either by click `tg` link or run `start 'tg://resolve?domain=<domain>&post=<post_id>'` bring `Unigram` to front and opens that message!

**Comment by FrayxRulez** [comment]
I added explicit command line handling in https://github.com/UnigramDev/Unigram/commit/4fa8e846a8ad9aedf111dfca03d4edee4b2eb6a5
Starting from the next update, `Telegram.exe tg://...` and `Telegram.exe t.me/...` will be properly handled.
