### ISSUE TITLE
Opacity animation on dragging the window

### ISSUE THREAD

**Issue by emvaized** [UnigramDev/Unigram#3046]
Sorry for opening this ticket here, I didn't find any Discussions section. 

I really like the opacity animation when you drag the Unigram window around: 
![ezgif com-video-to-gif](https://github.com/UnigramDev/Unigram/assets/37851576/72ecfa3c-83a3-490a-bfd3-3933a60bfae3) 

Is it possible to get the same effect for all other system windows, such as Settings, Explorer, Firefox? Maybe there's some utility out there which adds it system-wide? Thanks in advance

**Comment by FrayxRulez** [comment]
Hi, the transparency effect that you're showing doesn't come from Unigram itself but it's likely happening thanks to some other software on your machine.
