### ISSUE TITLE
can't open an issue....

### ISSUE THREAD

**Issue by abrogard** [UnigramDev/Unigram#3049]
sorry about this...   I want to go to that telegram link to open an issue there but when I do it wants me to give my phone number which I do and then it says it has sent me a message 'to my account' 'via telegram' but i find no messages anywhere and simply cannot proceed.
sorry to mess your threads with this but you can delete it after, hopefully, steering me to some place I can seek advice on why I cannot switch audio back on on unigram videos?

**Comment by FrayxRulez** [comment]
You are entering the wrong phone number on the website. Remember to include the international prefix.
Another solution is to send a link to bugs.telegram.org to yourself on Telegram and click on it, you will be automatically logged into the website.
