### ISSUE TITLE
Hi 👋

### ISSUE THREAD

**Issue by PyaePhyo8612** [UnigramDev/Unigram#3054]
Please do not report bugs or make suggestions/feature requests through issues on GitHub. We have moved to https://bugs.telegram.org/ , please refer to the README for further information.

**Comment by makisukurisu** [comment]
Hello, @PyaePhyo8612 , please do not create issues here, _especially if you don't change the message asking not to create issues here_.

If you have any questions regarding the app, you are welcome at:
https://t.me/unigraminsiders

If you want to report a bug, or suggest a feature, go to:
https://bugs.telegram.org

Thank you! I'll close this issue now.
