### ISSUE TITLE
Errors before building

### ISSUE THREAD

**Issue by zandiarash** [UnigramDev/Unigram#3057]
Hello dear community
I want to build Unigram and I've done build instructions step by step but I've faced with these errors, Can anyone tell me how to solve them?

OS : Windows 11 22H2 22621.2134
Visual Studio : 2022 Version 17.7.4

![Untitled](https://github.com/UnigramDev/Unigram/assets/10775073/fea38502-c209-4d24-b455-ad6bf62166d0)

**Comment by FrayxRulez** [comment]
I've just done a small edit to the build instructions, but from what I can see in the screenshot you didn't follow any of the build steps.
