### ISSUE TITLE
a kritical accessibility bug has been reintroduced again after long time that it has been fixed in one of the beta versions

### ISSUE THREAD

**Issue by amirmahdifard** [UnigramDev/Unigram#3060]
yesterday that the beta version (10.2.0.9120_x64) has been releaced, it fixed a huge problem that blind people wer dealing with for actually a long time, from the start of unigram's usage for blind comunity until then: it fixed the focus problem: for example, when we opened a chat, it properly mooved us to the unread messages part, or the part where we left it before: when we searched something in the chat, it was finally functional, and it properly moved our focus to the wanted message: when we klicked on a replyed original message or the pinned message or klicked on a link that mentions a specific message, it properly and exactly moved our focus to wanted message: this is a huge thing that was mainly holding so many people from not being able to do some things with unigram and they had to do it with android: but sadly, i don't know that what happened to the todays beta version (10.2.1 (9135) X64), this fix got broke again: developer, we, all blinds, really wish you to give us this huge fix again: very thanks to you.

**Comment by MarcAnt01** [comment]
As it is written in the texture that you deleted and ignored, bug reports here are no longer allowed.

(the bug fix is in the next beta)

**Comment by amirmahdifard** [comment]
@MarcAnt01 i haven't ignoard that, just since this is a bug that is holding us back and we are dealing with it, since years, i wanted to say it here so develepor can see it and don't loos track of what has revurted this fix so he can refix it again: can i kindely request you to open this just until fela seen it? then you can freely close it: thanks.

**Comment by MarcAnt01** [comment]
@amirmahdifard rules are for everybody, you are no exception

**Comment by MarcAnt01** [comment]
Also please stop spamming here, the bug has alreadg been fixed as I already told you
