### ISSUE TITLE
Weird if condition

### ISSUE THREAD

**Issue by AleTopp** [UnigramDev/Unigram#3061]
Hello,
I was exploring how Unigram uploads files and found this if condition I think it's wrong (or there is something I do not understand below):

https://github.com/UnigramDev/Unigram/blob/e4e4fa5f3b6e477d8c57cf58159866e50e452771/Telegram/ViewModels/ComposeViewModel.cs#L404

and by the context I think it should be:

`if (permissions.CanSendPhotos && permissions.CanSendVideos)`

By the Git Blame I see @FrayxRulez is the one who made the commit. 
Sorry to disturb in case this wasn't necessary.

**Comment by FrayxRulez** [comment]
@AleTopp @FrayxRulez is also the only one to commit in this repository.

**Comment by FrayxRulez** [comment]
@AleTopp But yes, it’s correct. Thank you for pointing out.

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/12b5e31aa74b25eacd5d1a8400c956c4edc234da
