### ISSUE TITLE
Main window crashes with security code enabled version 10.2.3 (9241)

### ISSUE THREAD

**Issue by MaximvsStorm** [UnigramDev/Unigram#3064]
Main window crashes with security code enabled version 10.2.3 (9241) The application becomes non-functional. Only the tray icon remains.

**Comment by MarcAnt01** [comment]
Bug reports on GitHub are no longer allowed, as it's written in the texture that you ignored.

**Comment by MaximvsStorm** [comment]
Нахуй иди. гнида!
