### ISSUE TITLE
Long-touching "send" button sends a message

### ISSUE THREAD

**Issue by wojpawlik** [UnigramDev/Unigram#3065]
## Expected behavior 

Long-touching "send" button should allow to use the menu.

## Actual behavior

https://github.com/UnigramDev/Unigram/assets/23058303/d23948bf-c631-4cbd-ad6b-59493ce63162

**Comment by makisukurisu** [comment]
Hi, please do not remove messages asking you not to report bugs here.

And don't report new bugs here, please.

Use bugs.telegram.org instead.
I'll close this issue as not planned.

Thanks for understanding.

**Comment by FrayxRulez** [comment]
I likely fixed the issue and I will release a beta soon.
As @makisukurisu mentioned, it would be better to use [bugs.telegram.org](bugs.telegram.org) to report issues.
