### ISSUE TITLE
Error Building without WebRTC

### ISSUE THREAD

**Issue by atrdev-rgb** [UnigramDev/Unigram#3068]
using Telegram.Views.Calls;

namespace Telegram.Services

VoipGroupService.cs  
Severity Code Description Project File String Suppression State
Error CS0234 The type or namespace name 'Calls' does not exist in the namespace 'Telegram.Views' (the assembly reference may be missing). Telegram D:\Unigram\Telegram\Services\VoipGroupService.cs 20 Active

VoipService.cs  
Severity Code Description Project File String Suppression State
Error CS0234 The type or namespace name 'Calls' does not exist in the namespace 'Telegram.Views' (the assembly reference may be missing). Telegram D:\Unigram\Telegram\Services\VoipService.cs 17 Active

**Comment by FrayxRulez** [comment]
You can fix the code and open a pull request.
