### ISSUE TITLE
Duplicate in Shared Media page

### ISSUE THREAD

**Issue by Fernandus91** [UnigramDev/Unigram#307]
Shared Media page shows two photos icons, the first is empty. Also, other categories shows at least two months of media that you can't open.
App version: Windows Store
![wp_ss_20170619_0001](https://user-images.githubusercontent.com/29466231/27328022-dc969792-55b0-11e7-818c-da34bb5902ff.png)

**Comment by larsschellhas** [comment]
Please be a little more precise with the title in the future :) for example "duplicated shared media page"

This helps us to better keep track of the problems :)

**Comment by Fernandus91** [comment]
Done! :) thanks for your patience @larsschellhas

**Comment by auchri** [comment]
"Duplicated photo icon in shared media page" would be even better 😉
