### ISSUE TITLE
WatchDog FileNotFoundException

### ISSUE THREAD

**Issue by atrdev-rgb** [UnigramDev/Unigram#3070]
WatchDog.Initialize();

public static void Initialize()
{
    NativeUtils.SetFatalErrorCallback(FatalErrorCallback);
`System.IO.FileNotFoundException: "The specified module was not found. (Exception from HRESULT: 0x8007007E)"`

 public NetworkService(IClientService clientService, ISettingsService settingsService, IEventAggregator aggregator)
 {
          _watcher = HttpProxyWatcher.Current;
`System.IO.FileNotFoundException: "The specified module was not found. (Exception from HRESULT: 0x8007007E)"`

Please help me find this missing file

**Comment by FrayxRulez** [comment]
@atrdev-rgb Hi, can you avoid creating a new issue for each problem that you’re encountering while trying to compile the app and just use one?

We can’t know that file you are missing, it could be anything. This refers most likely to a C++ library that you had to build.

**Comment by atrdev-rgb** [comment]
I did everything according to the instructions. Everything came together without errors. The only thing I did was turn off calls. But I checked it when creating it. Dll files are located next to the exe file.

For some reason, Telegram.Native.dll does not load. Although it is assembled without errors according to your instructions

**Comment by Flores1124mmorales** [comment]
Es bonito trabajar telegram

**Comment by Yvmsi1100** [comment]
أنا
