### ISSUE TITLE
App Installer failed to install package dependencies. Ask the developer for package.

### ISSUE THREAD

**Issue by DevHanza** [UnigramDev/Unigram#3072]

**Comment by makisukurisu** [comment]
Hello!

Could you try to install dependencies from https://unigramappx.t.me ? (Dependencies are other apps files in that channel)

If the problem persists, you can try to use PowerShell to install the app using Add-AppxPackage applet. (And let us know what the output of it is)
If you would like to get more precise instructions on that matter - let us know.

Also, I would kindly ask you not to create new issues on this repository, as the template suggested. Bug reports are to be issued on https://bugs.telegram.org, and for any other issues you can contact us on https://unigraminsiders.t.me

**Comment by MarcAnt01** [comment]
I assume the issue has been solved, since no further comments were made
