### ISSUE TITLE
Thanks for that

### ISSUE THREAD

**Issue by ecomcodeLab** [UnigramDev/Unigram#3075]
Thank you for this working way to get telegram on windows pc. i tried telegram desktop but this always wantet to have premissions i dont know why but i can open it directly with exe i get error groupadmin has restricted this app

but unigram is working great

**Comment by Abdulaziz-Faqihi** [comment]
@badplay Unigram is actually an excellent program

**Comment by MarcAnt01** [comment]
Hello, Unigram is a UWP app, hence it's not possible to run the .exe file directly as you wish
