### ISSUE TITLE
The problem with the session in Unigram

### ISSUE THREAD

**Issue by serjan-nasredin** [UnigramDev/Unigram#3076]
When logging in through devices, I can't log out of Unigram right away. I had to end the session twice to stop writing to Saved Message (bookmarks).
![image](https://github.com/UnigramDev/Unigram/assets/67647968/e2e28083-0585-4f56-b9ea-08672305ffe6)
I try to log out of Unigram via my phone, and at the same time I write to Saved Massage.

**Comment by FrayxRulez** [comment]
Not Unigram issue, and again reporting to bugs.telegram.org is the recommended way.
