### ISSUE TITLE
Open last folder

### ISSUE THREAD

**Issue by Maasea** [UnigramDev/Unigram#3079]
Regardless of whether it is restarted or opened from minimization, Unigram always opens 'All chats'. 

I tried Telegram Desktop, and opening from minimization opens the last folder.

**Comment by FrayxRulez** [comment]
Unigram is not aware of whether you're restoring the window from minimization or launching it from scratch, so this feature can't be implemented.

**Comment by Maasea** [comment]
Can you provide the button: always open last folder？There's no need to determine whether restoring  from minimization or launching.

**Comment by FrayxRulez** [comment]
@Maasea No, a similar feature is already provided by Telegram Premium
