### ISSUE TITLE
Missing features: Option  for sticker/emoji panel to require a click instead of hover & compact chat lists

### ISSUE THREAD

**Issue by chaosdrop** [UnigramDev/Unigram#3084]
The last telegram client I used, had an option to make the sticker/emoji panel only open on a click, and it made telegram far less annoying. 

The other major missing feature is compact chat lists. Everything is huge, less than half the chats I'm used to fit in the same window size, and I don't see any options to make things smaller.

**Comment by MarcAnt01** [comment]
Hello, you can disable the sticker panel opening on hover from diagnostic settings (click 10 times on Unigram version from settings) to be able to open/close only with a click.
Unigram respects the size of the window given by the system, if you think it is too small you can decrease the font/screen size from system settings.
Furthermore for the future, I ask you to report bugs/ make feature request from bugs.telegram.org as already pointed out in GitHub
