### ISSUE TITLE
Unable to install Chinese language pack @zh_CN, unable to try built-in translation from English to Chinese.

### ISSUE THREAD

**Issue by PP9995** [UnigramDev/Unigram#3093]
![Snipaste_2024-05-16_19-59-48](https://github.com/UnigramDev/Unigram/assets/40771505/5c12996d-d956-45c8-8ce2-c5816e682b7f)

![Snipaste_2024-05-16_20-02-14](https://github.com/UnigramDev/Unigram/assets/40771505/df72dd1b-55cd-43c0-81e0-83cfd5424876)

The software is very well done!
Unable to install Chinese language pack @zh_CN, unable to try built-in translation from English to Chinese.
But it can translate Chinese into English.
The official app can do it!

**Comment by makisukurisu** [comment]
For Unigram there are two Chinese translations:
- https://t.me/setlanguage/zh-hant-beta
- https://t.me/setlanguage/zh-hans-beta

You can find all the available translations by going to:
https://translations.telegram.org/en/unigram/
And hitting "Other languages..." button
