### ISSUE TITLE
https://go.cb-w.com/messaging?address=0x25D5eE3851a1016AfaB42798d8Ba3658323e6498&messagePrompt=gm&botInviteCode=xge8u1

### ISSUE THREAD

**Issue by Trickg98** [UnigramDev/Unigram#3096]
Please do not report bugs or make suggestions/feature requests through issues on GitHub. We have moved to https://bugs.telegram.org/ , please refer to the README for further information.

**Comment by Trickg98** [comment]
0x25d5ee3851a1016afab42798d8ba3658323e64980x02e7a490b936c22b59262e2d5af27485c9bf042fCutting 🔪hrough the 0s

📞 @GangstaPig
🤖 @GangstaPigBot
✖️ x.com/GangstaPigCalls

❗️Sol version will be up soon

• gangstapig.com
• docs.gangstapig.com
• disclaimer.gangstapig.com
https://t.me/GangstaPigCallshttps://x.com/Dexerto/status/17939568571799637350x02E7A490B936C22b59262e2d5af27485C9BF042f0xcde172dc5ffc46d228838446c57c1227e0b82049https://basescan.org/address/0xf1a29069ed13dae2811f21b1b5aab3cdf3f18950https://www.dextools.io/app/en/ether/pair-explorer/0x81e21c3c7977da5988a727679ae616106b4665fd?t=1716601497752<iframe id="dextools-widget"
    title="DEXTools Trading Chart"
    width="500" height="400"
    src="https://www.dextools.io/widget-chart/en/ether/pe-light/0x81e21c3c7977da5988a727679ae616106b4665fd?theme=light&chartType=2&chartResolution=30&drawingToolbars=false"></iframe><iframe id="dextswap-aggregator-widget"
    title="DEXTswap Aggregator"
    width="400" height="420"
    src="https://www.dextools.io/widget-aggregator/en/swap/eth/0x257ea2581e424ceae68bd91b5956cb28c96ee479"></iframe>https://t.me/CumRocket_2024cosmosvaloper1c4k24jzduc365kywrsvf5ujz4ya6mwympnc4enhttps://platform.arkhamintelligence.com/explorer/entity/hbliuwbhttps://www.patreon.com/posts/to-mr-picked-101668271?utm_medium=sharesheet&utm_source=sharesheet&utm_campaign=postshare_creator&utm_content=join_link

**Comment by makisukurisu** [comment]
@FrayxRulez, can you please remove this spam issue? Thanks!
