### ISSUE TITLE
设置页面动画效果过多

### ISSUE THREAD

**Issue by PandaFiredoge** [UnigramDev/Unigram#3097]
应该是鼠标按下之后再动画，而不是鼠标放上去就动画It should be animated after the mouse is pressed, not when the mouse is put on it.

**Comment by PandaFiredoge** [comment]
![动画](https://github.com/UnigramDev/Unigram/assets/131285299/576f04d0-0d73-4572-bf39-cc97b88294a7)

**Comment by PandaFiredoge** [comment]
应该是类似这样的动画It should be an animation similar to this
![59a897b33bbb7b2ef9b561a61d55952a](https://github.com/UnigramDev/Unigram/assets/131285299/a862c599-8cfa-4bb7-859c-ce53e8b45804)

**Comment by MarcAnt01** [comment]
Hello, animating on hover is a design choice. Thanks for your feedback
