### ISSUE TITLE
I don't believe this change to be correct. The tests intentionally use a different value. The .env.example file is not for running the tests.

### ISSUE THREAD

**Issue by Ahmed30mara2018** [UnigramDev/Unigram#3098]
I don't believe this change to be correct. The tests intentionally use a different value. The .env.example file is not for running the tests.

_Originally posted by @GrahamCampbell in https://github.com/laravel/laravel/pull/6407#pullrequestreview-2083567416_

**Comment by makisukurisu** [comment]
Hello, it would seem that your report is not related to Unigram.

If you have something to say about Unigram, please create a new issue, and/or, let us know https://unigraminsiders.t.me!
