### ISSUE TITLE
26bf89450175d7b5cb05c174af3bf3d897e36952

### ISSUE THREAD

**Issue by Rafee2134** [UnigramDev/Unigram#3099]
26bf89450175d7b5cb05c174af3bf3d897e36952

> _Originally posted by @Rafee2134 in https://github.com/UnigramDev/Unigram/pull/3082#issuecomment-2148797214_Batch Installation ID: - - - [ ] - [ ] - [ ] # 3f842192-6628-483e-8b2b-ec7394faeab4~~@Rafee2134 []()****~~

**Comment by MarcAnt01** [comment]
Closing, since the given pull request has been merged
