### ISSUE TITLE
No way to cancel forwarding a message on desktop

### ISSUE THREAD

**Issue by Yoshi2889** [UnigramDev/Unigram#310]
When forwarding a message on desktop and changing your mind, there is no way to cancel out of the "Select a recipient to foward to" screen (not even via the back button or Escape).

**Comment by FrayxRulez** [comment]
Considering this a duplicate of #239

**Comment by Yoshi2889** [comment]
Oh it didn't show up when I searched, my apologies.

**Comment by FrayxRulez** [comment]
No problem! Any effort is appreciated
