### ISSUE TITLE
error - $ "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -ExecutionPolicy ByPass ./build.ps1 -vcpkg_root ../../vcpkg -nupkg

### ISSUE THREAD

**Issue by chetangdoinfotech** [UnigramDev/Unigram#3100]
ckult@chetan-gdo MINGW64 /d/telecalls/Unigram/td/example/uwp (master)
$ "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -ExecutionPolicy ByPass ./build.ps1 -vcpkg_root ../../vcpkg -nupkg

given this error -
CMake Error at C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:67 (try_compile):
  Failed to configure test project build system.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)
  CMakeLists.txt:9 (project)

-- Configuring incomplete, errors occurred!
EXE RETURNED EXIT CODE 1
CALLSTACK:
Command           Arguments                            Location
-------           ---------                            --------
CheckLastExitCode {}                                   build.ps1: line 30
prepare           {}                                   build.ps1: line 46
run               {}                                   build.ps1: line 154
build.ps1         {vcpkg_root=../../vcpkg, nupkg=True} build.ps1: line 174
<ScriptBlock>     {}                                   <No file>
At D:\telecalls\Unigram\td\example\uwp\build.ps1:32 char:5
+     throw $msg
+     ~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (EXE RETURNED EX...
:String) [], RuntimeException
    + FullyQualifiedErrorId : EXE RETURNED EXIT CODE 1

**Comment by makisukurisu** [comment]
Hello, can you please provide details on your error?
Like what were you trying to do, following what instructions and on which step.

Also, please, if possible, can you paste the error inside a multiline code block (you can make one by writing \` character three times)

```
Then your error message will be shown more or less correct
```

To do this, I entered:
\`\`\`
Then your error message will be shown more or less correct
\`\`\`
