### ISSUE TITLE
Performance issues with multiple accounts and many groups

### ISSUE THREAD

**Issue by AqlaSolutions** [UnigramDev/Unigram#3101]
Steps to reproduce:
1. Add 6 accounts (3 must have premium for this to work). Or add more if you know how to overcome the limit.
2. Each account must be joined to 100-200 supergroups (don't try to join all at once or your account will be banned), channels may work too
3. Each account must have a folder with all groups and a folder for private chats
4. When you chat from the private chats folder, everything works ok
5. Now switch to the groups folder
6. Scroll chatlist to load all the groups, pick several groups one by one and scroll their history to read 100-200-300 messages
7. Try typing a message using your keyboard (just hold any letter key), you may notice 1-5 seconds lags where the app doesn't respond to any input
8. Repeat 5-7 for each account, the effect increases with each cycle

The supergroups must have 1000+ members and a flow of 3 or more messages per minute.

You may also notice the freezes when scrolling the groups folder chatlist (after it's fully loaded). Sometimes it's even not rendered properly.

According to my benchmarks, these freezes are caused by Garbage Collection.

**Comment by MarcAnt01** [comment]
Hello, as it's written in the warning that appears before creating issues, bug reports on GitHub are no longer accept. Please use https://bugs.telegram.org

**Comment by AqlaSolutions** [comment]
https://bugs.telegram.org/c/41112
