### ISSUE TITLE
Unigram versione. 10.15.3.70 installato su Xbox one s si chiude continuamente . "Premetto che non sono un esperto come voi" ma vorrei risolvere se possibile.Grazie!! 

### ISSUE THREAD

**Issue by Cioccos** [UnigramDev/Unigram#3114]

**Comment by FrayxRulez** [comment]
L'applicazione si chiude quando passi ad un gioco o durante l'utilizzo?

**Comment by FrayxRulez** [comment]
App keeps closing due to extremely low memory limits on the console.

**Comment by Cioccos** [comment]
Ok ti ringrazio....ma ora non funziona piu neanche Telegram web......insomma praticamente un disastro ### 😅😅
