### ISSUE TITLE
The automatic download file size can only be set to 2G

### ISSUE THREAD

**Issue by ymk895** [UnigramDev/Unigram#3116]
This software automatically downloads videos and files, but the maximum download limit can only be set to 2GB. I hope to increase it to 4GB, as 4GB is the limit set by Telegram. Many files now exceed 2GB  Thank you

**Comment by pratyakshm** [comment]
the android app has a limit of 2 GB 🤔

**Comment by ymk895** [comment]
But I'm using the computer version

**Comment by ymk895** [comment]
Although the Android app is limited to 2GB, I am downloading the desktop version, which should support 4GB. Many 4GB compressed files cannot be downloaded automatically. Please fix this issue. Thank you.

**Comment by FrayxRulez** [comment]
@ymk895 I just wonder how many users and how often they need to automatically download files up to 4GB.

**Comment by gus33000** [comment]
@FrayxRulez I know this is stretching this issue a tiny bit but does Unigram have size limits for auto downloaded images? I frequently end up with a lot of images downloaded regardless of size it seems, would be nice to be able to limit that, unless thats a bug. Not that 2GB or 4GB pictures are common whatsoever (I confess). But even small images of 100MB (uncompressed) are a bit, annoying.

**Comment by FrayxRulez** [comment]
@gus33000 images sent as images are always compressed and capped to 1280x1280, so there's no chance that they reach even a MB in size.
Images sent as file are treated as files, and respect files auto-download settings.

**Comment by gus33000** [comment]
> @gus33000 images sent as images are always compressed and capped to 1280x1280, so there's no chance that they reach even a MB in size. Images sent as file are treated as files, and respect files auto-download settings.

Ah right! Yeah uncompressed files would be considered files, sorry this crossed my mind completely. Thanks. I imagine theres no plan to add options to filter file types then? Anyway I know what to change now thank you
