### ISSUE TITLE
Unigram build crashes due to namespace not identified

### ISSUE THREAD

**Issue by Greenie0701** [UnigramDev/Unigram#3117]
Hello Developers!

This is an issue regarding Unigram build for windows, I have built Unigram dependencies successfully. But while building Unigram solution file via visual studio the projects telegram.stub, telegram.native.calls, telegram.native were built successfully without any compilation errors, but while building telegram target, the built interrupts due to an error mentioning namespace could not identified.
I try to find instances of these variables through the repo, but I was able to find usage of these variables rather than declaration of these variable were not found. What could the potential cause and fix for this issue?

Error Log:
![image](https://github.com/user-attachments/assets/42e34e62-8759-42be-8fa9-b75d63a7c68c)

Thanks !

**Comment by FrayxRulez** [comment]
Hi, you need TDLib version 1.8.37 to build the latest version of Unigram.

**Comment by Greenie0701** [comment]
> Hi, you need TDLib version 1.8.37 to build the latest version of Unigram.

I have built tdlib 1.8.37, but not sure why still the issue exist
Will recheck and come back

**Comment by FrayxRulez** [comment]
Those classes didn't exist prior to TDLib 1.8.37, so the most reasonable thing is that there's a mismatch with the library version.
