### ISSUE TITLE
App Crashes with Unhandled Exception at windows.UI.Xaml.dll (Help Needed!)

### ISSUE THREAD

**Issue by mags-31** [UnigramDev/Unigram#3120]
Hi, I'm new to development, and I'm trying to build Unigram. I managed to compile and build it successfully on my machine (Windows, Intel i5, VS2022), but when I hit the green "Run on local machine" button in Visual Studio, the app launches and then crashes immediately with this error:

`Unhandled exception at windows.UI.Xaml.dll in telegram.exe: 0xc000027b
`

The error seems related to `windows.UI.Xaml.dll`, and after googling a bit, I saw something about app animations possibly causing issues like this, but I’m not really sure. Is this a UI problem? Or something else I might be missing? 😅

I’d really appreciate it if someone could help me understand what’s going on here or point me in the right direction to fix it!

My Setup:
- Windows (version info)
- Intel i5 processor
- Visual Studio 2022

Sorry if this is a basic question, still learning the ropes! Thanks in advance! 🙏

**Comment by FrayxRulez** [comment]
The issue may be caused by missing DLLs in the app layout folder (Telegram\bin\x64\Debug), this seem to happen in some configurations with vcpkg libraries.

**Comment by mags-31** [comment]
Thanks for the response! but I'm not entirely sure how to identify which ones. Could you suggest how I can track or confirm what's missing in the app layout folder? 

Also, I checked the Event Viewer and found this error log related to Windows.UI.Xaml.dll. Not sure how this gonna help. But, Any guidance would be greatly appreciated.

```
Faulting application name: Telegram.exe, version: 1.0.0.0, time stamp: 0x62a3c35e
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.22621.4249, time stamp: 0x6ba81271
Exception code: 0xc000027b
Fault offset: 0x00000000005a5157
Faulting process id: 0x0x339C
Faulting application start time: 0x0x1DB26328117C07F
Faulting application path: C:Unigram\Telegram.Msix\bin\x64\Debug\AppX\Telegram.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: fd106dfc-d25c-4818-beef-ced8884e7518
Faulting package full name: 38833FF26BA1D.UnigramPreview_10.15.3.0_x64__g9c9v27vpyspw
Faulting package-relative application ID: App
```
```
AppName Telegram.exe 
  AppVersion 1.0.0.0 
  AppTimeStamp 62a3c35e 
  ModuleName Windows.UI.Xaml.dll 
  ModuleVersion 10.0.22621.4249 
  ModuleTimeStamp 6ba81271 
  ExceptionCode c000027b 
  FaultingOffset 00000000005a5157 
  ProcessId 0x339c 
  ProcessCreationTime 0x1db26328117c07f 
  AppPath C:Unigram\Telegram.Msix\bin\x64\Debug\AppX\Telegram.exe 
  ModulePath C:\Windows\System32\Windows.UI.Xaml.dll 
  IntegratorReportId fd106dfc-d25c-4818-beef-ced8884e7518 
  PackageFullName 38833FF26BA1D.UnigramPreview_10.15.3.0_x64__g9c9v27vpyspw 
```

**Comment by FrayxRulez** [comment]
Make sure that your output folder contains the following files:
```
│   App.xbf
│   AppxManifest.xml
│   avcodec-58.dll
│   avformat-58.dll
│   avutil-56.dll
│   libcrypto-3-x64.dll
│   libssl-3-x64.dll
│   libvlc.dll
│   libvlccore.dll
│   lz4d.dll
│   Microsoft.AppCenter.Analytics.dll
│   Microsoft.AppCenter.Crashes.dll
│   Microsoft.AppCenter.dll
│   Microsoft.Bcl.HashCode.dll
│   Microsoft.Graphics.Canvas.dll
│   Microsoft.Graphics.Canvas.winmd
│   Microsoft.UI.Xaml.Markup.winmd
│   Microsoft.UI.Xaml.winmd
│   Microsoft.Web.WebView2.Core.dll
│   Microsoft.Web.WebView2.Core.winmd
│   Newtonsoft.Json.dll
│   ogg.dll
│   opus.dll
│   resources.pri
│   Rg.DiffUtils.dll
│   RLottie.dll
│   RLottie.winmd
│   SharpDX.Direct3D11.dll
│   SharpDX.dll
│   SharpDX.DXGI.dll
│   SQLitePCLRaw.batteries_v2.dll
│   SQLitePCLRaw.core.dll
│   SQLitePCLRaw.provider.winsqlite3.dll
│   swresample-3.dll
│   swscale-5.dll
│   System.Collections.Immutable.dll
│   System.Reflection.Metadata.dll
│   System.Runtime.CompilerServices.Unsafe.dll
│   System.Runtime.dll
│   Telegram.exe
│   Telegram.Native.Calls.dll
│   Telegram.Native.Calls.winmd
│   Telegram.Native.dll
│   Telegram.Native.winmd
│   Telegram.Td.dll
│   Telegram.Td.winmd
│   Telegram.xr.xml
│   ucrtbased.dll
│   vs.appxrecipe
│   WebView2Loader.dll
│   zlib1.dll
│   zlibd1.dll
```
If not, then there's something to adjust in your environment depending on what files are missing.

**Comment by FrayxRulez** [comment]
Hi, I guess that you built the app using the latest version of vcpkg instead of the old recommended one.
I've updated the build instructions to support this scenario, please take a look [here](https://github.com/UnigramDev/Unigram/blob/08133f14139c535bcd71ad193a547672055b509b/Documentation/Build-instructions.md).
For reference, this is caused by a [bug in vcpkg](https://github.com/microsoft/vcpkg/issues/41782) that affects hybrid C++/C# solutions as this one. Applying the patch should solve the issue.

**Comment by mags-31** [comment]
Thanks It is working now, I replaced the old vcpkg folder with the new vcpkg folder using updated instructions, and I got my own unigram work! I'm really happy. thanks for the help.
happy to see many new versions 😄
