### ISSUE TITLE
Can't see all the text and photos when the description is too long.

### ISSUE THREAD

**Issue by Mideks** [UnigramDev/Unigram#3123]
When I am trying to write a long description, I can't scroll it, and can't see the photo. 
![image](https://github.com/user-attachments/assets/e52c9908-61e8-470d-8993-03374a5f08e6)

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/df8091089156ca73e2a441deaa4fe444a8c8f333
