### ISSUE TITLE
Message Counter Issue 

### ISSUE THREAD

**Issue by Mideks** [UnigramDev/Unigram#3132]
A fairly common bug is that the message counter shows outdated data.
How it looks in the chat list:
![image](https://github.com/user-attachments/assets/393ac146-c97b-4880-a690-e30198134a82)
Although in fact there are no unread messages in the chat anymore:
![image](https://github.com/user-attachments/assets/4a0dad43-2627-466c-a425-0b2a22a52896)
It only helps if you forcibly mark messages as read

**Comment by Mideks** [comment]
Most often I saw this bug in chats with topics enabled
It also affects the account's unread message counter, which is confusing.

![image](https://github.com/user-attachments/assets/26323c27-3209-4b92-bd06-62a8c7ecab31)
![image](https://github.com/user-attachments/assets/d489f605-4213-4bc8-9236-ae418fb9306b)

**Comment by frapox** [comment]
> Most often I saw this bug in chats with topics enabled It also affects the account's unread message counter, which is confusing.

Exactly the same here.

**Comment by FrayxRulez** [comment]
This is a known issue listed in #2953

**Comment by Mideks** [comment]
...well, this is a bug that has not been fixed for 2 years. closed as not planned. Lol. Okay.

**Comment by FrayxRulez** [comment]
It's a duplicate, there's no need to have two tickets for a bug that can't be fixed.
