### ISSUE TITLE
Restore the old minimal icon

### ISSUE THREAD

**Issue by Ehab-d** [UnigramDev/Unigram#3135]
Please restore the old mono/minimal Telegram icon because it looked so good with WhatsApp. At least an option can be put in Appearance to choose the old icon.

![image](https://github.com/user-attachments/assets/e01350db-2865-43a4-89f3-65b68b1d85e1)

**Comment by makhlwf** [comment]
@Ehab-d There's no option to change the applications icon dynamically on Windows

**Comment by FrayxRulez** [comment]
This is the new logo and that's what we like.

**Comment by Ehab-d** [comment]
@FrayxRulez Well you are right about that. But can you send me the old icon in high quality so that I can change it on my end??

**Comment by FrayxRulez** [comment]
This is GitHub, so it should be quite easy to get the old icon from the changes history.
The problem here is that this is a UWP app, it doesn't use "win32" .ico files and thus I'm not sure you can easily replace it

**Comment by Ehab-d** [comment]
@FrayxRulez Can you please help me finding the old icon? I coudn't find it in the changes history.
