### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by puneetsngh** [UnigramDev/Unigram#320]
New Windows Fluent Design

Windows 10 new sharesheet support

**Comment by TiagoDanin** [comment]
Suggestion: Blur effect in contact
![IMG](https://user-images.githubusercontent.com/5731176/27750688-48cfd102-5daf-11e7-8138-3e511cc1854c.jpg)

**Comment by TiagoDanin** [comment]
@TiagoDanin

**Comment by rabiet** [comment]
You show it yourself with your screenshot. Visibility is awful and looks aren't good either, sorry :/

**Comment by larsschellhas** [comment]
Fluent Design will be implemented in the future as most People will receive it just by the future updates coming by September.
Therefore I will Close this issue :)
