### ISSUE TITLE
Modal dialog on inline button messages

### ISSUE THREAD

**Issue by bugada** [UnigramDev/Unigram#321]
If you press an inline button and a message is returned, this message appears in a modal dialog; in telegram android this message is shown on a top layer that auto hides himself after a while. Also a solution like official telegram wp (showing the message on the status line on top) would be good imho.

![photo_2017-06-29_10-44-57](https://user-images.githubusercontent.com/4438193/27679289-8fdda8c8-5cb8-11e7-88b6-235702a211ab.jpg)

Unigram 0.3.442.0
Windows version: 10.0.15063.414

**Comment by FrayxRulez** [comment]
Showing it in the `StatusBar` would be confusing on desktop

**Comment by bugada** [comment]
Yes I agree, I've understimated the desktop version. This is UWP :-)

**Comment by larsschellhas** [comment]
Soooo... I will Close this issue then :)
if someone want to insist, be free to reopen it.

**Comment by bugada** [comment]
lars why did you close the modal dialog issue?

we agreed that the status bar was a bad idea, but the autohiding layer (centered like tdesktop, or on top like android) is a good idea because you loose time clicking on OK.

**Comment by larsschellhas** [comment]
You are right. I took your both "agree" on the bad idea "Status bar" as closing Argument. sorry
