### ISSUE TITLE
App crashes when trying to edit username

### ISSUE THREAD

**Issue by brullsker** [UnigramDev/Unigram#324]
When I tap on the "Username" field in settings page, the app crashes and  I'm on my Windows  Start screen.
I've tested this on Mobile, version 0.3.442 AND 0.3.443, bit not on PC.
My device: Microsoft Lumia 950 XL, Windows 10 Mobile Anniversary Update 10.0.14393.1066

**Comment by FrayxRulez** [comment]
Can you contact me at t.me/frayxrulez?

**Comment by brullsker** [comment]
Yes of course
