### ISSUE TITLE
fully implement share-feature

### ISSUE THREAD

**Issue by 2b2bff** [UnigramDev/Unigram#325]
The search on this page doesn't work as well. So it's pretty unusable unless someone has a specific avatar.

**Comment by larsschellhas** [comment]
Sharing from other Apps is not yet implemented. Therefore I will rename this issue.

**Comment by 2b2bff** [comment]
This explains why it is like it is... ;)

**Comment by FrayxRulez** [comment]
Implemented in https://github.com/UnigramDev/Unigram/commit/1f21ac3332995956efb3f07b0eefe6d296f75d6a

**Comment by xperiandri** [comment]
Share Target doesn't work in X pre-release
