### ISSUE TITLE
Search and send a GIF in app. 

### ISSUE THREAD

**Issue by Telescuffle** [UnigramDev/Unigram#327]
Implement a system where GIFS can be searched in app and sent in app.

**Comment by FrayxRulez** [comment]
You can use @gif inline bot to search and send gifs.

**Comment by Telescuffle** [comment]
Ahh, great. Didn't know. Thanks

**Comment by Telescuffle** [comment]
@FrayxRulez Do the GIF's actually play in preview? As mine don't move unless sent. 

Also, is there anyway to maximise the GIF previews like when viewing saved GIFs? 

Also, the app is amazing! Thanks

**Comment by FrayxRulez** [comment]
No, gifs don't move to keep the app the more performant as possible (if you use it on mobile you'll notice that even a couple playing simultaneously on screen will cause some issues)

Also maximizing is not possible _at the moment_
