### ISSUE TITLE
Markdown Messages

### ISSUE THREAD

**Issue by Silic0nS0ldier** [UnigramDev/Unigram#334]
The Telegram API already supports this, and people are able to use it via the `@bold` bot. Bot method however isn't the cleanest solution, especially when frequently and with more advanced use of Markdown syntax.

Would be nice if there were a way to send Markdown messages without an intermediate bot (which introduces privacy concerns). This could come in the form of a switch in the settings, a button that appears when markdown syntax is detected, or something entirely different.

Would also be sweet if syntax highlighting for programming languages could be a thing.

**Comment by FrayxRulez** [comment]
The app supports formatting messages using __, **, ` and triple `

**Comment by Silic0nS0ldier** [comment]
Ah. Double for `_` and `*`.

**Comment by FrayxRulez** [comment]
Yep, as Telegram Android and Desktop

**Comment by Silic0nS0ldier** [comment]
Is this markdown logic supposed to apply to notification replies to?

**Comment by FrayxRulez** [comment]
Not in production, but already done "in code"
