### ISSUE TITLE
Notifications In-App Sounds sounds play as media

### ISSUE THREAD

**Issue by DarthJahus** [UnigramDev/Unigram#335]
Version: `0.4.506.0`

When In-App Sounds are activated from Notifications and Sounds settings, they play as media (music / video), and appear in the volume panel. From there, we can tap the ▶️ button and play them again. When music is played by another application, it is stopped and replaced by that notification sound.

Moreover, In-App Sounds play even when Quiet Hours (Don't disturb) option is activated. Is it an expected behaviour? For instance, TDesktop doesn't play notification sounds when Don't disturb is turned on.

**Comment by FrayxRulez** [comment]
Closing since we're not going to have in-app notifications.

**Comment by larsschellhas** [comment]
@FrayxRulez Area you deleting them?
