### ISSUE TITLE
Cannot sign in after re-signin on Phone with Telegramm app

### ISSUE THREAD

**Issue by xperiandri** [UnigramDev/Unigram#337]
I reset my Lumia 929 and reinstalled Windows 10 1703
Then after I signed in on mobile I was like signed out on PC. However Unigram still displays UI as if I didn't signed out but empty. And doing sign out does nothing.

**Comment by FrayxRulez** [comment]
Update the app to 0.4.521

**Comment by xperiandri** [comment]
App reinstallation helped

**Comment by xperiandri** [comment]
Yep, now it is 0.4.521
