### ISSUE TITLE
Share target does not work from first lainch

### ISSUE THREAD

**Issue by xperiandri** [UnigramDev/Unigram#338]
Version 0.4.521.0
When I share with Unigram first time UI looks like this
![image](https://user-images.githubusercontent.com/2365592/28500390-1d32d322-6fd0-11e7-95c9-3b3bc066893f.png)

And nothing can be shared with anyone

**Comment by FrayxRulez** [comment]
Share is not implemented at all

**Comment by xperiandri** [comment]
OK 🙂
Then at least this is good

**Comment by ikarago** [comment]
The current share implementation is from a pretty ancient build and hasn't been updates with the rest of the app. 

I've temporarily disabled it in the newer dev-builds until we've replaced it with a newer implementation.

**Comment by ikarago** [comment]
Also, dupe of #325
