### ISSUE TITLE
Search feature in Forward dialog is missing

### ISSUE THREAD

**Issue by ikarago** [UnigramDev/Unigram#339]
The search-button on the Forward-dialog is currently static and does nothing. This needs to become a workable search option or needs to be removed.

**Comment by larsschellhas** [comment]
this issue is some month old now... Is there a solution in sight?
Maybe in combination with #594, too ?

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/54dccaf9668a824935bff3e2b3d9689eb5537b04
