### ISSUE TITLE
Annyoing notifications & no chat refresh?

### ISSUE THREAD

**Issue by Tourniquet88** [UnigramDev/Unigram#340]
Hi,

a lot of times when you're in a chat you still get windows notifications popups which are pretty annyoing. 

When you swipe them away, or just wait until they go away, somtimes the chat isn't refreshing and you can't actually see what the person has wrote.

15063.483 - 0.4.521.0

**Comment by FrayxRulez** [comment]
Refreshing issue should have been fixed by 6fcb6d86d75edfedf90dc9acbcbee3cd4b1bcf34 and 49a279d5da046a708b717b10a1310515e8459aa6
