### ISSUE TITLE
Unhandled exception thrown after sharing a Tweet from Twitter app

### ISSUE THREAD

**Issue by Silic0nS0ldier** [UnigramDev/Unigram#341]
Shared a tweet from the Twitter app via the share interface, selected Unigram as the share target.
Following this, the Unigram share-post dialog (whatever that dialogue is called) appeared, however is was missing the names of the chats.  I didn't have many chats, so I chose the top one (colour matched the intended chat). Dialog disappeared as expected, but the expected message was never sent. As such I tried again, and an unhandled exception warning appeared as I hit send (in the share-post dialog). I dismissed this first exception warning, which was soon replaced by another. I left this as is, took a screenshot, and while blacking out personal info so I can report the issue here, the app closed/crashed on its own.

![image](https://user-images.githubusercontent.com/17376090/28567996-a0820510-7177-11e7-904b-9ded63a46007.png)

Unigram version: 0.4.521.0
Twitter app version: 5.8.1.0
OS: Windows 10 Pro, version 1703, build 15063.483

If any more details are needed, let me know.

**Comment by FrayxRulez** [comment]
Have you tried to search issues by "share"?

**Comment by Silic0nS0ldier** [comment]
Seriously... Your response is to point out that it isn't finished. Sure, its not done, but that doesn't mean it should result in a crash.

**Comment by ikarago** [comment]
Dupe of #325 (https://github.com/UnigramDev/Unigram/issues/325) and the share target has been disabled in the new builds until we've replaced it with new code.
