### ISSUE TITLE
optimize "add members to groups"

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#344]
I think it would be better not to list the selected contacts in the searchbar.

Instead one should mark them (like with manage) in the contact list which is filtered by the Input in the search bar.

Further on it would be usefull to make marked contacts always visible Independent from the search Input and put them on top of the list. That way it´s easy to Control wether you are going to add someone to a Group you didn´t wanted to add him to.

**Comment by FrayxRulez** [comment]
I think that an UI where contacts change their order everytime you select/unselect them would be crazily confusing, that's why you see selected ones in the search bar (as happens in any other telegram app, or messaging/mail app where you can search and choose multiple contacts)

**Comment by larsschellhas** [comment]
Well... Yes
