### ISSUE TITLE
set group/channel picture via the @bing-bot

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#345]
It would be usefull to set the group/channel picture by searching something via the @bing bot.

**Comment by FrayxRulez** [comment]
The app can't rely on a bot for a built-in functionality

**Comment by larsschellhas** [comment]
Okay, I get that. But another way to search bing for a group Picture is still a reasonable Feature request, isn´t it? Let me Change the title of this issue

**Comment by FrayxRulez** [comment]
I don't know how can be a good idea to put a 2/3 full days effort to code a tertiary feature

**Comment by larsschellhas** [comment]
It may be a tertiary Feature, but it´s one that brings a really nice Addition to the UX. 
For example WhatsApp has this Feature:
![wp_ss_20170801_0001](https://user-images.githubusercontent.com/14281234/28820652-b44f22b8-76b2-11e7-9b62-b119c3237542.png)

And even though I see, that the app shouldn´t rely on a bot for this, it was my suggestion, because it would be probably the most effortless way to achieve this.

I understand if you don´t want to do it, because it it definitely no core-feature and needs a lot of work, but I would still let it be here as Feature request.
