### ISSUE TITLE
set group picture is not possible while creating a group

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#347]
Clicking on this button doesn´t do anything!!! 😠 
![image](https://user-images.githubusercontent.com/14281234/28787802-e8b3d3ea-761d-11e7-8662-ca19238d850b.png)

You should be able to set the Group Picture here, too. See issue #345 for additional suggestions for setting a group Picture.

**Comment by FrayxRulez** [comment]
Duplicate? #346

**Comment by larsschellhas** [comment]
oh yes.. probably happened due to the Server issues yesterday
