### ISSUE TITLE
Hook into incoming messages

### ISSUE THREAD

**Issue by GsHeri** [UnigramDev/Unigram#352]
Hey there,

quick question..
I want to extend unigram to capture my incoming commands from my private group (to call various triggers in my home LAN).

i thought i might as well ask and save some (or..a lot of) digging :D 

where would i have to hook into unigram to get the first possible occurrence of an incoming group message? (i want to parse specific keywords when they are sent, and just do nothing when they aren't).

i found the "onMessageChanged" handler, but it doesn't behave like i expect (it seems like many messages are piped through it on every change?)
i just want to capture every new incoming message, where is the point to start?

I'd appreciate any help :)
thx!

**Comment by FrayxRulez** [comment]
Hey, you should implement `IHandle<TLMessageCommonBase>` and subscribe your class to the `ITelegramEventAggregator` singleton instance
