### ISSUE TITLE
Incorrect integration with People popup in TaskBar

### ISSUE THREAD

**Issue by xperiandri** [UnigramDev/Unigram#353]
Default view is displayed instead of messaging view.
![image](https://user-images.githubusercontent.com/2365592/28968626-970c8910-7929-11e7-81a2-be18e2ed3c69.png)

**Comment by mikekosulin** [comment]
Same issue.
But also I got error 800706BE:

0. Open contact via People bar
1. Click to Unigram
2. Don't close Unigram
3. Click to another contact from People bar

**Comment by larsschellhas** [comment]
please open a new issue for it
