### ISSUE TITLE
408 MTProtoService: operation timed out

### ISSUE THREAD

**Issue by ZeekoZhu** [UnigramDev/Unigram#356]
I use the same proxy setting in unigram as it in telegram desktop, but Unigram throw an error : MTProtoService: operation timed out

![uwperror](https://user-images.githubusercontent.com/13861843/28995512-9460aa3a-7a1d-11e7-9bb3-b33c465f3b41.png)

![tgdesk](https://user-images.githubusercontent.com/13861843/28995491-1da4fcca-7a1d-11e7-9421-d967d363e8bb.png)

**Comment by FrayxRulez** [comment]
UWP apps can't connect to localhost (loopback).
You should be able to circumvent the isolation using `checknetisolation.exe`:

To enable loopback use this command:
```checknetisolation loopbackexempt -a -n=<package family name>```

To disable loopback use this command:
```checknetisolation loopbackexempt -d -n=<package family name>```

Source: [Stackoverflow](https://stackoverflow.com/questions/33259763/uwp-enable-local-network-loopback)

**Comment by dmnmsc** [comment]
There is an app called [Enable AppContainer Loopback ](https://github.com/tiagonmas/Windows-Loopback-Exemption-Manager)that allows you to connect to localhost. Check it here: https://github.com/tiagonmas/Windows-Loopback-Exemption-Manager

**Comment by ZeekoZhu** [comment]
thanks， I just forgot the limitation
