### ISSUE TITLE
Unable to click/add/call a shared contact

### ISSUE THREAD

**Issue by Fernandus91** [UnigramDev/Unigram#360]
A friend shared with me a contact, like title says, I was unable to use it.
Unigram 0.5.575.0 on W10M 14393.1593

**Comment by larsschellhas** [comment]
@Fernandus91 Also sending a contact is impossible, too

**Comment by Fernandus91** [comment]
Ok, I'm changing the title then, even because there is no open issues about it

**Comment by FrayxRulez** [comment]
@Fernandus91 It's better to have separate issues.

**Comment by Fernandus91** [comment]
@FrayxRulez ok, I'm gonna open another issue

**Comment by FrayxRulez** [comment]
It's now possible to save contacts to your telegram account: https://github.com/UnigramDev/Unigram/commit/a7973b6bca87b785c55f53934101c838e4a39750
