### ISSUE TITLE
Add the "share contact" feature

### ISSUE THREAD

**Issue by Fernandus91** [UnigramDev/Unigram#361]
Like @larsschellhas said, it is impossible to share a contact

**Comment by FrayxRulez** [comment]
Would you prefer to have an in-app page where to select the contact to share or to use the system dialog?

**Comment by Fernandus91** [comment]
@FrayxRulez I don't have particular preferences, maybe the community does. But according to me, you can use a way that does not take you too much time

**Comment by Fernandus91** [comment]
@FrayxRulez wow, really, REALLY fast... Thanks
