### ISSUE TITLE
Duplicate "trend stickers" icon in sticker panel

### ISSUE THREAD

**Issue by Fernandus91** [UnigramDev/Unigram#365]
![senza nome](https://user-images.githubusercontent.com/29466231/29240300-6f5b9458-7f62-11e7-83df-5687891552e4.png)

The first is near the GIF button and the second is at the end.

**Comment by FrayxRulez** [comment]
You should get more sticker sets, so you won't notice it

**Comment by Fernandus91** [comment]
They are already a lot, and it is still noticeable
