### ISSUE TITLE
App crashes if dialog has location messages

### ISSUE THREAD

**Issue by cherepets** [UnigramDev/Unigram#368]
Version: 0.5.575.0

Steps to reproduce:
1. Send location
2. Quit Unigram
3. Open Unigram again
4. Open the same chat
5. App crashes.

From event viewer:
Faulting application name: Unigram.exe, version: 1.0.0.0, time stamp: 0x5985b440
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.14393.1378, time stamp: 0x594a17be
Exception code: 0xc000027b
Fault offset: 0x00000000006d6abb
Faulting process id: 0xc50
Faulting application start time: 0x01d31a4dd134d232
Faulting application path: C:\Program Files\WindowsApps\38833FF26BA1D.UnigramPreview_0.5.575.0_x64__g9c9v27vpyspw\Unigram.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: a8057916-2d12-4783-beee-f8e424107bd4
Faulting package full name: 38833FF26BA1D.UnigramPreview_0.5.575.0_x64__g9c9v27vpyspw
Faulting package-relative application ID: App

**Comment by FrayxRulez** [comment]
Duplicate, #354, update the app
