### ISSUE TITLE
Telegra.ph

### ISSUE THREAD

**Issue by deltapir** [UnigramDev/Unigram#371]
What if i decided to make an instant view page inside unigram instead of using an external browser and then copy the link of the page i just created?
It can be useful as well adding a telegra.ph link to the site itself instead of creating the whole editor inside unigram.

**Comment by larsschellhas** [comment]
What exactly are you asking for? Is your question a question or Suggestion?
Please be more clear with Feature requests :)

**Comment by deltapir** [comment]
Yes it is a missing features. 
I imagined a page inside Unigram where I can write a telegra.ph page just like the site itself does. I dont know if it is possible to do. 

It can be useful (if my idea is impossible to accomplish) adding a link to telegra.ph site: Maybe in the top menu where "Help, new group or channel" are.

**Comment by FrayxRulez** [comment]
@deltapir Makes no sense to me
