### ISSUE TITLE
Unhandled exception randomly and repeatly appear

### ISSUE THREAD

**Issue by Jack-Works** [UnigramDev/Unigram#374]
![image](https://user-images.githubusercontent.com/5390719/30012152-1885e618-9170-11e7-94b4-dc7c49485a53.png)

**Comment by akusmin** [comment]
Same for me. Error appears when you are mentioned via @. Chat become unusable.

**Comment by FrayxRulez** [comment]
Fixed https://github.com/UnigramDev/Unigram/commit/1d3a0bf1d59d9e4339b65b150ccc2f75921c23bf
