### ISSUE TITLE
Unable to interact with multiple chats via Windows 10 My People

### ISSUE THREAD

**Issue by d1vanloon** [UnigramDev/Unigram#375]
# Expected Behavior

Click one "person" in the taskbar to open the Unigram chat with that contact. Repeat for a second person. Return to the first person and send a message. The message is sent.

# Actual Behavior

When returning to the first person, an exception is thrown when clicking the compose field.

![image](https://user-images.githubusercontent.com/9598082/30123245-f7bcdc24-92f6-11e7-9582-92f98aafb1b1.png)

I don't think Unigram can handle multiple instances as allowed by My People.

# Workaround

Only open one "person" at a time.

# Environment

Windows 10 1703 build 16278.1000 (rs3_release)

**Comment by ikarago** [comment]
Unigram is indeed not able to run multiple instances at the same time, hence why it crashes when you try to open multiple chats at the same time. We're constantly working on improving Unigram, and we hope to bring this feature to run multiple instances as well in the future.

**Comment by xperiandri** [comment]
Same thing if the same thread (contact messages) opened in app and from People button.
![image](https://user-images.githubusercontent.com/2365592/31315573-0696257a-ac24-11e7-9202-9e2cd0bfd88b.png)

**Comment by FrayxRulez** [comment]
This is going to be solved with X update: https://t.me/unigram/162
