### ISSUE TITLE
When muting a channel, there is no immediate update in the roster reflecting mute state

### ISSUE THREAD

**Issue by roman380** [UnigramDev/Unigram#376]
The respective icon should appear/disappear immediately when mute state changes.

**Comment by FrayxRulez** [comment]
What's the roster?

**Comment by roman380** [comment]
![](https://i.imgur.com/Qzm3q64.png)

**Comment by FrayxRulez** [comment]
It works for me

**Comment by roman380** [comment]
Consistently does not work for me, 0.6.614.0

**Comment by FrayxRulez** [comment]
Always or sometimes? If only sometimes can you reproduce?

**Comment by roman380** [comment]
I just added a few channels - worked on none of them. I tried a channel I already had before - did not work either. Muting it further I don't see it ever working, including after switching to Contacts, Settings, then back to Chats. Simply does not work.

**Comment by FrayxRulez** [comment]
Tried many times, I can't simply reproduce this.

**Comment by roman380** [comment]
Over this time I rebooted system, killed Unigram process at least once. I still have this bug every time I unmute/mute any channel.

**Comment by FrayxRulez** [comment]
App version?

**Comment by roman380** [comment]
0.6.614.0

**Comment by roman380** [comment]
(sorry, closed by mistake)

**Comment by bugada** [comment]
I can reproduce this bug both in mobile and desktop

1) open a chat
2) go to chat settings
3) disable (or enable) notification and sound
4) go back to the chat list

In the list the icon doesn't reflect the new status

**Comment by FrayxRulez** [comment]
Still 
![2017-09-24_16-30-11](https://user-images.githubusercontent.com/8152849/30783586-a784acca-a145-11e7-8dd1-69c35498093a.gif)

**Comment by FrayxRulez** [comment]
Still

![2017-09-24_16-31-44](https://user-images.githubusercontent.com/8152849/30783598-dc3fa136-a145-11e7-9aff-9a9222eb5adc.gif)

**Comment by bugada** [comment]
Sorry tested with latest developer version

**Comment by FrayxRulez** [comment]
Same.

**Comment by DarthJahus** [comment]
@FrayxRulez This may be a connection issue.

**Comment by FrayxRulez** [comment]
Yes, it can, you might want to check if changing the setting from Unigram changes it in other clients as well.

**Comment by bugada** [comment]
No fela check this (latest developer version)

![test](https://user-images.githubusercontent.com/4438193/30786878-5d4f81d8-a17d-11e7-8500-ddd8350387bf.gif)

**Comment by bugada** [comment]
Ok in groups works but not in bot, normal chat and channel

**Comment by FrayxRulez** [comment]
It works for every chat but users. Try to be a bit more precise the next time.
There's a huge difference between channels, supergroups, chats, users.
