### ISSUE TITLE
Error pasting image

### ISSUE THREAD

**Issue by akusmin** [UnigramDev/Unigram#383]
Some times image pasting triggers exception

![image](https://user-images.githubusercontent.com/13545868/30522436-affec376-9bf1-11e7-85ed-bbf73ec5ea2f.png)

**Comment by FrayxRulez** [comment]
I need some repro to be able to fix this.

**Comment by akusmin** [comment]
@FrayxRulez i have no ideas how to repro it... i didn't see such error for several weeks till today. 
if you need any specific information to investigate root issue then please let me know .
