### ISSUE TITLE
hamburger menu enhancement 

### ISSUE THREAD

**Issue by alighamari** [UnigramDev/Unigram#384]
![image](https://user-images.githubusercontent.com/24440862/30537171-88eee438-9c1d-11e7-91d0-168f8fb644d1.png)
in hamburger menu chats-contacts-calls-settings can be at top and new group and new channel can be down of them.
it makes sense for me that something I need more is upper.

**Comment by ikarago** [comment]
Fixed in this commit: https://github.com/UnigramDev/Unigram/commit/5f3b44b6d23ffccb4d85b1e6ce69ecc5f40c1c78
