### ISSUE TITLE
Notifications lag

### ISSUE THREAD

**Issue by akusmin** [UnigramDev/Unigram#386]
I'm getting lag around 1 hour or even more for messages notifications.
Official client works fine. 
Is there any way to make notification work as they should?

Cheers.

**Comment by FrayxRulez** [comment]
Telegram guys are working to find a solution. 
I’m closing this issue since it is not directly related to the app.

**Comment by akusmin** [comment]
@FrayxRulez is there any way to track telegram issue?

**Comment by FrayxRulez** [comment]
As a temporary solution I've introduced local notifications while the app is running (like tdesktop does): https://github.com/UnigramDev/Unigram/commit/41f460863180afe683f6fc9ad328832b2fcb269b
