### ISSUE TITLE
Carriage returns are removed from description

### ISSUE THREAD

**Issue by electricduck** [UnigramDev/Unigram#387]
![screen shot 2017-09-21 at 21 49 48 edit](https://user-images.githubusercontent.com/1594644/30718655-7cac6c10-9f18-11e7-8da9-f4629a126c78.png)

This group's description had carriage returns in it, but as soon as I even open the group info panel in Unigram (even without editing the description), Unigram seems to set it, but seems lose carriage returns for other clients, even though they're perfectly visible in Unigram.

_(public group seen in description is **not safe for work**, as a warning)_

Right client: Unigram `0.6.614.0`, on Windows 10 1703
Left client: Telegram `1.1.23-alpha`, on macOS Sierra

**Comment by FrayxRulez** [comment]
The carriage return is actually lost when you save changes in the **edit group** page and not when you open the infos one, there's quite a difference.
