### ISSUE TITLE
Failed to connect to proxy

### ISSUE THREAD

**Issue by ZeppLu** [UnigramDev/Unigram#388]
Telegram is blocked in Mainland China so proxy is needed.

I've set up proxy setting in Unigram, but it keep displaying "connecting to proxy" in titlebar. All other programs (including UWP apps) can easily connect to Internet with the same proxy setting.

Usually I would set up a global proxy in Windows with ShadowSocks so that extra configuration is not needed, but UWP apps are quite special since they ignore global proxy setting by default, so I use [this](https://loopback.codeplex.com/) program to force them to respect my setting. This trick works quite well for a large number of UWP apps, except Unigram.

**Comment by alighamari** [comment]
@ZeppLu AFAIK unigram only can use socks5 check the version of the socks you are using

**Comment by FrayxRulez** [comment]
Can you provide some more detailed repro? So I can try myself.

**Comment by ZeppLu** [comment]
FYI, when I run `curl ip.ipify.org` in console with or without argument `--socks5 localhost:1080` (pay attention to 5), it gives me different output. One is my VPS’s ip, the other is my real ip.

And I’m currently using Chrome extension SwitchyOmega to manage proxy settings inside Chrome, it support both socks4 & socks5. I find that my proxy setting (127.0.0.1:1080) only works when I choose socks5.



Zepp Lu
Department of Automation, Tsinghua University
Email: luzepu678@gmail.com

发件人: alighamari
发送时间: 2017年9月23日 00:33
收件人: UnigramDev/Unigram
抄送: Zepp; Mention
主题: Re: [UnigramDev/Unigram] Failed to connect to proxy (#388)

@ZeppLu AFAIK unigram only can use socks5 check the version of the socks you are using

**Comment by ZeppLu** [comment]
Sure, I’m using [ShadowSocks-Windows](https://github.com/shadowsocks/shadowsocks-windows), the latest version (v4.0.6) to set up my socks proxy. But in order to use ShadowSocks, you must first run a daemon on server side, and then connect to it from client side (these can actually be the same computer). For more infomation, please refer to [this site](https://shadowsocks.org). After configuration is done, enable `use proxy settings` in Unigram and fill the hostname and port.



Zepp Lu
Department of Automation, Tsinghua University
Email: luzepu678@gmail.com

发件人: Fela Ameghino
发送时间: 2017年9月23日 00:52
收件人: UnigramDev/Unigram
抄送: Zepp; Mention
主题: Re: [UnigramDev/Unigram] Failed to connect to proxy (#388)

Can you provide some more detailed repro? So I can try myself.

**Comment by Aster-the-Med-Stu** [comment]
@FrayxRulez This problem is indeed due to the fact that UWP application are not allowed to access localhost and you need to manually add Unigram to loopback exemption. More info is available on [StackOverflow](https://stackoverflow.com/questions/33259763/uwp-enable-local-network-loopback)
