### ISSUE TITLE
Some dialogs appear out of screen on RS3

### ISSUE THREAD

**Issue by FrayxRulez** [UnigramDev/Unigram#397]

**Comment by jankratochvilcz** [comment]
Would be great if you could provide repro steps @FrayxRulez, maybe something I could take a look at :-)

**Comment by FrayxRulez** [comment]
By example the dialog for live location, or the one for self destructing media, when the window is at min width

**Comment by larsschellhas** [comment]
I think this isn´t happening anymore, is it? I cannot see it in the two described examples at least.
Closable, @FrayxRulez ?

**Comment by FrayxRulez** [comment]
This seems to be fixed (at least in newer Windows versions).
