### ISSUE TITLE
Search box text appears behind the search icon

### ISSUE THREAD

**Issue by electricduck** [UnigramDev/Unigram#398]
![image](https://user-images.githubusercontent.com/1594644/31413011-50ab3172-ae0f-11e7-9cfd-17a6f6ba1e5b.png)

Low priority small UI issue, but when resizing Unigram to its smallest size, before it goes into its mobile layout (and the sidebar vanishes), the "Search for chats and messages" text appears behind the search icon.

_Unigram **0.8.666.0**_

**Comment by FrayxRulez** [comment]
Wouldn't look uglier if simply clipped?
