### ISSUE TITLE
Add localization in order to improve the app experience in other countries

### ISSUE THREAD

**Issue by pablojim99** [UnigramDev/Unigram#399]
I think that Unigram is big enough to support other languages, at least the most used ones. (Spanish, Russian, Chinese...idk)
What do you think? Any plans?

**Comment by FrayxRulez** [comment]
Something that should be done at the end

**Comment by pablojim99** [comment]
I know, just want to know if we are getting closer to that point in order to start helping with translation ;)

**Comment by FrayxRulez** [comment]
I’m a bit scared by this step because uwp localizations are somehow strict (you need to specify the property they should localize, and if you change the controls being used or similar things will be broken and loc keys would need to be manually updated for every language)

**Comment by pablojim99** [comment]
Yeah, definitely the best way to do it is finalize the UI first and then start adding the resources using x:Uid no?

**Comment by FrayxRulez** [comment]
Yes, I think @callummoffat will probably work on this. Wanna help him?

**Comment by pablojim99** [comment]
Since I'm relatively noob in GitHub I prefer not getting very involved in the code, but I will be pleased to help in the  Spanish translation.

**Comment by callummoffat** [comment]
Sure, I can work on making Unigram localization friendly. I do have exams coming up in the very near future, but I’ll have nothing but free time after the 24th of November. That okay?

**Comment by thunderluca** [comment]
@FrayxRulez what if we don't use UWP x:Uid strategy and we use the resources directly in XAML pages? Thanks to this method, you don't/will care about any refactoring issue that affects properties names and compiler can assist you if it can't find changed resource's names, without testing at runtime every time.

**Comment by callummoffat** [comment]
The advantage of the x:Uid and .resw file strategy is that it allows us to change shared strings in a single centralized location.

In addition, resource files make it much easier to localize. Plus, I think we should stick to UWP best practices where possible.

**Comment by callummoffat** [comment]
Okay, good news.

I've started working on implementing localization support. It is very much a long term project, but I've begun laying the groundwork. PR #405 integrated my initial groundwork, including a localization-ready IntroPage and AboutPage.

This is a monumental task, and I don't expect to complete it any time soon (I do have a life), but it isn't too difficult to implement - simply time-consuming in the extreme.

**Comment by xperiandri** [comment]
I will help with Ukrainian and Russian translations.
Just tell me when to start.

**Comment by jc-design** [comment]
I could do some German translation if need.
P.S.: Thank you for your work

**Comment by batkiz** [comment]
I could help with Chinese translation.
Thanks for this app.

**Comment by taijuin** [comment]
I could help with Traditional Chinese translation.

I try to do it in here:
https://crowdin.com/project/tryneeds/zh-TW#
