### ISSUE TITLE
Call initiation on mobile opens new window like mini mode on desktop

### ISSUE THREAD

**Issue by xperiandri** [UnigramDev/Unigram#400]
When I press call button on Mobile a new black window opens which display "Loading..."
However call is initiated and connection is successful. Although there are no signs of that.
Looks like mobile specific code is not executed and displayed mini call window instead of call overlay.

By the way what is the name of this small topmost window displayed on call? I can't find its name or sample in gallery.

**Comment by xperiandri** [comment]
It worked right for some time and now broken again

**Comment by FrayxRulez** [comment]
It seems related to the system more than to the app :(
