### ISSUE TITLE
Do not hide whole hamburger menu on large screen

### ISSUE THREAD

**Issue by xperiandri** [UnigramDev/Unigram#401]
Pivot was nice to quickly switch between views
Now hamburger hides everything and adds additional click to get to an action.
It would be better to leave icons of hamburger menu list visible if windows size is large enough

**Comment by pablojim99** [comment]
I agree, maybe it's a great idea using the NavigationView control with FCU, it adapts great automatically to the screen size and uses Fluent Design.

**Comment by FrayxRulez** [comment]
It's not possible to use the `NavigationView` control because it would make the app crash on previous operating system versions, so a custom control (Like the one we have right now) is needed.

**Comment by pablojim99** [comment]
Sad, maybe in the future...for now it would be great to modify this custom control in order to improve the adaptative desgin

**Comment by xperiandri** [comment]
It is not a big deal to implement acrylic.
Just swap brushes when mode changes.

**Comment by FrayxRulez** [comment]
I don't see how this is related to acrylic

**Comment by xperiandri** [comment]
Not related, just answered to @pablojim99 response. I can't see any difference from current implementation to NavigationView except acrylic

**Comment by FrayxRulez** [comment]
I'm going to close this: hamburger menu is quite secondary here (during a work day I usually don't open it at all, maybe a couple of times just to access Saved Messages, but I usually search for them) so I don't see the need to make it always visible

**Comment by xperiandri** [comment]
Not always visible but icons only in closed mode

![image](https://user-images.githubusercontent.com/2365592/32331979-f3987e78-bfec-11e7-9dba-c613aadd6fe9.png)

**Comment by FrayxRulez** [comment]
I really don't see this as something I'd like to have in my app :/
