### ISSUE TITLE
RAM and CPU Usage unreasonably high when opened from MyPeople

### ISSUE THREAD

**Issue by rabiet** [UnigramDev/Unigram#402]
If you open Unigram from MyPeople it takes more and more RAM and drives the CPU usage to the max. Even when you close the MyPeople Window this continues for a few minutes

**Comment by FrayxRulez** [comment]
@bugada seems to be related to your changes: when the app is open from MyPeople it starts fetching tons of pages of items

**Comment by bugada** [comment]
Really? I'll check

**Comment by FrayxRulez** [comment]
From a Telegram message:

> I just found another issue in new build. When I scroll down to the last message which is loaded in a channel or in a group and I wait to load the following messages, app automatically jumps to the last loaded message   and this goes on.
