### ISSUE TITLE
Group creation wizard has too many steps

### ISSUE THREAD

**Issue by xperiandri** [UnigramDev/Unigram#404]
What is the purpose of setting name of the group but then navigating to another page to select contacts but not doing it on the same page?

**Comment by larsschellhas** [comment]
@xperiandri To simplify the creation process? Where is the Problem with dedicating a new page for every Task and offer a strict and linear creation experience?

**Comment by FrayxRulez** [comment]
Steps are exactly the same across all telegram apps

**Comment by xperiandri** [comment]
On iPhone you select contacts first then you put a name and select a picture

**Comment by FrayxRulez** [comment]
I don’t like your attitude

**Comment by xperiandri** [comment]
What exactly do you dislike?
If there is a huge space what is the reason to split creation in two steps?
If it is a small screen that iPhone version behavior is more relevant.
