### ISSUE TITLE
Random Unhandled Exception

### ISSUE THREAD

**Issue by TwoUnderscorez** [UnigramDev/Unigram#409]
![image](https://user-images.githubusercontent.com/25303006/31575119-02162c70-b0e8-11e7-8442-4da9df61b6a3.png)
This just randomly occurred. After I pressed OK the chat kind of reloaded itself and everything was OK. No messages were lost.

**Comment by FrayxRulez** [comment]
Need a repro

**Comment by TwoUnderscorez** [comment]
what?

**Comment by FrayxRulez** [comment]
I need some instructions to reproduce the issue to be able to fix it

**Comment by TwoUnderscorez** [comment]
Sorry, It felt like it happened randomly. I'm pretty sure my friend sending me a picture to me has something to do with it...

**Comment by FrayxRulez** [comment]
Closing this then
