### ISSUE TITLE
Breaking: moving away from Template10

### ISSUE THREAD

**Issue by FrayxRulez** [UnigramDev/Unigram#416]
I think it's time to move away from [Template10](https://github.com/Windows-XAML/Template10) since it doesn't suit anymore our needs: it's quite not flexible and incomplete, and also it's more than a year that it doesn't receive any kind of update. I checked many times their repository, and the project seems to be still alive, but still moving in a direction I don't really like.

My idea right now is to use [MvvmCross](https://github.com/MvvmCross/MvvmCross), and reasons are simple:
- It's amazingly flexible
- It's a feature complete MVVM framework
- It doesn't include useless services

and it is also the framework I use daily at work since quite a while.

Any opinion on this?

**Comment by thunderluca** [comment]
I've honestly always worked with MVVMLight because of easy learning curve, but MVVMCross seems the best. I vote up for it

**Comment by FrayxRulez** [comment]
The problem with MVVMLight is that it doesn't have any kind of navigation infrastructure: it's almost only `IoC`and `DI`

**Comment by ikarago** [comment]
@FrayxRulez Go for it

**Comment by callummoffat** [comment]
@FrayxRulez I agree. Go forth and refactor!

**Comment by xperiandri** [comment]
I recommend Prism. It is simple.
The other problem with MVVMCross is that it does not use "Bait and Switch" trick which is strange and requires unnecessary code.
Also it is too abstract. For Windows only project you don't need all that stuff.

**Comment by FrayxRulez** [comment]
Seems that there's some kind of migration from Template10 to Prism atm: https://github.com/Windows-XAML/Template10/issues/1620
