### ISSUE TITLE
Splash screen is inconsistent

### ISSUE THREAD

**Issue by FrayxRulez** [UnigramDev/Unigram#417]
Right now splash screen background is inconsistent across devices:
- On desktop it will use the user accent color
- On mobile, with dark theme, will be black
- On mobile, with light theme, will be white, making the logo unreadable

Any solution?

**Comment by thunderluca** [comment]
We don't have many solutions, we can choose a fixed color for Unigram or we must leave this behavior. 

A "third" option could be create a custom splash screen that read actual splash screen background value and fade original color with user accent color, but if Microsoft continues to change its behavior, we can't patch it every time (ok, it could be one-per-SDK update, but it has no sense)

**Comment by larsschellhas** [comment]
@FrayxRulez I would let the background be like it is (transparent).
But couldn´t we make the background transparent with a light grey?
That way accent-colors would shine through - if I got it right - which I probably didn´t.

Last way would be to make the logo a light grey, instead of pure white

**Comment by thunderluca** [comment]
Any update? I saw that on Windows 10 Mobile, Microsoft itself, with its system apps updates, chose to leave the black background with dark theme....and white background with white logos when OS is set on light theme.

**Comment by FrayxRulez** [comment]
Since Mobile is quite secondary nowadays and the accent color looks nice on desktop I'd keep this behavior
