### ISSUE TITLE
When text copied from OneNote Mobile (UWP) it pasted as image

### ISSUE THREAD

**Issue by xperiandri** [UnigramDev/Unigram#423]
As OneNote Mobile, and other MS products put an image into clipboard along with text the image is pasted into Unigram.
I don't think it is a solution for this better than paste text too. So that if user pressed Esc and discarded image paste if text exists in clipboard it will be pasted into message text box.

**Comment by evgfilim1** [comment]
@xperiandri The same with Official Telegram client for Windows Phone.

**Comment by xperiandri** [comment]
What do you want to tell by your comment? That they have not found a workaround or you want that behavior to be preserved?
That app is not supported any more as you can see.

**Comment by FrayxRulez** [comment]
It is.

**Comment by evgfilim1** [comment]
@xperiandri Yes, they have not found a workaround.

**Comment by xperiandri** [comment]
But my idea have to work
