### ISSUE TITLE
Improve message deleting dialog usability

### ISSUE THREAD

**Issue by xperiandri** [UnigramDev/Unigram#424]
Usually you want to delete a message for you interlocutor too.
But checkbox is unset by default
![image](https://user-images.githubusercontent.com/2365592/31834130-a74cb5f0-b5d5-11e7-9738-b6c3885bc43d.png)

It would be better to have it set by default or even better to have 3 buttons in dialog:
* For me
* For everyone
* Cancel

**Comment by FrayxRulez** [comment]
Dialogs can't have more than two buttons in versions prior to Fall Creators Update. 

Also this is the default behavior in all the official apps

**Comment by xperiandri** [comment]
It is not about behavior but usability.
Is it possible to show 3 buttons dialog in Fall Creators Update and default dialog otherwise? I can prototype that.

**Comment by FrayxRulez** [comment]
I don't really like the idea of having three buttons... :(

**Comment by xperiandri** [comment]
Let's at least add an option to set or unset that checkbox by default
It is very annoying to write some weird thing and delete it for you only because you tried to do that quickly and forgot to set a checkbox.

**Comment by FrayxRulez** [comment]
I would like to have an option on GitHub to prevent people to ask to add options :)

**Comment by xperiandri** [comment]
😀
Haven't you met a scenario that I described?
