### ISSUE TITLE
Display chat share link

### ISSUE THREAD

**Issue by xperiandri** [UnigramDev/Unigram#432]
Display a copyable and shareable chat share link on chat or channel info page.
Right click with context menu to copy
Share button for share contract

**Comment by thunderluca** [comment]
I didn't understand very well, do you want a Share button for sharing a group chat or channel?

**Comment by DarthJahus** [comment]
@thunderluca

**Comment by FrayxRulez** [comment]
![cattura](https://user-images.githubusercontent.com/8152849/32079935-38f43e3e-baad-11e7-87de-3b988058ebd3.PNG)

Oke?

**Comment by xperiandri** [comment]
Looks cool!
Does it also have a context menu with "copy" item to copy to clipboard?

**Comment by FrayxRulez** [comment]
The share dialog has a clip button to copy the link

**Comment by xperiandri** [comment]
> I didn't understand very well, do you want a Share button for sharing a group chat or channel?

Yes, but as Share Source is not yet supported then it can be implemented later

**Comment by FrayxRulez** [comment]
![2017-10-27_19-02-54](https://user-images.githubusercontent.com/8152849/32116063-72f7c8ac-bb49-11e7-90b7-412ecb27d41b.gif)

**Comment by xperiandri** [comment]
That is why it is also convenient to have an in-place context menu with Copy item for quick mouse access.
But in general works amazing! Thanks @FrayxRulez !
