### ISSUE TITLE
Group name is not displayed from previous wizard page

### ISSUE THREAD

**Issue by xperiandri** [UnigramDev/Unigram#433]
After I typed a group name in the first page of group creation wizard this name is not propagated to the second page. See screenshot

![inkedwp_ss_20171021_0001_li](https://user-images.githubusercontent.com/2365592/32044750-1a216fc4-ba47-11e7-8786-057586ffd020.jpg)

**Comment by jankratochvilcz** [comment]
Just tested this, looks like the *Create Group* UI is a bit incomplete:
- Clicking the camera button in the first step does nothing
- Entering in the "group name" TextBox should go to the next step
- Test! in second step seems to be hardcoded (original report)

It could also be worth considering improving the UI in some ways:
- Changing the tick icon in the first step to right arrow. This would indicate there's a next step
- Removing the "1/30000". I know the official apps show this, but unsure it's useful. Maybe we could only show it when the number of members exceeds 10000 (this feels like a very edge case)
- Change the template of the TextBox controls in both steps to be consistent with the search box (1px bottom border accent brush highlight)
- Improve copy
- Add a small tooltip about what's a group. New users might struggle with the difference between a group and a channel

Would love to take a jab at improving this during the weekend!

**Comment by FrayxRulez** [comment]
This is fixed in a recent commit
