### ISSUE TITLE
Pull to refresh and refresh binding for keyboard

### ISSUE THREAD

**Issue by xperiandri** [UnigramDev/Unigram#436]
Sometimes when bad internet connection or after resume chat list stuck and do not update.
It would be nice to be able to do pull refresh with touch and wheel or press F5 to initiate refresh

**Comment by FrayxRulez** [comment]
There's no way to initiate refresh.

**Comment by xperiandri** [comment]
Why not? Can't we read chats again?

**Comment by FrayxRulez** [comment]
Nope, the app has a state, you can't just override it.
Also having a manual refresh is not an expected scenario.

**Comment by xperiandri** [comment]
As now it sticks and only closing and reopening helps to update it

**Comment by xperiandri** [comment]
Is there any option to fix this behavior and make updates smooth?
Now only loading some history and then scrolling to the most recent messages allows to load new messages

**Comment by FrayxRulez** [comment]
Actually if you are patient and you wait a while you should see the chat blink reloading all the messages.
