### ISSUE TITLE
Cache the last time app status

### ISSUE THREAD

**Issue by Charmandrigo** [UnigramDev/Unigram#439]
Specially on mobile. Because every time I open Unigram I have to wait for everything (recents history, chats) to load, which causes the app to be extremely slow specially on Mobile Data connection.
Unigram has even crashed because it takes so much time to load a chat that just automatically closes

My only suggestion is just to save and automatically load the last seen conversations on the app and then connect to get updates, so the app can save time trying to load conversations and chats and simply show what was on there last time while connecting to get updates

**Comment by FrayxRulez** [comment]
If this was easy we'd have this already 😝 

Duplicated of #242
