### ISSUE TITLE
Issues with Windows 10 share function

### ISSUE THREAD

**Issue by shmykelsa** [UnigramDev/Unigram#440]
- [ ]  It bypasses passcode protection
- [x]  Photo and videos can be sent just by opening the chat manually, no pop-up as in forward menu shown
- [x]  Files can't be shared at all

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/3725b0f29427eef76bba9ddce1a07ae7c6696667

**Comment by MarcAnt01** [comment]
The first point still needs fix

**Comment by melih** [comment]
@FrayxRulez Share menu is still able to bypass passcode lock.
