### ISSUE TITLE
Message time is overlapping the content

### ISSUE THREAD

**Issue by cherepets** [UnigramDev/Unigram#441]
App version is 0.9.726.0.
It occurred on desktop (I was not able to reproduce it on mobile but it might not be related to device family).
It may be possible that it is related to the link on the second row.
![capture](https://user-images.githubusercontent.com/12017106/32153418-03a3a866-bd5d-11e7-93cc-9f0124a4b5ad.PNG)

**Comment by raminmjj** [comment]
I have the same problem.
sometimes that happen, with or without link in content.

**Comment by FrayxRulez** [comment]
@cherepets does it fixes closing and reopening the chat?

**Comment by cherepets** [comment]
@FrayxRulez Yes, it does.

**Comment by FrayxRulez** [comment]
Should be fixed with https://github.com/UnigramDev/Unigram/commit/6c09b1f08ae6aabf8e4f7921a1c7462585990b51, feel free to open this again if the bug will persist in future versions
