### ISSUE TITLE
Improve markdown support when sending messages

### ISSUE THREAD

**Issue by FrayxRulez** [UnigramDev/Unigram#443]
I'm a lover of **, __ and ``` to format text, but end users might prefer to use some context menu and to see a live preview of what's he's doing. Also we need rich text editing already to support mentions without username.

To do so we need to complete some steps first:
- [x] parsing RTF in a decent and reliable way
- [x] parsing Markdown in a decent and reliable way
- [x] improve the `RichEditBox` experience

Entities I'd like to parse from markdown are:
- `**bold**`
- `__italic__`
- <code>`code`</code>
- ````pre formatted code````
- `[urls](https://.../)`
- `@[mentions](1234567890)`

Improving `RichEditBox` experience would mostly consist in implementing a custom context menu with bold italic and so on (only when there's some text selected) and to prevent the typical auto-expand behavior for text formattation: if I make the selected text bold and then I got space the text __should't__ be bold anymore

**Comment by thunderluca** [comment]
Totally agree, actual "BubbleTextBox" that extends RichEditBox has a lot of bugs/poor performance and that's critical for a chat client

**Comment by FrayxRulez** [comment]
This has been fixed by the following commits: https://github.com/UnigramDev/Unigram/commit/8c1d211ff2f7d48c6ebc974d311f16597b41ba4e https://github.com/UnigramDev/Unigram/commit/c0bb3e39c61c8bcae8aa8c47b40899de9d5b2282 https://github.com/UnigramDev/Unigram/commit/1a934d5ff47999afa9393aa96053621328db16fa
