### ISSUE TITLE
does this app support ipv6 ?

### ISSUE THREAD

**Issue by hosxy** [UnigramDev/Unigram#445]
I find I can't login when I only use ipv6. It support it?

**Comment by FrayxRulez** [comment]
Not in the master/develop branches, yes in native one

**Comment by Karmylr** [comment]
> Not in the master/develop branches, yes in native one

Does the master/develop branch still not support IPv6 now?

**Comment by FrayxRulez** [comment]
The app does support IPv6 since 2017
