### ISSUE TITLE
Glitch unread messages counter

### ISSUE THREAD

**Issue by Marocco2** [UnigramDev/Unigram#447]
Unigram W10M Lumia 930

After tap on a push notification of a chat that I have been mentioned but I kept it muted, if I go in main menu the messages counter of that chat seems like a normal one with notification enabled

**Comment by xperiandri** [comment]
Same thing

**Comment by TobiVanHelsinki** [comment]
Same thing here. Question: If I answered a message, shouldn't that message get marked as read? ATM those messages raises the "unread messages counter". I don't like that ^^.

**Comment by FrayxRulez** [comment]
This is going to be solved with X update: https://t.me/unigram/162
