### ISSUE TITLE
Can't forward more than one message

### ISSUE THREAD

**Issue by athosbr99** [UnigramDev/Unigram#450]
I am using Windows 10 Fall Creators Update, on stable release. My Unigram version is 0.9.767.0 (the latest in the time of writing, I guess). 

In the official app, I can select one message, and then, select several other messages by draging the cursor and then forward. On Unigram I can forward only one at a time.

Example by gifs:

![2017-11-04_00-07-46](https://user-images.githubusercontent.com/6440060/32401389-659b8562-c0f4-11e7-82a7-336d670eda49.gif)

![2017-11-04_00-08-20](https://user-images.githubusercontent.com/6440060/32401388-65623474-c0f4-11e7-9833-a44192992dbf.gif)

**Comment by FrayxRulez** [comment]
If you check both single message context menu and the one in the top `...` you'll notice a `Select message`/`Manage` option. You can use it to select multiple messages at once and forward or delete them.

**Comment by athosbr99** [comment]
Oops, failed to notice that. But the official approach is more intuitive I guess (or I am used to it already)

**Comment by FrayxRulez** [comment]
Tap & hold is dedicated already to the context menu, and that's the default action on Windows platform, same happens on iOS as well

**Comment by athosbr99** [comment]
In the current version (0.15.1218) there isn't a Select message option anymore.
