### ISSUE TITLE
missing size of music in the details

### ISSUE THREAD

**Issue by alighamari** [UnigramDev/Unigram#451]
there was lack of detail in many things before
but now everything is good except music that they don't have the full detail 
there should be size of music after time of that 
credit: @ichbinali13
it should be so nice if it show album art too and there be save in music library option in context menu too
![image](https://user-images.githubusercontent.com/24440862/32416625-70d148ea-c261-11e7-9424-6ae1a8e38239.png)

**Comment by FrayxRulez** [comment]
I’m going to close this since official apps don’t show file size for music messages

**Comment by alighamari** [comment]
![image](https://user-images.githubusercontent.com/24440862/33094161-7313b1c8-cf14-11e7-8057-57c8f0ee7c41.png)
but telegram desktop show it and it is so useful
