### ISSUE TITLE
Implement raise to speak

### ISSUE THREAD

**Issue by FrayxRulez** [UnigramDev/Unigram#452]
Use [Windows.Devices.Sensors.ProximitySensor](https://docs.microsoft.com/en-us/uwp/api/windows.devices.sensors.proximitysensor) to implement raise to speak functionality.

**Comment by xperiandri** [comment]
Wow interesting what is raise to speak

**Comment by FrayxRulez** [comment]
The ability to start recording a voice message by simply bringing it near the ear. 
The problem is that I made some experiments using the ProximitySensor and it seems to raise tons of exceptions :(
