### ISSUE TITLE
When Changing Account, still receive Messengaes from old Account

### ISSUE THREAD

**Issue by TobiVanHelsinki** [UnigramDev/Unigram#454]
On my Windows Mobile with Creators Update I switched unigram telegram accounts by log the old out and the new account in. But I sometimes receive windows notifications from the old account. If I open the app, just chats from the new account are there.
Reproducing is hard, i did not discover a pattern.

**Comment by FrayxRulez** [comment]
This is going to be solved with X update: https://t.me/unigram/162
