### ISSUE TITLE
Pinned messages unremovable

### ISSUE THREAD

**Issue by mfeltrin91** [UnigramDev/Unigram#46]
When you remove a pinned message by pressing on the "x" and you reopen the chat, it reappears

**Comment by FrayxRulez** [comment]
When you are a simple user (non admin) and you unpin the message the action is not synced across your sessions, it is just a local setting. 
Since the app has no caching right now this feature cannot be implemented, so I'm closing this issue. 

This feature will be available in the future

**Comment by jlanza** [comment]
How can you get the pinned message back? I'm just a member of a group and cannot do it.

**Comment by MarcAnt01** [comment]
>           How can you get the pinned message back? I'm just a member of a group and cannot do it.

Log out and log in again. The same is in official clients, it's something that doesn't depend on us

**Comment by killerdominater28-svg** [comment]
> > ```
> >       How can you get the pinned message back? I'm just a member of a group and cannot do it.
> > ```
> 
> Log out and log in again. The same is in official clients, it's something that doesn't depend on us
