### ISSUE TITLE
Chats are not loaded if Unigram was restored from background

### ISSUE THREAD

**Issue by motors-nsk** [UnigramDev/Unigram#460]
Hello,

1. Launch Unigram. All chats opens
2. Tap Home button 
3. Open Edge or other resource-intensive apps.
4. Tap Unigram icon again.
5. I see that chats are not loaded. This behavior has appeared 2 weeks ago. Only restart of Unigram helps

![wp_ss_20171109_0001](https://user-images.githubusercontent.com/32703851/32591154-9192c292-c550-11e7-8ba4-ca25a9bc7ddc.png)

Lumia 650

**Comment by ImagoPL** [comment]
I have this bug on desktop too. Chats loads after few seconds, but this is frustrating  :/

**Comment by FrayxRulez** [comment]
I added a "Retry" button in [0.10.849](https://github.com/UnigramDev/Unigram/releases/tag/v0.10.849)
