### ISSUE TITLE
When going to build the latest commits I get 2 errors in Visual Studio

### ISSUE THREAD

**Issue by JMccormick264** [UnigramDev/Unigram#466]
Just finished pulling the latest commits. When I try to build the solution, I get 2 errors in the output window

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0006	Metadata file 'D:\Desktop_Stuff\Github_Clones\Unigram\Unigram\ARM\Debug\Telegram.Api.Native\Telegram.Api.Native.winmd' could not be found	Telegram.Api.Native.Test	D:\Desktop_Stuff\Github_Clones\Unigram\Unigram\Telegram.Api.Native.Test\CSC	1	Active
Error	C3861	'InterlockedExchange8': identifier not found	Telegram.Api.Native	D:\Desktop_Stuff\Github_Clones\Unigram\Unigram\Telegram.Api.Native\ConnectionManager.cpp	23	
```

Any ideas on how to solve this?

**Comment by FrayxRulez** [comment]
@lorenzrox

**Comment by FrayxRulez** [comment]
If you’re in develop/master branch just unload Telegram.Api.Native project

**Comment by JMccormick264** [comment]
Will do

**Comment by JMccormick264** [comment]
That error only happens when Debugging with ARM enabled
Switching to x64, and those errors do not happen and I can build and deploy successfully.

**Comment by FrayxRulez** [comment]
Yes but that project is unused in develop branch, so the right thing is to unload it (even if you don't get errors)
