### ISSUE TITLE
APP crashes when switch picture in ImageView

### ISSUE THREAD

**Issue by Eweol** [UnigramDev/Unigram#47]
APP crashes when switch picture in ImageView

step by step:

select attachment -->
select a Picture -->
add a second Picture with add button-->
select the second Picture in ImageView -->
switch back to first Picture -->
app crashes

**Comment by FrayxRulez** [comment]
I'll investigate, thank you Lukas

**Comment by ikarago** [comment]
@FrayxRulez It's fixed with the crashing issue when you removed a picture. 😉
