### ISSUE TITLE
Cannot mute a just joined channel 

### ISSUE THREAD

**Issue by roman380** [UnigramDev/Unigram#470]
When I open a channel, esp. by reference from another chat, and click "Open Channel" button at the bottom joining channel succeeds. The button changes to Mute.

Most important is that Mute button does not work. When clicked, it remains "Mute" and no muting takes place.

Additionally, the view is confusing in other ways:

1. The channel does not appear in the list on the left, it is not highlighted when joined as anticipated
2. There is no UI element to leave the channel

The same scenario in web client is more intuitive and solid in terms of UX.

Version: 0.10.876.0

**Comment by roman380** [comment]
For those who suffer from the bug: the easiest workaround is this:

Once you joined the channel, do not click "mute" that does not work. Instead, click on channel name to get to channel details and uncheck "Notifications" there and go back.

Not only this does work, but Mute/Unmute button is operational from there.

**Comment by FrayxRulez** [comment]
This should be solved now.
