### ISSUE TITLE
Mark messages unread

### ISSUE THREAD

**Issue by roman380** [UnigramDev/Unigram#471]
This is a suggestion, not a bug.

Once shown, the messages are displayed under "Unread Messages" and are immediately marked read.

It is actually pretty convenient to move unread pointer backward in order to defer them for further reading. The client does not currently offer this (Skype, for instance, does).

Regardless, it would make sense to apply read state not immedately but with a delay of a second or two for the case the messages are displayed by mistake and user is quickly switching to another chat.

**Comment by FrayxRulez** [comment]
The best solution would be to mark messages as read while scrolling, but it's quite hard to keep the unread count up to date, and I'm not really able to

**Comment by FrayxRulez** [comment]
I've opened an issue at TDLib, in case you want to track the progress on their side: https://github.com/tdlib/td/issues/136

Once they'll support this, Unigram will mark messages as read while scrolling the chat.
Said this, I'm going to close this issue for now.

**Comment by FrayxRulez** [comment]
Done: https://github.com/UnigramDev/Unigram/commit/80a8269ab85f5ed914b443174965da2acba5f68c
