### ISSUE TITLE
Bot menu not shown when ReplyMarkup panel is open

### ISSUE THREAD

**Issue by bugada** [UnigramDev/Unigram#474]
Platform: Desktop only, mobile ok
Version: develop at commit bcbdb0d8

If you are in a bot with bot keyboard open and choose the three dots on the upper right, the bot menu collapses but the menu is not shown. See gif.

![test2](https://user-images.githubusercontent.com/4438193/32981660-b9586816-cc78-11e7-9550-56fdb2ad7ce5.gif)

**Comment by FrayxRulez** [comment]
I'm not going to consider this an issue anymore: that's how xaml focus behaves.
