### ISSUE TITLE
Bot Keyboard panel appears when scrolling chat

### ISSUE THREAD

**Issue by bugada** [UnigramDev/Unigram#475]
Platform: Desktop and Mobile
Version: develop at commit bcbdb0d8

If you have the bot menu collapsed, scrolling the chat something makes the bot menu to reappear automatically.

![test4](https://user-images.githubusercontent.com/4438193/32981902-74144786-cc7b-11e7-864b-e159d93337af.gif)

**Comment by FrayxRulez** [comment]
This is going to be solved with X update: https://t.me/unigram/162
