### ISSUE TITLE
Saving images from multiple images sent offers the same file name for different images

### ISSUE THREAD

**Issue by roman380** [UnigramDev/Unigram#477]
* There is no option to save all images at once.
* When I save one by one, images are saved correctly but the app offers the same file name for every image

**Comment by FrayxRulez** [comment]
The file name is actually the current time. What should I use?

**Comment by roman380** [comment]
The file originally could have a name, at the time of sending. Its reuse would be the best. If the name is lost, unavailable or collides with anything, you could make up a unique name. The way it works now when user is  supposed to save one by one even though he obviously sees a batch of images, and then the suggested names result in overwriting is really inconvenient.

**Comment by FrayxRulez** [comment]
Photos don't preserve their original file name. How can I generate an unique name? I don't like the idea to have arbitrary names.

**Comment by roman380** [comment]
You can add a suffix based on something you extract from EXIF or, if there is nothing useful, image file size. Even if not absolutely unique, it would minimize name collision chances and improve the situation. Preserving name is actually a good thing too.

**Comment by auchri** [comment]
Or just add `001`, `002`, ... to the image names.
