### ISSUE TITLE
Exception while opening media

### ISSUE THREAD

**Issue by bugada** [UnigramDev/Unigram#478]
Platform: Desktop & Mobile
Version: develop branch at commit 39348538

This happens the first time I tap on the media icon

![image](https://user-images.githubusercontent.com/4438193/32997614-7f44e5e4-cd92-11e7-9c27-5a23d57120d5.png)

![image](https://user-images.githubusercontent.com/4438193/32997661-2b804a92-cd93-11e7-98b7-80d7804f4671.png)

Then appears this

![image](https://user-images.githubusercontent.com/4438193/32997676-4e221a58-cd93-11e7-8715-d17fc956a5df.png)

**Comment by FrayxRulez** [comment]
Fixed removing the good stuff and leaving the old bad code
