### ISSUE TITLE
Error in Visual Studio while building latest commits from the develop branch

### ISSUE THREAD

**Issue by JMccormick264** [UnigramDev/Unigram#479]
I pulled the latest github commits. When I went to build the solution, I get the following error
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1503	Argument 2: cannot convert from 'string[]' to 'int'	Unigram	D:\Desktop_Stuff\Github_Clones\Unigram\Unigram\Unigram\ViewModels\Settings\SettingsStorageViewModel.cs	184	Active
```

[Image of error here](https://i.imgur.com/LzfIKR6.png)

**Comment by FrayxRulez** [comment]
You can replace the parameter with a zero, I’ll push a commit tomorrow (late night here)

**Comment by JMccormick264** [comment]
Take your time. Thank you for being quick with this!
