### ISSUE TITLE
Не запускается проект из исходников

### ISSUE THREAD

**Issue by Fart034** [UnigramDev/Unigram#480]
Выдает ошибку при развертывании Ошибка компилятора CS0006?

**Comment by rabiet** [comment]
Please speak English

**Comment by Fart034** [comment]
Does it generate an error while deploying Compiler error CS0006?

**Comment by Fart034** [comment]
I can not fix the error  CS0006 help.

**Comment by FrayxRulez** [comment]
Can you post the text you have in VS `Output` window?

**Comment by Fart034** [comment]
Thanks it worked, need the manual to fix the installation VisualStudio.
