### ISSUE TITLE
Menu Call

### ISSUE THREAD

**Issue by Fart034** [UnigramDev/Unigram#482]
Why when you click on the tab calls nothing happens?

**Comment by Fart034** [comment]
![23 11 2017 17_09_05](https://user-images.githubusercontent.com/14063025/33176734-2445ad22-d071-11e7-99d2-d6b9b622c199.png)

**Comment by larsschellhas** [comment]
You mean, why nothing happens when you click on someone in your calls-list?

Suggest a UX :)
Would you prefer calling that someone or to open the Chat with her?

**Comment by Fart034** [comment]
Yes, that's what. Yes I would prefer the chat.
