### ISSUE TITLE
Complete Unigram's "Community profile"

### ISSUE THREAD

**Issue by pablojim99** [UnigramDev/Unigram#483]
It will be great to add a "Code of conduct" (maybe [Contributor Covenant](https://www.contributor-covenant.org/version/1/4/code-of-conduct.html) or a modification of it) and an "Issue/Pull request template" in order to complete the recommend community standars.

![captura1](https://user-images.githubusercontent.com/17835916/33180028-9fb58a0a-d06b-11e7-9a83-6e6a98589f36.PNG)

What do you think?

**Comment by FrayxRulez** [comment]
I've added the __Code of conduct__ (I don't see the need tho). Would you like to propose issue and pull request templates?

Closing this since it isn't a real (app related) issue btw
