### ISSUE TITLE
Failed error

### ISSUE THREAD

**Issue by Fart034** [UnigramDev/Unigram#489]
Почему при сборке выходит ошибка >Сборка проекта "libtgvoip.UWP.vcxproj" завершена с ошибкой.

**Comment by FrayxRulez** [comment]
Clone recursively (`--recursive`)

**Comment by Fart034** [comment]
Рекурсивно я всегда клонирую, не помогает.

**Comment by Fart034** [comment]
git clone --recursive https://github.com/UnigramDev/Unigram.git Верно
