### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Fart034** [UnigramDev/Unigram#490]
Не удается открыть файл включение: mprapidef.h: No such file or directory, (компилируется исходный файл os\windows\NetworkSocketWinsock.cpp)	libtgvoip	C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\shared\iprtrmib.h	42

**Comment by FrayxRulez** [comment]
You can’t open tons of issues just because you aren’t able to compile the project. 
You need to install desktop C++ SDK alongside UWP C++ SDK

**Comment by Fart034** [comment]
Спасибо всё получилось
