### ISSUE TITLE
Notifications preview ignores private chats

### ISSUE THREAD

**Issue by shmykelsa** [UnigramDev/Unigram#491]
W10 Home 1709

Notifications previews will only work for groups or channels. Private chats messages don't show up, but they appear on action center no matter how much priority I give to Unigram. Uninstalling, resetting notifications, unchecking and re-checking settings won't work.

**Comment by MarcelBrusius** [comment]
@shmykelsa I had the same problem. I located the issue to be related to using MyPeople, though Unigram removed MyPeople support, and pinning contacts to the task bar.

Try disabling MyPeople and look if it fixes the issue.

**Comment by shmykelsa** [comment]
This indeed fixes the issue
