### ISSUE TITLE
Broken Unigram

### ISSUE THREAD

**Issue by akusmin** [UnigramDev/Unigram#492]
Second time I faced with the issue when Unigram became completely unusable. Unigram can be restoring only after reinstalling.
I have no ideas how to reproduce behavior. If you can give me some advice then I'll try to help.

Here is how Unigram looks like in a broken mode...

![image](https://user-images.githubusercontent.com/13545868/33539084-c4ccfd56-d8ee-11e7-9ae9-5c68edc3f4c4.png)

**Comment by FrayxRulez** [comment]
This is going to be solved with X update: https://t.me/unigram/162
