### ISSUE TITLE
Wrong images presentation

### ISSUE THREAD

**Issue by akusmin** [UnigramDev/Unigram#493]
There is an issue with pasting images into chat. If you are pasting several images into chat one by one you'll see only first one. Images become correct after reentering page.

Pasting two images into chat:
![image](https://user-images.githubusercontent.com/13545868/33541212-7838883e-d8f8-11e7-87e7-c98b3b57d984.png)

Reentering chat:
![image](https://user-images.githubusercontent.com/13545868/33541230-89dad36c-d8f8-11e7-8e29-63df76340e3f.png)

**Comment by FrayxRulez** [comment]
Update the app
