### ISSUE TITLE
Cannot set alphanumerical passcode

### ISSUE THREAD

**Issue by KamistixX** [UnigramDev/Unigram#495]
Hi,

Contrary to Telegram Desktop, we can't set alphanumerical passcode to lock/unlock the app. This can be a useful feature especially on Windows desktops/laptops with access to a physical keyboard, but without numeric keypad.
Currently only digits can be typed when setting up passcode.

Thanks !

**Comment by FrayxRulez** [comment]
Why have you closed it?

**Comment by KamistixX** [comment]
I thought it was not critical enough to leave it here among other issues

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/96fa402d793a249291dcdff448a645d7c6c5e1cc
