### ISSUE TITLE
Feature request: setting download folder

### ISSUE THREAD

**Issue by msvaillant** [UnigramDev/Unigram#497]
It would be better to able user to select folder where to save the files, because using temp folder is not nice option in most of cases (because Unigram stores there lots of its staff).
I have not investigated much, but it seems be easy to provide such a feature.

if you would have very little time on such a feature I will be glad to contribute to Unigram, but after New Year 🎅

**Comment by callummoffat** [comment]
I'll work on implementing this. I agree that it could be useful (so long as it is implemented in an unobtrusive way).

**Comment by callummoffat** [comment]
Unigram already offers the ability to save files outside of the temporary folder. Just right-click and select 'Save'. 

Unigram stores downloads in the temporary folder by default, because the majority of files it downloads are things you don't need to keep permanently (i.e. most images, etc.). Those files that you do wish to retain are infrequent enough that realistically, manual saving to another location is feasible.

**Comment by msvaillant** [comment]
I speak of kind of default behaviour like Telegram Desktop, without manually clicking on every item with "Save as", just clicking arrow invokes saving personal content (photos, files, videos) to specific folder.

for example, I received 10 photos of mockaps it chat - i need or to save as each of them? or try to find them inside temp folder - that is not easy, sometimes it is about docs, that are manually posted in some groups - to save each of them is about 3-5 except the only in Telegram Desktop

**Comment by enricorov** [comment]
Bump. Would be a _very_ useful feature to have. I use Telegram for school, I often need to access content from my usual folder (decompressing, saving elsewhere).

If this feature was implemented, I would gladly use Unigram instead of the super clunky desktop Telegram.

**Comment by FrayxRulez** [comment]
At the moment Unigram downloads are managed from C++, using `CreateFile2`, that only allows to access files inside AppData folder.

**Comment by FrayxRulez** [comment]
Implemented in https://github.com/UnigramDev/Unigram/commit/0582da784c50ffe1cdb8d8027caa5a8e24bc3ce0
