### ISSUE TITLE
Lost messages when Internet connection stops (and came back later)

### ISSUE THREAD

**Issue by dmnmsc** [UnigramDev/Unigram#499]
Unigram was in the background. I lost Internet connection at desktop and a minute later connection come back. I lost messages and notifications between lost and restablished connection. Some chats are updated because I reveived new messages after my connection came back. But some chats are outdated because I reveived new messages when Internet connection wasn't available.

![imagen](https://user-images.githubusercontent.com/8472142/34327339-dd5e1778-e8c1-11e7-948e-ec34f973f4d8.png)

**Comment by FrayxRulez** [comment]
https://github.com/UnigramDev/Unigram/commit/f037424682f4acefbff858231cdc2e78d7c05ef4 should improve the situation

**Comment by FrayxRulez** [comment]
This is going to be solved with X update: https://t.me/unigram/162
