### ISSUE TITLE
Phone calls don't work (or very exceptionally) 

### ISSUE THREAD

**Issue by SpringsTS** [UnigramDev/Unigram#501]
Hello

At first thank you for you application far better than the official Telegram on Windows phone!

I want to notify about the problem I have about calls:
Very often, when I try to call a contact, the call blocks in a random step (I can see the speaker button setting itself ON) and never progress, I have to stop the app and restart Unigram. Same when I receive a call.

And, always, after the first call/attempt, I cannot launch a second call without restarting Unigram, I have the message "Something went wrong."

Tried on Windows Phone 10 (Nokia Lumia 950).

Thank you in advance.

**Comment by FrayxRulez** [comment]
Situation should be better in 0.14.1161, closing this ATM
