### ISSUE TITLE
Solution not building

### ISSUE THREAD

**Issue by dante2130** [UnigramDev/Unigram#502]
Hi. Solution is not initially building (develop branch cloned)...

There is output from VS 2017:
`------ Skipped Build: Project: Telegram.Api.Native, Configuration: Debug ARM ------
Project not selected to build for this solution configuration 
------ Build started: Project: Telegram.Api, Configuration: Debug ARM ------
CSC : error CS0006: Metadata file 'C:\Users\dante\Desktop\Unigram\Unigram\ARM\Debug\Telegram.Api.Native\Telegram.Api.Native.winmd' could not be found
------ Build started: Project: Unigram.Core, Configuration: Debug ARM ------
CSC : error CS0006: Metadata file 'C:\Users\dante\Desktop\Unigram\Unigram\Unigram.Api\bin\ARM\Debug\Telegram.Api.dll' could not be found
CSC : error CS0006: Metadata file 'C:\Users\dante\Desktop\Unigram\Unigram\ARM\Debug\Telegram.Api.Native\Telegram.Api.Native.winmd' could not be found
------ Build started: Project: Unigram.Tasks, Configuration: Debug ARM ------
CSC : error CS0006: Metadata file 'C:\Users\dante\Desktop\Unigram\Unigram\Unigram.Api\bin\ARM\Debug\Telegram.Api.dll' could not be found
CSC : error CS0006: Metadata file 'C:\Users\dante\Desktop\Unigram\Unigram\ARM\Debug\Telegram.Api.Native\Telegram.Api.Native.winmd' could not be found
CSC : error CS0006: Metadata file 'C:\Users\dante\Desktop\Unigram\Unigram\Unigram.Core\bin\ARM\Debug\Unigram.Core.dll' could not be found
------ Build started: Project: UnigramHost, Configuration: Debug ARM ------
UnigramHost.vcxproj -> C:\Users\dante\Desktop\Unigram\Unigram\ARM\Debug\UnigramHost\UnigramHost.exe
------ Build started: Project: Unigram, Configuration: Debug ARM ------
C:\Program Files (x86)\Windows Kits\10\bin\10.0.16299.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets(263,5): Xaml Internal Error error WMC9999: The system cannot find the path specified. (Exception from HRESULT: 0x80070003)
========== Build: 1 succeeded, 4 failed, 8 up-to-date, 1 skipped ==========
`

Can anyone help me, please? I have desire to debug Xbox One version of app (Xbox One with activated dev. mode there's), but without successfully build i have no chances.

**Comment by FrayxRulez** [comment]
You need to manually compile Telegram.Api.Native by rightclicking it in the solution explorer (Also, to compile and run on Xbox One you have to choose x86 and not ARM)

**Comment by dante2130** [comment]
Of course, i understand it. Now i have target of X86 and on manually compiling of Telegram.Api.Native i have this errors:

`LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library
Telegram.Api.Native.vcxproj -> C:\Users\dante\Desktop\Unigram\Unigram\Debug\Telegram.Api.Native\Telegram.Api.Native.dll
C:\Users\dante\Desktop\Unigram\Unigram\Debug\Telegram.Api.Native\Telegram.Api.Native.winmd
C:\Users\dante\Desktop\Unigram\Unigram\Debug\Telegram.Api.Native\Telegram.Api.Native_Part.winmd
        2 file(s) moved.
Microsoft(R) Metadata Merge Utility Version 10.0.45.


Processing input metadata file C:\Users\dante\Desktop\Unigram\Unigram\Debug\Telegram.Api.Native\Metadata\Telegram.Api.Native.winmd.
Processing input metadata file C:\Users\dante\Desktop\Unigram\Unigram\Debug\Telegram.Api.Native\Metadata\Telegram.Api.Native_Part.winmd.
MDMERGE : error MDM2018: The type "Telegram.Api.Native.TL.ITLBinaryReader" defined in file C:\Users\dante\Desktop\Unigram\Unigram\Debug\Telegram.Api.Native\Metadata\Telegram.Api.Native_Part.winmd was referenced but could not be found.
MDMERGE : error MDM2018: The type "Telegram.Api.Native.TL.ITLBinaryWriter" defined in file C:\Users\dante\Desktop\Unigram\Unigram\Debug\Telegram.Api.Native\Metadata\Telegram.Api.Native_Part.winmd was referenced but could not be found.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: The command "mkdir "C:\Users\dante\Desktop\Unigram\Unigram\Debug\Telegram.Api.Native\Metadata\"
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: move /Y "C:\Users\dante\Desktop\Unigram\Unigram\Debug\Telegram.Api.Native\*.winmd" "C:\Users\dante\Desktop\Unigram\Unigram\Debug\Telegram.Api.Native\Metadata\"
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: mdmerge /metadata_dir "C:\Program Files (x86)\Windows Kits\10\References\..\UnionMetadata" /i "C:\Users\dante\Desktop\Unigram\Unigram\Debug\Telegram.Api.Native\Metadata" /o "C:\Users\dante\Desktop\Unigram\Unigram\Debug\Telegram.Api.Native\." /n 3 /partial /v
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: rmdir "C:\Users\dante\Desktop\Unigram\Unigram\Debug\Telegram.Api.Native\Metadata" /s /q
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: :VCEnd" exited with code 2.
Done building project "Telegram.Api.Native.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
`

As i understand - post-build command not successfully executed..
