### ISSUE TITLE
Telegram.Api.Native not successfully compiled

### ISSUE THREAD

**Issue by dante2130** [UnigramDev/Unigram#503]
`LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library
Telegram.Api.Native.vcxproj -> C:\Users\dante\Desktop\Unigram\Unigram\Debug\Telegram.Api.Native\Telegram.Api.Native.dll
C:\Users\dante\Desktop\Unigram\Unigram\Debug\Telegram.Api.Native\Telegram.Api.Native.winmd
C:\Users\dante\Desktop\Unigram\Unigram\Debug\Telegram.Api.Native\Telegram.Api.Native_Part.winmd
        2 file(s) moved.
Microsoft(R) Metadata Merge Utility Version 10.0.45.

Processing input metadata file C:\Users\dante\Desktop\Unigram\Unigram\Debug\Telegram.Api.Native\Metadata\Telegram.Api.Native.winmd.
Processing input metadata file C:\Users\dante\Desktop\Unigram\Unigram\Debug\Telegram.Api.Native\Metadata\Telegram.Api.Native_Part.winmd.
MDMERGE : error MDM2018: The type "Telegram.Api.Native.TL.ITLBinaryReader" defined in file C:\Users\dante\Desktop\Unigram\Unigram\Debug\Telegram.Api.Native\Metadata\Telegram.Api.Native_Part.winmd was referenced but could not be found.
MDMERGE : error MDM2018: The type "Telegram.Api.Native.TL.ITLBinaryWriter" defined in file C:\Users\dante\Desktop\Unigram\Unigram\Debug\Telegram.Api.Native\Metadata\Telegram.Api.Native_Part.winmd was referenced but could not be found.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: The command "mkdir "C:\Users\dante\Desktop\Unigram\Unigram\Debug\Telegram.Api.Native\Metadata\"
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: move /Y "C:\Users\dante\Desktop\Unigram\Unigram\Debug\Telegram.Api.Native\*.winmd" "C:\Users\dante\Desktop\Unigram\Unigram\Debug\Telegram.Api.Native\Metadata\"
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: mdmerge /metadata_dir "C:\Program Files (x86)\Windows Kits\10\References\..\UnionMetadata" /i "C:\Users\dante\Desktop\Unigram\Unigram\Debug\Telegram.Api.Native\Metadata" /o "C:\Users\dante\Desktop\Unigram\Unigram\Debug\Telegram.Api.Native\." /n 3 /partial /v
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: rmdir "C:\Users\dante\Desktop\Unigram\Unigram\Debug\Telegram.Api.Native\Metadata" /s /q
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(133,5): error MSB3073: :VCEnd" exited with code 2.
Done building project "Telegram.Api.Native.vcxproj" -- FAILED.`

**Comment by FrayxRulez** [comment]
But you can't create an issue every time you can't compile the app... Join our group: https://t.me/joinchat/AksYVT851opwnh1kQM85Jg
