### ISSUE TITLE
Background update of currently displayed channel scrolls the view away from current reading point

### ISSUE THREAD

**Issue by roman380** [UnigramDev/Unigram#506]
As the view scrolls away, it is rather annoying to have to scroll back and look for position to continue reading from.
  
Apparently on update the application should not scroll away and should just indicate availability of new items.

**Comment by FrayxRulez** [comment]
What do you mean

**Comment by roman380** [comment]
As simple as this: I have some channel selected and I read new posts. As I read new posts arrive and the application scrolls itself to the bottom. I have to scroll up and find the place where it interrupted my reading at.
