### ISSUE TITLE
Not appearing in the windows task bar as of 0.14.1160

### ISSUE THREAD

**Issue by romme** [UnigramDev/Unigram#508]
Not much else to say.

**Comment by pablojim99** [comment]
I had the same issue when I updated the app. The icon of the taskbar disappear but I was able to pin it back.
I don't know what can cause this issue. Maybe a Windows bug?

**Comment by FrayxRulez** [comment]
Apps have absolutely no control over the task bar icon.

**Comment by romme** [comment]
Reinstalling the app solved the issue.
