### ISSUE TITLE
Unigram won't open

### ISSUE THREAD

**Issue by BadCode7** [UnigramDev/Unigram#51]
I can't open the latest version of Unigram, I could install previous version successfully .
My device is HTC One M8 with Build 14393.321

**Comment by kesavaprasadarul** [comment]
Please tell about it. We need more information. Did you successfully install the latest version, and could not run it? If so, what was the error?

**Comment by BadCode7** [comment]
Yes I installed successfully and on opening the logo of Unigram shown, But after 5 seconds it crashes

**Comment by kesavaprasadarul** [comment]
@BadCode7 What's this?

**Comment by FrayxRulez** [comment]
But you did login the first time or the app never started?

**Comment by BadCode7** [comment]
No, I can't login

**Comment by FrayxRulez** [comment]
Try to install these dependencies and try again:
https://www.dropbox.com/s/rnmbumwcbzwpja5/Dependencies.Redstone.zip?dl=1

**Comment by BadCode7** [comment]
I installed them but problem exists.

**Comment by BadCode7** [comment]
@FrayxRulez 
No chance to open the latest version of unigram after installing those dependencies

**Comment by FrayxRulez** [comment]
Should work now
