### ISSUE TITLE
Notifications stopped working in 0.14.1160

### ISSUE THREAD

**Issue by ariel-** [UnigramDev/Unigram#511]
**Description:**

Notifications not work anymore as of current store version (v0.14.1160)

**Current behaviour:**

When you receive a message nothing appears in the notification center, when you open the app you have unread messages though.

**Expected behaviour:**

When you receive a message you should get a notification in the notifications center.

**Steps to reproduce the problem:**

1. Log in to Unigram
2. Go to Home Screen
3. Receive a message

**Platform:** Microsoft Lumia 640 XL LTE, Windows 10 Mobile 10.0.15063.850

**Notes:** Already checked notifications settings in the phone and on the app. Chat is not muted.

**Comment by ariel-** [comment]
Should've searched closed issues too (#507). Thank you anyways.

Now to wait the version bump on the store :P

**Comment by FrayxRulez** [comment]
0.14.1161 is already available!

**Comment by ariel-** [comment]
Broken again with Unigram X update (version 1.0.1491)
