### ISSUE TITLE
ReplyMarkup not updated after notification

### ISSUE THREAD

**Issue by bugada** [UnigramDev/Unigram#512]
Clicking on a notification when unigram has been suspended into a bot, resumes unigram but reply markup won't be updated anymore.

1 - open unigram ad enter in a bot with keyboard
2 - put unigram in background
3 - wait for notification from that bot
4 - click notification
5 - execute another bot command
6 - replymarkup is not updated

Workaround: go back to chat list and reenter into the bot, markup is ok.

Unigram Version: 0.14.1161
Platform: Mobile 
SO version: 1709
SO build: 10.0.15254.158

**Comment by bugada** [comment]
It happens often also after receiving a new message while i'm in the bot chat

**Comment by FrayxRulez** [comment]
This is going to be solved with X update: https://t.me/unigram/162
