### ISSUE TITLE
[Desktop] Disable GIF playback if unigram no longer focused

### ISSUE THREAD

**Issue by jp-weber** [UnigramDev/Unigram#514]
It would be great if the function would be implemented as in the "Telegram Desktop" client.

**Comment by FrayxRulez** [comment]
I don't think this is actually necessary: 
Videos (and GIFs, since they're actually mp4s) playback, contrary to what tdesktop does, is handled by the system and hardware accelerated.

**Comment by jp-weber** [comment]
@FrayxRulez but it would be very nice, if Unigram not focused the gif playback will stops like TelegramDesktop.
