### ISSUE TITLE
Error message on Lumia 1520 | W10M 10.0.14393

### ISSUE THREAD

**Issue by skid9000** [UnigramDev/Unigram#517]
Hi,

Some random error message started poping in the Unigram app on my Lumia 1520.

Unigram version : 0.14.1203

Don't have more details :/

<img src="https://puush.tuto-craft.com/photo_2018-01-24_12-35-36.jpg">

<img src="https://puush.tuto-craft.com/photo_2018-01-24_12-44-412.jpg">

**Comment by FrayxRulez** [comment]
Sorry but this isn’t sufficient in any way
