### ISSUE TITLE
[Question/Suggestion] option for rectangle/ellipse picture

### ISSUE THREAD

**Issue by revan1199** [UnigramDev/Unigram#52]
Hi,
I've been following the project now for some time and find it really amazing what has been done.
On thing what I don't like at many apps are the ellipse picture of the accounts. That's why I would like an option for this.

**Comment by ikarago** [comment]
Thank you for the suggestion!

We won't be implementing this, as it requires a lot of work (programmatically) and brings extra mass to the UI, which we try to keep as lean and clean as possible, so Unigram will be fast to use. ;)

My apologies for this, yet if you have more ideas, keep 'm coming! :)
