### ISSUE TITLE
Messages aligned to right

### ISSUE THREAD

**Issue by Ujinjinjin** [UnigramDev/Unigram#524]
Hi, app updated to version 0.14.1214.0 and now half of messages aligns to right instead of left. Like on picture.

Windows 10 Pro 1709
Build 16299.192

![image](https://user-images.githubusercontent.com/20992866/35587240-45cfe494-060e-11e8-9d50-d3f04fb1e623.png)

**Comment by FrayxRulez** [comment]
Update to 0.14.1216 when available (maybe already, I didn’t checked)
