### ISSUE TITLE
[Feature request] TDLib

### ISSUE THREAD

**Issue by ariel-** [UnigramDev/Unigram#525]
Since today Telegram announced [TDLib](https://github.com/tdlib/td) for building alternate clients. Is there a possibility for Unigram to start using it?

**Comment by FrayxRulez** [comment]
Tdlib is available on android since about two years, but it isn’t available for uwp.

**Comment by Alovchin91** [comment]
@FrayxRulez It's open source and written in cross-platform C++14. You could at least try to compile it, and then wrap it with C++/WinRT. So please re-open the issue.

**Comment by FrayxRulez** [comment]
https://t.me/unigram/162

**Comment by Alovchin91** [comment]
@FrayxRulez Now we're talking) This should have been the real answer to this issue since the very beginning. Thank you, excited about it! :smiley:
