### ISSUE TITLE
Quite so often Unigram stays not up to date not seeing new messages

### ISSUE THREAD

**Issue by roman380** [UnigramDev/Unigram#527]
Typically I would close it and restart, and new messages appear. Why don't add an explicit command to refresh? It can be a button or sliding something to side.

**Comment by FrayxRulez** [comment]
https://t.me/unigram/162

**Comment by FrayxRulez** [comment]
Can you write me at t.me/frayxrulez?

**Comment by roman380** [comment]
It is worth mentioning that Unigram X does the updates well!
