### ISSUE TITLE
Feature request: support People app in Windows 10

### ISSUE THREAD

**Issue by 1448839220** [UnigramDev/Unigram#531]
![image](https://user-images.githubusercontent.com/12206788/36733032-5a07a50c-1c0a-11e8-9aae-5b86983cc3d2.png)

**Comment by FrayxRulez** [comment]
Available in last store version

**Comment by zabi94** [comment]
is this available for groups too? I just downloaded the app but I can't find a way to pin them

**Comment by msvaillant** [comment]
I do not think that it is possible to integrate groups with "people", especially because it is supposed for any "person" to have at least e-mail, phone number, etc... so the feature is only about communication with someone, not the group at whole meaning
