### ISSUE TITLE
Unigram X lacks the ability to resize chat list horizontally / collapse to icon only

### ISSUE THREAD

**Issue by ScottRFrost** [UnigramDev/Unigram#537]
In the official telegram desktop, you can resize the chat list horizontally, including the ability to make it down to just the icons:

![image](https://user-images.githubusercontent.com/3866418/36790417-bef114fa-1c62-11e8-9bfa-e7d7f6a99402.png)

Please implement this functionality in Unigram X, as it saves quite a bit of screen real estate.

**Comment by ScottRFrost** [comment]
I believe this is mostly fixed by https://github.com/UnigramDev/Unigram/releases/tag/v1.2.1562

**Comment by FrayxRulez** [comment]
Somehow, you can’t resize the panels manually, it goes in compact mode automatically when window width is > 500 and < 820

**Comment by ScottRFrost** [comment]
Windows Store isn't offering me the new build yet, but if they have to ability to make it icon-only hopefully they can just add a toggle to settings to force it to always render in "compact" icon-only mode

**Comment by FrayxRulez** [comment]
Update is still being certified. 
I’m not a fan of having dozens of small options tho.

**Comment by FrayxRulez** [comment]
Implemented in https://github.com/UnigramDev/Unigram/commit/200c66756b7d5b7aa22c02d7fbc22fe6bfbf5ce8
