### ISSUE TITLE
Support My People notifications

### ISSUE THREAD

**Issue by xperiandri** [UnigramDev/Unigram#539]
https://docs.microsoft.com/en-us/windows/uwp/contacts-and-calendar/my-people-notifications

**Comment by xperiandri** [comment]
https://mspoweruser.com/uwp-community-toolkit-v2-2-now-available-people-shoulder-taps-support/

**Comment by FrayxRulez** [comment]
Supported image types
- GIF
- Static Image (JPEG, PNG)
- Spritesheet (vertical only)

Telegram stickers are WEBP, they aren’t over HTTP and the notification payload has no infos about them. 

I also don’t like UWP toolkit.

**Comment by xperiandri** [comment]
But at least sent images can be displayed

**Comment by FilipeRamalho** [comment]
WebP can be converted to JPEG/PNG, by loading WebP as BMP and then convert it to JPEG/PNG.
https://stackoverflow.com/questions/41665/bmp-to-jpg-png-in-c-sharp
https://github.com/JosePineiro/WebP-wrapper
If this isn't desired image/Gif notifications could still be implemented.

You don't have to use the UWP toolkit for that. You can make a toast XML and then start it (See example below)

The source doesn't have to be HTTP
"The URI of the asset. This can be either HTTP/HTTPS web URI, a msappx URI, or a path to a local file."

Example Toast XML
```
<toast hint-people="mailto:johndoe@mydomain.com">
    <visual lang="en-US">
        <binding template="ToastGeneric">
            <text hint-style="body">Toast fallback</text>
            <text>Add your fallback toast content here</text>
        </binding>
        <binding template="ToastGeneric" experienceType="shoulderTap">
            <image src="https://docs.microsoft.com/en-us/windows/uwp/contacts-and-calendar/images/shoulder-tap-pizza-static.png"
                spritesheet-src="https://docs.microsoft.com/en-us/windows/uwp/contacts-and-calendar/images/shoulder-tap-pizza-spritesheet.png"
                spritesheet-height='80' spritesheet-fps='25' spritesheet-startingFrame='15'/>
        </binding>
    </visual>
</toast>
```
Starting the notification 
```
ToastNotification notification = new ToastNotification(xmlContent);
ToastNotificationManager.CreateToastNotifier().Show(notification);
```
Result
![pizza-notification-small](https://user-images.githubusercontent.com/25137217/42764913-143605d0-8917-11e8-8daf-befa75d80a09.gif)

**Comment by FrayxRulez** [comment]
This ticket is closed.

**Comment by mautheus** [comment]
@FrayxRulez 😂

**Comment by xperiandri** [comment]
@FrayxRulez you may be more specific 😃
