### ISSUE TITLE
How do I make calls?

### ISSUE THREAD

**Issue by roboxv** [UnigramDev/Unigram#542]
Hello.

You app is awesome. Thank you.

It seems it supports calls. But I don't get how I can make ones.

Windows 10 desktop. Unigram X 1.0.1491

**Comment by xperiandri** [comment]
Not supported.
Unfortunately @FrayxRulez was not managed to implement calls and inline reply in reliable way yet.
Some troubles in managing state from two separate processes which required for VoIP integration in UWP.

Especially on Mobile it hangs and does not work until you reboot device.

**Comment by ScottRFrost** [comment]
Receiving calls is also broken.  If these features are not coming soon, you should probably update https://github.com/UnigramDev/Unigram/wiki/Features to remove Voice Calls as a feature, as users may rely on them and won't expect them to be broken.

**Comment by FrayxRulez** [comment]
Receiving calls isn't "__broken__". Receiving calls isn't implemented at all, and it will never be.

**Comment by xperiandri** [comment]
You are so pessimistically confident 🤣

**Comment by ScottRFrost** [comment]
Skype / Viber / etc all work on UWP, so I wouldn't say "never will be" unless it's a design choice rather than a platform limitation.  Either way, I didn't mean any offense by calling it broken.  Perhaps this is a good call for contributors to put on the front page / root readme.md ?

**Comment by FrayxRulez** [comment]
I'm not looking for contributors.

It's a platform limitation.
Calls need to run in a separate process from the app and this causes many problems:
- Multiple TDLib instances can't run simultaneously due to files access
- Even if TDLib could, Telegram servers only send updates to a single connection in the same session: only calls process or main app process would receive updates, breaking completely the app functionalities.

**Comment by luminelx64** [comment]
The official Telegram app for Windows phone supports calling.
How were they able to implement it?

**Comment by FrayxRulez** [comment]
Windows phone and Windows are two different things

**Comment by xperiandri** [comment]
@luminelx64 they don't use native VoIP API
You can notice that custom call UI is used that mimics system UI.

**Comment by segin** [comment]
You don't have to be passive-aggressive about not getting your way. Grow up, @comfuzio

**Comment by comfuzio** [comment]
I've just asked if there is going to be calls in the app, it doesn't seem so. What's the point in having a half app?
Now if you want to have half apps and be happy with it, that's your deal, not mine.
P.S. Keep and apply your advice to your self mate

**Comment by xperiandri** [comment]
Point is to have energy efficient client that works in Connected Standby mode

**Comment by FrayxRulez** [comment]
Calls will be available with latest update, but they won't be integrated in any way with the system.
You won't be able to answer while the app is closed, nor you won't be able to close the app while the call is in progress.
If you don't close the call popup then you should be able to mimize the app, but if you close it the call will get muted: Windows doesn't allow to record while the app is hidden, and the app gets suspended by the system anyway if you minimize it (I want to underline that I'm talking about minimizing, not leaving it below some other window)

**Comment by xperiandri** [comment]
@FrayxRulez do you mean you re-implemented calls the same way as TG for Windows Phone does? In-process and with no Windows integration?

**Comment by FrayxRulez** [comment]
I don’t know how calls in Telegram WP are, but yes.

**Comment by ScottRFrost** [comment]
lul, I forgot I was subscribed to this since I had commented.

The basically sole developer (check commits) is openly hostile to GitHub users & doesn't know how to implement this feature anyway.  

I recommend that you just go back to the official client where voice calls work and forget about this project like I did.

**Comment by MarcAnt01** [comment]
Calls have been implemented and learn to respect the dev, you are a just a rude child

**Comment by comfuzio** [comment]
I'm sorry for the off-topic but why do you think that when we say something other than "thank you" we are children? The segin guy above towards me, now MarcAnt01 towards ScottRFrost.
I don't know how old ScottRFrost is, but I am not a kiddo nor I need to grow up or need some rude strangers from the web to tell me how to behave. It is you guys, who need to listen up your user base and grow up. Or stay as you are and lose even more people!

**Comment by MarcAnt01** [comment]
I was not talking with you, everyone can say whatever he thinks, but as the dev is doing all this without being paid a cent, I want that all have a minimum respect for him

**Comment by comfuzio** [comment]
Point taken :)

**Comment by FrayxRulez** [comment]
Well, it’s not my fault if most of Windows background tasks (including VoIP) require to run in a separate process and this causes issues with TDLib:
First of all TDLib needs to read and write from a database and this can’t be a shared operation, as result only a single Client can be created at once. 
Second thing, even being able to create two Clients operating on the same database there would be still a problem: Telegram sends updates to a single connection per session. 
As result only the main app (or the voip call, if started before the app) would receive updates and the calls won’t work properly anyway. (I spent quite a lot of time together with telegram engineer  a year ago when calls have been first introduced trying to find out a viable solution, but it hasn’t been found)

Last but not least: this is an open source project, maintained only by me:
- I have a full time job that takes most of my time
- I earn absolutely nothing from this project, and it is just an hobby for me, so in my opinion you can pretend absolutely nothing, especially being unrespectul.

**Comment by comfuzio** [comment]
Imho make a patreon page, so people can donate and help the project, even if people can't donate (example) 10$, they can 1$/month. I've switched to linuxmint 19 a few days now and use the telegram they have there, very happy with it so far! If I go back to w10, I will give it another try!

**Comment by xperiandri** [comment]
@FrayxRulez, I've been thinking about this

> First of all TDLib needs to read and write from a database and this can’t be a shared operation, as result only a single Client can be created at once.
> Second thing, even being able to create two Clients operating on the same database there would be still a problem: Telegram sends updates to a single connection per session.

And I have a question. Why can't you use TDLib in host only and then IPC to visual app all the commands and data?

**Comment by FrayxRulez** [comment]
Because you can’t exchange objects between processes and you have to serialize them, and this would surely affect performances

**Comment by xperiandri** [comment]
It will a bit. I'm not sure that it will be too expensive.
As you don't need to serialize photos or streams the only left some texts and internal states.

**Comment by FrayxRulez** [comment]
Every data received from telegram servers passes via tdlib, the app should be able to process tons of updates, and it would be needed to pass full objects, probably in json. It would affect quite a lot. 

Also, most important, IPC in UWP isn’t reliable at all, and it’s quite crazy to use it for something like this. It is more designed to pass small infos between process (eg in a music app inform the UI that the active song has changed)

**Comment by FrayxRulez** [comment]
Also I want to add that Unigram prior to TDLib was using IPC to make calls using system integration and it was basically not functional. (And data was serialized in MT rather than JSON)

**Comment by xperiandri** [comment]
Well I would prefer to have that overhead than having call muted when phone lock near to your head after lock timeout and you can't figure out what happened
Can we use db as read only in UI app? But send all commands via IPC to host

**Comment by FrayxRulez** [comment]
No, sorry, there's no real world viable way to integrate calls with system.

**Comment by FrayxRulez** [comment]
Especially being Windows Mobile a side market. The app isn't receiving any mobile-specific optimization anymore, and all the existing ones are being rewritten to be PC optimized over time.
