### ISSUE TITLE
Voice and video messages problems.

### ISSUE THREAD

**Issue by hoseinzamani** [UnigramDev/Unigram#543]
voice message can't be stoped manually, it will just stop automatically when it gets finished. if you try to stop it by the button it keeps playing over and over.
video messages play with no sound and they can't be stopped from playing too.

thanks for the speed and caching ability of last update.

**Comment by ariel-** [comment]
In addition the voice messages show a static 'waveform' image and you can't 'seek' to start from the middle of the message for example

**Comment by iPonyRadio** [comment]
Unigram X 1.2.1569
Windows 10 17134.1

Audio messages not playing whatsoever. Click play, no reaction. Audio waveforms show half-played.

![yyydneu 1](https://user-images.githubusercontent.com/5401039/38909413-88b36ed2-4292-11e8-8c0d-eb44d19cd6e2.png)

**Comment by MarcAnt01** [comment]
@hoseinzamani  do you have still problems with audio messages? Video ones are already covered with another ticket

**Comment by MarcAnt01** [comment]
@iPonyRadio your issue is already cover by that one https://github.com/UnigramDev/Unigram/issues/298
