### ISSUE TITLE
InkCanvas integration

### ISSUE THREAD

**Issue by arcadiogarcia** [UnigramDev/Unigram#544]
If this is somehting the project maintainers consider interesting, I'd like to implement this feature and send a PR, here is a description of the proposed feature:

While using Unigram I often find myself switching to Sketchpad to make a quick sketch, copying it in the clipboard and pasting it in Unigram to send it to someone. I think it would be really cool if Unigram had the option to quickly send handwritten notes and doodles, this is how I imagine the feature:

- In the list of possible attachments, have an additional option labeled Ink, Canvas, Sketch, Drawing or something along those lines
![image](https://user-images.githubusercontent.com/9416356/36871438-1fe41d08-1d57-11e8-9d7b-f6c499dd46e0.png)
- When the user selects it, show a page with an InkCanvas covering the whole window, a basic windows ink toolbar with extra "send" and "cancel" buttons.
- The user can write/draw, and then pressing the "send" button will close the canvas send the drawing while pressing "cancel" while exit the canvas without sending anything.
    - Initially, the canvas would be rasterized to a picture and sent just as any other regular picture. However, there are additional delighters that could be added: generating and sending a gif that shows the strokes appearing one by one, and attaching to that gif the native windows ink data so if the receiver uses unigram it is converted back to ink and displayed without any quality loss.

I think this could be a cool differentiator over other Unigram clients, while still preserving total compatibility and requiring little work.

**Comment by Wphelp98737** [comment]
آموزش و پروش

**Comment by amirali013** [comment]
@Wphelp98737 🤔

**Comment by MarcAnt01** [comment]
@arcadiogarcia I have seen this feature request 1 year and half later, anyway wouldn't it be easier to add a sketch function in the preview of sent pictures like Telegram mobile apps?

**Comment by MarcAnt01** [comment]
Closing, if you plan to discuss about this further I'll reopen it
