### ISSUE TITLE
Cant login via proxy

### ISSUE THREAD

**Issue by Losses** [UnigramDev/Unigram#545]
1. Open Unigram, enter my phone #,
2. Set the proxy,
3. Infinite progress bar for several hours.

The proxy server is accessible, but Unigram was unable to handle it.

What should I do to provide some log or something else....?

**Comment by FrayxRulez** [comment]
Proxy is handled by TDLib, you might want to open an issue [here](https://github.com/tdlib/td), specifying that’s about TDLib for UWP.

**Comment by Jack-Works** [comment]
@FrayxRulez Hello, tdlib say they already fix the problem, when can unigram update to the latest version of tdlib?

**Comment by FrayxRulez** [comment]
As @levlam said the fix will be available with the next update.

**Comment by FrayxRulez** [comment]
Working in the last Store release

**Comment by Losses** [comment]
@FrayxRulez amazing, it works again :D
