### ISSUE TITLE
No sticker preview 

### ISSUE THREAD

**Issue by ariel-** [UnigramDev/Unigram#546]
When previewing (tap and hold over a sticker) from a collection (opened after tapping on a sticker that is sent to chat): screen is darkened but no preview shows.

When previewing from the added sticker sets (tapping on the sticker button): Screen is darkened and the legend 'Unigram.ViewModels.Dialogs.StickerViewModel' appears

Unigram X 1.0.1516 Mobile

**Comment by someniatko** [comment]
Confirming, I have the same issue: https://ibb.co/gC6oQd

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/6b594dc641e2966d8ab886d1c36d044432d192a2

**Comment by heroje** [comment]
Doesn't seem to work in 3.14.2670 on a Windows 10 PC using a mouse - I don't get a preview at all.

**Comment by MarcAnt01** [comment]
Done in https://github.com/UnigramDev/Unigram/commit/93e0b60eb96bd77e7d2f6332359a4dd3648ddf1a
