### ISSUE TITLE
Notifications synchronization between mobile and PC does not work

### ISSUE THREAD

**Issue by penartur** [UnigramDev/Unigram#547]
Steps to reproduce:

1. Make sure that your PC and phone are connected to the same MS account, and that Cortana notifications synchronization is enabled (that is, you get notifications from your phone on your PC).
2. Install Unigram X on both your PC and phone; log in to the same account.
3. Receive some telegram message.

Expected results:
There is only one notification on PC; click on this notification opens Unigram X.

Actual results:
There are two notifications on PC (one from local Unigram X, and another from "Unigram X * via Cortana" in the "Mobile device" section). Click on the second notification opens Cortana with the message "You got a notification from Unigram X on Mobile device, so check there for more details".

I'm using latest windows 10 stable on PC (16299.248) and latest (last?) windows 10 fast ring on mobile (15254.158). Unigram is at latest version on both.

**Comment by FrayxRulez** [comment]
I don’t think there’s actually any API to handle notifications synchronization

**Comment by penartur** [comment]
@FrayxRulez I heard that it should work without any effort from the developer, if application ID and notification ID match? (and it certainly works in first-party apps such as Mail).

I may be wrong though. I'll try to find some more information on how this could be implemented.

**Comment by Silic0nS0ldier** [comment]
The feature is [Universal Dismiss](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/universal-dismiss) I believe. All it requires is a single common id (`RemoteId`), and Windows should have everything it needs to identify duplicates (fixing this issue) and dismiss the notification across the Windows platform.

**Comment by FrayxRulez** [comment]
All notifications are unique:
- they have an unique `Group` (chat id)
- an unique `Tag` (message id)
- and an unique `RemoteId`

Push notifications are also suppressed while the app is open, to only provide you in-app notifications (that are much more reliable). 
Useless to say that in-app ones use the same “uniqueness” logic as the others. 
You can spot in-app notifications from the text, that is sightly different, and since a couple of version from the profile picture. 

Obviously if you receive an in-app notification, and then you leave the app there’s no way to prevent duplicated ones from my side. 
The system should recognize this from `Tag`, `Group` and `RemoteId` and simply replace the others.

**Comment by penartur** [comment]
> Obviously if you receive an in-app notification, and then you leave the app there’s no way to prevent duplicated ones from my side.

I believe that I'm talking about the opposite scenario here? If we forget about desktop for a minute: I've received a notification on mobile (I guess it's a push notification); opened the app by clicking on its live tile; and received another notification for the same message (I guess it's an in-app notification).

As I understand, for in-app notifications you set `Group` to `c9999` (where 9999 is group id), `Tag` to `2222` (where `2222` is message id multiplied by 1048576), and `RemoteId` to `2222_c9999`.
But I'm not sure where push notifications are handled? I was unable to find it and check that `Group`, `Tag` and `RemoteId` are computed in same way there.

Additionally, it seems that `NotificationService.OnPushNotificationReceived` (https://github.com/UnigramDev/Unigram/blob/4832e8fab3cc1fe9df813e42dda5a83952da4e97/Unigram/Unigram/Services/NotificationsService.cs#L184) does not actually do anything? Probably some code is missing there?

**Comment by penartur** [comment]
I've just found another place where you seem to create notifications: https://github.com/UnigramDev/Unigram/blob/1fdc2899f77d185eb98dc67140be1867917ea915/Unigram/Unigram.Tasks/TLPushUtils.cs#L209

And these notifications do not have their `RemoteId` set. Could that be the problem?

**Comment by FrayxRulez** [comment]
`OnPushNotificationReceived` is used to suppress push notifications while the app is open (`e.Handled = true;`). 

`TLPushUtils.cs` isn’t used anymore (since more than a year I think 😆)

This is the class you’re looking for:
https://github.com/UnigramDev/Unigram/blob/523c570cc811ee4535763aef6c93d1e8e231bcb0/Unigram/Unigram.Native.Tasks/NotificationTask.cpp#L705

**Comment by penartur** [comment]
> TLPushUtils.cs isn’t used anymore (since more than a year I think 😆)

Oh I see now. It would be easier if there was no dead unused code :)

> This is the class you’re looking for:

Yes, I've already mentioned it in my first comment today. `NotificationTask::UpdateToast` from that class is only called from `NotificationTask::UpdateToastAndTiles` in the same class, and from `NotificationTask.Handle` in C# code: https://github.com/UnigramDev/Unigram/blob/523c570cc811ee4535763aef6c93d1e8e231bcb0/Unigram/Unigram/Services/NotificationsService.cs#L131
(and that C# code is where you multiply messageId by 1048576 and prepend `c` char to the group ID).
So that's one kind of notifications (as you have said, there are two kinds, in-app and push).

`NotificationTask::UpdateToastAndTiles`, in turn, is only called from TLPushUtils (which you say is not used anymore) and from `NotificationTask::Run` which deals with `RawNotification` which does not seem to be created anywhere? Or is that the incoming push details in JSON? It parses that JSON and then calls `UpdateToast` with its own `Tag` and `Group` which seem to be computed in a way different from `NotificationService.cs`.

So here it is:

1) https://github.com/UnigramDev/Unigram/blob/523c570cc811ee4535763aef6c93d1e8e231bcb0/Unigram/Unigram/Services/NotificationsService.cs
2) https://github.com/UnigramDev/Unigram/blob/523c570cc811ee4535763aef6c93d1e8e231bcb0/Unigram/Unigram.Native.Tasks/NotificationTask.cpp

Both have their own `GetTag` and `GetGroup` logic (seems to be for push vs in-app notifications).
And the logic seems to be a bit different:

1) In C# code, `Tag` is messageId multiplied by 1048576, while in C++ code, `Tag` is just messageId.
2) In C# code, `Group` is computed differently for basic group and supergroup (different fields are used), while in C++, `Group` is always `"c"+chat_id` (if that field exists). In C# code, `Group` seems to be `string.Empty` for channels, while in C++, it is `"c"+channel_id`.
3) `RemoteId` is then computed in `NotificationTask::UpdateToast` from `Tag` and `Group`, always in the same way. Which does not help if `Tag` and `Group` are computed differently.

Could that seeming inconsistency between `GetTag` and `GetGroup` computations in these two places explain the problem, or am I missing something?

**Comment by FrayxRulez** [comment]
They are computed exactly in the same way:
Message ids are in a different space, in the running app, the `<< 20` is used to get the original message id. 
Channels and Supergroups are the same thing.

**Comment by penartur** [comment]
It's super-odd, but now I'm getting three (!) toasts and four toast sounds on desktop for some messages (both for messages in one-on-one chats, and for mentions in supergroups). 

1) First, I get a toast with channel logo / user avatar, from "Unigram X", with the corresponding sound;
2) Then, after some 500-2000ms, I get a toast without logo, from "Unigram X | via Cortana", and it sounds as if two toasts arrived at once (second notification sound starts playing, and then is interrupted by a third);
3) Then, another 500-2000ms later, I get a third toast with channel logo / user avatar, also from "Unigram X", accompanied by a fourth notification sound.

However, there are only two notifications in notification center (one with channel logo / user avatar in "Unigram X" section, and another without a logo from "Unigram X | via Cortana" in "Mobile device" section).

So it seems that something goes terribly wrong with Windows as well. Ideally, there should be only one notification and one toast and one sound. Two at most, if notification synchronization is broken. But definitely not three toasts and not four sounds within a couple of seconds.

I guess we need a little help from someone who is experienced with all this notifications stuff.

**Comment by FrayxRulez** [comment]
I’m quite experienced, to be honest (I work daily with WinRT since it is born). 

Tried to simply uninstall and reinstall the app or to kill all the Telegram (> Unigram) active sessions on that machine?

Not to reset the app.
Resetting the app would just lead to an additional duplicated notification:
Local app data are deleted, but notifications channel isn’t resetted, but the token yet changes:
This mean that you’ll end up with a zombie session with active notifications.

**Comment by penartur** [comment]
> I’m quite experienced, to be honest (I work daily with WinRT since it is born).

Oh, sorry about that! I said that because you originally commented that you don't know about notifications synchronization feature...

> Tried to simply uninstall and reinstall the app or to kill all the Telegram (> Unigram) active sessions on that machine?

Yes, killing Unigram sessions (and then logging in again) did the trick, and now I'm back on square one but without these four sounds per message at least 😁 

I've experimented a little with sessions and here is what I'm getting:

When there is only one session on PC (and Unigram is open but is not in front): it displays one toast with avatar; only one notification is displayed in Notification center on PC.

When there is only one session on Mobile: it displays one toast without avatar (push notification?) when Unigram is closed (this toast is also shown on PC without icon from "Unigram X | via Cortana"), and then another (in-app notification?) for the same message when I open Unigram by clicking on its tile (this one is also shown on PC without icon from "Unigram X | via Cortana"). Both notifications are displayed in Notification center on mobile, under "Unigram X". Both notifications are displayed in Notification center on PC, under "Mobile device", as originating from "Unigram X | via Cortana".

When there are sessions on both PC and Mobile (with Unigram closed on Mobile, and open but not in front on PC): PC displays one toast with avatar from "Unigram X" and then displays another toast without icon from "Unigram X | via Cortana"; both notifications are displayed in Notification center on PC, one under "Unigram X", and another under "Mobile device". Mobile displays one toast without avatar from "Unigram X"; this single notification is displayed in Notification center on Mobile, under "Unigram X".

There were no other Unigram sessions active on my account during that testing.

**Comment by penartur** [comment]
Overall, it looks as if `RemoteId` was ignored at all.

It could be caused by some incompatible `RemoteId` value (could Windows e.g. ignore `RemoteId` if it's too long? One could only guess; there is no any hint of such limitation in API docs).

Another possible reason is that it does not work with `ToastNotification` (although `RemoteId` is mentioned in API docs for `ToastNotification`). MS article on Universal Dismiss (mentioned there by @Silic0nS0ldier) gives an example of `RemoteId` for `ScheduledToastNotification`. Could it be that Universal Dismiss only works with scheduled notifications? Again, who knows.

**Comment by penartur** [comment]
And here is another thing I've noticed: https://github.com/UnigramDev/Unigram/blob/523c570cc811ee4535763aef6c93d1e8e231bcb0/Unigram/Unigram.Native.Tasks/NotificationTask.cpp#L683

Compare with API docs: https://docs.microsoft.com/en-us/uwp/api/windows.ui.notifications.toastnotificationmanager#Windows_UI_Notifications_ToastNotificationManager_CreateToastNotifier_System_String_

> public static ToastNotifier CreateToastNotifier(String applicationId)
> Parameters
> applicationId String The unique ID of the app.
> ...
> Remarks
> The app identified by applicationId must belong to the same package as the caller.

`"App"` string does not look like unique system-wide application ID.

Also, there is another article on notifications mirroring: https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/notification-mirroring ; if it is to be trusted, Unigram notifications from the phone should not have reached my PC at all, provided that PC and mobile app have "__either the same display name or the same PFN (Package Family Name)__". Is that the case?
Article also mentions workaround for that broken PC<->Mobile synchronization; one could simply disable notification mirroring for Unigram on Mobile. I'm going to try it now...

**Comment by FrayxRulez** [comment]
Package family name isn’t something arbitrary, and if you set a wrong value there the notification won’t show up at all. 

Specifying the entry point (`App`) is necessary because notifications task is executed in a separate process, that’s actually a window-less app without a name nor entry in the apps list. 
If I omit `App` you’ll get the notification from that secondary app, and I won’t be able to handle notifications history from the main app (nor I won’t be able to update main app tile from the background task)

**Comment by penartur** [comment]
So I think I have figured it out.

Universal Dismiss and Notification Mirroring are two very different features. (It could well be that Universal Dismiss works; unfortunately, I'm unable to test it because Telegram temporary banned my login attempts because there were too many during all these experiments with sessions).

### Duplicate notifications between PC and Mobile

Notifications from Unigram on Mobile should not appear on PC regardless of all that `RemoteId` stuff; Windows should mute these simply because there is Unigram on PC and it displays some toasts (any toasts). It does not work, either because there is a bug in Windows / UWP / Cortana (doubtful), or because some of the conditions listed on https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/notification-mirroring were violated.

### Duplicate notifications between push and in-app

In-app notifications will always be displayed along with push notifications, creating duplicate toasts/notifications, regardless of `RemoteId`. There is no way to update old notification; one could only remove it - so new (in-app) notification is always displayed in notification center in addition to the old (push) one.

So there is just an UX question of what should be done with this. One option is to remove all pending notifications when the app is opened. Another is to cache static `HashSet` of `RemoteId`s of all displayed notifications, and ignore any notification having `RemoteId` that was added to `HashSet` before (so that for every message, notification will only be displayed once). Or maybe there are other options; or some combinations of these could be used.

**Comment by penartur** [comment]
I've just checked, and Universal Dismiss indeed does work. Dismissing in-app notification on PC dismisses push notification on Mobile, and vice versa.

So the only problems remaining are the ones outlined in my previous comment.

**Comment by FrayxRulez** [comment]
> So there is just an UX question of what should be done with this. 

Windows should replace automatically notifications with the same `Group` and `Tag`. That's what `Group` and `Tag` are for: to make a notification unique.

**Comment by FrayxRulez** [comment]
> One option is to remove all pending notifications when the app is opened. Another is to cache static HashSet of RemoteIds of all displayed notifications

Not really, since the notifications process is just executed when a notification is actually received and it dies after that.
And obviously saving a list of notifications ids on disk just doesn't make any sense.

**Comment by Silic0nS0ldier** [comment]
Each group presumably has a tag that can be reliably regenerated. If that's the case, it should just be a matter of using `Windows.UI.Notifications.ToastNotificationHistory.RemoveGroup(groupTag);` when a chat has is unread status changed. Sure, there will be cases where there are notifications to clear, but it should work reliably.

Regarding the duplicates from device notification mirroring, it could be a race condition. If the app on another device (like PC) doesn't send a notification when the other device has, the notification will get forwarded. Its supposed to address an Edge case where the app hasn't been launched yet, but I think that Edge case needs another check if its the case. I'm not sure how `RemoteId` and the notification tags play into this.

**Comment by FrayxRulez** [comment]
So there was actually a bug in the code that generates the `Tag` in the in-app `NotificationService`, this has been now fixed (I can't remember if it is fixed already in the store version or not), so I'm closing this.
Feel free to open this ticket again if you'll still have this problem after next app update 👍
