### ISSUE TITLE
[UX] Keyboard navigation / scrolling is broken on PC

### ISSUE THREAD

**Issue by penartur** [UnigramDev/Unigram#548]
Some examples:

- [ ] 1. Click on any chat in chat list; press PgUp/PgDn. It should scroll the chat window; but instead, the focus seems to remain on chat list, and these keys scroll the chat list.
- [ ] 2. Click on the chat window (to switch the focus there). Press Up/Down. It should scroll the chat window; instead it moves through messages, one message at the time. If you had some long message selected, pressing Up moves you to the previous message, which could be several screens before.
- [ ] 3. Click on the chat window and press PgUp/PgDn. It should scroll the chat window one screen at the time; instead it moves through messages as in (2), except that it selects a message which is at least 1 screen away from the current position.
- [ ] (2) and (3) is also applicable to the Instant View, except that it is linked to paragraphs there instead of messages. That is, pressing Up/Down moves you to the previous/next paragraph (regardless of their length - even if they don't fit in a single screen), instead of moving you X lines up/down.

I believe that (1) could be fixed by setting a focus to the chat window upon opening the chat; and (2), (3), (4) could be fixed by setting some flag of the chat / instant view window controls. However, I don't really have any knowledge about UWP UI.

**Comment by FrayxRulez** [comment]
Well, actually this is how focus and scrolling works in Windows and UWP apps theirself (and it is fully handled by the system).
There isn’t any flag to set, just to write a lot of code to make it work as you suggested. 

I’m keeping this open for now, but it is obviously low priority.

**Comment by penartur** [comment]
> Well, actually this is how focus and scrolling works in Windows and UWP apps theirself

I've just checked other UWP apps, and here are the few examples:

1) Scrolling in Photos list works just as in Unigram; it is not a problem there because all photo elements are of the same height there.
2) Scrolling in Mail messages list works just as in Unigram (and it's not a problem there too for the same reason). Focus does not work there, too; however, pressing Enter on some specific message does switch the focus to the message window.
3) Scrolling in Mail message works as expected, scrolling X lines / 1 screen at the time.
4) Scrolling in Edge (OK, it's not fair) works as expected.
5) Scrolling in MSN News specific story works as expected.
6) Scrolling in Twitter feed is broken too, which makes it unusable on miceless PCs (such as laptops). Thankfully, I'm only using Twitter from browser on my PC.

I don't understand how MSN News story / Mail message is any diferent from Unigram Instant View. It should definitely work there.

And the problem with chat window (messages list) is probably that it tries to be two things at once - both a long page that is supposed to be read sequentially, and a list of objects that could be selected? It probably warrants some feature request to the UWP team (as it affects Unigram / Twitter and other similar apps with feeds of non-uniform elements); however, I don't know the specific components used, and cannot write such a feature request. Probably some other UWP developer glancing around could in their free time? (tag: help wanted)

**Comment by penartur** [comment]
An important addition: the scrolling just worked fine in one of the chats. Just after I've clicked on a specific message, it ceased to work correctly.

It seems that there are three possible states:

1) Focus is on the specific chat in chats list;
2) Focus is on the chat window;
3) Focus is on the specific chat message.
4) (and, probably, focus on the chats list, but not on the specific chat)

In the first state, keyboard scrolling scrolls through chats in chat list. In the third state, it scrolls through messages in chat window (the behavior described above as broken). In the second state, it scrolls through chat window just as it is supposed to (i.e. Up/Down scroll X lines up/down; PgUp/PgDn scroll to previous / next screen).

The problem is that it is tricky to get into the second state. What I've found out so far:

1) Clicking on the chat area is interpreted as a click on the message under the pointer, and so will switch navigation to the third mode.
2) Opening channel from the chats list is interpreted as a click on the channel under the pointer, and so will switch navigation to the first mode.
3) Opening chat from the chats list will set a focus on the message text input box (custom Unigram logic?), and will switch navigation to some second mode hybrid: PgUp/PgDn/Down are handled correctly until user enters into the message composing mode, which is invoked by typing any text or pressing Up.

So it seems that problems 1 through 3 in my original bug report could be solved after all, by performing the following changes:
1) Do not intercept Up key presses when in chat;
2) For channels, set focus to the chat window (not specific chat message) in manner similar to how it is set in chats;
3) (not sure if possible in UWP) Make messages non-focusable, so that click on the message will set the focus to the chat window instead of specific message. There is no reason for messages to be focusable anyway. The same stands for Instant View; paragraphs should not be focusable there.

**Comment by FrayxRulez** [comment]
Messages need to be focusable to allow you to click their content

**Comment by penartur** [comment]
> Messages need to be focusable to allow you to click their content

What clicking do you have in mind? I've just checked, and clicking on hyperlink in message does not switch me out of mode 2 to mode 3; scrolling continues to work correctly.

**Comment by Tirraon** [comment]
@FrayxRulez I didn't look, how did you implement messages list, but (2) and (3) can be fixed with ListView.PreviewKeyDown event. Just handle Up/Down/PgUp/PgDown keys manually with ScrollViewer.ChangeView(/**/). And set KeyRoutedEventArgs.Handled to true, that system handling will be ignored.
But it can work only with Fall Creators Update+. 
Another way - using Dispatcher.AcceleratorKeyActivated, but it is kind of pain.

```c#
private void ItemsList_Loaded(object sender, RoutedEventArgs e)
{
    if (ApiInformation.IsEventPresent(typeof(UIElement).FullName, nameof(UIElement.PreviewKeyDown)))
        ((UIElement)sender).PreviewKeyDown += PreviewKeyDown;
}

private void PreviewKeyDown(object sender, KeyRoutedEventArgs e)
{
    if (e.Key != VirtualKey.PageDown
        && e.Key != VirtualKey.PageUp)
        return;

    var scroll = ((FrameworkElement)sender).FindVisualChildren<ScrollViewer>().FirstOrDefault();
    if (scroll == null)
        return;

    var vOffset = scroll.VerticalOffset;

    if (e.Key == VirtualKey.PageDown)
        vOffset += scroll.ViewportHeight;
    else if (e.Key == VirtualKey.PageUp)
        vOffset -= scroll.ViewportHeight;

    scroll.ChangeView(null, vOffset, null, false);
    e.Handled = true;
}
```

**Comment by FrayxRulez** [comment]
It is probably better to use automation peers to scroll the list

**Comment by Tirraon** [comment]
Another problem:
If some users want Up/Down for scrolling, another users (including me) want to move focus with ability to open ContextMenu.
No problem with PgDown/PgUp, I think.

> It is probably better to use automation peers to scroll the list
Probably, I have never used it.

**Comment by FrayxRulez** [comment]
Context menu requests are handled by the system through `ContextRequested` event, so if there is any keyboard shortcut it supports it already.

**Comment by Tirraon** [comment]
There are ["Shift+F10, Menu button"](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/collection-commanding#creating-context-menus)
But UWP-devs should to implement it manually, as I understand.

**Comment by Tirraon** [comment]
I have tried to implement it in my project and fount, that Shift+F10 and Menu button work fine, but only when ContextFlyout is setted to GridViewItem (ListViewItem), not inside of ItemTemplate.

**Comment by xperiandri** [comment]
> Messages need to be focusable to allow you to click their content

#551

**Comment by ArianMozafari** [comment]
It would be great to cycle through chats using ctrl + tab and ctrl + shift + tab shortcuts, just like web browsers and TDesktop.

**Comment by xperiandri** [comment]
`Ctrl+PgUp` and `Ctrl+PgDown` look more relevant

**Comment by FrayxRulez** [comment]
So I'm closing this as ListView must scroll by blocks as this is the only way for visually impaired people to read messages.
