### ISSUE TITLE
Do not count unread messages from groups and channels on tile and lock screen badges

### ISSUE THREAD

**Issue by xperiandri** [UnigramDev/Unigram#550]
Ability to disable:
1. Counting unread messages in channels
2. Counting unread messages in groups

They are useless on badge. You will probably never get them all read.

**Comment by FrayxRulez** [comment]
Lockscreen counter is updated by telegram servers, and I have no control over it.

**Comment by xperiandri** [comment]
Do you know where can I post an issue to add such setting on their side?
