### ISSUE TITLE
Application key does not invoke context menu on message but removes focus

### ISSUE THREAD

**Issue by xperiandri** [UnigramDev/Unigram#551]
Application keyboard key must work the same as mouse right click.
However when you focused any message in chat and press Application key it does not invoke context menu but focus is being removed from message.

**Comment by FrayxRulez** [comment]
What's application key?

**Comment by FrayxRulez** [comment]
Wow, this is really complex to do. Way too much.

**Comment by alighamari** [comment]
@DarthJahus it remove keyboard focus (it's a white border)

**Comment by FrayxRulez** [comment]
Done, at least in messages list, will see if to implement it in the rest of the app in the future (it actually require a lot of work to for every place)

**Comment by alighamari** [comment]
i think this is fixed
