### ISSUE TITLE
Windows Server 2016 support

### ISSUE THREAD

**Issue by euglv** [UnigramDev/Unigram#553]
Is Windows Server 2016 supported? 
It have almost the same API as Windows 10, except Microsoft Store and some other small things.
Is it possible to build stand-alone version without Microsoft Store support? Are there any conditional defines for this? 
May be you have standalone builds somewhere for download?

**Comment by FrayxRulez** [comment]
The app should be compatible with Server.
The problem about out-of-store distribution is code signing: to be able to install the appxbundle you would need to manually install a self signed certificate, or I'd need to buy a certificate from a trusted authority (and they quite cost).

Anyway, you can get a self signed appxbundle from Releases tab here on GitHub, but it is somehow outdate (given the fact that compiling takes quite a lot of time and I have to build it two times to be able to distribute it on both store and here. Also given the small amount of people that are probably looking for the app outside the store)
