### ISSUE TITLE
GIFs are not repeated seamlessly

### ISSUE THREAD

**Issue by OneCrazyRussian** [UnigramDev/Unigram#555]
There's a noticeable stutter when Unigram repeats a GIF loop, here are examples of the same GIF being played in Telegram for Android and Unigram

https://i.imgur.com/MpjXO4A.mp4 - Telegram for Android
https://i.imgur.com/xbhP4Lp.gifv - Unigram

**Comment by FrayxRulez** [comment]
GIFs playback is provided by Windows itself using `MediaPlayer` class.

**Comment by OneCrazyRussian** [comment]
Is this a wontfix? MediaPlayer can be manipulated and set up to play the files seamlessly, as seen in 
https://social.msdn.microsoft.com/Forums/vstudio/en-US/7271f51c-d8d0-401a-ad55-fb57ff475182/seamless-looping-of-video-in-wpf?forum=wpf
Moreover there are some alternatives to be explored, like Xamarin MediaManager or WPFMediaToolkit

**Comment by FrayxRulez** [comment]
App isn’t WPF

**Comment by OneCrazyRussian** [comment]
It seems like you are reading half of the comment and neglecting the other half, mkay

Xamarin MediaManager is an UWP library though, and you can still look at WPFMT's code and use Win32 and COM for Universal Windows Platform (UWP) apps (multimedia) API's to make improvements 
https://msdn.microsoft.com/en-us/library/windows/apps/mt592899.aspx?f=255&MSPPError=-2147217396

**Comment by FrayxRulez** [comment]
Using MF isn't truly a good idea: we'd have to reinvent warm water to do exactly what `MediaPlayer` does under the hoods.
`Xamarin MediaManager` isn't a good idea as well, since under the hoods it uses `MediaPlayer` (or worse, `MediaElement`) that under the hoods uses MF.

**Comment by Tirraon** [comment]
Unigram Target MinVersion is 10.0.14393.0, so it is possible to use [animated BitmapImage](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.imaging.bitmapimage#animated-images) without MediaPlayer. But it is not guarantee to fix this issue, it can be problem on UWP side.

**Comment by FrayxRulez** [comment]
GIFs are .mp4 files.

**Comment by Tirraon** [comment]
@FrayxRulez oh, I got it
