### ISSUE TITLE
Click Drag/Long Click to select multiple messages to forward/delete/copy

### ISSUE THREAD

**Issue by ScottRFrost** [UnigramDev/Unigram#560]
The right click > select method is not very discoverable / usable.  Would it be possible to make click / drag (lasso select) work for selecting multiple messages to forward / delete / copy?  If now, how about adding long clicking on a message putting you into select mode, please.

**Comment by FrayxRulez** [comment]
Uwp doesn’t support “holding” using mouse. 
Lasso selection would be probably cool, but I don’t know how to implement it.

**Comment by ScottRFrost** [comment]
In [GestureRecognizer Events](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Input.GestureRecognizer#Events) , it looks like you have to specify HoldWithMouse in [Windows.UI.Input.GestureSettings](https://docs.microsoft.com/en-us/uwp/api/windows.ui.input.gesturesettings) , but I've never used UWP before so I'm not sure if it will work in the case of Unigram.

**Comment by FrayxRulez** [comment]
I’m not a fan of GestureRecognizer 😅 also we have holding with touch already there, and it would interfere

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/6b1d018d6d59dafb7f5222fe8c7b8800c492f952
