### ISSUE TITLE
In compact mode, you lose the ability to search chats

### ISSUE THREAD

**Issue by ScottRFrost** [UnigramDev/Unigram#561]
When the UI is in compact mode, the magnifying glass is missing and there doesn't appear to be a way to search chats without it.  If you have no chat currently open, perhaps typing a few characters can begin a search.  For example you type "Ste" and it finds your contact named "Steve".

**Comment by dmnmsc** [comment]
Expanding the bar using ctrl+e or ctrl+F when no chat is load could do the trick. Same as settings, calls or contacts do.

**Comment by MarcAnt01** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/414163ac4b951b64ad2c04bd14984cf789274a87
