### ISSUE TITLE
Unable to view photos and videos in 1.2.1562 (Mobile)

### ISSUE THREAD

**Issue by topkecleon** [UnigramDev/Unigram#562]
Hi, I'm running Unigram X 1.2.1562 on 1703 on a Lumia 640. 

Since the new update, tapping on a photo will display the animation (enlarging to the size of the screen) but then turn black, leaving me on the screen to view a photo but without one. Swiping in any direction does nothing.

Tapping on a video enters the video screen, but the video is also black. However, I can swipe left/right to the next photo or video.  If it is a photo, the image loads but I cannot zoom or swipe. If it is a video, the thumbnail loads and it will play normally, and I am again able to swipe to the next photo/video, but swiping to the video I originally opened does not let me view it.

Regardless of which photo or video I tap, the information shown for the sender, date, etc is always for the latest image posted in the group. (see screenshot below)

I can view and zoom photos sent as files.

I did not encounter this issue on desktop.

Screenshot of the black photo view:
![Blank photo view](https://user-images.githubusercontent.com/13046303/37437703-1c74c2f8-27c5-11e8-880a-4017254683a9.png)

Thanks for all your hard work!

**Comment by miladxandi** [comment]
@topkecleon 👍🏼

**Comment by madriani** [comment]
I have Unigram X 1.2.1562 and a Lumia 950 on 1709, and I noticed the same problems with the last update.

**Comment by ArionWT** [comment]
Have same issue on Lumia 640.

**Comment by smdkhossain** [comment]
I'm also facing this problem in last update with Lumia 40XL. Dev said that he will try to recover this bug, so stay connected and try to update when release a new version.

**Comment by topkecleon** [comment]
Thanks, looking forward to this hitting the store.
