### ISSUE TITLE
Zoom images with Ctrl++, -, 0, "/"

### ISSUE THREAD

**Issue by xperiandri** [UnigramDev/Unigram#563]
Ctrl++ - +10%
Ctrl+- - -10%
Ctrl+0 - reset to 100%
Ctrl+/ - reset to fit screen

**Comment by FrayxRulez** [comment]
Zoom broken photos viewer on mobile, because testers haven’t been able to do their job. 

I’ll just remove this feature some day, so I’m closing this.

**Comment by xperiandri** [comment]
Why? It works perfectly fine I tested both on Surface Pro and on Lumia

Do you mean that I can't swipe them left and right?

**Comment by FrayxRulez** [comment]
That. 
And also photos appear black on some devices.

**Comment by xperiandri** [comment]
So why not leave it open.
I'd like to implement this.
If someone has such a hardly reproducible issue let him debug it on his device.

**Comment by FrayxRulez** [comment]
Because there’s no way to fix the swipe issue

**Comment by xperiandri** [comment]
But it works in Pictures app
They just determine 2 states:
1. 100% (or fit) scale - you can swipe
2. other scale factor - pinch to zoom

**Comment by xperiandri** [comment]
That is all, just when you zoom out you can't zoom out less than fit scale or 100%. On that scale swipe is enabled

**Comment by FrayxRulez** [comment]
I’m not talking about the scaling, but about zooming itself. 
I’m going to fully remove zoom functionality.

**Comment by xperiandri** [comment]
Why will you do that I still haven't got

**Comment by FrayxRulez** [comment]
https://github.com/UnigramDev/Unigram/issues/563#comment-373441847

**Comment by xperiandri** [comment]
I don't understand this phrase

> Zoom broken photos viewer on mobile, because testers haven’t been able to do their job.

**Comment by FrayxRulez** [comment]
If you open a photo on mobile you’ll get a black screen (and this might be fixable). 
If you open a photo on a big touch screen you can’t scroll through the gallery by swiping left and right (and this isn’t fixable)

**Comment by xperiandri** [comment]
> If you open a photo on a big touch screen you can’t scroll through the gallery by swiping left and right (and this isn’t fixable)

It is fixable. Let me fix that

**Comment by FrayxRulez** [comment]
It isn’t fixable, because `ScrollViewer`captures any kind of manipulation event.

**Comment by xperiandri** [comment]
Tell me which file I will fix that.
It is just a matter of enabling and disabling some manipulations.

**Comment by FrayxRulez** [comment]
Thank you, but you can’t change `ManipulationMode` to `ScrollViewer`, or it would simply stop working 😊

https://github.com/UnigramDev/Unigram/blob/develop/Unigram/Unigram/Controls/GalleryContent.xaml

**Comment by DarthJahus** [comment]
@xperiandri I don't understand how testers didn't do their job, here. The version which included this feature wasn't available as appx for testers, was it? I may be wrong, but I personally got it from the Store.

**Comment by FrayxRulez** [comment]
By testers I simply mean some friends with a touch screen (since I don’t have any)
