### ISSUE TITLE
Compact mode activates on mobile

### ISSUE THREAD

**Issue by ariel-** [UnigramDev/Unigram#565]
Per issue description, compact mode is triggered after switching (either by hamburguer menu or by swiping right) to the contacts screen, when returning to chats you'll find compact mode enabled and there is no way to disable it without force exiting the app (hold back button and swipe the task down) and starting it again

**Comment by FrayxRulez** [comment]
Compact mode is triggered by window size and I don’t see why it should work on mobile, expecially if you don’t use suggested screen scaling

**Comment by ariel-** [comment]
> I don’t see why it should work on mobile

But it is. Lumia 640 XL, Unigram X 1.2.1562.
To add to the report, it happens whenever you switch from the 'Chats' to any other tab (ie Contacts,Calls,Settings) and back

**Comment by FrayxRulez** [comment]
Sorry, I meant “why it wouldn’t work”.

**Comment by ariel-** [comment]
Ah. but how does one prevent/disable it?

**Comment by FrayxRulez** [comment]
Probably using a screen scaling more appropriate for a smartphone

**Comment by ariel-** [comment]
Could an option be added to change between auto compact mode and disable? I like my screen scaling as it is
