### ISSUE TITLE
Ctrl+Tab and Ctrl+Shift+Tab shortcut keys for moving between chats

### ISSUE THREAD

**Issue by MahdiGhiasi** [UnigramDev/Unigram#566]
This is a shortcut key on Telegram Desktop. It would be nice to have it on Unigram too.

**Comment by DarthJahus** [comment]
@MahdiGhiasi Unigram has different shortcuts. Use ALT+UP and ALT+DOWN to switch between chats. CTRL+PAGE_UP and CTRL+PAGE_DOWN work too.

**Comment by MahdiGhiasi** [comment]
@DarthJahus Oh, didn't know that. Thanks 🙂
