### ISSUE TITLE
Typing on chat page should start typing on the "Message" box even when not in focus

### ISSUE THREAD

**Issue by MahdiGhiasi** [UnigramDev/Unigram#567]
When you click on a bubble or something, but are still in the chat screen (and not selected any text), it would be nice if starting to type automatically sets the focus to the _Message_ box and starts to type there, as Telegram Desktop does.

**Comment by penartur** [comment]
@MahdiGhiasi Probably related to Unigram#548

**Comment by penartur** [comment]
@MahdiGhiasi Probably related to #548
