### ISSUE TITLE
My People Notification Count

### ISSUE THREAD

**Issue by joshuader6** [UnigramDev/Unigram#569]
I'm on Win 10 Slow Ring 
Version: 1803
Build: 17120.1
Unigram is on version: X 1.2.1562

I'm getting notifications as usual. And the Unigram Taskbar icon shows the Badge with the correct unread count. 
But on the Contacts, i've pinned with My People there is no such badge. 
For Email this works but not for Unigram.

**Comment by DarthJahus** [comment]
That and linking notifications to contacts haven't been implemented yet.

**Comment by FrayxRulez** [comment]
This isn't really supported by UWP.
As stated [here](https://docs.microsoft.com/en-us/windows/uwp/contacts-and-calendar/my-people-notifications#falling-back-to-toast) toast notifications are just a fallback when `hint-people` attribute is set.

This means that you'd get the counter to increase, but you won't see any popup.

**Comment by joshuader6** [comment]
But isn't that the whole Purpose of myPeople ? So you can see if an important person sent you anything at one glance? 
Why bothering for the my people integration if it lacks one of the most important features?

**Comment by joshuader6** [comment]
Well, it would help to see if an important Person messaged me. 
It wouldn't necessarily need to be a counter. Just a "Hey this contact has sent you a conversation".
If that doesn't work why would I need my People in the first place? 

It works very well for Mail and Skype.

**Comment by FrayxRulez** [comment]
_You_ don't care about notifications. All the other users do.
The app used `hint-people` attribute initially, and I received so many reports about notifications not working as expected that I had to remove that.

**Comment by joshuader6** [comment]
Well, that sounds like a serious case of shitty implementation by MS. 
I'm sadly not very familiar with UWP Programming but why is MS able to implement it into Mail and Skype for example and 3rd party devs can't have Notifications and MyPeople Badges?
No wonder nobody uses MyPeople.

**Comment by joshuader6** [comment]
So if i am understanding `hint-people` from the MS Doc properly, then if you use `hint-people` there will only be a MyPeople notification + the badge and no normal Toast? 
Wouldn't it be possible to make the behavior configurable? 
So that users can decide if they always want toasts or if they want MyPeople to behave differently.

**Comment by FrayxRulez** [comment]
No, sorry, I'm against having tons of (confusing) settings in the app.
Skype and Mail behave exactly the same as any other app:
Contact badge is updated, but the notification is muted and appears in the notification center silently.

**Comment by joshuader6** [comment]
Mh okay. 
At least I do now understand why no one else is implementing MyPeople support in their apps. 

And yes I totally agree, that such a setting wouldn't be at the right place in Unigram. 
The option to force Toasts should be in MyPeople itself. 

But on the other hand, I don't really understand why People would complain about not receiving notifications when they have MyPeople activated. The MS Documentation states, that there is a Fallback when a contact isn't pinned or the MyPeople notification somehow fails to display. 
But well I guess we'll have to wait for MS to somehow make MyPeople usable. (At least for what I know Unigram is the only 3rd party app that supports it ATM)

**Comment by joshuader6** [comment]
I've suggested an idea in on:
[wpdev.uservoice.com](https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/33681253-my-people-notification-badge-vs-my-people-notifica).

**Comment by Phenome** [comment]
Can we maybe revisit this? Maybe something has changed on the Windows side.
In My People settings, there is a "Show notifications from My People" (not sure if that's the exact translation).
So I assume if Unigram used the `hint-people` attribute, we'd (also) get a notification? So it's up to Windows settings, and as so, would not clutter the settings in the app.

I just reinstalled Unigram and this was a killer feature for me. Precisely this:
> This means that you'd get the counter to increase, but you won't see any popup.

But for other people, they could just enable that setting on Windows taskbar settings.
Apparently I'm in the minority, if you've received so many reports :|
I'd really love this option, though. 🙏
