### ISSUE TITLE
Unable to create a new group

### ISSUE THREAD

**Issue by penartur** [UnigramDev/Unigram#570]
Unigram version: 1.2.1562.

Steps to reproduce:
1. Hamburger button, New group.
2. Enter "test" as the group name, press the green check mark ("next").
3. List is empty (_should it be empty? It's prepopulated with all contacts in TDesktop_); enter any search term, select some users.

Expected result: number of users above the search area goes from "0/100000" to "N/100000"; green check mark ("next") becomes active; on pressing that check mark, new group is created.

Actual result: number of users above the search area remains at "0/100000"; green check mark ("next") remains disabled; user cannot press it and cannot complete creation of the new group.

![image](https://user-images.githubusercontent.com/1332951/37610650-3838447a-2bb1-11e8-939d-f5c41d298e1a.png)

**Comment by bugada** [comment]
Yes also on mobile

**Comment by larsschellhas** [comment]
This issue is three month old and a pretty big deal breaker.
Would be nice to see some movements on this 😄

**Comment by larsschellhas** [comment]
I would recommend that every contact who is checked after you have searched for it, should stay checked on top of the search list or at least in the search list, when the search phrase is changed or deleted.

**Comment by FrayxRulez** [comment]
Yeah that’s actually the hard part

**Comment by larsschellhas** [comment]
I can imagine that... Would it be possible to have two lists on top of each other?
I you check someone on the lower list (global search) he gets added to the List of selected people?
And unchecking him in the top or bottom list would erase him from the List of selected people?

**Comment by FrayxRulez** [comment]
Fixxxxed

**Comment by HAsadian** [comment]
@FrayxRulez I can't create a public group (with custom id)

**Comment by FrayxRulez** [comment]
> @FrayxRulez I can't create a public group (with custom id)

@HAsadian you have to create the group, convert it to supergroup, and then you can assign an username, as it happens in official apps

**Comment by HAsadian** [comment]
@FrayxRulez I'm so sorry. I can't create publice channel (with custom username)
