### ISSUE TITLE
Group converted in supergroup looses history

### ISSUE THREAD

**Issue by bugada** [UnigramDev/Unigram#571]
If you convert a group in a supergroup you loose the group history: telegram on Android or ios shows history.
Then if the group is pinned, it goes on top (in telegram android or ios the position is unchanged).

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/dc57ad542f41af7c502dd2c8a8084edac614eab9

**Comment by morenj96** [comment]
@FrayxRulez 😍😍🙌
