### ISSUE TITLE
Inline keyboard response support

### ISSUE THREAD

**Issue by bugada** [UnigramDev/Unigram#572]
Please add support for the response layer for inline keyboard.

**Comment by FrayxRulez** [comment]
What's this?

**Comment by bugada** [comment]
Oh Fela I'm very  sorry, I hardly remembered the meening of this ugly message.

Btw, in all telegram clients when you  interact with a bot inline keyboard, the bot can answer something to you, and that message is displayed as layer on center or top of the screen. See this example in TDesktop.

![test4](https://user-images.githubusercontent.com/4438193/45509526-17fa6d00-b798-11e8-83fc-52eed3fcb2e5.gif)

This feature was present in the old Unigram but not after Unigram X.
Thank you

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/86b3603e8cab6ebee36de66cb323ddcf142d9b59
