### ISSUE TITLE
Unigram reliably crashes when trying to display/load certain messages

### ISSUE THREAD

**Issue by penartur** [UnigramDev/Unigram#575]
When I try to scroll into the certain part of the certain chat, Unigram crashes. It looks like that: any message more than, say, 900 messages ago is displayed fine, any message less than, say, 800 messages ago is displayed fine; anything in between results in Unigram crash, no matter if I scroll in there or if I enter the text of the message into search.

Here is the event description from Event Viewer:

```
Faulting application name: Unigram.exe, version: 1.0.0.0, time stamp: 0x5ab12369
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.16299.248, time stamp: 0xc27fa098
Exception code: 0xc000027b
Fault offset: 0x00000000006e80e9
Faulting process id: 0x1b38
Faulting application start time: 0x01d3c7a7cf7829c2
Faulting application path: C:\Program Files\WindowsApps\38833FF26BA1D.UnigramPreview_1.2.1569.0_x64__g9c9v27vpyspw\Unigram.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: d9bcd7b3-774e-41c2-b5ec-87893835c51b
Faulting package full name: 38833FF26BA1D.UnigramPreview_1.2.1569.0_x64__g9c9v27vpyspw
Faulting package-relative application ID: App
```

Let me know if I can provide some additional crash info somehow.

Unigram version: 1.2.1569

**Comment by FrayxRulez** [comment]
Sorry but the informations you provided are more than useless.
If this problem only occurs in a specific chat then you must provide an invite link to join it.

**Comment by penartur** [comment]
> Sorry but the informations you provided are more than useless.

Is there any way to get more debug info from the crash?

Unfortunately, I cannot provide the link to this secret chat.

**Comment by FrayxRulez** [comment]
Well, a secret chat isn’t a channel, to begin with. 
No, there’s no way

**Comment by penartur** [comment]
> Well, a secret chat isn’t a channel, to begin with.

Sorry, it was a mistype. Unigram crashed when scrolling through the secret chat.

It's sad if there is no way to get the underlying exception.

**Comment by penartur** [comment]
There is a way, after all. I've snatched a minidump from WER temp folder; where do I send it?

But what's more important, I've found a specific message that crashes Unigram. It's an ordinary message, it does not look weird, it was not crafted by someone malicious, but when I forward it to my "saved messages" using TDesktop, attempting to open "saved messages" in Unigram reliably crashes it. Should I send this message to you on Telegram, so that you could reproduce the problem?

**Comment by FrayxRulez** [comment]
Wonder if I should close this 👀

**Comment by FrayxRulez** [comment]
Closing this...
