### ISSUE TITLE
After re-enabling notifications, they don't pop-up anymore and no there are no sounds

### ISSUE THREAD

**Issue by notNSANE** [UnigramDev/Unigram#577]
Not sure what info I can add here but I re enabled notifications everywhere regarding Unigram X and nothing worked. 

I'm going to manually delete the app and cache from the protected Windows folders to see if it helps.

Using Win 10 x64 fully updated.

Edit: namely, the notifications DO reach the action center, but nothing ever pops up. I don't have this issue with other Win 10 apps such as Mail or Newsflow.

This is my config for it:

![xmwoy30](https://user-images.githubusercontent.com/7162375/38730786-48207786-3eee-11e8-93ff-fc91a64d3e25.png)

![hm2cx4u](https://user-images.githubusercontent.com/7162375/38732119-7c2b35f2-3ef3-11e8-8ed2-701b876a9cd2.png)

**Comment by FrayxRulez** [comment]
It was probably related to My People... Do you still have this problem?
