### ISSUE TITLE
Unigram website no more available

### ISSUE THREAD

**Issue by madriani** [UnigramDev/Unigram#578]
The Unigram website ( http://unigram.me ) seems to be expired on the 13th of April and has not been renewed.
Moreover, I see no commits on the project in the last few weeks.

Is the project still alive?

Thank you!

**Comment by ScottRFrost** [comment]
For other github users that aren't on the Telegram channel but are wondering, alireza replied on the Unigram Insiders Telegram channel:

> Updates are in hold because Dev needs to focus on real life. And this has been advised here several times. Unigram development will come back one day or another

**Comment by unauthorized-401** [comment]
+1, can't install from windows store

**Comment by ScottRFrost** [comment]
http://unigram.me seems to have been purchased by an expired domain camper.  I'd say this [along with adding ads](https://github.com/UnigramDev/Unigram/commit/5c6e6d968104d252386d8515d662e355bb94a094) is probably the end for our old friend Unigram.

Are there any other alternative clients for Windows?  Official Telegram desktop is still kind of iffy for me on playing notification noises.

**Comment by FrayxRulez** [comment]
I haven’t added any kind of ads.
Telegram is going to introduce a new kind of proxy servers, that will allow sponsored channels.
