### ISSUE TITLE
Replying doesn't always bring up the original message above the text box

### ISSUE THREAD

**Issue by ghost** [UnigramDev/Unigram#579]
Sometimes when attempting to reply, the indicator above the text box displaying the message being replied to doesn't appear. This is only on random occasions. When a message is typed and sent, the reply does send properly. The only issue is in that I cannot tell that I'm replying due to the indicator not appearing.

Additional Info:
Windows 10 **1803** (I actually only just updated yesterday, and the problem existed _before then_ in **1709**)

**Comment by MarcAnt01** [comment]
@FrayxRulez don't know if you've done something, but this behavior has stopped now

**Comment by FrayxRulez** [comment]
I'd leave this open
