### ISSUE TITLE
Unread message counter does not reset when entering a chat

### ISSUE THREAD

**Issue by MarcelBrusius** [UnigramDev/Unigram#58]
![photo_2016-10-25_17-29-27](https://cloud.githubusercontent.com/assets/22997398/19692679/13c184b8-9ad9-11e6-8e94-73bd0bee5b3d.jpg)

**Comment by ikarago** [comment]
Notifications for this chat also needs to be cleared upon opening the chat!

**Comment by marcel93b** [comment]
Counter is cleared if the corresponding chat is open and a new messages arrives.

**Comment by larsschellhas** [comment]
Counter is also cleared if the chat is open and one writes a message by himself. 
Still not reset by just opening the chat

**Comment by FrayxRulez** [comment]
duplicate #24
