### ISSUE TITLE
Streaming Audio and Video Support

### ISSUE THREAD

**Issue by omkarnathsingh** [UnigramDev/Unigram#580]
I am a new user of Unigram X. 
Feature request: Please add streaming capabilities to Unigram X. It will be a nice additions for users. Thanks.

**Comment by FrayxRulez** [comment]
TDLib doesn’t support this: https://github.com/tdlib/td/issues/161

**Comment by omkarnathsingh** [comment]
@FrayxRulez But Telegram X, based on tdlib has streaming audio support already!😊

**Comment by FrayxRulez** [comment]
That's a bit different, and I just linked you a TDLib feature request made by Telegram X developer, I cannot be clearer than that :P
