### ISSUE TITLE
Sample Wallpapers W10M

### ISSUE THREAD

**Issue by mautheus** [UnigramDev/Unigram#581]
App in W10M is not applying the sample wallpapers in the conversations. You select one of them but it is not displayed on the screen to be applied.
![wp_ss_20180609_0001](https://user-images.githubusercontent.com/40085049/41188270-3641365c-6b91-11e8-8fb0-108b0c349ba8.png)

**Comment by mautheus** [comment]
This problem keeps occurring on the phone

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/5ed7e19dfedebc6df82bd3c69170c88833fdd863

**Comment by mautheus** [comment]
@FrayxRulez Thanks for the hard work. 👏🏻
