### ISSUE TITLE
Lock password unavailable W10M

### ISSUE THREAD

**Issue by brunoarmonico** [UnigramDev/Unigram#583]
I have already tried to reinstall, but the option still unavailable.

PS
This option was available before, but now no more.
![wp_ss_20180614_0001](https://user-images.githubusercontent.com/22664781/41415710-90e2eb00-6fbf-11e8-9c95-57f4ff156291.png)

**Comment by mautheus** [comment]
@brunoarmonico @ferferga said that this feature has not yet been implemented
