### ISSUE TITLE
Notifications for current chat resent after latest app upgrade

### ISSUE THREAD

**Issue by bugada** [UnigramDev/Unigram#584]
On mobile, Lumia 950xl, if I interact with a bot, some of the last messages received are sent as notification after the phone is locked. 

I'm using Unigram X 1.3.1577. 
The previous version worked fine.

Thank you

**Comment by bugada** [comment]
Update: now with 1.6.1590 on Lumia 950xl every message received ina group, even if the group is stil opened, generates a notification.

Thank you

**Comment by FrayxRulez** [comment]
The first one is from the app, the second one is from telegram servers
