### ISSUE TITLE
Notifications for silent chats are delivered anyway

### ISSUE THREAD

**Issue by marcel93b** [UnigramDev/Unigram#59]
![photo_2016-10-25_17-51-50](https://cloud.githubusercontent.com/assets/22997398/19693488/0c9131fe-9adc-11e6-95f1-3444f33dd578.jpg)
![photo_2016-10-25_17-51-56](https://cloud.githubusercontent.com/assets/22997398/19693487/0c8a279c-9adc-11e6-9e1c-cba803619c96.jpg)

**Comment by FrayxRulez** [comment]
Notifications are always delivered if the message is replying to user message, like in this case.

![image](https://cloud.githubusercontent.com/assets/8152849/19693931/b19c0178-9add-11e6-8f92-2d6885a27fd4.png)
