### ISSUE TITLE
List of calls doesn´t show the contact´s profile picture and other improvements

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#590]
List of calls doesn´t show the contact´s profile picture and clicking doesn´t open the contact profile/chat.

**Comment by larsschellhas** [comment]
Since clicking does now open the chat with the regarding person, I´ll use this issue for the following suggestions to improve the calls list:

1) Show the profile picture of the calling/called person (still)
2) Don´t show the names of missed calls in red (it´s somehow ugly IMHO), but recolour the "missed call" and the regarding time in the system accent Color. That way they will be distinguishable from other calls, but fit better into Windows´ design. The telephone app handles it the same way.

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/6c16c112bbe56ca3384880f8525a43f570c6b2f5

**Comment by MarcAnt01** [comment]
I think also the red color applied to the "missed call" dialog and not to the person who called should be added
