### ISSUE TITLE
open the pictures-app-explorer-addin when sending a picture from the gallery on the PC

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#591]
When you want to upload a new group picture on the PC the opened explorer-window automatically shows not any folder but the Pictures-Application (see picture).

![image](https://user-images.githubusercontent.com/14281234/41623646-b7c1502e-7413-11e8-9f21-e1f2efc5e009.png)

Can this be the standard when trying to send a picture from the gallery?

![image](https://user-images.githubusercontent.com/14281234/41623719-e8b3b5b4-7413-11e8-974f-a2737367d7c3.png)

**Comment by FrayxRulez** [comment]
It simply uses the latest app you used to pic a file, afaik

**Comment by larsschellhas** [comment]
Yep, you´re right. Sorry for bringing this up then!
