### ISSUE TITLE
Pressing the down arrow in a chat does not go to most recent message

### ISSUE THREAD

**Issue by yamnakshatriya** [UnigramDev/Unigram#593]
Is this WAD? In conversations with thousands of replies, this means the user has to scroll through every single message to get to the most recent message. I expected the down arrow to go to most recent message.
![unigram](https://user-images.githubusercontent.com/34869135/41740881-57011948-7591-11e8-9466-3789acb6c4b3.png)

**Comment by FrayxRulez** [comment]
I'd say this is fixed
