### ISSUE TITLE
Videos in instant view articles won´t play

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#596]
Videos in instant view articles won´t play.

Also clicking on a video in an instant view article the first media is opened in Fullscreen.

**Comment by larsschellhas** [comment]
Also it would be better if videos in an instant view article would be streamed instead of downloaded permanently. Though I see that this is much more difficult to achieve.

**Comment by FrayxRulez** [comment]
Tdlib doesn't support streaming

**Comment by FrayxRulez** [comment]
Thix is fixed
