### ISSUE TITLE
App does not always start properly when opened via a notification

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#598]
Often when I open Unigram via a notification I get this screen:
![image](https://user-images.githubusercontent.com/14281234/42099379-8e4bc236-7bbd-11e8-8b56-0cb3cf21fc92.png)

Sadly I couldn´t manage to find the source yet. Sometimes it works, sometimes not.
Neither the Hamburger-Menu nor the search button are clickable.
I will further investigate this matter.

**Comment by FrayxRulez** [comment]
I've never been able to reproduce this issue on my device, so I wonder if this is still valid

**Comment by larsschellhas** [comment]
I was wondering, too. Let´s close it.
