### ISSUE TITLE
Different space between message bubbles in the same message group

### ISSUE THREAD

**Issue by Ujinjinjin** [UnigramDev/Unigram#600]
As you can see on the pictures below, there are different space between first-second bubbles (2px) and rest of them (3px). Kinda **hurts**

![picture 1](https://user-images.githubusercontent.com/20992866/42276388-510a295c-7f9c-11e8-8d6c-fb7c3da16d53.png)

![picture 2](https://user-images.githubusercontent.com/20992866/42276591-00cfc5fe-7f9d-11e8-8046-8e09221bf893.png)

**Comment by FrayxRulez** [comment]
Can't reproduce

**Comment by Ujinjinjin** [comment]
just send 3 or more messages in a row

**Comment by FrayxRulez** [comment]
Do you think I don't test the stuff I do before publishing it?

![immagine](https://user-images.githubusercontent.com/8152849/42277759-b54caea2-7f98-11e8-9857-c7ebd3aa1449.png)

**Comment by Ujinjinjin** [comment]
Yeah, that was stupid sorry. By the way, tested on 3 another laptops, and none of them had this issue, so it is something on my device. Sorry for disturbing

**Comment by FrayxRulez** [comment]
If you have some weird screen scaling (mobile device?) might be a rendering issue

**Comment by Ujinjinjin** [comment]
No, using laptop with 125% scale (recommended)

**Comment by Ujinjinjin** [comment]
Oh, yeah, that's it, changed on 100% and it works fine
