### ISSUE TITLE
"Launch Unigram when system starts" setting is completely ignored.

### ISSUE THREAD

**Issue by net-cat** [UnigramDev/Unigram#606]
I've disabled the "Launch Unigram when system starts" setting, yet when I reboot my machine, Unigram notifications still come pouring in.

This tells me that Unigram is still running in the background, which means it's still starting when the system starts.

**Comment by FrayxRulez** [comment]
Notifications are sent by Telegram servers as it happens on iOS and this doesn’t require the app to be running.
Also, UWP apps can’t stay active when you close them: once you press the red X they’re terminated, and there’s no way for the developer to prevent this or to start some always-active background service when this happens.

**Comment by net-cat** [comment]
So, the follow up question is "How do I silence notifications in Unigram?"

If I close the app, I don't want to keep getting notifications.

**Comment by net-cat** [comment]
Force stopping the app on Android definitely stop the notifications.

But okay. This battle isn't worth fighting.

**Comment by segin** [comment]
If and only if the application is using it's own push notification
solution. However, very few do this as it eats lots of battery life.

The majority of apps use Google Cloud Messaging that works akin to iOS and
Windows.
