### ISSUE TITLE
Conversations opened in new windows periodically duplicate last message

### ISSUE THREAD

**Issue by wizzard0** [UnigramDev/Unigram#607]
Repro: 1. Open convo in new window
2. Write 2-3 messages
3. Wait for 5 minutes
4. Observe last message is repeated as well with today's date. 
5. Gets repeated over and over every some minutes.

My guesstimate is that this happens when the list of recent conversations gets refreshed.

Version: Unigram X 1.7.1594, Windows 10 1803 (17134.165)

**Comment by alighamari** [comment]
an example of what happen

![image](https://user-images.githubusercontent.com/24440862/42685822-531ec2f2-86a9-11e8-8e7e-737d9a65fa9b.png)

**Comment by FrayxRulez** [comment]
I need repro steps...

**Comment by MarcAnt01** [comment]
Does that still happen?
