### ISSUE TITLE
[1.7.1594] Bug: Messages stay unread after you focus conversation opened in new window

### ISSUE THREAD

**Issue by wizzard0** [UnigramDev/Unigram#608]
Repro: 1. Open 2 conversations in new windows
2. Receive a message in unfocused one
3. Focus the window with new message
4. Observe the "unread" label isnt cleared.

Version: Unigram X 1.7.1594, Windows 10 1803 (17134.165)

**Comment by FrayxRulez** [comment]
Fixed
