### ISSUE TITLE
When opening chat in new window, chat list focus remains out of sync in original window

### ISSUE THREAD

**Issue by roman380** [UnigramDev/Unigram#615]
While the new window opens great as expected, original window keeps the selection on the clicked item, which corresponds to chat of new window. 

If original window showed different chat at click time, it keeps showing it regardless of changed selection. Chat list selection, I suppose, is expected to revert back so that original window UI stays consistent.

**Comment by MarcAnt01** [comment]
Does it still happen now?

**Comment by roman380** [comment]
Yes. Just updated to 2.1.1778 and the issue is here.

**Comment by roman380** [comment]
The problem still existed unless fixed just recently
