### ISSUE TITLE
Selecting multiline text in message (to be sent) control, Shift+Up might scroll the control with messages above

### ISSUE THREAD

**Issue by roman380** [UnigramDev/Unigram#617]
When you select multi-line text before sending, Shift+Up and Shift+Down work correctly going through lines of text. Once you reached the beginning of the text where selection long longer changes with key presses, further key presses scroll the upper control instead. This however does not happened with Shift+Down combination.

Update: similar happens without selection. Going up (Up key) when cursor is at the beginning of text scrolls messages. And going down does the same. Shift+Up, Shift+Down behavior is different.

**Comment by FrayxRulez** [comment]
Text selection and list scrolling are system features and consequently there's no way I can fix this behavior
