### ISSUE TITLE
Ability to set custom sounds for Unigram notifications on PC

### ISSUE THREAD

**Issue by malnabokor** [UnigramDev/Unigram#619]
Notification Sound is greyed out and it is "Default" and can not be changed. It would be great if it could be changed so it would not have to share the same sound as other general Windows notifications.

**Comment by HAsadian** [comment]
You can change notifications of unigram from windows settings
![wp_ss_20180913_0003](https://user-images.githubusercontent.com/39188028/45486752-7a8c4280-b771-11e8-998a-fd6a806b1d88.png)

**Comment by malnabokor** [comment]
I mean it on Windows 10 Desktop.

![image](https://user-images.githubusercontent.com/42355484/45504706-dc0cdb00-b78a-11e8-88f6-aa5d978502e2.png)

**Comment by TheFireRed** [comment]
Any news on this?

**Comment by FrayxRulez** [comment]
Not yet

**Comment by ransagy** [comment]
Not sure if this is exactly related; is this why "Sounds" is disabled/grayed out for anything in the Notification and Sounds settings page on desktop?

**Comment by piratetub** [comment]
Can we get any updates on this please? Just an acknowledgment from a dev would be enough.. :)

**Comment by joshms123** [comment]
i'd like an update on this too. this would be great! :)

**Comment by Ghorthalon** [comment]
I too would like to be able to set custom sounds for messages in Unigram.

**Comment by pitermach** [comment]
+1 from me. What makes this even more frustrating is that there's a bug in Windows currently that if you change the notification sound for the whole system in sound settings, it becomes completely silent so changing it there is not an option. So the only 2 options we currently have is default Windows sound or no sound for any notification which is a bit annoying. :)

**Comment by megapro17** [comment]
Haha updates goes brrr

**Comment by crashinz** [comment]
any update on this? i can't hear the notification sound when i'm in a game, be nice to turn it up 300% or something

**Comment by MarcAnt01** [comment]
Done in https://github.com/UnigramDev/Unigram/commit/3e22bacfbfd43f0d009323df30b5ff4c73a936e5
