### ISSUE TITLE
Live tile & notifications don't work properly 

### ISSUE THREAD

**Issue by MarcelBrusius** [UnigramDev/Unigram#62]
- the live tile doesn't work as expected (may be related to the "broken" unread messages counter)
- (multiple) notifications belonging to one chat don't vanish when one of those notifications is clicked
- some notifications arrive late (and persist) even when already opened

**Comment by Sc0tTyXL** [comment]
Same for quick status icon, but I assume that uses tile notification count

**Comment by ferferga** [comment]
Live tile should have the option to show the profile picture of the person/group you have unread messages as well.

**Comment by FrayxRulez** [comment]
Unread messages count is now updated in real time: https://github.com/UnigramDev/Unigram/commit/7a13b786090fdf9cb9b9549584b51a4e17dfb17e

**Comment by notuxius** [comment]
Is it possible to show unread messages counter in the taskbar when the app is closed but is pinned to the taskbar - like in Skype or Mail apps?

**Comment by MarcAnt01** [comment]
> Is it possible to show unread messages counter in the taskbar when the app is closed but is pinned to the taskbar - like in Skype or Mail apps?

It should be already shown if you haven't disabled push notifications (as I have done)
