### ISSUE TITLE
Ability to Copy Image from the Image Viewer

### ISSUE THREAD

**Issue by DarthJahus** [UnigramDev/Unigram#625]
**Actual behaviour:** When you browse images from Image Viewer and want to copy one of them, you need to press ••• then click on "Show in chat", and then right click the image in the conversation to copy it.

**Desired behaviour:** From the Image Viewer, right click the image or press ••• and you'd find "Copy Image" right there.

As always, thank you for your amazing work 😉

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/ddb0680a1c04d6dc8cb885669d05ee30f07cb27d
