### ISSUE TITLE
Select and copy phone from contact card

### ISSUE THREAD

**Issue by xperiandri** [UnigramDev/Unigram#627]
Please, add the ability to select and copy a phone number from the contact card
![image](https://user-images.githubusercontent.com/2365592/45088546-f9e69a00-b111-11e8-914f-314cc023ea15.png)

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/4b67ecb5f1c215f5045d589bc45af27f392b27d3

**Comment by xperiandri** [comment]
Thanks!
