### ISSUE TITLE
My People isn't loading, contacts sync is also broken

### ISSUE THREAD

**Issue by sukram230799** [UnigramDev/Unigram#628]
Windows Version 1809 Build 17744.1003 AMD64
Unigram Version 1.8.1607

Since the last version of Unigram the People Bar is not properly loading. Instead, the hamburger menu is shown (which can be opened). Even if Unigram is already opened the People Bar still won't load.

![peoplesbarunigram](https://user-images.githubusercontent.com/7346153/45212750-faa83900-b295-11e8-893b-9c4d4f54960b.png)

**Comment by domcote** [comment]
confirmed.

**Comment by FrayxRulez** [comment]
Resolved at https://github.com/UnigramDev/Unigram/commit/35b20cfdd60852459bae69fc8e76ec179f35d2ba
