### ISSUE TITLE
context menu of text is hidden

### ISSUE THREAD

**Issue by alighamari** [UnigramDev/Unigram#629]
Unigram version: 2.0.1608
Windows version: 1809
Windows build: 17751.1
Insider: true 

context menu over text had problem since Microsoft tried to make a new default context menu for textblock and textboxes 
but now in the latest build of Unigram right clicking on texts or links show no context menu and nothing happen

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/c32532a75ace993885a7204f085ab9da649ba793
