### ISSUE TITLE
no/slow internet connection => vanished chat history

### ISSUE THREAD

**Issue by MarcelBrusius** [UnigramDev/Unigram#63]
as far as I experienced this issue, it only occurs when the app is completely restarted and there's no (or just slow) internet connection available

**Comment by marcovr** [comment]
@marcel93b This isn't a bug, it's simply because IIRC there is no caching implemented yet. This means the chat data doesn't get saved and each time the app starts it has to get loaded (which obviously doesn't work without internet connection)
