### ISSUE TITLE
No context menu for messages on RS5 builds (system context menu is popped up)

### ISSUE THREAD

**Issue by DarthJahus** [UnigramDev/Unigram#631]
Right clicking message content shows system context menu with "Select all" only option, instead of triggering the application's context menu (reply, copy, forward, etc.).

Another effect is that you can't copy links by right-clicking them (system context menu still has "Select all" only).

![image](https://user-images.githubusercontent.com/7353366/45218148-75755200-b29e-11e8-83a5-da3346586f14.png)

**Affected builds:** RS5 (tested on 17728, 17751).

**Comment by domcote** [comment]
Confirmed on 17744.1003 as well.

**Comment by DarthJahus** [comment]
On 19H1 build 18234, it seems that Microsoft has tweaked that behaviour to stop showing the system's menu; now, the problem is that Unigram's context menu is still absent.

They may have done this because on Skype, right clicking the text used to show both context menues. Now, it shows Skype's built-in menu only. So… they "fixed" it for their app 😂

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/c32532a75ace993885a7204f085ab9da649ba793
