### ISSUE TITLE
title bar text doesn't show status of connection and always is Unigram

### ISSUE THREAD

**Issue by alighamari** [UnigramDev/Unigram#632]
title bar doesn't show connecting when there is no connection or its still trying to connect 
it should also show waiting for network 
![image](https://user-images.githubusercontent.com/24440862/45218932-75854a00-b2be-11e8-86bd-028a54e66761.png)

**Comment by FrayxRulez** [comment]
Resolved at https://github.com/UnigramDev/Unigram/commit/a776a956beb583a4073e083ad962bd559ce34334
