### ISSUE TITLE
Proxy page shortcut

### ISSUE THREAD

**Issue by M450ud** [UnigramDev/Unigram#633]
please add a shortcut in hamburger menu for quick access to proxy page.

**Comment by FrayxRulez** [comment]
I've added with https://github.com/UnigramDev/Unigram/commit/0cc53732bef4c2e15931243d9074e33f1f04234d a shortcut that will only appear if the app is having troubles while reaching Telegram servers ("Connecting...")

![immagine](https://user-images.githubusercontent.com/8152849/45237965-729b5100-b2e0-11e8-86f5-734eaa8ed658.png)
