### ISSUE TITLE
SECURITY: Domain serving malware

### ISSUE THREAD

**Issue by Zenexer** [UnigramDev/Unigram#634]
The description for this repo currently links to http://unigram.me/ which is actively serving malware.  Please remove all references to it.

**Comment by FrayxRulez** [comment]
Please do a pull request I’ll accept it

**Comment by Zenexer** [comment]
I can't do a pull request; it's in the description.

**Comment by Zenexer** [comment]
![image](https://user-images.githubusercontent.com/504130/45249617-34f2f400-b2f1-11e8-95e5-53098589e51e.png)

**Comment by FrayxRulez** [comment]
👌

**Comment by rabiet** [comment]
The same link is in the wiki footer and should be removed, too
