### ISSUE TITLE
Windows 10 Share function not working

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#636]
When selecting a file from apps that support Windows 10 Share function, like Photos or Desktop, I can see the possibility to share it though Unigram, but when it opens Unigram it does nothing

**Comment by FrayxRulez** [comment]
Duplicate of #440

**Comment by MarcAnt01** [comment]
Yep, right, but it mentions just photos, while the problem happens with every type of file

**Comment by FrayxRulez** [comment]
I'll refactor it to be more generic
