### ISSUE TITLE
There's no option to notify members when I pin a message in a group

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#637]
There's no option to do a silent pin or a pin with notification, I've seen that silent broadcast has just been implemented, is it possible to do the same with pinned messages?

**Comment by MarcAnt01** [comment]
I've done more tests and it seems to work in most cases, but sometimes it doesn't appear, but randomly I cannot understand what it is due to

**Comment by MarcAnt01** [comment]
@FrayxRulez I think it's better deleting this issue, I will create a new one when I understand the situation when it's not working properly

**Comment by FrayxRulez** [comment]
Marked as blocked as I need more info to proceed
