### ISSUE TITLE
Settings inactive and not saving

### ISSUE THREAD

**Issue by tofylion** [UnigramDev/Unigram#64]
None of the settings load and when I change the sync with people hub or enable location services, they don't save for the next time I open the app. Plus the app takes WAY TOO LONG TO LOAD UP.

**Comment by tofylion** [comment]
I really like how you added the reply from the notification. ☺

**Comment by kesavaprasadarul** [comment]
Hi, Thank you for the feedback. 
We haven't started working on the Settings page at all, those switches are all just placeholders. Tune in to the Unigram Insiders channel for updates about the progress. And regarding the loading time, yes, we are aware of it, we are making a diagnosis of several parts of the app that causes a slowdown at the start. We will try and fix it. :)

**Comment by tofylion** [comment]
@kesavaprasadarul Thanks for your reply. I really like this app and the fact that it was done by windows lovers is just amazing. This reminds me of PoGo, before Niantic made it hard for them to continue. Telegram is open source and I think you'll get the hang of this app. This really puts the fun in Telegram. ☺

**Comment by kesavaprasadarul** [comment]
@tofylion Cool. Happy testing the app, please do post more feedback. 😉
