### ISSUE TITLE
Improvement in auto download setting for chats and groups/channels

### ISSUE THREAD

**Issue by amirso94** [UnigramDev/Unigram#640]
Please implement this option in autodownload setting and let us choose separately activing auto download for chats and groups/channels.
Right Now they are all combined.
Thanks

**Comment by FrayxRulez** [comment]
You have separate options for contacts, private chats, supergroups and channel.
You can't personalize specific chats tho (and this won't come any time soon).

**Comment by amirso94** [comment]
@FrayxRulez @FrayxRulez 
I had test this on mobile and laptop
Just when i activate voice auto download for groups ( the third one) my voices download itself when I'm chatting with my friend ( and voices in groups are loaded too which I don't want)
is it what you program? I mean I say I think it's not correct.
1.8.1607
