### ISSUE TITLE
Instructions for compiling are outdated - Template10

### ISSUE THREAD

**Issue by Zenexer** [UnigramDev/Unigram#641]
The current instructions for compiling are outdated.  The solution references Template10 [here](https://github.com/UnigramDev/Unigram/blob/543559bee4971de4571019d5e8689371f1bf747f/Unigram/Unigram.sln#L45).  That means there should be something at `Libraries\Template10-version_1.1.12_vs2017\Template10 (Library)\Template10 (Library).csproj`, but the `Template10-version_1.1.12_vs2017` directory doesn't exist because [it's in .gitignore](https://github.com/UnigramDev/Unigram/blob/543559bee4971de4571019d5e8689371f1bf747f/.gitignore#L266), and there's [no corresponding submodule](https://github.com/UnigramDev/Unigram/blob/543559bee4971de4571019d5e8689371f1bf747f/.gitmodules).  I assume it's a custom fork of Template10.

The instructions [say to use the Template10 NuGet package](https://github.com/UnigramDev/Unigram/blob/develop/README.md#dependencies).  If I replace the references to the custom Template10 project with the Template10 NuGet package, I get a variety of build errors indicating that vanilla Template10 won't work:

![image](https://user-images.githubusercontent.com/504130/45260439-ab592a00-b3b5-11e8-9055-17dc06d7c7ad.png)

**Comment by FrayxRulez** [comment]
Development at the moment isn't really open source, due to some complications we had with clones in the Store.
If you want the missing components you can still ping me on Telegram and I might decide to provide them to you 😅
