### ISSUE TITLE
ability to search in (send menu)

### ISSUE THREAD

**Issue by samij263** [UnigramDev/Unigram#642]
In send (forward) menu, "search" doesn't work

**Comment by MarcAnt01** [comment]
It should have been fixed in this commit https://github.com/UnigramDev/Unigram/commit/ae83f39280995a10afd2278f8763a52b8c68aa5c

**Comment by amirso94** [comment]
no it's not. i still have this issue on mobile & PC

**Comment by MarcAnt01** [comment]
Yep, bro, I was wrong, in fact I have deleted comment not to create confusion

**Comment by amirali013** [comment]
@samij263 😍

**Comment by FrayxRulez** [comment]
Duplicate of #339
