### ISSUE TITLE
Profile picture isn't shown over multi account selection

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#643]
Over the multiple account selection there should be an area with the profile picture, but instead of it there's  a blank space which is the same color as system accent. It should be as the following photo (Telegram X for Android) 
![448413356_160746](https://user-images.githubusercontent.com/43090263/45265176-96c57200-b447-11e8-8477-db6b3e7de649.jpg)

**Comment by FrayxRulez** [comment]
This is intended, I prefer the current UI

**Comment by MarcAnt01** [comment]
OK, I trust you😀👍
