### ISSUE TITLE
Size of selectable area

### ISSUE THREAD

**Issue by morenj96** [UnigramDev/Unigram#646]
Before version 1607, selectable area of keys (send, attach, ... in a chat page) were square, but now became similar to a circular shape.
It makes slower chatting for users.
Please make it a square shape to select.

**Comment by ferferga** [comment]
The circular squared animation is great, but the new area to tap/click in buttons difficulties many things using the app. Would be great if the animation could be kept the same (circular) but the old touchable/clickable area returns.

**Comment by FrayxRulez** [comment]
Rolled back to squared buttons

**Comment by ferferga** [comment]
No way to have the squared buttons for tapping, but a circular animation when pressing, like new versions do?
