### ISSUE TITLE
Time of inseting picture for profile

### ISSUE THREAD

**Issue by morenj96** [UnigramDev/Unigram#647]
It was a vantage point for Unigram that now isn't visible. Time and date of inserting profile picture was visible until about 5 months ago versions
Please add again it.

**Comment by FrayxRulez** [comment]
Sadly, [TDLib](https://github.com/tdlib/td/) doesn't support this feature at the moment

**Comment by morenj96** [comment]
Sadly 😢

**Comment by FrayxRulez** [comment]
This has been implemented in recent Unigram versions!
