### ISSUE TITLE
Frequently Contacts 

### ISSUE THREAD

**Issue by morenj96** [UnigramDev/Unigram#648]
This ability works when the user has some data for frequently of contacts profiles from previous versions. But if a user start using Unigram version 1607 (even 1609, 1610, 1620) or he just reinstalled it, this ability doesn't work for him, and contacts don't shown with searching profile, opening profile, even opening chat page.
"Recent" works well, but not for "Chats", in search.
Please check it.

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/f1b832d7b52cb1559ae34914e300a765cbb055a2

**Comment by morenj96** [comment]
Thank you Fela 🌹🙏
