### ISSUE TITLE
The app lacks of error messages

### ISSUE THREAD

**Issue by amirso94** [UnigramDev/Unigram#649]
Messages not shown:

- [x] Sign in experience
- [x] Expired join links
- [ ] Trying to add a person that left the group
- [ ] Pin more than 4 chats
- [ ] Add to a group non contacts that have disabled that option in privacy 
- [ ] Add to group a person or a bot that's already in
- [ ] Access a group where you are banned
- [ ] Post a content where you 
- [ ]  Accounts restricted for spam trying to post in groups

**Comment by larsschellhas** [comment]
If you try to add an admin to your group, but the person is already an admin, there should be a Info-Message to inform about that, since admins won´t be filtered from the list regarding to #587

**Comment by FrayxRulez** [comment]
If you try to add an admin to your group, but the person is already an admin, then you'll get the edit admin page, as it happens in the official apps.

**Comment by FrayxRulez** [comment]
> 
> 
> If you try to add an admin to your group, but the person is already an admin, there should be a Info-Message to inform about that, since admins won´t be filtered from the list regarding to #587

you try to add an admin to your group, but the person is already an admin, then you'll get the edit admin page, as it happens in the official apps.

**Comment by 3xploiton3** [comment]
(request) add more pin chat and drag drop chat like telegram official

**Comment by MarcAnt01** [comment]
> (request) add more pin chat and drag drop chat like telegram official

The number of pinned chat is the same as official client, drag ane drop in chat list isn't possible, but you can reorder them directly from settings

**Comment by 3xploiton3** [comment]
![image](https://user-images.githubusercontent.com/19517680/54433196-d6a24480-475d-11e9-999c-3bb24d2ef9b7.png)

bettergram can do more pin, it will very helpful for manage many group

**Comment by MarcAnt01** [comment]
@3xploiton3 Unigram follows official guidelines, so won't take features from non-official clients

**Comment by DarthJahus** [comment]
There is a situation when the user joins too many channels in a short time and gets limited by Telegram.

Telegram X shows the error message "Too many requests, try again in xx minutes"

However, Unigram X shows: "This conversation doesn't exist".
