### ISSUE TITLE
Search group messages by member

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#650]
Messages search misses the ability to filter them by their owner

**Comment by FrayxRulez** [comment]
Is is available in any Telegram app :)

**Comment by MarcAnt01** [comment]
@FrayxRulez Didn't know, just noticed with Telegram X😂

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/91ffde8e08c83260ffd32e5c00eaa79c7623ac89
