### ISSUE TITLE
Send live locations

### ISSUE THREAD

**Issue by ferferga** [UnigramDev/Unigram#654]
Live locations aren't available at the moment of writing.

**Comment by xperiandri** [comment]
Do you mean that there is a button to share a live location which does nothing?

**Comment by ferferga** [comment]
Exactly

**Comment by ferferga** [comment]
> Do you mean that there is a button to share a live location which does nothing?

Exactly :)

**Comment by bugada** [comment]
Confirmed on mobile, the live position doesn't work. Worked as expected in previous version on october 8th.

**Comment by MarcAnt01** [comment]
As for the moment, the focus in on Desktop, it'd be nice to be able to see live location shared by other people properly outside of the preview

**Comment by FrayxRulez** [comment]
Closing this, as it makes no sense to have live location anymore.
