### ISSUE TITLE
Improve Channels' appearance

### ISSUE THREAD

**Issue by ferferga** [UnigramDev/Unigram#655]
In Telegram X for Android, messages from channels appears centered inside the chat window and bigger than messages in other chats. This is also true for TDesktop, which doesn't display the messages centered like in TX, but displays them much bigger than Unigram in PC, which makes so much sense, as currently there is some wasted space.

**Comment by Poolitzer** [comment]
I second this.

**Comment by Poolitzer** [comment]
@Poolitzer I really second this ;P

**Comment by FrayxRulez** [comment]
I'd like to add the adaptive layout for wide screens, as TDesktop does, but this would require a lot of work and probably some performance deterioration.
I can set a maximum width to the messages panel, but this would simply center the messages, without changing sent messages alignment (as TDesktop does).
Could this work for you? (As I don't really like this, I would prefer left alignment)

**Comment by ferferga** [comment]
Yeah, by reading it, seems fine for me! Would be great if you could provide some screenshots to see the final appearance (I still can't imagine it so well), allowing also the rest of the members in the group to check and give some feedback.

**Comment by MarcAnt01** [comment]
As for readability in channel I would suggest to remove the "mute/unmute" button and move it to the same area as groups and private chats, as it is on Telegram X

**Comment by FrayxRulez** [comment]
I'd say this can be considered ok after the adaptive layout for wide screens introduction
