### ISSUE TITLE
Search results disappear when the search field looses focus

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#656]
If you search for something search results in form of contacts, global search results and messages appear.
But if you click somewhere or you close the touchkeyboard by pressing the back button, the search fiel looses focus and the previously shown global results and found messages disappear.
Example Pictures incoming.

**Comment by larsschellhas** [comment]
## Mobile
![image](https://user-images.githubusercontent.com/14281234/45322394-cd3ae400-b550-11e8-91af-5382c14b69b7.png)
![image](https://user-images.githubusercontent.com/14281234/45322416-d75ce280-b550-11e8-97e8-b6de5d6d2c74.png)

## Desktop
![image](https://user-images.githubusercontent.com/14281234/45322484-1428d980-b551-11e8-9089-a30efff64d41.png)
![image](https://user-images.githubusercontent.com/14281234/45322503-1e4ad800-b551-11e8-8e86-ada0cb0a03ea.png)

**Comment by FrayxRulez** [comment]
This should be fixed in some recent commit
