### ISSUE TITLE
Improve Multi-Account´s Burger-Menu appearence

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#658]
First of all:
## It looks great!
second:
#### two little things that would make it even better 🙀 IMHO 

1. Add a little shadow below the coloured area. It will give it some light depth (where the red line is)
2. Since you can still scroll up and down a little bit on touch screens or when the accounts are all shown and the list is long enough, this could need a little polishing, because the coloured part stays in it place. I see two possibilities for this: either scroll the coloured region up and down the same amount or somehow fixating the account managing part of the hamburger menu (but I guess it is not possible 🙈 )

![inked246922591_215056_li](https://user-images.githubusercontent.com/14281234/45323049-a54c8000-b552-11e8-9e90-b00ed5aa3450.jpg)

**Comment by FrayxRulez** [comment]
I'm not going to add the shadow, but I fixed the scroll issue here https://github.com/UnigramDev/Unigram/commit/90077337d4cd404dfb5345f4293ad40b4c85702d

**Comment by larsschellhas** [comment]
Fine for me 😄
