### ISSUE TITLE
Extend content into the titlebar

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#659]
Similar to Microsoft´s strategy to extend the navigation view into the title bar in apps like Mail, To-Do, Calendar, it would be nice to see Unigram adapt some of these designs.

![image](https://user-images.githubusercontent.com/14281234/45323610-5a336c80-b554-11e8-8c2b-f726547ad122.png)

For example when no chat is opened the background image and the chat section´s shadow could be extended into the title bar, just like this:

![unigram - mockups - ohne chat](https://user-images.githubusercontent.com/14281234/45326669-332d6880-b55d-11e8-8164-a388f7f7aa06.jpg)

And if you open a chat, the chat header would appear exactly as it is now, but the shadow which gives a feeling of depth would still be there:

![unigram - mockups - mit chat](https://user-images.githubusercontent.com/14281234/45326768-8acbd400-b55d-11e8-9622-26f39249a3e7.jpg)

If you would like to go even further you could give the chat-info-header, the pinned messages and even the header bar of the chat list (and the title bar above) an acrylic/transparent/blurry effect to make it look even cooler:

![unigram - mockups - mit chat - acrylic](https://user-images.githubusercontent.com/14281234/45326865-cc5c7f00-b55d-11e8-97a0-8d82745b3cae.jpg)

This resembles somehow the usage of acrylic in the top navigation pane as shown e.g. in the Microsoft Store.

![image](https://user-images.githubusercontent.com/14281234/45326963-4260e600-b55e-11e8-9478-fbc73479b554.png)

Maybe it would even have sense to use the top navigation pane at desktop, but there would probably be a lot of problems supporting the still used W10Mobile devices.

Sources: https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview

**Comment by FrayxRulez** [comment]
Done! https://github.com/UnigramDev/Unigram/commit/ef25acf50cf8b3f6b2eed034db968f1328278f76
