### ISSUE TITLE
Duplicated entries on my contact list

### ISSUE THREAD

**Issue by ghost** [UnigramDev/Unigram#66]
I was using the App while I walked to Contacts' list and I saw that some contacts were duplicated or triplicated
![wp_ss_20161102_0009](https://cloud.githubusercontent.com/assets/23224727/19950895/caccbd30-a15a-11e6-807a-2eb44fa8bd66.png)
![wp_ss_20161102_0008](https://cloud.githubusercontent.com/assets/23224727/19950898/d68d3992-a15a-11e6-939c-d6e29fe08778.png)
Then I closed the App and opened again, another one apeared duplicated (only once) after a few minutes.

**Comment by mohsens22** [comment]
@jozeeatm 😐

**Comment by jozeeatm** [comment]
After I resumed Unigram, it happened again
![wp_ss_20161103_0003](https://cloud.githubusercontent.com/assets/23224727/19952223/e6cf5002-a163-11e6-8fa7-1e73e53b0ce6.png)

**Comment by raminmjj** [comment]
> After I resumed Unigram, it happened again
> ![wp_ss_20161103_0003](https://cloud.githubusercontent.com/assets/23224727/19952223/e6cf5002-a163-11e6-8fa7-1e73e53b0ce6.png)

I have the same problem.
in some cases duplicated contact has no image profile.

**Comment by FrayxRulez** [comment]
Looks like you're using a __two years old__ Unigram version...

**Comment by raminmjj** [comment]
> Looks like you're using a **two years old** Unigram version...

no it's not my phone screenshot. that's just a "Quote"
I'm using the latest version."2.0.1684"
