### ISSUE TITLE
Video messages are audio free

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#660]
There's no audio with the video messages recorded with Unigram, it's not possible neither to play video messages recorded by other people

**Comment by larsschellhas** [comment]
There is audio recorded, but you can´t replay it in Unigram.

**Comment by MarcAnt01** [comment]
Just tested now and on my Android device I cannot the audio, so Unigram doesn't record audio. (tested with 2.0.1630 latest appxbundle from PC). What version have you used to test?

**Comment by larsschellhas** [comment]
Same version on my phone. Check I you´ve allowed Unigram to use your microphone, please.

**Comment by MarcAnt01** [comment]
@larsschellhas Yes, I have allowed it. Is it possible it is a PC-only bug, then🤔?
