### ISSUE TITLE
Bot start interface

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#663]
This is a missing feature, I cannot describe it in words, but I have attached that screenshot from Telegram X to be more clear
![image](https://user-images.githubusercontent.com/43090263/45347409-50d5ee80-b5ac-11e8-8a15-6c335242096b.png)

**Comment by MarcAnt01** [comment]
Partially fixed in https://github.com/UnigramDev/Unigram/commit/1e7522c9ae125f3b2c94270f3f8ccd8eaa01c4a2

**Comment by FrayxRulez** [comment]
Fixed
