### ISSUE TITLE
Show online status dot near the profile picture bubble in chat search 

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#664]
Here a picture of how it should be
![image](https://user-images.githubusercontent.com/43090263/45347990-aeb70600-b5ad-11e8-8c5c-3b14f2928cc5.png)

**Comment by FrayxRulez** [comment]
Online status is a Telegram X only feature, and I'm not going to implement it

**Comment by MarcAnt01** [comment]
OK, no problem

**Comment by MarcAnt01** [comment]
Reponed as it's in Telegram as well now

**Comment by FrayxRulez** [comment]
Done!
