### ISSUE TITLE
Support for robots (if it's possible)

### ISSUE THREAD

**Issue by samij263** [UnigramDev/Unigram#666]
Apparently the app doesn't support robots.

**Comment by larsschellhas** [comment]
Unigram does of course support Telegram bots. 
What problems do you run into?

**Comment by samij263** [comment]
@larsschellhas 1- viewing bot's profile
2- start option won't appear unless i write manually.

**Comment by MarcAnt01** [comment]
@samij263 Duplicate of that https://github.com/UnigramDev/Unigram/issues/663

**Comment by MarcAnt01** [comment]
Anyway, when creating issues you have to be more clear
