### ISSUE TITLE
Can't talk in Unigram to people pinned on my taskbar

### ISSUE THREAD

**Issue by SaulNunez** [UnigramDev/Unigram#670]
In the newest versions of Windows 10 you can pin people from your contacts to the taskbar, and you can choose an app to talk to them directly. However, when I select Unigram I have no chat window. I do however have the hambuger menu, but it does nothing.

![unigram_pinned](https://user-images.githubusercontent.com/13012976/45375860-71557700-b5b3-11e8-96b3-3ea8bbebf766.jpg)

**Comment by sukram230799** [comment]
Thanks for your report but this problem was already addressed in [35b20cf](https://github.com/UnigramDev/Unigram/commit/35b20cfdd60852459bae69fc8e76ec179f35d2ba)
