### ISSUE TITLE
add options to recent action as same as tlgrm desktop

### ISSUE THREAD

**Issue by samij263** [UnigramDev/Unigram#672]
And also it loads just few recent actions(as i always seen).

**Comment by MarcAnt01** [comment]
@samij263 Try to explain yourself

**Comment by MarcAnt01** [comment]
I think it's better adding this information to my issue https://github.com/UnigramDev/Unigram/issues/638 and closing this one, just to make Fela's work easier

**Comment by FrayxRulez** [comment]
Duplicate of #638
