### ISSUE TITLE
Windows 10 My People integration doesn't work

### ISSUE THREAD

**Issue by vahandr** [UnigramDev/Unigram#673]
The "Click to connect this app" button in the Windows 10 MyPeople settings opens Unigram, but nothing else happens.

**Comment by MarcAnt01** [comment]
@vahandr What version are you running?

**Comment by larsschellhas** [comment]
@MarcAnt01 It is already fixed in the latest commits, but not published in the store yet. Please be patient for some more days 🙂 and thanks for the report
