### ISSUE TITLE
Founder badge (member section only)

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#677]
It's not possible to understand who's the founder of a group from group member section, it shows "admin" weather founder or not

**Comment by HAsadian** [comment]
@MarcAnt01 I think its better show members in a section named "members". and show admins in another section named "admins" ( this section is available but only admins can see it )

**Comment by MarcAnt01** [comment]
@HAsadian Yes, it would be a very nice improvement too even if Idk any telegram client with it

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/56c2685ba31e6bfbd7a996a012012d12d101ae03
