### ISSUE TITLE
in group and channel admin list app show last seen of creator and not "creator" word

### ISSUE THREAD

**Issue by alighamari** [UnigramDev/Unigram#679]

**Comment by alighamari** [comment]
![image](https://user-images.githubusercontent.com/24440862/45511529-82b8a200-b7b2-11e8-9622-77b173bc2ded.png)

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/9b16d0fbe77c8ffab3370207881cbe41a4ed5218
