### ISSUE TITLE
 hi

### ISSUE THREAD

**Issue by sinakiyani** [UnigramDev/Unigram#68]
hello. We unigram a nice update. And I think that we are together. Why the update is not received? I myself, for example, I have a good idea of the chat part layout, or from above, and a lot of things I chose nice. thank you

**Comment by kesavaprasadarul** [comment]
Hi,
Thank you using Unigram. We are happy of your enthusiasm towards the project. To give ideas and immediate feedback, please join Unigram Insiders Channel on Telegram. Regarding the updates, we are working and trying to bring out a better and a stable version of Unigram as the next update. :)
