### ISSUE TITLE
add administrator suggestion in administrators section should be only visible to admins who have right to add admin

### ISSUE THREAD

**Issue by alighamari** [UnigramDev/Unigram#680]
![image](https://user-images.githubusercontent.com/24440862/45511718-fb1f6300-b7b2-11e8-8ed7-d6c6543979cd.png)

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/bfce356ae4f224c079c2a9de1a0342ff5f166469
