### ISSUE TITLE
App randomly showing "updating" on title bar even though connection is fine

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#684]
This behavior started with 1646
![image](https://user-images.githubusercontent.com/43090263/45559776-af68ca00-b843-11e8-8aff-63afeabd02c8.png)

**Comment by MarcAnt01** [comment]
I've found out the situation when it happens: after closing Unigram and opening it again, it doesn't happen after reboot or after force closing Unigram via task manager

**Comment by FrayxRulez** [comment]
This should be fixed
