### ISSUE TITLE
Proxy Shortcut while we are using proxy

### ISSUE THREAD

**Issue by amirso94** [UnigramDev/Unigram#686]
as some proxies get slow and we have to change it _so if we are using a proxy_ maybe it's better always having that shortcut near the search button.
i'm just saying having it while proxy is on but not on usual connection.
thanks.

**Comment by FrayxRulez** [comment]
This is fixed.
Proxy shortcut will be shown if any of the following conditions are true:
- Waiting for network/connecting
- Current connection might be subject to restrictions
- Current connection is happening through a proxy
