### ISSUE TITLE
Graphic bug with chat open in a new window

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#688]
When opening a chat in a new window some elements overlap
![image](https://user-images.githubusercontent.com/43090263/45570422-003beb00-b863-11e8-9227-fe98fbbd5edd.png)

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/d6ab1167a1335c12887d3fdb5c9030f75512c1d8
