### ISSUE TITLE
Profile picture not working after changing or deleting it

### ISSUE THREAD

**Issue by amirso94** [UnigramDev/Unigram#689]
After changing or deleting my profile picture it shows nothing and i can't open it too. ( and i should notice it change/delete it correctly).
I have to reopen the app to see or open my profile photo.
2.0.1646 on mobile

![blur-636726064269685953](https://user-images.githubusercontent.com/43098665/45583462-ef798c80-b8d7-11e8-83b8-638b5d6e0aa6.jpg)

**Comment by amirso94** [comment]
@amirso94 Beside this bug☝🏼
After adding a new profile picture, the saved mesages default photo will change to the new profile picture and it will solve by restarting the app
2.0.1684

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/1f27263b3dacc335826f3a8d28561f067ffb00e5
