### ISSUE TITLE
Bugs with inline bots

### ISSUE THREAD

**Issue by amirso94** [UnigramDev/Unigram#690]
- [x] When I'm using inline bots like sticker and vid, it doesn't show any pic of the results, it's annoying specially about sticker inline bot.
2.0.1646 on mobile
Thanks.

![wp_ss_20180915_0006](https://user-images.githubusercontent.com/43098665/45584244-69644280-b8e5-11e8-8935-5f71a6d1b649.png)
![wp_ss_20180915_0008](https://user-images.githubusercontent.com/43098665/45584246-69fcd900-b8e5-11e8-810a-d8512d8e8bc5.png)

- [x] After clicking on gif bot the keyboard isn't triggered automatically

- [x] It seems like sometimes you write too fast, so that the inline-bot either does not process the message at all or it only processes some of the first letters of the word. If that happens you need to add or delete a letter and wait shortly for it to update.
I´ve experienced this e.g. with @gif and @bing

**Comment by MarcAnt01** [comment]
![image](https://user-images.githubusercontent.com/43090263/56861831-3028a080-69a5-11e9-8d65-90d2e81c028c.png)

**Comment by MarcAnt01** [comment]
![image](https://user-images.githubusercontent.com/43090263/57018519-29f42780-6c24-11e9-8d3e-ed8488b4b6d5.png)

**Comment by barinbritva** [comment]
I also noticed that sometimes Unigram sends text in wrong order. For instance, if I type "hello" I can see in my bot logs that first request contains "hell", but second "he".

**Comment by cewbdex** [comment]
Also it would be nice to block the send button (or replace it with erase button as it is on Android).

**Comment by GameSpeck** [comment]
Here are some more bugs I found:

**- Glitched inline placeholer/text**
![image](https://user-images.githubusercontent.com/43648146/81692420-00e3b500-947c-11ea-9bb0-702dc8f0ef49.png)
The inline text overlaps the bot's username

**-Glitch when switching chats when an inline bot is used**
How to reproduce:
1. Type any inline bot's name (for eg, [at]rextester_bot)
2. Don't type anything (You will only see the inline text placeholder)
3. Switch chats
4. This: 
![image](https://user-images.githubusercontent.com/43648146/81694232-b4e63f80-947e-11ea-8861-dd8fe97fcaf3.png)

**-Inline preview doesn't disappear when bot's name is removed**
How to reproduce:
1. Use any inline bot (for eg, [at]rextester_bot)
2. Type anything and then quickly select all using ctrl+a and delete it
3. This: 
![image](https://user-images.githubusercontent.com/43648146/81694772-608f8f80-947f-11ea-8e07-175fc30ec20c.png)

**Comment by FrayxRulez** [comment]
So all the problems above should be fixed. Please feel free to open a new ticket if they will still occur or you find any other inline bots-related issue in version 4.0.x.
