### ISSUE TITLE
On Desktop the back button is not working in search chat section

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#698]
To get back to chat, it's necessary writing a character and pressing "X" or going to chat from hamburger menu

**Comment by larsschellhas** [comment]
on PC only

**Comment by larsschellhas** [comment]
On PC, pressing the back button doesn´t cause the search box to lose the focus.

**Comment by MarcAnt01** [comment]
I haven't understood your comment

**Comment by larsschellhas** [comment]
If you open the search box, focus is put onto it. That way the touch keyboard opens or you can type directly on your hardware keyboard.
If you press the back button on the phone the touch keyboard gets closed and the focus is taken away from the search field. That way, if the search field is empty, the search closes.
You can see the same behaviour in the desktop version. Open search and click anywhere else in the app on a free (non-button) area, the focus is taken away from the search field and search closes.

**Comment by MarcAnt01** [comment]
Oh, OK, got now, had just noticed that the behavior was strange, nothing more😂

**Comment by larsschellhas** [comment]
@FrayxRulez Of course to use the back button would be an option, but I guess that would collide with the recent correct behaviour on phones.
I would suggest to take one of your new animated approaches, where the magnifier goes over to the left and add a X-Button on the right, which shows up as soon as the search field is opened and not only when there is text in it.

**Comment by MarcAnt01** [comment]
The button on right is already here, but can be used only when typing at least a character

**Comment by MarcAnt01** [comment]
@FrayxRulez I think a swipe from bottom would be great if you don't want to fix it

**Comment by MarcAnt01** [comment]
Fixed in some recent commits
