### ISSUE TITLE
Skype-uwp-like call pop-up

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#703]
Call pop-up would be nice for Desktop users. Actually, it should be smaller than Skype one as there are no video calls in Telegram
![image](https://user-images.githubusercontent.com/43090263/45596146-941ecb80-b9b7-11e8-903b-9c8b0cacc037.png)

**Comment by FrayxRulez** [comment]
Done in https://github.com/UnigramDev/Unigram/commit/99a54e52511c44d214e75633a381879a29f7cf4e

**Comment by MarcAnt01** [comment]
Thank you so much for adding it, could you change the size of the pop-up Window? 'Cause I think that the actual one is slightly too big
