### ISSUE TITLE
Support poll bot links sharing

### ISSUE THREAD

**Issue by xperiandri** [UnigramDev/Unigram#706]
Register @poll bot
Create poll
The will be a link in it to share it.

When you tap that link in web version the share dialog opens and I can choose a group to share it. But nothing happens in Unigram

**Comment by FrayxRulez** [comment]
There's no bot named @poll...

**Comment by MarcAnt01** [comment]
@FrayxRulez Try t.me/vote, I got an error too with it

**Comment by DarthJahus** [comment]
@MarcAnt01

**Comment by MarcAnt01** [comment]
@DarthJahus Reason of tag?

**Comment by alighamari** [comment]
he mean links like http://t.me/PollBot?startgroup=0d11680708568e510637488238c49c19

**Comment by MarcAnt01** [comment]
@alighamari Yep, common problem to all pool bots

**Comment by alighamari** [comment]
can we change the title to add support for all action links 
like t.me/{0}?startgroup or tg://{0}?startgroup 
this action adds the {0} to groups send start@{0} with a token like "0d11680708568e510637488238c49c19"

**Comment by FrayxRulez** [comment]
Duplicate of #574
