### ISSUE TITLE
Improve ESC behaviour when using answer, forward or search functionality

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#712]
If you select a message to answer to, open the forward dialog for a message or even if you open the search field, you might want to abort that action. One of my usual ways to do something like that is to press the ESC button. 
Unfortunately that does not only close the forward dialog or abort the answer, but it closes the complete chat. In case of the search field it even closes **only** the chat, but not the search field - even additional presses of the ESC button do nothing to it as long as there is no content written in it.

Because of that I would suggest that by pressing the ESC button the last opened dialog/search is closed, while additional presses would close previously opened dialogs or the chat page.
The only combinations of these three functions to be open seem to be:
1) "Answer" to a message, without sending it
2a) Open the search field
3a) Open the forward dialog (in this case the search field only stays open, if you have written something already
2b) Open the forward dialog
3b) Open the search of the forward dialog

**Comment by FrayxRulez** [comment]
This is fixed

**Comment by larsschellhas** [comment]
When I have a chat open and use the chat-list-search, ESC still closes the chat first

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/e197606bf6e1db3eb7229ce075a173a55bac3c62
