### ISSUE TITLE
Sometimes inline-bots don´t process the written text correctly

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#713]
It seems like sometimes you write too fast, so that the inline-bot either does not process the message at all or it only processes some of the first letters of the word. If that happens you need to add or delete a letter and wait shortly for it to update.
I´ve experienced this e.g. with @gif and @bing

**Comment by bugada** [comment]
The same happens if you cut & past the whole line. 
You need to delete some parts of the text.

**Comment by MarcAnt01** [comment]
I've edited https://github.com/UnigramDev/Unigram/issues/690  to be more generic
