### ISSUE TITLE
I can't reply to a message if I open Unigram through notifications

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#714]

**Comment by FrayxRulez** [comment]
Duplicate of #579?

**Comment by MarcAnt01** [comment]
Nope, already checked that issue and it's about a behavior of message someones reply to not the message reply

**Comment by FrayxRulez** [comment]
Then I can't understand this one

**Comment by MarcAnt01** [comment]
When I open Unigram from a notification, replies don't work

**Comment by FrayxRulez** [comment]
Then it's a duplicate :D

**Comment by MarcAnt01** [comment]
Idk, in that bug said that the replied is sent and just not displayed in the preview as usual

**Comment by larsschellhas** [comment]
@MarcAnt01 Yes and this is really how it it. If you click answer but nothing shows up, you still reply to the correct message, if you send your message

**Comment by MarcAnt01** [comment]
But If I can't select the message I reply to, how can the reply be sent?

**Comment by MarcAnt01** [comment]
Guys, they are different things, trust me

**Comment by larsschellhas** [comment]
What message was it then?
I see no difference, because I never encountered a behaviour where I could not reply, but sometimes the "reply banner" is not visible.

**Comment by MarcAnt01** [comment]
How can you reply to a message, if the banner doesn't appear?

**Comment by larsschellhas** [comment]
You simply write the message and send it. It is still processed as a reply to that message.
It is exactly what #579 is about.
