### ISSUE TITLE
Default path for downloading files and medias 

### ISSUE THREAD

**Issue by mrg1373** [UnigramDev/Unigram#724]
every time i want to save a pic or video or file, unigram ask me the path , please add default path which is changeable in settings.

**Comment by Giakin** [comment]
I need to, i try to link "document" mklink folder but doesnt work ;( some idea?

**Comment by FrayxRulez** [comment]
Implemented in https://github.com/UnigramDev/Unigram/commit/0582da784c50ffe1cdb8d8027caa5a8e24bc3ce0

**Comment by Elsayed-A** [comment]
> Implemented in [0582da7](https://github.com/UnigramDev/Unigram/commit/0582da784c50ffe1cdb8d8027caa5a8e24bc3ce0)

how to get unigram to ask download path for each file
