### ISSUE TITLE
GIF bot search action

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#725]
Maybe this happens with other in-line bots too, but I don't know another one to test it too. Anyway, after tapping gif near the person who sent the gif, it starts the bot, but search doesn't trigger automatically as it should be

**Comment by FrayxRulez** [comment]
Can we create a single ticket about inline bot issues?

**Comment by MarcAnt01** [comment]
This happens with all inline bots, tested now

**Comment by FrayxRulez** [comment]
That's what I'm saying. Inline bots have a lot of issues and right now we have a bunch of tickets about them. It makes sense to create a single one.

**Comment by MarcAnt01** [comment]
You are right, I will create a ticket with all the problems with them

**Comment by MarcAnt01** [comment]
Edited https://github.com/UnigramDev/Unigram/issues/690 to be more generic
