### ISSUE TITLE
@sticker bot shows placeholders

### ISSUE THREAD

**Issue by skrachkovsky** [UnigramDev/Unigram#730]
Sticker shows placeholder on any emoji

![applicationframehost_2018-09-21_14-00-18](https://user-images.githubusercontent.com/32353818/45877501-bee99500-bda6-11e8-805e-de27ffc2ff0e.png)

**Comment by MarcAnt01** [comment]
Duplicate of https://github.com/UnigramDev/Unigram/issues/690
