### ISSUE TITLE
swipe left or right to forward or reply

### ISSUE THREAD

**Issue by mrg1373** [UnigramDev/Unigram#732]
Please add it to massage bubble, windows 10 support swipe gestures. Why you didn't add it?

**Comment by MarcAnt01** [comment]
Maybe swipe left to answer and right to go back, otherwise it makes no sense

**Comment by mrg1373** [comment]
No i mean when you swipe a specific message, user could forward or reply to that message, like in official version of telegram in store

**Comment by MarcAnt01** [comment]
Idk how it is Telegram for WP but Android and iOS clients have swipe left to answer and swipe right to go back

**Comment by MarcAnt01** [comment]
Swipe added in https://github.com/UnigramDev/Unigram/commit/ca3547b7fcda90ab68caff35f9510f8ae95b0b75

**Comment by MarcAnt01** [comment]
Go back gestures aren't supported by uwp, so they will never come to the app

**Comment by caeslucio** [comment]
I've using a Windows 10 touchscreen leptop Dell 15r 5537, and I'm unable to use swipe to reply on current version of Unigram, both Store (8.6.7182.0) and Direct (8.7.7352.0) versions.
