### ISSUE TITLE
Can't load all of the chats sometimes

### ISSUE THREAD

**Issue by RezaT4795** [UnigramDev/Unigram#733]
If you leave the app for a few hours, then launch the app, it won't load all of the chats. You have to relaunch the app.
It may be a random bug, but I've seen it happen several times.

**Comment by MarcAnt01** [comment]
Does it still happen with 2.x versions?

**Comment by RezaT4795** [comment]
Yes. Actually, I don't remember it happened before 2.x versions.

**Comment by FrayxRulez** [comment]
This is fixed with filters introduction
