### ISSUE TITLE
Improvements for compact mode

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#734]
I would suggest the following things

- [ ] Add a button for compact mode, it's faster then resizing manually and through it, when I exit from it, I can have the normal resizing, without moving it back. My idea is about a double tap/click on the three lines of hamburger menu, so that it's easily working also from compact mode 

- [ ] Revert back compact mode when resizing a window on PC like before 1.8

**Comment by FrayxRulez** [comment]
Current resizing behavior is exactly the same as TDesktop, as a lot of people requested to make the app work this way. As this I'm closing this ticket for now.
