### ISSUE TITLE
Problems with links to bot personalized commands in private

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#737]
To reproduce this issue, it's necessary to get in a group with Marie bot and type /rules, after clicking on the button in bot answer, it goes automatically to private chat, where there's a "start" button, after pressing it, it should disappear, but it doesn't

**Comment by FrayxRulez** [comment]
Duplicate of #574

**Comment by MarcAnt01** [comment]
Sorry, didn't think it was correlated with deep linking
