### ISSUE TITLE
Improvements to photo viewer

### ISSUE THREAD

**Issue by jp-weber** [UnigramDev/Unigram#743]
- [ ] Making swipe touch gesture shorter
- [ ] simplify the switch between images with mouse, currently a wheel is required

**Comment by MarcAnt01** [comment]
Touch to go to next photos isn't implemented in Microsoft Photo and I don't think everyone would like it, as for the double tap to zoom, yes, cool feature

**Comment by jp-weber** [comment]
Gesture navigation between photos are already implemented, but the gesture is too long. It would be better, if the gesture has the same way length like in the Teleram Messenger app.

**Comment by larsschellhas** [comment]
I agree, but I would add that also the intertia of the movement could be considered.
If I swipe fast I want the picture to change, but when I swipe slow or even don´t move anymore and release I would probably want to stay on that on picture 🤔 

So my suggestion is: Make the length of the gesture or the necessary displacement to switch a function of the moving velocity. That way you would need to swipe a picture further to a side if you swipe very slowly, but a fast swipe in the middle of the screen would do the job, too.

**Comment by MarcAnt01** [comment]
@jp-weber I agree, I have a touch screen laptop and I have to swipe for about 6 inches lol

**Comment by MarcAnt01** [comment]
Anyway, zoom function is already covered by https://github.com/UnigramDev/Unigram/issues/702

**Comment by MarcAnt01** [comment]
I would also point out that switch the keyboard arrow is slow and if I click twice in a short time, it moves just of a picture

**Comment by FrayxRulez** [comment]
This should be done, I'd say?
