### ISSUE TITLE
Send with "enter" in forward menu

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#750]

**Comment by GingerPlusPlus** [comment]
<kbd>Ctrl</kbd>+<kbd>K</kbd> "insert link" also does not allow to confirm with Enter.

Also, perhaps a separate issue: regardless of "Send by <kbd>Enter</kbd>" setting, when trying to reply to a message from within notification, <kbd>Enter</kbd> always inserts a newline, and <kbd>Ctrl</kbd>+<kbd>Enter</kbd>... makes <kbd>Enter</kbd> do nothing?

**Comment by FrayxRulez** [comment]
Push notifications are handled by the system and there's no way we can change the keyboard behavior there

**Comment by MarcAnt01** [comment]
Yep, template used by Unigram with two toasts can't trigger one of the two buttons with enter, already sent a request to Microsoft to change this behaviour

**Comment by MarcAnt01** [comment]
As for the link section, you can open a new ticket, so that we can keep track of it separately
