### ISSUE TITLE
wrong message while deleting a contact

### ISSUE THREAD

**Issue by amirso94** [UnigramDev/Unigram#752]
hi
when you wanna delete a contact it shows this message " are you sure you want to delete this chat? "
but it should shows " are you sure you want to delete this __contact__? "
it's a bit confusing at first time, please fix it.
thanks

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/f0d1bcf120c08a63b207746f69e8af5711e7f162
