### ISSUE TITLE
[Feature] Windows Hello protection

### ISSUE THREAD

**Issue by DjArt** [UnigramDev/Unigram#758]
That's nice feature. When sensors like fingerprint or Iris is available, user can use it. When it's not available, user can use own pin-code or password from MS account.

**Comment by FrayxRulez** [comment]
If you enable the passcode lock then you will have "Unlock with fingerprint" option

**Comment by larsschellhas** [comment]
Maybe it would be better to activate the option for Windows Hello directly, but force to set a passcode if none is set yet?

**Comment by FrayxRulez** [comment]
I prefer to keep the UX the same as the official Telegram apps
