### ISSUE TITLE
Auto-play gifs in instant view

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#760]

**Comment by LookedPath** [comment]
Any word on this? The fact that GIFs don't autoplay is super annoying because it's impossible to see their content.

**Comment by MarcAnt01** [comment]
> Any word on this? The fact that GIFs don't autoplay is super annoying because it's impossible to see their content.

Agree, but we just have to wait. The dev has little time to work on Unigram atm

**Comment by FrayxRulez** [comment]
This is done
