### ISSUE TITLE
Graphic bug with system alerts

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#762]
![image](https://user-images.githubusercontent.com/43090263/46210537-4304c500-c331-11e8-8b93-b162e8374605.png)

Started happening with 2.1.1729

**Comment by larsschellhas** [comment]
I don´t see it?. What do you mean?

**Comment by FrayxRulez** [comment]
What's the bug?

**Comment by larsschellhas** [comment]
The dialog being light, but Unigram being dark, I guess

**Comment by MarcAnt01** [comment]
Yep and blur shit

**Comment by larsschellhas** [comment]
Ah yes, it should be dark, too.

But it isn´t blured. But, it would look nice, I think 🤔

**Comment by MarcAnt01** [comment]
I don't know if it's wanted, but the blur in the picture is awful

**Comment by FrayxRulez** [comment]
There isn't any blur

**Comment by MarcAnt01** [comment]
So, what's the background? After the alert appears it tends to white😐

**Comment by FrayxRulez** [comment]
Somehow fixed in https://github.com/UnigramDev/Unigram/commit/74d559f569a2c8ce6f93f58bde6c27f83538720c
This will now happen only if you change in-app theme without closing and reopening it, created a more generic ticket here: https://github.com/UnigramDev/Unigram/issues/806

**Comment by MarcAnt01** [comment]
Restarted happening with 3.4.2153

**Comment by FrayxRulez** [comment]
This happens when you switch theme in the app without closing and reopening it
