### ISSUE TITLE
Collapsed panel doesn't expand when going to settings, calls, contacts

### ISSUE THREAD

**Issue by dmnmsc** [UnigramDev/Unigram#766]
Was working on previos version, not in .1731 

![image](https://user-images.githubusercontent.com/8472142/46230515-1c628080-c369-11e8-8458-e1dd543683ba.png)

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/414163ac4b951b64ad2c04bd14984cf789274a87
