### ISSUE TITLE
Round video message form factor while being played

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#770]
Now the round video messages are rounded only before being played

**Comment by FrayxRulez** [comment]
This is actually a limitation in the UWP platform, it doesn't seem to be possible to render the video round

**Comment by MarcAnt01** [comment]
Is it possible to adapt the square to the theme? I use dark theme and having it light is a pain in the ass

**Comment by FrayxRulez** [comment]
no, that's not a square, it is the video itself

**Comment by MarcAnt01** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/582c071da5905c2b0733812269bbadd023d68392
