### ISSUE TITLE
Title doesn't disappear in compact mode

### ISSUE THREAD

**Issue by mikekosulin** [UnigramDev/Unigram#772]
![image](https://user-images.githubusercontent.com/6089872/46255620-d5c77000-c4a7-11e8-8817-c418f8ace4c6.png)

Unigram: 2.1.1731
Windows 10 Pro (Build 17134.185)
Resolution 2560x1440 (125%)

**Comment by larsschellhas** [comment]
duplicate of #707 
It got fixed in the code 18 hours ago
