### ISSUE TITLE
My People color is white even though the one set from Unigram is dark

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#773]
System accent is not even working

**Comment by FrayxRulez** [comment]
Somehow fixed in https://github.com/UnigramDev/Unigram/commit/74d559f569a2c8ce6f93f58bde6c27f83538720c
This will now happen only if you change in-app theme without closing and reopening it, created a more generic ticket here: https://github.com/UnigramDev/Unigram/issues/806
