### ISSUE TITLE
Bad grouping by month in shared media page

### ISSUE THREAD

**Issue by Stefano-BS** [UnigramDev/Unigram#775]
On ver 2.1.1751 if I go to the shared media page of any chat (both single chats or groups), elements are grouped inside the correct month, but if a month has a lot of media shared, they get splitted into n sections of the same month

**Comment by FrayxRulez** [comment]
This is a limitation in the UWP platform, adding items to an already visible group causes a Catastrophic failure

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/66150617039162cd3f17b2db4876501750a79a09 by removing grouping.
