### ISSUE TITLE
Dont work socks 5

### ISSUE THREAD

**Issue by mohammadraufzahed** [UnigramDev/Unigram#777]
i cant connect tor socks proxy

**Comment by FrayxRulez** [comment]
If you're running the proxy on your PC (localhost/127.0.0.1 and so on) you must enable local loopback for the app: https://docs.microsoft.com/en-us/windows/iot-core/develop-your-app/loopback#enabling-loopback-for-a-uwp-application

**Comment by mohammadraufzahed** [comment]
Thankful
