### ISSUE TITLE
1761 breaks long messages in chat view preview and link one 

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#778]

**Comment by FrayxRulez** [comment]
@MarcAnt01 Non ho capito

**Comment by MarcAnt01** [comment]
Quando avvicini il cursore sulla chat nei messaggi non letti o nei link, non mostra più un piccolo pop up col testo del messaggio o l'url come avveniva prima

**Comment by MarcAnt01** [comment]
Come non detto, ho provato a reinstallare Unigram e si è sistemato
