### ISSUE TITLE
profile pictures in a chat

### ISSUE THREAD

**Issue by morenj96** [UnigramDev/Unigram#781]
Size of profile (or group, channel) picture has changed. It has smaller size now; However name of User (or group, channel) and it details below line of it, have previous size.
It made imbalance in size of profile and size of name and details.
There is this problem on Mobile, not PC.
Please resize it.

version 2.1.1761
OS 15063
5.7" scale 150%

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/4262ce970248176968dcfba2d674dda3162729e5
