### ISSUE TITLE
The application freezes briefly when Windows accent color changes

### ISSUE THREAD

**Issue by majid-vaghari** [UnigramDev/Unigram#784]
If you set Windows to automatically pick the accent color from background (In colors settings), the accent color would change every time the background color changes (if you've set your background color to slide show). The sudden change of Windows accent color will cause the Unigram app to freeze for a second, then its color changes and it continues to run smoothly.
I think this is a bug which is related to the way the app renders itself.

**Comment by FrayxRulez** [comment]
All the UWP apps are rendered by the UWP framework itself, and most of them freeze when switching theme from system settings. The same won’t happen if you switch it from the in-app setting (as a demonstration that the freeze isn’t in the app itself, but most likely in the host)

**Comment by majid-vaghari** [comment]
I just tested this.
When the accent color changes I can keep typing in the Windows settings app. It doesn't freeze. Everything works normally. But in the Unigram app as soon as the background changes I cannot type anything for more than 2 seconds. This doesn't appear to be normal.

**Comment by FrayxRulez** [comment]
Can you explain me how to set the background color to slide show?

**Comment by majid-vaghari** [comment]
Go to Settings > Personalization > Background.
Select _Slideshow_ as background. You can choose your slide albums and other related settings.

Then go to Settings > Personalization > Colors.
There's a checkbox "Automatically pick an accent color from my background". Make sure it's checked.

Now open Unigram. Go to settings > appearance.
There's a checkbox "Use system accent color". Make sure it's checked.
This will make Unigram change certain colors according to Windows theme and accent color.

Now just wait for the background color to change. Consequently, it will change Unigram's appearance.
If you were typing a message in a chat before this exact time. You will notice that the UI temporarily freezes for a moment. After that all the characters that you've typed will show and the app will work smoothly.

**Comment by FrayxRulez** [comment]
I see. I did some UI profiling and there's nothing weird happening: both layout (where I have some control on) and rendering (that's totally platform dependant) aren't doing anything unusual/slow.

I'd like to do some CPU profiling as well, but Diagnostics Hub isn't working for some reason.

**Comment by FrayxRulez** [comment]
(Just to be perfectly clear: the app doesn't handle the theme switch in any way, this is fully handled internally by UWP framework)

**Comment by majid-vaghari** [comment]
I understand that the app doesn't do anything about the theme switch. But do you confirm that once the theme changes, the app freezes for about 1-2 seconds? 😄

**Comment by FrayxRulez** [comment]
Yep, I said this in the first comment, and that's why I didn't close the ticket. 
I'm quite sure that this depends on how much elements in the view are using the accent color.
If you try, by example, to add a new account/go to the login screen, where here are just a couple of elements, the theme switch is quite immediate.

**Comment by FrayxRulez** [comment]
(Feel free to write me on [Telegram](t.me/frayxrulez) btw)

**Comment by FrayxRulez** [comment]
I'm closing this as this is a a Windows wide problem, and not an app-specific issue.
This said: you can try to change theme within the app and from system settings, and you'll notice that in the first case the change is nearly instant, while in the second one all the UWP apps (Settings included) will freeze for some instants.
