### ISSUE TITLE
play gifs in a loop when opened in fullscreen

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#785]
Most of all the fantastic gifs in the world provide their magic by being played in a endless loop. 
In Unigram they do so, too, as long as you don´t open them Fullscreen (clicking on them while gif-autoplay is enabled).
Please replay the gifs therefore in a loop, when they are opened in fullscreen.

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/9599c84cba74fb496a210dfe465dcf53a352de3f
