### ISSUE TITLE
Check if gif is already playing, before opening it in fullscreen

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#786]
If you have gif-autoplay enabled, it might occur that some gifs don´t play directly (but are blurry an show the GIF-Button) and you need to move the view up and down a bit so that they start to play.
But when you click on the gif-Button it opens directly in Fullscreen, which would be not, what you probably wished for.

Therefore please check if the gif is already playing in its message-sized windows, before you open it in Fullscreen.

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/05cdd34d5bde0ebfd8c7d7dfc5e47ca3c6240605
