### ISSUE TITLE
"add admin" permission toggle in the admin settings of the creator is shown as "off"

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#787]

**Comment by larsschellhas** [comment]
....
If you create a super group and go to the admin information of yourself (creator) the permission toggle to add admins is shown as "off". Though you are able to add new admins.

**Comment by MarcAnt01** [comment]
Sure, I've just pointed out a bug on how it is displayed

**Comment by larsschellhas** [comment]
Sure you did :) 
I would simply welcome it, if the issues contain more specific information, so that it becomes clear just from the title what exactly the problem is and in the text where and when exactly it occurs. 😊

**Comment by MarcAnt01** [comment]
Yep, I'm not very good at explaining issues both in my native language and in English😂

**Comment by larsschellhas** [comment]
Haha :D Yes, and obviously I make mistakes, too^^
