### ISSUE TITLE
Application defection for cache memory usage

### ISSUE THREAD

**Issue by morenj96** [UnigramDev/Unigram#788]
When I've written some lines in a chat, and I use multitasking, after returning to the app (and I want to see my write as draft), I see all of Enter Spaces (that used for writing in next line) have been deleted. 🙁
And my sentences in each line mixed with previous and next lines sentences.
This issue found in new version (2.1.1761), there wasn't it in 2.1.1731

**Comment by dmnmsc** [comment]
@morenj96 It happens as well when you just switch chat

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/3acacd66c590b7f5c1a7e7cb71eb5a02290999b7
