### ISSUE TITLE
Passcode required after log out

### ISSUE THREAD

**Issue by majid-vaghari** [UnigramDev/Unigram#789]
After I've enabled local passcode I logged out of my account.
Now when I open the app it requires passcode. After I enter passcode I see the first page which allows me to log in again.
This is a bug. Local passcode should be deleted on log out or even when the session is closed by server.

**Comment by MarcAnt01** [comment]
You can't call a bug something that hasn't been implemented yet, anyone added enhacement label, as yours is a good suggestion

**Comment by majid-vaghari** [comment]
Well, this should be standard behavior.
I don't expect the app to require pass code when no account is logged in 🤷‍♂️
