### ISSUE TITLE
i need update 

### ISSUE THREAD

**Issue by pohapada** [UnigramDev/Unigram#79]
Why don't update????

**Comment by ikarago** [comment]
We're working on updates for the app. Please be patient, and if you really need the updates in the meantime you can always follow the instructions on the main page of this GitHub to build your own version from the newest development-code.

**Comment by pohapada** [comment]
Tanks for your  group

**Comment by Alexmitter** [comment]
@pohapada Many Tanks back

**Comment by pohapada** [comment]
Please complete the sticker place or change the this sticker 😂😂😂😅

**Comment by Alexmitter** [comment]
@pohapada We had a hard time to find the best sticker we could deliver, this sticker is good for every situation. A Full Sticker Panel will comming Soon(TM)

**Comment by pohapada** [comment]
...and,please add (on/off) for send by enter.😉

**Comment by mohsens22** [comment]
@pohapada داداچ بسه دیگه گاییدی !!!

**Comment by FrayxRulez** [comment]
@mohsens22 PORCODDIOOOOOO
