### ISSUE TITLE
Right click/long press for "save as/open in) in gif full screen view as it is already in photo one

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#793]

**Comment by FrayxRulez** [comment]
Marking as blocked as the media player prevents the context menu from showing up

**Comment by MarcAnt01** [comment]
Gotcha, but why the behaviour changes with photos? All right, there

**Comment by FrayxRulez** [comment]
Uhm, because there isn't any media player when you open a photo
