### ISSUE TITLE
Disable pointer, while using keyboard

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#797]
This feature would be very important for laptop users, in fact by typing I sometimes open other chats, by placing the hand on touchpad

**Comment by FrayxRulez** [comment]
UWP doesn’t support disabling touchpad. 
I doubt there’s actually any existent app (including win32 ones) that disables the touchpad as you type

**Comment by MarcAnt01** [comment]
All Microsoft Office Suit, does, anyway, if not supported by uwp, no problem

**Comment by FrayxRulez** [comment]
I doubt it’s actually the Office suite. Sounds more like some driver feature.

**Comment by FrayxRulez** [comment]
Yep, it’s a drivers feature: https://www.google.it/search?q=disable+touchpad+while+typing&ie=UTF-8&oe=UTF-8&hl=en-it&client=safari

**Comment by MarcAnt01** [comment]
Oh, OK, anyway Office function is better as it disables the pointer at all and not only the accidental touches
