### ISSUE TITLE
Picture preview via notification (only with Unigram open)

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#799]

**Comment by Stefano-BS** [comment]
If possible, not like Telegram X for android does (image preview only if there is only one message notified)

**Comment by FrayxRulez** [comment]
This isn't possible as TDLib doesn't get executed when a notification is received

**Comment by MarcAnt01** [comment]
So, why in Telegram X is working? I thought it was a UWP limitation, but I've noticed that new RS5 capture tool had screenshot preview

**Comment by FrayxRulez** [comment]
Telegram X doesn't use push notifications and it is always executed in background: every time a new message is received the code executed to show a notification is the same as the app is being executed.

Unigram differs in this, as while the app is closed no code is running, and push notifications are triggered directly on the device by Telegram push servers.

**Comment by MarcAnt01** [comment]
Very clear, thank you

**Comment by FrayxRulez** [comment]
So this is probably doable, but only in notifications generated while the app is open, I don't know if it would worth to

**Comment by MarcAnt01** [comment]
Due to calls not integrated with system, I always keep Unigram open and I think it's what most people do

**Comment by FrayxRulez** [comment]
Yeah it actually makes sense on PC

**Comment by FrayxRulez** [comment]
Blocked as currently there's no APIs to update a specific notification content (as the download should be async) and simply replacing it seems to fail hard when download is too fast

**Comment by xperiandri** [comment]
@FrayxRulez, but as you decided to go away from VoIP host process and you implemented app launch at startup. Then, as far as I know, the app can handle push-notifications itself, isn't it?
I mean that it can intercept push-notification received by the system, then get info from it, go to Telegram server for additional data and display a new notification itself.
Am I wrong?

**Comment by MarcAnt01** [comment]
> So this is probably doable, but only in notifications generated while the app is open, I don't know if it would worth to

Hey, now that the app can run in background allowing in-app notifications to work with the window closed, can you consider implementing that?
