### ISSUE TITLE
Auto-locking sometimes won't work on PC

### ISSUE THREAD

**Issue by CodersGit** [UnigramDev/Unigram#801]
I guess, it happens when app is suspended by system because it happend always when I was on another desktop or my computer was locked (in last case works only 1 minute auto-locking, 5 mminute and more won't.
System: Windows 1803

**Comment by MarcAnt01** [comment]
Does that still happen?

**Comment by FrayxRulez** [comment]
@MarcAnt01 Yes

**Comment by CodersGit** [comment]
It seems like it was fixed
