### ISSUE TITLE
Problems in hiding caption in photo viewer on Windows 10 Mobile

### ISSUE THREAD

**Issue by morenj96** [UnigramDev/Unigram#805]
- Open a picture in Unigram. (you'll see picture comment is visible)
- touch the screen to hide comment.
- touch again to reshow picture comment. (here, you'll see comment become visible for a moment and it will been hidden immediately)

Unigram 2.1.1818 (happens only on Mobile)

**Comment by MarcAnt01** [comment]
Unable to reproduce

**Comment by morenj96** [comment]
@MarcAnt01 Why?
It isn't exist in previous versions

**Comment by dmnmsc** [comment]
@MarcAnt01 I can reproduce on mobile. And it's a pain on videos because you can't go forward or rewind

**Comment by MarcAnt01** [comment]
@dmnmsc @morenj96 OK, so happens in mobile only, because on PC I cannot reproduce

**Comment by MarcAnt01** [comment]
There are no APIs to fix it on Mobile so far

**Comment by morenj96** [comment]
@MarcAnt01 It doesn't need to fix, when in previous versions all thing were good.
So it's able to return viewer codes to previous versions

**Comment by MarcAnt01** [comment]
What was the latest version with it functional?

**Comment by morenj96** [comment]
@MarcAnt01 I think it was version 2.1.1778

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/f42e3306b1e8c78d02ea9ab43bc823a47a59726c

**Comment by MarcAnt01** [comment]
Reopened as mobile users reported that bug continues also with the fix

**Comment by MarcAnt01** [comment]
Closing, since mobile support has been dropped
