### ISSUE TITLE
Useless "Return to call" message on top of chats while call pop up is open

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#808]

**Comment by FrayxRulez** [comment]
It's useful when you close the popup

**Comment by MarcAnt01** [comment]
So, can you disable it when the pop-up is open?

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/63c0238c8723240dd95a918e310bec9ef87803eb
