### ISSUE TITLE
Fit videos (and maybe pictures) to the window/screen size, even when their resolution is smaller

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#813]
If you use your PC screen or your high dpi mobile device to watch a video you don´t want it to be smaller than the window, because that´s just wasted space. And although the quality might not be good enough to embrace the high resolution of your PC or phone, you probably still want to have it Fullscreen instead of being so small that you have to hold right in front of your face.

PC - not maximized window
![image](https://user-images.githubusercontent.com/14281234/46827114-7ec37400-cda0-11e8-8155-98d553b5176b.png)

PC - maximized window
![image](https://user-images.githubusercontent.com/14281234/46827322-03ae8d80-cda1-11e8-9515-7c20a2e09379.png)

Mobile
![image](https://user-images.githubusercontent.com/14281234/46827426-3a84a380-cda1-11e8-8f8c-0ac874a3b1bb.png)

Therefore I would suggest to stretch videos and maybe even pictures to the full screen size.

**Comment by FrayxRulez** [comment]
You can now zoom pictures and videos so I'm closing this
