### ISSUE TITLE
Improve animation of messages when entering selection mode

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#814]
When you enter the selection mode in a chat, the selection boxes appear on the left. Because they need some space, the received messages are moved a little bit to the right, using an animation. While this works beautifully, the same animation is active on the send messages, which are on the right side.
This results in the send messages "jumping" a little bit to the left, just to move animatedly to the right again.
Actually the send messages would only need to adapt to the possible width, which might be affected in a very thin window.
The same adaption occurs to the received messages, too, of course. But it seems like that the adaption to the new width occurs instantaneously instead of being animated at the same duration as the movement. This results in a "jump" of the right side of the message.

**Comment by FrayxRulez** [comment]
Animation is provided by the system and there's no way to customize it

**Comment by larsschellhas** [comment]
Damn it!
Which kind of animation did you use? 
I´ll open a ticket for it then 🙈

**Comment by FrayxRulez** [comment]
I didn't used any animation, that's the default behavior when turning on multiple selection

**Comment by FrayxRulez** [comment]
`ListView.SelectionMode = SelectionMode.Multiple;`

**Comment by FrayxRulez** [comment]
I doubt they will do anything regarding, it's this way since first Windows 10 release, and I doubt no one noticed it.

Also, this kind of animation it's a limitation of the UWP framework itself
