### ISSUE TITLE
Suggestions for additional animations

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#816]
These are some suggestions for new animations, which could be used to add a more fluent feeling of the UI. Of course these are just suggestions and I don´t really now, which even could be implemented, but I hope to give you some ideas! I´ll add more ideas, when I encounter them 😄 

### Edits to this issue
- 12.10.2018: Added "Pinned Message" section

### Group-, Secret-Chat- & Channel-Creation
The creation dialog opens with an swipe in from Bottom to top (I guess, it´s the "page refresh" page transition - good choice!), but the title bar part above the dialog appears instantaneously. I would suggest to move it in from bottom to top with the rest of the page if possible or maybe just fade in (maybe everything together). The same goes for all steps of the creation process. Though I would suggest to use the "horizontal slide" page transition between the single steps of the creation process, since they follow up on each other. 

#### Sticker Panel
Add an opening animation to the sticker panel as is already present in the send file panel (similar to context menu). At min-width the message-field could move up and "reveal" the sticker panel.

#### Open a chat 
Right now the chat just appear, including the chat top bar, pinned message and messages. When there is no chat open, yet, it might be smooth if:
- chat top bar would be swiped in from top (including existing pinned message) or if
- chat top bar would fade in.
The messages could fade in, too. Of course it shouldn't be too slow, because you don´t want to loose to much time.
I guess this would mostly match the "page refresh" page transition.

Though I would prefer another way, where you could to swipe in the whole chat frame from the left, because it "comes" from the chat list. That way you could swipe it out to the right, when another chat is opened. This is represented by the "horizontal slide" page transition. And when using the back-button you could reverse the slide direction.

#### Entering multi selection mode
The multi selection mode has already one nice animation - the number of marked messages. I would suggest the same animation to swipe in all symbols of the multi selection bar. Additionally I would suggest to swipe & fade out the normal chat top bar to the top. And I´d like you to add the same behaviour to the old/disappearing count of messages.
Another option would be to swipe out the disappearing elements to the bottom or top and fade in the new elements.

#### Using multi selection mode
Could you add the same fade-in animation for the marked message background as is used for the background of a selected chat in chat list and search?

#### Chat profile page
I would suggest to use the "drill" page transition when opening the chat info, since you are "drilling" deeper into the chat info. You could use a connected animation for the profile picture, name and status ("recently seen, etc....") to move them to the chat info page, too, which would add a nice effect to that and makes space for the "Info" title.

#### Pinned message [added on 12.10.2018]
I would suggest that when you close a pinned message that it swipes up and out. I think you could maybe use the [EdgeUIThemeTransition](https://docs.microsoft.com/de-de/windows/uwp/design/motion/xaml-animation#showhide-edge-ui
) to achieve that.
If a new pinned message is added you could swipe out the old one to the top and swipe in the new one from the top - this will of course draw some attention to the pinned message, but that´s what the pinned message is for after all, I guess.
Because of that you might even think about swiping the pinned message always in from the top when entering the chat.

**Comment by MarcAnt01** [comment]
@larsschellhas something when picture gets closed by swiping up?

**Comment by FrayxRulez** [comment]
I'm closing this as I added a bunch of animations already
