### ISSUE TITLE
Add a button to open windows keyboard on desktop (use smilies)

### ISSUE THREAD

**Issue by dmnmsc** [UnigramDev/Unigram#82]
I miss a button on dekstop build to open the windows keyboard and use smilies.

**Comment by ikarago** [comment]
@gxsaurav Can you create a mockup for a stickers panel with integration from GIFs and a link to the soft keyboard emojis?

**Comment by FrayxRulez** [comment]
Actually it is not possible to show up emoji keyboard from code

**Comment by FrayxRulez** [comment]
Implemented emojis panel in https://github.com/UnigramDev/Unigram/commit/a0560413a837fbf7b800dbe6e034b8e634e349d0
