### ISSUE TITLE
Sticker pack preview box not showing recently added stickers

### ISSUE THREAD

**Issue by RubeensVinicius** [UnigramDev/Unigram#821]
On every Telegram client, when you add new stickers to a pack, it takes some time for them to be added to your sticker panel. But, on the official ones, a reliable way to test a sticker before it's loaded for everyone is to click on any sticker from pack to open the preview box. This box is always updated with the newest ones on the other clients, but not on Unigram.

Is it possible to make this behavior consistent with the other clients?

**Comment by FrayxRulez** [comment]
Hi, at the moment TDLib doesn't support forcing a refresh of a sticker pack, so there is no way I can fix this at the moment.
I've informed TDLib creators about the limitation and they're looking for a solution.
I'm going to close this ticket as "blocked", but I'll keep this up to date in case of any news.
