### ISSUE TITLE
Hearth emoji issue

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#823]
With earth emoji inserted by Windows Emoji panel, I can't see the associated stickers, but if I insert the earth emoji from emoji-app section it works

**Comment by FrayxRulez** [comment]
Because the one provided by Windows keyboard isn't the classic heart emoji:
The one commonly used by any operating system is `U+2764, U+FE0F`, but Microsoft rather uses `U+2764` only

**Comment by MarcAnt01** [comment]
Microsoft is always Microsoft
