### ISSUE TITLE
Bubble interface for people when adding them to create a new group

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#825]
![image](https://user-images.githubusercontent.com/43090263/47099949-ae59fc80-d236-11e8-9c31-529678157a77.png)

**Comment by FrayxRulez** [comment]
This quite depends on the platform where you are. Windows and iOS usually display basic text in this situation (just check the email composer)

**Comment by MarcAnt01** [comment]
Oh, haven't thought about that, but for example when I want to create a new group and add people, I see that part is bugged on Unigram, it makes confusion with columns and with the text
