### ISSUE TITLE
"Open in browser" instead of "Open in" in instant view

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#826]
As Windows 10 has a default browser, I think this text for the button would be more clear

**Comment by FrayxRulez** [comment]
I don't have the copy for this

**Comment by MarcAnt01** [comment]
What do you mean?

**Comment by FrayxRulez** [comment]
I don't have "Open in browser" string, just "Open in..."

**Comment by MarcAnt01** [comment]
So, I guess that would be bad for translationns
