### ISSUE TITLE
Missing "forward message" dialog when adding a person to a normal group

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#827]

**Comment by FrayxRulez** [comment]
Is there any telegram client that still have "forward messages" dialog?

**Comment by MarcAnt01** [comment]
Mmmmmmm
![image](https://user-images.githubusercontent.com/43090263/47238996-46491900-d3e4-11e8-94f8-837a2b87a856.png)
![image](https://user-images.githubusercontent.com/43090263/47239009-53660800-d3e4-11e8-8e71-64547d25957b.png)
Both Telegram and Telegram X

**Comment by FrayxRulez** [comment]
I'm not going to add this feature as it is sorta deprecated (Telegram Desktop and iOS apps aren't showing it, and it is quite useless in my opinion)
