### ISSUE TITLE
New message box context menu conflicts with text corrections context menu

### ISSUE THREAD

**Issue by xperiandri** [UnigramDev/Unigram#832]
If you type incorrect word in Skype then you will see that text corrections context menu is displayed on top of custom context menu
![image](https://user-images.githubusercontent.com/2365592/47236116-d2a70c00-d3e3-11e8-9034-ee8f8fc8f961.png)

But in Unigram it appears on top of custom
![image](https://user-images.githubusercontent.com/2365592/47236170-fb2f0600-d3e3-11e8-8870-664397988459.png)
And does not appear at all with **Application** keyboard key.

**Comment by FrayxRulez** [comment]
I have no idea about how Skype manages to do that. There isn't any API to handle spellcheck context menu

**Comment by FrayxRulez** [comment]
Oh well, I got how the problem has been solved in Skype: that context menu isn't custom at all...

**Comment by MarcAnt01** [comment]
@FrayxRulez placing it on the right of the copy/paste dialog?

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/6d7345ad0bae030c21557eaaa373959349047a9e

**Comment by xperiandri** [comment]
Text correction menu item no longer appear at all

**Comment by MarcAnt01** [comment]
> Text corrections menu item no longer appear at all

Spell checker has been removed

**Comment by xperiandri** [comment]
Why?
