### ISSUE TITLE
Little graphic bug when pausing a gif

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#836]
![image](https://user-images.githubusercontent.com/43090263/47270920-e6cd4380-d572-11e8-9591-83d79a2a6f30.png)
(the volume ui has nothing to do with that problem, just pressed it accidentally when taking the screenshot)

**Comment by FrayxRulez** [comment]
Maybe some detailed repro steps could be helpful...

**Comment by MarcAnt01** [comment]
You are right, play a gif full screen and pause with space bar

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/f42e3306b1e8c78d02ea9ab43bc823a47a59726c
