### ISSUE TITLE
Esc must not work (close chat) in hosted view

### ISSUE THREAD

**Issue by xperiandri** [UnigramDev/Unigram#839]

**Comment by MarcAnt01** [comment]
Hosted view?

**Comment by xperiandri** [comment]
People App

**Comment by MarcAnt01** [comment]
By pressing esc you can open mail or use other app that synced with that contact

**Comment by xperiandri** [comment]
@MarcAnt01, no, this is what happens with Esc
![image](https://user-images.githubusercontent.com/2365592/47366398-46982b80-d6e6-11e8-9446-7ae301b76d81.png)
Just blank view like in Unigram main window.
Which is weird in Unigram main window too. Why would I close it at all with Esc?
I even can't dismiss context menu with Esc because it closes chat!

**Comment by MarcAnt01** [comment]
Oh, true reproduced now, weird, as "esc" should have the same behavior as back button

**Comment by xperiandri** [comment]
Well, it must depend on screen size and displayed items

**Comment by MarcAnt01** [comment]
Seems it happened to me just one or two time, while in the other situations it's OK

**Comment by FrayxRulez** [comment]
Fixed, can't link a commit as the code where this is located isn't part of the repository
