### ISSUE TITLE
See "last seen"/ status in hosted view (People App)

### ISSUE THREAD

**Issue by xperiandri** [UnigramDev/Unigram#840]
Add a bar with **last seen** info on top of Peaople App hosted view

**Comment by HammyHavoc** [comment]
Would absolutely love to see this come to Unigram.

**Comment by FrayxRulez** [comment]
Closing this as My People is getting removed in 19H1

**Comment by Tirraon** [comment]
@FrayxRulez I am not sure, but where it was official information, that My People will be removed in 19H1?

**Comment by FrayxRulez** [comment]
https://twitter.com/thebookisclosed/status/1073316790770515970
