### ISSUE TITLE
Notification count on live tile, task bar icon and lockscreen is not updated

### ISSUE THREAD

**Issue by larsschellhas** [UnigramDev/Unigram#842]

**Comment by FrayxRulez** [comment]
Tile has been fixed here: https://github.com/UnigramDev/Unigram/commit/42429aab3c9d14c2f7c6f41f289abec349745716.
However, badge counter can't be fixed as this information isn't included anymore in Telegram push notifications.

**Comment by mautheus** [comment]
@FrayxRulez 🙌🏻
