### ISSUE TITLE
Swipe up to close gallery broken in 2.3.1929

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#844]
It's broken just for photos, with video and gifs are OK

**Comment by MarcAnt01** [comment]
The swipe is broken just in the picture area, the gesture works through blank area around the picture

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/a97a518b1f6d1e01396ca71dd6393059d2b56ebe
