### ISSUE TITLE
Bug for long press over photos/videos/GIFs

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#845]
When the long press menu appears the gif is opened at full screen

**Comment by FrayxRulez** [comment]
Wasn't happening before swipe to reply?

**Comment by MarcAnt01** [comment]
I don't remember, it you send me an older .appx I will test

**Comment by MarcAnt01** [comment]
Doesn't happen with versions prior to the introduction of swipe to reply

**Comment by FrayxRulez** [comment]
Then I will have to remove swipe to reply once again

**Comment by morenj96** [comment]
@FrayxRulez It will Good job Fela 👌

**Comment by FrayxRulez** [comment]
This is fixed
