### ISSUE TITLE
Implement back button as Microsoft Store

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#847]
This would offer a better usability in Tablet Mode for big tablets of PCs in fact because of gestures lack and of big screen I have to move the hand to bottom left part every time

**Comment by MarcAnt01** [comment]
Taken from Microsoft site, this should be the newer version of back button https://docs.microsoft.com/en-gb/windows/uwp/design/basics/navigation-history-and-backwards-navigation
Hope it can be helpful

**Comment by FrayxRulez** [comment]
I quite dislike the idea to have in-app back button to be honest. It would just make everything much more complex to handle and it would take space from the content area...

**Comment by MarcAnt01** [comment]
Yes, I understand, but the interaction with tablets would be another thing with it😜

**Comment by FrayxRulez** [comment]
It would be a problem especially with popups, as it won't be possible to show the button over them

**Comment by MarcAnt01** [comment]
Added in https://github.com/UnigramDev/Unigram/commit/6863a72a106d937219093e5b88da49723a50f5bb
