### ISSUE TITLE
Unable play preview for existing GIFs and lag display received GIF messages.

### ISSUE THREAD

**Issue by vboxpro** [UnigramDev/Unigram#851]
Unigram
1. Chat window "GIF" storage area, unable play existing GIF animations (only display as images)
![screenshot_96](https://user-images.githubusercontent.com/37661865/47599402-4906b980-d962-11e8-957d-97b80180e37b.png)

2. No easy option for search new GIF animations by word as on Telegram.
3. Received GIF animation messages from friends difficult play instant as on telegram. take bit time (kind of lagging) 

note: those 1/2/3 works properly on official telegram desktop and apps.

please do not add directx facility to unigram for any development reason. so we cannot be install app on env like virtual machines.

**Comment by larsschellhas** [comment]
2. Just type @gif and search for words.

**Comment by MarcAnt01** [comment]
1. already covered by https://github.com/UnigramDev/Unigram/issues/669
2. as @larsschellhas said
3. unable to reproduce the lags
