### ISSUE TITLE
Draft resets caret position when app gets resumed

### ISSUE THREAD

**Issue by morenj96** [UnigramDev/Unigram#856]
![wp_ss_20181028_0006](https://user-images.githubusercontent.com/19172238/47618370-5dc08a00-dae7-11e8-8f27-528ee9c811e9.png)
![wp_ss_20181028_0005](https://user-images.githubusercontent.com/19172238/47618371-5dc08a00-dae7-11e8-91cc-00059a3170be.png)

When I typing in middle line, then use multitasking, after returning to the app, I see the sign of type is in after latest word (in my sentence)

**Comment by FrayxRulez** [comment]
I can't really understand...

**Comment by morenj96** [comment]
@FrayxRulez When I written 2 lines, and I returned to first line and typing, then use multitasking, after returning to the app, I see location of the blinker sign of typing (I don't know it name) changed and it located in after the latest word, not in the first line

**Comment by bugada** [comment]
Yes Fela, on mobile when you move the textbox cursor in a position different to the last endline, after resuming the app, but only the first time, the cursor is placed at end of last line, like when you tap on the textbox.

**Comment by FrayxRulez** [comment]
That’s because after resume the text most likely comes from the draft

**Comment by bugada** [comment]
Probably, or the message box receives focus.
But what's strange, it happens only the first time you resume the app. The the cursor remain in its original position.

**Comment by bugada** [comment]
Ah fela sorry, it happens only if you change something in the text, then after position the cursor is at the end of the message. If you don't change anything thenpostion won't change. So as you told, is related to the draft saving
