### ISSUE TITLE
My People windows can't open CompactOverlay windows

### ISSUE THREAD

**Issue by xperiandri** [UnigramDev/Unigram#857]
Pressing on in-chat call button in a hosted view

![image](https://user-images.githubusercontent.com/2365592/47618443-c73a9b80-dadb-11e8-9879-9657543031c1.png)

opens call popup in a hosted view 

![image](https://user-images.githubusercontent.com/2365592/47618419-9195b280-dadb-11e8-8727-a77247e0a67f.png)

but must activate the main view and do call as usual

**Comment by FrayxRulez** [comment]
I can’t understand what’s the problem

**Comment by MarcAnt01** [comment]
Can you make a screen record of both behaviours as we can't get nothing?

**Comment by FrayxRulez** [comment]
If the overlay gets opened rather than the window it’s because there’s some code check to determine if it is actually possible to open it. Opening the main window to be able to open the call window doesn’t sound as a great plan to me...

**Comment by FrayxRulez** [comment]
Closing this as My People is getting removed in 19H1
