### ISSUE TITLE
Show date when scrolling up

### ISSUE THREAD

**Issue by Tourniquet88** [UnigramDev/Unigram#858]
On telegram desktop you can see the date of the current conversation when you scroll up. If you're in a lot of a group chats it can be pretty handy to see the date of the current conversation.

I really miss that feature on Unigram. Please consider to add that in the future. :)

**Comment by FrayxRulez** [comment]
This is sorta complex as the app supports this feature already by deleting this line:
https://github.com/UnigramDev/Unigram/blob/develop/Unigram/Unigram/Views/ChatPage.Bubbles.xaml.cs#L78

The problem, however, is that UWP isn't designed to perform this kind of operations (such as having to calculate the position of the items in the view while they scroll and so on) and the app experience would suffer from this, losing smoothness while scrolling.

**Comment by MarcAnt01** [comment]
@FrayxRulez is it possible to show the date while scrolling has been interrupted and hide it during the scrolling action?
Wouldn't be the best choice, but much better than nothing

**Comment by Tourniquet88** [comment]
![image](https://user-images.githubusercontent.com/20756329/48019858-bcfc4b00-e134-11e8-9dc7-b540bc0f8eac.png)

How about this: You can just add it to the header, so it shouldn't be a problem for performance. You could possibly make it only visible when you scroll up and as soon as the scrolling stopped or you scroll down it disappears?

Maybe that would be a good compromise? 

A different idea would be to make it in general how Skype UWP showed the dates. So you have the date always shown like that in header no matter if you scroll up and down. So this could replace the current date show system.

But I guess you guys want Unigram as close as possible to the desktop version, right?
