### ISSUE TITLE
Pasting files doesn't work

### ISSUE THREAD

**Issue by sprainbrains** [UnigramDev/Unigram#859]
I tried to drop a file into chat. The file dropped but doesn't loading.

![1](https://user-images.githubusercontent.com/10284309/47718434-7781de80-dc59-11e8-98b8-b7188ea89b37.png)

Win 10: 1809
Unigram build: 2.3.1929

**Comment by MarcAnt01** [comment]
Seems that you have been restricted from writing there

**Comment by morenj96** [comment]
@sprainbrains Update to 2.3.1937

**Comment by sprainbrains** [comment]
> Seems that you have been restricted from writing there

It was in my Favorites chat. I checked it with other chats and have the same problem.

**Comment by sprainbrains** [comment]
> 
> 
> @sprainbrains Update to 2.3.1937

![1](https://user-images.githubusercontent.com/10284309/47719308-c6307800-dc5b-11e8-8ce5-44d3f1d13de0.png)

Already. The problem didn't go away.

**Comment by FrayxRulez** [comment]
From where are you dragging files?

**Comment by sprainbrains** [comment]
> From where are you dragging files?

From Windows Explorer

**Comment by FrayxRulez** [comment]
Go to Settings > Click 10 times on the app version > Set Verbosity level to Warning. Then try to send the file again, and send me the log.

**Comment by sprainbrains** [comment]
>  Then try to send the file again, and send me the log


[log1.zip](https://github.com/UnigramDev/Unigram/files/2529728/log1.zip)

I'm trying to paste with CTRL+C,CTRL+P. Drag'n'Drop with a mouse works perfectly.

**Comment by FrayxRulez** [comment]
So you are pasting files, and not drag & dropping them. There's quite of a difference.

**Comment by sprainbrains** [comment]
> So you are pasting files, and not drag & dropping them. There's quite of a difference.

Yep.. It is my mistake. Sorry. 
But copy-paste from Explorer doesn't work.

**Comment by sprainbrains** [comment]
> 
> 
> It is a known issue: the app can't access the file you pasted, so there's no way I can fix this.
> Furthermore I'm marking this as blocked, as I have no idea about how to fix this.

OK(
But on the other hand, the official client cant do it.

**Comment by MarcAnt01** [comment]
@FrayxRulez don't know if helpful, but with this steps I'm able to paste files:
1. Download a file from a Telegram chat/channel;
2. Select "open in folder";
3. Copy
4. Paste

**Comment by FrayxRulez** [comment]
Because those files are in the app folder and the app can access them at any time

**Comment by MarcAnt01** [comment]
>           Because those files are in the app folder and the app can access them at any time

Would be nice to have a "copy" option for those files, so that I can skip the second step tho

**Comment by FrayxRulez** [comment]
I believe I fixed this in https://github.com/UnigramDev/Unigram/commit/5860cb836c807fb4bc3b56510262d95dde3fdca0
