### ISSUE TITLE
Interrupt swiping when the picture is the first one or the latest one

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#863]
Unigram with new gallery doesn't have this behaviour any longer. Happens both with group/profile pictures and with shared media

**Comment by omfgnuts** [comment]
How about cycling from the last one to the first one and vice versa, to avoid being stuck on the first/last image

**Comment by MarcAnt01** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/d0000b383f4870dd7ede6c07d74300209815a1ef
