### ISSUE TITLE
Share invite link is not working

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#864]
Error message: "this app can't share right now"

**Comment by FrayxRulez** [comment]
Add member > Invite by link as in official apps

**Comment by MarcAnt01** [comment]
Right, sorry, I have noticed anyway that "share link" is not working, will edit the issue, mentioning that

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/2f088d6c55841b43c7975b81429a29894b45f49a
