### ISSUE TITLE
Text-photo

### ISSUE THREAD

**Issue by deltapir** [UnigramDev/Unigram#87]
When you want to write a text under a photo you are going to share, the text-box disappear under the keybord. The only way to make that box appears above the keybord is to hide the home/cortana buttons. After that everything works as expected, with the home/cortana buttons visible as well.

**Comment by deltapir** [comment]
It seems this bug is fixed.

**Comment by FrayxRulez** [comment]
Should be fixed in latest build. Can you verify?
