### ISSUE TITLE
People app source filter cluttered by Unigram entries

### ISSUE THREAD

**Issue by adrianghc** [UnigramDev/Unigram#873]
In the People app, you can filter what sources to show contacts from. Unfortunately, the list of sources is cluttered by dozens of entries for Unigram (maybe one of them is added after each app update?). This is on 1803.

**Comment by FrayxRulez** [comment]
This has been fixed in a recent commit. Sadly enough, I can't remove already created entries. You might need to logout and login again in the app.

**Comment by adrianghc** [comment]
I see, thank you very much. So if I do that now, I shouldn't get a new entry when the next update is installed?

**Comment by FrayxRulez** [comment]
It wasn't related to updates, actually, just a setting that wasn't stored properly. Yes, you won't get any more duplicates :) just make sure to have the latest version installed.

**Comment by adrianghc** [comment]
Thank you. Unfortunately, signing out and back in doesn't remove the entries so I guess I will have to reset the app.

**Comment by mautheus** [comment]
@adrianghc
