### ISSUE TITLE
Display badge instead of window screenshot in Task View for secondary views

### ISSUE THREAD

**Issue by xperiandri** [UnigramDev/Unigram#874]
When I opened a few secondary views with chats there is hard to figure out which chat belongs to which user in Task View (Win+Tab). It would be nice to see a badge with his/her picture and name instead of window screenshot.

**Comment by FrayxRulez** [comment]
I doubt this is actually possible...

**Comment by xperiandri** [comment]
Maybe. For Win32 it is possible.
[VSCommands](https://github.com/squaredinfinity/VSCommands) implements this.
I'm not sure about UWP API

**Comment by FrayxRulez** [comment]
UWP apps can't work with windows handles so it isn't possible to use `DwmSetIconicThumbnail`/`DwmSetIconicLivePreviewBitmap` function. (For the same reason, Unigram doesn't have task bar blink when you receive a message)

**Comment by FrayxRulez** [comment]
It's sufficient to check the documentation [here](https://docs.microsoft.com/en-us/windows/desktop/api/dwmapi/nf-dwmapi-dwmseticonicthumbnail): "desktop apps only".
