### ISSUE TITLE
Text size preview isn't working

### ISSUE THREAD

**Issue by Xashyar** [UnigramDev/Unigram#875]
![image](https://user-images.githubusercontent.com/34171942/48033550-f3f05200-e170-11e8-901e-ac13645ef4ea.png)

Resolution: 3820x2160
Scaling: 250%
Tested Version: 2.3.1977

+[Feature Request] I use 200% scaling on the regular app, the current view of Unigram looks too large, is it possible to enable scaling?

**Comment by FrayxRulez** [comment]
This is known, as a workaround you can simply close and reopen the app.

Scaling is supported natively by Windows 10 and by apps designed to run on it (as Unigram is), so you should probably refer to system settings for that.

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/b74e282509fff4ab554fbbd7128d15159ea1e376
