### ISSUE TITLE
Support for "Mouse Wheel Click Scrolling"

### ISSUE THREAD

**Issue by Xashyar** [UnigramDev/Unigram#876]
I also requested this on [tdesktop ](https://github.com/telegramdesktop/tdesktop/issues/5199)which was subsequently closed/ignored.
it could be very useful for navigating long chats or instant views.

Version: 2.3.1977

**Comment by Xashyar** [comment]
@MarcAnt01 not considered a enhancement?

**Comment by MarcAnt01** [comment]
I have to check if uwp has APIs for that, if I don't add labels there's always a reason
