### ISSUE TITLE
Proxy Manager Fails to Detect Proxy

### ISSUE THREAD

**Issue by Xashyar** [UnigramDev/Unigram#877]
![image](https://user-images.githubusercontent.com/34171942/48034710-c35ee700-e175-11e8-92b4-785857091a0f.png)
even though it is easily detected by other apps...
Version: 2.3.1977

**Comment by FrayxRulez** [comment]
UWP apps can’t connect to localhost by default, you should follow this steps: https://docs.microsoft.com/en-us/windows/iot-core/develop-your-app/loopback
(The idea is to had some kind of warning when trying to add a localhost proxy in future releases of Unigram tho.)

**Comment by Xashyar** [comment]
@FrayxRulez 
the provided doc seems to belong to windows iot-core, I couldn't find the provided values in registry, 

> [HKEY_LOCAL_MACHINE\system\currentcontrolset\services\mpssvc\parameters]
>         "IoTInboundLoopbackPolicy"=dword:00000001
is iot-core different form Regular PC windows?

is there a less abusive way (Proxy Sponsored ads) to get this thing use proxies?

does telegram provide official proxies?

**Comment by FrayxRulez** [comment]
You have to check _Enabling loopback for a UWP application_ (Sorry, I thought to have linked that anchor directly).
Unigram package family name (to be passed with `-n` parameter) is `38833FF26BA1D.UnigramPreview_g9c9v27vpyspw`.

**Comment by Xashyar** [comment]
Thanks!
@FrayxRulez 
Since this is a community-oriented dev, do you think it's ethical to leverage ads for giving a simple service like internet access to 3rd to blocked countries?

**Comment by FrayxRulez** [comment]
Proxy ads are delivered by proxies directly through Telegram, and I like to respect their desire. (Telegram earns nothing from those ads, they are managed directly by proxy owners)

**Comment by levlam** [comment]
@Xashyar Of course, there is a choice. They can buy a server and install a private proxy without sponored channel there, or they can try to find a proxy, paid by proxy owner himself, without sponsored channel. The last option isn't free for users also, because they will need to pay their time for finding such proxy and waiting for a slower file downloads. But there can't be a completely free option anyway, because owning a proxy always costs some money. Showing one sposored channel has been chosen as the best way to cover the cost of maintainig a proxy server and at the same time minimally annoy proxy users.

**Comment by Xashyar** [comment]
> 
> 
> Proxy ads are delivered by proxies directly through Telegram, and I like to respect their desire. (Telegram earns nothing from those ads, they are managed directly by proxy owners)

@FrayxRulez

1. I take your silence as not having any answer to this. if so please remove the subtitle "for the Community" you are misusing those words, unless you mean the advertising, data mining community :)

2. you are right, they are not directly delivered by Telegram, but the Platform allows for such things, there are so many bots collecting user's info all without their explicit consent. and this is the Platform's fault not Third Parties.

3. if you guys are community devs, (i.e. not paid by Telegram) I don't know why are you wasting your time on such a **Bloated Platform** like Telegram.
I do because there is no other choice, everyone is on this thing.

> They can buy a server and install a private proxy without sponored channel

you might as well build your own messenger (hint: [Signalapp](https://github.com/signalapp) repo)

> But there can't be a completely free option anyway

@levlam may I introduce you to things like ProtonVPN or TorProject?

@DarthJahus Do you dare to +Heart this? D

**Comment by FrayxRulez** [comment]
The community includes who create, pay and offer proxies to the people as well 😊
I think that @levlam summarized well my opinion, furthermore no one forces you to use sponsored proxies, you're free to use the solution that best fits for you, including using a different messenger.

**Comment by Alexmitter** [comment]
@Xashyar

>  "and Finally if you guys are community devs, (i.e. not paid by Telegram) I don't know why are you wasting your time on such a Bloated Platform like Telegram."

Telegram is not bloated, it is well balanced and you are wrong. There is nothing wrong with giving the chance to people who offer you something that cost them money for free, to get something back. Nothing. And if You don't like it, you can just use Signal because you seem to think it is actually even in the near of Telegram in terms of quality and functionality. Or maybe you may use your own Proxy.

**Comment by Xashyar** [comment]
> The community includes who create, pay and offer proxies to the people as well 😊
> I think that @levlam summarized well my opinion, furthermore no one forces you to use sponsored proxies, you're free to use the solution that best fits for you, including using a different messenger.

very well,
so since you seem to be in touch with all of these so called creators, would you mind Introducing some Ad-Free ones? to prove that I'm free to use the solution that best fits me. 
Thanks in advance.

A different messenger is my preferred but not all inclusive option, good for the Tely guys :)

**Comment by DarthJahus** [comment]
@Xashyar, here's my suggestion: Go get a VPS, install a MTProxy, use it and offer it _free of ads_ while ensuring stability and less than 1000 ms ping while more than 4000 Iranians are connected at once. We'll see if you can sustain that for longer than a month or two without people funding you or… advertising :)

**Comment by Xashyar** [comment]
> you seem to think it is actually even in the near of Telegram in terms of quality and functionality. Or maybe you may use your own Proxy.
@Alexmitter 
I don't think that Signal matches Telegram in terms of quality and functionality, but it surely leaves light years behind in terms of Privacy and respecting user's choices.

PS: Look up the word "Bloated" in your dictionary.
then look into Telegram Settings/Bots/Channels to get a better sense, and then maybe compare it to another messenger.
@FrayxRulez 
and since you think it's open source send me the link of Telegram X/iOS/MTProto to date repos/implementations for better enlightenment.

**Comment by Alexmitter** [comment]
> but it surely leaves light years behind in terms of Privacy and respecting user's choices.
this is incorrect in all terms, telegram is clear about its privacy and user's choice and isnt a US Based Company like Wisper Systems.

>  then look into Telegram Settings/Bots/Channels to get a better sense, and then maybe compare it to another messenger.
Telegram is not just a simple SMS Replacement, its Messenger on the level of stuff like MSN Messenger back in its days, it is feature rich and power user focused. And in this terms, it is clear, straight forward and not bloated in any terms. But again, if you don't like it, don't use it.

**Comment by FrayxRulez** [comment]
@Xashyar sorry but no one here stated that Telegram is fully open source and I think this isn't the focus of this thread, so I'd ask you to stop being off topic.

**Comment by stek29** [comment]
So, you just don't want to pay for block circumvention -- neither by having sponsored channel, nor by paying people who host proxies, nor by setting up your own proxy, nor by spending time looking for ad-free proxy, nor by switching to different app, nor by moving into a country with minimal internet censorship / making your government stop blocking everything they don't like?

Those are the options you have. Choosing one is free will.

You have one more option, actually. Abuse the system and make a modified app which doesn't show sponsored channel.

You have also mentioned data mining -- but proxy owners don't get any data from sponsored channel. Proxy owners get no data about users except the ip (and anonymized stats from telegram). They can of course analyze what DCs you connect to in what order, see what amount of data flows through the connection, and try to make sense of that -- but there's nothing you can do about that.

Sorry for jumping to conclusions -- but I don't think it's about privacy -- it's about abusing other people's trust and tricking the system to avoid paying for what you get.

**Comment by Xashyar** [comment]
> @Xashyar, here's my suggestion: Go get a VPS, install a MTProxy, use it and offer it _free of ads_ while ensuring stability and less than 1000 ms ping while more than 4000 Iranians are connected at once. We'll see if you can sustain that for longer than a month or two without people funding you or… advertising :)

@DarthJahus @stek29
and Here's my slightly easier suggestion/choice (**only** bridge users),
![userstats-bridge-country-ir-2018-10-08-2018-11-07](https://user-images.githubusercontent.com/34171942/48154654-6af72900-e2de-11e8-9212-8604f3fb845d.png)

+ ping is <**300ms** for Telegram

**Comment by MarcAnt01** [comment]
Closing this conversation as it's just shit ot stuff

**Comment by Xashyar** [comment]
> 
> 
> You have to check _Enabling loopback for a UWP application_ (Sorry, I thought to have linked that anchor directly).
> Unigram package family name (to be passed with `-n` parameter) is `38833FF26BA1D.UnigramPreview_g9c9v27vpyspw`.
@FrayxRulez 
![image](https://user-images.githubusercontent.com/34171942/48265765-9a26ab00-e442-11e8-9fa9-424231f1c024.png)

**Comment by FrayxRulez** [comment]
If you search through closed issues you can find some UI tool to do this
