### ISSUE TITLE
Button to go the end of a chat doesn't work in certain conditions

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#879]
Happens to me in supergroups, I haven't a private chat long enough to reproduce that

**Comment by FrayxRulez** [comment]
If you aren't sure about the cause, it might be better to not include a reason at all.

**Comment by MarcAnt01** [comment]
Other users confirmed me, that happens in that case, I have just said I'm unable to reproduce from private chats

**Comment by FrayxRulez** [comment]
I'm unable to reproduce this issue in any kind of chat even going back to 2016 and I'm quite sure that history position doesn't affect in any way that button

**Comment by bugada** [comment]
It happens often at least on mobile. I think it's related to the loading message that is not yet finished when you enter the chat, so the last message is the last loaded at that time.

I'll try to find a repro.

**Comment by MarcAnt01** [comment]
On PC for me happens just rarely

**Comment by MarcAnt01** [comment]
I haven't managed to reproduce it recently, I think it's fixed now
