### ISSUE TITLE
help

### ISSUE THREAD

**Issue by amirali013** [UnigramDev/Unigram#88]
this app dont install on my pc
Error code 0x800B0109 
& 
Unable to install bundle file:///C:/Unigram_0.1.31.87_ARM.appxbundle because it does not have an appropriate application package for x64 architecture.

**Comment by ikarago** [comment]
The package currently provided on HockeyApp (via the Unigram Channel) is only for Phones, so you can't install those on non-ARM machines. 

We'll release official packages for PCs and tablets a later time. ;)
