### ISSUE TITLE
[Feature Request] Encrypted Option for Saved Messages

### ISSUE THREAD

**Issue by Xashyar** [UnigramDev/Unigram#880]
Secert Chat Like , on-device or end-to-end encryption for Saved Messages.

**Comment by Xashyar** [comment]
@MarcAnt01 Since you Like "s**t ot stuff" a lot.

**Comment by FrayxRulez** [comment]
This is the kind of stuff you have to ask to Telegram: twitter.com/Telegram

**Comment by Xashyar** [comment]
@FrayxRulez
alright but don't call it Spamming, it's Education.
since you're an unofficial repo why do you care for Official Telegram's Permission?
do you decide for user's or Telegram?

**Comment by MarcAnt01** [comment]
Are you able to understand that you have to stop this kinda ot?

**Comment by FrayxRulez** [comment]
I know how Signal works and I doubt this is the right place where to educate me about it. If you really want to, you can explain me Signal goodies reaching me on Telegram, my username is the same as here.

I want Unigram to behave the most as possible as official apps, that's all. After all I'm not creating my own messenger, but a Telegram client (and I'm not really interested in offering additional features).

**Comment by Xashyar** [comment]
> I'm not going to block you nor to lock your tickets

You're being too generous! @FrayxRulez 

> Are you able to understand that you have to stop this kinda ot?

@MarcAnt01 
It's not OT amigo, I'm just wondering why does implementing this has anything to do with twitter/telegram?

Are you able understand the meaning of Questions & Transparency?
or you're just indifferent like @FrayxRulez 

I'm just wondering :
are you following Official Guidelines? if not why remain Unofficial then? Merge with the rich kids with 1.7 billion funding from who knows where :)

**Comment by MarcAnt01** [comment]
https://github.com/UnigramDev/Unigram/blob/develop/CONTRIBUTING.md

**Comment by Xashyar** [comment]
> 
> 
> https://github.com/UnigramDev/Unigram/blob/develop/CONTRIBUTING.md

👍 
now you're acting civilized.
