### ISSUE TITLE
"Save as..." contex menu doesn't appear until you download full file

### ISSUE THREAD

**Issue by NogrTL** [UnigramDev/Unigram#882]
When the file isn't downloaded or it's currently downloading it doesn't have 'Save as' context menu![No 'Save as...'](https://user-images.githubusercontent.com/12021449/48157415-32545100-e2d8-11e8-9989-b9acd9670286.png)

After completely downloading file this option appears!['Save as' appeard](https://user-images.githubusercontent.com/12021449/48157476-60399580-e2d8-11e8-8a4b-6fcd9f37df0a.png)

I'm not sure is it a bug or it design that way but it'll be better if this button would appear from the start

**Comment by FrayxRulez** [comment]
This is a design decision, but I might decide to change this in future releases. Leaving this open!

**Comment by MarcAnt01** [comment]
Closing as official clients have the same behaviour, if it gets changed in the future feel free to reopen this issue.
