### ISSUE TITLE
Opening/Saving/Managing Media Files 

### ISSUE THREAD

**Issue by Xashyar** [UnigramDev/Unigram#883]
1. If the File is previously downloaded (tedesktop directory) it will make duplicates in the (Unigram Directory)
2. Since MP3s could not be played within the app, it should open them using system's default but it opens them using MediaInfo. (I'm not sure if it's a System bug or yours)
3. Could the app use more simplified directories, perhaps user modifiable, like Downloads/Unigram?

**Comment by FrayxRulez** [comment]
1. As you love privacy so much Microsoft don't allow apps to access arbitrary folders in your file system and other apps informations, hence there's no way the app can determine if you have downloaded that file already from tdesktop (as is, the app can't even determine which account you use to login into tdesktop nor access its database, would be an huge security flaw if possible)
2. The app uses the system's default app to open any file externally.
3. As 1st step, even allowing you to insert an arbitrary path the app won't be able to write/read there.

**Comment by Xashyar** [comment]
> The app uses the system's default app to open any file externally.

That's what isn't working right now, My Default App for MP3s isn't MediaInfo as I've mentioned above.
I will test this for other extensions as well. 

So apart from arbitrary paths wouldn't Downloads/Unigram make more sense than this:

Users\[REDACTED]\AppData\Local\Packages\[REDACTED(but not sure why)].UnigramPreview_[REDACTED(but not sure why)]\LocalState\0\documents

I think you rushed to close this ticket.

**Comment by FrayxRulez** [comment]
Downloads\Unigram is an arbitrary location. UWP apps can only write to their own folder in %LOCALAPPDATA%
