### ISSUE TITLE
Graphic bug with "show in chat" in 2.4

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#885]
With 2.4 when you open a picture and via photo viewer right click and click on "show in chat" you will have this result. (by shared media section doesn't happen)
![image](https://user-images.githubusercontent.com/43090263/48202664-cfa99680-e365-11e8-9d21-1474eece9827.png)

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/27078197c45a8e114ad40a6ad52569898ee96063

**Comment by Xashyar** [comment]
@MarcAnt01  How did u take the screenshot?

**Comment by MarcAnt01** [comment]
RS5 Snip and scatch tool

**Comment by Xashyar** [comment]
> 
> 
> RS5 Snip and scatch tool

Ow it used to block screenshots on 2.3

**Comment by FrayxRulez** [comment]
It should block screenshots in secret chats

**Comment by Xashyar** [comment]
> 
> 
> It should block screenshots in secret chats

got it now...
