### ISSUE TITLE
Message align issues

### ISSUE THREAD

**Issue by Ujinjinjin** [UnigramDev/Unigram#888]
After recent updates 2.4.2019 & 2.4.2022 I have message displaying issues, if application window is wide, they are align to line that somewhere in center. Screenshots also attached

I have 1920x1080 display

Screens:

- Full display with 100% scale

![f_100](https://user-images.githubusercontent.com/20992866/48217098-8eca7580-e397-11e8-89ac-f0bf0f60de85.jpg)

- Full display with 125% scale

![f_125](https://user-images.githubusercontent.com/20992866/48217116-968a1a00-e397-11e8-8bae-ef18a6a8365d.jpg)

- Windowed with 125%, when it is not too wide

![w_125_1](https://user-images.githubusercontent.com/20992866/48217331-2334d800-e398-11e8-8c3b-83b3f2998c4f.jpg)

- Windowed with 125% when it is almost full display wide

![w_125_2](https://user-images.githubusercontent.com/20992866/48217400-4b243b80-e398-11e8-8fb8-acb3c693d42c.jpg)

Tried to reset application and reinstall it, did not helped. Also updated from 2019 to 2022, but neither helped.

**Comment by larsschellhas** [comment]
It´s a feature, so that messages can be read better. You can deactivate that "wide display optimized" look in the advanced settings. Though it might get deactivated by default in the next update.

**Comment by FrayxRulez** [comment]
This isn't an issue, but a feature. You can disable it from Settings > Advanced > Adaptive layout for wide screen.

Next version will have this turned off by default.

**Comment by Ujinjinjin** [comment]
![image](https://user-images.githubusercontent.com/20992866/48218788-c0ddd680-e39b-11e8-96a8-bab51321e377.png)

do not have this option in settings, but thanks anyway, will wait till next update

**Comment by FrayxRulez** [comment]
Just make the window wider
