### ISSUE TITLE
Remove notifications when the chat has been read.

### ISSUE THREAD

**Issue by ikarago** [UnigramDev/Unigram#89]
Remove Unigram-notifications from the Action Center when;
- The appropriate chat has been opened.
- The appropriate chat has been read in another Telegram client (handled on the next time Unigram is opened)

**Comment by AGreatFish** [comment]
Please try to also update the badge on the Glance Screen when the chat has been read on another client.

**Comment by adrianghc** [comment]
This should also work for the notification counter badge on the taskbar.
