### ISSUE TITLE
Supergroup recent actions have disappeared

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#894]
With 2.4.2032 and new chat info section this seems to have been removed

**Comment by FrayxRulez** [comment]
It’s in > Manage group > Administrators > Recent actions

**Comment by MarcAnt01** [comment]
@FrayxRulez OK, but I think it's not the right place to display it, both Telegram for Android an Telegram Desktop have "recent actions" section directly in "manage group" section

**Comment by FrayxRulez** [comment]
For now
