### ISSUE TITLE
Links unreadable when using dark accent color

### ISSUE THREAD

**Issue by HimbeersaftLP** [UnigramDev/Unigram#897]
When using a dark accent color like grey, links in chat messages are almost unreadable.

See this screenshot:
[Screenshot](https://i.imgur.com/CBejFjF.png)

Possible ways to address this:
- Use Telegram's color scheme for links (#831)
- Add a color picker for link color in the appearance settings

**Comment by FrayxRulez** [comment]
There are two solutions to this, both with cons:
**Set the same foreground as the rest the text, from code.**
- Cons: links would stay of the same color if you change theme

**Set some specific color by overriding XAML resource.**
- Pros: would reflect theme changes
- Cons: the same color would be applied to any link in the app, not just ones in messages

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/e540141f2f2c79b09b8acc8cad3631ae279874e6

**Comment by HimbeersaftLP** [comment]
Thanks, I really appreciate the work you people are doing.
