### ISSUE TITLE
Chats with unread messages sometimes don't open in the right position

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#898]
Sometimes when opening private chats with unread message, the chat isn't open close to "unread messages" banner, but almost 20 messages above

**Comment by MarcAnt01** [comment]
@FrayxRulez seems that Unigram opens the chat above the "unread messages" banner and not under it, when this bug occours

**Comment by GingerPlusPlus** [comment]
It brought me to newest / bottom, perhaps because that's what it does when you try to go to chat you're already in?

**Comment by MarcAnt01** [comment]
This is fixed now
