### ISSUE TITLE
Share link from MSN News, Sports or Money to Unigram freezes the app

### ISSUE THREAD

**Issue by bugada** [UnigramDev/Unigram#907]
When i use share button on any app to share a link to unigram, the unigram contact windows appears, but after sending message the app freezes. Sometimes this message is shown:

![wp_ss_20181121_0002](https://user-images.githubusercontent.com/4438193/48863964-6eed7580-edcb-11e8-9ea6-8923c58adfc6.png)

**Comment by bugada** [comment]
I didn't tried on desktop but on mobile happens also after rebooting the Phone. The same app can share its link to Whatsapp but not to Unigram

**Comment by bugada** [comment]
If i am not wrong, the News app is UWP, isn't it? Sharing a news freezes unigram for example.

**Comment by bugada** [comment]
But sharing from Fitbit works, even if the Unigram contacts window is in English, while that from news is in italian.

**Comment by bugada** [comment]
Ok problematic app are MSN News, MSN Money and MSN Sport. But i can share a news to Twitter UWP or Whatsapp without peoblem.

**Comment by MarcAnt01** [comment]
@bugada It's clear it's a uwp problems and not Unigram one, Twitter and Whatsapp aren't uwp apps....

**Comment by MarcAnt01** [comment]
> Ok problematic app are MSN News, MSN Money and MSN Sport. But i can share a news to Twitter UWP or Whatsapp without peoblem.

Twitter is PWA

**Comment by bugada** [comment]
Skype is a true UWP and works as expected.

**Comment by DarthJahus** [comment]
@bugada Working with one app doesn't mean there's nothing wrong. Even though this isn't a huge issue, if the app freezes, it may be worth investigating.

**Comment by bugada** [comment]
Therefore the exception is shown only if I close the MSN app. If i leave it open the app Unigram freezes  and after about one minute it crashes.
