### ISSUE TITLE
Add emoji while editing message

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#909]

**Comment by tvardero** [comment]
@MarcAnt01 You can use "Win"+":" combination to open windows' emoji list.

**Comment by MarcAnt01** [comment]
> @MarcAnt01 You can use "Win"+":" combination to open windows' emoji list.

I know, but as you can see you can add emoji also directly through the app and this option isn't available while editing

**Comment by FrayxRulez** [comment]
Done!
