### ISSUE TITLE
Problems with Telegram passport

### ISSUE THREAD

**Issue by tvardero** [UnigramDev/Unigram#912]
Please, notice that i use russian translate, it's possible to be normal in english translete - i've not checked this.

Bug devided in different parts:
- [ ] **Design improvements:**
* Password input dialog box:
![image](https://user-images.githubusercontent.com/45442278/49194101-6e844a00-f38a-11e8-9d40-38b334df72dd.png)
* Add new document dialog box is empty:
![image](https://user-images.githubusercontent.com/45442278/49194411-b5bf0a80-f38b-11e8-8699-2267417a5733.png)
* Button mapping, missclick (and Telegram Passport removal) is possible:
![image](https://user-images.githubusercontent.com/45442278/49194452-de470480-f38b-11e8-8b41-a81a365eb72b.png)

- [ ] **Document list russian translate missing:**
![image](https://user-images.githubusercontent.com/45442278/49194561-5a414c80-f38c-11e8-8dfc-8e096792916a.png)

- [ ] **"Delete Telegram Passport" button is not working nor showing any confirm dialog box.**

- [ ] **Personal info can't be changed**

**Comment by MarcAnt01** [comment]
Why has it been closed @tvardero ?

**Comment by FrayxRulez** [comment]
Makes sense honestly. Telegram Passport is out of scope and it isn't going to be developed any further in Unigram.
