### ISSUE TITLE
(BUG) Delete message "for everyone" checkbox missing

### ISSUE THREAD

**Issue by tvardero** [UnigramDev/Unigram#913]
![image](https://user-images.githubusercontent.com/45442278/49196112-4f89b600-f392-11e8-9bc9-590476688e32.png)
(translation: "Are you shure you want to delete 1 message?")

It's a private conversation, not public group nor supergroup.
![image](https://user-images.githubusercontent.com/45442278/49196231-ccb52b00-f392-11e8-97bd-ebf33d5a3338.png)

**Comment by FrayxRulez** [comment]
You can delete for everyone only messages sent within 48 hours from now.

**Comment by tvardero** [comment]
@FrayxRulez In that case in official Telegram client when you delete message in dialog box appears the note "The other party interlocutor will have a copy."
