### ISSUE TITLE
Add missing icons in some menus

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#914]
**Leave group from group info**
E74D

**Copy username and bio/group description**
E8C8

**Edit profile picture**
From camera: E722
From gallery: EB9F

**Paste in search bars**
E77F

**Text formatting in typing bar**
Undo: E7A7
Redo: E7A6
Cut: E8C6
Copy: E8C8
Paste: E77F
Formatting: E8D2
Select all: E8B3
Delete: E74D
Bold: E8DD
Italic: E8DB
Monospace: E97F
Create link: E71B
Plain text: E97E

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/d0f846cf3173e139360ef02712e52ccf3e881f7a
