### ISSUE TITLE
Multiple send image as file doesn't work with drag and drop

### ISSUE THREAD

**Issue by kowalski7cc** [UnigramDev/Unigram#915]
Sending multiple images and marking one, multiple or all the behaveaur is always send all as images and not as files.
Sending them directly through the app is fine

**Comment by MarcAnt01** [comment]
What do you mean by marking one?

**Comment by kowalski7cc** [comment]
I mean when multiple image are being dropped on unigram, if only I select one image to send as file, or multiple, it will send as picture and not as file

**Comment by MarcAnt01** [comment]
Unable to reproduce

**Comment by kowalski7cc** [comment]
![bug](https://user-images.githubusercontent.com/5065094/49797994-73111100-fd41-11e8-90c2-1abc5c3bc782.png)
Correct behaviour

**Comment by kowalski7cc** [comment]
![bug2](https://user-images.githubusercontent.com/5065094/49798018-845a1d80-fd41-11e8-9edd-208cfae42ef2.png)
Wrong behaviour

**Comment by MarcAnt01** [comment]
Happens just with drag and drop, OK

**Comment by MarcAnt01** [comment]
It's working with new media sender
