### ISSUE TITLE
Can't open sticker panel using touch screen

### ISSUE THREAD

**Issue by Jack-Works** [UnigramDev/Unigram#916]
It seemed Unigram recently add a new feature that sticker panel will open while the mouse is hovering.
But this brokes the touch screen, it likely to unexpectedly treat touch-leave as mouse-leave.

**Comment by FrayxRulez** [comment]
Fixed (?) in https://github.com/UnigramDev/Unigram/commit/fd67f2328b922063a31f812bbc31058e313ffc59
