### ISSUE TITLE
Disable call for the person who logged in's account

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#921]
Repro steps:
1. click on a mention of you in the chat;
2. click on phone number.
Then you'll get this exception
![image](https://user-images.githubusercontent.com/43090263/49696078-cd289f80-fba4-11e8-8597-3f78b9cb4a6c.png)

I would suggest to open directly the shared media section as workaround, since this section is unuseful

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/4329032470caaae2f046c4843a4c0299a4706aa8
