### ISSUE TITLE
If a secret chat gets deleted, opening new secret chat redirects to it, instead of opening a new one

### ISSUE THREAD

**Issue by hub-ch** [UnigramDev/Unigram#924]
with certain telegram contact, after cancelled(end) secret chat but unable start a new one. (only re-appear previous cancelled conversation that cannot send message further)

   however on telegram-android doesnt have that issue also android app can start new secret chat as well from its end with unigram.

**Comment by MarcAnt01** [comment]
@hub-ch Why are you bug reporting with an old version of Unigram?

**Comment by thawisakprasreod** [comment]
@YOY098765YOY

**Comment by vboxpro** [comment]
@hub-ch is correct. 🥇  unigram latest version on microsoft store has that problem. above version number mentioned might be unigram repository release tag.
  @MarcAnt01 you can reproduce the issue.

**Comment by MarcAnt01** [comment]
You need to specify the version in a more precise way and tell repro steps

**Comment by hub-ch** [comment]
above i have explained @MarcAnt01. read below,

assume windows 10 1803, 1809 or else
Unigram 2.4.2031
# download latest Unigram from microsoft store
# login to telegram account
# choose a preferred contact, go to default chat(profile) and then start a "secret chat"
# send some test messages to your contact (it'll works as normal)
# now ex: "delete chat" from another telegram contact end (tell your friend to "delete chat") or delete by yourself.
# then you'll see "secret chat cancelled"
# you can "clear history" or "delete chat" from your end (optional)
# go to that contact again. try to start "secret chat" again
# it'll re-appear previous secret chat as "secret chat cancelled" (bug)

 but your friend can start "secret chat" again again from official android client

hopes those details clear to reproduce the issue.
have a good day.

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/2cb28233ccacf30bf8647643b7b7d85eaa13ce43
