### ISSUE TITLE
Suggestion: use Windows UI Library to support NavigationView on W10M

### ISSUE THREAD

**Issue by jp-weber** [UnigramDev/Unigram#926]
Through the release of Windows UI Library, it is possible to run the NavigationView and etc. on W10M.

https://github.com/Microsoft/microsoft-ui-xaml
https://docs.microsoft.com/de-de/uwp/toolkits/winui/getting-started

**Comment by FrayxRulez** [comment]
Fluent effects have been disabled by choose on Windows Mobile to optimize app performances.

**Comment by jp-weber** [comment]
But you could handle it with a custom style?

**Comment by callummoffat** [comment]
Sure, but that would require a ton of extra work for a platform that is dying anyway.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by FrayxRulez** [comment]
I don't see why using NavigationView when we have something that looks exactly  the same? 🤔

**Comment by jp-weber** [comment]
Yes, that's true, but my main concern was to use the new and same controls on the old platforms as on the new ones. Gradually most of the controls will be added to the library and maybe the CommandBarFlyout is currently interesting as well?
