### ISSUE TITLE
Contact has joined message not being placed correctly in chat history

### ISSUE THREAD

**Issue by MrFobwatch** [UnigramDev/Unigram#928]
When a new contact joins Telegram and you receive the message 

> John Doe has joined Telegram!

on a different device the message is not recognized as read. This can be seen when conversation is started on this other device and a chat history is created. Upon returning to Unigram even if you were up to date and read on the other device, an unread message icon shows up in Unigram for this contact with the message

> John Doe has joined Telegram!"

Once it has been read on Unigram it is then inserted into the chat history out of sequence only on Unigram.

**Steps to Reproduce**

1. Have a new contact join Telegram while Unigram is closed/off.
2. Begin a conversation with new contact using a client other than Unigram.
3. Ensuring that you have read all the current messages in that conversation, open Unigram and look for that contact.

**Comment by MarcAnt01** [comment]
That happens, because this kind of messages are not synced among devices, just try with tdesktop and telegram for your mobile device

**Comment by MarcAnt01** [comment]
Moreover it's for security, if someone accesses to your account, you wouldn't be aware of it

**Comment by MrFobwatch** [comment]
My question is why it places it in the history incorrectly. If a contact joins on the 10th and you have a conversation on the 12th when you reopen unigram on the 13th it marks the very beginning of the chat as starting on the 12th like it should but it then puts a heading for the 10th with the new contact message afterwards.

**Comment by MarcAnt01** [comment]
>           My question is why it places it in the history incorrectly. If a contact joins on the 10th and you have a conversation on the 12th when you reopen unigram on the 13th it marks the very beginning of the chat as starting on the 12th like it should but it then puts a heading for the 10th with the new contact message afterwards.

Sorry, haven't understood

**Comment by MarcAnt01** [comment]
I'll try to reproduce as soon as a contact of mine joins Telegram

**Comment by MarcAnt01** [comment]
Will try to reproduce as soon as a contact of mine joins Telegram

**Comment by MarcAnt01** [comment]
If I send some messages the history is placed correctly when I reproduced, is the problem correlated to what's sent by other person?

**Comment by FrayxRulez** [comment]
In the API version used by Unigram at the moment contact joined message isn’t a message but an update, this means that it isn’t part of the chat history and its placement might vary from client to client, and unread state is a local value as well.
