### ISSUE TITLE
Random propics not loaded in some menus

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#930]
Sometimes, some profile pictures aren't displayed in some menus, for example in banned or ristricted users, when I click on the profile of some of those people, the profile picture is displayed and when I go back all  they are fine in the menu.

**Comment by MarcAnt01** [comment]
The Android client seems to handle this situations by loading the generic profile pictures just with initial letters and changing them during the loading, while Unigram doesn't refresh unless the section is reloaded

**Comment by FrayxRulez** [comment]
Would be nice to have a list of those places

**Comment by MarcAnt01** [comment]
- Group members info;
- Join private group banner;
- Permissions view when admin of a group;
- Channel members and restricted people

**Comment by MarcAnt01** [comment]
There might be others, but these are the main ones
