### ISSUE TITLE
Pinned message position

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#931]
With long pinned messages, Unigram displays the central part of the messages, while official clients display the beginning

**Comment by FrayxRulez** [comment]
I can't understand

**Comment by someniatko** [comment]
Consider a long message, "1 2 3 4 5 ... 9998 9999 10000"
Pin this message in the group chat.
It will be displayed as "... 4998 4999 5000 5001 ...", but expected "1 2 3 4 5 6 7 ..."

**Comment by morenj96** [comment]
@someniatko Isn't it middle of message text?

**Comment by MarcAnt01** [comment]
@morenj96 Yep, but the correct behaviour is the beginning
