### ISSUE TITLE
How can I get Unigram if I don't have Windows Store?

### ISSUE THREAD

**Issue by ArmeF97** [UnigramDev/Unigram#934]
I disabled the Windows Store, because of privacy.
Is it possible to install Unigram without having the Windows Store installed?

**Comment by MarcAnt01** [comment]
Take a look here, but version isn't as updated as the one pushed in Microsoft Store
Unigramdev.github.io

**Comment by ArmeF97** [comment]
Thanks! Shouldn't it be in the readme?

**Comment by MarcAnt01** [comment]
> Thanks! Shouldn't it be in the readme?

Added five minutes ago

**Comment by ArmeF97** [comment]
Thanks!
