### ISSUE TITLE
Telegra.ph page with non-existing link crashes the app

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#939]
Steps to reproduce:
1. Open `[that](http://telegra.ph/OnePlus-ITA-09-05);
2. Click "open in" to open via browser
The app crashes

**Comment by MarcAnt01** [comment]
In Telegram for Android the page is not opened in instant view, but directly via browser, where this page is shown
![image](https://user-images.githubusercontent.com/43090263/50514145-a02d2580-0a9c-11e9-9fa1-d97b8a669bdb.png)

**Comment by FrayxRulez** [comment]
No longer crashes
