### ISSUE TITLE
Inconsistent formatting with codeblocks (` and ```)

### ISSUE THREAD

**Issue by Knifa** [UnigramDev/Unigram#946]
Hey, discovered this weird one today on 2.4.2073.

It looks like code formatting is inconsistently applied depending on what you say. The same happens for inline ` and block ```. 

![image](https://user-images.githubusercontent.com/622619/50576767-d78b3180-0e10-11e9-88fe-0078c729b76d.png)

Couldn't work out what the rules were. The official Telegram client formats them all as expected.

**Comment by FrayxRulez** [comment]
Recently fixed, give it a try!
