### ISSUE TITLE
[Enhancement] Multiple Instances of Unigram App

### ISSUE THREAD

**Issue by hub-ch** [UnigramDev/Unigram#955]
Request for extend development for support to multiple instances for Unigram app.

![untitled](https://user-images.githubusercontent.com/45872460/50981357-67299200-152d-11e9-95ab-d21de215c2ca.png)

**Comment by MarcAnt01** [comment]
This would be pretty useless, you can already open chats in separeted windows

**Comment by hub-ch** [comment]
@MarcAnt01 No, you've misunderstood. If we can run multiple instances of Unigram, it means we can use (login to) multiple accounts on same pc (under same user account).

Official telegram have given solution by offering default installer telegram desktop and telegram portable.
https://desktop.telegram.org (Telegram Desktop) > https://telegram.org/dl/desktop/win
https://telegram.org/dl/desktop/win_portable (Telegram Portable)
   so Unigram?

 _"Not-together"_ i think it also necessary each logins, databases must be stored separately as two software. (to be clear, it should not as login to multiple account using one unigram app)

I see, there's also available additional install option via https://unigramdev.github.io so user can trick to install another manually. but as today, 
 unigram on store - 2.4.2073.0
 unigram (above git*.io) - 2.3.1929
    just we also expect, latest features, vulnerability/bug fixes etc as well.

However, secret chat only available for desktop through Unigram. so we really need this, please be consider extend development make available it soon. its not hard task :)

**Comment by MarcAnt01** [comment]
> @MarcAnt01 No, you've misunderstood. If we can run multiple instances of Unigram, it means we can use (login to) multiple accounts on same pc (under same user account).
> 
> Official telegram have given solution by offering default installer telegram desktop and telegram portable.
> https://desktop.telegram.org (Telegram Desktop) > https://telegram.org/dl/desktop/win
> https://telegram.org/dl/desktop/win_portable (Telegram Portable)
> so Unigram?
> 
> _"Not-together"_ i think it also necessary each logins, databases must be stored separately as two software. (to be clear, it should not as login to multiple account using one unigram app)
> 
> I see, there's also available additional install option via https://unigramdev.github.io so user can trick to install another manually. but as today,
> unigram on store - 2.4.2073.0
> unigram (above git*.io) - 2.3.1929
> just we also expect, latest features, vulnerability/bug fixes etc as well.
> 
> However, secret chat only available for desktop through Unigram. so we really need this, please be consider extend development make available it soon. its not hard task :)

Making it possible it's not that simple and few people would really need that, Unigram supports multiple accounts, so there isn't this need as in TDestkop for users who have more than an account.

As for manual install you are right, we should update it more often👍

**Comment by hub-ch** [comment]
"As for manual install you are right, we should update it more often👍"
   
Keep anything task reminder on PC for do it same time push to store :D or use any free storage facility to upload it quick within one click or drag-and-drop if github complex 
we dont need io.-page updates, notes. just can read it from somewhere else or on default repo 

have a nice day! @MarcAnt01 🎉

**Comment by MarcAnt01** [comment]
Yep, already thought about, .appxbundle files can't be attached, should zip them or find another solution. Thanks for the tip
