### ISSUE TITLE
Remember position in group info

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#956]
Atm if I scroll down in a group info and open someone's profile, when I go back, Unigram forgets the position and the upper part of the section is displayed.

**Comment by morenj96** [comment]
@MarcAnt01 True
+1

**Comment by FrayxRulez** [comment]
Implemented here: https://github.com/UnigramDev/Unigram/commit/59bc92fb7a97daa6b779b578d8f079dd3e39e26c
