### ISSUE TITLE
Unhandled Exception when changing theme

### ISSUE THREAD

**Issue by kochie** [UnigramDev/Unigram#959]
Might be a duplicate of #784 I'm running `rs_prerelease 18312` on a Surface pro 6 and when I toggle `Use system accent color` or change any theme setting I get this error message. [Can't copy or paste the error 😢]

![image](https://user-images.githubusercontent.com/10809884/51217469-55f0e300-197c-11e9-9776-06b734d89bb6.png)

**Comment by FrayxRulez** [comment]
Reproduced, thanks
