### ISSUE TITLE
Installing without the store: failed to install package dependencies

### ISSUE THREAD

**Issue by Hitaro** [UnigramDev/Unigram#961]
I get this error when I run the file `2.4.2073.AppxBundle`:

    App Installer failed to install package dependencies. Ask the developer for Microsoft.VCLibs.140.00 package. 

![u](https://user-images.githubusercontent.com/18015032/51576203-422e0b00-1ead-11e9-9b41-1635501b023b.png)

**Comment by MarcAnt01** [comment]
Hi, are you on 1809?

**Comment by Hitaro** [comment]
What is '1809'?

**Comment by morenj96** [comment]
@Hitaro 😐 it's number of a version

**Comment by MarcAnt01** [comment]
> Hi, are you on 1809?

Windows 10 Version, but don't worry, was due to some missing dependencies. Now it's OK
