### ISSUE TITLE
My People "taskbar" SECURITY problem

### ISSUE THREAD

**Issue by thunderbirdtr** [UnigramDev/Unigram#962]
When we add "password,pin" method into the unigram there is a security issue in "people in taskbar" . When I open the "first shortcut"(person) in unigram it is asking "pin" as usually but without "typing" anything just nevermind that part and open "second" shortcut(person) in taskbar It just open magically without even "asking" password. We can just bypass pin so easily. I can also do that "reverse" way too. Open second person and leave then open first person and I can see that chat too. 

Requirement : Add 2 people into the "taskbar" shortcut and It will happened. 

Thank you.

**Comment by FrayxRulez** [comment]
I'm not sure about fixing My People issue as My People is going to get removed from future Windows updates (https://twitter.com/thebookisclosed/status/1073316790770515970)

So I'm marking this as won't fix for now

**Comment by thunderbirdtr** [comment]
It is true. I jut got new 19H1 updates and It just gone.

**Comment by alexhampu** [comment]
I still think this is a security issue and it should either get fixed, or the functionality removed as not everybody will update immediately to 19H1, and it's still possible to read messages without Pin / Password on older versions of Windows 10 (with support for My People).

**Comment by MarcAnt01** [comment]
There's no reason of keeping a Windows 10 version which isn't the latest, especially considering the support

**Comment by alexhampu** [comment]
> 
> 
> There's no reason of keeping a Windows 10 version which isn't the latest, especially considering the support

I agree, I am always updating, however for example the colleagues in my office do not like to update as often, and most of them skip a version or two. And this happens with a lot of people and this puts the security risk for this issue higher in my opinion.
