### ISSUE TITLE
Generated files will cause infinite retries after cache cleanup

### ISSUE THREAD

**Issue by Marocco2** [UnigramDev/Unigram#963]
Happens in 2073 PC only version
![image](https://user-images.githubusercontent.com/3944248/51712733-03748e00-2030-11e9-8f75-79335915346d.png)
Steps to reproduce:
1. Use Win-Shift-S and select an area of the display
2. Press Ctrl-V inside unigram and send the image in a chat
3. Wait a few days (IMHO it could be influenced from Stored media time lapsed, mine is set to 3 days)
4. Return to chat and look at the image. It should appear as above and increase CPU usage.

**Comment by Stefano-BS** [comment]
@Marocco2 Known

**Comment by MarcAnt01** [comment]
@Marocco2 why don't you use Windows Snip & Sketch tool, it should preserve the content in a notification

**Comment by Marocco2** [comment]
@MarcAnt01 Because Win-Shift-S is faster and easier

**Comment by MarcAnt01** [comment]
Open notification panel and click on qs tile, isn't that difficult, but Microsoft should trigger it with the shortcut you are talking about btw

**Comment by FrayxRulez** [comment]
This should have been fixed by https://github.com/UnigramDev/Unigram/commit/28410d6149efdf58630e2f63e8a43df99fb55440
