### ISSUE TITLE
"Windos hello" protection login problem

### ISSUE THREAD

**Issue by thunderbirdtr** [UnigramDev/Unigram#964]
Windows hello is asking for pin but when I tried to use other methods and get "authentication
" and say "Hello [My name]" but It still asking for "pin" password. logon method need to change dynamically because in normal "windows lock screen" It can ask pin or password but when I use other "login method" like iris or finger or "nfc" It still handling that automatically. So there is a problem on that part in unigram as well. 

Thank you.

**Comment by FrayxRulez** [comment]
This isn't a bug in Unigram, but something probably not supported by Windows.
