### ISSUE TITLE
Missing feature: out of box polls

### ISSUE THREAD

**Issue by msvaillant** [UnigramDev/Unigram#969]
According to [the release in 22, December](https://telegram.org/blog/polls) - Telegram introduced non-bot like polls support.
In my case, there are plenty resources already using it and it would be nice for Unigram to stay on the actual branch of development

**Comment by MarcAnt01** [comment]
Hi, please read [contributing guidelines](https://github.com/UnigramDev/Unigram/blob/develop/CONTRIBUTING.md) before opening issues.
There you can find the ticket in TDlib to track the issue. Polls won't be implemented untill it supports them
