### ISSUE TITLE
Better error messages for noobs

### ISSUE THREAD

**Issue by Marocco2** [UnigramDev/Unigram#97]
![image](https://cloud.githubusercontent.com/assets/3944248/20716828/e2d0b2de-b653-11e6-8f7a-b9faf1b8f95a.png)
![image](https://cloud.githubusercontent.com/assets/3944248/20716908/13615480-b654-11e6-9ddb-8d61a26dc764.png)

Here there is an example of a raw error message

**Comment by FrayxRulez** [comment]
Those error messages are useful to diagnose the problem.
