### ISSUE TITLE
Use the same Saved Messages position in hamburger menu as in TD

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#971]
In Telegram Desktop it's here, and would be handy having it in Unigram, as well
![image](https://user-images.githubusercontent.com/43090263/52521798-fdf88400-2c7c-11e9-976d-09b607455a61.png)

**Comment by FrayxRulez** [comment]
We have account switcher there, and menu is ordered as Android client.

**Comment by MarcAnt01** [comment]
> We have account switcher there, and menu is ordered as Android client.

Space above it could be used with this purpose, as no profile picture is being shown as in official clients.

**Comment by MarcAnt01** [comment]
Moreover you stated that it's ordered as in Android client, but this isn't true
![image](https://user-images.githubusercontent.com/43090263/52521940-4fa20e00-2c7f-11e9-8f03-5dc4cd13060c.png)
![image](https://user-images.githubusercontent.com/43090263/52521962-8e37c880-2c7f-11e9-9ba6-832e91806280.png)

**Comment by MarcAnt01** [comment]
Being an Android user I would love to have the same ui of hamburger menu on PC, btw
