### ISSUE TITLE
Missing keyboard shortcuts

### ISSUE THREAD

**Issue by GingerPlusPlus** [UnigramDev/Unigram#974]
<kbd>Ctrl</kbd>+<kbd>W</kbd> &mdash; close window; available in TDesktop

Unigram 2.4.2073, Windows 10 64bit Build 17763.

[wiki]: https://github.com/UnigramDev/Unigram/wiki/User-Manual:-Shortcuts

**Comment by FrayxRulez** [comment]
<kbd>Ctrl</kbd>+<kbd>W</kbd>won't come as you can't close the window without closing the app

**Comment by GingerPlusPlus** [comment]
Closing the app doesn't stop the notifications, so it doesn't sound like an issue.

**Comment by GingerPlusPlus** [comment]
Why won't (<kbd>Shift</kbd>+) <kbd>Ctrl</kbd>+<kbd>Tab</kbd> be added / fixed?

**Comment by MarcAnt01** [comment]
@FrayxRulez Ctrl + W doesn't work with chat opened in a new window, what's the point of having it, then?

**Comment by GingerPlusPlus** [comment]
<kbd>Ctrl</kbd>+<kbd>Q</kbd> doesn't work as well on single-chat windows.
