### ISSUE TITLE
Add volume control to video player

### ISSUE THREAD

**Issue by wojpawlik** [UnigramDev/Unigram#975]

**Comment by MarcAnt01** [comment]
@GingerPlusPlus What do you mean?

**Comment by GingerPlusPlus** [comment]
Ability to adjust how loud the video plays (on Windows 10).

**Comment by MarcAnt01** [comment]
> Ability to adjust how loud the video plays (on Windows 10).

Why would you need that stuff? Anyway, it's in no official client

**Comment by FrayxRulez** [comment]
It's actually handy to be able to set the volume level for the specific app on desktop

**Comment by MarcAnt01** [comment]
> It's actually handy to be able to set the volume level for the specific app on desktop

Yes, you both are right, in my laptop I use volume rockers in the right side, but for a classic PC would be nice👍

**Comment by Stefano-BS** [comment]
@MarcAnt01 Use ear trumpet app from the store

**Comment by MarcAnt01** [comment]
@Stefano-BS Quote original message, otherwise I get tagged lol

**Comment by MarcAnt01** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/2af49bf7f564440423e652cde6669438206fcbbe
