### ISSUE TITLE
Move Recent actions to a more accessible place

### ISSUE THREAD

**Issue by GingerPlusPlus** [UnigramDev/Unigram#976]
Current location: Group profile > <kbd>:gear: Manage group</kbd> > <kbd>:star: Administrators</kbd> (?!) > <kbd>🕔 Recent actions</kbd>

Coming from TDesktop, I find hiding it behind <kbd>:star: Administrators</kbd> counter-intuitive. I assumed it's not yet implemented, until I noticed Github issues about it and brute-searched everywhere.

Also, it requires whooping 4 clicks to access (compared to 3 in TDesktop).

I suggest moving <kbd>🕔 Recent actions</kbd> straight to group profile view or <kbd>...</kbd> menu in chat view (2 clicks away), or at least to <kbd>:gear: Manage group</kbd>, as in TDesktop and TgX (3 clicks away).

**Comment by MarcAnt01** [comment]
The manage group section follows Mobile clients ui, as soon as recents actions were moved under admins section, Unigram did it, as well. Currently the best implementation would be keeping it directly in manage group for big groups and and under admins in small ones, as happens in latest Telegram for Android/iOS

**Comment by GingerPlusPlus** [comment]
Huh? I just checked, both Android clients display <kbd>Recent actions</kbd> under  <kbd>✏️ Manage group</kbd> (which is also the admin management screen in TgX), no matter the supergroup size. Non-supergroups don't have recent actions at all.

Why differenciate between small and big groups? Sounds unintuitive.

**Comment by MarcAnt01** [comment]
Idk, you should ask marketing team, but from the latest versions of mobile clients that's the behaviour

**Comment by GingerPlusPlus** [comment]
Don't know about iOS, but I haven't observed any differentiation in Android clients.

**Comment by MarcAnt01** [comment]
> Don't know about iOS, but I haven't observed any differentiation in Android clients.

You aren't running latest version on Play Store or you don't manage a group with less than 200 people

**Comment by MarcAnt01** [comment]
Closing this for now, as this section has been following mobile clients guidelines so far

**Comment by GingerPlusPlus** [comment]
> You aren't running latest version on Play Store or you don't manage a group with less than 200 people

Untrue. I am running latest TgX `0.21.3.1036-armeabi-v7a`, and I yesterday tried in nonX too.

I actually do manage 2 supergroups with <30 members, one of which I own.
And in both of those in TgX, <kbd>Recent actions</kbd> is in <kbd>✏️ Manage group</kbd>.

And, even if I'm somehow wrong, I wouldn't copy bad ideas from official clients.

> this section has been following mobile clients guidelines so far

What do you mean?

**Comment by MarcAnt01** [comment]
Telegram X isn't an official client, I'm talking about standard Telegram

**Comment by GingerPlusPlus** [comment]
If the goal is to mimic Android's official client interface (why?), why not move it to <kbd>✏️ Manage group</kbd>, and

1. Be consistent with small supergroups in Telegram for Android,
2. Be consistent with tgx and TDesktop,
3. Decrease amount of clicks to access,
4. Improve discoverability for people who don't use Telegram for Android.
