### ISSUE TITLE
Autocomplete by pressing Tab doesn't work after suspending the app

### ISSUE THREAD

**Issue by GingerPlusPlus** [UnigramDev/Unigram#977]
1. Start typing an username or a command or :emoji.
2. Choose one suggestion from the list using arrow keys, then press <kbd>Tab</kbd>.

Works fine after launching Unigram, after suspending it stops working.

**Comment by FrayxRulez** [comment]
Working now

**Comment by sethazazel** [comment]
I don't know if this is a bug or if this feature has never been added, but it would be nice if it comes. Telegram Desktop has this feature and TelegramX has something similar.

**Comment by MarcAnt01** [comment]
> I don't know if this is a bug or if this feature has never been added, but it would be nice if it comes. Telegram Desktop has this feature and TelegramX has something similar.

Wdym?

**Comment by sethazazel** [comment]
> 
> 
> > I don't know if this is a bug or if this feature has never been added, but it would be nice if it comes. Telegram Desktop has this feature and TelegramX has something similar.
> 
> Wdym?

Tab autocomplete for bot commands not working. I am not a long time unigram user thats why i don't know if this feature added and not working correctly or  its never added.

**Comment by MarcAnt01** [comment]
> > > I don't know if this is a bug or if this feature has never been added, but it would be nice if it comes. Telegram Desktop has this feature and TelegramX has something similar.
> > 
> > 
> > Wdym?
> 
> Tab autocomplete for bot commands not working. I am not a long time unigram user thats why i don't know if this feature added and not working correctly or its never added.

Does that always open or just after suspending the app?

**Comment by sethazazel** [comment]
> 
> 
> > > > I don't know if this is a bug or if this feature has never been added, but it would be nice if it comes. Telegram Desktop has this feature and TelegramX has something similar.
> > > 
> > > 
> > > Wdym?
> > 
> > 
> > Tab autocomplete for bot commands not working. I am not a long time unigram user thats why i don't know if this feature added and not working correctly or its never added.
> 
> Does that always open or just after suspending the app?

It always directly sends the commands like you press enter.
