### ISSUE TITLE
When "unread chats" selected, if you move to another chat after you read one, it should be removed from list

### ISSUE THREAD

**Issue by ArmeF97** [UnigramDev/Unigram#979]
When "unread chats" selected, if you move to another chat after you read one, it should be removed from list
![immagine](https://user-images.githubusercontent.com/6240983/52857632-0262e800-3128-11e9-922e-6f45a9ed8d6c.png)
As you can see I read the group "Billi foster" (last one), and I moved to "ACSO - IM-PJ", the group "Billi foster" should have been removed from the "unread chats" list

**Comment by FrayxRulez** [comment]
Mh, no

**Comment by ArmeF97** [comment]
It's no more an "unread chat"

**Comment by FrayxRulez** [comment]
I can remove the filter if you prefer

**Comment by ArmeF97** [comment]
What do you mean?

**Comment by FrayxRulez** [comment]
I can remove the option to filter chats by unread messages at all

**Comment by ArmeF97** [comment]
Why would you remove a feature?
