### ISSUE TITLE
Focus on input after clicking message

### ISSUE THREAD

**Issue by NoobTW** [UnigramDev/Unigram#982]
Feature request:
I think the input (the blue rectangle) should get focus no matter user clicks on the input (blue) or messages (red) like Telegram Desktop does.

![image](https://user-images.githubusercontent.com/9292238/52896505-f9474900-3203-11e9-820e-27c5dfc85a71.png)

**Comment by FrayxRulez** [comment]
I'm not sure this is technically possible, or I would have implemented this already :/

**Comment by MarcAnt01** [comment]
Now if you click on a message and start typing the focus will be moved there

**Comment by FrayxRulez** [comment]
Yep, everywhere you start typing text field will be focused.
Same applies to chats search in forward dialog and main list (in the second case there shouldn't be any chat open)
