### ISSUE TITLE
When "unread chats", there is a message to read, but it's not in the list

### ISSUE THREAD

**Issue by ArmeF97** [UnigramDev/Unigram#983]
When "unread chats", there is a message to read, but it's not in the list
![immagine](https://user-images.githubusercontent.com/6240983/52898178-161b5680-31db-11e9-827a-26aa6c8e8f65.png)

**Comment by FrayxRulez** [comment]
Steps to reproduce?

**Comment by MarcAnt01** [comment]
> Steps to reproduce?

Try to send a message with your second account (no unread messages) when you are already in the unread messages section and you'll see that the chat won't appear there.

**Comment by FrayxRulez** [comment]
I'm not able tro reproduce this.

**Comment by MarcAnt01** [comment]
Doesn't happen any longer with the introduction of folders
