### ISSUE TITLE
Add more right click actions to the icon in start menu and taskbar 

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#985]
I don't know their name in uwp development, but they are almost the same thing as [Android app shorcuts](https://developer.android.com/guide/topics/ui/shortcuts/).
At the moment there's just "saved message" action, would be nice to have there the option to start a new chat and latest recent chats.
Their implementation in Telegram for Android
![image](https://user-images.githubusercontent.com/43090263/52903639-b778cb80-3220-11e9-97ab-fe845fa6fbaa.png)

**Comment by FrayxRulez** [comment]
Hey, sorry but this won't come.
Users don't use much the JumpList and doing this would require really a lot of time and code to do this and I don't think it is worth.
