### ISSUE TITLE
Tab autocompletion should insert the command into the input instead of sending it

### ISSUE THREAD

**Issue by GingerPlusPlus** [UnigramDev/Unigram#986]

**Comment by MarcAnt01** [comment]
duplicate of https://github.com/UnigramDev/Unigram/issues/977

**Comment by MarcAnt01** [comment]
If you want to add further information, just edit that issue

**Comment by GingerPlusPlus** [comment]
They're related, but separate. That one is about autocomplete not working, this one is about it behaving differently than TDesktop.

**Comment by FrayxRulez** [comment]
Why you created 4 issues about tab not being functional

**Comment by GingerPlusPlus** [comment]
Because they're different issues with Tab

**Comment by FrayxRulez** [comment]
Issue is the same, as the code for all of this stuff is in place already
