### ISSUE TITLE
Problems with message search per person when switching chat

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#989]
Repro steps:
1. Open a group;
2. Search messages from a person;
3. Open another group;
4. Open search.

Now you will see the message search from the person of previous chat in search bar

**Comment by wizzard0** [comment]
this looks related to an account-switching bug I observed

**Comment by MarcAnt01** [comment]
> this looks related to an account-switching bug I observed

Point out what happened, so that I can add further details if needed

**Comment by FrayxRulez** [comment]
This should be fixed as well
