### ISSUE TITLE
(1) Back button in fullscreen (x86) chat view needs 2 clicks, (2) Can't open the same chat after leaving it from fullscreen (x86)

### ISSUE THREAD

**Issue by MarcelBrusius** [UnigramDev/Unigram#99]
Edition: x86
OS: Windows 10 Pro, 14393.447
Repro (1):
- click on a chat in the overview
- the chat is shown in Fullscreen
- (try to) leave the chat using the back button in the upper left corner, doesn't work on 1st try
- click a 2nd time to actually leave the chat

Repro (2):
- leave an open chat
- (try to) enter the same chat again, doesn't work
- open and leave another one first
- enter the previous chat without any problems

**Comment by marcel93b** [comment]
please connect this issue to issue #100 (Design inconsistency in x86) since they are connected: 
This issue only occurs in Fullscreen chat view, which only shows when Unigram was minimized prior to opening a chat window (see edit in #100 )

**Comment by FrayxRulez** [comment]
I think this issues were solved in the last week, and I'm closing this issue. Feel free to reopen it if in the next build (0.1.146+) the problem persists
