### ISSUE TITLE
unhandled exception on startup

### ISSUE THREAD

**Issue by raminmjj** [UnigramDev/Unigram#990]
the application worked, but after reopening this message appears.
I installed application several times but this issue wasn't solved.
![whatsapp image 2019-02-18 at 22 37 52](https://user-images.githubusercontent.com/991847/52972774-239a3180-33d1-11e9-9c53-303cb68206fd.jpeg)

**Comment by MarcAnt01** [comment]
Latest build has this problem on mobile devices, downgrade the app as a temporary workaround

**Comment by MarcAnt01** [comment]
Fixed build has been pushed to the Store

**Comment by raminmjj** [comment]
after updating from the store. the problem was solved. you can close this issue.
thank you.
