### ISSUE TITLE
Media continues to play after using the Esc key to go back

### ISSUE THREAD

**Issue by CallenMagnuson** [UnigramDev/Unigram#993]
When opening a video and hitting the Esc. key to go back to the chat, the audio will continue to play. When using the back button in the upper left corner, audio stops as expected.

Using Unigram 2.5.2083 on Windows 10 1809

**Comment by FrayxRulez** [comment]
Fixed in https://github.com/UnigramDev/Unigram/commit/e35e4cac2239d40f1a22c276c3d08b8ddeb3bb4f
