### ISSUE TITLE
Cannot go back in some conditions

### ISSUE THREAD

**Issue by MarcAnt01** [UnigramDev/Unigram#994]
How to reproduce: search for something in chats search and click on empty space (right or left part is the same). Now you cannot go back unless with the X.

**Comment by FrayxRulez** [comment]
Does this still happen?

**Comment by MarcAnt01** [comment]
Yes, it seems related to missing focus or kinda

**Comment by FrayxRulez** [comment]
Then I don't understand what this issue is about

**Comment by MarcAnt01** [comment]
That I cannot go back after clicking on an element of the app

**Comment by FrayxRulez** [comment]
Can you make a list of steps as you would explain this to someone that never used the app?

**Comment by MarcAnt01** [comment]
Repro steps:
1. Press Ctrl + E
2. Search something that will bring you to few results for example fffffff
3. Click in any part of the app except that
![image](https://user-images.githubusercontent.com/43090263/56867080-6c79f200-69e1-11e9-9745-1d0f3c5de44a.png)
4. Press Esc
