### ISSUE TITLE
When displaying photo in full window, click should return to the chat, like in TDesktop

### ISSUE THREAD

**Issue by wojpawlik** [UnigramDev/Unigram#995]

**Comment by MarcAnt01** [comment]
Since click is used to show/hide caption, it would be useful to have this action in blank area near the photo, where that doesn't happen

**Comment by MarcAnt01** [comment]
Done in https://github.com/UnigramDev/Unigram/commit/d0000b383f4870dd7ede6c07d74300209815a1ef
